#!/usr/bin/env python3
"""Add verified writing-market batch 7 (2026-09-30).

Ten NEW markets, read from the batch-4 backlog. No crawling. The extraction step
now checks the database first, so nothing here was wasted on a market that
already exists - batches 5 and 6 each lost one that way.

Every figure was read off the publication's own guidelines page on 2026-09-30.
Raw page text is retained under research/batch4/<slug>.txt.

Five of these ten publish a firm rate. Two pay in copies rather than money and
say so. Three publish no rate at all. None has been given a figure its
publication did not publish.

Two base countries are verifiable: Inscape is at inscape.byu.edu and Blue Mesa
Review at bmr.unm.edu, both US .edu domains. The rest record "International"
rather than a guess.
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OPPS = ROOT / "content/opportunities.json"
PUBC = ROOT / "content/hub/pub-countries.json"
V = "2026-09-30"


def rec(slug, publication, title, seo, excerpt, official, apply_url, apply_email,
        apply_method, sources, elig, types, type_label, pay, wc, response,
        status, deadline, ai, want, dont, reqs, rights, how, keywords):
    return {
        "status": "published", "vertical": "writing",
        "lastVerified": V, "publishedAt": V,
        "experience": "not-stated",
        "editorExperience": {"status": "not-yet-submitted"},
        "id": slug, "slug": slug, "publication": publication,
        "title": title, "seoTitle": seo, "excerpt": excerpt,
        "officialUrl": official, "applyUrl": apply_url, "applyEmail": apply_email,
        "applyMethod": apply_method, "sources": sources,
        "eligibility": elig, "writingTypes": types, "writingTypeLabel": type_label,
        "pay": pay, "wordCount": wc, "response": response,
        "submissionStatus": status, "deadline": deadline, "aiPolicy": ai,
        "whatTheyWant": want, "whatTheyDontWant": dont, "requirements": reqs,
        "rights": rights, "howToSubmit": how, "keywords": keywords,
    }


def src(name, url):
    return [{"name": name, "url": url}]


def pay(cur, lo, hi, display, conditions, timing):
    return {"currency": cur, "amountMin": lo, "amountMax": hi,
            "display": display, "conditions": conditions, "timing": timing}


def intl(summary="No stated country restriction on the guidelines page."):
    return {"summary": summary, "mode": "not-stated", "includesRegions": [],
            "allowsDiaspora": True, "notStated": True}


NEW = []

# ------------------------------------------- 1 Blue Mesa Review
NEW.append(rec(
    "blue-mesa-review", "Blue Mesa Review",
    "Poetry, fiction, nonfiction and visual art",
    "Blue Mesa Review: $25 per piece, 6,000-word cap, no AI",
    "Blue Mesa Review pays $25 per poem, essay, short story or artwork published "
    "during its general reading period. Fiction and nonfiction run to 6,000 "
    "words and poetry packets hold no more than three poems. It does not accept "
    "writing or art generated by or with the use of AI, rights revert to the "
    "author upon publication, and it waives the submission fee for incarcerated "
    "authors and artists.",
    "https://bmr.unm.edu/submissions/",
    "https://bmr.unm.edu/submissions/", None,
    "Submittable — fee waived for incarcerated authors",
    src("Blue Mesa Review — Submissions (official)", "https://bmr.unm.edu/submissions/"),
    {"summary": "Open internationally. Blue Mesa Review states it gladly accepts submissions "
                "from incarcerated authors and artists and waives the submission fee for them.",
     "mode": "worldwide", "includesRegions": [], "allowsDiaspora": True, "notStated": False},
    ["poetry", "fiction", "creative-nonfiction"],
    "Poetry, fiction, nonfiction and visual art",
    pay("USD", 25, 25, "$25 per poem, essay, short story or artwork published",
        "Official submissions page: Blue Mesa Review pays $25 per poem, essay, short story or "
        "artwork published in the magazine during its general reading period. A flat rate "
        "regardless of category or length.",
        "Not publicly stated"),
    {"min": None, "max": 6000,
     "display": "Fiction and nonfiction no more than 6,000 words; poetry no more than three "
                "poems per packet"},
    {"label": "Standard two to six months, sometimes longer given volume",
     "band": "3-plus-months", "official": True},
    "open", None, "prohibited",
    ["Fiction of no more than 6,000 words.",
     "Nonfiction of no more than 6,000 words.",
     "Poetry: no more than three poems per packet.",
     "Visual art."],
    ["Writing or art generated by or with the use of AI."],
    ["Submit online via Submittable only.",
     "Keep prose to 6,000 words and poetry to three poems per packet.",
     "Incarcerated authors and artists: the submission fee is waived for you, and submissions "
     "are welcomed.",
     "Expect two to six months, and longer during heavy periods."],
    "Rights revert to the author upon publication.",
    ["Read https://bmr.unm.edu/submissions/ before sending.",
     "A flat $25 regardless of category, so length does not change the payment.",
     "Submittable is the only route."],
    ["blue mesa review", "university of new mexico", "poetry", "fiction", "nonfiction",
     "visual art", "$25", "6000 words", "incarcerated writers", "no ai"]))

# ------------------------------------------- 2 Inscape Journal
NEW.append(rec(
    "inscape-journal", "Inscape Journal",
    "Fiction, creative nonfiction, poetry and visual art",
    "Inscape Journal: $20 per piece, no AI in or out",
    "Inscape Journal awards $20 for each piece accepted into its general issues. "
    "Fiction and creative nonfiction run to one piece under 4,000 words, or up "
    "to four flash pieces under 1,000 words each. It does not accept work "
    "created by artificial intelligence, and states it will not use AI to review "
    "your writing in any way. All rights revert to the author upon publication.",
    "https://inscape.byu.edu/submit/",
    "https://inscape.byu.edu/submit/", None, "Online portal only",
    src("Inscape Journal — Submit (official)", "https://inscape.byu.edu/submit/"),
    intl(),
    ["fiction", "creative-nonfiction", "poetry"],
    "Fiction, creative nonfiction, poetry and visual art",
    pay("USD", 20, 20, "$20 for each piece accepted into a general issue",
        "Official submit page: all accepted general issue submissions are awarded $20 for each "
        "piece. Student selection pieces remain unpaid, because BYU students submit their work "
        "for free. The $20 applies to the general issue, not the student selection.",
        "Not publicly stated"),
    {"min": None, "max": 4000,
     "display": "One piece under 4,000 words, or up to four flash pieces under 1,000 words each"},
    {"label": "Not stated; reading periods apply", "band": "not-stated", "official": False},
    "open",
    {"date": None,
     "display": "Submissions follow reading periods. One submission per genre per reading "
                "period is allowed — for example one poetry and one fiction submission — but "
                "each genre must be uploaded individually.",
     "recurring": True},
    "prohibited",
    ["Fiction: one piece under 4,000 words, or up to four flash pieces under 1,000 words each.",
     "Creative nonfiction on the same terms.",
     "Poetry and visual art from emerging and established creators alike."],
    ["Pieces created by Artificial Intelligence. Inscape states it appreciates original, human "
     "work.",
     "Your name, email or mailing address inside any attachment — the journal reads blind."],
    ["Submit through the online portal only.",
     "Keep prose under 4,000 words, or send up to four flash pieces under 1,000 words each.",
     "Upload each genre separately; one submission per genre per reading period.",
     "Remove your name, email and mailing address from all attachments."],
    "Inscape acquires first serial rights and archival rights; all rights revert back to the "
    "author upon publication.",
    ["Read https://inscape.byu.edu/submit/ before sending.",
     "Strip identifying details from the files — it reads blind.",
     "One genre at a time, uploaded separately."],
    ["inscape journal", "byu", "fiction", "creative nonfiction", "poetry", "$20",
     "4000 words", "flash", "blind reading", "no ai"]))

# ------------------------------------------- 3 Points in Case
NEW.append(rec(
    "points-in-case", "Points in Case", "Humour articles and lists",
    "Points in Case: $35 an article, $10 a list, paid in five days",
    "Points in Case pays $35 for accepted articles of a preferred 600 to 1,000 "
    "words and $10 for accepted lists of 200 to 600 words, typically within five "
    "days of acceptance. It replies to every submission, with an average "
    "response time of two weeks, and does not accept AI-assisted writing. "
    "Article and list submissions through Submittable are always free.",
    "https://www.pointsincase.com/submissions",
    "https://www.pointsincase.com/submissions", None,
    "Submittable — rolling, always free",
    src("Points in Case — Submissions (official)",
        "https://www.pointsincase.com/submissions"),
    intl(),
    ["humour", "essays", "articles"], "Humour articles and lists",
    pay("USD", 10, 35, "$35 per accepted article; $10 per accepted list",
        "Official submissions page: Points in Case pays $35 for accepted articles and $10 for "
        "accepted lists, typically within five days of acceptance. It prefers 600 to 1,000 words "
        "for articles and 200 to 600 words for lists. Optional paid add-ons are available for "
        "an expedited decision, a decision breakdown and editorial notes.",
        "Typically within five days of acceptance"),
    {"min": 200, "max": 1000,
     "display": "Articles 600–1,000 words preferred; lists 200–600 words preferred"},
    {"label": "Average two weeks; replies to every submission", "band": "under-2-weeks",
     "official": True},
    "open", None, "prohibited",
    ["Articles, preferably 600 to 1,000 words.",
     "Lists, preferably 200 to 600 words."],
    ["AI-assisted writing. Points in Case asks that generative AI not be used to draft or revise "
     "a submission."],
    ["Submit articles and lists through Submittable, on a rolling basis, always free.",
     "Keep articles to 600–1,000 words and lists to 200–600 words.",
     "Expect a reply in about two weeks — every submission is answered.",
     "Paid add-ons exist for a faster decision or editorial notes if you want them."],
    "Not stated on the official submissions page.",
    ["Read https://www.pointsincase.com/submissions before sending.",
     "Rolling and free, with a two-week average — one of the faster markets here.",
     "Payment lands within about five days of acceptance."],
    ["points in case", "humour", "comedy", "articles", "lists", "$35", "$10",
     "two week response", "no ai"]))

# ------------------------------------------- 4 Vestal Review
NEW.append(rec(
    "vestal-review", "Vestal Review", "Flash fiction",
    "Vestal Review: $75 via PayPal, flash fiction only",
    "Vestal Review is a magazine for flash fiction and pays contributors $75, "
    "sent via PayPal, against a $3 reading fee for general submissions — "
    "proposals carry no fee. It assumes writing has not been produced, shaped or "
    "edited by AI, asks for first electronic rights, and reverts all rights to "
    "the writer afterwards.",
    "https://www.vestalreview.net/guidelines",
    "https://www.vestalreview.net/guidelines", None,
    "Online submission — $3 reading fee, none for proposals",
    src("Vestal Review — Guidelines (official)", "https://www.vestalreview.net/guidelines"),
    intl(),
    ["fiction"], "Flash fiction",
    pay("USD", 75, 75, "$75 per contributor, sent via PayPal",
        "Official guidelines: contributors receive $75, sent via PayPal. A $3 reading fee "
        "applies to general submissions and goes toward production of the journal, technology "
        "fees and payment for the authors. No reading fee is charged for proposals.",
        "Not publicly stated"),
    {"min": None, "max": None,
     "display": "Flash fiction — the magazine's whole remit; no word limit stated on the "
                "guidelines page"},
    {"label": "Not stated; wait for a reply before submitting again", "band": "not-stated",
     "official": True},
    "open",
    {"date": None,
     "display": "Submissions are taken during Vestal Review's reading periods. You may submit "
                "as often as you like during them, but only one piece per submission, and only "
                "after hearing back about the previous one.",
     "recurring": True},
    "prohibited",
    ["Flash fiction. That is the magazine's entire remit.",
     "Proposals, which carry no reading fee."],
    ["Writing produced, shaped or edited by AI. The guidelines state the magazine assumes your "
     "writing has not been.",
     "More than one piece per submission, or a second submission before the first is answered."],
    ["Pay the $3 reading fee for general submissions; proposals are free.",
     "Send one piece per submission.",
     "Wait until you hear back before submitting again.",
     "Have a PayPal account — that is how the $75 is sent."],
    "Vestal Review asks for first electronic rights. After that period all rights revert to the "
    "writer, with the request that you acknowledge Vestal Review in any subsequent printing, "
    "whether on the web or in hard copy.",
    ["Read https://www.vestalreview.net/guidelines before sending.",
     "Write flash — nothing longer belongs here.",
     "One piece at a time, and wait for the answer."],
    ["vestal review", "flash fiction", "$75", "paypal", "$3 reading fee", "first electronic rights",
     "no ai"]))

# ------------------------------------------- 5 The Aurora Journal
NEW.append(rec(
    "the-aurora-journal", "The Aurora Journal", "Prose and poetry",
    "The Aurora Journal: $12 a piece, decision in 1–3 weeks",
    "The Aurora Journal pays $12 per piece and takes up to two prose pieces at a "
    "time of a maximum 1,000 words each. It emails a decision within one to "
    "three weeks and offers paid speed at $3 for a 24-hour response, $8 for "
    "detailed feedback within a week, or $14 for both. It asks for First North "
    "American Serial Rights while the writer retains all legal rights.",
    "https://www.theaurorajournal.org/submit",
    "https://www.theaurorajournal.org/submit", None,
    "Email — with paid expedited options",
    src("The Aurora Journal — Submit (official)", "https://www.theaurorajournal.org/submit"),
    intl(),
    ["fiction", "poetry", "creative-nonfiction"], "Prose and poetry",
    pay("USD", 12, 12, "$12 per piece",
        "Official submit page: The Aurora Journal states its payment philosophy and that it pays "
        "$12 per piece. Separately it offers paid response options: $3 per piece for a 24-hour "
        "response, $8 per piece for two full paragraphs of detailed, actionable feedback within "
        "one week, and $14 per piece for both. Those are service fees, not payment.",
        "Not publicly stated"),
    {"min": None, "max": 1000, "display": "Prose: up to 2 pieces at a time, 1,000 words maximum"},
    {"label": "Decision emailed within 1–3 weeks", "band": "2-4-weeks", "official": True},
    "open", None, "not-stated",
    ["Prose: up to two pieces at a time, 1,000 words maximum each.",
     "Poetry, for which the $8 feedback tier gives two full paragraphs of detailed, actionable "
     "notes."],
    ["Prose over 1,000 words, or more than two pieces at a time."],
    ["Submit by email to the address on the submit page.",
     "Keep prose to 1,000 words and send at most two pieces.",
     "Take the $3 tier for a 24-hour response, $8 for detailed feedback within a week, or $14 "
     "for both.",
     "If the work is accepted elsewhere, email to withdraw."],
    "The Aurora Journal asks for First North American Serial Rights. The writer retains all "
    "legal rights to their work, with a request to credit The Aurora Journal as where the work "
    "was featured.",
    ["Read https://www.theaurorajournal.org/submit before sending.",
     "The paid tiers buy speed and feedback, not a better decision.",
     "Email the journal to withdraw if you place elsewhere."],
    ["the aurora journal", "prose", "poetry", "$12", "1000 words", "1-3 weeks",
     "expedited response", "fnasr"]))

# ------------------------------------------- 6 Raleigh Review
NEW.append(rec(
    "raleigh-review", "Raleigh Review", "Poetry, flash fiction and short fiction",
    "Raleigh Review: $15 per work used, 1–3 month response",
    "Raleigh Review offers optional payment of $15 per work used plus one copy "
    "of the magazine, and pays in extra copies for contributors without a bank "
    "account or PayPal. It takes fiction up to 1,000 words and from 1,001 to "
    "7,500 words, aims for First North American Rights with all rights reverting "
    "on publication, and typically responds in one to three months.",
    "https://raleighreview.org/submit",
    "https://raleighreview.org/submit", None,
    "Submittable (poetry currently open) — DuoSuma closed",
    src("Raleigh Review — Submit (official)", "https://raleighreview.org/submit"),
    intl(),
    ["poetry", "fiction"], "Poetry, flash fiction and short fiction",
    pay("USD", 15, 15, "$15 per work used, plus one copy of the magazine",
        "Official submit page: optional payment is currently $15 per work used and one copy of "
        "the magazine. For those without a bank account or PayPal, payment is made in extra "
        "copies of the issue. The word \"optional\" is the magazine's own, so treat the $15 as "
        "the current rate rather than a guarantee.",
        "Not publicly stated"),
    {"min": None, "max": 7500,
     "display": "Fiction up to 1,000 words, and fiction from 1,001 to 7,500 words"},
    {"label": "Typically 1–3 months, occasionally 3–6", "band": "1-3-months", "official": True},
    "open",
    {"date": None,
     "display": "General submissions for poetry, flash fiction and short fiction open 1 January "
                "to 31 March. As of 30 September 2026 Submittable is open for poetry "
                "submissions and DuoSuma is closed while the editors catch up on reading.",
     "recurring": True},
    "prohibited",
    ["Fiction up to 1,000 words.",
     "Fiction from 1,001 to 7,500 words.",
     "Poetry, including for the Raleigh Review Poetry Book Prize."],
    ["Artificial intelligence, plagiarism, abridging, or renaming a piece that was published "
     "elsewhere. The magazine says plainly not to try it."],
    ["Check which portal is open — Submittable for poetry, DuoSuma currently closed.",
     "General submissions for poetry, flash and short fiction run 1 January to 31 March.",
     "Expect one to three months, occasionally up to six.",
     "If you have no bank account or PayPal, say so — payment comes in extra copies."],
    "Raleigh Review aims for First North American Rights on everything it publishes. Fiction, "
    "poetry and contest work are all First North American Rights opportunities, and all rights "
    "revert back to the author on publication.",
    ["Read https://raleighreview.org/submit and check which portal is open before sending.",
     "Poetry is open now on Submittable; DuoSuma is closed.",
     "The extra-copies option is a real alternative if you cannot take a transfer."],
    ["raleigh review", "poetry", "flash fiction", "short fiction", "$15", "7500 words",
     "fnar", "rights revert", "no ai"]))

# ------------------------------------------- 7 Gulf Stream Magazine
NEW.append(rec(
    "gulf-stream-magazine", "Gulf Stream Magazine",
    "Fiction, poetry, creative nonfiction, hybrid work, translation and reviews",
    "Gulf Stream Magazine: 5,000 words, $3 per submission",
    "Gulf Stream Magazine publishes fiction, poetry, creative nonfiction, hybrid "
    "works, translations, book reviews and visual art, with fiction and creative "
    "nonfiction at 5,000 words and book reviews at 500 to 750 words. Work must "
    "be original, created without AI, and previously unpublished apart from "
    "translations. It holds first serial rights with copyright reverting on "
    "publication.",
    "https://gulfstreamlitmag.com/submissions/",
    "https://gulfstreamlitmag.com/submissions/", None,
    "Submittable — $3 per submission",
    src("Gulf Stream Magazine — Submissions (official)",
        "https://gulfstreamlitmag.com/submissions/"),
    intl(),
    ["fiction", "poetry", "creative-nonfiction", "translation", "reviews"],
    "Fiction, poetry, creative nonfiction, hybrid work, translation and reviews",
    pay(None, None, None, "Not stated on the public submissions page; $3 per submission",
        "The public submissions page sets length limits, the originality and AI requirements and "
        "the rights position, and charges $3 per submission, but publishes no payment rate, so "
        "BRYME records no figure.",
        "Not publicly stated"),
    {"min": 500, "max": 5000,
     "display": "Fiction and creative nonfiction 5,000 words (or 3 pieces of up to 1,000 words); "
                "book reviews 500–750 words"},
    {"label": "Best efforts within six months, sometimes longer", "band": "3-plus-months",
     "official": True},
    "open", None, "prohibited",
    ["Fiction of 5,000 words, or three pieces of up to 1,000 words each.",
     "Creative nonfiction of 5,000 words.",
     "Book reviews of 500 to 750 words, of books published within the past year.",
     "Poetry, hybrid works, translations and visual art."],
    ["Work created with the use of AI. It must be original.",
     "Previously published work, with the exception of translations.",
     "Reviews of books published more than a year ago.",
     "Submissions by email or mail, unless the editors have invited you.",
     "More than one submission per genre at a time."],
    ["Submit through Submittable at $3 per submission.",
     "Multiple submissions are welcome, but no more than one per genre at a time.",
     "Keep prose to 5,000 words and reviews to 500–750 words of a book from the past year.",
     "Do not email or mail unless invited."],
    "Gulf Stream Magazine holds first serial rights for the material it publishes, with the "
    "copyright reverting back to the author upon publication.",
    ["Read https://gulfstreamlitmag.com/submissions/ before sending.",
     "One genre at a time.",
     "Reviews must be of recent books — within the past year."],
    ["gulf stream magazine", "fiction", "poetry", "creative nonfiction", "translation",
     "book reviews", "5000 words", "$3", "no ai"]))

# ------------------------------------------- 8 Shō Poetry Journal
NEW.append(rec(
    "sho-poetry-journal", "Shō Poetry Journal", "Poetry and visual art",
    "Shō Poetry Journal: paid in copies, 30-day response",
    "Shō Poetry Journal pays one contributor's copy and charges a $3 reading fee "
    "that funds print issues for all contributors, including international ones. "
    "It offers a 30-day response time on every Submittable submission, does not "
    "accept AI-generated work or art, and reverts rights to the author upon "
    "publication.",
    "https://shopoetryjournal.com/submissions/",
    "https://shopoetryjournal.com/submissions/", None,
    "Submittable only — $3 reading fee",
    src("Shō Poetry Journal — Submissions (official)",
        "https://shopoetryjournal.com/submissions/"),
    intl(),
    ["poetry"], "Poetry and visual art",
    pay(None, None, None, "Payment is one contributor's copy; $3 reading fee",
        "Official submissions page: payment is one contributor's copy. A $3 reading fee helps "
        "produce and distribute print issues to all contributors, including international "
        "contributors and cover artists, and makes the 30-day response time feasible. BRYME "
        "records no monetary figure because the consideration is a copy, not cash.",
        "Not applicable — paid in copies"),
    {"min": None, "max": None, "display": "No word or poem limit stated on the submissions page"},
    {"label": "30 days on every Submittable submission", "band": "1-3-months", "official": True},
    "open", None, "prohibited",
    ["Poetry.",
     "Visual art that has not been created or manipulated using AI."],
    ["AI-generated work. Art must not have been created or manipulated using AI.",
     "Submissions sent by contact form, email or social media — they are discarded."],
    ["Submit via Submittable and pay the $3 reading fee.",
     "Do not send work by contact form, email or social media.",
     "Expect a response within 30 days.",
     "Credit Shō Poetry Journal with first publication if the work is republished elsewhere."],
    "Shō Poetry Journal requests first serial rights, plus the right to republish accepted works "
    "on its website, use excerpts in its social media feeds, and submit work to venues such as "
    "Poetry Daily. Rights revert to the author upon publication, with a request to credit the "
    "journal with first publication.",
    ["Read https://shopoetryjournal.com/submissions/ before sending.",
     "Paid in copies, not cash — the $3 fee is what makes the print run and the 30-day "
     "turnaround possible.",
     "Submittable is the only route that will be read."],
    ["sho poetry journal", "poetry", "visual art", "contributor copy", "$3 reading fee",
     "30 day response", "submittable", "no ai"]))

# ------------------------------------------- 9 The New Verse News
NEW.append(rec(
    "the-new-verse-news", "The New Verse News", "Poetry",
    "New Verse News: 1–3 poems by email, fortnight response",
    "The New Verse News takes one to three unpublished poems pasted into the body "
    "of an email — no attachments — and its editors try to respond within a "
    "fortnight. Authors retain all rights after first appearance. It rejects "
    "AI-created or AI-enhanced poetry while noting that its own site graphics "
    "are AI-generated.",
    "https://newversenews.blogspot.com/",
    "https://newversenews.blogspot.com/", "nvneditor@gmail.com",
    "Email, poems in the body — no attachments",
    src("The New Verse News — Submission Guidelines (official)",
        "https://newversenews.blogspot.com/"),
    intl(),
    ["poetry"], "Poetry",
    pay(None, None, None, "Not stated on the public guidelines page",
        "The public guidelines set out the submission route, the rights position and the "
        "response time but publish no payment rate, so BRYME records no figure.",
        "Not publicly stated"),
    {"min": None, "max": None, "display": "One to three unpublished poems per email"},
    {"label": "Editors try to respond within a fortnight", "band": "2-4-weeks", "official": True},
    "open", None, "prohibited",
    ["One to three unpublished poems."],
    ["AI-created or AI-enhanced poetry. The editors reject it, while noting separately that the "
     "site's own graphics are generated using AI applications at Shutterstock and NightCafé.",
     "Attachments. Poems go in the body of the email.",
     "Emails that do not follow the guidelines printed at the top of the page — they are "
     "deleted."],
    ["Send one to three unpublished poems in the body of an email to nvneditor@gmail.com.",
     "No attachments.",
     "Follow the guidelines exactly — non-conforming emails are deleted.",
     "Expect a reply within about a fortnight."],
    "Authors retain all rights after first appearance in The New Verse News.",
    ["Read the guidelines at the top of https://newversenews.blogspot.com/ before sending.",
     "Paste into the email body; do not attach.",
     "Rights stay with you after first publication."],
    ["new verse news", "poetry", "1-3 poems", "email submission", "fortnight response",
     "rights retained", "no ai"]))

# ------------------------------------------- 10 Home Planet News
NEW.append(rec(
    "home-planet-news", "Home Planet News",
    "Poetry, prose, music and visual art",
    "Home Planet News: unpaid, no fees, up to 6 poems",
    "Home Planet News has no submission fees, no ads and no paywalls, and says "
    "plainly that while it cannot pay contributors in gratuities it is generous "
    "with its gratitude. It takes up to six poems in a single file, asks for a "
    "third-person bio under 100 words, and accepts previously published work "
    "where the writer holds the copyright.",
    "https://homeplanetnews.com/issue-21-submissions/",
    "https://homeplanetnews.com/issue-21-submissions/", None,
    "Online submission — no fees",
    src("Home Planet News — Submissions (official)",
        "https://homeplanetnews.com/issue-21-submissions/"),
    intl(),
    ["poetry", "fiction", "creative-nonfiction"],
    "Poetry, prose, music and visual art",
    pay(None, None, None, "Unpaid — no submission fees, no ads, no paywalls",
        "Official submissions page: Home Planet News states it has no submission fees, no ads "
        "and no paywalls, and that while it cannot pay contributors in gratuities it is generous "
        "with its gratitude. BRYME records no figure because there is none. Nothing to pay and "
        "nothing to earn.",
        "Not applicable — unpaid"),
    {"min": None, "max": None, "display": "Poetry: up to 6 poems in a single file"},
    {"label": "Not stated", "band": "not-stated", "official": False},
    "open", None, "not-stated",
    ["Poetry: up to six poems in a single file.",
     "Visual art — photography, painting, drawings and digital art — as low- or high-resolution "
     "JPEG attachments.",
     "Poems set to music, provided it is your poem or a poem in the public domain, and you own "
     "the copyright on the music, lyrics and recordings.",
     "A brief third-person bio note under 100 words."],
    ["Work you do not hold the copyright to. Previously published work is acceptable only if you "
     "still hold the rights."],
    ["Send up to six poems in a single file.",
     "Include a third-person bio under 100 words.",
     "Send art as JPEG attachments, low or high resolution.",
     "Confirm you own the rights to anything previously published or set to music."],
    "Previously published work is acceptable if the writer holds the copyright. No specific "
    "rights transfer is stated on the submissions page.",
    ["Read https://homeplanetnews.com/issue-21-submissions/ before sending.",
     "Free to enter and unpaid — the credit is the whole return.",
     "Rights ownership is the only hard requirement."],
    ["home planet news", "poetry", "prose", "visual art", "music", "unpaid", "no fees",
     "6 poems", "copyright"]))


BASE = {
    "blue-mesa-review": ("US", "United States"),
    "inscape-journal": ("US", "United States"),
    "points-in-case": ("", "International"),
    "vestal-review": ("", "International"),
    "the-aurora-journal": ("", "International"),
    "raleigh-review": ("", "International"),
    "gulf-stream-magazine": ("", "International"),
    "sho-poetry-journal": ("", "International"),
    "the-new-verse-news": ("", "International"),
    "home-planet-news": ("", "International"),
}


def main():
    data = json.loads(OPPS.read_text(encoding="utf-8"))
    opps = data["opportunities"]
    existing = {o["slug"] for o in opps}
    dupes = [r["slug"] for r in NEW if r["slug"] in existing]
    if dupes:
        sys.exit(f"ERROR: slug collision: {dupes}")
    seen = set()
    for r in NEW:
        if r["slug"] in seen:
            sys.exit(f"ERROR: duplicate slug inside batch: {r['slug']}")
        seen.add(r["slug"])
        p = r["pay"]
        if p["amountMin"] == 0 or p["amountMax"] == 0:
            sys.exit(f"ERROR: {r['slug']} has a zero pay amount")
        if p["amountMin"] is not None and p["amountMax"] is not None \
                and p["amountMin"] > p["amountMax"]:
            sys.exit(f"ERROR: {r['slug']} pay range inverted")
        for k in ("officialUrl", "excerpt", "seoTitle", "howToSubmit", "whatTheyWant"):
            if not r.get(k):
                sys.exit(f"ERROR: {r['slug']} missing {k}")

    opps.extend(NEW)
    data["opportunities"] = opps
    data["updatedAt"] = V
    OPPS.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    if PUBC.exists():
        pc = json.loads(PUBC.read_text(encoding="utf-8"))
        for r in NEW:
            base, label = BASE[r["slug"]]
            pc[r["slug"]] = {"base": base, "label": label}
        PUBC.write_text(json.dumps(pc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"Added {len(NEW)} verified records. Total opportunities: {len(opps)}")


# ---------------------------------------------------------------------------
# The extraction step for this batch checked the database first, so nothing
# read here was wasted on a market that already exists. That is a change from
# batches 5 and 6, which each lost one.
#
# 405 usable guidelines pages remain unread. No further crawling required.
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    main()
