#!/usr/bin/env python3
"""Append official-only worldwide writing listings. 19 August 2026."""
import json
from pathlib import Path

ROOT = Path("/home/user/nextclip")
path = ROOT / "content" / "opportunities.json"
data = json.loads(path.read_text())
existing = {o["id"] for o in data["opportunities"]}

def base(**kw):
    o = {
        "status": "published",
        "vertical": "writing",
        "lastVerified": "2026-08-19",
        "publishedAt": "2026-08-19",
        "experience": "not-stated",
        "editorExperience": {"status": "not-yet-submitted"},
    }
    o.update(kw)
    return o

NEW = [
    base(
        id="new-lines",
        slug="new-lines",
        publication="New Lines Magazine",
        title="Essays, reportage, first person, reviews",
        seoTitle="New Lines Magazine pitches: worldwide, pay not stated",
        excerpt="New Lines considers essays and reportage from anywhere in the world. Official pitch page: email submissions@newlinesmag.com. A dollar fee is not on that page. Do not treat third-party $800 claims as verified. AI-assisted work is banned.",
        officialUrl="https://newlinesmag.com/pitch/",
        applyUrl="mailto:submissions@newlinesmag.com",
        applyEmail="submissions@newlinesmag.com",
        applyMethod="Email pitch (under 300 words) or on-spec Word draft",
        sources=[{"name": "New Lines — Submissions (official)", "url": "https://newlinesmag.com/pitch/"}],
        eligibility={
            "summary": "Official page: submissions on virtually any topic from anywhere in the world if the story is compelling, well written and accurate. Beat focus is the Middle East, Africa and South Asia, plus the US, Europe, Latin America, Russia and Central Asia. That is a beat, not a passport list.",
            "mode": "open",
            "notStated": False,
        },
        writingTypes=["essays", "journalism", "personal-essays", "reviews", "analysis"],
        writingTypeLabel="Reportage, arguments, history essays, first person, reviews",
        pay={
            "currency": None,
            "amountMin": None,
            "amountMax": None,
            "display": "Not publicly stated on the official pitch page",
            "conditions": "The official Submissions page does not publish a fee. Third-party lists have quoted $800. That figure is not copied here.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": None, "display": "Pitch under 300 words. Finished length is part of the pitch, not a published limit."},
        response={"label": "Not publicly stated", "band": "not-stated", "official": False},
        submissionStatus="open",
        deadline=None,
        aiPolicy="prohibited",
        whatTheyWant=[
            "Five official sections: Reportage; Arguments (not op-eds); Anchored in History; First Person; Review.",
            "A cold pitch under 300 words: envisioned lead, one or two short paragraphs, brief lit review, bio/access, proposed length and file date.",
            "On spec: say so in the subject line, attach a Word document, and still include a proper pitch.",
            "AP style. They generally do not use hyperlinks and never use footnotes.",
        ],
        whatTheyDontWant=[
            "Op-eds. Academic abstracts. Jargon.",
            "Anything translated, written, developed or assisted by AI. Official: that can end the working relationship.",
            "A made-up dollar fee.",
        ],
        requirements=["Email submissions@newlinesmag.com", "Pitch a story, not a topic", "No AI"],
        rights="Not publicly stated on the official pitch page.",
        howToSubmit=["Read https://newlinesmag.com/pitch/.", "Email submissions@newlinesmag.com."],
        keywords=["new lines", "middle east", "africa", "south asia", "reportage", "first person"],
    ),
    base(
        id="himal-southasian",
        slug="himal-southasian",
        publication="Himal Southasian",
        title="Long-form journalism, essays and analysis on Southasia",
        seoTitle="Himal Southasian pitches: paid, rate told on commission",
        excerpt="Himal Southasian is open to pitches from writers across Southasia and the world. Official: they have set rates, and the standard rate is told as part of a commission. A public dollar figure is not on the current guidelines. AI-generated content is treated as plagiarism.",
        officialUrl="https://www.himalmag.com/submission-guidelines/",
        applyUrl="mailto:editorial@himalmag.com",
        applyEmail="editorial@himalmag.com",
        applyMethod="Email a 300–600 word pitch",
        sources=[{"name": "Himal Southasian — Submission guidelines (official)", "url": "https://www.himalmag.com/submission-guidelines/"}],
        eligibility={
            "summary": "Official: journalists, scholars, writers and other thinkers from all over Southasia and the world. Subject must relate to Southasia. That is a beat, not a closed country list.",
            "mode": "open",
            "notStated": False,
        },
        writingTypes=["journalism", "essays", "opinion", "analysis", "interviews", "reviews", "fiction"],
        writingTypeLabel="Long-form reportage, analysis, essays, interviews, reviews, occasional fiction",
        pay={
            "currency": None,
            "amountMin": None,
            "amountMax": None,
            "display": "Set rates — amount told on commission",
            "conditions": "Official: Himal has set rates of remuneration; the final sum is based on length and nature. The standard rate is communicated as part of any commission or offer of publication. Older third-party pages quoted $100–$150. That figure is not on the current official guidelines and is not copied here.",
            "timing": "Processed on a calendar-month cycle after publication. Official: banking procedures can delay payment by up to two months.",
        },
        wordCount={"min": 1200, "max": 4000, "display": "Rarely under 1,200; most pieces about 2,000–4,000 words"},
        response={"label": "If no reply in two weeks, assume they will not take it", "band": "under-2-weeks", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="prohibited",
        whatTheyWant=[
            "Regional or cross-border Southasia stories, or very local stories told with a regional perspective.",
            "A 300–600 word pitch: argument or narrative plus a tentative outline. Up to three previous-work links.",
            "Completed articles may be attached. Drafts as Word documents, not PDFs or Google Doc links.",
            "Occasional original short fiction — send a completed draft.",
        ],
        whatTheyDontWant=[
            "News or weekend-supplement features. Academic jargon for specialists.",
            "Previously published work — official: without exception.",
            "AI chatbots, writing tools or auto-generative systems used to produce content or analysis. Official: treated as plagiarism.",
        ],
        requirements=["Email editorial@himalmag.com", "Original unpublished work", "Southasia relevance"],
        rights="Copyright of the published article remains with Himal unless otherwise agreed.",
        howToSubmit=["Read https://www.himalmag.com/submission-guidelines/.", "Email editorial@himalmag.com."],
        keywords=["himal", "southasia", "south asia", "kathmandu", "longform"],
    ),
    base(
        id="climate-home-news",
        slug="climate-home-news",
        publication="Climate Home News",
        title="Climate news, features and investigations",
        seoTitle="Climate Home News freelance: from £0.35 a word",
        excerpt="Climate Home News commissions freelance reporting from around the world. Official: rates start at £0.35 a word (GBP). Pitch under 300 words — not a finished article. Comment pieces on the same page are unpaid. Do not use AI to write pitches or stories.",
        officialUrl="https://www.climatechangenews.com/about/write-for-us/",
        applyUrl="https://www.climatechangenews.com/about/write-for-us/",
        applyEmail=None,
        applyMethod="Email a short pitch to the named news or investigations editor",
        sources=[{"name": "Climate Home News — Write for us (official)", "url": "https://www.climatechangenews.com/about/write-for-us/"}],
        eligibility={
            "summary": "Official: freelance journalists, experts and organisations. They have a modest budget to commission reporting from around the world. No country list.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["journalism", "analysis"],
        writingTypeLabel="Climate news, features, investigations",
        pay={
            "currency": "GBP",
            "amountMin": None,
            "amountMax": None,
            "display": "From £0.35 a word",
            "conditions": "Official for news, features and investigations: rates start at £0.35 a word (GBP). A standard 600-word news story should usually interview and quote three or more sources. Comment pieces on the same page are generally unpaid — that is not this card. Travel expenses only by prior agreement.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": None, "display": "Pitch under 300 words. A standard news story is described as 600 words; longer features exist. No single required range."},
        response={"label": "They cannot guarantee a response", "band": "not-stated", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="prohibited",
        whatTheyWant=[
            "Climate stories with an international outlook: finance, carbon markets, energy transition, critical minerals, human rights, land conflict, loss and damage, greenwash, climate diplomacy.",
            "What is new, why it matters internationally, main actors, sources, your background, where the action is.",
            "News/analysis/features: Megan Rowling (mr at climatehomenews.com). Investigations: Sebastian Rodriguez (sr at climatehomenews.com).",
        ],
        whatTheyDontWant=[
            "A finished article instead of a pitch.",
            "Stories based only on a research paper, a widely distributed report, or a conference panel.",
            "Stories solely about climate impacts or a wind farm unless there is something new.",
            "AI-written pitches. Official: they will not respond to pitches that appear AI-generated.",
            "Comment if you expect pay — official: comment is generally unpaid.",
        ],
        requirements=["Short pitch, not a draft", "Climate + international angle", "No AI pitch"],
        rights="Not publicly stated on the write-for-us page.",
        howToSubmit=["Read https://www.climatechangenews.com/about/write-for-us/.", "Email the named editor. Addresses are written as mr [at] climatehomenews.com on the official page."],
        keywords=["climate home", "climate", "freelance", "gbp", "investigations"],
    ),
    base(
        id="clarkesworld-fiction",
        slug="clarkesworld-fiction",
        publication="Clarkesworld Magazine",
        title="Science fiction and fantasy short stories",
        seoTitle="Clarkesworld fiction: 14¢ a word, open worldwide",
        excerpt="Clarkesworld is open for original science fiction and fantasy of 1,000–22,000 words. Official rate is 14 US cents a word via PayPal, cheque or wire. Stories from all over the world and translations are welcome. AI-assisted work is banned. Simultaneous submissions are not allowed.",
        officialUrl="https://clarkesworldmagazine.com/submissions/",
        applyUrl="https://clarkesworldmagazine.com/submissions_tracker/",
        applyEmail=None,
        applyMethod="Official online submissions tracker — do not email stories",
        sources=[{"name": "Clarkesworld — Submission Guidelines (official)", "url": "https://clarkesworldmagazine.com/submissions/"}],
        eligibility={
            "summary": "Official: stories from all over the world. Translations welcome even if previously published in another language. English-language rights.",
            "mode": "open",
            "notStated": False,
        },
        writingTypes=["fiction"],
        writingTypeLabel="Science fiction or fantasy short story",
        pay={
            "currency": "USD",
            "amountMin": None,
            "amountMax": None,
            "display": "14¢ per word",
            "conditions": "Official fiction rate: 14¢ per word. Payment via PayPal or check. International authors may request wire transfers.",
            "timing": "Not publicly stated on the guidelines page beyond the payment methods.",
        },
        wordCount={"min": 1000, "max": 22000, "display": "1,000–22,000 words, no exceptions"},
        response={"label": "Average typically under two days; query after two weeks", "band": "under-2-weeks", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="prohibited",
        whatTheyWant=[
            "Well-written science fiction or fantasy. Dark SF/F is allowed. Horror as a genre is not.",
            "Standard manuscript format, .RTF or .DOCX, via the online tracker only.",
            "A cover letter that follows Neil Clarke’s published cover-letter guidance.",
        ],
        whatTheyDontWant=[
            "Email or postal submissions. Simultaneous submissions. Re-submitting a rejected story.",
            "Another story within seven days of a rejection.",
            "Work translated, written, developed or assisted by AI writing tools. Official: that can get you banned.",
            "A long official list of hard sells includes zombies, sexy vampires, talking cats or swords, and pun-dependent humour. Read the page.",
        ],
        requirements=["Online tracker only", "1,000–22,000 words", "No simultaneous submissions", "No AI"],
        rights="First world electronic rights (text and audio), first print rights, and non-exclusive anthology rights for the annual Clarkesworld anthology. English-language unless stated otherwise.",
        howToSubmit=["Read https://clarkesworldmagazine.com/submissions/.", "Submit at https://clarkesworldmagazine.com/submissions_tracker/.", "Keep your tracking number."],
        keywords=["clarkesworld", "science fiction", "fantasy", "14 cents", "worldwide"],
    ),
    base(
        id="clarkesworld-nonfiction",
        slug="clarkesworld-nonfiction",
        publication="Clarkesworld Magazine",
        title="Non-fiction articles for SF/F readers",
        seoTitle="Clarkesworld non-fiction: 10¢ a word, query first",
        excerpt="Clarkesworld pays 10 US cents a word, up to 2,500 words, for original articles of interest to science-fiction and fantasy readers. Query first — do not send a finished article. AI-assisted articles are not being considered.",
        officialUrl="https://clarkesworldmagazine.com/submissions/",
        applyUrl="mailto:nonfiction@clarkesworldmagazine.com",
        applyEmail="nonfiction@clarkesworldmagazine.com",
        applyMethod="Email a query — subject NONFICTION QUERY",
        sources=[{"name": "Clarkesworld — Submission Guidelines (official)", "url": "https://clarkesworldmagazine.com/submissions/"}],
        eligibility={
            "summary": "No country list on the official non-fiction guidelines.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["essays", "articles", "other"],
        writingTypeLabel="SF/F non-fiction article",
        pay={
            "currency": "USD",
            "amountMin": None,
            "amountMax": None,
            "display": "10¢ per word, up to 2,500 words",
            "conditions": "Official: 10¢ a word up to the 2,500-word limit. Footnotes are liked but not counted in the word count.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": 2500, "display": "Up to 2,500 words"},
        response={"label": "No published response time. They generally only reply to queries they want to follow up.", "band": "not-stated", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="prohibited",
        whatTheyWant=[
            "Articles on the genre publishing business, the writing or reading process, or scientific material useful in SF stories.",
            "A query letter with subject NONFICTION QUERY: [title or concept] to nonfiction@clarkesworldmagazine.com.",
            "Thoughtful, in-depth, well-written subjects they have not covered.",
        ],
        whatTheyDontWant=[
            "A completed article instead of a query.",
            "Reviews, literary criticism, interview pitches, reprints.",
            "Articles written, co-written or assisted by AI.",
            "Convention reports, award rants, ten-rules lists, personal alien-abduction memoirs.",
        ],
        requirements=["Query first", "Original to Clarkesworld", "No AI"],
        rights="Not separately restated for non-fiction beyond originality. See the official page.",
        howToSubmit=["Read the non-fiction section of https://clarkesworldmagazine.com/submissions/.", "Email nonfiction@clarkesworldmagazine.com."],
        keywords=["clarkesworld", "nonfiction", "science fiction", "10 cents"],
    ),
    base(
        id="uncanny-fiction",
        slug="uncanny-fiction",
        publication="Uncanny Magazine",
        title="Speculative short fiction",
        seoTitle="Uncanny Magazine fiction: 10¢ a word — window 24 Aug–7 Sep 2026",
        excerpt="Uncanny’s official submissions page: original speculative fiction of 750–10,000 words pays 10 US cents a word including audio rights. The next fiction window is 24 August to 7 September 2026. AI-written work is rejected and can ban the author.",
        officialUrl="https://www.uncannymagazine.com/submissions/",
        applyUrl="https://uncannymagazine.moksha.io/publication/uncanny-magazine",
        applyEmail=None,
        applyMethod="Moksha when the fiction window is open",
        sources=[{"name": "Uncanny Magazine — Submissions (official)", "url": "https://www.uncannymagazine.com/submissions/"}],
        eligibility={
            "summary": "Official: passionate, diverse SF/F from writers from every conceivable background. No country list.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["fiction"],
        writingTypeLabel="Speculative short fiction",
        pay={
            "currency": "USD",
            "amountMin": None,
            "amountMax": None,
            "display": "10¢ per word (including audio rights)",
            "conditions": "Official fiction rate only. Poetry is a separate $40-per-poem card. Essays are listed at $100 on acceptance — that is not this card.",
            "timing": "Not publicly stated beyond the fiction rate itself.",
        },
        wordCount={"min": 750, "max": 10000, "display": "750–10,000 words"},
        response={"label": "They try to respond in 30 days; query after 60 days", "band": "1-3-months", "official": True},
        submissionStatus="upcoming",
        deadline={
            "display": "Fiction window 24 August–7 September 2026",
            "openingDate": "2026-08-24",
            "windowStart": "2026-08-24",
            "windowEnd": "2026-09-07",
            "recurring": False,
        },
        aiPolicy="prohibited",
        whatTheyWant=[
            "Original unpublished speculative fiction. Intricate, experimental stories with verve.",
            "Modern manuscript format, .RTF/.DOC/.DOCX, via Moksha.",
            "Cover letter: length, significant publishing history, anything relevant to that story.",
        ],
        whatTheyDontWant=[
            "Do not submit fiction before 24 August 2026.",
            "Multiple stories at once. Resubmitting a rejected story.",
            "Any submission written with artificial intelligence or similar technologies. Undisclosed AI can permanently bar you.",
        ],
        requirements=["Wait for 24 August 2026", "Moksha only", "750–10,000 words", "No AI"],
        rights="Payment includes audio rights. Broader contract terms are not fully quoted on the public page.",
        howToSubmit=["Watch https://www.uncannymagazine.com/submissions/.", "When open, use https://uncannymagazine.moksha.io/publication/uncanny-magazine."],
        keywords=["uncanny", "speculative fiction", "10 cents", "moksha"],
    ),
    base(
        id="uncanny-poetry",
        slug="uncanny-poetry",
        publication="Uncanny Magazine",
        title="Speculative poetry",
        seoTitle="Uncanny Magazine poetry: $40 a poem — open to 31 Aug 2026",
        excerpt="Uncanny is open to original unpublished speculative poetry of any length from 17 to 31 August 2026. Official pay is $40 per poem. Up to five poems, sent as separate submissions. AI-written work is banned.",
        officialUrl="https://www.uncannymagazine.com/submissions/",
        applyUrl="https://uncannymagazine.moksha.io/publication/3",
        applyEmail=None,
        applyMethod="Moksha — poetry window open through 31 August 2026",
        sources=[{"name": "Uncanny Magazine — Submissions (official)", "url": "https://www.uncannymagazine.com/submissions/"}],
        eligibility={
            "summary": "No country list. Same magazine-wide invitation to writers from every conceivable background.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["poetry"],
        writingTypeLabel="Speculative poetry",
        pay={
            "currency": "USD",
            "amountMin": 40,
            "amountMax": 40,
            "display": "$40 per poem",
            "conditions": "Official poetry rate only.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": None, "display": "Any length"},
        response={"label": "They try to respond in 30 days; query after 60 days", "band": "1-3-months", "official": True},
        submissionStatus="deadline",
        deadline={
            "date": "2026-08-31",
            "display": "Poetry window 17–31 August 2026",
            "windowStart": "2026-08-17",
            "windowEnd": "2026-08-31",
            "recurring": False,
        },
        aiPolicy="prohibited",
        whatTheyWant=["Original unpublished speculative poetry.", "Up to five poems, each as its own Moksha submission."],
        whatTheyDontWant=["Resubmitting a rejected poem.", "AI-written poetry."],
        requirements=["Moksha", "Window closes 31 August 2026", "No AI"],
        rights="Not fully quoted on the public page.",
        howToSubmit=["Submit via the poetry Moksha link on https://www.uncannymagazine.com/submissions/."],
        keywords=["uncanny", "poetry", "speculative", "$40"],
    ),
    base(
        id="griffith-review-bodies",
        slug="griffith-review-bodies",
        publication="Griffith Review",
        title="Bodies of Work — fiction and non-fiction",
        seoTitle="Griffith Review Bodies of Work: AUD$0.75/word, closes 23 Aug 2026",
        excerpt="Griffith Review’s Bodies of Work edition is open for fiction and non-fiction up to 4,000 words until 23 August 2026 (AEST). Official print rate is AUD$0.75 per word. Most writers are Australian; some are from overseas. That is not a closed country list. Disclose any generative AI.",
        officialUrl="https://www.griffithreview.com/for-writers/",
        applyUrl="https://griffithreview.submittable.com/submit",
        applyEmail=None,
        applyMethod="Official Submittable call — Bodies of Work",
        sources=[{"name": "Griffith Review — For Writers (official)", "url": "https://www.griffithreview.com/for-writers/"}],
        eligibility={
            "summary": "Official writers’ guidelines: most contributors are from Australia, some from overseas. That is a description, not a closed nationality list. Do not hide this card from Nigeria on that sentence alone.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["essays", "fiction", "journalism", "personal-essays", "creative-nonfiction"],
        writingTypeLabel="Themed fiction or non-fiction",
        pay={
            "currency": "AUD",
            "amountMin": None,
            "amountMax": None,
            "display": "AUD$0.75 per word (print)",
            "conditions": "Official: fiction and non-fiction commissioned for the print edition is paid at AUD$0.75 per word. Poetry is AUD$200 per poem. GR Online is a flat AUD$500 — that is a different door, opened only in occasional call-outs.",
            "timing": "Not publicly stated on the For Writers page",
        },
        wordCount={"min": None, "max": 4000, "display": "No longer than 4,000 words"},
        response={"label": "Within eight weeks of the call-out closing date", "band": "1-3-months", "official": True},
        submissionStatus="deadline",
        deadline={
            "date": "2026-08-23",
            "display": "Closes 11.59pm AEST, 23 August 2026",
            "windowStart": "2026-07-13",
            "windowEnd": "2026-08-23",
            "recurring": False,
        },
        aiPolicy="disclosure-required",
        whatTheyWant=[
            "Non-fiction and fiction that responds to the Bodies of Work theme — the human body in a digital, biohacking, looksmaxxing age; disability and gender; historic misconceptions.",
            "Erudite yet accessible writing for a general reader. British/Australian spelling will be applied in-house.",
        ],
        whatTheyDontWant=[
            "Work after 23 August 2026 AEST.",
            "Undisclosed generative AI. If you use AI-assisted technologies for creative purposes, disclose it in the cover letter. A statement will run with the published work.",
        ],
        requirements=["Submittable", "≤4,000 words", "Responds to the theme", "Disclose AI if used"],
        rights="Not fully quoted on the For Writers page. Successful print pieces go through a publishing contract.",
        howToSubmit=["Read https://www.griffithreview.com/for-writers/.", "Submit at https://griffithreview.submittable.com/submit before 23 August 2026 AEST."],
        keywords=["griffith review", "australia", "bodies of work", "aud", "essay"],
    ),
    base(
        id="overland-fiction",
        slug="overland-fiction",
        publication="Overland",
        title="Print and Friday Fiction",
        seoTitle="Overland fiction: $580 print / $180 online — Australia and Aotearoa only",
        excerpt="Overland’s official fiction page currently accepts stories only from writers living and/or working in or around Australia and Aotearoa New Zealand. Print pay is $580; online Friday Fiction is $180, plus 12% super. Nigeria does not qualify. Response can take up to six months.",
        officialUrl="https://overland.org.au/submit/fiction-submissions/",
        applyUrl="https://overland.submittable.com/submit/8320/fiction-for-overland-234-non-subscribers",
        applyEmail=None,
        applyMethod="Submittable — complete story only",
        sources=[
            {"name": "Overland — Fiction submissions (official)", "url": "https://overland.org.au/submit/fiction-submissions/"},
            {"name": "Overland — Rates increase, 1 July 2026 (official)", "url": "https://overland.org.au/2026/07/rates-increase/"},
        ],
        eligibility={
            "summary": "Official: currently only accepting fiction from writers living and/or working in or around Australia and Aotearoa New Zealand. Nigeria does not qualify.",
            "mode": "restricted",
            "includesCountries": ["AU", "NZ"],
            "allowsDiaspora": False,
            "notStated": False,
        },
        writingTypes=["fiction"],
        writingTypeLabel="Short fiction",
        pay={
            "currency": "AUD",
            "amountMin": 180,
            "amountMax": 580,
            "display": "$580 print; $180 online (+ 12% super)",
            "conditions": "Fiction submissions page: $580 for print, $180 for Friday Fiction online. A 1 July 2026 official announcement lists the same print-fiction and online-article figures and adds 12% superannuation. The pages use a dollar sign; Overland is an Australian magazine. Currency is recorded here as AUD. Do not convert to USD or naira.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": None, "display": "Not publicly stated. Complete stories only — no novel excerpts."},
        response={"label": "Up to 6 months. Non-subscribers are not guaranteed a response time.", "band": "3-plus-months", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="not-stated",
        whatTheyWant=[
            "Politically engaged, intellectually challenging, inventive fiction.",
            "New work from emerging writers in regional Australia is actively sought.",
            "Word document, 12pt Times New Roman, double-spaced. One story at a time.",
        ],
        whatTheyDontWant=[
            "Writers who do not live or work in or around Australia or Aotearoa New Zealand.",
            "Novel excerpts. A second story while one is still under consideration.",
            "Resubmitting an edited rejected story unless invited.",
        ],
        requirements=["Live or work in/around AU or NZ", "One complete story", "Submittable"],
        rights="Copyright remains with the authors. CAL copying income is split 80% author / 20% publisher.",
        howToSubmit=["Read https://overland.org.au/submit/fiction-submissions/.", "Use the subscriber or non-subscriber Submittable link on that page."],
        keywords=["overland", "australia", "new zealand", "fiction", "not nigeria"],
    ),
    base(
        id="overland-online",
        slug="overland-online",
        publication="Overland",
        title="Online literary, political and cultural analysis",
        seoTitle="Overland online nonfiction: $180 plus super",
        excerpt="Overland’s online magazine wants short, punchy, topical literary, political and cultural analysis. Official current rate is $180 plus 12% super. Personal essays are not taken unless tightly tied to political concerns. No country restriction is stated on the nonfiction page.",
        officialUrl="https://overland.org.au/submit/nonfiction-submissions/",
        applyUrl="https://overland.submittable.com/submit/19452",
        applyEmail=None,
        applyMethod="Submittable (completed piece) or the official pitch form",
        sources=[
            {"name": "Overland — Nonfiction submissions (official)", "url": "https://overland.org.au/submit/nonfiction-submissions/"},
            {"name": "Overland — Pitch to Overland (official)", "url": "https://overland.org.au/submit/pitch-to-overland/"},
            {"name": "Overland — Rates increase, 1 July 2026 (official)", "url": "https://overland.org.au/2026/07/rates-increase/"},
        ],
        eligibility={
            "summary": "The official online nonfiction page does not list countries. Do not copy the Australia/NZ fiction rule onto this card.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["essays", "opinion", "analysis", "reviews"],
        writingTypeLabel="Online analysis / polemic",
        pay={
            "currency": "AUD",
            "amountMin": 180,
            "amountMax": 180,
            "display": "$180 (+ 12% super, + GST if applicable)",
            "conditions": "Official nonfiction page and the 1 July 2026 rates note: $180 for online articles, plus 12% superannuation. Print nonfiction is listed as $550 on the current nonfiction page and as $580 on the July 2026 rates announcement — those two official figures do not match, so print nonfiction is not given its own card here. Currency is recorded as AUD; the pages use a dollar sign.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": 800, "max": 1200, "display": "Pitch page: finished online articles generally 800–1,200 words", "notes": "Stored range is from the pitch page, not a hard limit on the nonfiction page."},
        response={"label": "Up to 6 months", "band": "3-plus-months", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="not-stated",
        whatTheyWant=[
            "Short, punchy, topical literary, political and cultural analysis.",
            "A completed piece via Submittable, or a ~100-word pitch on the pitch page: what, why you, how it differs, when you can file.",
        ],
        whatTheyDontWant=[
            "Personal essays or creative nonfiction online unless very consistently linked to political concerns.",
            "Do not invent a print-essay fee while the two official print figures disagree.",
        ],
        requirements=["Submittable or official pitch form", "Political/cultural analysis"],
        rights="Copyright remains with the authors.",
        howToSubmit=["Read https://overland.org.au/submit/nonfiction-submissions/.", "Pitch page: https://overland.org.au/submit/pitch-to-overland/."],
        keywords=["overland", "australia", "online essay", "polemic"],
    ),
    base(
        id="americas-quarterly",
        slug="americas-quarterly",
        publication="Americas Quarterly",
        title="Politics, business and culture in the Americas",
        seoTitle="Americas Quarterly pitches: Latin America and the Caribbean",
        excerpt="Americas Quarterly occasionally accepts proposals from new authors. Official contact page: send a one- to two-paragraph pitch outlining the argument and conclusions to aqeditors@as-coa.org. A fee is not stated on that page.",
        officialUrl="https://www.americasquarterly.org/contact/",
        applyUrl="mailto:aqeditors@as-coa.org",
        applyEmail="aqeditors@as-coa.org",
        applyMethod="Email a one- to two-paragraph pitch",
        sources=[{"name": "Americas Quarterly — Contact (official)", "url": "https://www.americasquarterly.org/contact/"}],
        eligibility={
            "summary": "No nationality list. The magazine covers politics, business and culture in Latin America and the Caribbean. That is a beat, not a passport rule.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["journalism", "analysis", "opinion"],
        writingTypeLabel="Reported or argued piece on the Americas",
        pay={
            "currency": None,
            "amountMin": None,
            "amountMax": None,
            "display": "Not publicly stated on the official contact page",
            "conditions": "The official contact page says AQ commissions most articles and occasionally accepts proposals. It does not publish a rate.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": None, "display": "Not publicly stated"},
        response={"label": "Not publicly stated", "band": "not-stated", "official": False},
        submissionStatus="open",
        deadline=None,
        aiPolicy="not-stated",
        whatTheyWant=["A one- to two-paragraph pitch outlining the article’s argument and conclusions.", "Subject matter in AQ’s Latin America and Caribbean remit."],
        whatTheyDontWant=["A made-up fee. The official contact page does not state one.", "Treating this as a high-volume open call — official: most articles are commissioned."],
        requirements=["Email aqeditors@as-coa.org", "Short pitch"],
        rights="Not publicly stated on the contact page.",
        howToSubmit=["Read https://www.americasquarterly.org/contact/.", "Email aqeditors@as-coa.org."],
        keywords=["americas quarterly", "latin america", "caribbean", "pitch"],
    ),
    base(
        id="nacla",
        slug="nacla",
        publication="NACLA",
        title="Online journalism on Latin America and the Caribbean",
        seoTitle="NACLA online pitches: $100–$200 if writing is your living",
        excerpt="NACLA wants short pitches — not drafts — on Latin America, the Caribbean, US Latinx communities and US hemispheric policy. Official: a small honorarium of $100–$200 for contributors who depend on writing as their primary income. Typical online length 1,200–1,500 words. Spanish pitches are welcome.",
        officialUrl="https://nacla.org/write-for-nacla/",
        applyUrl="mailto:editor@nacla.org",
        applyEmail="editor@nacla.org",
        applyMethod="Email a short query to the web editor",
        sources=[{"name": "NACLA — Write for NACLA (official)", "url": "https://nacla.org/write-for-nacla/"}],
        eligibility={
            "summary": "Official: academics, activists, students and journalists. No country list. Coverage is Latin America, the Caribbean, US Latinx communities and US policy in the hemisphere.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["journalism", "analysis", "essays"],
        writingTypeLabel="Online reported analysis",
        pay={
            "currency": "USD",
            "amountMin": 100,
            "amountMax": 200,
            "display": "$100–$200 honorarium if writing is your primary income",
            "conditions": "Official: limited budget. Currently they offer a small honorarium to contributors who depend on writing as their primary source of income, including freelance reporters and graduate students. The honorarium ranges from $100–$200 depending on the type of piece. Original photos: $25 each for contributors who make a living from photography. Currency is not labelled on the page; figures are recorded here as USD. Do not treat every accepted piece as paid.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": 1200, "max": 1500, "display": "Typically 1,200–1,500 words online; longer considered case by case"},
        response={"label": "They aim for quick turnarounds", "band": "not-stated", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="not-stated",
        whatTheyWant=[
            "A short query: the story, why you, the reporting process, why unique and timely, plus clips.",
            "Journalistic narrative with sociocultural or political-economic context — more analysis than straight news.",
            "Hyperlinks for verifiable facts. Pitches and drafts in Spanish are welcome.",
        ],
        whatTheyDontWant=["Completed drafts or manuscripts for the web.", "Footnotes instead of links.", "Assuming payment if writing is not your primary income."],
        requirements=["Pitch only, to editor@nacla.org", "Latin America / Caribbean / Latinx / US hemispheric policy"],
        rights="Web articles are available for republication with “Originally published in NACLA” and a link. Print magazine articles are copyrighted.",
        howToSubmit=["Read https://nacla.org/write-for-nacla/.", "Email editor@nacla.org. Investigations/grant ideas: jchandler@nacla.org."],
        keywords=["nacla", "latin america", "caribbean", "honorarium"],
    ),
    base(
        id="the-tyee",
        slug="the-tyee",
        publication="The Tyee",
        title="News, features and first-person from British Columbia and Cascadia",
        seoTitle="The Tyee freelance: $300 a day",
        excerpt="The Tyee pays freelancers a day rate of $300 and usually assigns one- to three-day stories. Official focus is British Columbia, Cascadia and beyond. No country list. AI-written journalism is not published. If you hear nothing in seven business days, they are unlikely to take the pitch.",
        officialUrl="https://thetyee.ca/submissions/",
        applyUrl="mailto:editor@thetyee.ca",
        applyEmail="editor@thetyee.ca",
        applyMethod="Email one named senior editor — do not pitch several at once",
        sources=[{"name": "The Tyee — Submissions (official)", "url": "https://thetyee.ca/submissions/"}],
        eligibility={
            "summary": "No nationality list. The magazine is focused on British Columbia, Cascadia and beyond. That is a beat. They welcome pitches from people underrepresented in the media.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["journalism", "personal-essays", "analysis", "opinion"],
        writingTypeLabel="Reported news, features, analysis, first person",
        pay={
            "currency": "CAD",
            "amountMin": 300,
            "amountMax": 900,
            "display": "$300 a day (usually 1–3 days)",
            "conditions": "Official: $300 day rate. Assignment length is agreed as a one-day, two-day or three-day story. Stories above three days are less common. The page does not label CAD or USD; The Tyee is a Canadian magazine. Currency is recorded here as CAD. Do not convert.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": None, "display": "Not publicly stated. Fee is a day rate, not a word rate."},
        response={"label": "If no reply in seven business days, they are unlikely to move forward", "band": "under-2-weeks", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="prohibited",
        whatTheyWant=[
            "First-person that joins expertise and lived experience; counter-intuitive takes; critical analysis of a live controversy.",
            "Subject line [PITCH]: headline. Angle, scene or quotes, hook, sources, why The Tyee, why you.",
            "One editor only. Unsure which: editor@thetyee.ca.",
        ],
        whatTheyDontWant=[
            "A topic without an angle.",
            "Journalism written or generated by AI.",
            "Pitching more than one editor at the same time.",
        ],
        requirements=["One editor", "Clear angle", "No AI journalism"],
        rights="Not publicly stated on the submissions page.",
        howToSubmit=["Read https://thetyee.ca/submissions/ and The Tyee’s AI policy.", "Email one listed senior editor."],
        keywords=["the tyee", "british columbia", "canada", "day rate", "cascadia"],
    ),
    base(
        id="wasafiri-interviews",
        slug="wasafiri-interviews",
        publication="Wasafiri",
        title="Interviews",
        seoTitle="Wasafiri interviews: typically £150, currently open",
        excerpt="Wasafiri is open year-round for interviews via its Taylor & Francis portal. Official typical fee is £150 for a transcribed and edited interview of 4,000–5,000 words. Fiction, life writing and poetry are closed on the same page. AI-generated content is not permitted.",
        officialUrl="https://www.wasafiri.org/submit/",
        applyUrl="https://rp.tandfonline.com/submission/create?journalCode=rwas",
        applyEmail=None,
        applyMethod="Official Taylor & Francis submissions portal",
        sources=[{"name": "Wasafiri — Submit (official)", "url": "https://www.wasafiri.org/submit/"}],
        eligibility={
            "summary": "Official: they do not discriminate on age, gender, nationality, race or sexuality. International contemporary writing.",
            "mode": "open",
            "notStated": False,
        },
        writingTypes=["interviews"],
        writingTypeLabel="Interview",
        pay={
            "currency": "GBP",
            "amountMin": 150,
            "amountMax": 150,
            "display": "Typically £150",
            "conditions": "Official: Wasafiri pays for all creative submissions and reviews. The published table is “an indication only of a typical fee.” Interviews (transcribed and edited): £150. Critical academic articles are open on the same page but are not listed in the payment table.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": 4000, "max": 5000, "display": "4,000–5,000 words"},
        response={"label": "Not separately stated for interviews. Critical articles: 9–12 months.", "band": "not-stated", "official": False},
        submissionStatus="open",
        deadline=None,
        aiPolicy="limited",
        whatTheyWant=["A transcribed and edited interview of 4,000–5,000 words submitted through the official portal."],
        whatTheyDontWant=[
            "Fiction, life writing or poetry while those doors are closed.",
            "Articles formed of AI-generated content, or produced through machine translation — treated as plagiarism. Assistive software is permitted.",
        ],
        requirements=["Taylor & Francis portal", "4,000–5,000 words"],
        rights="Not fully stated on the submit page.",
        howToSubmit=["Read https://www.wasafiri.org/submit/.", "Submit at the Taylor & Francis link on that page."],
        keywords=["wasafiri", "interview", "gbp", "commonwealth"],
    ),
    base(
        id="the-offing-wit-tea",
        slug="the-offing-wit-tea",
        publication="The Offing",
        title="Wit Tea — humour",
        seoTitle="The Offing Wit Tea: $25–$100, open to 1 Oct 2026",
        excerpt="The Offing’s humour department, Wit Tea, is open through 1 October 2026. Official contributor fee is $25–$100 depending on department and length. No submission fee in 2026. Comedic work in any genre, no more than 8 pages. AI only if it is an intentional, disclosed critique of AI.",
        officialUrl="https://theoffingmag.com/submit/submission_guidelines/",
        applyUrl="https://theoffingmag.submittable.com/submit",
        applyEmail=None,
        applyMethod="Submittable — Wit Tea",
        sources=[
            {"name": "The Offing — Submission Guidelines (official)", "url": "https://theoffingmag.com/submit/submission_guidelines/"},
            {"name": "The Offing — Submittable (official)", "url": "https://theoffingmag.submittable.com/submit"},
        ],
        eligibility={
            "summary": "No country list on the official guidelines.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["other", "fiction", "essays"],
        writingTypeLabel="Humour / satire",
        pay={
            "currency": "USD",
            "amountMin": 25,
            "amountMax": 100,
            "display": "$25–$100 on publication",
            "conditions": "Official sitewide: upon publication, contributors are paid a $25–$100 fee, depending on department and number/length of works. Novel excerpts emailed separately are unpaid.",
            "timing": "Upon publication",
        },
        wordCount={"min": None, "max": None, "display": "No more than 8 pages"},
        response={"label": "They try to respond within six months", "band": "3-plus-months", "official": True},
        submissionStatus="deadline",
        deadline={
            "date": "2026-10-01",
            "display": "Wit Tea listed as ending 1 October 2026",
            "windowEnd": "2026-10-01",
            "recurring": False,
        },
        aiPolicy="disclosure-required",
        whatTheyWant=["Comedic work in any genre. Strong character voices, absurdity, momentum, vulnerability, surprise."],
        whatTheyDontWant=[
            "Email submissions.",
            "More than one piece per department at a time.",
            "AI unless it is an intentional engagement or critique of AI, marked with where and how it was used.",
        ],
        requirements=["Submittable only", "≤8 pages", "Previously unpublished in English"],
        rights="First serial rights worldwide in English and non-exclusive anthology rights. Contributor retains other rights and must cite The Offing if relicensed.",
        howToSubmit=["Read https://theoffingmag.com/submit/submission_guidelines/.", "Submit Wit Tea via https://theoffingmag.submittable.com/submit."],
        keywords=["the offing", "humour", "wit tea", "$25"],
    ),
    base(
        id="the-rumpus-essays",
        slug="the-rumpus-essays",
        publication="The Rumpus",
        title="Essays, fiction and poetry",
        seoTitle="The Rumpus: $500 prose, closed until 15 September 2026",
        excerpt="The Rumpus pays $500 for prose and comics and $200 for poetry for work accepted on or after 1 April 2026. Official Submittable: fiction, essays and poetry are closed until 15 September 2026 so they can catch up. Interviews are closed until September. AI-assisted work is not considered.",
        officialUrl="https://therumpus.net/about/",
        applyUrl="https://therumpus.submittable.com/submit",
        applyEmail=None,
        applyMethod="Submittable when the genre reopens — do not email",
        sources=[
            {"name": "The Rumpus — About / Writers’ Guidelines (official)", "url": "https://therumpus.net/about/"},
            {"name": "The Rumpus — Submittable (official)", "url": "https://therumpus.submittable.com/submit"},
        ],
        eligibility={
            "summary": "No country list. Official: emerging and established writers.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["essays", "fiction", "poetry", "personal-essays"],
        writingTypeLabel="Essays, fiction, poetry",
        pay={
            "currency": "USD",
            "amountMin": 200,
            "amountMax": 500,
            "display": "$500 prose/comics; $200 poetry/interviews",
            "conditions": "Official About page: starting for work accepted on or after 1 April 2026, $500 for prose and comics and $200 for poetry and interviews. Submittable repeats $500 prose/comics and $200 poetry.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": None, "display": "Not a single sitewide limit on the About page. El Alboroto (Spanish section) states a 2,500-word maximum — that is a different card."},
        response={"label": "They hope to respond within three months. Do not query sooner.", "band": "1-3-months", "official": True},
        submissionStatus="upcoming",
        deadline={
            "display": "Fiction, essays and poetry reopen 15 September 2026",
            "openingDate": "2026-09-15",
            "recurring": False,
        },
        aiPolicy="prohibited",
        whatTheyWant=["Original unpublished fiction, poetry, essays, comics, criticism, interviews — when that genre is listed as open.", "One submission per section at a time. Simultaneous submissions allowed if you withdraw promptly."],
        whatTheyDontWant=[
            "Do not submit essays, fiction or poetry before 15 September 2026.",
            "Pitches. Official: they do not accept pitches under any circumstances.",
            "Work written with assistance from or by AI.",
            "Previously published work, including personal blogs and social media.",
        ],
        requirements=["Wait until 15 September 2026", "Submittable", "Previously unpublished", "No AI"],
        rights="Not fully stated on the About page.",
        howToSubmit=["Do not submit now.", "On or after 15 September 2026, use https://therumpus.submittable.com/submit and only the categories that appear."],
        keywords=["the rumpus", "essays", "$500", "september 2026"],
    ),
    base(
        id="the-rumpus-el-alboroto",
        slug="the-rumpus-el-alboroto",
        publication="The Rumpus",
        title="El Alboroto — Spanish-language section",
        seoTitle="The Rumpus El Alboroto: Spanish prose $500, currently open",
        excerpt="El Alboroto is The Rumpus’s Spanish-language section. Official Submittable: same pay as the English magazine — $500 for prose and comics, $200 for poetry. Maximum 2,500 words. Complete work only, no pitches. AI is banned.",
        officialUrl="https://therumpus.submittable.com/submit",
        applyUrl="https://therumpus.submittable.com/submit/352155/el-alboroto",
        applyEmail=None,
        applyMethod="Submittable — El Alboroto",
        sources=[{"name": "The Rumpus Submittable — El Alboroto (official)", "url": "https://therumpus.submittable.com/submit"}],
        eligibility={
            "summary": "Spanish-language work. No country list on the El Alboroto guidelines.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["essays", "fiction", "poetry", "reviews", "interviews", "other"],
        writingTypeLabel="Spanish fiction, essays, criticism, comics, interviews, poetry",
        pay={
            "currency": "USD",
            "amountMin": 200,
            "amountMax": 500,
            "display": "Same as The Rumpus: $500 prose/comics; $200 poetry",
            "conditions": "Official El Alboroto text: they pay the same rates as The Rumpus.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": 2500, "display": "Maximum 2,500 words. Microfiction: up to three pieces of 1,000 words or fewer in one file."},
        response={"label": "They hope to respond within three months", "band": "1-3-months", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="prohibited",
        whatTheyWant=[
            "Unpublished Spanish-language work with a cover letter (max one page) and a third-person bio.",
            "Criticism that takes a position. Personal essays with depth. Interviews with living critical dialogue. Fiction with its own universe.",
        ],
        whatTheyDontWant=["Pitches or unfinished work.", "AI assistance.", "More than one live submission per category."],
        requirements=["Spanish", "Submittable", "≤2,500 words", "No AI"],
        rights="Not fully stated on the Submittable blurb.",
        howToSubmit=["Read the El Alboroto guidelines on https://therumpus.submittable.com/submit.", "Submit only to El Alboroto."],
        keywords=["el alboroto", "rumpus", "spanish", "español", "$500"],
    ),
    base(
        id="words-without-borders-reviews",
        slug="words-without-borders-reviews",
        publication="Words Without Borders",
        title="Book reviews",
        seoTitle="Words Without Borders book reviews: $175, still open",
        excerpt="Words Without Borders closed general submissions on 10 August 2026. Official exception: book-review pitches for titles at least four months from publication. Official review fee is $175. Email submissions@wordswithoutborders.org with subject “Book review”.",
        officialUrl="https://wordswithoutborders.org/submissions/",
        applyUrl="mailto:submissions@wordswithoutborders.org",
        applyEmail="submissions@wordswithoutborders.org",
        applyMethod="Email a review pitch — subject Book review",
        sources=[{"name": "Words Without Borders — Submissions (official)", "url": "https://wordswithoutborders.org/submissions/"}],
        eligibility={
            "summary": "No country list on the current submissions page. WWB publishes international writing in translation.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["reviews"],
        writingTypeLabel="Book review",
        pay={
            "currency": "USD",
            "amountMin": 175,
            "amountMax": 175,
            "display": "$175",
            "conditions": "Official current rates: book reviews $175. Authors and translators are paid equally on translated writing. Fiction/nonfiction $150 per 1,000 words capped at $350, poetry $50–$75, interviews $175 — those doors are closed as of 10 August 2026 and are not this card.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": None, "display": "Not publicly stated for reviews"},
        response={"label": "Not publicly stated", "band": "not-stated", "official": False},
        submissionStatus="open",
        deadline=None,
        aiPolicy="not-stated",
        whatTheyWant=["A pitch for a book with a publication date at least four months in the future.", "Subject line: Book review."],
        whatTheyDontWant=["General fiction, poetry or nonfiction while the 10 August 2026 close is in force. Official: those submissions will not be considered or answered."],
        requirements=["Email submissions@wordswithoutborders.org", "Book at least four months from publication"],
        rights="Translators hold copyrights to their translations. Review rights are not separately spelled out.",
        howToSubmit=["Read https://wordswithoutborders.org/submissions/.", "Email a review pitch only."],
        keywords=["words without borders", "translation", "book review", "$175"],
    ),
    base(
        id="brevity-essays",
        slug="brevity-essays",
        publication="Brevity",
        title="Flash nonfiction (750 words or fewer)",
        seoTitle="Brevity flash essays: $45 — closed until September",
        excerpt="Brevity pays a $45 honorarium via PayPal for featured flash essays of 750 words or fewer. Official Submittable: the Brief Nonfiction category is open September–April. In August it is closed. AI-generated or AI-assisted work is rejected. Writers from many countries have been published; there is no country list.",
        officialUrl="https://brevitymag.com/submissions/",
        applyUrl="https://brevity.submittable.com/submit",
        applyEmail=None,
        applyMethod="Submittable — closed until September",
        sources=[
            {"name": "Brevity — Submissions (official)", "url": "https://brevitymag.com/submissions/"},
            {"name": "Brevity — Submittable (official)", "url": "https://brevity.submittable.com/submit"},
        ],
        eligibility={
            "summary": "Official: they have published writers from India, Egypt, the Netherlands, Ireland, Spain, Malaysia, Qatar and Japan, and many previously unpublished authors. No closed country list.",
            "mode": "open",
            "notStated": False,
        },
        writingTypes=["essays", "creative-nonfiction", "personal-essays"],
        writingTypeLabel="Flash creative nonfiction",
        pay={
            "currency": "USD",
            "amountMin": 45,
            "amountMax": 45,
            "display": "$45 honorarium if featured",
            "conditions": "Official: authors are paid a $45 honorarium for featured essays, via PayPal.",
            "timing": "Not publicly stated beyond PayPal",
        },
        wordCount={"min": None, "max": 750, "display": "750 words or fewer"},
        response={"label": "Not publicly stated", "band": "not-stated", "official": False},
        submissionStatus="upcoming",
        deadline={
            "display": "Brief Nonfiction open September–April. Currently closed (August).",
            "openingDate": "2026-09-01",
            "recurring": True,
        },
        aiPolicy="prohibited",
        whatTheyWant=["Extremely brief essays, 750 words or fewer.", "Preferred format: single space, no indent, extra space between paragraphs, unless form is a design element."],
        whatTheyDontWant=["Do not submit during the summer close.", "AI-generated work, including writing partially created or assisted by an LLM."],
        requirements=["Wait until September", "≤750 words", "Submittable", "No AI"],
        rights="Not fully stated on the submissions page.",
        howToSubmit=["Do not submit in August.", "From September, use https://brevity.submittable.com/submit."],
        keywords=["brevity", "flash", "cnf", "$45", "750 words"],
    ),
    base(
        id="markaz-review",
        slug="markaz-review",
        publication="The Markaz Review",
        title="Essays, features, fiction and reviews from SWANA",
        seoTitle="The Markaz Review: SWANA writing, honorarium amount not stated",
        excerpt="The Markaz Review wants essays, features, fiction, memoir, poetry and reviews that amplify the Middle East, North Africa and Southwest Asia. Official: every contributor is paid an honorarium within 30 days of publication — the dollar amount is not on the submissions page. Comedy-issue deadline 1 September 2026; year-round pitches also invited. No AI.",
        officialUrl="https://themarkaz.org/submissions/",
        applyUrl="https://duotrope.com/duosuma/submit/the-markaz-review-OGqkp",
        applyEmail="editor@themarkaz.org",
        applyMethod="Duosuma, or a short query to an editor",
        sources=[{"name": "The Markaz Review — Submissions (official)", "url": "https://themarkaz.org/submissions/"}],
        eligibility={
            "summary": "Official mission: amplify voices from the Middle East, North Africa and Southwest Asia (SWANA). Open to emerging and established writers, and to writing in multiple languages. That is a mission, not a closed passport list.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["essays", "journalism", "fiction", "poetry", "reviews", "interviews", "personal-essays", "opinion"],
        writingTypeLabel="Essay, feature, fiction, poetry, review, interview",
        pay={
            "currency": None,
            "amountMin": None,
            "amountMax": None,
            "display": "Honorarium — amount not published",
            "conditions": "Official FAQ: TMR pays all contributors an honorarium within 30 days of publication. The page does not state a dollar figure.",
            "timing": "Within 30 days of publication",
        },
        wordCount={"min": 750, "max": 3000, "display": "Submissions 750–3,000 words; features/reviews often 1,000–3,000; opinion 750–1,500"},
        response={"label": "Not publicly stated", "band": "not-stated", "official": False},
        submissionStatus="open",
        deadline={
            "date": "2026-09-01",
            "display": "Comedy issue: 1 September 2026. Year-round submissions also invited.",
            "windowEnd": "2026-09-01",
            "recurring": False,
        },
        aiPolicy="prohibited",
        whatTheyWant=[
            "Work from and about SWANA. Strong point of view, clear voice, authority, a commanding lead.",
            "Comedy issue: fiction, nonfiction, poetry, hybrid — humorous writing or writing about humour. Deadline 1 September.",
            "Query: one or two sentences on the story, why TMR, why you, plus clips if you are new.",
        ],
        whatTheyDontWant=[
            "AI-generated or AI-assisted text or images. Official: violators are permanently banned. Spellcheck/grammar tools are fine.",
            "Stories or corrections in the body of an email — Word or Google Doc, track changes.",
            "A made-up honorarium number.",
        ],
        requirements=["Duosuma or editor query", "No AI", "SWANA relevance"],
        rights="Not fully stated on the submissions FAQ.",
        howToSubmit=["Read https://themarkaz.org/submissions/.", "Duosuma portal (comedy portal noted as opening 21 August) or query editor@themarkaz.org."],
        keywords=["markaz", "swana", "middle east", "north africa", "comedy issue"],
    ),
    base(
        id="strange-horizons-fiction",
        slug="strange-horizons-fiction",
        publication="Strange Horizons",
        title="Speculative fiction",
        seoTitle="Strange Horizons fiction: 10¢ a word — closed until fall 2026",
        excerpt="Strange Horizons pays 10 US cents a word (minimum $60) for original speculative fiction up to 10,000 words. Official page updated 9 August 2026: currently closed; they anticipate opening again in fall 2026. Worldwide. Author-only translations only. AI/LLM stories are not considered.",
        officialUrl="https://strangehorizons.com/wordpress/submit/fiction-submission-guidelines/",
        applyUrl="https://strangehorizons.com/wordpress/submit/fiction-submission-guidelines/",
        applyEmail="fiction@strangehorizons.com",
        applyMethod="Moksha when they reopen — do not email stories",
        sources=[{"name": "Strange Horizons — Fiction Submission Guidelines (official)", "url": "https://strangehorizons.com/wordpress/submit/fiction-submission-guidelines/"}],
        eligibility={
            "summary": "Official: submissions from anywhere in the world. British spellings are fine.",
            "mode": "open",
            "notStated": False,
        },
        writingTypes=["fiction"],
        writingTypeLabel="Speculative fiction",
        pay={
            "currency": "USD",
            "amountMin": 60,
            "amountMax": None,
            "display": "10¢ per word (minimum $60)",
            "conditions": "Official: 10¢/word USD, minimum $60, within 60 days of contract. PayPal or check. Word count is rounded up to the next 100 words.",
            "timing": "Within 60 days of contract",
        },
        wordCount={"min": None, "max": 10000, "display": "Up to 10,000 words; under 5,000 preferred"},
        response={"label": "Not stated for the closed period", "band": "not-stated", "official": False},
        submissionStatus="upcoming",
        deadline={
            "display": "Official: currently closed; anticipate opening again in fall 2026. No exact date.",
            "recurring": False,
        },
        aiPolicy="prohibited",
        whatTheyWant=[
            "Good speculative fiction, including work from or about diverse and under-represented perspectives, written without exoticising.",
            "When open: Moksha only. Previously unpublished in English.",
        ],
        whatTheyDontWant=[
            "Do not submit while the page says closed.",
            "Simultaneous or multiple submissions. Reprints previously published in English. Resubmissions.",
            "Stories translated or written using LLMs/AI.",
            "Translations by someone other than the original author — those go to sister magazine Samovar.",
        ],
        requirements=["Wait for the fall 2026 reopen", "Moksha", "Speculative", "No AI"],
        rights="First-printing world exclusive English-language rights including audio for six months. After that you may republish. Archive removal allowed after one year.",
        howToSubmit=["Do not submit now.", "Watch https://strangehorizons.com/wordpress/submit/fiction-submission-guidelines/."],
        keywords=["strange horizons", "speculative fiction", "10 cents", "closed"],
    ),
    base(
        id="electric-literature-essays",
        slug="electric-literature-essays",
        publication="Electric Literature",
        title="Personal narrative essays",
        seoTitle="Electric Literature personal essays: $100 — currently closed",
        excerpt="Electric Literature pays $100 for personal-narrative essays of 2,000–6,500 words. Official Submittable: this category is closed to the public (members may submit year-round). Cultural criticism pitches are also closed. Generative AI is not accepted except rare, disclosed artistic uses.",
        officialUrl="https://electricliterature.com/about/submit/",
        applyUrl="https://electricliterature.submittable.com/submit",
        applyEmail=None,
        applyMethod="Submittable when a public window opens — or EL membership",
        sources=[{"name": "Electric Literature — Submissions (official)", "url": "https://electricliterature.com/about/submit/"}],
        eligibility={
            "summary": "No country list. Public windows are limited; $5/month or $50/year members may submit year-round.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["personal-essays", "essays", "creative-nonfiction"],
        writingTypeLabel="Personal narrative essay",
        pay={
            "currency": "USD",
            "amountMin": 100,
            "amountMax": 100,
            "display": "$100",
            "conditions": "Official: $100 for personal narrative, with 90-day exclusivity. Recommended Reading fiction is $300; The Commuter is $100; interviews and reading lists $75 — those are separate, and several are also closed.",
            "timing": "Not publicly stated beyond acceptance",
        },
        wordCount={"min": 2000, "max": 6500, "display": "2,000–6,500 words"},
        response={"label": "About six to eight months when open", "band": "3-plus-months", "official": True},
        submissionStatus="closed",
        deadline={"display": "Official: Personal Narrative is closed for submissions. No next public date on the page.", "recurring": False},
        aiPolicy="prohibited",
        whatTheyWant=["When open: a full draft of a narrative essay that interrogates, investigates, adventures or introspects."],
        whatTheyDontWant=["Do not submit while Submittable says closed, unless you are an EL member using the member link.", "Generative-AI work except rare, disclosed artistic uses."],
        requirements=["Wait for a public window or join as a member", "Full draft", "2,000–6,500 words"],
        rights="Official: $100 for publishing rights, with 90-day exclusivity.",
        howToSubmit=["Read https://electricliterature.com/about/submit/.", "Do not use the public Submittable link while it says closed."],
        keywords=["electric literature", "personal essay", "$100", "closed"],
    ),
    base(
        id="undark",
        slug="undark",
        publication="Undark Magazine",
        title="Science, society and reported features",
        seoTitle="Undark pitches: science and society — pay not stated on official pages",
        excerpt="Undark wants reported features, essays and op-eds where science collides with politics, economics and culture. Official door: the submissions form, not a general email. A fee is not published on the submissions or “what we’re looking for” pages. AI may not write pitches or drafts.",
        officialUrl="https://undark.org/submission-guidelines/",
        applyUrl="https://undark.org/submission-guidelines/",
        applyEmail=None,
        applyMethod="Official online submissions form — do not email pitches",
        sources=[
            {"name": "Undark — Submissions (official)", "url": "https://undark.org/submission-guidelines/"},
            {"name": "Undark — What is Undark looking for? (official)", "url": "https://undark.org/what-is-undark-looking-for/"},
            {"name": "Undark — AI policy (official)", "url": "https://undark.org/ai-policy/"},
        ],
        eligibility={
            "summary": "No country list. First-time contributors must include a bio and clips.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["journalism", "essays", "opinion", "reviews"],
        writingTypeLabel="Reported feature, essay, op-ed, review",
        pay={
            "currency": None,
            "amountMin": None,
            "amountMax": None,
            "display": "Not publicly stated on the official pages checked",
            "conditions": "Neither the submissions page nor the “What is Undark looking for?” page publishes a rate. Third-party guides have quoted other numbers. Those numbers are not copied here.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": None, "max": None, "display": "Not publicly stated. They run reported features, book reviews, photo essays, op-eds and about a dozen long-form narratives a year."},
        response={"label": "They will try to respond expeditiously; a small team, it may take time", "band": "not-stated", "official": True},
        submissionStatus="open",
        deadline=None,
        aiPolicy="prohibited",
        whatTheyWant=[
            "Stories where science intersects everyday life — vaccines, climate, agrochemicals, renewable energy, AI, research culture, money and bias in labs.",
            "Use the form. Pitch meetings are generally Wednesdays 11 a.m. EST.",
            "If you have not written for them: bio plus clips.",
        ],
        whatTheyDontWant=[
            "Emailing a pitch to a general inbox.",
            "A made-up fee.",
            "Pitches or drafts generated or line-edited by AI. Official exception only when AI itself is the subject, with disclosure.",
            "Purely historical yarns, or first-person outside the op-ed silo unless your presence is essential. Climate/environment pitches are the most common and the hardest to land.",
        ],
        requirements=["Official form only", "Clips if you are new", "No AI pitch or draft"],
        rights="Not stated on the submissions page. Separate republishing guidelines exist for published Undark stories.",
        howToSubmit=["Read https://undark.org/what-is-undark-looking-for/ and https://undark.org/ai-policy/.", "Submit via the form on https://undark.org/submission-guidelines/."],
        keywords=["undark", "science", "journalism", "pitch"],
    ),
    base(
        id="conde-nast-traveler",
        slug="conde-nast-traveler",
        publication="Condé Nast Traveler",
        title="Travel features, essays and service",
        seoTitle="Condé Nast Traveler pitches: from $300 for 500–600 words",
        excerpt="Condé Nast Traveler’s official pitch page (updated 24 March 2026) pays from $300 for 500–600 words. Pitch only — no spec drafts. Inclusive coverage including BIPOC, LGBTQ+ and disabled travellers. No country list. AI policy is not stated on that page.",
        officialUrl="https://www.cntraveler.com/info/how-to-pitch-conde-nast-traveler",
        applyUrl="https://www.cntraveler.com/info/how-to-pitch-conde-nast-traveler",
        applyEmail=None,
        applyMethod="Email the named section editor — firstname_lastname@condenast.com",
        sources=[{"name": "How to Pitch Condé Nast Traveler (official)", "url": "https://www.cntraveler.com/info/how-to-pitch-conde-nast-traveler"}],
        eligibility={
            "summary": "No country list. Preference on destination guides is given to writers based in the city they cover, or who spend notable time there. That is expertise, not a nationality ban.",
            "mode": "open",
            "notStated": True,
        },
        writingTypes=["journalism", "personal-essays", "articles"],
        writingTypeLabel="Travel feature, service, first person",
        pay={
            "currency": "USD",
            "amountMin": 300,
            "amountMax": None,
            "display": "From $300 for 500–600 words",
            "conditions": "Official: rates start at $300 for 500 to 600 words. They do not accept pre-written stories on spec.",
            "timing": "Not publicly stated",
        },
        wordCount={"min": 500, "max": 600, "display": "Rate example: 500–600 words. Other lengths exist; no single required range.", "notes": "Stored min/max is the official rate example, not a hard limit for every franchise."},
        response={"label": "Not a single published reply time for every desk", "band": "not-stated", "official": False},
        submissionStatus="open",
        deadline=None,
        aiPolicy="not-stated",
        whatTheyWant=[
            "A paragraph or two: suggested headline, angle, sources/characters, why now. News pegs help. Responsible travel.",
            "Stories, not destinations. Disclose any sponsored trip.",
            "Desks include Women Who Travel, destination guides, cruising, outdoors, destination features, air travel, points, shopping, identity, food, hotels, vacation rentals, Travel Well, Future of Travel.",
        ],
        whatTheyDontWant=[
            "“I’m going to X, need anything?”",
            "The same idea sent to multiple editors.",
            "Diary travelogues or stream-of-consciousness trip recaps.",
            "A finished spec draft.",
        ],
        requirements=["Pitch only", "One editor", "Disclose sponsored travel"],
        rights="Not stated on the pitch page.",
        howToSubmit=["Read https://www.cntraveler.com/info/how-to-pitch-conde-nast-traveler (updated 24 March 2026).", "Email the named editor as firstname_lastname@condenast.com."],
        keywords=["conde nast traveler", "travel", "$300", "freelance"],
    ),
]

added = []
for o in NEW:
    if o["id"] in existing:
        continue
    data["opportunities"].append(o)
    added.append(o["id"])

data["updatedAt"] = "2026-08-19"
path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
print("added", len(added), added)
print("total", len(data["opportunities"]))
