#!/usr/bin/env python3
"""The Google Analytics 4 head block, defined once and shared.

Every generator and scripts/inject-analytics.py import this so that a page
regenerated from a template is byte-identical to a page that was injected in
place. Without a single definition the two paths drift apart and the next full
build shows a spurious diff across thousands of files.

Ordering inside the returned block is load-bearing:

  1. `gtag()` is defined and the Consent Mode v2 defaults are set, inline.
  2. The gtag.js loader is requested.
  3. `gtag('config', ...)` runs.

A Google tag that initialises without seeing a consent default assumes consent
was GRANTED, which is the opposite of what the EEA/UK rules require, so the
default has to be the first Google thing on the page - ahead of the AdSense
loader that callers already emit.

The defaults are scoped to the EEA, the UK and Switzerland by explicit ISO
region codes. Visitors elsewhere are never placed in a denied state, so
measurement still works for the audience that reads these desks. Google's own
CMP (AdSense > Privacy & messaging) sends the matching `consent update` when a
visitor makes a choice; this block only governs the moment before that.

Set `analytics.enabled` to false in site.config.json to emit nothing at all.
"""
from __future__ import annotations

import json
from pathlib import Path

# EEA = EU-27 plus Iceland, Liechtenstein and Norway; then the UK and
# Switzerland. Spelled out because the region parameter takes ISO codes.
CONSENT_REGIONS = (
    "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR", "DE", "GR",
    "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL", "PL", "PT", "RO", "SK",
    "SI", "ES", "SE", "IS", "LI", "NO", "GB", "CH",
)

LOADER_HOST = "googletagmanager.com/gtag/js"

# The site's Content-Security-Policy is `script-src 'self' https:` with no
# 'unsafe-inline' (server/server.js, mirrored in production), so an inline
# bootstrap is blocked by the browser and never executes. Everything therefore
# lives in an external file under /assets/, the same reason home-theme.js and
# lazy-grid.js are external. `connect-src 'self' https:` already permits the
# measurement beacons gtag.js sends.
ASSET_PATH = "assets/gtag-init.js"

_COMMENT = (
    "<!-- Google tag (gtag.js). Consent Mode v2 defaults live in /" + ASSET_PATH + "\n"
    "     because the site CSP is script-src 'self' https: with no unsafe-inline, so\n"
    "     an inline bootstrap would be blocked and never run. Defaults are scoped to\n"
    "     the EEA/UK/CH; visitors elsewhere are unaffected. -->\n"
)


def config(root: Path | None = None) -> dict:
    """The `analytics` block of site.config.json, or {} when absent."""
    root = Path(root) if root else Path(__file__).resolve().parent.parent
    try:
        cfg = json.loads((root / "site.config.json").read_text(encoding="utf-8"))
    except Exception:
        return {}
    return cfg.get("analytics") or {}


def ga_id(root: Path | None = None) -> str:
    an = config(root)
    if not an.get("enabled"):
        return ""
    gid = str(an.get("gaId") or "").strip()
    return gid if gid.startswith("G-") else ""


def asset_js(root: Path | None = None) -> str:
    """Contents of /assets/gtag-init.js, or "" when analytics is off.

    Synchronous and placed ahead of the async gtag loader, so the consent
    default is already queued in dataLayer before gtag.js executes. gtag.js
    drains that queue in order, which is what makes the default arrive first.
    """
    gid = ga_id(root)
    if not gid:
        return ""
    regions = ", ".join("\"" + r + "\"" for r in CONSENT_REGIONS)
    return (
        "/* GA4 bootstrap for " + gid + ". External file on purpose: the site CSP is\n"
        "   script-src 'self' https: with no unsafe-inline, so an inline bootstrap is\n"
        "   blocked and never runs - the same reason home-theme.js is external.\n"
        "   Generated by scripts/analytics_head.py; do not edit by hand. */\n"
        "window.dataLayer = window.dataLayer || [];\n"
        "function gtag() { dataLayer.push(arguments); }\n"
        "/* Consent Mode v2 defaults, scoped to the EEA, UK and Switzerland. A Google\n"
        "   tag that initialises without seeing a default assumes consent was GRANTED.\n"
        "   Google's own CMP (AdSense > Privacy & messaging) sends the matching\n"
        "   consent update once a visitor chooses; this governs the moment before. */\n"
        "gtag('consent', 'default', {\n"
        "  'ad_storage': 'denied',\n"
        "  'ad_user_data': 'denied',\n"
        "  'ad_personalization': 'denied',\n"
        "  'analytics_storage': 'denied',\n"
        "  'wait_for_update': 500,\n"
        "  'region': [" + regions + "]\n"
        "});\n"
        "gtag('js', new Date());\n"
        "gtag('config', '" + gid + "');\n"
    )


def ga_head(root: Path | None = None) -> str:
    """The head block, or "" when analytics is off. Ends with a newline."""
    gid = ga_id(root)
    if not gid:
        return ""
    return (
        _COMMENT
        + '<script src="/' + ASSET_PATH + '"></script>\n'
        + '<script async src="https://www.googletagmanager.com/gtag/js?id=' + gid + '"></script>\n'
    )
