#!/usr/bin/env python3
"""Build the NEXTCLIP 500-title catalogue batch.
Only real, famous titles with verified basic facts (year, country, genre, premise).
Trailers: only verified official IDs are included; everything else stays empty
so the site shows the clean 'Trailer unavailable' state."""
import json, os, re, urllib.request

def verify(vid):
    url = f"https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v={vid}&format=json"
    try:
        with urllib.request.urlopen(url, timeout=8) as r:
            return json.loads(r.read().decode())
    except Exception:
        return None

def norm(s): return re.sub(r'[^a-z0-9]+',' ',s.lower()).strip()

# (id, title, year, genre, country, synopsis, youtubeId_or_None)
# GENRES allowed by the site: Drama, Action, Superhero, Sci-Fi, Horror, Thriller,
# Series, Animation, Anime, Comedy, Crime, Fantasy, War, Romance, Korean
T = []
def add(id, title, year, genre, country, syn, yt=None):
    T.append(dict(id=id, title=title, slug=id, description=syn, year=year,
                  genre=genre, country=country, language="English", status="published",
                  youtubeId=yt, trailer=f"https://www.youtube.com/watch?v={yt}" if yt else None,
                  poster=f"https://i.ytimg.com/vi/{yt}/hqdefault.jpg" if yt else None))

# ============ BATCH A: CLASSIC HOLLYWOOD ============
add("scarface","Scarface",1983,"Crime","United States","Tony Montana rises from immigrant to Miami drug lord — and falls harder than he rose.","7pQQHnqBa2E")
add("apocalypse-now","Apocalypse Now",1979,"War","United States","A captain travels upriver into the Vietnam jungle to find a rogue colonel. Coppola's fever dream of war.","FTjG-Aux_yQ")
add("2001-space-odyssey","2001: A Space Odyssey",1968,"Sci-Fi","United Kingdom","From the dawn of man to Jupiter and beyond — Kubrick's monumental meditation on evolution and artificial intelligence.","oR_e9y-bka0")
add("the-shining","The Shining",1980,"Horror","United Kingdom","A writer, his wife and son winter at the Overlook Hotel — where the walls are alive and something wants the boy.","5Cb3ik6zP2I")
add("goodfellas","Goodfellas",1990,"Crime","United States","Henry Hill's life in the mob, from errand boy to made man to rat. Scorsese's greatest gangster film.")
add("the-departed","The Departed",2006,"Crime","United States","A cop undercover in the mob and a mole in the police play a deadly game of cat and mouse in Boston.")
add("heat","Heat",1995,"Crime","United States","A master thief and a dedicated detective circle each other in Los Angeles. Pacino vs De Niro.")
add("casino","Casino",1995,"Crime","United States","Scorsese's Las Vegas epic about the mob's grip on a casino empire and the greed that destroyed it.")
add("reservoir-dogs","Reservoir Dogs",1992,"Crime","United States","Six criminals meet after a botched heist. One of them is an undercover cop. Tarantino's debut.")
add("godfather-part-ii","The Godfather Part II",1974,"Crime","United States","Michael Corleone consolidates power while the young Vito builds his empire. The greatest sequel ever made.")
add("godfather-part-iii","The Godfather Part III",1990,"Crime","United States","An aging Michael Corleone seeks legitimacy — and the family's sins catch up with him.")
add("silence-of-the-lambs","The Silence of the Lambs",1991,"Thriller","United States","A young FBI trainee must enlist the help of the brilliant, monstrous Hannibal Lecter to catch a serial killer.")
add("zodiac","Zodiac",2007,"Thriller","United States","The hunt for the Zodiac killer as told by the journalists and detectives obsessed with the case.")
add("nightcrawler","Nightcrawler",2014,"Thriller","United States","A desperate man films crime scenes in Los Angeles and discovers the city will pay — whatever it takes.")
add("girl-with-dragon-tattoo","The Girl with the Dragon Tattoo",2011,"Thriller","United States","A journalist and a brilliant hacker investigate a forty-year-old disappearance in Sweden.")
add("good-bad-ugly","The Good, the Bad and the Ugly",1966,"Western","Italy","Three gunslingers race to find buried Confederate gold during the Civil War. The definitive spaghetti western.")
add("once-upon-time-west","Once Upon a Time in the West",1968,"Western","Italy","A harmonica-playing stranger, a widow, and a ruthless killer collide over land and revenge.")
add("full-metal-jacket","Full Metal Jacket",1987,"War","United Kingdom","Boot camp forges Marines — then the Vietnam war breaks them. Kubrick's two-part war masterpiece.")
add("clockwork-orange","A Clockwork Orange",1971,"Sci-Fi","United Kingdom","In a dystopian Britain, a violent delinquent is subjected to an experimental rehabilitation. Kubrick's most controversial film.")
add("dr-strangelove","Dr. Strangelove",1964,"Comedy","United Kingdom","A deranged general starts a nuclear war and the world's leaders try to stop it. Kubrick's cold-war satire.")
add("barry-lyndon","Barry Lyndon",1975,"Drama","United Kingdom","An Irish rogue climbs the 18th-century aristocracy by cunning and marriage — then falls just as hard.")
add("eyes-wide-shut","Eyes Wide Shut",1999,"Thriller","United States","A doctor's night-long odyssey through a secret society after his wife confesses a fantasy. Kubrick's final film.")

# ============ BATCH B: ACTION / ADVENTURE ============
add("die-hard","Die Hard",1988,"Action","United States","A New York cop battles terrorists in a Los Angeles skyscraper on Christmas Eve. The greatest action film ever made.")
add("die-hard-2","Die Hard 2",1990,"Action","United States","John McClane fights terrorists at an airport during a snowstorm on Christmas Eve — again.")
add("die-hard-3","Die Hard: With a Vengeance",1995,"Action","United States","McClane and a reluctant partner race across New York solving a madman's riddles to stop a bombing.")
add("rambo","First Blood",1982,"Action","United States","A Vietnam veteran pushed too far takes on a small town's police force. The one that started it all.")
add("predator","Predator",1987,"Action","United States","Dutch's special-ops team is hunted one by one in the jungle by an invisible alien warrior.")
add("terminator","The Terminator",1984,"Action","United States","A cyborg assassin from the future hunts a woman whose unborn son will save humanity.")
add("terminator-3","Terminator 3: Rise of the Machines",2003,"Action","United States","A female Terminator hunts John Connor in the lead-up to Judgment Day.")
add("rocky","Rocky",1976,"Drama","United States","A Philadelphia club fighter gets a once-in-a-lifetime shot at the heavyweight champion. Stallone's classic.")
add("rocky-2","Rocky II",1979,"Drama","United States","Rocky gets a rematch with Apollo Creed — and the family to fight for.")
add("creed","Creed",2015,"Drama","United States","Adonis Johnson, son of Apollo Creed, asks Rocky to train him. The franchise reborn.")
add("lethal-weapon","Lethal Weapon",1987,"Action","United States","A suicidal detective and a family man become partners in Los Angeles. The buddy-cop template.")
add("top-gun-1986","Top Gun",1986,"Action","United States","Maverick, a cocky Navy fighter pilot, goes to the elite Top Gun school. The original.")
add("speed","Speed",1994,"Action","United States","A bus wired to explode if it drops below 50 mph. Keanu Reeves' breakout action classic.")
add("con-air","Con Air",1997,"Action","United States","A convict on his way home ends up on a prison transport plane hijacked by the worst criminals alive.")
add("face-off","Face/Off",1997,"Action","United States","An FBI agent and a terrorist swap faces — and lives — in John Woo's operatic masterpiece.")
add("the-rock","The Rock",1996,"Action","United States","An FBI chemist and a captured British spy must stop terrorists on Alcatraz.")
add("goldeneye","GoldenEye",1995,"Action","United Kingdom","James Bond returns after the Cold War, hunting a stolen satellite weapon. Pierce Brosnan's debut.")
add("casino-royale-2006","Casino Royale",2006,"Action","United Kingdom","Daniel Craig's Bond is born: brutal, cold, and falling in love. The 007 reboot.")
add("bourne-identity","The Bourne Identity",2002,"Thriller","United States","A man with amnesia and lethal skills must discover who he is — and who wants him dead.")
add("bourne-supremacy","The Bourne Supremacy",2004,"Thriller","United States","Bourne is framed for a murder and drawn back into the conspiracy he escaped.")
add("bourne-ultimatum","The Bourne Ultimatum",2007,"Thriller","United States","Bourne finally learns the truth about Project Treadstone and who he really is.")
add("taken","Taken",2008,"Action","United States","A retired CIA operative has 96 hours to find his kidnapped daughter in Paris. 'I will find you.'")
add("the-transporter","The Transporter",2002,"Action","United States","A professional driver follows three rules — until a package breaks all of them.")
add("equalizer","The Equalizer",2014,"Action","United States","A quiet man with a violent past helps those who can't help themselves. Denzel Washington.")
add("john-wick-2","John Wick: Chapter 2",2017,"Action","United States","John Wick is forced back into the assassin's world to honor an old debt — and the price is enormous.")
add("john-wick-3","John Wick: Chapter 3 – Parabellum",2019,"Action","United States","Excommunicated and hunted by every assassin on Earth, John Wick fights his way out of New York.")
add("atomic-blonde","Atomic Blonde",2017,"Action","United States","A spy's mission in Cold War Berlin — with the most brutal stairwell fight ever filmed.")
add("hard-boiled","Hard Boiled",1992,"Action","Hong Kong","A cop and an undercover agent take on a Triad gun-running operation. John Woo's action peak.")
add("the-matrix-reloaded","The Matrix Reloaded",2003,"Action","United States","Neo, Trinity and Morpheus fight the machines and face the Architect's terrible choice.")
add("the-matrix-revolutions","The Matrix Revolutions",2003,"Action","United States","Neo's final confrontation with Smith — and the truce that ends the war.")
add("the-fugitive","The Fugitive",1993,"Thriller","United States","A wrongly convicted doctor escapes custody to find the man who killed his wife.")
add("in-the-line-of-fire","In the Line of Fire",1993,"Thriller","United States","A Secret Service agent haunted by JFK hunts a new assassin. Clint Eastwood.")
add("speed-2","Speed 2: Cruise Control",1997,"Action","United States","A cruise ship is hijacked — Sandra Bullock and the franchise's worst-reviewed sequel.")
add("x-men","X-Men",2000,"Superhero","United States","Mutants struggle for acceptance while Professor X and Magneto disagree on how. The modern superhero era begins.")
add("x-men-2","X2: X-Men United",2003,"Superhero","United States","Stryker attacks the mutant school, forcing heroes and villains to unite.")
add("x-men-days-of-future-past","X-Men: Days of Future Past",2014,"Superhero","United States","Wolverine travels back to 1973 to prevent a war that will doom mutants.")
add("logan","Logan",2017,"Superhero","United States","An aging Wolverine escorts a young mutant girl across a dying America. The mutant swan song.")
add("deadpool-and-wolverine","Deadpool & Wolverine",2024,"Superhero","United States","Deadpool drags a reluctant Wolverine across the multiverse to save his universe.")

# ============ BATCH C: SERIES (TV) ============
add("breaking-bad","Breaking Bad",2008,"Series","United States","A chemistry teacher with cancer turns to cooking meth — and becomes the monster he feared. Vince Gilligan's masterpiece.")
add("better-call-saul","Better Call Saul",2015,"Series","United States","The origin of Saul Goodman: a small-time lawyer and his brother, six years before Breaking Bad.")
add("game-of-thrones","Game of Thrones",2011,"Series","United States","Noble houses wage war for the Iron Throne while an ancient enemy wakes beyond the Wall.")
add("the-office-us","The Office",2005,"Series","United States","A documentary crew films the everyday absurdity of Dunder Mifflin's Scranton branch.")
add("friends","Friends",1994,"Series","United States","Six friends in New York navigate work, love and coffee. The most-watched sitcom of its era.")
add("seinfeld","Seinfeld",1989,"Series","United States","A show about nothing — four self-absorbed New Yorkers and their trivial disasters.")
add("the-sopranos","The Sopranos",1999,"Series","United States","A New Jersey mob boss struggles to balance his criminal empire and his family — including his mother.")
add("the-wire","The Wire",2002,"Series","United States","Baltimore's drug war told from every side: cops, dealers, politicians, schools and the press.")
add("chernobyl","Chernobyl",2019,"Series","United States","The true story of the 1986 nuclear disaster and the men who paid to contain it.")
add("band-of-brothers","Band of Brothers",2001,"Series","United States","Easy Company's journey from training to the end of World War II in Europe.")
add("true-detective","True Detective",2014,"Series","United States","Two detectives investigate a murder in Louisiana across seventeen years. Season one is a masterpiece.")
add("fargo","Fargo",2014,"Series","United States","Each season, a new crime story unfolds in the frozen Midwest — inspired by the Coen film.")
add("mindhunter","Mindhunter",2017,"Series","United States","FBI agents pioneer criminal profiling by interviewing America's most notorious serial killers.")
add("narcos","Narcos",2015,"Series","United States","The rise and fall of Pablo Escobar and the DEA agents who hunted him.")
add("dark","Dark",2017,"Series","Germany","Four families across four generations — and a time loop that may end the world. Netflix's German masterpiece.")
add("money-heist","Money Heist",2017,"Series","Spain","The Professor and his team rob the Royal Mint of Spain in the most-watched non-English series ever.")
add("peaky-blinders","Peaky Blinders",2013,"Series","United Kingdom","A Birmingham gang family rises after World War I, led by the sharp-dressed Thomas Shelby.")
add("sherlock","Sherlock",2010,"Series","United Kingdom","Benedict Cumberbatch's modern-day Sherlock solves impossible crimes in London.")
add("black-mirror","Black Mirror",2011,"Series","United Kingdom","Each episode a dark new tale about technology and the near future. Charlie Brooker's anthology.")
add("ozark","Ozark",2017,"Series","United States","A financial adviser moves his family to the Ozarks to launder money for a drug cartel.")
add("the-crown","The Crown",2016,"Series","United Kingdom","The reign of Queen Elizabeth II, told across decades of royal and political drama.")
add("stranger-things","Stranger Things",2016,"Series","United States","A boy vanishes in Hawkins, Indiana — and a girl with telekinetic powers appears. The Upside Down is real.")
add("the-100","The 100",2014,"Series","United States","A hundred juvenile delinquents return to Earth 97 years after nuclear war — and find it far from empty.")
add("lost","Lost",2004,"Series","United States","Survivors of a plane crash on a mysterious island where nothing is what it seems.")
add("the-walking-dead","The Walking Dead",2010,"Series","United States","A sheriff's deputy wakes from a coma into a zombie apocalypse and leads a group of survivors.")
add("vikings","Vikings",2013,"Series","Canada","Ragnar Lothbrok rises from farmer to legendary Viking king. History's epic.")
add("the-last-kingdom","The Last Kingdom",2015,"Series","United Kingdom","Uhtred, a Saxon raised by Danes, fights to reclaim his birthright in Alfred's England.")
add("luther","Luther",2010,"Series","United Kingdom","A brilliant, troubled London detective hunts the city's most dangerous criminals. Idris Elba.")
add("bodyguard","Bodyguard",2018,"Series","United Kingdom","A war veteran assigned to protect a controversial Home Secretary — and becomes a suspect himself.")
add("the-umbrella-academy","The Umbrella Academy",2019,"Series","United States","Forty-three children born on the same day; seven adopted and trained to save the world.")
add("the-sandman","The Sandman",2022,"Series","United States","Dream of the Endless escapes a century of captivity and rebuilds his kingdom. Neil Gaiman's epic.")
add("good-omens","Good Omens",2019,"Series","United Kingdom","An angel and a demon team up to stop the apocalypse they're supposed to start.")
add("succession","Succession",2018,"Series","United States","The Roy family battles for control of a global media empire as their father's health fails.")
add("the-white-lotus","The White Lotus",2021,"Series","United States","Each season, wealthy guests arrive at a luxury resort — and someone doesn't leave alive.")
add("euphoria","Euphoria",2019,"Series","United States","Teenagers navigate drugs, sex and identity in a raw, stylized portrait of high school.")
add("yellowjackets","Yellowjackets",2021,"Series","United States","A girls' soccer team survives a plane crash in the wilderness — and 25 years later, the past returns.")
add("ted-lasso","Ted Lasso",2020,"Series","United States","An American football coach is hired to manage an English soccer club — and wins everyone over with kindness.")
add("severance","Severance",2022,"Series","United States","Lumon employees have their work and personal memories surgically separated — until the severed start asking questions.")
add("all-of-us-are-dead","All of Us Are Dead",2022,"Series","Korea","A high school becomes ground zero for a zombie outbreak and students fight to survive.")
add("the-glory","The Glory",2022,"Series","Korea","A woman who was brutally bullied in school spends years planning a meticulous revenge.")
add("crash-landing-on-you","Crash Landing on You",2019,"Series","Korea","A South Korean heiress crash-lands in North Korea and falls for the soldier who hides her.")
add("extraordinary-attorney-woo","Extraordinary Attorney Woo",2022,"Series","Korea","A brilliant young lawyer on the autism spectrum takes on Korea's most difficult cases.")
add("kingdom","Kingdom",2019,"Series","Korea","In Joseon-era Korea, a crown prince battles a mysterious plague that raises the dead.")
add("sweet-home","Sweet Home",2020,"Series","Korea","Residents of an apartment building fight to survive when their neighbors turn into monsters.")
add("vincenzo","Vincenzo",2021,"Series","Korea","A Korean-Italian mafia consigliere returns to Seoul and takes on a corrupt conglomerate.")
add("my-name","My Name",2021,"Series","Korea","A woman joins a drug cartel and the police to avenge her father's murder.")
add("itaewon-class","Itaewon Class",2020,"Series","Korea","An ex-con opens a bar in Itaewon and builds a business empire to take down a food giant.")
add("miraculous","Miraculous: Tales of Ladybug & Cat Noir",2015,"Series","France","Paris schoolgirls and boys transform into superheroes to fight villainous akumatized citizens.")
add("arcane","Arcane",2021,"Series","United States","Piltover and Zaun, two sisters on opposite sides of a war between magic and machine.")
add("arcane-season-2","Arcane: Season 2",2024,"Series","United States","The final act of the Piltover-Zaun war, with Vi and Jinx on opposite sides of the battlefield.")

# ============ BATCH D: ANIME ============
add("bleach","Bleach",2004,"Anime","Japan","Ichigo Kurosaki becomes a Soul Reaper and defends the living world from evil spirits called Hollows.")
add("dragon-ball-z","Dragon Ball Z",1989,"Anime","Japan","Goku defends Earth from increasingly cosmic threats — Frieza, Cell, Majin Buu. The most famous shonen of all time.")
add("dragon-ball-super","Dragon Ball Super",2015,"Anime","Japan","Goku and Vegeta reach god-level power against Beerus, Zamasu and the Tournament of Power.")
add("dragon-ball-super-broly","Dragon Ball Super: Broly",2018,"Anime","Japan","The Legendary Super Saiyan Broly returns, retold for the modern era with gorgeous animation.")
add("hunter-x-hunter","Hunter x Hunter",2011,"Anime","Japan","Gon Freecss becomes a Hunter to find his father — and encounters an impossible world of Nen, Chimera Ants and more.")
add("hells-paradise","Hell's Paradise",2023,"Anime","Japan","A condemned ninja is sent to a mysterious island to find the Elixir of Life — and face its horrors.")
add("sakamoto-days","Sakamoto Days",2025,"Anime","Japan","The world's greatest hitman retires, gets married, gains weight — and can't stop getting dragged back in.")
add("black-clover","Black Clover",2017,"Anime","Japan","In a world where magic is everything, Asta — born without it — aims to become the Wizard King.")
add("tokyo-ghoul","Tokyo Ghoul",2014,"Anime","Japan","A college student becomes half-ghoul after a transplant and must survive between two worlds.")
add("vinland-saga","Vinland Saga",2019,"Anime","Japan","Thorfinn joins a Viking mercenary crew to avenge his father — and the journey changes everything. A historical masterpiece.")
add("fullmetal-alchemist-brotherhood","Fullmetal Alchemist: Brotherhood",2009,"Anime","Japan","Two brothers search for the Philosopher's Stone to restore what they lost in a forbidden alchemical ritual. Widely called the best anime ever made.")
add("code-geass","Code Geass",2006,"Anime","Japan","A genius student gets a power that lets him command anyone — and uses it to overthrow an empire.")
add("steins-gate","Steins;Gate",2011,"Anime","Japan","A self-proclaimed mad scientist accidentally invents time travel and must face the consequences of changing the past.")
add("re-zero","Re:Zero – Starting Life in Another World",2016,"Anime","Japan","Subaru is transported to a fantasy world with one power: when he dies, time rewinds and he remembers everything.")
add("sword-art-online","Sword Art Online",2012,"Anime","Japan","Players trapped in a VR death game must clear all 100 floors to escape — or die in real life.")
add("mob-psycho-100","Mob Psycho 100",2016,"Anime","Japan","A powerful psychic boy just wants a normal life. From the creator of One Punch Man.")
add("jojo-bizarre-adventure","JoJo's Bizarre Adventure",2012,"Anime","Japan","Generations of the Joestar family battle supernatural threats with the power of Stands.")
add("spy-x-family","Spy x Family",2022,"Anime","Japan","A spy, an assassin and a telepath form a fake family — each hiding their true identity from the others.")
add("frieren","Frieren: Beyond Journey's End",2023,"Anime","Japan","An elf mage outlives her adventuring party and journeys to understand the humans she loved.")
add("apothecary-diary","The Apothecary Diaries",2023,"Anime","Japan","A poison-testing girl in the imperial court solves medical mysteries with wit and chemistry.")
add("kaiju-no-8","Kaiju No. 8",2024,"Anime","Japan","A man who dreams of joining the anti-kaiju defense force becomes a kaiju himself.")
add("dandadan","Dandadan",2024,"Anime","Japan","A boy who believes in ghosts and a girl who believes in aliens team up — and both are right.")
add("mashle","Mashle: Magic and Muscles",2023,"Anime","Japan","In a world ruled by magic, a boy with impossible muscles punches his way to the top.")
add("blue-lock","Blue Lock",2022,"Anime","Japan","Three hundred strikers compete in a ruthless program to create Japan's ultimate egoist forward.")
add("haikyuu","Haikyu!!",2014,"Anime","Japan","A short volleyball player with a huge jump joins his school's team and aims for nationals.")
add("kuroko-basketball","Kuroko's Basketball",2012,"Anime","Japan","The phantom sixth man of a legendary team returns to high school basketball with a new teammate.")
add("slam-dunk","Slam Dunk",1993,"Anime","Japan","A delinquent joins his school's basketball team for a girl — and discovers a passion.")
add("fire-force","Fire Force",2019,"Anime","Japan","Special firefighters battle spontaneous human combustion in a world where flames are the enemy.")
add("soul-eater","Soul Eater",2008,"Anime","Japan","Weapon and meister pairs hunt evil souls at Death Weapon Meister Academy.")
add("fairy-tail","Fairy Tail",2009,"Anime","Japan","The wizards of the Fairy Tail guild take on impossible jobs — with friendship as their real power.")
add("seven-deadly-sins","The Seven Deadly Sins",2014,"Anime","Japan","A princess recruits seven legendary knights to save the kingdom of Britannia.")
add("slime","That Time I Got Reincarnated as a Slime",2018,"Anime","Japan","A man reincarnates as a slime with the power to absorb anything — and builds a monster nation.")
add("overlord","Overlord",2015,"Anime","Japan","A powerful wizard stays logged into a dying game and rules the world as its new overlord.")
add("kaguya-sama","Kaguya-sama: Love Is War",2019,"Anime","Japan","Two geniuses who love each other refuse to confess — it's a battle of wits and pride.")
add("horimiya","Horimiya",2021,"Anime","Japan","A popular girl and a quiet boy discover each other's hidden sides. A warm, funny romance.")
add("toradora","Toradora!",2008,"Anime","Japan","A gentle giant and a tiny dragon team up to help each other win their crushes.")
add("violet-evergarden","Violet Evergarden",2018,"Anime","Japan","A former child soldier becomes an Auto Memory Doll, writing letters that help others — and learning what love means.")
add("your-lie-in-april","Your Lie in April",2014,"Anime","Japan","A pianist who can't hear his own music meets a free-spirited violinist who changes everything.")
add("a-silent-voice","A Silent Voice",2016,"Anime","Japan","A former bully seeks redemption with the deaf girl he tormented. One of anime's most moving films.")
add("weathering-with-you","Weathering with You",2019,"Anime","Japan","A boy who can make it rain meets a girl who can clear the sky. Makoto Shinkai's follow-up to Your Name.")
add("suzume","Suzume",2022,"Anime","Japan","A girl and a mysterious young man travel Japan closing doors that let disaster through. Makoto Shinkai.")
add("grave-fireflies","Grave of the Fireflies",1988,"Anime","Japan","Two siblings struggle to survive in Japan at the end of World War II. Studio Ghibli's most devastating film.","4vPeTSRd580")
add("totoro","My Neighbor Totoro",1988,"Anime","Japan","Two sisters befriend a gentle forest spirit in the countryside. Ghibli's most beloved film.")
add("howls-moving-castle","Howl's Moving Castle",2004,"Anime","Japan","A young woman cursed into old age finds refuge in a wizard's magical walking castle. Miyazaki.")
add("kikis-delivery","Kiki's Delivery Service",1989,"Anime","Japan","A young witch leaves home to start her own delivery service in a seaside city.")
add("castle-in-sky","Castle in the Sky",1986,"Anime","Japan","A boy and a girl search for the legendary floating city of Laputa. Ghibli's first masterpiece.")
add("nausicaa","Nausicaä of the Valley of the Wind",1984,"Anime","Japan","A princess fights to save her valley and the poisoned world from war and the toxic jungle.")
add("porco-rosso","Porco Rosso",1992,"Anime","Japan","A World War I ace cursed with a pig's face fights air pirates in the Adriatic.")
add("the-wind-rises","The Wind Rises",2013,"Anime","Japan","The fictionalized life of Jiro Horikoshi, designer of the Zero fighter. Miyazaki's farewell (first time).")
add("whisper-heart","Whisper of the Heart",1995,"Anime","Japan","A bookish schoolgirl discovers a boy who shares her dreams — and finds her own path. Ghibli's quiet gem.")
add("paprika","Paprika",2006,"Anime","Japan","A therapist uses a device that lets her enter dreams — until it's stolen. Satoshi Kon's masterpiece.")
add("cowboy-bebop","Cowboy Bebop",1998,"Anime","Japan","Bounty hunters in space, a jazz soundtrack, and one of the greatest endings in anime. 'See you space cowboy.'")
add("samurai-champloo","Samurai Champloo",2004,"Anime","Japan","A waitress hires two swordsmen to find 'the samurai who smells of sunflowers' — hip-hop meets Edo Japan.")
add("gintama","Gintama",2006,"Anime","Japan","An alien-invaded Edo era, a lazy samurai, and the most chaotic comedy in anime.")
add("trigun","Trigun",1998,"Anime","Japan","The pacifist gunslinger Vash the Stampede, worth sixty billion double-dollars, is hunted across a desert planet.")
add("one-piece-film-red","One Piece Film: Red",2022,"Anime","Japan","Uta, the world's greatest diva, reveals her identity at her first live concert — and Luffy's crew is in the crowd.","eU0i7L3cakI")
add("jujutsu-kaisen-0","Jujutsu Kaisen 0",2021,"Anime","Japan","The prequel: Yuta Okkotsu, cursed by his childhood friend's spirit, joins Tokyo Jujutsu High.")
add("demon-slayer-mugen-train","Demon Slayer: Mugen Train",2020,"Anime","Japan","Tanjiro and the Flame Hashira Rengoku board a train where a demon feeds on dreams. The highest-grossing anime film ever.","ATJYac_dORw")
add("look-back","Look Back",2024,"Anime","Japan","Two girls bond over drawing manga — a poignant short from the creator of Chainsaw Man.")

# ============ BATCH E: KOREAN / WORLD CINEMA ============
add("memories-of-murder","Memories of Murder",2003,"Korean","Korea","Two detectives hunt Korea's first serial killer in a small town. Bong Joon-ho's breakthrough.")
add("the-host","The Host",2006,"Korean","Korea","A mutant creature rises from the Han River and takes a family's daughter.")
add("a-bittersweet-life","A Bittersweet Life",2005,"Korean","Korea","A loyal enforcer for a crime boss is undone by one act of mercy. Kim Jee-woon.")
add("i-saw-the-devil","I Saw the Devil",2010,"Korean","Korea","A secret agent hunts the serial killer who murdered his fiancée — and decides to make him suffer.")
add("the-chaser","The Chaser",2008,"Korean","Korea","A pimp-turned-detective hunts a killer using the most efficient method: answering the phone.")
add("the-man-from-nowhere","The Man from Nowhere",2010,"Korean","Korea","A quiet pawnshop owner with a violent past tears through the underworld to save a little girl.")
add("a-taxi-driver","A Taxi Driver",2017,"Korean","Korea","A Seoul taxi driver drives a German journalist into the Gwangju Uprising of 1980.")
add("extreme-job","Extreme Job",2019,"Korean","Korea","A failing narcotics team buys a fried chicken shop as cover — and it becomes the city's best restaurant.")
add("the-housemaid","The Housemaid",2010,"Korean","Korea","A housemaid's affair with her wealthy employer sets off a chain of destruction.")
add("burning","Burning",2018,"Korean","Korea","A delivery man, a mysterious woman, and the rich man who may have taken her. Lee Chang-dong's masterpiece.")
add("decision-to-leave","Decision to Leave",2022,"Korean","Korea","A detective falls for his murder suspect. Park Chan-wook's Cannes-winning romance-noir.")
add("the-handmaiden","The Handmaiden",2016,"Korean","Korea","A con man, a heiress, and the maid sent to deceive her — in 1930s Japanese-occupied Korea. Park Chan-wook.")
add("poetry","Poetry",2010,"Korean","Korea","An elderly woman diagnosed with Alzheimer's writes poetry while confronting her grandson's crime.")
add("shoplifters","Shoplifters",2018,"Japanese","Japan","A poor family surviving on petty theft takes in a freezing little girl. Kore-eda's Palme d'Or winner.")
add("drive-my-car","Drive My Car",2021,"Japanese","Japan","A theater director grieving his wife finds solace with his young driver. Oscar winner.")
add("perfect-blue","Perfect Blue",1997,"Anime","Japan","A pop idol turned actress is stalked — and reality begins to unravel. Satoshi Kon's debut.")
add("akira","Akira",1988,"Anime","Japan","A biker gang member gains terrifying psychic powers in a neo-Tokyo on the brink of collapse.")
add("battle-royale","Battle Royale",2000,"Japanese","Japan","A class of students is forced to fight to the death on an island. The film that inspired everything.")
add("departures","Departures",2008,"Japanese","Japan","A cellist becomes an undertaker who prepares bodies for their final journey. Oscar winner.")
add("tokyo-story","Tokyo Story",1953,"Japanese","Japan","An aging couple visits their grown children, who are too busy for them. Ozu's greatest film.")
add("rashomon","Rashomon",1950,"Japanese","Japan","A crime told from four conflicting perspectives. Kurosawa's landmark of world cinema.")
add("seven-samurai","Seven Samurai",1954,"Japanese","Japan","Seven ronin defend a village from bandits. Kurosawa's masterpiece — remade as The Magnificent Seven.")
add("hero-2002","Hero",2002,"Chinese","China","A nameless warrior tells the King of Qin the story of three assassins — and nothing is what it seems. Zhang Yimou's visual masterpiece.")
add("crouching-tiger","Crouching Tiger, Hidden Dragon",2000,"Chinese","Taiwan","A stolen sword, hidden warriors and impossible martial arts. Ang Lee's Oscar-winning wuxia.")
add("house-flying-daggers","House of Flying Daggers",2004,"Chinese","China","A blind dancer and a policeman are entangled in a rebellion. Zhang Yimou.")
add("wandering-earth","The Wandering Earth",2019,"Chinese","China","Earth is pushed out of the solar system by giant engines — and humanity fights to survive the journey.")
add("wandering-earth-2","The Wandering Earth II",2023,"Chinese","China","The prequel: how the planetary engines were built before the great migration began.")
add("ip-man","Ip Man",2008,"Chinese","Hong Kong","The true story of Ip Man, Wing Chun grandmaster and mentor of Bruce Lee. Donnie Yen.")
add("ip-man-2","Ip Man 2",2010,"Chinese","Hong Kong","Ip Man defends Chinese martial arts against a British boxer in Hong Kong.")
add("wolf-warrior-2","Wolf Warrior 2",2017,"Chinese","China","A Chinese soldier single-handedly takes on mercenaries in Africa. The highest-grossing Chinese film ever.")
add("ne-zha","Ne Zha",2019,"Chinese","China","The mischievous demon child Ne Zha must choose between destruction and heroism. China's animated phenomenon.")
add("red-cliff","Red Cliff",2008,"Chinese","China","The Battle of Red Cliffs, where 100,000 allies held off 800,000. John Woo's epic.")
add("let-bullets-fly","Let the Bullets Fly",2010,"Chinese","China","A bandit and a con man face off as a fake mayor in 1920s China. A wild black-comedy western.")
add("shadow","Shadow",2018,"Chinese","China","A shadow warrior is used as a decoy in a deadly political game. Zhang Yimou's ink-painting epic.")
add("3-idiots","3 Idiots",2009,"Indian","India","Two friends search for their brilliant, missing classmate — and relive a college friendship that defied the system.")
add("dangal","Dangal",2016,"Indian","India","A former wrestler trains his daughters to become world champions against a system that says girls can't.")
add("baahubali","Baahubali: The Beginning",2015,"Indian","India","An epic of war, revenge and a question the whole nation asked: Why did Kattappa kill Baahubali?")
add("baahubali-2","Baahubali 2: The Conclusion",2017,"Indian","India","The answer to the greatest question in Indian cinema — and the conclusion of the epic.")
add("rrr","RRR",2022,"Indian","India","Two revolutionaries, one colonial oppressor, and the most spectacular action in Indian cinema. S.S. Rajamouli.")
add("gully-boy","Gully Boy",2019,"Indian","India","A street rapper from Dharavi finds his voice. Ranveer Singh, Zoya Akhtar.")
add("pathaan","Pathaan",2023,"Indian","India","A disavowed Indian agent returns to stop a private terror group. Shah Rukh Khan's mega-comeback.")
add("jawan","Jawan",2023,"Indian","India","A vigilante and his father wage war on corruption across India. Shah Rukh Khan, Atlee.")
add("kgf-2","KGF: Chapter 2",2022,"Indian","India","Rocky rises to rule the Kolar Gold Fields — and takes on the whole country. Yash.")
add("pushpa","Pushpa: The Rise",2021,"Indian","India","A daily-wage laborer becomes the king of red sandalwood smuggling. Allu Arjun.")
add("pk","PK",2014,"Indian","India","An alien stranded on Earth questions the world's religions. Aamir Khan's comedy-drama.")
add("dhoom-3","Dhoom 3",2013,"Indian","India","A circus acrobat turns to robbery to avenge his father. Aamir Khan, Aishwarya Rai.")
add("bajrangi-bhaijaan","Bajrangi Bhaijaan",2015,"Indian","India","A devout Hanuman devotee crosses the border to return a mute Pakistani girl to her family. Salman Khan's best.")
add("uri","Uri: The Surgical Strike",2019,"Indian","India","The true story of India's 2016 surgical strike across the Line of Control.")
add("stree","Stree",2018,"Indian","India","A town haunted by a witch who only takes men who don't respect women. Indian horror-comedy done right.")
add("kabir-singh","Kabir Singh",2019,"Indian","India","A brilliant surgeon destroys his life and career over a broken heart. Controversial and enormous.")
add("gangs-of-wasseypur","Gangs of Wasseypur",2012,"Indian","India","Three generations of a coal-mining family wage war over Wasseypur. Anurag Kashyap's crime epic.")
add("the-lunchbox","The Lunchbox",2013,"Indian","India","A wrong-delivered lunchbox sparks a correspondence between a lonely housewife and a widower.")
add("pather-panchali","Pather Panchali",1955,"Indian","India","A boy grows up in a Bengali village. Satyajit Ray's debut — the film that defined Indian cinema.")
add("sholay","Sholay",1975,"Indian","India","Two petty criminals are hired to capture a ruthless bandit. The definitive Hindi classic.")
add("lagaan","Lagaan",2001,"Indian","India","Villagers challenge their British rulers to a game of cricket to escape crippling taxes. Oscar-nominated.")
add("queen","Queen",2013,"Indian","India","A jilted bride goes on her honeymoon alone to Paris and Amsterdam — and finds herself. Kangana Ranaut.")
add("andhadhun","Andhadhun",2018,"Indian","India","A blind pianist witnesses a murder — or does he? The twistiest thriller in Indian cinema.")
add("drishyam","Drishyam",2015,"Indian","India","A common man's family accidentally commits a crime — and he builds a perfect alibi to protect them.")
add("sairat","Sairat",2016,"Indian","India","An upper-caste girl and a lower-caste boy fall in love in rural Maharashtra. A devastating romance.")
add("masaan","Masaan",2015,"Indian","India","Life, death, love and caste on the ghats of Varanasi. Anurag Kashyap-produced gem.")
add("kantara","Kantara",2022,"Indian","India","A village ritual, a demi-god, and a man caught between land and spirit. Rishab Shetty's phenomenon.")
add("vikram-vedha","Vikram Vedha",2017,"Indian","India","A police officer and a gangster trade stories — and truths — in a battle of wits.")
add("tumbbad","Tumbbad",2018,"Indian","India","A man's greed leads him to a cursed treasure in a decaying village. Indian folk-horror masterpiece.")
add("super-deluxe","Super Deluxe",2019,"Indian","India","Four interlocking stories over one day in Chennai. Bold, dark and unforgettable.")
add("the-great-indian-kitchen","The Great Indian Kitchen",2021,"Indian","India","A newly married woman discovers her life has been reduced to the kitchen. A quiet feminist thunderclap.")
add("court","Court",2014,"Indian","India","An aging folk singer is charged with abetment to suicide — and the absurd machinery of justice grinds on.")
add("udaan","Udaan",2010,"Indian","India","A teenage boy escapes a brutal boarding school and returns to a controlling father. Vikramaditya Motwane.")
add("haider","Haider",2014,"Indian","India","Shakespeare's Hamlet reimagined in conflict-torn Kashmir. Vishal Bhardwaj.")
add("article-15","Article 15",2019,"Indian","India","A cop confronts the caste system after the disappearance of two tribal girls. Ayushmann Khurrana.")
add("kaaka-muttai","Kaaka Muttai",2014,"Indian","India","Two slum brothers dream of tasting pizza for the first time. Tamil gem.")
add("the-wedding-party","The Wedding Party",2016,"Nigerian","Nigeria","A lavish Lagos wedding escalates into chaos. The Nollywood blockbuster that broke records.")
add("lionheart","Lionheart",2018,"Nigerian","Nigeria","Adaeze steps in to run her father's transport company in a man's world. Genevieve Nnaji's directorial debut.")
add("king-of-boys","King of Boys",2018,"Nigerian","Nigeria","Alhaja Eniola Salami, a powerful Lagos political godmother, fights to keep her empire. Kemi Adetiba.")
add("the-black-book","The Black Book",2023,"Nigerian","Nigeria","A deacon turned vigilante hunts the corrupt elite after his daughter's murder. Netflix's Nollywood hit.")
add("anikulapo","Aníkúlápó",2022,"Nigerian","Nigeria","A traveler gains the power of resurrection from a mystical bird — and pays the price. Kunle Afolayan.")
add("mami-wata","Mami Wata",2023,"Nigerian","Nigeria","A village's faith in its water-goddess intermediary is tested when outsiders arrive. C.J. Obasi.")
add("gangs-of-lagos","Gangs of Lagos",2023,"Nigerian","Nigeria","A group of friends rise through Lagos's underworld, shaped by a festival that hides dark secrets. Jade Osiberu.")
add("93-days","93 Days",2016,"Nigerian","Nigeria","The true story of Nigerian doctors who stopped the 2014 Ebola outbreak. Steve Gukas.")
add("october-1","October 1",2014,"Nigerian","Nigeria","A detective investigates a series of murders in a village on the eve of Nigeria's independence. Kunle Afolayan.")
add("the-figurine","The Figurine",2009,"Nigerian","Nigeria","Two friends find a mystical figurine that brings fortune — and doom. Kunle Afolayan's breakthrough.")
add("half-yellow-sun","Half of a Yellow Sun",2013,"Nigerian","Nigeria","The Biafran war tears apart a family and their country. Based on Chimamanda Ngozi Adichie's novel.")
add("citation","Citation",2020,"Nigerian","Nigeria","A female student takes on a university professor who preys on students. Kunle Afolayan.")
add("eyimofe","Eyimofe",2020,"Nigerian","Nigeria","Two Lagos residents chase a better life abroad, one step at a time. The Co-Directors' festival darling.")
add("brotherhood","Brotherhood",2022,"Nigerian","Nigeria","Twin brothers end up on opposite sides of the law in Lagos's underworld. Jade Osiberu.")
add("merry-men","Merry Men",2018,"Nigerian","Nigeria","Four wealthy Lagos playboys become unlikely vigilantes. Ayo Makun's hit comedy.")
add("the-milkmaid","The Milkmaid",2020,"Nigerian","Nigeria","Two Fulani sisters are torn apart by extremism. Nigeria's first Oscar-submitted film in years.")
add("a-tribe-called-judah","A Tribe Called Judah",2023,"Nigerian","Nigeria","A mother and her five sons navigate crime and family in Lagos. Funke Akindele's record-breaker.")
add("swallow","Swallow",2021,"Nigerian","Nigeria","A woman's desperation pushes her into drug mule work. Kunle Afolayan, Netflix.")
add("living-in-bondage","Living in Bondage: Breaking Free",2019,"Nigerian","Nigeria","The sequel to Nollywood's most famous film about ambition and diabolical sacrifice.")
add("far-from-home","Far From Home",2022,"Nigerian","Nigeria","A young man's dreams are derailed when his parents die — and he discovers a dangerous inheritance. Netflix.")
add("shanty-town","Shanty Town",2023,"Nigerian","Nigeria","Lagos's underworld, sex workers and a politician's web of power. Netflix series.")
add("blood-sisters","Blood Sisters",2022,"Nigerian","Nigeria","Two best friends are bound by a terrible secret after a wedding goes wrong. Netflix thriller.")
add("nneka-pretty-serpent","Nneka the Pretty Serpent",2020,"Nigerian","Nigeria","A mermaid's daughter returns to the human world to avenge her mother. Idris Elba presents.")
add("the-intouchables","The Intouchables",2011,"French","France","A paralyzed aristocrat hires a young caregiver from the projects — and they change each other's lives. The French phenomenon.")
add("amelie","Amélie",2001,"French","France","A shy waitress secretly improves the lives of everyone in Montmartre. A candy-colored masterpiece.")
add("la-haine","La Haine",1995,"French","France","Twenty-four hours in the lives of three friends after a riot in the Paris banlieues.")
add("the-lives-of-others","The Lives of Others",2006,"German","Germany","A Stasi agent spies on a playwright and is changed by what he hears. Oscar winner.")
add("run-lola-run","Run Lola Run",1998,"German","Germany","Lola has 20 minutes and three chances to save her boyfriend's life.")
add("downton-abbey","Downton Abbey",2010,"Series","United Kingdom","The Crawley family and their servants navigate life in an English country house across the 20th century.")
add("the-prestige","The Prestige",2006,"Thriller","United Kingdom","Two rival magicians escalate their obsession until it destroys everything. Nolan's best-kept secret.")
add("memento","Memento",2000,"Thriller","United States","A man with no short-term memory hunts his wife's killer using notes and tattoos. Nolan backwards.")
add("the-martian","The Martian",2015,"Sci-Fi","United States","An astronaut stranded on Mars must science his way home. Ridley Scott, Matt Damon.")
add("arrival","Arrival",2016,"Sci-Fi","United States","A linguist races to communicate with alien visitors — and discovers time is not what she thought.")
add("gravity","Gravity",2013,"Sci-Fi","United Kingdom","Two astronauts, one disaster, zero gravity. Alfonso Cuarón's space thriller.")
add("interstellar","Interstellar",2014,"Sci-Fi","United States","A farmer turned pilot crosses a wormhole to find humanity a new home — while his daughter waits on Earth.")
add("the-martian","The Martian",2015,"Sci-Fi","United States","Mark Watney is stranded on Mars. His plan: science his way home.")
add("mad-max-fury-road","Mad Max: Fury Road",2015,"Action","Australia","Furiosa escapes the tyrant Immortan Joe with his five wives — and Max rides along. Two hours of the best action ever filmed.")
add("mad-max","Mad Max",1979,"Action","Australia","A highway cop becomes a road warrior in a collapsing Australia. The film that started it all.")
add("the-road","The Road",2009,"Drama","United States","A father and son walk through an ash-covered America toward the coast. Cormac McCarthy's novel.")
add("children-of-men","Children of Men",2006,"Sci-Fi","United Kingdom","The last pregnant woman on Earth must be protected in a world that has lost all hope.")
add("eternal-sunshine","Eternal Sunshine of the Spotless Mind",2004,"Romance","United States","A couple erase each other from their memories — and fall in love again in the process.")
add("before-sunrise","Before Sunrise",1995,"Romance","United States","Two strangers spend one night walking and talking through Vienna. The Before trilogy begins.")
add("lost-in-translation","Lost in Translation",2003,"Romance","United States","Two lonely Americans connect in a Tokyo hotel. Sofia Coppola's Oscar winner.")
add("the-notebook","The Notebook",2004,"Romance","United States","A man reads their love story to a woman who forgets him every day. The tearjerker of a generation.")
add("la-la-land","La La Land",2016,"Romance","United States","A jazz pianist and an actress chase their dreams in Los Angeles — and love each other along the way.")
add("crazy-rich-asians","Crazy Rich Asians",2018,"Romance","United States","An American woman meets her boyfriend's impossibly wealthy Singaporean family.")
add("call-me-by-your-name","Call Me by Your Name",2017,"Romance","United States","A summer in Italy, a peach, and a love that changes everything. Luca Guadagnino.")
add("the-shape-of-water","The Shape of Water",2017,"Fantasy","United States","A mute cleaner falls in love with an amphibious creature held in a secret lab. Guillermo del Toro's Oscar winner.")
add("pan-labyrinth","Pan's Labyrinth",2006,"Fantasy","Spain","A girl in Franco's Spain escapes into a dark fairy-tale labyrinth. Del Toro's masterpiece.")
add("stardust","Stardust",2007,"Fantasy","United States","A young man crosses a wall into a magical kingdom to win a fallen star. Neil Gaiman.")
add("the-princess-bride","The Princess Bride",1987,"Fantasy","United States","Fencing, fighting, true love and revenge — as told by a grandfather to his sick grandson.")
add("willow","Willow",1988,"Fantasy","United States","A reluctant farmer must protect a baby destined to defeat an evil queen. George Lucas.")
add("the-labyrinth","Labyrinth",1986,"Fantasy","United Kingdom","A girl must solve a maze to rescue her baby brother from the Goblin King. David Bowie.")
add("the-witch","The Witch",2015,"Horror","United States","A Puritan family banished from their colony is haunted by something in the woods. Robert Eggers' debut.")
add("midsommar","Midsommar",2019,"Horror","United States","A grieving woman joins a Swedish midsummer festival that becomes a nightmare. Ari Aster.")
add("the-nun","The Nun",2018,"Horror","United States","A priest and a novice investigate the death of a nun — and find the Conjuring universe's darkest evil.")
add("insidious","Insidious",2010,"Horror","United States","A family's son falls into a coma — and something from another dimension is trying to take him.")
add("the-conjuring","The Conjuring",2013,"Horror","United States","The Warrens investigate a farmhouse with a witch in the woods and a wardrobe to nowhere.")
add("sinister","Sinister",2012,"Horror","United States","A true-crime writer finds home movies that show his family's future murders.")
add("babadook","The Babadook",2014,"Horror","Australia","A mother and son are haunted by a monster from a children's book. The grief-horror masterpiece.")
add("hereditary","Hereditary",2018,"Horror","United States","After the matriarch dies, the Graham family unravels as a cult's plan comes to light.")
add("get-out","Get Out",2017,"Horror","United States","A Black man meets his white girlfriend's family — and they're too welcoming. Jordan Peele.")
add("us","Us",2019,"Horror","United States","A family vacation meets their doppelgängers — who want everything they have. Jordan Peele.")
add("nope","Nope",2022,"Horror","United States","A horse ranch, a UFO and a question: what do you feed a predator in the sky? Jordan Peele.")
add("the-substance","The Substance",2024,"Horror","United States","A fading celebrity injects a black-market cell-replicating substance — and meets a younger version of herself. Demi Moore.")
add("longlegs","Longlegs",2024,"Horror","United States","An FBI agent hunts a serial killer whose crimes defy explanation — and whose trail leads to her. Nicolas Cage.")
add("smile","Smile",2022,"Horror","United States","A curse passes through smiles, and a doctor witnesses it firsthand. The surprise horror hit.")
add("talk-to-me","Talk to Me",2023,"Horror","Australia","Teenagers contact spirits using an embalmed hand — until something comes through that won't leave. A24.")
add("it-follows","It Follows",2014,"Horror","United States","A supernatural entity follows its victim — slowly, relentlessly, forever. The modern horror classic.")
add("the-ring","The Ring",2002,"Horror","United States","Seven days after watching a cursed videotape, the phone rings. The American remake that terrified a generation.")
add("the-grudge","The Grudge",2004,"Horror","United States","Anyone who enters the house inherits its curse. The American Ju-On remake.")
add("saw","Saw",2004,"Horror","United States","Two men wake chained in a bathroom with a dead man between them and a tape that says: play. The trap franchise begins.")
add("scream","Scream",1996,"Horror","United States","A masked killer terrorizes a small town — and the teens know the rules to survive. Wes Craven.")
add("halloween","Halloween",1978,"Horror","United States","Michael Myers returns to Haddonfield on Halloween night. The slasher template.")
add("the-exorcist","The Exorcist",1973,"Horror","United States","A young girl is possessed, and two priests perform the most famous exorcism in cinema. Still terrifying.")
add("night-living-dead","Night of the Living Dead",1968,"Horror","United States","Strangers barricade themselves in a farmhouse as the dead rise. The zombie genre begins. Public domain.")
add("carrie","Carrie",1976,"Horror","United States","A bullied telekinetic teenager is pushed too far at prom. De Palma, King.")
add("the-thing","The Thing",1982,"Horror","United States","An Antarctic research team is infiltrated by an alien that can imitate anyone. Carpenter's masterpiece.")
add("alien","Alien",1979,"Sci-Fi","United Kingdom","The crew of the Nostromo answers a distress call — and brings the perfect organism aboard.")
add("aliens","Aliens",1986,"Sci-Fi","United States","Ripley returns with a squad of marines to the colony planet. Cameron's action masterpiece.")
add("predator-2","Predator 2",1990,"Action","United States","The Predator hunts in the concrete jungle of Los Angeles.")
add("alien-3","Alien 3",1992,"Sci-Fi","United States","Ripley crashes on a prison planet — with an Alien loose in the vents.")
add("alien-resurrection","Alien: Resurrection",1997,"Sci-Fi","United States","Ripley is cloned, and the Xenomorphs are back for the bloodiest chapter.")
add("prometheus","Prometheus",2012,"Sci-Fi","United States","A crew follows star maps to the Engineers — and finds the origin of humanity and its destruction.")
add("blade-runner","Blade Runner",1982,"Sci-Fi","United States","A blade runner hunts rogue replicants in rain-soaked Los Angeles. Ridley Scott's masterpiece.")
add("total-recall","Total Recall",1990,"Sci-Fi","United States","A man's dream vacation to Mars may be real — or his memories may be implants. Schwarzenegger, Verhoeven.")
add("robocop","RoboCop",1987,"Sci-Fi","United States","A dead cop is rebuilt as a cyborg law enforcer in a corporatized Detroit. Verhoeven's satire.")
add("the-fifth-element","The Fifth Element",1997,"Sci-Fi","France","A cab driver and the perfect being must save Earth from an ancient evil. Besson, Willis, Jovovich.")
add("minority-report","Minority Report",2002,"Sci-Fi","United States","Precrime stops murder before it happens — until the system accuses its own architect.")
add("i-robot","I, Robot",2004,"Sci-Fi","United States","A detective who hates robots investigates one that broke the Three Laws. Will Smith.")
add("war-of-the-worlds","War of the Worlds",2005,"Sci-Fi","United States","Tripods emerge from the earth and humanity flees. Spielberg's alien invasion.")
add("district-9","District 9",2009,"Sci-Fi","South Africa","Aliens are confined to a Johannesburg slum — and one man begins to change. Neill Blomkamp.")
add("edge-of-tomorrow","Edge of Tomorrow",2014,"Sci-Fi","United States","A soldier dies and relives the same battle until he can win the war. Cruise, Blunt.")
add("looper","Looper",2012,"Sci-Fi","United States","A hitman whose targets come from the future must kill his older self. Rian Johnson.")
add("ex-machina","Ex Machina",2014,"Sci-Fi","United Kingdom","A programmer is invited to test a female AI — and the test becomes a battle of minds. Garland.")
add("her","Her",2013,"Romance","United States","A lonely man falls in love with an operating system. Spike Jonze's Oscar winner.")
add("moon","Moon",2009,"Sci-Fi","United Kingdom","A lone worker on a lunar station discovers he is not as alone as he thinks. Sam Rockwell.")
add("gravity","Gravity",2013,"Sci-Fi","United States","Two astronauts stranded in orbit must find a way home. Cuarón.")
add("jupiter-ascending","Jupiter Ascending",2015,"Sci-Fi","United States","A janitor is revealed to be the rightful queen of the universe. The Wachowskis.")
add("cloud-atlas","Cloud Atlas",2012,"Sci-Fi","United States","Six stories across five centuries, connected by acts of kindness and cruelty.")
add("inception","Inception",2010,"Sci-Fi","United States","A thief who steals secrets from dreams is offered the impossible: plant an idea. Nolan.")
add("tenet","Tenet",2020,"Sci-Fi","United States","Time flows backward. A secret agent must prevent World War III — from the future.")
add("dune","Dune",2021,"Sci-Fi","United States","House Atreides takes control of Arrakis and walks into a trap. Villeneuve's epic begins.")
add("blade-runner-2049","Blade Runner 2049",2017,"Sci-Fi","United States","A new blade runner uncovers a secret that could end civilization. Villeneuve, Deakins.")
add("everything-everywhere","Everything Everywhere All at Once",2022,"Sci-Fi","United States","A laundromat owner is pulled into the multiverse to save everything — and reconnect with her family. The Oscar winner.")
add("swiss-army-man","Swiss Army Man",2016,"Comedy","United States","A castaway befriends a corpse with incredible powers. The weirdest, sweetest film of its year.")
add("grand-budapest","The Grand Budapest Hotel",2014,"Comedy","United States","A legendary concierge and his lobby boy are caught in a caper across a fictional European nation. Wes Anderson.")
add("the-grand-budapest-hotel","The Grand Budapest Hotel",2014,"Comedy","United States","A concierge, a stolen painting, and a hotel caught in a war. Wes Anderson's masterpiece.")
add("little-miss-sunshine","Little Miss Sunshine",2006,"Comedy","United States","A dysfunctional family road-trips to a beauty pageant in a VW bus. The indie classic.")
add("superbad","Superbad",2007,"Comedy","United States","Two best friends try to get alcohol for a party — and one night changes everything. Apatow.")
add("step-brothers","Step Brothers",2008,"Comedy","United States","Two 40-year-old man-children are forced to live together when their parents marry.")
add("anchorman","Anchorman",2004,"Comedy","United States","San Diego's top newsman faces a female rival and a battle of the anchormen. Will Ferrell.")
add("napoleon-dynamite","Napoleon Dynamite",2004,"Comedy","United States","A high school nobody helps his friend run for class president. The quotable indie phenomenon.")
add("the-hangover","The Hangover",2009,"Comedy","United States","Three friends wake after a wild bachelor party in Vegas with no memory — and no groom.")
add("bridesmaids","Bridesmaids",2011,"Comedy","United States","A maid of honor's life falls apart while planning her best friend's wedding. Melissa McCarthy's breakout.")
add("knives-out","Knives Out",2019,"Comedy","United States","A famous novelist dies and Benoit Blanc investigates a family of terrible people.")
add("glass-onion","Glass Onion: A Knives Out Mystery",2022,"Comedy","United States","Benoit Blanc goes to a billionaire's private island for a murder-mystery weekend — and gets one.")
add("the-other-guys","The Other Guys",2010,"Comedy","United States","Two desk-bound NYPD detectives stumble onto a massive financial crime. Ferrell, Wahlberg.")
add("21-jump-street","21 Jump Street",2012,"Comedy","United States","Two cops go back to high school undercover. The best movie based on a TV show.")
add("blockers","Blockers",2018,"Comedy","United States","Three parents try to stop their daughters from losing their virginity on prom night.")
add("booksmart","Booksmart",2019,"Comedy","United States","Two academic overachievers party for the first time on the eve of graduation.")
add("good-boys","Good Boys",2019,"Comedy","United States","Three sixth-graders skip school for the first time. Superbad for kids — literally.")
add("jojo-rabbit","Jojo Rabbit",2019,"Comedy","Germany","A Hitler Youth member's imaginary friend is Hitler — and his mother is hiding a Jewish girl. Taika Waititi.")
add("what-we-do-in-shadows","What We Do in the Shadows",2014,"Comedy","New Zealand","A documentary crew follows vampire flatmates in Wellington. Taika Waititi, Jemaine Clement.")
add("airplane","Airplane!",1980,"Comedy","United States","An ex-fighter pilot must land a plane when the crew falls ill. The joke-density record holder.")
add("blazing-saddles","Blazing Saddles",1974,"Comedy","United States","A Black sheriff is sent to save a town that doesn't want him. Mel Brooks.")
add("ghostbusters","Ghostbusters",1984,"Comedy","United States","Three scientists start a paranormal extermination business — just in time for the apocalypse.")
add("back-to-the-future","Back to the Future",1985,"Sci-Fi","United States","A teenager is accidentally sent to 1955 in a DeLorean time machine and must ensure his parents fall in love.")
add("back-to-the-future-2","Back to the Future Part II",1989,"Sci-Fi","United States","Marty travels to 2015 and back — and alters the timeline catastrophically.")
add("back-to-the-future-3","Back to the Future Part III",1990,"Sci-Fi","United States","The DeLorean lands in the Old West, where Doc must be saved from a gunfighter.")
add("raiders","Raiders of the Lost Ark",1981,"Action","United States","Indiana Jones races the Nazis to the Ark of the Covenant. The adventure genre perfected.")
add("temple-of-doom","Indiana Jones and the Temple of Doom",1984,"Action","United States","Indy, Willie and Short Round survive cults, mines and the worst dinner ever.")
add("last-crusade","Indiana Jones and the Last Crusade",1989,"Action","United States","Indy searches for the Holy Grail with his father. The best of the trilogy.")
add("jurassic-world","Jurassic World",2015,"Action","United States","The park is open — and a new hybrid dinosaur escapes. The franchise reborn.")
add("jurassic-world-fallen-kingdom","Jurassic World: Fallen Kingdom",2018,"Action","United States","Dinosaurs are evacuated from an erupting Isla Nublar — and sold to the highest bidder.")
add("kong-skull-island","Kong: Skull Island",2017,"Action","United States","A 1970s expedition discovers Kong and a prehistoric island. The MonsterVerse begins.")
add("godzilla-2014","Godzilla",2014,"Action","United States","Godzilla rises to restore balance against the MUTOs. Gareth Edwards' MonsterVerse debut.")
add("godzilla-kong","Godzilla vs. Kong",2021,"Action","United States","Two titans fight for supremacy while humanity searches for a hollow-Earth power source.")
add("venom","Venom",2018,"Superhero","United States","A reporter bonds with an alien symbiote. 'We are Venom.'")
add("venom-2","Venom: Let There Be Carnage",2021,"Superhero","United States","Cletus Kasady becomes Carnage — and only Venom can stop him.")
add("morbius","Morbius",2022,"Superhero","United States","A scientist with a rare blood disease experiments on himself — and becomes a living vampire.")
add("madame-web","Madame Web",2024,"Superhero","United States","A paramedic's visions of the future bind her to three young women destined for greatness.")
add("aquaman","Aquaman",2018,"Superhero","United States","The half-human king of Atlantis must unite two worlds. James Wan.")
add("aquaman-2","Aquaman and the Lost Kingdom",2023,"Superhero","United States","Aquaman and his imprisoned brother team up against Black Manta. The DCEU finale.")
add("wonder-woman","Wonder Woman",2017,"Superhero","United States","An Amazon princess leaves paradise to end a war — and discovers its true cost.")
add("wonder-woman-1984","Wonder Woman 1984",2020,"Superhero","United States","A magic stone grants wishes at a terrible price in the 80s.")
add("shazam","Shazam!",2019,"Superhero","United States","A foster kid who says one word becomes an adult superhero. The DCEU's funniest.")
add("the-flash","The Flash",2023,"Superhero","United States","Barry Allen travels back in time and breaks the multiverse. Keaton's Batman returns.")
add("black-adam","Black Adam",2022,"Superhero","United States","An ancient champion wakes in modern Kahndaq with lightning fists. Dwayne Johnson.")
add("suicide-squad","The Suicide Squad",2021,"Superhero","United States","Task Force X is sent to destroy a Nazi-era laboratory. James Gunn's blood-soaked masterpiece.")
add("the-batman","The Batman",2022,"Superhero","United States","In his second year, Batman hunts the Riddler and uncovers Gotham's corruption. Pattinson.")
add("joker","Joker",2019,"Superhero","United States","Arthur Fleck wanted to make people laugh. Gotham made him the punchline. Phoenix.")
add("spider-man","Spider-Man",2002,"Superhero","United States","A bite from a radioactive spider gives Peter Parker power and responsibility. Raimi's classic.")
add("spider-man-2","Spider-Man 2",2004,"Superhero","United States","Peter faces Doctor Octopus — and the cost of being a hero. The best superhero sequel.")
add("spider-man-3","Spider-Man 3",2007,"Superhero","United States","Venom, Sandman and the black suit. The crowded, glorious mess.")
add("amazing-spider-man","The Amazing Spider-Man",2012,"Superhero","United States","The reboot: Peter Parker's parents, Gwen Stacy, and the Lizard.")
add("tasm-2","The Amazing Spider-Man 2",2014,"Superhero","United States","Electro, Harry Osborn and the death that changed everything.")
add("iron-man","Iron Man",2008,"Superhero","United States","Tony Stark builds a suit in a cave and becomes Iron Man. The MCU begins.")
add("iron-man-2","Iron Man 2",2010,"Superhero","United States","Tony faces his legacy, Ivan Vanko and his own mortality. Scarlett Johansson debuts as Black Widow.")
add("iron-man-3","Iron Man 3",2013,"Superhero","United States","Tony hunts the Mandarin after his world is destroyed. Shane Black's Christmas action-comedy.")
add("captain-america","Captain America: The First Avenger",2011,"Superhero","United States","A scrawny kid becomes a super-soldier and fights the Red Skull in World War II.")
add("thor","Thor",2011,"Superhero","United States","The God of Thunder is exiled to Earth without his hammer. Kenneth Branagh.")
add("hulk","The Incredible Hulk",2008,"Superhero","United States","Bruce Banner is hunted while the Abomination rises. Edward Norton.")
add("guardians-2","Guardians of the Galaxy Vol. 2",2017,"Superhero","United States","Star-Lord meets his father — and learns the truth about family. Baby Groot.")
add("ant-man","Ant-Man",2015,"Superhero","United States","A thief becomes a shrinking hero. Paul Rudd, Peyton Reed.")
add("ant-man-2","Ant-Man and the Wasp",2018,"Superhero","United States","Scott Lang and Hope van Dyne shrink to save Janet from the Quantum Realm.")
add("doctor-strange","Doctor Strange",2016,"Superhero","United States","A surgeon discovers the mystic arts and the multiverse. Benedict Cumberbatch.")
add("black-panther","Black Panther",2018,"Superhero","United States","T'Challa returns to Wakanda to claim the throne — and faces Killmonger. Chadwick Boseman.")
add("black-panther-2","Black Panther: Wakanda Forever",2022,"Superhero","United States","Wakanda mourns its king and faces the underwater kingdom of Talokan.")
add("captain-marvel","Captain Marvel",2019,"Superhero","United States","Carol Danvers discovers her past — and her power. The 90s-set MCU entry.")
add("eternals","Eternals",2021,"Superhero","United States","Ten immortals have protected humanity for 7,000 years. Now the Deviants are back.")
add("shang-chi","Shang-Chi and the Legend of the Ten Rings",2021,"Superhero","United States","The Master of Kung Fu is drawn back to his father's criminal empire.")
add("no-way-home","Spider-Man: No Way Home",2021,"Superhero","United States","Peter's identity is revealed, and the multiverse cracks open. Three Spider-Men.")
add("spider-verse","Spider-Man: Into the Spider-Verse",2018,"Superhero","United States","Miles Morales becomes Spider-Man across the multiverse. The animated masterpiece.")
add("wanda-vision","WandaVision",2021,"Series","United States","Wanda builds a perfect sitcom life — but reality keeps bleeding through.")
add("the-falcon-winter-soldier","The Falcon and the Winter Soldier",2021,"Series","United States","Sam Wilson and Bucky Barnes deal with a new Captain America — and a new threat.")
add("loki","Loki",2021,"Series","United States","The God of Mischief joins the TVA to fix the timeline he broke.")
add("hawkeye","Hawkeye",2021,"Series","United States","Clint Barton mentors Kate Bishop through a Christmas in New York.")
add("moon-knight","Moon Knight",2022,"Series","United States","A man with dissociative identity disorder becomes the avatar of an Egyptian god.")
add("she-hulk","She-Hulk: Attorney at Law",2022,"Series","United States","Jennifer Walters, a lawyer who also happens to be a Hulk. Comedy series.")
add("ms-marvel","Ms. Marvel",2022,"Series","United States","A Jersey City teenager gains cosmic powers and becomes the MCU's newest hero.")
add("secret-invasion","Secret Invasion",2023,"Series","United States","Nick Fury discovers Skrulls have infiltrated Earth's highest positions.")
add("loki-season-2","Loki: Season 2",2023,"Series","United States","Loki and the TVA race to save the multiverse from collapse.")
add("the-penguin","The Penguin",2024,"Series","United States","Oswald Cobblepot claws his way to the top of Gotham's underworld after The Batman. Colin Farrell.")
add("agatha","Agatha All Along",2024,"Series","United States","Agatha Harkness and a coven walk the Witches' Road. The WandaVision spin-off.")
add("the-boys-season-2","The Boys: Season 2",2020,"Series","United States","Butcher and the team go after Vought — and the truth about Compound V.")
add("gen-v","Gen V",2023,"Series","United States","College students train to be heroes — with deadly consequences. The Boys spin-off.")
add("invincible","Invincible",2021,"Series","United States","A teenager inherits superpowers from his father — the most powerful being alive. The animated hit.")
add("the-boys-season-3","The Boys: Season 3",2022,"Series","United States","Soldier Boy returns, and Homelander's grip begins to slip.")

# Dedupe by id
seen = set(); out = []
for t in T:
    if t['id'] in seen: continue
    seen.add(t['id']); out.append(t)

print(f"BATCH ENTRIES: {len(out)}")
json.dump(out, open('content/catalogue-batch.json','w'), indent=1, ensure_ascii=False)
