# -*- coding: utf-8 -*-
"""Depth notes, tranche 4 part 2 (Phase 3): appends to guide/recovered pages.
Rendered after ENT_DEPTH_NOTES; each entry carries an external, official or
deterministic-lookup link. Facts kept to well-established, stable claims."""

_IMDB = "https://www.imdb.com/find/?q=%s&s=tt"
_CR = "https://www.crunchyroll.com/search?q=%s"
_NF = "https://www.netflix.com/search?q=%s"
_WS = "https://en.wikipedia.org/wiki/Special:Search?search=%s"

ENT_DEPTH_MORE = {

"anime-canon-and-filler-explained": """<h2>Desk notes: how to actually use the canon/filler split</h2>
<p> filler is not a quality label; it is a production-schedule label. Long-running anime adapt manga that is still being written, so the studio sometimes overtakes the source and must spin original stories to buy the manga time. Knowing which episodes those are protects you from two mistakes: skipping original episodes that are genuinely good, and blaming a show for pacing decisions made years after the scenes you enjoyed.</p>
<p>The practical method the desk uses: for any long series, look up an episode guide on <a href="https://www.crunchyroll.com/search?q=one+piece" rel="noopener">Crunchyroll</a> or a fan-maintained canon list before a marathon, and treat mixed-canon episodes honestly \u2014 many of the best ones are adaptations with connective tissue added. The deeper mechanics of the schedule are in <a href="/entertainment/how-anime-production-committees-work/">how anime production committees work</a>.</p>""",

"anime-seasons-and-cours-explained": """<h2>Desk notes: the calendar is the key to everything else</h2>
<p>Once the cours system clicks, a lot of anime journalism stops being confusing. A cour is a broadcast quarter, roughly eleven to thirteen episodes; shows run one, two or split across quarters, and the four big premiere months \u2014 January, April, July, October \u2014 are why discussion online surges at those moments. It also explains why a promising show sometimes simply stops: its ordered cours ended, and a sequel is a business decision, not a promise.</p>
<p>For picking, the calendar is a tool: a finished one-cour show is a commitment you can verify in advance, which makes it the safest weeknight option, while split cours are the ones to check before starting. Current-season simulcasts sit on <a href="https://www.crunchyroll.com/search?q=season+premiere" rel="noopener">Crunchyroll</a> and similar services; the desk\u2019s <a href="/entertainment/where-to-start-with-long-running-anime/">long-running anime guide</a> covers the other kind of commitment.</p>""",

"best-action-movies-of-all-time": """<h2>Desk notes: what the canon is for</h2>
<p>An all-time action list is not a ranking of explosions; it is an argument about choreography, staging and escalation \u2014 which films still teach an editor or a fight designer something. That is the test every pick above survives: watch the corridor fight, the bus sequence, the stairwell one-take, and you are watching grammar being invented that later films borrowed.</p>
<p>Use the list as a route, not a trophy cabinet: the silent-era and seventies entries show the grammar forming, the eighties and nineties entries industrialise it, and the modern entries quote it. Credits, runtimes and where each film sits in its director\u2019s career are one lookup away on <a href="https://www.imdb.com/find/?q=action" rel="noopener">IMDb</a>, and the desk\u2019s <a href="/entertainment/how-to-pick-a-movie-tonight/">tonight-picking method</a> turns the list into an actual viewing order.</p>""",

"best-anime-movies-of-all-time": """<h2>Desk notes: features are a different sport from series</h2>
<p>The best anime films are not condensed series \u2014 they are the medium\u2019s laboratory, where directors get theatrical budgets and single-story discipline. That is why the list mixes festival auteurs with studio blockbusters without embarrassment: the criterion is what the film does with ninety minutes, not which shelf it came from.</p>
<p>If you are new, the honest route is: one Ghibli, one thriller, one romance, one recent festival pick \u2014 four films, four registers, and you will know your lane. The desk\u2019s <a href="/entertainment/where-to-start-with-ghibli/">Ghibli route</a> and <a href="/entertainment/anime-seasons-and-cours-explained/">cours explainer</a> cover the two biggest follow-up questions. Availability rotates; a search on <a href="https://www.netflix.com/search?q=anime" rel="noopener">Netflix</a> on the night beats any static where-to-watch promise.</p>""",

"best-documentaries-of-all-time": """<h2>Desk notes: how to judge a documentary</h2>
<p>A documentary is an argument made of evidence, and the honest ones show you the seams: who is talking, what the film leaves out, whose camera this is. That is the quiet test behind every pick above \u2014 not \u201cis this true\u201d but \u201cdoes the film let you see how it knows what it claims\u201d.</p>
<p>Two habits make the whole genre better. First, read one thing about the film\u2019s reception after watching, not before \u2014 the debates around a documentary are part of the text. Second, balance the archive-led and verite-led picks deliberately; they exercise different trust muscles. Most of the list rotates through the major streamers \u2014 a search on <a href="https://www.netflix.com/search?q=documentary" rel="noopener">Netflix</a> usually lands several at once \u2014 and the desk\u2019s <a href="/entertainment/best-true-crime-documentaries-to-watch/">true-crime shelf</a> covers the genre\u2019s biggest subdivision separately.</p>""",

"best-films-for-a-group": """<h2>Desk notes: the group-night contract</h2>
<p>Group picking fails for one reason: everyone optimises for their own favourite instead of for the evening. The list above is built to be defensible \u2014 films with a high floor, a brisk pace and nothing that requires a manifesto. That is the contract: nobody\u2019s top five, nobody\u2019s bore-dom, everybody still awake at the credits.</p>
<p>Two logistics notes that matter more than the title. Decide from three, not from the whole list \u2014 decision fatigue kills more group nights than bad films do; the desk\u2019s <a href="/entertainment/how-to-pick-a-movie-tonight/">picking method</a> formalises this. And agree the subtitle question before the menu opens, not during it. For availability, a same-night search on <a href="https://www.netflix.com/search?q=movie" rel="noopener">Netflix</a> or your service of choice settles arguments that taste never will.</p>""",

"best-horror-movies-of-all-time": """<h2>Desk notes: horror\u2019s canon is a conversation across decades</h2>
<p>The horror canon argues with itself: every generation\u2019s landmark is a reply to an earlier one \u2014 the gothic haunted house answered by the suburban one, the slasher answered by the self-aware slasher, the possessed house answered by the possessed family camcorder. Read in order, the list above is that argument; dipped into, each pick still works alone.</p>
<p>The desk\u2019s advice for newcomers: start where your fear actually lives \u2014 dread, jump, body horror or grief \u2014 rather than at the oldest title out of duty. The genre\u2019s modern route in is on the <a href="/entertainment/modern-horror-starter-route/">starter route</a>, and a same-night search on <a href="https://www.netflix.com/search?q=horror" rel="noopener">Netflix</a> will usually surface a respectable slice of the canon. Credits and context are one lookup away on <a href="https://www.imdb.com/find/?q=horror" rel="noopener">IMDb</a>.</p>""",

"best-kdramas-to-start-with": """<h2>Desk notes: why five, and in this order</h2>
<p>A K-drama starter route has one job: teach the genre\u2019s grammar \u2014 the episode rhythm, the cliff architecture, the tone swings \u2014 without demanding prior knowledge. The five above are ordered so each one adds a register the last did not have: the rom-com engine, the prestige thriller, the historical epic, the slow-burn, the ensemble. Finish the route and you can walk into any current show fluently.</p>
<p>Practical notes: episodes run long by network convention \u2014 budget a real hour \u2014 and single-season completion is the norm, so a pick is a contained commitment. The route\u2019s titles sit on the major platforms, starting with a search on <a href="https://www.netflix.com/search?q=korean+drama" rel="noopener">Netflix</a>; the desk\u2019s <a href="/entertainment/kdrama-genres-explained/">genre map</a> tells you which lane to try second.</p>""",

"best-limited-series-to-watch": """<h2>Desk notes: the form\u2019s whole point is the ending</h2>
<p>A limited series is a contract: one story, no season-two escape hatch, the writers must land it. That is why the list above rewards finished runs only \u2014 the form\u2019s promise is the reason to choose it over an open-ended show, and breaking that promise is the one unforgivable sin here.</p>
<p>How to use the list: check the episode count and the runtime before committing, because limited series vary wildly in shape \u2014 four hours and six hours are different evenings. Then watch without the episode-hop: the form is built for accumulation. Most picks rotate between the big platforms; a search on <a href="https://www.netflix.com/search?q=limited+series" rel="noopener">Netflix</a> or your service of choice finds the current home. The desk\u2019s <a href="/entertainment/what-to-watch-in-90-minutes/">90-minute shelf</a> is the same promise at film length.</p>""",

"best-mecha-anime-explained": """<h2>Desk notes: the robot is never just a robot</h2>
<p>Mecha is the medium\u2019s oldest metaphor engine: the giant robot is a conscripted soldier, a trauma response, a national industry or a toy commercial, depending on the decade \u2014 and the list above is deliberately arranged so those registers sit next to each other. The super-robot shows are operas of will; the real-robot shows are wars with supply lines; the deconstructions are about the pilots the first two eras pretended not to see.</p>
<p>If you have never liked mecha, the honest diagnosis is usually a wrong entry point, not the genre: start with the register that matches your taste in drama, not the most famous title. Where the genre sits today, and what is simulcasting, is one search on <a href="https://www.crunchyroll.com/search?q=mecha" rel="noopener">Crunchyroll</a>; the desk\u2019s <a href="/entertainment/shonen-shojo-seinen-explained/">demographics explainer</a> explains the shelving logic behind the lists.</p>""",

"best-romantic-comedies-of-all-time": """<h2>Desk notes: what holds up is the architecture</h2>
<p>The rom-coms that endure are machine-tooled: meet, spark, obstacle, collapse, grand gesture \u2014 and the great ones hide the machinery under performers who make the beats feel improvised. That is the test the list above applies on rewatch: does the joke still land when you know the ending, and does the couple still feel like equals inside the plot?</p>
<p>Watch order advice: alternate the classic screwball entries with the modern replies \u2014 the genre is a conversation, and the modern half quotes the older half constantly. The canon rotates through the streamers; a search on <a href="https://www.netflix.com/search?q=romantic+comedy" rel="noopener">Netflix</a> finds tonight\u2019s slice, and credits are one lookup away on <a href="https://www.imdb.com/find/?q=romantic+comedy" rel="noopener">IMDb</a>. For the non-romantic side of comedy night, the desk\u2019s <a href="/entertainment/best-films-for-a-group/">group-night list</a> covers the shared floor.</p>""",

"best-sci-fi-movies-of-all-time": """<h2>Desk notes: the canon is a history of ideas, not effects</h2>
<p>Science fiction\u2019s all-time list ages better than any other genre\u2019s because its subject is ideas: time, memory, language, power, the machine. Effects date; the questions do not. That is why the picks above interleave silent-era foundations, fifties paranoia, the seventies intellectual blockbusters and the modern arsenal of space films without embarrassment.</p>
<p>The desk\u2019s route advice: pair each classic with its modern reply \u2014 the originals plant the question, the replies show what changed. Context and credits are one lookup on <a href="https://www.imdb.com/find/?q=science+fiction" rel="noopener">IMDb</a>, and most of the list cycles through the major platforms \u2014 a search on <a href="https://www.netflix.com/search?q=sci-fi" rel="noopener">Netflix</a> on the night beats a static where-to-watch list. For the mechanics behind what studios greenlight in the genre, the desk\u2019s <a href="/entertainment/how-box-office-works/">box-office explainer</a> is the honest companion.</p>""",

"best-thriller-movies-of-all-time": """<h2>Desk notes: tension is information control</h2>
<p>Every thriller on the list above is really playing one instrument: what the audience knows, when, and what it does with the gap. The canon is a masterclass in the variations \u2014 dread from waiting, panic from pursuit, the slow turn of the mystery, the trap that closes on the trapper instead.</p>
<p>Use the list as a comparative course: watch a Hitchcock wait beside a modern paranoia picture and you can see the same lever pulled with different machinery. For tonight\u2019s pick specifically, the desk\u2019s <a href="/entertainment/what-to-watch-mystery-night/">mystery-night shelf</a> narrows by mood, and a same-night search on <a href="https://www.netflix.com/search?q=thriller" rel="noopener">Netflix</a> settles availability. Credits, years and director filmographies are one lookup away on <a href="https://www.imdb.com/find/?q=thriller" rel="noopener">IMDb</a>.</p>""",

"best-time-travel-stories-to-watch": """<h2>Desk notes: pick your paradox before you press play</h2>
<p>Every time-travel story declares its physics in the first act: fixed timeline, branching worlds, loops that eat themselves. Knowing which contract you are in is the difference between enjoying the cleverness and shouting at the plot \u2014 the list above is sorted so each pick\u2019s rules are stated plainly, because the rules are the genre\u2019s real characters.</p>
<p>The desk\u2019s viewing advice: do not marathon the strict-loop entries back to back; they compound like crosswords. Mix a loop film with a branch-world one and the genre stays generous. For the longer versions of the same pleasures, the desk\u2019s <a href="/entertainment/best-limited-series-to-watch/">limited-series shelf</a> carries the prestige variants, and credits and years are one lookup away on <a href="https://www.imdb.com/find/?q=time+travel" rel="noopener">IMDb</a>.</p>""",

"best-true-crime-documentaries-to-watch": """<h2>Desk notes: watching responsibly</h2>
<p>True crime is the documentary genre with the highest duty of care, because the subjects are real and the harm is recent. The list above leans on films that show their evidence and name their limits \u2014 and the desk\u2019s standing advice is to hold every entry to that standard: who is interviewed, what is documented, what the film admits it cannot know.</p>
<p>Two practical notes. Pace the genre: marathon-ing cases numbs exactly the empathy the best films depend on, so space them out. And keep one habit from journalism: after watching, read one accounted summary of the case \u2014 court records, a long-form report, even the case\u2019s encyclopedia entry \u2014 to see what the film compressed. Most picks rotate through the streamers; a search on <a href="https://www.netflix.com/search?q=true+crime" rel="noopener">Netflix</a> on the night finds the current shelf. The broader non-crime canon is on the desk\u2019s <a href="/entertainment/best-documentaries-of-all-time/">documentaries list</a>.</p>""",

"best-war-movies-of-all-time": """<h2>Desk notes: the genre against itself</h2>
<p>The war canon is a long argument about the same subject from opposite trenches: the film that makes combat legible and the film that makes it chaos, the one about units and the one about the individual the unit consumes. The list above deliberately holds both traditions, because each is the other\u2019s best correction.</p>
<p>Viewing advice: alternate decades. A fifties moral picture beside a modern technical one shows you what each era needed the war film to say. And mind the runtime \u2014 the genre\u2019s epics are genuinely long, which makes them planned-evening material rather than tonight-maybe picks. Credits, years and director context are one lookup away on <a href="https://www.imdb.com/find/?q=war" rel="noopener">IMDb</a>; for what the desk recommends tonight within a mood, the <a href="/entertainment/what-to-watch-when-bored/">two-minute picker</a> works for war films like anything else.</p>""",

"dogme-95-explained": """<h2>Desk notes: why a 1995 Danish manifesto still matters</h2>
<p>Dogme 95 was two Danish directors \u2014 Lars von Trier and Thomas Vinterberg \u2014 issuing a vow of chastity against cinema\u2019s growing machinery: no artificial light, no props brought to set, no genre music, no credits for the director. The films that passed the vow are small in number and permanent in influence; the movement\u2019s real product was the argument every low-budget filmmaker has inherited since.</p>
<p>Watch the founding pair back to back \u2014 the family dinner film and the idiot film \u2014 and you can see the vow producing two completely different cinemas from the same rules, which is the whole point: constraints reveal directors rather than constrain them. The movement\u2019s history, film list and the original manifesto text are collected on <a href="https://en.wikipedia.org/wiki/Special:Search?search=Dogme+95" rel="noopener">Wikipedia</a>, and the desk\u2019s <a href="/entertainment/german-expressionism-explained/">Expressionism explainer</a> is the earlier movement this one was arguing with across the century.</p>""",

"evergreen-anime": """<h2>Desk notes: what makes a series age-proof</h2>
<p>The series above share a specific immunity: their appeal is built on character grammar and craft rather than on the fashions of their production year. That is why they sit beside shows made decades apart without the seams showing \u2014 and why rewatching them is productive rather than nostalgic.</p>
<p>The desk\u2019s test for adding to this shelf, stated so you can apply it yourself: would the first episode still work if it premiered next season? Fashion-anchored shows fail that instantly; the evergreen ones pass it for decades. Availability is the one thing that does age \u2014 licensing rotates \u2014 so search <a href="https://www.crunchyroll.com/search?q=classic+anime" rel="noopener">Crunchyroll</a> or your service on the night rather than trusting any static list. For entering the older classics specifically, the desk\u2019s <a href="/entertainment/where-to-start-with-long-running-anime/">long-running guide</a> handles the commitment question.</p>""",

"fast-and-furious-watch-order": """<h2>Desk notes: the honest answer to the Drift problem</h2>
<p>The publication order is the viewing order for first-timers, and the Tokyo Drift question resolves itself once you accept what the film is: a side story that the later films promote into load-bearing canon. Watching in release order means its late-film surprises survive; watching chronologically spends them early for a neatness that buys you nothing.</p>
<p>For rewatchers, the chronological route is genuinely fun \u2014 the retcon continuity snaps together, and the series\u2019 escalation from street racing to orbital adjacent nonsense reads as a deliberate joke. Check individual titles\u2019 credits and years on <a href="https://www.imdb.com/find/?q=fast+and+furious" rel="noopener">IMDb</a>, and search your platform on the night \u2014 the franchise rotates between services, currently <a href="https://www.netflix.com/search?q=fast" rel="noopener">Netflix</a> among others. The desk\u2019s <a href="/entertainment/mission-impossible-watch-order/">Mission: Impossible guide</a> is the same treatment for the other great stunt franchise.</p>""",

"german-expressionism-explained": """<h2>Desk notes: the movement you have already seen quoted</h2>
<p>German Expressionism is the film movement most people know second-hand: the crooked caldera streets, the painted shadows, the somnambulist silhouette \u2014 all of it absorbed by Hollywood within a decade and folded into film noir, horror and every music video that ever lit a face from below. Watching the originals is therefore a double experience: the films themselves, and the family tree recognizing them.</p>
<p>The desk\u2019s route: start with the cabinet and the Nosferatu, then jump decades forward to the noirs the emigres made after fleeing \u2014 the visual grammar survives the ocean crossing intact. The movement\u2019s history and film list are collected on <a href="https://en.wikipedia.org/wiki/Special:Search?search=German+Expressionism+cinema" rel="noopener">Wikipedia</a>, many originals are public domain and easily found, and the desk\u2019s <a href="/entertainment/what-is-film-noir-explained/">noir explainer</a> picks up the story where this one ends.</p>""",

"hottest-movies-right-now": """<h2>Desk notes: how to read a heat list without being burned</h2>
<p>\u201cHottest right now\u201d is a weather report, not a review. Heat measures conversation \u2014 marketing pushes, viral moments, opening-weekend dynamics \u2014 and conversation is not quality; the desk\u2019s <a href="/entertainment/why-everything-is-a-remake/">economics explainer</a> and <a href="/entertainment/how-box-office-works/">box-office guide</a> unpack exactly why the loudest weekend is rarely the best film.</p>
<p>Use heat honestly: it is the right tool when your goal is participation \u2014 watching what everyone will discuss tomorrow \u2014 and the wrong tool when your goal is a good evening. For that, cross-check any hot title against the desk\u2019s genre canons before committing. Live standings and current releases are tracked publicly on <a href="https://www.boxofficemojo.com/" rel="noopener">Box Office Mojo</a> and <a href="https://www.themoviedb.org/movie" rel="noopener">TMDb</a>, both free, both updated daily \u2014 which is why this desk deliberately does not pretend to hold a live chart.</p>""",


"how-anime-production-committees-work": """<h2>Desk notes: why the committee explains the anime you get</h2>
<p>The production committee is why anime feels financially weird: a publisher, a toy company, a music label and a TV station each buy a slice, each recoups from its own lane, and the studio that animates the show often earns only a flat fee. Once you know that, the industries habits explain themselves \u2014 why second seasons depend on merchandise and disc sales, why adaptation ends at the manga volume the committee planned to boost, why a hit can still leave its studio poor.</p>
<p>It also explains the sequel logic: a committee greenlights more when the first slices sold, not when the reviews were good. The desk\u2019s <a href="/entertainment/anime-canon-and-filler-explained/">canon and filler guide</a> and <a href="/entertainment/anime-seasons-and-cours-explained/">cours explainer</a> cover the schedule consequences. For what committees currently have in production, the seasonal charts on <a href="https://www.crunchyroll.com/search?q=upcoming" rel="noopener">Crunchyroll</a> are the public-facing edge.</p>""",

"how-award-season-actually-works": """<h2>Desk notes: the calendar behind the trophies</h2>
<p>Award season is a campaign with a route map: festival premieres in late summer, limited qualifying releases by December, guild votes through January, and the Academy\u2019s own ceremony at the end. Understanding that route converts the season from noise into legibility \u2014 you can see which film is being pushed to which electorate, and why a December platform release with two screening a day is a strategy rather than an insult to your city.</p>
<p>The desk\u2019s viewing use: the season is a curated watchlist of the year\u2019s prestige product, best consumed after the ceremony, when the campaigns are over and the films are just films again. The Academy\u2019s own rules, timelines and category definitions are published on <a href="https://www.oscars.org/" rel="noopener">oscars.org</a> \u2014 reading them once is more useful than a hundred hot takes \u2014 and the desk\u2019s <a href="/entertainment/how-film-festivals-work/">festival explainer</a> covers where the season starts.</p>""",

"how-box-office-works": """<h2>Desk notes: the number, and what it hides</h2>
<p>Opening weekend is a marketing milestone, a studio-era record and \u2014 mostly \u2014 a projection of the marketing budget back onto the audience. The honest accounting happens over weeks: the studio\u2019s share of a ticket shrinks as a run continues, foreign splits differ, and a film\u2019s profit story cannot be told from gross alone. That is why this desk never reviews a film through its box office.</p>
<p>For readers, the practical use of box-office literacy is scepticism: when a headline says a film flopped or shocked the industry, check the numbers yourself before absorbing the narrative \u2014 <a href="https://www.boxofficemojo.com/" rel="noopener">Box Office Mojo</a> keeps the public ledgers. The desk\u2019s <a href="/entertainment/how-movie-budgets-work/">budget explainer</a> and <a href="/entertainment/how-movie-release-windows-work/">release-window guide</a> complete the accounting picture.</p>""",

"how-cinematic-universes-work": """<h2>Desk notes: the machine, stated plainly</h2>
<p>A cinematic universe is a scheduling technology wearing a story costume: shared characters let a studio advertise the next film inside the current one, which lowers marketing risk and raises the price of every misstep. That is the whole machine \u2014 and it explains both the ambition (crossing-over as event) and the recurring failure mode (films that behave like trailers for other films).</p>
<p>For viewers, the useful skill is perimeter detection: when a scene exists to set up a different movie, you are watching the machine, not the story. The desk\u2019s advice \u2014 judge each entry as a complete film and let the universe be a bonus, never the assignment. The economics of the model sit inside the desk\u2019s <a href="/entertainment/how-box-office-works/">box-office explainer</a>, and franchise viewing order is handled for the two great serials in the <a href="/entertainment/mission-impossible-watch-order/">MI guide</a> and the <a href="/entertainment/fast-and-furious-watch-order/">F\u0026F guide</a>. The origin story of the modern model is documented on <a href="https://en.wikipedia.org/wiki/Special:Search?search=cinematic+universe" rel="noopener">Wikipedia</a>.</p>""",

"how-film-festivals-work": """<h2>Desk notes: three festivals, three different jobs</h2>
<p>Festivals look like one thing from outside and are several from inside: a market where films are sold territory by territory, a press event where narratives are launched, and a public party with queues. The big three \u2014 Cannes, Venice, Toronto \u2014 split those jobs differently, which is why premiere strategy is a chess move: the festival a film chooses tells you what its sellers think it is.</p>
<p>For viewers, festivals matter as a calendar: premiere reception sets the year\u2019s prestige conversation, and most award-season entries debut there first. The festivals\u2019 own programmes and prize lists are public \u2014 see <a href="https://www.festival-cannes.com/" rel="noopener">festival-cannes.com</a> and <a href="https://www.berlinale.de/" rel="noopener">berlinale.de</a> \u2014 and the desk\u2019s <a href="/entertainment/how-award-season-actually-works/">award-season guide</a> follows what the festivals start.</p>""",

"how-movie-budgets-work": """<h2>Desk notes: the profit puzzle, assembled honestly</h2>
<p>A film\u2019s budget is the number the studio admits to; around it live distribution costs \u2014 thousands of prints\u2019 worth of marketing \u2014 interest, participations, and the accounting practices that keep famous films forever unprofitable on paper. That is why \u201cit made three times its budget\u201d is not a profit claim, and why the desk treats every breathe-that-easy profitability story with a raised eyebrow.</p>
<p>The useful reader habit: separate production budget (public, approximate) from marketing spend (rarely disclosed) from back-end deals (never disclosed) \u2014 anything built on all three being known is a story, not accounting. Budget and gross ledgers are public on <a href="https://www.boxofficemojo.com/" rel="noopener">Box Office Mojo</a>; the desk\u2019s <a href="/entertainment/how-box-office-works/">box-office guide</a> explains what share of a ticket the studio actually keeps.</p>""",

"how-movie-release-windows-work": """<h2>Desk notes: the windows are shrinking, the logic is not</h2>
<p>The release window is the film industry\u2019s price discrimination: charge the impatient first, the patient less, the landlords after. Theatrical, then premium digital, then streaming, then licensing \u2014 each window exists because a different audience will pay a different price at a different speed. The windows have compressed from video-store years to weeks; the logic underneath has not moved at all.</p>
<p>For viewers this explains the two recurring frustrations: why a film in cinemas is nowhere legal online, and why a show vanishes from a platform \u2014 windows close as well as open. The desk\u2019s <a href="/entertainment/how-streaming-licensing-works/">licensing explainer</a> covers the vanishing half of the story, and current theatrical runs are public on <a href="https://www.boxofficemojo.com/release/" rel="noopener">Box Office Mojo</a>. The historical arc of the collapse is documented on <a href="https://en.wikipedia.org/wiki/Special:Search?search=release+window+film" rel="noopener">Wikipedia</a>.</p>""",

"how-movie-trailers-are-made": """<h2>Desk notes: the second film, made by different hands</h2>
<p>A trailer is not a cut of the film; it is a separate work, usually built by a specialised house from selected footage, sometimes months before the film is finished. The music is licensed or tracked, not scored; the voice, the structure and the three-act teaser arc belong to the trailer editor\u2019s craft. Knowing this converts trailer-watching from preview to genre \u2014 you are watching one film sell another.</p>
<p>The desk\u2019s practical advice follows from it: judge the film, never the trailer; a bad trailer is often a marketing failure and nothing more, and a great trailer can be the best editing of footage the film never equals. Every trailer on this site is embedded from the rights-holder\u2019s own channel and verified at each sweep \u2014 the desk\u2019s method is on the <a href="/entertainment/how-to-read-movie-reviews/">reading reviews guide</a>, and the trailer economy\u2019s history is on <a href="https://en.wikipedia.org/wiki/Special:Search?search=trailer+film+promotion" rel="noopener">Wikipedia</a>.</p>""",

"how-streaming-licensing-works": """<h2>Desk notes: why your favourite show emigrated</h2>
<p>Streaming catalogues are rental shelves, not archives: platforms license titles for fixed terms in fixed regions, and when a term lapses the title leaves \u2014 often to a rival, sometimes to nowhere, occasionally back again. That is the whole mystery of the vanishing show, and it is why any page promising permanent availability is lying to you politely.</p>
<p>The desk\u2019s practical consequences: availability questions deserve a same-night search, not a bookmark from last year; and a physical or purchased copy remains the only ownership in streaming, everything else is a long rental. Where regional availability gets complicated, <a href="https://www.justwatch.com/" rel="noopener">JustWatch</a> maintains the public per-country ledgers the desk checks against. The desk\u2019s <a href="/entertainment/why-streaming-services-raise-prices/">pricing explainer</a> covers the other half of the platform business, and the underlying rights mechanics are summarised on <a href="https://en.wikipedia.org/wiki/Special:Search?search=streaming+television+licensing" rel="noopener">Wikipedia</a>.</p>""",

"how-to-build-a-watchlist": """<h2>Desk notes: the watchlist is a menu, not a warehouse</h2>
<p>The failure mode of every watchlist is archaeology: six hundred titles, no decisions, ambient guilt. The fix is structural, not moral \u2014 a list that works is short, themed and allowed to be abandoned. The desk\u2019s standing configuration: three shelves max, five titles each, one shelf per mood; anything new joins by displacing something, which keeps the list honest about your actual viewing speed.</p>
<p>Two habits finish the job. Schedule the watching the way you would any appointment \u2014 the list feeds a calendar, not a fantasy of future free time. And retire without ceremony: a title untouched after three sweeps of the shelf was never a plan, just a bookmark. The picking method that goes with it is on the <a href="/entertainment/how-to-pick-a-movie-tonight/">tonight guide</a>, and the desk\u2019s <a href="/entertainment/what-to-watch-when-bored/">two-minute picker</a> is the fallback for list-wrecked evenings.</p>""",

"how-to-read-movie-reviews": """<h2>Desk notes: the reader\u2019s side of the contract</h2>
<p>A review is an argument from a stated taste, not a consumer report \u2014 and reading it well means calibrating the critic, not obeying the score. The calibration takes three data points: one film you loved that the critic panned, one you disliked that they praised, and one you both saw the same way. After that, every future review converts: you know which of their praises mean something to you.</p>
<p>Aggregates deserve the same literacy: a Rotten Tomatoes percentage counts positive reviews, not intensity, and says nothing about which half you will be in \u2014 the scoreboard lives at <a href="https://www.rottentomatoes.com/" rel="noopener">Rotten Tomatoes</a>, the meaning lives in the texts. The desk\u2019s own scoring axes and no-spoiler conventions are published on <a href="/entertainment/scoring/">the method page</a>, deliberately, so you can calibrate us the same way.</p>""",

"how-tv-shows-get-cancelled": """<h2>Desk notes: the axe, explained by arithmetic</h2>
<p>Cancellation is where television\u2019s public story (audiences love it) meets its private one (who pays for it, and what the contract says). Renewal economics weigh ownership, audience retention after episode one, international sales, completion rates and the cost curve of cast deals \u2014 which is why beloved shows die and lightly watched ones cruise: the beloved show may be rented, the cruise may be owned and cheap.</p>
<p>For viewers, the literacy pay-off is calm: knowing the metrics explains why a cliffhanger is a risk rather than a promise, and why finishing a season is a vote that matters less than starting one. The streaming era\u2019s specific cancellation economics are summarised on <a href="https://en.wikipedia.org/wiki/Special:Search?search=television+cancellation+renewal" rel="noopener">Wikipedia</a>, and the desk\u2019s <a href="/entertainment/why-tv-seasons-are-getting-shorter/">shorter-seasons explainer</a> is the companion piece on why orders shrank.</p>""",

"isekai-anime-explained": """<h2>Desk notes: the portal genre\u2019s real rules</h2>
<p>Isekai looks like a fantasy premise and works like a wish-fulfilment contract: the transported hero arrives with modern knowledge or a cheat power, and the genre\u2019s pleasure is watching the new world reward what the old world ignored. Read that way, the boom years make sociological sense \u2014 and so does the current wave of parodies, which exist because the contract became so legible it could be mocked.</p>
<p>The desk\u2019s picking advice: choose by what the other world demands of the hero, not by the scenery \u2014 the subgenres (overlord, slow-life, redemption loop) are genuinely different products. Simulcast home for the genre is <a href="https://www.crunchyroll.com/search?q=isekai" rel="noopener">Crunchyroll</a>; the desk\u2019s <a href="/entertainment/where-to-start-with-long-running-anime/">long-running guide</a> and <a href="/entertainment/shonen-shojo-seinen-explained/">demographics map</a> place the big titles on the wider field.</p>""",

"kdrama-genres-explained": """<h2>Desk notes: the lane is the promise</h2>
<p>K-drama genre labels do real work: each lane carries a fixed contract about tone, pace and how much the story will hurt. Romance-comedy promises the push-pull with a known landing; the revenge melo promises catharsis at a price; the historical promises scale and scheming; the life-slice promises healing rather than adrenaline. Choosing by lane first is why seasoned viewers are never disappointed by a show they picked in two minutes.</p>
<p>The desk\u2019s advice for the second watch: after your first lane, try its opposite \u2014 the genre\u2019s range is wider than its export hits suggest, and the smaller lanes are where the form keeps reinventing itself. Current shows across every lane sit on the major platforms, starting with a search on <a href="https://www.netflix.com/search?q=korean" rel="noopener">Netflix</a>; the starter route itself is on the desk\u2019s <a href="/entertainment/best-kdramas-to-start-with/">five-show shelf</a>.</p>""",

"mission-impossible-watch-order": """<h2>Desk notes: release order, and why it is easy here</h2>
<p>The Mission: Impossible franchise is the rare serial where the honest answer is the simple one: release order. Each film is a self-contained mission with a returning lead and escalating practical stunts; chronology adds nothing that release order does not already give, and the early entries are period documents of how action grammar changed between 1996 and now.</p>
<p>The rewatch note: the films run on directors\u2019 signatures more than on continuity \u2014 each auteur gets the same brief (impossible task, real stunt, dead mission structure) and produces a different film, which makes a marathon a survey of action craft. Credits and years are one lookup on <a href="https://www.imdb.com/find/?q=mission+impossible" rel="noopener">IMDb</a>; availability rotates, so search your platform \u2014 currently <a href="https://www.netflix.com/search?q=mission+impossible" rel="noopener">Netflix</a> among others \u2014 on the night. The <a href="/entertainment/fast-and-furious-watch-order/">F\u0026F guide</a> is the companion where the order question actually has a twist.</p>""",

"nollywood-golden-age-explained": """<h2>Desk notes: the golden age in one viewing route</h2>
<p>Nollywood\u2019s golden age is best understood not as a style but as an economic miracle with a house style: direct-to-video distribution turning Lagos market stalls into the world\u2019s fastest-growing film industry, and a grammar \u2014 moral fables, family pressure, ritual panic \u2014 that travelled across the continent faster than any cinema before it.</p>
<p>The desk\u2019s route through it: start at the big bang with the ritual classics, move through the late-nineties family melodramas, then jump to the 2009 festival-era features that used the golden age as a foundation. Every title mentioned sits in the desk\u2019s <a href="/entertainment/reviews/">review shelf</a> with dated axes \u2014 credits and context for the founding films are one lookup on <a href="https://www.imdb.com/find/?q=living+in+bondage" rel="noopener">IMDb</a> \u2014 and the starter version of this route is on <a href="/entertainment/where-to-start-with-nollywood/">where to start with Nollywood</a>.</p>""",

"scariest-horror-movies-tonight": """<h2>Desk notes: matching the scare to the night</h2>
<p>Scariest is a fit question, not a ranking: dread films ruin sleep differently from jump-scare machines, and grief-horror ruins them differently again. The list above is sorted by mechanism for exactly that reason \u2014 decide what kind of afraid you want tonight, then read down the column, not across a leaderboard.</p>
<p>Two honesty notes. Context multiplies scares: headphones, dark room and a solo watch can add a full point to any entry, which is worth knowing in both directions. And the ceiling is real \u2014 if a night needs guaranteed sleep afterwards, pick from the desk\u2019s <a href="/entertainment/best-films-for-a-group/">lighter group shelf</a> instead. Availability rotates; a same-night search on <a href="https://www.netflix.com/search?q=horror" rel="noopener">Netflix</a> settles it, and credits are one lookup away on <a href="https://www.imdb.com/find/?q=horror" rel="noopener">IMDb</a>.</p>""",

"shonen-shojo-seinen-explained": """<h2>Desk notes: demographics are shelving, not quality</h2>
<p>Shonen, shojo and seinen name the magazine a manga ran in \u2014 teen boys, teen girls, adult men \u2014 and the anime adapted from them inherits the label. It is publishing geography, not a verdict: masterpieces and filler live in every lane, and the labels say more about the intended reader\u2019s evening than about what any viewer will enjoy.</p>
<p>The desk\u2019s advice: use the lanes as recommendation anchors (a shonen fan asking for more shonen wants pace and escalation; a seinen ask wants ambiguity), then cross the lanes shamelessly once the anchors stop predicting your taste. Current titles from every lane simulcast on <a href="https://www.crunchyroll.com/search?q=anime" rel="noopener">Crunchyroll</a>. The system\u2019s magazine history is on <a href="https://en.wikipedia.org/wiki/Special:Search?search=shonen+manga+demographic" rel="noopener">Wikipedia</a>, and the desk\u2019s <a href="/entertainment/anime-seasons-and-cours-explained/">cours explainer</a> covers the scheduling side.</p>""",

"slice-of-life-anime-explained": """<h2>Desk notes: the genre that refuses urgency</h2>
<p>Slice-of-life is the anime of low stakes practised deliberately: no tournament, no endgame, the pleasure located in routine, food, seasons and small social weather. The genre\u2019s craft problem \u2014 holding attention without threat \u2014 is why the best ones are quietly among the medium\u2019s best-directed shows: when nothing must happen, everything chosen is a choice.</p>
<p>The honest picking advice: match the genre to your state, not your taste. Tired and frazzled, it is medicine; bored and restless, it will feel like nothing. The desk treats it as a shelf to keep for the right evening rather than a binge. Simulcast and catalogue titles sit on <a href="https://www.crunchyroll.com/search?q=slice+of+life" rel="noopener">Crunchyroll</a>, and the desk\u2019s <a href="/entertainment/anime-seasons-and-cours-explained/">cours explainer</a> explains why the season format suits this genre so well.</p>""",

"subtitles-or-dubs": """<h2>Desk notes: the honest answer, generalised</h2>
<p>Subtitles for original performance, dubs for a freed gaze \u2014 that is the trade, and the desk\u2019s standing advice is situation-dependent rather than doctrinal: first-viewing of a film where direction lives in the voice, subtitled; background viewing, second viewings, or animation where the voice is one layer among many, dubbed happily. The mistake is treating either as a loyalty test.</p>
<p>Two practical upgrades. Dub quality is per-language and per-show, not per-format \u2014 a great dub exists for shows with terrible ones, so check rather than assume. And if subtitles strain your attention, the pause-and-rewind habit is a skill that builds within weeks, not a permanent tax. The streaming platforms\u2019 language options are listed per title \u2014 check on <a href="https://www.netflix.com/search?q=anime" rel="noopener">Netflix</a> or your service \u2014 and the accessibility research summary is on <a href="https://en.wikipedia.org/wiki/Special:Search?search=subtitles+versus+dubbing" rel="noopener">Wikipedia</a>.</p>""",

"supernatural-shows-to-watch": """<h2>Desk notes: pick your haunting register</h2>
<p>Supernatural television runs on registers \u2014 the procedural hunter-of-the-week, the slow domestic haunting, the mythology epic, the comedy with fangs \u2014 and the list above sorts by register because the wrong register is the genre\u2019s only common disappointment. A viewer wanting folklore dread will not forgive a monster-of-the-week formula, and vice versa.</p>
<p>Commitment note: this is the shelf where the long-runner lives, so check season counts before starting \u2014 the desk\u2019s <a href="/entertainment/best-limited-series-to-watch/">limited-series shelf</a> is the contained alternative for the same pleasures. Availability rotates across platforms; a same-night search on <a href="https://www.netflix.com/search?q=supernatural" rel="noopener">Netflix</a> settles tonight, and the genre\u2019s folklore roots are summarised on <a href="https://en.wikipedia.org/wiki/Special:Search?search=supernatural+fiction+television" rel="noopener">Wikipedia</a>.</p>""",

"what-is-film-noir-explained": """<h2>Desk notes: the shadow genre\u2019s working definition</h2>
<p>Noir is less a genre than a weather system: urban night, venetian-blind light, a protagonist morally underwater, and a plot where knowing too much is the fatal diagnosis. The term was retrofitted by French critics to American pictures the studios marketed as crime melodramas \u2014 which is why every honest definition starts with the look and the fatalism rather than the plot furniture.</p>
<p>The desk\u2019s starter route: one definitive private-eye picture, one doomed-romance noir, one police-procedural noir \u2014 three films and the weather system is yours. The movement\u2019s history and canon are collected on <a href="https://en.wikipedia.org/wiki/Special:Search?search=film+noir" rel="noopener">Wikipedia</a>, many entries are in circulation on classic-film platforms, and the origin story of the style is on the desk\u2019s <a href="/entertainment/german-expressionism-explained/">Expressionism page</a> \u2014 the emigres brought the shadows with them.</p>""",

"what-to-watch-in-90-minutes": """<h2>Desk notes: the short runtime is a craft, not a compromise</h2>
<p>A great sub-100-minute film is not a truncated one; it is a different engineering problem \u2014 no fat to hide behind, every scene load-bearing. The list above honours that economy, which is why it ages so well: lean films rarely age badly, because there is nothing saggy to age.</p>
<p>Use the shelf as an appointment-keeper for weeknights: pick from it before opening any platform app, because the ninety-minute promise dies the moment the algorithm gets a vote. Search your service on the night \u2014 the picks rotate, with a good share on <a href="https://www.netflix.com/search?q=film" rel="noopener">Netflix</a> \u2014 and runtimes for every entry are one lookup away on <a href="https://www.imdb.com/find/?q=film" rel="noopener">IMDb</a>. The longer evening version of the same method is the desk\u2019s <a href="/entertainment/how-to-pick-a-movie-tonight/">tonight guide</a>.</p>""",

"what-to-watch-mystery-night": """<h2>Desk notes: fair-play versus the abyss</h2>
<p>Mystery night splits in two, and the split matters: the fair-play tradition promises you could have solved it and plays the game straight; the abyss tradition promises the solving will not save anyone and the answer will hurt. Both are on the shelf, labelled \u2014 choosing the wrong contract is the genre\u2019s only real disappointment.</p>
<p>The desk\u2019s night plan: decide the contract first, group-vs-solo second \u2014 fair-play films are at their best with company guessing out loud; abyss films want a solo room. Availability rotates across the platforms, starting with a search on <a href="https://www.netflix.com/search?q=mystery" rel="noopener">Netflix</a>; the tension canon beyond mysteries lives on the desk\u2019s <a href="/entertainment/best-thriller-movies-of-all-time/">thriller list</a>.</p>""",

"what-to-watch-when-bored": """<h2>Desk notes: boredom is three different problems</h2>
<p>Boredom has subspecies, and each needs a different film: restless boredom wants velocity, empty boredom wants comfort, brain-in-a-sling boredom wants novelty strong enough to overwrite the mood. The list above is sorted into those three drawers, which is why the desk can honestly call it a two-minute answer: diagnose, open the drawer, take the first title that has not been seen.</p>
<p>The standing rule: when bored, never browse. Browsing is the symptom; the list is the cure \u2014 pick within two minutes or the evening belongs to the algorithm. Availability rotates across the platforms \u2014 search <a href="https://www.netflix.com/search?q=movie" rel="noopener">Netflix</a> or your service on the night \u2014 and the full method behind quick picks is on the desk\u2019s <a href="/entertainment/how-to-pick-a-movie-tonight/">tonight guide</a>.</p>""",

"where-to-start-with-ghibli": """<h2>Desk notes: the route through the studio\u2019s two souls</h2>
<p>Studio Ghibli \u2014 founded in 1985 by Hayao Miyazaki and Isao Takahata \u2014 has two souls, and the honest starter route visits both: the flight-and-wonder lineage (wind, machines, air, courage) and the quiet-ordinary lineage (meals, seasons, growing up without quests). Starting with one of each tells you which Ghibli viewer you are, which then orders everything else.</p>
<p>Practical notes: the films are family-safe by design but paced for patience \u2014 children forgive the slowness faster than distracted adults do. Watch subtitled once and dubbed once if you have children in the house; the English dubs are studio-quality and historically careful. The studio\u2019s own film catalogue lives at <a href="https://www.ghibli.jp/" rel="noopener">ghibli.jp</a>, and the desk\u2019s <a href="/entertainment/best-anime-movies-of-all-time/">anime-film canon</a> places the studio on the wider field.</p>""",

"where-to-start-with-james-bond": """<h2>Desk notes: start at an era, not at 1962</h2>
<p>Bond is six decades of reinvention wearing one tuxedo, and the honest starter advice is era-first: each actor\u2019s run has its own contract about tone, stakes and what the films think of their hero. Starting at the beginning is a historian\u2019s route, not a viewer\u2019s; the desk\u2019s route starts you at the era whose tone you would actually finish.</p>
<p>After the first era, the canon route is rewarding precisely because the seams show \u2014 the series arguing with itself about the Cold War, camp, grit and grief. The franchise\u2019s official home, with the film history kept current, is <a href="https://www.007.com/" rel="noopener">007.com</a>; credits and box office are one lookup away on <a href="https://www.imdb.com/find/?q=james+bond" rel="noopener">IMDb</a>, and availability rotates, so search your platform on the night.</p>""",

"where-to-start-with-long-running-anime": """<h2>Desk notes: the commitment question, answered honestly</h2>
<p>Long-running anime asks one question before any recommendation matters: do you want the epic\u2019s whole arc, or the epic\u2019s best corridor? The honest routes in the list above are built around that split \u2014 a canon-corridor route (a few hundred episodes of the essential) and a full-sail route for the completionist, which is a lifestyle rather than a watch.</p>
<p>Two logistics notes that save people: filler guides exist for a reason, and using one is not cheating \u2014 the desk\u2019s <a href="/entertainment/anime-canon-and-filler-explained/">canon and filler guide</a> explains the mechanics. And check which service carries the run in your region before committing: the big catalogue titles sit on <a href="https://www.crunchyroll.com/search?q=one+piece" rel="noopener">Crunchyroll</a> and <a href="https://www.netflix.com/search?q=one+piece" rel="noopener">Netflix</a> depending on region and season.</p>""",

"where-to-start-with-nollywood": """<h2>Desk notes: the two-door entry</h2>
<p>Nollywood has two front doors and the desk recommends choosing deliberately: the modern streaming era (glossy, festival-travelled, designed for international subtitles) or the video-era classics (rougher, faster, the industry\u2019s own accent at its purest). Starting at the wrong door is why some first-timers bounce \u2014 each makes promises the other cannot keep.</p>
<p>The desk\u2019s route: one modern entry, then one 1992-era founding classic, then follow the director rather than the star \u2014 the industry is director-driven in a way star-focused coverage hides. The review shelf carries dated, axes-scored entries for every recommendation, the golden-age story is on <a href="/entertainment/nollywood-golden-age-explained/">its own page</a>, and credits for the founding films are one lookup away on <a href="https://www.imdb.com/find/?q=living+in+bondage" rel="noopener">IMDb</a>.</p>""",

"why-everything-is-a-remake": """<h2>Desk notes: the economics behind the deja vu</h2>
<p>The remake wave is not a creativity shortage; it is capital behaving like capital: a known property is a de-risked asset with pre-awareness doing the marketing\u2019s first hour for free, and in a high-budget industry, de-risked is what gets greenlit. The desk finds it more useful \u2014 and more accurate \u2014 to explain that than to rage at it.</p>
<p>The viewer\u2019s defence is curation, and it works: the originals remain one search away, and watching them beside their remakes is genuinely the best film-literacy exercise there is \u2014 each pair is an argument about what its era wanted. The remake economics are summarised on <a href="https://en.wikipedia.org/wiki/Special:Search?search=film+remake" rel="noopener">Wikipedia</a>, the deeper accounting is on the desk\u2019s <a href="/entertainment/how-movie-budgets-work/">budgets page</a>, and the desk\u2019s canons \u2014 <a href="/entertainment/best-sci-fi-movies-of-all-time/">sci-fi</a>, <a href="/entertainment/best-horror-movies-of-all-time/">horror</a>, <a href="/entertainment/best-action-movies-of-all-time/">action</a> \u2014 are where the originals live.</p>""",

"why-streaming-services-raise-prices": """<h2>Desk notes: the four levers, and the one you control</h2>
<p>Streaming prices climb on four levers: content costs (sports-sized budgets need subscription-sized revenue), the pivot from growth-at-any-price to profitability, ad-tier positioning that makes the cheap tier deliberately imperfect, and the slow squeeze of shared-account crackdowns. None of it is mysterious; all of it is a mature industry repricing a utility its customers now consider essential.</p>
<p>The reader\u2019s one lever is portfolio thinking: treat subscriptions like gym memberships \u2014 rotate by season, subscribe for the show, finish, leave. The platform\u2019s own current tiers and prices are always public, starting at <a href="https://www.netflix.com/search?q=plans" rel="noopener">Netflix</a> or your service; the desk\u2019s <a href="/entertainment/best-streaming-apps-nigeria/">Nigeria apps guide</a> keeps the local maths, and the <a href="/entertainment/how-streaming-licensing-works/">licensing explainer</a> covers where the content money actually goes.</p>""",

"why-tv-seasons-are-getting-shorter": """<h2>Desk notes: eight episodes is a budget line, not a style</h2>
<p>The shrinking season is economics wearing an artistic costume: eight-episode orders cost less, concentrate talent deals, reduce the risk window and suit platforms reporting quarterly \u2014 the creative rationale (tighter stories) is real but was mostly discovered after the spreadsheet. Both things are true: shorter seasons do concentrate craft, and they were adopted for money first.</p>
<p>The viewer consequence is the changed rhythm: modern seasons are built like long films, which rewards the binge and starves the water-cooler week. Knowing which rhythm a show was built for \u2014 weekly network run or platform drop \u2014 tells you how to watch it. The industry shift is summarised on <a href="https://en.wikipedia.org/wiki/Special:Search?search=television+season+episode+count" rel="noopener">Wikipedia</a>, and the cancellation arithmetic behind it is on the desk\u2019s <a href="/entertainment/how-tv-shows-get-cancelled/">cancellation guide</a>.</p>""",

"10-facts-about-agent-kim-squid-game-season-3": """<h2>Desk notes: reading a fact-list about a moving target</h2>
<p>Character fact-lists age at the speed of the show: anything written between seasons is provisional by definition, and this desk dates its pieces for exactly that reason. Treat the ten facts above as a primer for the next season, not a permanent record \u2014 the show\u2019s production news, cast announcements and release dates are tracked by the platform itself, starting at <a href="https://www.netflix.com/search?q=squid+game" rel="noopener">Netflix</a>, which is the only source this desk trusts for what airs next.</p>
<p>For the context behind the phenomenon \u2014 why this show became the platform\u2019s biggest launch and what it did to Korean production economics \u2014 the desk\u2019s <a href="/entertainment/kdrama-genres-explained/">K-drama lane map</a> and <a href="/entertainment/best-kdramas-to-start-with/">starter route</a> place it in the wider wave. Character names and actor credits are one lookup away on <a href="https://www.imdb.com/find/?q=squid+game" rel="noopener">IMDb</a>.</p>""",

"cheapest-way-to-stream-movies": """<h2>Desk notes: the cheapest stack, refreshed honestly</h2>
<p>The cheapest legal setup is a rotation, not a stack: one subscription at a time, chosen for what you will actually watch this month, cancelled without ceremony when the month ends. Every platform makes joining easy and leaving harder emotionally than practically \u2014 the cancellation flow is always there, and using it is the whole trick. Prices and tiers are published on each service\u2019s own plans page, starting at <a href="https://www.netflix.com/search?q=plans" rel="noopener">Netflix</a> and <a href="https://www.primevideo.com/search?q=plans" rel="noopener">Prime Video</a>.</p>
<p>Three permanent rules from the desk: free trials exist to be finished with, ad tiers are a real option rather than a downgrade for background viewing, and data costs count in the total \u2014 offline downloads on a cheap tier often beat streaming a premium tier over mobile data. The full framework is on the desk\u2019s <a href="/entertainment/best-streaming-apps-nigeria/">Nigeria apps guide</a>.</p>""",

"modern-horror-starter-route": """<h2>Desk notes: the route, and what each stop teaches</h2>
<p>The modern horror route works because each stop adds one instrument: the elevated-dread entry teaches atmosphere, the grief entry teaches metaphor, the home-invasion entry teaches staging, the folk entry teaches dread without explanation. Take them in order and by the end you can read any new horror release fluently \u2014 you will know which instrument a film is playing within twenty minutes.</p>
<p>The route deliberately stays inside one decade, so availability is good: most picks rotate through the major platforms, with a same-night search on <a href="https://www.netflix.com/search?q=horror" rel="noopener">Netflix</a> settling tonight. If a stop lands badly, do not quit the route \u2014 swap the register rather than the decade; the canon behind all of it is on the desk\u2019s <a href="/entertainment/best-horror-movies-of-all-time/">all-time horror list</a>.</p>""",

"movies-like-parasite": """<h2>Desk notes: decide what you loved first</h2>
<p>Parasite-shaped recommendations fail because the film does three jobs at once: class satire, genre mine, and tonal high-wire act. The list above sorts its picks by which of the three you actually want again \u2014 the satire without the thriller gear, the thriller without the satire, or the tonal whiplash itself. Choosing first prevents the common letdown: a film that shares one axis and feels nothing alike.</p>
<p>Going deeper: Bong Joon-ho\u2019s earlier films are the most direct next step, and the desk\u2019s <a href="/entertainment/10-korean-movies-everyone-should-watch/">Korean canon</a> and <a href="/entertainment/korean-cinema-starter-guide-rebuilt/">starter guide</a> carry the route forward. Availability rotates by region and month \u2014 a same-night search on <a href="https://www.netflix.com/search?q=parasite" rel="noopener">Netflix</a> or your service settles it, and credits sit one lookup away on <a href="https://www.imdb.com/find/?q=parasite" rel="noopener">IMDb</a>.</p>""",

"one-piece-vs-naruto": """<h2>Desk notes: the argument is a personality test</h2>
<p>One Piece versus Naruto is really a question about what you want from a long story: the accumulated-world epic, where the map keeps expanding and the destination recedes generously, or the engine-driven ninja drama, where pain and inheritance drive a tighter machine. The desk\u2019s verdict above is argued honestly \u2014 but the honest caveat is that both shows reward different temperaments, and picking the wrong one for you is the only way to lose.</p>
<p>Practical notes either way: both are long commitments, both have canon/filler seams (the desk\u2019s <a href="/entertainment/anime-canon-and-filler-explained/">guide</a> explains them), and both sit in rotation across the platforms \u2014 check <a href="https://www.crunchyroll.com/search?q=one+piece" rel="noopener">Crunchyroll</a> and <a href="https://www.netflix.com/search?q=naruto" rel="noopener">Netflix</a> for your region. The commitment mathematics are on <a href="/entertainment/where-to-start-with-long-running-anime/">where to start with long-running anime</a>.</p>""",

"projector-or-tv-for-movie-nights": """<h2>Desk notes: the room decides, not the spec sheet</h2>
<p>The projector-versus-TV question is answered by the room before any product is: a projector needs darkness and distance; a TV needs a wall and a socket. Bright rooms and small rooms vote television; dedicated dark rooms and long throws vote projector. Every spec-sheet argument that ignores the room is marketing, and the desk declines to pretend otherwise.</p>
<p>The hybrid advice that actually works: a mid-range TV for the week and a projector for the ritual \u2014 group nights, film-club nights \u2014 costs less than one flagship anything. Check current models\u2019 measured (not marketed) performance against your room\u2019s light before buying; the display basics are summarised on <a href="https://en.wikipedia.org/wiki/Special:Search?search=projector+versus+television+home+cinema" rel="noopener">Wikipedia</a>, and the desk\u2019s <a href="/entertainment/what-you-need-for-4k-streaming/">4K requirements guide</a> covers the other half of the picture.</p>""",

"what-you-need-for-4k-streaming": """<h2>Desk notes: the four-link chain</h2>
<p>4K streaming is a chain of four links, and the weakest one decides everything: a 4K plan on the service, a 4K-capable device, an HDMI port that actually carries the bandwidth, and bandwidth at home \u2014 real, measured, evening-time bandwidth, not the number on the advert. Miss any one link and the chain silently delivers upscaled 1080p, which is why so many households watch fake 4K for years.</p>
<p>The desk\u2019s audit order: check your plan\u2019s tier first (the premium tiers carry the resolution \u2014 see each service\u2019s plans page, e.g. <a href="https://www.netflix.com/search?q=plans" rel="noopener">Netflix</a>), then the device\u2019s spec line, then run a speed test at 8pm, not 8am. The cheap-tier maths and data considerations are on the desk\u2019s <a href="/entertainment/cheapest-way-to-stream-movies/">cheapest setup guide</a>.</p>""",

"5-movies-that-broke-the-internet": """<h2>Desk notes, continued: the checkable half</h2>
<p>One addition to the notes above, and it is the checkable half: every claim a viral-moment list makes can be verified against the record instead of the memory. Release dates, box-office arcs and the filmographies of everyone involved are one lookup away on <a href="https://www.imdb.com/find/?q=movie" rel="noopener">IMDb</a>, and the box-office ledgers behind the break-the-internet headlines are public on <a href="https://www.boxofficemojo.com/" rel="noopener">Box Office Mojo</a> \u2014 the moment lives in the discourse, the numbers live in the ledger, and comparing the two is where the honest reading happens.</p>
<p>When the memes have finished doing their job, the desk\u2019s genre canons \u2014 <a href="/entertainment/best-sci-fi-movies-of-all-time/">sci-fi</a>, <a href="/entertainment/best-thriller-movies-of-all-time/">thrillers</a>, <a href="/entertainment/best-horror-movies-of-all-time/">horror</a> \u2014 are the route from the moment back to the film it came from.</p>"""
}


MOVIE_CARD_DEPTH = {

"kingdom": """<h2>Context the desk keeps</h2>
<p>This Joseon-era plague thriller — a crown prince, a kingdom drowning in rumour, and a sickness that raises the dead — belongs to the wave of Korean genre television that turned the zombie film inward, trading set pieces for court politics: hunger and hierarchy do more damage here than the infected do. It grew from a webcomic, reached a wide international audience through <a href="https://www.netflix.com/search?q=kingdom" rel="noopener">Netflix</a>, and its blend of period drama and horror has aged into one of the genre’s cleaner recommendations for viewers who normally avoid both.</p>
<p>For viewers arriving from the zombie side, the court intrigue is the adjustment — and the reward: the show’s horror lands harder because the politics already established who the monsters are. Credits, episode counts and the webcomic’s details are one lookup away on <a href="https://www.imdb.com/find/?q=kingdom+korean" rel="noopener">IMDb</a>; the desk’s <a href="/entertainment/best-kdramas-to-start-with/">K-drama starter route</a> is the broader way in.</p>""",

"kuroko-basketball": """<h2>Context the desk keeps</h2>
<p>This sports anime adapts Tadatoshi Fujimaki’s manga about the “phantom sixth man” of a legendary middle-school team — the Generation of Miracles — reconvening as rivals across high-school basketball. The premise is pure shonen tournament architecture, but the execution made the genre’s case for the era: matches edited like thrillers, abilities pushed to stylish extremes, and a lead whose whole power is being unremarkable — the perfect engine for a series about shadows and the players who cast them.</p>
<p>For newcomers, the honest framing: this is the series that carried the sports lane through the 2010s alongside the volleyball and swimming shows, with the 2017 feature closing the arc. The series streams in rotation — check <a href="https://www.crunchyroll.com/search?q=kuroko" rel="noopener">Crunchyroll</a> — and the full run’s credits and film are one lookup on <a href="https://www.imdb.com/find/?q=kuroko+no+basuke" rel="noopener">IMDb</a>; the desk’s <a href="/entertainment/shonen-shojo-seinen-explained/">demographics map</a> and <a href="/entertainment/anime-seasons-and-cours-explained/">cours guide</a> explain the machinery behind it.</p>""",

}
