# BRYME Entertainment — the catalogue (batch 23, 11 Sep 2026). Expanded from batch 22.
# House rule: every entry links ONLY to pages that genuinely discuss the title
# (verified against page text at build time — the build fails if a link lies).

CATALOGUE_SHELVES = [
("fantasy", "Fantasy &amp; Sci-Fi",
"Big worlds, bigger ideas — every film here is argued about somewhere on this desk.",
[
 ("Interstellar", "2014", "Film", "Time, gravity and the price of a promise — the ending the desk keeps defending.", ["movies-like-interstellar-guide", "7-movies-we-wished-never-ended"]),
 ("Arrival", "2016", "Film", "First contact as a language puzzle — the patient sibling of the Interstellar picks.", ["movies-like-interstellar-guide", "dune-sci-fi-epics-guide"]),
 ("Dune: Part Two", "2024", "Film", "Villeneuve's sandworm epic, and why the scale finally feels earned.", ["dune-sci-fi-epics-guide", "7-movies-we-wished-never-ended"]),
 ("Blade Runner 2049", "2017", "Film", "The same patient, enormous-screen visual language as the modern Dune films.", ["dune-sci-fi-epics-guide", "movies-like-interstellar-guide"]),
 ("Alien", "1979", "Film", "The haunted house in space — the whole franchise in viewing order on the desk.", ["alien-franchise-in-order"]),
 ("The Martian", "2015", "Film", "Science as the hero — the optimistic counterweight to the Interstellar picks.", ["movies-like-interstellar-guide", "dune-sci-fi-epics-guide"]),
 ("Gravity", "2013", "Film", "Survival in the silent dark — the purest cinema-vs-physics ride on the shelf.", ["movies-like-interstellar-guide", "dune-sci-fi-epics-guide"]),
]),
("anime", "Anime",
"Entry points, long-runners and the vocabulary to argue about them properly.",
[
 ("Solo Leveling", "2024", "Anime", "From E-rank joke to system-wielder — the rise that spawned a wave.", ["solo-leveling-e-rank-to-s-rank", "10-anime-like-solo-leveling-you-should-watch", "solo-leveling-vs-hunter-x-hunter-the-similarities-and-differences"]),
 ("Frieren: Beyond Journey's End", "2023", "Anime", "The quiet masterpiece about what happens after the quest.", ["best-anime-to-watch-now"]),
 ("One Piece", "1999", "Anime", "The longest voyage in shonen — does the journey justify the runtime?", ["one-piece-vs-naruto", "best-anime-to-watch-now"]),
 ("Naruto", "2002", "Anime", "The ninja epic on the other side of the desk's biggest head-to-head.", ["one-piece-vs-naruto", "best-anime-to-watch-now"]),
 ("Hunter x Hunter", "2011", "Anime", "Gon's journey and the Chimera Ant peak — the other half of the Solo Leveling comparison.", ["solo-leveling-vs-hunter-x-hunter-the-similarities-and-differences", "10-anime-like-solo-leveling-you-should-watch"]),
 ("Attack on Titan", "2013", "Anime", "Was Eren really the villain? The desk takes the question seriously.", ["was-eren-yeager-really-the-villain"]),
 ("Jujutsu Kaisen", "2020", "Anime", "Cursed energy, style to spare — a modern shonen benchmark.", ["10-anime-like-solo-leveling-you-should-watch", "best-anime-to-watch-now"]),
 ("Demon Slayer", "2019", "Anime", "One of animation's prettiest sword systems, and a brother to save.", ["10-anime-like-solo-leveling-you-should-watch"]),
 ("Kaiju No. 8", "2024", "Anime", "Monster-fighting with a salaryman's second chance — a Solo Leveling blood relative.", ["10-anime-like-solo-leveling-you-should-watch", "solo-leveling-e-rank-to-s-rank"]),
 ("That Time I Got Reincarnated as a Slime", "2018", "Anime", "Isekai nation-building — the friendly face of the overpowered-rebirth wave.", ["10-anime-like-solo-leveling-you-should-watch", "solo-leveling-e-rank-to-s-rank"]),
 ("Tower of God", "2020", "Anime", "Climb the tower, betray everything — the webtoon ascent pick.", ["10-anime-like-solo-leveling-you-should-watch"]),
 ("Chainsaw Man", "2022", "Anime", "Devil hunting with a chain and a dream — the year's loudest debut.", ["best-anime-to-watch-now"]),
 ("Spirited Away", "2001", "Anime film", "Miyazaki's spirit-world bathhouse — one more scene, forever.", ["7-movies-we-wished-never-ended", "how-to-pick-a-movie-tonight"]),
 ("Your Name", "2016", "Anime film", "The comet, the stairs, the question — the film that converts non-anime viewers.", ["7-movies-we-wished-never-ended"]),
]),
("kdrama", "K-Drama &amp; Korean screen",
"Series and cinema from the desk's deepest shelf — gateway route included.",
[
 ("Squid Game", "2021", "K-drama", "Why season 1 became a global phenomenon — and Agent Kim's season-3 file.", ["squid-game-season-1-why-it-became-a-global-phenomenon", "10-facts-about-agent-kim-squid-game-season-3", "alice-in-borderland-vs-squid-game"]),
 ("Sweet Home", "2020", "K-drama", "Monsters at the doorstep, humans worse inside — the survival-K follow-up.", ["10-shows-like-alice-in-borderland-you-should-watch-next", "10-facts-about-agent-kim-squid-game-season-3"]),
 ("Parasite", "2019", "Korean film", "Bong Joon-ho's staircase comedy-thriller that rewrote the Oscar conversation.", ["10-korean-movies-everyone-should-watch", "korean-cinema-starter-guide-rebuilt", "movies-like-parasite"]),
 ("Memories of Murder", "2003", "Korean film", "The serial-killer procedural that started the Bong dynasty argument.", ["10-korean-movies-everyone-should-watch", "korean-cinema-starter-guide-rebuilt"]),
 ("Oldboy", "2003", "Korean film", "The revenge landmark — corridor fight included.", ["10-korean-movies-everyone-should-watch", "korean-cinema-starter-guide-rebuilt"]),
 ("The Handmaiden", "2016", "Korean film", "Park Chan-wook's most beautiful con, in three acts.", ["10-korean-movies-everyone-should-watch", "korean-cinema-starter-guide-rebuilt"]),
 ("Decision to Leave", "2022", "Korean film", "The detective who falls for the widow — Park's late-career stunner.", ["10-korean-movies-everyone-should-watch", "korean-cinema-starter-guide-rebuilt"]),
 ("Burning", "2018", "Korean film", "The slow-burn mystery that ends on cinema's great unanswered question.", ["10-korean-movies-everyone-should-watch", "korean-cinema-starter-guide-rebuilt"]),
 ("Train to Busan", "2016", "Korean film", "The zombie train that outruns its own genre.", ["10-korean-movies-everyone-should-watch", "korean-cinema-starter-guide-rebuilt"]),
 ("Snowpiercer", "2013", "Korean film", "Class war on rails, in carriage order.", ["10-korean-movies-everyone-should-watch"]),
 ("The Host", "2006", "Korean film", "The creature feature that is really about a family — and a river.", ["10-korean-movies-everyone-should-watch", "korean-cinema-starter-guide-rebuilt"]),
 ("A Taxi Driver", "2017", "Korean film", "A fare into the Gwangju Uprising — the most emotional ride on the list.", ["10-korean-movies-everyone-should-watch"]),
]),
("mind", "Mind-benders, mysteries &amp; Nolan",
"Films that rearrange themselves on rewatch — the desk's order-of-watching guides included.",
[
 ("Memento", "2000", "Film", "The backwards puzzle that started the Nolan conversation.", ["christopher-nolan-movies-order"]),
 ("Inception", "2010", "Film", "The heist inside the dream — the crowd-pleaser that argues with itself.", ["christopher-nolan-movies-order"]),
 ("The Dark Knight", "2008", "Film", "Not science fiction, but pure Nolan craft — the character entry in the order.", ["christopher-nolan-movies-order"]),
 ("Tenet", "2020", "Film", "Inversion as plot and problem — the puzzle box, argued.", ["christopher-nolan-movies-order", "movies-like-interstellar-guide"]),
 ("Dunkirk", "2017", "Film", "Three timelines, one beach — the war film as clockwork.", ["christopher-nolan-movies-order"]),
 ("Oppenheimer", "2023", "Film", "Nolan's three-hour dialogue bomb — where it sits in the viewing order.", ["christopher-nolan-movies-order", "5-movies-that-broke-the-internet"]),
 ("Knives Out", "2019", "Whodunit", "The modern drawing-room murder — a mood pick for a sharp, fun night.", ["how-to-pick-a-movie-tonight"]),
]),
("horror", "Horror &amp; the undead",
"The modern horror starter route and the vampire canon — fear, sorted by feeling.",
[
 ("Get Out", "2017", "Horror", "A smart first door into modern horror — thriller bones, social teeth.", ["modern-horror-starter-route"]),
 ("A Quiet Place", "2018", "Horror", "Silence and attention turned into the main source of pressure.", ["modern-horror-starter-route"]),
 ("Hereditary", "2018", "Horror", "Grief as horror — the route's heavy lift, and worth it.", ["modern-horror-starter-route"]),
 ("Midsommar", "2019", "Horror", "Daylight horror — the breakup film wearing a flower crown.", ["modern-horror-starter-route"]),
 ("The Menu", "2022", "Horror", "Service-industry rage plated as a dinner party — the route's black-comic stop.", ["modern-horror-starter-route"]),
 ("Nope", "2022", "Horror", "The spectacle-observatory — Jordan Peele's UFO western.", ["modern-horror-starter-route"]),
 ("Scream", "1996", "Horror", "The slasher that keeps resurrecting — legacy-sequel lessons included.", ["5-movies-that-broke-the-internet"]),
 ("Nosferatu", "2024", "Vampire", "The gothic original, resurrected — where the vampire era began and returns.", ["modern-horror-starter-route"]),
 ("Interview with the Vampire", "1994", "Vampire", "Vampires as tragic, gorgeous rock stars — the gothic romance era begins here.", ["modern-horror-starter-route"]),
 ("Let the Right One In", "2008", "Vampire", "The Swedish masterpiece that made vampires lonely again.", ["modern-horror-starter-route"]),
]),
("spectacle", "Superhero &amp; spectacle",
"The cameo carnivals, the last stands and the event cinema the internet argues about.",
[
 ("Deadpool &amp; Wolverine", "2024", "Film", "The cameo carnival that broke the internet's rules on purpose.", ["movies-like-deadpool-and-wolverine", "5-movies-that-broke-the-internet"]),
 ("Logan", "2017", "Film", "The superhero western that chose an ending — the no-4 companion pick.", ["movies-like-deadpool-and-wolverine"]),
 ("The Suicide Squad", "2021", "Film", "Rated-super chaos with a soft heart — the do-overs the desk enjoys.", ["movies-like-deadpool-and-wolverine"]),
 ("Free Guy", "2021", "Film", "The NPC who wakes up — videogame comedy with blockbuster manners.", ["movies-like-deadpool-and-wolverine"]),
 ("Spider-Man: No Way Home", "2021", "Film", "The multiverse fan-service event — where the internet actually broke.", ["5-movies-that-broke-the-internet", "movies-like-deadpool-and-wolverine"]),
 ("Barbie", "2023", "Film", "The toy-aisle satire that took over a summer — event cinema by idea, not cape.", ["5-movies-that-broke-the-internet", "7-movies-we-wished-never-ended"]),
 ("Top Gun: Maverick", "2022", "Film", "The legacy sequel that earned its runway — how a 36-year wait paid off.", ["7-movies-we-wished-never-ended", "how-to-pick-a-movie-tonight"]),
]),
("tv", "Box-set &amp; binge TV",
"The series the desk defends — death games, prison breaks and one unfinished argument.",
[
 ("Breaking Bad", "2008", "Series", "Two seasons in, still the best argument on television.", ["breaking-bad-two-seasons-opinion"]),
 ("Prison Break", "2005", "Series", "Season one in one sitting — and why it still holds.", ["why-prison-break-season-1-is-still-one-of-the-best-tv-seasons"]),
 ("Alice in Borderland", "2020", "J-drama", "The death-game cousin of Squid Game — and how they really compare.", ["10-shows-like-alice-in-borderland-you-should-watch-next", "alice-in-borderland-vs-squid-game"]),
 ("Liar Game", "2007", "J-drama", "The con-game ancestor — where the death-game DNA was banked.", ["10-shows-like-alice-in-borderland-you-should-watch-next"]),
 ("Into the Badlands", "2015", "Series", "The underrated martial-arts western the desk defends without irony.", ["into-the-badlands-was-underrated"]),
 ("Money Heist", "2017", "Series", "The gang, the plan, the bells — the heist serial to start after a prison break.", ["why-prison-break-season-1-is-still-one-of-the-best-tv-seasons"]),
]),
("world", "World cinema — Indian, Nigerian &amp; beyond",
"Nollywood, Indian spectacle and the global shelves — the desk's regional starter guides.",
[
 ("RRR", "2022", "Indian cinema", "The maximalist action anthem — the Indian starter five begins with scale.", ["indian-cinema-first-five"]),
 ("Dangal", "2016", "Indian cinema", "Wrestling, daughters, and grounded pressure over spectacle.", ["indian-cinema-first-five"]),
 ("Tumbbad", "2018", "Indian cinema", "Greed as folklore — the Indian horror-treasure curiosity.", ["indian-cinema-first-five"]),
 ("The Black Book", "2023", "Nollywood", "Lagos conspiracy thriller — the Nigerian shelf's modern calling card.", ["nigerian-thrillers-worth-your-time"]),
 ("October 1", "2014", "Nollywood", "Period procedural — colonial Nigeria on the trail of a killer.", ["nigerian-thrillers-worth-your-time"]),
 ("Brotherhood", "2022", "Nollywood", "Twin brothers on opposite sides of the law — action with family stakes.", ["nigerian-thrillers-worth-your-time"]),
]),
]

# per-shelf desk guides, listed under the tiles
CATALOGUE_SHELF_FOOTERS = {
 "fantasy": [("dune-sci-fi-epics-guide", "The Dune & sci-fi epics guide"), ("christopher-nolan-movies-order", "Nolan in order"), ("alien-franchise-in-order", "Alien in order")],
 "anime": [("best-anime-to-watch-now", "The best anime to watch now"), ("anime-canon-and-filler-explained", "Canon & filler, explained"), ("anime-seasons-and-cours-explained", "Seasons & cours, explained")],
 "kdrama": [("best-kdramas-to-start-with", "The K-drama starter route"), ("korean-cinema-starter-guide-rebuilt", "Korean cinema starter guide"), ("10-korean-movies-everyone-should-watch", "Ten Korean films")],
 "mind": [("christopher-nolan-movies-order", "Nolan in order"), ("movies-like-interstellar-guide", "Movies like Interstellar"), ("how-to-pick-a-movie-tonight", "Pick a movie tonight")],
 "horror": [("modern-horror-starter-route", "The modern horror starter route"), ("how-to-build-a-watchlist", "Build a watchlist"), ("how-to-pick-a-movie-tonight", "Pick a movie tonight")],
 "spectacle": [("movies-like-deadpool-and-wolverine", "Movies like Deadpool & Wolverine"), ("5-movies-that-broke-the-internet", "Five that broke the internet")],
 "tv": [("why-prison-break-season-1-is-still-one-of-the-best-tv-seasons", "Prison Break S1, defended"), ("breaking-bad-two-seasons-opinion", "Breaking Bad at two seasons"), ("10-shows-like-alice-in-borderland-you-should-watch-next", "Shows like Alice in Borderland")],
 "world": [("indian-cinema-first-five", "Indian cinema: first five"), ("nigerian-thrillers-worth-your-time", "Nigerian thrillers"), ("best-streaming-apps-nigeria", "Where to stream in Nigeria")],
}

# ---- quick-picks layer (batch 23): desk-curated recommendation starters ----
# These are NOT coverage links — they are honest one-line picks so browsing can
# start a recommendation. Labelled as such on the page; no pretend reviews.
CATALOGUE_STARTERS = {
"fantasy": [
 ("The Lord of the Rings: The Fellowship of the Ring", "2001", "Film", "The quest begins — the template for every world-big fantasy since."),
 ("The Lord of the Rings: The Two Towers", "2002", "Film", "The middle chapter that widens the war and perfects the march."),
 ("The Lord of the Rings: The Return of the King", "2003", "Film", "Eleven Oscars' worth of ending — earn the farewell."),
 ("Harry Potter and the Sorcerer's Stone", "2001", "Film", "The doorway film: the castle, the letters, the world that raised a generation."),
 ("The Matrix", "1999", "Film", "The red pill, the bullet time, the simulation argument that ate pop culture."),
 ("The Empire Strikes Back", "1980", "Film", "The sequel that outran its original and taught blockbusters to be dark."),
 ("Blade Runner", "1982", "Film", "Rain, neon, and what counts as a person — sci-fi's great mood."),
 ("Back to the Future", "1985", "Film", "The perfect time-travel plot: setup, payoff, DeLorean."),
 ("Jurassic Park", "1993", "Film", "The theme park that broke the world — spectacle with a brain."),
 ("Terminator 2: Judgment Day", "1991", "Film", "The action sequel that flipped its villain into its protector."),
 ("Edge of Tomorrow", "2014", "Film", "Live, die, repeat — the time-loop war movie that never drags."),
 ("District 9", "2009", "Film", "Aliens parked over Johannesburg — satire with exoskeletons."),
 ("Ex Machina", "2014", "Film", "One house, one test, one AI — the quietest thriller about consciousness."),
 ("Pan's Labyrinth", "2006", "Film", "Fairy tale as war story — beautiful and merciless."),
 ("The Princess Bride", "1987", "Film", "As you wish — the swashbuckler everyone quotes."),
 ("Stardust", "2007", "Film", "A fallen star, a witch, a sky pirate — fantasy comfort food."),
 ("The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", "2005", "Film", "The wardrobe, the winter, the lion — the classic gateway fantasy."),
 ("Game of Thrones", "2011", "Series", "The show that made fantasy prestige television — winter came."),
 ("House of the Dragon", "2022", "Series", "Targaryens at their own throats — the family road to ruin."),
 ("The Witcher", "2019", "Series", "Monster contracts and destiny paperwork — the bingeable sword-and-sorcery."),
],
"anime": [
 ("Death Note", "2006", "Anime", "A notebook that kills and the two geniuses circling it — the gateway thriller."),
 ("Fullmetal Alchemist: Brotherhood", "2009", "Anime", "Two brothers versus equivalent exchange — the all-timer plot."),
 ("Steins;Gate", "2011", "Anime", "A microwave that texts the past — the time-travel gut-punch."),
 ("Code Geass", "2006", "Anime", "Chess-player rebellion with a masked leader — plan-within-plan drama."),
 ("Cowboy Bebop", "1998", "Anime", "Bounty hunters, jazz, and style that never ages — see you, space cowboy."),
 ("Akira", "1988", "Anime", "Neo-Tokyo exploding in hand-drawn frame after frame — the landmark."),
 ("My Hero Academia", "2016", "Anime", "A quirkless kid inherits the greatest power — the shonen school formula done proud."),
 ("Vinland Saga", "2019", "Anime", "Vikings, revenge, and a slow lesson about violence — the epic with a conscience."),
 ("Spy x Family", "2022", "Anime", "Spy dad, assassin mum, telepathic kid — the found-family comfort hit."),
 ("Dr. Stone", "2019", "Anime", "Rebuild all of science from a stone-age start — the optimism engine."),
 ("Tokyo Ghoul", "2014", "Anime", "Half-human, half-ghoul, all identity crisis — the dark classic."),
 ("Haikyu!!", "2014", "Anime", "Volleyball, velocity, and the best teamwork writing in sports anime."),
 ("Blue Lock", "2022", "Anime", "Three hundred strikers, one spot — football as battle royale."),
 ("One Punch Man", "2015", "Anime", "The strongest hero, bored — the parody with blockbuster fight animation."),
 ("Mob Psycho 100", "2016", "Anime", "An overpowered teen who just wants to be better at being a person."),
 ("Mushoku Tensei: Jobless Reincarnation", "2021", "Anime", "The isekai rebirth done with novel-grade worldbuilding."),
 ("Made in Abyss", "2017", "Anime", "A cute art style hiding the deepest cruelty in adventure fiction."),
 ("A Silent Voice", "2016", "Anime film", "Bullying, deafness, forgiveness — the redemptive tearjerker."),
 ("Princess Mononoke", "1997", "Anime film", "Gods versus industry — Miyazaki's fiercest forest."),
 ("My Neighbor Totoro", "1988", "Anime film", "The gentlest film about moving house ever made."),
 ("Perfect Blue", "1997", "Anime film", "Idols, stalkers, dissolving identity — the psychological thriller that influenced a decade of cinema."),
 ("Weathering with You", "2019", "Anime film", "Love versus the weather — Shinkai's rain-soaked follow-up."),
],
"kdrama": [
 ("Crash Landing on You", "2019", "K-drama", "A paraglider, a border, a captain — the romance phenomenon."),
 ("Goblin", "2016", "K-drama", "An immortal soldier seeking his bride — the fantasy-romance benchmark."),
 ("Mr. Sunshine", "2018", "K-drama", "1900s Joseon, a US Marine, and the most beautiful melancholy on television."),
 ("Vincenzo", "2021", "K-drama", "Mafia consigliere versus chaebol villains — dark comedy with a full course of revenge."),
 ("My Mister", "2018", "K-drama", "Three brothers and a wiretap — the quiet masterpiece about kindness."),
 ("Extraordinary Attorney Woo", "2022", "K-drama", "A brilliant autistic lawyer and whale metaphors — the warmth wave."),
 ("Hospital Playlist", "2020", "K-drama", "Five doctors, one band, twenty years of friendship — the comfort slice."),
 ("Reply 1988", "2015", "K-drama", "One alley, five families, pure nostalgia — the neighbourhood classic."),
 ("Itaewon Class", "2020", "K-drama", "A bar, a grudge, a decade-long plan for revenge — the underdog entrepreneurial hit."),
 ("Signal", "2016", "K-drama", "A walkie-talkie across time solving cold cases — the procedural with feelings."),
 ("Kingdom", "2019", "K-drama", "Zombies in the Joseon court — period politics meets the undead."),
 ("The Glory", "2022", "K-drama", "Bullying revenge planned over decades — the coldest slow burn."),
 ("Weak Hero Class 1", "2022", "K-drama", "A small strategist in a brutal school — the tension machine."),
 ("Twenty-Five Twenty-One", "2022", "K-drama", "Fencing, first love, and the IMF era — the bittersweet youth romance."),
 ("Hometown Cha-Cha-Cha", "2021", "K-drama", "Seaside village, useless-charming handyman — the healing romance."),
 ("Business Proposal", "2022", "K-drama", "Blind date mistaken for a CEO — the office romcom at full speed."),
 ("Alchemy of Souls", "2022", "K-drama", "Soul-swapping mages in a high-fantasy Joseon — the worldbuilding pick."),
 ("Mr. Queen", "2020", "K-drama", "A modern chef in a queen's body — the comedy that shouldn't work and does."),
 ("D.P.", "2021", "K-drama", "Deserters chased and understood — the military drama with teeth."),
 ("Move to Heaven", "2021", "K-drama", "Trauma cleaners and the lives objects leave behind — the cry-angler."),
],
"mind": [
 ("Shutter Island", "2010", "Film", "A missing patient and an unreliable island — the twist that rewrites the case."),
 ("The Sixth Sense", "1999", "Film", "I see dead people — the reveal that made twist endings a spectator sport."),
 ("Fight Club", "1999", "Film", "Insomnia, soap, and the rule you never talk about."),
 ("The Prestige", "2006", "Film", "Two magicians, one secret — the obsession film with a triple turn."),
 ("Donnie Darko", "2001", "Film", "A giant rabbit, a falling engine, 28 days — the cult time-loop."),
 ("The Truman Show", "1998", "Film", "A life broadcast without consent — the sunny existential escape."),
 ("Source Code", "2011", "Film", "Eight minutes on a train, over and over — the tight loop thriller."),
 ("Looper", "2012", "Film", "Hitmen who close their own loops — time travel with consequences."),
 ("Gone Girl", "2014", "Film", "A missing wife and a diary — the marriage autopsy."),
 ("Se7en", "1995", "Film", "Two detectives, seven sins, one box — the procedural that ends cold."),
 ("Zodiac", "2007", "Film", "The case that eats its hunters — obsession as procedure."),
 ("Prisoners", "2013", "Film", "Two fathers, one kidnapping, moral freefall — the winter thriller."),
 ("Coherence", "2013", "Film", "A dinner party, a comet, sliding doors — micro-budget mind-bender."),
 ("Predestination", "2014", "Film", "The snake eats its tail — the paradox done properly."),
],
"horror": [
 ("The Shining", "1980", "Horror", "A winter hotel and a father unravelling — all work and no play."),
 ("Psycho", "1960", "Horror", "The shower, the motive, the mother — where modern horror begins."),
 ("Halloween", "1978", "Horror", "The Shape, the suburbs, the night he came home — slasher zero."),
 ("The Exorcist", "1973", "Horror", "Possession as ordeal — still the genre's feared standard."),
 ("It", "2017", "Horror", "A town, a clown, a losers' club — the coming-of-age creature hit."),
 ("The Conjuring", "2013", "Horror", "The haunted-house franchise starter — craft over gore."),
 ("Insidious", "2010", "Horror", "The Further — jump-scare architecture done clean."),
 ("The Ring", "2002", "Horror", "Seven days after the tape — the J-horror wave, Americanised."),
 ("Us", "2019", "Horror", "Doppelgängers with scissors — Peele's national funhouse mirror."),
 ("It Follows", "2014", "Horror", "A shape that walks — dread as a slow, steady pace."),
 ("The Babadook", "2014", "Horror", "Grief as a pop-up book monster — the art-horror landmark."),
 ("Talk to Me", "2022", "Horror", "An embalmed hand, a sixty-second high — the possession party gone wrong."),
 ("Barbarian", "2022", "Horror", "A double-booked Detroit house — the structure-is-the-scare thriller."),
 ("Sinister", "2012", "Horror", "Home movies that should stay unwatched — the found-footage-flavoured dread."),
 ("Annihilation", "2018", "Horror", "Area X refracts everything that enters — sci-fi horror as self-destruction."),
 ("28 Days Later", "2002", "Horror", "Empty London, rage-infected runners — the zombie reset."),
 ("The Descent", "2005", "Horror", "Six women, one cave system, no width to scream in."),
],
"spectacle": [
 ("Batman Begins", "2005", "Film", "The reboot that taught capes to be serious — fear as a weapon."),
 ("The Dark Knight Rises", "2012", "Film", "Bane, the pit, and the biggest ending in the trilogy."),
 ("Iron Man", "2008", "Film", "A genius in a cave — the launch frame of a universe."),
 ("The Avengers", "2012", "Film", "The team-up that proved the experiment — kebab after."),
 ("Avengers: Infinity War", "2018", "Film", "Thanos collects — the empire-strikes ending for a generation."),
 ("Avengers: Endgame", "2019", "Film", "The reassemble-and-avenge finale — the biggest curtain call."),
 ("Guardians of the Galaxy", "2014", "Film", "A mixtape, a ragtag crew — comedy cosmic saved the slate."),
 ("Thor: Ragnarok", "2017", "Film", "The gladiator rainbow reboot — the funniest Thor by miles."),
 ("Spider-Man: Into the Spider-Verse", "2018", "Film", "Every frame a comic panel — the animation that rewired the genre."),
 ("Wonder Woman", "2017", "Film", "No man's land — the war-front entrance that landed."),
 ("Man of Steel", "2013", "Film", "Superman with weight and wrecking balls — the divisive origin."),
 ("X-Men: Days of Future Past", "2014", "Film", "Two timelines, one reset — the franchise-fixing time travel."),
 ("Mad Max: Fury Road", "2015", "Film", "Two hours of forward momentum — the action masterclass."),
 ("John Wick", "2014", "Film", "They took his dog — the cleanest action premise ever built."),
 ("Mission: Impossible – Fallout", "2018", "Film", "Practical stunts at terminal velocity — the series' peak."),
 ("Gladiator", "2000", "Film", "Are you not entertained — the sword-and-sandal revenge epic."),
],
"tv": [
 ("Game of Thrones", "2011", "Series", "Nine families, one throne — the water-cooler colossus."),
 ("The Last of Us", "2023", "Series", "A fungus apocalypse, a smuggler, a girl — the game adaptation that cleared the curse."),
 ("Stranger Things", "2016", "Series", "The Upside Down, the bikes, the 80s — the nostalgia juggernaut."),
 ("Severance", "2022", "Series", "Work-life balance via brain surgery — the office mystery box."),
 ("The Boys", "2019", "Series", "Supes as celebrities with bodies to hide — the genre's id."),
 ("Chernobyl", "2019", "Series", "What is the cost of lies — five hours of procedural dread."),
 ("Peaky Blinders", "2013", "Series", "Flat caps, razor parties, family empire — the gangland rise."),
 ("Sherlock", "2010", "Series", "The deducing detective in the smartphone age — three-episode bursts of speed."),
 ("Lupin", "2021", "Series", "A gentleman thief avenges his father in Paris — the slick heist serial."),
 ("True Detective", "2014", "Series", "Two detectives, seventeen years, one cult — season one's long shadow."),
 ("Better Call Saul", "2015", "Series", "How Jimmy becomes Saul — the tragedy of small compromises."),
 ("The Queen's Gambit", "2020", "Series", "Chess, pills, and genius — the checkered triumph."),
 ("Arcane", "2021", "Series", "Two sisters between a city and under-city — the animated marvel."),
 ("Invincible", "2021", "Series", "The superhero cartoon that goes where the capes bleed."),
 ("Dark", "2017", "Series", "Four families, three time zones, one cave — the German knot."),
 ("Black Mirror", "2011", "Series", "Technology as horror anthology — each episode a new panic."),
 ("Mr. Robot", "2015", "Series", "Hackers, corporations, unreliable everything — the paranoid landmark."),
],
"world": [
 ("3 Idiots", "2009", "Indian cinema", "Engineering college, one dare: chase excellence — the crowd-pleasing classic."),
 ("Lagaan", "2001", "Indian cinema", "Villagers versus the Empire at cricket — the underdog musical epic."),
 ("Gangs of Wasseypur", "2012", "Indian cinema", "Two families, decades of feud — the crime saga with songs and swagger."),
 ("Andhadhun", "2018", "Indian cinema", "A blind pianist who sees too much — the twist labyrinth."),
 ("Baahubali: The Beginning", "2015", "Indian cinema", "Why did Kattappa do it — the spectacle question that filled stadiums."),
 ("Queen", "2013", "Indian cinema", "A honeymoon alone becomes a self-found road — the joyful one."),
 ("King of Boys", "2018", "Nollywood", "Lagos business, underworld ambitions — the Eniola Salami saga."),
 ("The Wedding Party", "2016", "Nollywood", "One society wedding, everything that can go wrong — the record-setting comedy."),
 ("Oloture", "2019", "Nollywood", "An undercover journalist in a trafficking ring — the investigative gut-punch."),
 ("The Set Up", "2019", "Nollywood", "A heist that outgrows its crew — the slick conspiracy thriller."),
 ("Anikulapo", "2022", "Nollywood", "A mystical resurrector bird in the old Oyo empire — the folklore epic."),
 ("Citation", "2020", "Nollywood", "A student fights back against a professor — the #MeToo campus drama."),
 ("93 Days", "2016", "Nollywood", "The Ebola containment story — Lagos against the clock."),
 ("City of God", "2002", "World cinema", "Two boys, one favela, endless exits closing — the Brazilian landmark."),
 ("Amélie", "2001", "World cinema", "A Montmartre waitress engineers strangers' happiness — the whimsical classic."),
 ("Infernal Affairs", "2002", "World cinema", "Mole versus mole in the Hong Kong police — the identity tension Scorsese remade."),
 ("Roma", "2018", "World cinema", "A year with a household in 1970s Mexico City — the memory masterpiece."),
],
}
