"""BRYME Fitness - expansion batch (Sept 2026): ten beginner-first guides that
fill the desk's real gaps - progressions, form depth, soreness literacy,
equipment honesty and food-first protein. Same rules as the rest of the desk:
general information, never medical advice, no miracle claims, medical
boundaries stated plainly. Body links are root-level by convention;
build-routing prefixes them with /fitness/ on the routed tree."""

FIT_MORE_2 = [
("push-up-progression", "guide",
"From wall to full: the push-up progression that actually works",
"The honest ladder from wall push-ups to full-floor reps - each step defined, each step earned, no jumping ahead.",
"""<p>Most people fail at push-ups for one reason: they start at the version they cannot do yet, grind out three ugly reps, and quit. The fix is a ladder. Every rung below is a real exercise - you can build genuine strength on any one of them - and you only climb when the current rung says so.</p>
<h2>The five rungs</h2>
<p><b>1. Wall push-ups.</b> Stand arm's length from a wall, hands at chest height and slightly wider than shoulders. Lower your chest to the wall, press back. The body stays straight from head to heel - the wall version exists to teach that line. Start at three sets of eight.</p>
<p><b>2. Incline push-ups.</b> Hands on a table, then a chair, then a low step - the lower the surface, the harder the rep. The rule that matters: hips in line with shoulders, no piking. When you can do three sets of ten on a surface, drop the surface height.</p>
<p><b>3. Knee push-ups.</b> Knees on the floor, feet up or down - pick one and keep it consistent. Everything from the knees to the head moves as one plank. Three sets of eight here is the gate to the next rung, not three reps of grinding.</p>
<p><b>4. Negative push-ups.</b> Start at the top, lower yourself as slowly as you can - three to five seconds - then reset. Lowering is where most strength is built, and negatives let you practise the full-range path while it is still too heavy to lift back up.</p>
<p><b>5. Full push-ups.</b> First rep usually arrives in weeks, not months, if the rungs were honest. Then the game changes: more reps, feet elevated, slower tempos.</p>
<h2>The rules that make it work</h2>
<p>Train the progression two to three times a week, not daily - the strength is built between sessions, not during them (see <a href="/rest-days-and-recovery/">rest days and recovery</a>). Log your sets; the ladder only works if you know which rung you are on. One clean rep at a harder rung beats five sloppy ones at an easier rung - a sagging hip or a shrugging shoulder is a downgrade no matter what your hands are doing. And the plank is not separate homework: the body line you practise in <a href="/how-to-plank/">the plank</a> is the same line every push-up lives and dies by.</p>
<h2>When it stalls</h2>
<p>Stalls are normal and usually mean one of three things: you jumped rungs, you stopped adding reps, or you are sleeping like it does not matter (<a href="/sleep-and-exercise-performance/">it does</a>). Stay at the rung, add one rep per set per week, and let <a href="/how-progressive-overload-works/">progressive overload</a> do what it always does - slowly.</p>
<p>General information, not medical advice. Chest, shoulder or arm pain that is not muscular - or anything that feels wrong rather than merely hard - is a stop and a professional conversation, not a gritted-teeth situation.</p>"""),
("squat-form-beginners", "guide",
"The beginner's squat: six checkpoints and the chair trick",
"Depth, heels, knees and the box-squat method - the form guide that starts where you actually are.",
"""<p>The squat is the one movement pattern you already own - you perform it every time you sit down. Training it is just adding load and range to something familiar. What wrecks beginners is not weakness; it is skipping the checkpoints and hopping to depth before the pattern is stable.</p>
<h2>The six checkpoints</h2>
<p><b>Feet:</b> shoulder-width, toes turned out 15 to 30 degrees - whatever lets your knees track over your toes without twisting. <b>Weight:</b> mid-foot, whole foot gripping the floor - not the toes, not the heels as a religion. <b>Brace:</b> a small breath in, stomach firm like bracing for a nudge. <b>Chest:</b> proud, not arched - the torso hinges forward naturally as you go down; a collapse is different from a hinge. <b>Knees:</b> travelling in the same direction as the toes, out over the little toes, never caving inward. <b>Depth:</b> as deep as you can control with a flat back - hips at or below knee height for most people, and less is fine while you earn it.</p>
<h2>The chair trick (use it for a week)</h2>
<p>Stand in front of a chair facing away. Sit down slowly - three seconds - and stand up without using your hands or plopping. That is a box squat, and it teaches the whole pattern: the lean, the knee track, the controlled descent. Lower the chair height over a week or two and you will arrive at a full squat without ever having flailed at one.</p>
<h2>Three honest notes</h2>
<p><b>Knees over toes is fine.</b> The knees-passing-the-toes scare is gym folklore; knees travel forward in every deep squat in every culture. The thing to police is knees caving <em>inward</em>, not forward. <b>Sore thighs the next day are the pattern working</b> - see <a href="/muscle-soreness-vs-injury/">soreness versus injury</a> for the difference. <b>Depth without control is not depth.</b> A half squat you own beats a wobbly full squat you fake.</p>
<h2>Where it fits</h2>
<p>Two or three times a week inside <a href="/strength-training-for-beginners/">the beginner strength pattern</a>, progressed by reps first and then by load - backpack, then anything with a handle - exactly as <a href="/how-progressive-overload-works/">progressive overload</a> describes. The <a href="/exercise-library-legs/">leg exercise library</a> carries the variations when the basic pattern is boring you, and boredom is a training problem worth solving.</p>
<p>General information, not medical advice. Sharp joint pain, clicking with pain, or anything that feels structural rather than muscular: stop and ask a professional.</p>"""),
("muscle-soreness-vs-injury", "guide",
"Sore or injured? The difference every beginner needs to read",
"DOMS explained honestly, the red flags that are not soreness, and the stop rules that keep a beginner in the game.",
"""<p>Beginners quit for two opposite reasons: they feel sore and think they are injured, or they are injured and think they are just sore. Both are literacy problems. Here is the plain-language version.</p>
<h2>Normal soreness (DOMS)</h2>
<p>Delayed onset muscle soreness is the dull, symmetrical, both-sides ache that peaks one to two days after new or harder training and fades within about a week. It is strongest after exercises your body has not met before, worse when the movement lowers weight slowly (negatives, long descents), and it does not mean damage is being done - it mostly means the session was new. It feels <em>tender</em>: worse when you stretch or use the muscle, better once you are moving and warm. Walking, easy movement, light activity and sleep are the treatment; waiting is the cure. Training the sore muscle lightly is fine - training it hard again is counterproductive until the ache clearly fades.</p>
<h2>What soreness is not</h2>
<p><b>Sharp pain at a specific point</b> - a pinpoint in a joint, a stab during one part of a movement - is not DOMS. <b>Pain that arrived during the session</b>, mid-rep, with a pop, a tweak or a sudden wrongness, is not DOMS. <b>Swelling, bruising, a joint that will not bear weight or move through its range</b> is not DOMS. <b>Pain that gets worse day by day</b> instead of better is not DOMS. None of these need gritted teeth; they need stopping and, honestly, a professional - which is not a failure, it is the same maintenance mindset the home desk applies to a house.</p>
<h2>The stop rules</h2>
<p>Stop a set when form degrades, not when discomfort arrives - burning muscles are normal, wrong-feeling joints are not. Skip a workout when soreness changes how you move; train around a sore body part rather than through it. And the rule that outranks everything: pain that is sharp, worsening, localised to a joint, or accompanied by swelling gets assessed before it gets trained around again. Fitness is a decades-long project; three quiet days now is the cheap version of every alternative.</p>
<h2>Prevention, honestly</h2>
<p>Warm up properly (<a href="/how-to-warm-up/">the covering-a-shoulders-to-hamstrings version</a>), progress slowly (<a href="/how-progressive-overload-works/">small jumps</a>), keep the surprising-new-exercise spikes rare, and treat <a href="/sleep-and-exercise-performance/">sleep</a> as part of the programme. Soreness will still visit - it just will not be a mystery, and it will not make your decisions for you.</p>
<p>General information, not medical advice, and deliberately not a diagnosis tool. When in doubt, a professional looks at it; that is always the right call.</p>"""),
("resistance-bands-guide", "guide",
"Resistance bands: the cheapest honest gym you can buy",
"What bands do well, what they do badly, how tension really works, and six movement patterns that cover the whole body.",
"""<p>A set of resistance bands costs less than a month of most gyms, fits in a drawer, and covers every fundamental movement pattern. That is not marketing; it is mechanics. It is also not a claim that bands replace everything - they have real limits, stated plainly below.</p>
<h2>How band tension actually works</h2>
<p>Weights are heaviest at the bottom of a rep and constant through the range. Bands are the opposite: relaxed at the start, hardest at the end, when the band is longest under stretch. That changes the feel (easier to start, brutal to finish) and it is why the last third of every band rep is where the growth lives. The practical rule: control the return stroke - never let the band snap you back - because the lowering half is where the work hides, the same principle <a href="/push-up-progression/">the push-up ladder</a> uses.</p>
<h2>What to buy (little, and once)</h2>
<p>A loop/mini-band set plus a long tube band with handles covers everything a beginner needs. Colour codes are not standardised between brands - a red band from one maker can be lighter than a yellow from another - so buy by stated resistance or by trying, never by colour. A door anchor multiplies the exercises, cheaply. Skip anything with metal hooks that can snap toward your face; fabric-loop bands last longer than latex and do not roll.</p>
<h2>Six patterns, whole body</h2>
<p><b>Push:</b> band behind the back, press forward (bench-press pattern). <b>Pull:</b> anchored band, row toward the ribs - the pattern most desk-bound lives are missing. <b>Squat:</b> band under feet, handles at shoulders (<a href="/squat-form-beginners/">same six checkpoints</a>). <b>Hinge:</b> anchored low, pull through the hips - the deadlift pattern without a barbell. <b>Overhead press:</b> stand on the band, press up. <b>Rotate/carry:</b> anchored band anti-rotation holds, which quietly train the core harder than most crunch routines.</p>
<h2>The honest limits</h2>
<p>Bands are awkward to load very heavy - leg and back strength eventually outgrows them, which is a good problem that arrives after months of progress. Resistance is hard to measure precisely, so progression is by reps, tempo and band thickness rather than kilograms - the same logic as <a href="/how-progressive-overload-works/">overload</a>, different dial. And bands wear out: inspect for nicks and tears, and retire a band before it retires itself mid-set.</p>
<p>Two or three full-body sessions a week with the six patterns satisfies the strength guideline for a long time (<a href="/strength-training-for-beginners/">the structure</a>), and pairs perfectly with <a href="/workout-at-home-no-equipment/">the no-equipment set</a> for days when even the drawer feels far away.</p>
<p>General information, not medical advice. A band snapping is a nuisance; check anchors and skin, and keep your face out of the line of any stretched band.</p>"""),
("stretching-before-or-after", "guide",
"Stretching before or after? Both - just not the same kind",
"Dynamic movement before, static stretching after: what the evidence actually says, minus the folklore.",
"""<p>The oldest argument in the gym - stretch or don't stretch - dissolves once you stop treating stretching as one thing. There are two distinct tools, and the only real mistake is using them at the wrong time.</p>
<h2>Before: move, do not hold</h2>
<p>Long static holds before training - the bent-over toe touch held for thirty seconds - are the folklore part. Held stretches before heavy effort can temporarily reduce force production and do very little to prevent injury on their own. What a warm-up actually needs is <b>dynamic movement</b>: leg swings, arm circles, walking lunges, gentle versions of the exercises you are about to do. That raises temperature, moves joints through their range and rehearses the patterns - which is exactly what <a href="/how-to-warm-up/">the covering warm-up</a> is built from. Think of it as rehearsal, not lengthening.</p>
<h2>After: hold, gently</h2>
<p>Static stretching - the classic held stretches - belongs after training, or as its own session. Evidence for it as an injury-prevention shield is weaker than most people assume, but for range of motion and the simple, underrated act of downshifting after effort, it earns its place. Hold each stretch 20 to 30 seconds, to tension not pain, breathe, and do not bounce. Calves, hip flexors, hamstrings, chest and hip-glute stretches cover most bodies most of the time.</p>
<h2>What flexibility is really for</h2>
<p>Stretching will not spot-reduce soreness - <a href="/muscle-soreness-vs-injury/">DOMS</a> fades on its own schedule, and stretching a very sore muscle hard usually feels worse, not better. It will not replace strength work; range without control is just a longer fall. The honest case for it: it maintains the range your training and your desk are quietly stealing, it feels better than stiffness, and ten quiet minutes after a session is the easiest habit in fitness to keep.</p>
<h2>The one-line version</h2>
<p>Move before. Hold after. Warm up with purpose (<a href="/how-to-warm-up/">the method</a>), train the patterns (<a href="/strength-training-for-beginners/">beginner strength</a>), and let the held stretches be the cool-down, not the rehearsal.</p>
<p>General information, not medical advice. Stretching should never chase pain, and post-injury flexibility work belongs to the professional treating it.</p>"""),
("protein-foods-nigeria", "guide",
"Protein on a Nigerian plate: food first, powder never required",
"Eggs, beans, fish, chicken, groundnut, crayfish - what a portion looks like on a real plate, and how to reach your day without imported anything.",
"""<p>The protein conversation online starts with a scoop and a shaker. It should start with a market list. Nigerian kitchens already sit on some of the cheapest complete and complementary protein sources anywhere - the gap is usually knowing what a portion looks like, not affording a tub of imported powder.</p>
<h2>What your day actually needs</h2>
<p>For most adults, the baseline is roughly 0.8 grams of protein per kilogram of body weight per day, and people training for strength aim higher - the honest ranges and the maths live in <a href="/how-much-protein-do-you-need/">Protein, honestly</a>. The number matters less than the pattern: some protein at each meal beats one enormous dinner, because your plate is a rhythm, not a single event.</p>
<h2>The plate, in real portions</h2>
<p><b>Eggs:</b> about 6 g each - two eggs is a breakfast anchor. <b>Beans</b> (cooked, in porridge, as moi-moi or akara): roughly 15-18 g per generous cup, plus the fibre everything else in your day is missing. <b>Fish</b> - mackerel (titus), croaker, sardines: around 20 g per palm-sized piece, with the oils as a bonus. <b>Chicken</b> (thigh as much as breast): about 25 g per palm-and-a-half portion. <b>Groundnut/peanuts:</b> a small handful is 7-8 g and useful, though calorie-dense - the handful, not the bag. <b>Crayfish, ground and scattered in stews:</b> a quiet protein multiplier in the pots that already feed you. <b>Milk or yoghurt:</b> about 8 g per cup where it fits. <b>Green peas and soy (in togba/warà forms):</b> respectable supporting numbers.</p>
<h2>Combining without obsessing</h2>
<p>Animal sources are complete; plant sources each have a gap - beans are low in one set of building blocks, grains in another - and the classic pairings your kitchen already uses (beans and garri/agege, rice and beans, ewa agoyin with bread) close them. You do not need perfection in a single meal, just variety across the day and week. That is the whole science of combining, stated in market terms.</p>
<h2>Where powder fits (spoiler: it is optional)</h2>
<p>A scoop is convenient on the heaviest training days and genuinely useful when appetite, budget or schedule makes food targets hard - but it is food with marketing, not a category of its own. Every gram it offers, the plate above offers cheaper. Spend the difference on eggs and fish.</p>
<h2>The honest pattern that works</h2>
<p>Anchor each meal with one protein source, keep eggs in permanent rotation, let beans carry the days money is tight, and check your weekly average rather than today's perfection - the same rhythm argument <a href="/how-much-protein-do-you-need/">the protein guide</a> makes. Training gives the protein a job; the <a href="/strength-training-for-beginners/">beginner strength pattern</a> is where that job gets assigned.</p>
<p>General information, not medical or dietary advice. Kidney conditions, pregnancy and specific medical diets change the targets - those conversations belong to a clinician who can see your history.</p>"""),
("beginner-running-plan", "guide",
"Zero to 30 minutes of running: an eight-week walk-run plan",
"Walk, then run, then walk again - the honest build from the sofa to thirty continuous minutes, with rest built in.",
"""<p>Every injured beginner runner made the same mistake: they ran for as long as enthusiasm lasted, on day one. The walk-run method exists because it works with the way bodies adapt - short running bursts inside walks, the bursts growing weekly, until one day the walks quietly disappear. Eight weeks is the honest average; taking ten is not failure, it is the same plan respecting your legs.</p>
<h2>The shape of the plan</h2>
<p>Three sessions a week - never back-to-back, because <a href="/rest-days-and-recovery/">rest days</a> are where the adaptation happens - plus the walking you already do. Each session: five minutes of brisk walking to warm up (<a href="/how-to-warm-up/">why the warm-up matters</a>), then the week's pattern, then five minutes of easy walking to finish.</p>
<p><b>Weeks 1-2:</b> run 1 minute, walk 2 minutes - repeat 7 times. <b>Week 3:</b> run 2, walk 2, x6. <b>Week 4:</b> run 3, walk 2, x5. <b>Week 5:</b> run 5, walk 2, x4. <b>Week 6:</b> run 8, walk 2, x3. <b>Week 7:</b> run 12, walk 2, x2, then run 5 more. <b>Week 8:</b> run 20 continuous. Somewhere in the week after: 30.</p>
<h2>The pace that makes it work</h2>
<p>Run slowly. Slower than that. The test is the talk test - you should be able to speak a full sentence while running; if you cannot, you are jogging your sprints and the plan will collapse into <a href="/muscle-soreness-vs-injury/">soreness, stalling or shins</a>. Speed is a later-year project; week one to week eight has exactly one job, and it is minutes, not minutes-per-kilometre.</p>
<h2>The two honest warnings</h2>
<p><b>Shins and knees complain before they fail.</b> Aches that fade during a warm-up are normal; pain that sharpens as you run, or is there the next morning at step-out-of-bed, is the stop-and-scale-back signal - repeat the previous week rather than pushing through. <b>Shoes are the one purchase.</b> You do not need a watch, kit or app; you need cushioned shoes with room for your toes, and a surface that is not concrete if you have a choice.</p>
<h2>Where this fits the desk</h2>
<p>This is the running-side companion to <a href="/30-day-walking-plan/">the 30-day walking plan</a> - walkers graduate here, and repeat runners use it as the return-from-a-break template. The full comparison of the two modes lives in <a href="/walking-vs-running/">walking or running</a>, and the breathing that feels impossible in week one is just <a href="/breathing-during-exercise/">breathing during exercise</a> at a harder tempo - it settles.</p>
<p>General information, not medical advice. A check-up before starting is the sensible move if you have heart risk factors, joint problems, a long sedentary history, or any doubt at all.</p>"""),
("morning-or-evening-workout", "guide",
"Morning or evening workouts? The honest answer is boring",
"Performance peaks in the evening, habit formation favours the morning - and consistency beats both. Here is how to actually choose.",
"""<p>The internet has strong opinions about workout timing. The research has a mild, well-replicated finding and a very boring truth. Here is both, so you can stop searching and start training.</p>
<h2>What the evidence says</h2>
<p>On raw performance, the body is measurably stronger and faster in the late afternoon and early evening - body temperature, nerve conduction and reaction time all peak roughly then, and studies of strength and power tend to find their best numbers in that window. On habit formation, morning exercisers stick with it better in most adherence research: the day has not yet had a chance to steal the slot, and willpower is freshest before decisions pile up. Both findings are real. They point in different directions on purpose - one measures a single session, the other measures months.</p>
<h2>The boring truth</h2>
<p>Across weeks and months, the timing you can repeat is the timing that wins, and total weekly volume beats circadian optimisation by a distance nobody has measured with a microscope. A slightly weaker evening session done fifty times a year demolishes a physiologically perfect morning session done eleven times. The evidence-aware position: if you already train consistently, carry on; if you are choosing, pick the slot your actual life protects - not the one a stranger's routine protects.</p>
<h2>Practical notes for each camp</h2>
<p><b>Morning people:</b> your spine and tissues are stiffer at dawn - spend an extra three to five minutes on the warm-up (<a href="/how-to-warm-up/">the covering version</a>), and eat or at least sip something before anything hard. Early sessions also make the <a href="/sleep-and-exercise-performance/">sleep</a> story easier: hard training too close to bedtime pushes it around. <b>Evening people:</b> you will hit your best numbers and should still keep a hard-session cut-off two to three hours before bed. After-work sessions run on pre-planned food - the 4pm hunger crash kills more evening workouts than laziness ever did.</p>
<h2>What never changes</h2>
<p>Progressive overload does not care what time it is (<a href="/how-progressive-overload-works/">the mechanism</a>), rest days do not move (<a href="/rest-days-and-recovery/">the recovery rules</a>), and the <a href="/30-day-walking-plan/">thirty-day habit machine</a> works at any hour you show up. Choose a slot, protect it for a month, and let the calendar - not the clock - make the argument.</p>
<p>General information, not medical advice.</p>"""),
("fitness-trackers-worth-it", "guide",
"Fitness trackers: what they measure well, what they guess, and who needs one",
"Steps and heart rate are solid; calories burned is a costume. An honest buyer's guide by budget, with the free alternative stated first.",
"""<p>The first honest thing to say about fitness trackers: the most important number they count - steps - is already in your pocket. A phone in a pocket or hand counts steps almost as well as a wrist device, for free. A tracker earns its price only after that, so let's price it honestly.</p>
<h2>What trackers measure well</h2>
<p><b>Steps:</b> good on the wrist, very good enough. <b>Heart rate:</b> optical wrist sensors are genuinely useful for spotting effort trends - resting heart rate drifting down over months of training is real, measurable progress - though they lag during brief intervals. <b>Sleep duration:</b> decent at the when-and-how-long, weaker at the sleep-stages story, which is part measurement and part educated guess. <b>The daily pattern:</b> the quiet superpower - a tracker's real value is not any single number, it is the trend lines that make you notice a sedentary Tuesday you would have ignored.</p>
<h2>What they guess</h2>
<p><b>Calories burned:</b> the headline number is a costume. Wrist devices estimate energy expenditure from heart rate and motion with error margins that studies have repeatedly measured at significant percentages, sometimes wildly so per individual. Use the number as a relative nudge (this day moved more than that day), never as permission to eat it back. <b>Stress scores, readiness, VO2 max from thin air:</b> interesting, partially grounded, not gospel. <b>Sleep stages:</b> treat as a mood ring with a PhD.</p>
<h2>Who actually needs one</h2>
<p>Three groups get real value: <b>beginners building the walking habit</b> (the step count plus the streak does the motivating - see <a href="/how-many-steps-a-day/">what the steps are for</a>), <b>runners past the beginner plan</b> who want heart-rate pacing on the wrist (<a href="/beginner-running-plan/">the plan that precedes this</a>), and <b>data people</b> - you know who you are - who will genuinely enjoy the trends. Everyone else: use the phone, walk the stairs, spend the money on shoes.</p>
<h2>Buying, by tier</h2>
<p><b>Under budget:</b> a basic band counts steps, reads heart rate and syncs - everything a beginner needs, honestly. <b>Middle:</b> better sensors, GPS for runners, sleep tracking with fewer guesses. <b>High:</b> nicer screens and ecosystem features; measured accuracy improves only modestly - the jumps are in comfort, not truth. Whatever the tier: the tracker serves the habits (<a href="/30-day-walking-plan/">the walking plan</a>, <a href="/weekly-planner/">the weekly planner</a>), never the reverse - a device that makes you anxious is a device to return.</p>
<p>General information, not medical advice. Heart-rate data is a wellness guide, not a medical device, and any worrying rhythm or chest symptom goes to a clinician, not a forum.</p>"""),
("water-during-workout", "guide",
"Drinking during workouts: thirst, honesty and the one-hour rule",
"Fluids before, during and after - what actually helps, what the sports-drink aisle wants you to believe, and when water is simply enough.",
"""<p>Hydration advice used to be a maths exam - ounces per pound, schedules, alarms. The modern evidence-aware version is refreshingly simpler, and it starts with a sense most people were taught to ignore: thirst.</p>
<h2>Before: arrive stocked, not flooded</h2>
<p>You cannot pre-hydrate an hour before like filling a tank; the body simply disposes of the surplus. The useful version: drink normally across the day (<a href="/how-much-water-to-drink-a-day/">the daily-honest guide</a>), and have a glass in the hour before a session. Your urine running pale through the day is the dashboard light that matters - dark means start sipping.</p>
<h2>During: thirst is a real instrument</h2>
<p>For sessions under about an hour - which covers every beginner workout on this desk - drinking to thirst is the evidence-backed method, and water is the right fluid. A water bottle within arm's reach, sips when you notice it, no schedule required. Over an hour of continuous sweat, or in serious heat, drinking on a rougher rhythm (something every 15-20 minutes) stops you falling behind, because thirst lags actual loss in long efforts. The <a href="/30-day-walking-plan/">walking plan</a> needs none of this drama; a hard <a href="/30-day-core-programme/">core session</a> needs a bottle nearby and common sense.</p>
<h2>Sports drinks: the aisle vs the evidence</h2>
<p>Sports drinks exist for one specific job: replacing fluid, salts and fast carbohydrate during endurance efforts beyond roughly an hour, where the carbs measurably help. For a 40-minute workout they are sugary drinks wearing a lab coat - water does the job at no cost. The salt tablets and electrolyte waters aimed at casual gym-goers solve a problem most of them do not have; heavy sweaters in Nigerian heat doing long sessions are the honest audience.</p>
<h2>After: the quiet litres that matter</h2>
<p>Rehydration is a meal-and-evening affair, not a chug: drink across the hours after, eat normally (food carries fluid and salts better than anything in a bottle), and let pale urine confirm you are back. Weighing before and after a long sweaty session - roughly a kilogram lost meaning about a litre to replace - is the old coach's check, and it still works.</p>
<h2>The one-line version</h2>
<p>Arrive stocked, drink to thirst under an hour, add structure beyond it, let food finish the job - and treat <a href="/benefits-of-morning-water/">the morning glass</a> as the ritual that keeps the whole system honest.</p>
<p>General information, not medical advice. Fluid rules genuinely change with kidney, heart and blood-pressure conditions - those belong to your clinician, not a webpage.</p>"""),
]
