#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch 16: training past 40 - ageing, bone density, recovery, mobility, menopause, arthritis.

Tuples: (slug, kind, title, dek, body)
Sources in FIT_SOURCES_16, wired via the build hook.
"""

FIT_MORE_16 = [

("muscle-loss-after-40-explained", "Train", "Muscle loss after 40: what really happens and what reverses it",
"Sarcopenia without the doom: the actual rates of age-related muscle loss, why protein and resistance training are the countermeasures, and what the evidence says works at every starting age.",
"""<p>The number everyone quotes &mdash; "you lose 3&ndash;8% of muscle per decade after 30" &mdash; is real, and almost always quoted without the half that matters more: the loss is not a fixed tax on ageing. It is strongly modulated by two inputs, and both respond to intervention at any age you start.</p>
<h2>What actually happens</h2>
<p>Age-related muscle loss (sarcopenia) has three moving parts: <b>muscle fibres shrink and some are lost</b>, particularly fast-twitch fibres, which is why explosive power declines faster than strength; <b>anabolic resistance</b> creeps in &mdash; older muscle builds less protein per gram of protein eaten, so the same diet that maintained mass at 30 under-maintains at 55; and <b>activity patterns drift</b>, which is the largest and least discussed driver &mdash; much of what is called "ageing" in sedentary adults is deconditioning wearing ageing's clothes. The honest read from the research: the decline curve of an active person with adequate protein looks nothing like the sedentary average the scary numbers come from.</p>
<h2>The two countermeasures, in order of power</h2>
<p><b>Resistance training</b> is the primary lever &mdash; and the evidence here is among the strongest in exercise science: progressive lifting increases muscle mass and strength in people in their 70s, 80s and 90s, with trials in care-home populations showing dramatic strength gains. The over-40 prescription is not exotic: two to four sessions weekly, progressive load, the same principles as the <a href="/fitness/how-many-reps-for-muscle/">reps-for-muscle guide</a>, with warm-ups taken more seriously and the <a href="/fitness/how-to-warm-up/">warm-up guide</a>'s protocols no longer optional. <b>Protein</b> is the second lever, precisely because of anabolic resistance: the evidence supports higher per-meal doses than younger adults need &mdash; roughly 1.2&ndash;1.6 g/kg daily, weighted toward higher-protein meals rather than one protein-heavy dinner &mdash; which the <a href="/fitness/how-much-protein-do-you-need/">protein guide</a> works through practically. Leucine-rich sources do slightly more work per gram in older muscle, which is a refinement, not a rule.</p>
<h2>What does not work, and what to expect</h2>
<p>Testosterone booster supplements do not meaningfully change this picture &mdash; the <a href="/fitness/testosterone-booster-truth/">booster audit</a> covers that aisle &mdash; and neither does walking alone, which is superb for everything else but a weak hypertrophy stimulus. What to expect honestly: strength returns faster than size (neural adaptation first), visible mass takes months, and the first-year gains for a detrained over-40 beginner routinely exceed what a 25-year-old lifter sees &mdash; because there is more to rebuild. The <a href="/fitness/strength-training-over-50/">over-50 guide</a> takes the next decade's version of this plan; this one covers the decade where the habit decides everything after it.</p>
<p>The honest summary: muscle loss after 40 is real, common and mostly optional. Lift heavy things twice a week, eat more protein than feels necessary, and the curve bends &mdash; at 40, at 60, at 80. The research on this is about as close to unanimous as nutrition and exercise science ever gets.</p>"""),

("exercise-for-bone-density-explained", "Train", "Exercise for bone density: the stimulus bones actually respond to",
"Osteoporosis prevention decoded — why impact and heavy load build bone, why swimming does not, and the age-by-age plan the evidence supports.",
"""<p>Bone is living tissue that remodels continuously &mdash; and like muscle, it adapts specifically to the stresses placed on it. That specificity is the whole game: the wrong exercise leaves bones untouched no matter how fit it makes you feel, and the right stimulus is narrower than the advice columns suggest.</p>
<h2>What bone responds to</h2>
<p>Bone-building (osteogenesis) is triggered by <b>mechanical loading that is unusual and high-magnitude</b> &mdash; the skeleton's sensors register strain rates well above daily life and lay down mineral in response. Two stimulus families qualify. <b>Impact loading</b>: jumping, hopping, landing, running &mdash; the ground-reaction forces several times bodyweight that signal the skeleton to reinforce. <b>Heavy resistance</b>: squats, deadlifts, overhead pressing &mdash; muscles pulling hard on their attachment points. What does not qualify, however healthy: swimming and cycling &mdash; genuinely excellent cardio with near-zero skeletal loading, which is why lifelong swimmers can have unremarkable bone density, and why the <a href="/fitness/zone-2-cardio-explained/">zone-2 guide</a>'s prescriptions need a bone-stimulus partner, not replacement. The dose research is concrete: brief, high-intensity loading &mdash; tens of hard jumps or heavy sets &mdash; outperforms long, gentle activity.</p>
<h2>The age-by-age picture</h2>
<p><b>Up to about 30</b> the job is building peak bone mass &mdash; the bank balance every later decade draws from; impact sport and heavy lifting in the teens and twenties is the highest-return bone investment available. <b>30s&ndash;menopause</b> the job is maintenance &mdash; keeping the loading habit keeps the balance steady. <b>After menopause</b> oestrogen withdrawal accelerates loss, and the evidence-supported response is the same loading, plus attention to calcium, vitamin D and medical assessment where risk is elevated &mdash; the <a href="/fitness/menopause-and-exercise-explained/">menopause-and-exercise guide</a> covers that window in full. <b>Older age</b> shifts the emphasis but not the stimulus: heavy-ish resistance and controlled impact (even hard walking on stairs counts at the frail end) slow loss, and balance work &mdash; the <a href="/fitness/balance-training-why-it-matters/">balance guide</a> &mdash; becomes the fall-prevention half of the osteoporosis equation, because a fracture needs both a fall and a fragile bone.</p>
<h2>The honest caveats</h2>
<p>Three. Loading must be progressive &mdash; the skeleton adapts to repeated identical stimulus, so the jumps get higher or the bar gets heavier over time. Existing osteoporosis changes the menu &mdash; high-impact work needs medical clearance and professional programming, as the <a href="/fitness/muscle-soreness-vs-injury/">injury-versus-soreness guide</a>'s referral logic applies with extra force here. And exercise is one leg of bone health &mdash; nutrition, hormones, smoking and alcohol all sit in the equation, and the exercise leg cannot fully carry a plan missing the others.</p>
<p>The honest summary: bones want brief, heavy, unusual loads &mdash; jumps and barbells, not laps. Build the bank before 30, maintain the habit after, and pair the loading with balance work as the decades advance. It is one of the clearest cases in exercise science where the specific stimulus matters more than the general fitness.</p>"""),

("recovery-changes-with-age-explained", "Recover", "How recovery changes with age: what slows down and what you can do about it",
"The honest science of ageing recovery — what genuinely slows, what is actually deconditioning, and the protocol changes that keep training consistent past 40.",
"""<p>The over-40 training conversation keeps returning to one complaint: "I do not recover like I used to." Some of that is physiology, some is arithmetic &mdash; and telling them apart is what keeps training consistent instead of a cycle of ambitious weeks and enforced breaks.</p>
<h2>What genuinely slows</h2>
<p>The research-supported changes are real but bounded: <b>muscle protein synthesis responds more slowly</b> to the same stimulus (anabolic resistance &mdash; the mechanism the <a href="/fitness/muscle-loss-after-40-explained/">muscle-loss guide</a> builds on), <b>connective tissue adapts more slowly</b> than muscle, which is why tendons and joints lag behind muscular ambition &mdash; the classic over-40 injury pattern is a muscle-ready, tendon-unready lift; and <b>sleep architecture changes</b>, with less deep sleep on average, which matters because sleep is when most repair happens &mdash; the <a href="/fitness/sleep-and-exercise-performance/">sleep guide</a>'s protocols rise in importance, not relevance, with age. Hormonal shifts contribute but explain less than the recovery-supplement aisle claims.</p>
<h2>What is actually deconditioning</h2>
<p>The larger hidden factor: most over-40s comparing themselves to their twenties are comparing a trained twenty-something body to a less-trained current one &mdash; and trained bodies recover faster at any age. Detrained tissue recovers slowly; reconditioned tissue recovers well. The evidence that consistency beats youth: masters athletes with maintained training volumes show recovery profiles much closer to young athletes than to sedentary peers. The practical translation: the "I cannot recover" experience after a long layoff is mostly the layoff, and it resolves with weeks of consistent moderate work &mdash; the <a href="/fitness/restarting-exercise-after-a-break/">restart guide</a>'s gradualism is not caution, it is the actual physiology of rebuilding recovery capacity.</p>
<h2>The protocol changes that work</h2>
<p>The evidence-honest adjustments are modest and unglamorous. <b>Warm up for real</b> &mdash; longer, more specific, per the <a href="/fitness/how-to-warm-up/">warm-up guide</a>; this is the single best-rewarded change. <b>Manage volume before intensity</b>: cut total sets before cutting load &mdash; heavy work stays valuable, junk volume stops being free. <b>Space hard sessions further apart</b> for the same muscle groups, and use the <a href="/fitness/deload-weeks-explained/">deload rhythm</a> proactively rather than as repair. <b>Protect sleep ruthlessly</b> and hit protein targets &mdash; the <a href="/fitness/rest-days-and-recovery/">rest-days guide</a> covers the weekly architecture that makes all of it fit. What does not help: recovery gadgets as substitutes for any of the above &mdash; the honest audits of that shelf are in the <a href="/fitness/ice-bath-cold-plunge-truth/">cold-plunge verdict</a> and the <a href="/fitness/massage-guns-worth-it/">massage-gun review</a>.</p>
<p>The honest summary: recovery does change with age &mdash; slower synthesis, slower tendons, lighter sleep &mdash; and the changes are managed, not mourned: warm up properly, trade volume for quality, sleep like it is training (it is), and stay consistent long enough for the body to relearn recovering. Masters athletes are the proof of concept: the decline mostly belongs to those who stop.</p>"""),

("mobility-after-40-explained", "Train", "Mobility after 40: what stiffens, why, and the twenty minutes that fix most of it",
"Age-related stiffness decoded — the real causes of losing range, which changes respond to movement, and an evidence-based daily minimum.",
"""<p>Stiffness after 40 feels like a slow closing of options &mdash; shoulders that will not go overhead, hips that resist the squat, a back that objects to the floor. The honest science splits that stiffness into causes that respond beautifully to training and one that needs managing rather than fixing &mdash; and the twenty-minute daily response covers most people entirely.</p>
<h2>What actually stiffens</h2>
<p>Three mechanisms, only one of which is "ageing" proper. <b>Use-dependent shortening</b>: tissues adapt to the positions they live in &mdash; desk hours shorten hip flexors, forward shoulders settle into place; this is adaptation, not decay, and it reverses on the same timescale it formed. <b>Connective-tissue changes</b>: tendons and joint capsules slowly lose water content and elasticity &mdash; genuine ageing, but responsive: loaded stretching and full-range strength work measurably maintain range. <b>Strength loss at end-range</b>: much of what feels like "stiffness" is weakness in the stretched position &mdash; the nervous system guards ranges it cannot control, and the <a href="/fitness/mobility-vs-flexibility/">mobility-versus-flexibility explainer</a>'s distinction matters here: passive flexibility you cannot control under load is not usable mobility. The practical upshot: most over-40 stiffness is one-third desk adaptation, one-third weakness, one-third real tissue change &mdash; and two of the three are training problems with training solutions.</p>
<h2>The twenty-minute daily minimum</h2>
<p>The evidence-supported routine is small and boring: <b>full-range strength work</b> two or three times weekly is the backbone &mdash; deep squats, overhead pressing, deadlifts through a full range maintain mobility better than any stretch because they build control at end-range; then <b>daily end-range loading</b> &mdash; the squat hold, the wall slide, the hip airplane, the loaded stretch &mdash; ten to twenty minutes holding and moving through the ranges your day steals; and <b>the walk-and-move floor</b> &mdash; frequent position changes through the day, which the desk-worker guides treat as non-negotiable. Static stretching earns a supporting role &mdash; held 30&ndash;60 seconds post-session for the specific tight spots, per the <a href="/fitness/stretching-before-or-after/">timing explainer</a> &mdash; not the lead. What does not work: a monthly yoga class as the whole plan, passive gadgets, or stretching cold before heavy lifts.</p>
<h2>When it is not stiffness</h2>
<p>The honest boundary: range loss that is rapid, asymmetric, night-painful or accompanied by swelling is not a mobility problem &mdash; it is the <a href="/fitness/muscle-soreness-vs-injury/">soreness-versus-injury guide</a>'s referral territory, and at over-40 the threshold for professional assessment should be lower, not higher. Ageing joints occasionally carry genuine pathology that no stretch routine should be asked to absorb.</p>
<p>The honest summary: stiffness after 40 is mostly a movement-practice deficit wearing a biological costume. Train full ranges under load, spend twenty honest minutes a day at your end-ranges, change position constantly through the day &mdash; and the options stay open, because the evidence is clear that range follows function, and function follows practice, at every age studied.</p>"""),

("menopause-and-exercise-explained", "Understand", "Menopause and exercise: what changes and how training adapts",
"The evidence-based guide to training through perimenopause and menopause — muscle, bone, symptoms, and the programming shifts that matter most.",
"""<p>Menopause &mdash; and the multi-year perimenopause before it &mdash; changes the hormonal environment training happens in, and with it some of training's inputs and outputs. The honest evidence gives a clear picture: exercise remains the single best-supported intervention across the transition, with a few specific emphases that earn their place.</p>
<h2>What the oestrogen decline changes</h2>
<p>Three exercise-relevant shifts. <b>Bone loss accelerates</b> in the years around the final period &mdash; the highest-rate bone-loss window of adult life &mdash; which makes the loading priorities in the <a href="/fitness/exercise-for-bone-density-explained/">bone-density guide</a> specifically urgent here: impact and heavy resistance are the mechanical half of the standard medical advice, alongside calcium, vitamin D and clinical assessment. <b>Muscle maintenance gets harder</b> &mdash; oestrogen supports muscle protein synthesis, so its decline raises the importance of the two countermeasures from the <a href="/fitness/muscle-loss-after-40-explained/">muscle-loss guide</a>: progressive resistance training and higher protein intake, both with direct evidence in menopausal populations. And <b>body composition drifts</b> toward central fat &mdash; which responds to the same resistance-plus-protein plan plus general activity, not to targeted "hormone-balance" workouts, which have no evidence behind the label.</p>
<h2>Exercise as symptom management</h2>
<p>The transition's symptoms have a nuanced evidence picture worth stating honestly. <b>Mood, sleep and quality of life</b> show consistent improvement with regular exercise across trials &mdash; among the best-supported non-hormonal interventions there is. <b>Hot flushes</b> are the honest grey area: exercise does not reliably reduce their frequency in trials, despite the folk claim &mdash; though fitness moderates their impact and some evidence suggests regular activity blunts severity. <b>Joint aches</b>, common and under-discussed, respond to the same loading-plus-mobility pattern as everything else here &mdash; the <a href="/fitness/mobility-after-40-explained/">mobility guide</a>'s protocol doubles as the joint-care plan. The medical context matters: hormone replacement therapy is a legitimate, evidence-based option for many, decided with a clinician &mdash; exercise complements it rather than competing, and this desk's position throughout is that medical decisions belong to doctors and the <a href="/fitness/muscle-soreness-vs-injury/">referral guidance</a>, not fitness content.</p>
<h2>The programming shifts</h2>
<p>What actually changes in the plan: <b>resistance training moves to the centre</b> &mdash; from one pillar to the load-bearing one, two to four days weekly with real progression; <b>impact work is added deliberately</b> for bone, where joints allow; <b>recovery and sleep hygiene rise in priority</b> as both age and transition change them &mdash; the <a href="/fitness/sleep-and-exercise-performance/">sleep guide</a>'s protocols again; and <b>consistency beats intensity</b>, because the benefits that matter here &mdash; bone, muscle, mood, metabolic &mdash; accumulate from regular moderate practice, not heroic weeks. Nothing about the transition requires stopping hard training; the evidence on masters athletes through this window is unambiguous that maintained intensity serves them well.</p>
<p>The honest summary: menopause changes the stakes, not the rules. Lift heavy, load the skeleton, eat protein, sleep deliberately, and keep the habit boring and permanent &mdash; the transition is the strongest argument in a training life for the unglamorous plan done for years.</p>"""),

("exercising-with-arthritis-explained", "Recover", "Exercising with arthritis: what the evidence says is safe and helpful",
"Osteoarthritis and movement decoded — why the old rest advice was backwards, which activities the evidence supports, and the flare-day rules.",
"""<p>For most of the twentieth century the arthritis advice was rest the joint. The evidence reversed that completely: movement is now first-line management for the most common arthritis, and understanding why &mdash; and how &mdash; turns exercise from a risk into the treatment.</p>
<h2>Why movement helps, mechanically</h2>
<p>Osteoarthritis is the wear-and-remodelling condition of joint cartilage, and the mechanical facts explain the advice. Cartilage has no blood supply &mdash; it feeds by <b>diffusion driven by movement</b>: compression and release during activity pumps nutrients in and waste out, so a sedentary joint is a malnourished joint. Second, the joint's real shock absorbers are the <b>muscles around it</b>: a strong quadriceps measurably reduces load on knee cartilage, and strength deficits predict progression. Third, <b>pain sensitises</b>: inactivity-driven deconditioning and fear-avoidance amplify pain processing, and the cycle runs downhill fast. Hence the clinical consensus across every major guideline: exercise &mdash; strength, aerobic and mobility &mdash; is first-line osteoarthritis management, with a pain-relief effect that trials put on par with common painkillers for many patients, without their side effects.</p>
<h2>What the evidence supports</h2>
<p>The menu, in evidence order: <b>strength training</b> around the affected joints &mdash; the strongest evidence base there is, with the <a href="/fitness/how-many-reps-for-muscle/">reps guide</a>'s principles applied conservatively and progressively; <b>low-impact aerobic work</b> &mdash; walking, cycling, swimming, the <a href="/fitness/walking-vs-running/">walking-versus-running trade-offs</a> settled in favour of walking for load-sensitive joints; and <b>range-of-motion work</b> &mdash; the <a href="/fitness/mobility-after-40-explained/">mobility guide</a>'s daily minimum, which for arthritic joints is maintenance rather than improvement. Weight management sits alongside as the other first-line intervention for weight-bearing joints, and the maths there is blunt: every kilogram of bodyweight is several kilograms of knee load per step. What to avoid: high-impact loading on actively painful joints, deep end-range work through sharp pain, and the boom-bust pattern of heroic sessions followed by week-long flares &mdash; consistency at moderate doses beats intensity every time, per the same architecture as the <a href="/fitness/rest-days-and-recovery/">rest-days guide</a>.</p>
<h2>The flare-day rules, and the boundary</h2>
<p>Two practical rules from the clinical literature. <b>The two-hour rule</b>: exercise-related ache that settles within two hours was probably a useful dose; pain lasting into the next day says the dose was too high &mdash; scale the load, not the habit. <b>Sharp versus achy</b>: muscular ache around a joint is work; sharp, catching or swelling pain inside it is a stop signal. And the boundary this desk always draws applies here with full force &mdash; diagnosis, inflammatory arthritis (rheumatoid and friends behave differently and need rheumatology care), rapid deterioration, and any hot, swollen joint belong to medical professionals, per the <a href="/fitness/muscle-soreness-vs-injury/">soreness-versus-injury guide</a>; general information is what this page is, and it is not a substitute for the clinician who knows the joint.</p>
<p>The honest summary: the arthritic joint is not a museum piece &mdash; it is a structure that feeds on movement, stabilises under muscle and stiffens under fear. Strength around it, gentle load through it, consistency above heroics, and professional care for everything outside that brief: the evidence calls that combination the best medicine available, and it costs nothing but the habit.</p>"""),

]

FIT_SOURCES_16 = {
    "muscle-loss-after-40-explained": [
        ("PubMed \u2014 sarcopenia and resistance training in older adults", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("NIH \u2014 age-related muscle loss research", "https://www.nia.nih.gov/")],
    "exercise-for-bone-density-explained": [
        ("PubMed \u2014 mechanical loading and bone density trials", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("WHO \u2014 osteoporosis and physical activity", "https://www.who.int/")],
    "recovery-changes-with-age-explained": [
        ("PubMed \u2014 recovery kinetics in masters athletes", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("Harvard Health Publishing \u2014 exercise and ageing", "https://www.health.harvard.edu/")],
    "mobility-after-40-explained": [
        ("PubMed \u2014 range-of-motion training in older adults", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("ACE \u2014 flexibility and mobility guidance", "https://www.acefitness.org/")],
    "menopause-and-exercise-explained": [
        ("PubMed \u2014 exercise trials in menopausal women", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("Harvard Health Publishing \u2014 menopause and fitness", "https://www.health.harvard.edu/")],
    "exercising-with-arthritis-explained": [
        ("PubMed \u2014 exercise therapy for osteoarthritis", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("CDC \u2014 arthritis and physical activity", "https://www.cdc.gov/arthritis/")],
}
