# B71: the exercise library database - 53 moves across 5 category pages.
# Each move: id (page anchor), name, cat, muscles, equip, cues (setup first),
# mistake, sets, easier, harder. Honest, no medical claims, plain ASCII.

PUSH = "push"; PULL = "pull"; LEGS = "legs"; CORE = "core"; COND = "cond"

EXERCISES = [
# ---------------- PUSH: chest, shoulders, triceps ----------------
{"id": "incline-push-up", "name": "The incline push-up", "cat": PUSH,
 "muscles": "Chest, shoulders, triceps", "equip": "A bench, table edge or sturdy chair",
 "cues": ["Hands shoulder-width on the bench, body one straight line from head to heels.",
          "Lower your chest to the edge, elbows about 45 degrees from your sides.",
          "Press the floor away until your arms are straight again.",
          "Squeeze your stomach so your hips do not sag."],
 "mistake": "Going too fast. Two seconds down, one second up - the slow reps are the ones that count.",
 "sets": "3 sets of 6-12 reps, rest 60-90 seconds.",
 "easier": "Raise the surface: a wall push-up (hands on a wall) is the easiest version.",
 "harder": "Lower the surface. When the floor feels easy, see the full push-up."},
{"id": "push-up", "name": "The push-up", "cat": PUSH,
 "muscles": "Chest, shoulders, triceps", "equip": "None",
 "cues": ["Hands just outside your shoulders, body one straight line.",
          "Look at the floor a little ahead of you, not at your feet.",
          "Lower until your chest is a fist-height from the floor.",
          "Press up and think about pushing the floor away from you."],
 "mistake": "Hips sagging or piking. If your lower back strains, drop to your knees or raise your hands - form beats reps.",
 "sets": "3 sets of 5-15 reps, rest 60-90 seconds.",
 "easier": "Knees down, or hands on a bench (the incline push-up).",
 "harder": "Feet on a step, a backpack with books, or slow the lowering phase to three seconds."},
{"id": "pike-push-up", "name": "The pike push-up", "cat": PUSH,
 "muscles": "Shoulders, triceps", "equip": "None",
 "cues": ["From a push-up position, walk your feet in so your hips point at the ceiling.",
          "Your body forms an upside-down V. Head between your arms.",
          "Bend your elbows and lower the top of your head toward the floor.",
          "Press back up without letting your hips sink."],
 "mistake": "Turning it into a normal push-up by letting the hips drop. The hips stay high the whole time.",
 "sets": "3 sets of 4-10 reps, rest 90 seconds.",
 "easier": "Walk the feet less far in - a less steep angle is easier.",
 "harder": "Raise your feet on a step. This is the road to handstand push-ups."},
{"id": "dumbbell-bench-press", "name": "The dumbbell bench press", "cat": PUSH,
 "muscles": "Chest, shoulders, triceps", "equip": "Two dumbbells and a bench (or the floor)",
 "cues": ["Lie back, dumbbells at chest level, elbows about 45 degrees from your body.",
          "Press the dumbbells up and slightly toward each other.",
          "Lower with control until your upper arms reach bench level.",
          "Keep your wrists stacked over your elbows the whole time."],
 "mistake": "Flaring the elbows out to a straight line with your shoulders - it grinds the shoulder joints. Keep them at 45 degrees.",
 "sets": "3 sets of 8-12 reps, rest 90 seconds.",
 "easier": "Do it on the floor (the floor press): no bench needed and it protects the shoulder.",
 "harder": "Slow the lowering to three seconds, or press one dumbbell at a time."},
{"id": "dumbbell-shoulder-press", "name": "The dumbbell shoulder press", "cat": PUSH,
 "muscles": "Shoulders, triceps", "equip": "Two dumbbells",
 "cues": ["Sit or stand, dumbbells at shoulder height, palms facing forward.",
          "Squeeze your stomach so your ribs do not flare.",
          "Press straight up until your arms are overhead.",
          "Lower until the dumbbells are level with your ears."],
 "mistake": "Leaning back and turning it into an incline press. If you cannot stay upright, the weight is too heavy.",
 "sets": "3 sets of 8-12 reps, rest 90 seconds.",
 "easier": "Seated with your back supported, or alternate arms.",
 "harder": "Stand up, or pause one second at the top of each rep."},
{"id": "dumbbell-chest-fly", "name": "The dumbbell chest fly", "cat": PUSH,
 "muscles": "Chest", "equip": "Two dumbbells and a bench or the floor",
 "cues": ["Lie back, dumbbells above your chest, elbows softly bent.",
          "Open your arms out wide, as if hugging a barrel.",
          "Stop when your upper arms reach bench level.",
          "Bring the dumbbells back together the same way."],
 "mistake": "Bending and straightening the elbows as you go - that becomes a press. The elbow angle stays fixed.",
 "sets": "3 sets of 10-15 reps, rest 60 seconds. Light weights: this one rewards control, not load.",
 "easier": "Smaller range: stop the open phase earlier.",
 "harder": "Pause two seconds at the widest point."},
{"id": "dumbbell-lateral-raise", "name": "The dumbbell lateral raise", "cat": PUSH,
 "muscles": "Side shoulders", "equip": "Two light dumbbells",
 "cues": ["Stand tall, a light dumbbell in each hand at your sides.",
          "Raise both arms out to the sides, elbows slightly bent.",
          "Stop at shoulder height - no higher.",
          "Lower slowly; do not let gravity do the work."],
 "mistake": "Swinging the weight up with your hips. Your shoulders should do the lifting, not momentum.",
 "sets": "3 sets of 12-15 reps, rest 60 seconds. Go lighter than you think.",
 "easier": "Raise one arm at a time, holding a rail with the other.",
 "harder": "Pause one second at the top, or add a slow three-second lowering."},
{"id": "bench-dip", "name": "The bench dip", "cat": PUSH,
 "muscles": "Triceps, front shoulders", "equip": "A bench, chair or step",
 "cues": ["Sit on the edge, hands beside your hips, fingers forward.",
          "Slide your hips off the bench, legs bent or straight.",
          "Bend your elbows to lower your hips - elbows point back, not out.",
          "Press back up until your arms are straight."],
 "mistake": "Letting the shoulders shrug up to your ears. Keep them pulled down away from your ears the whole set.",
 "sets": "3 sets of 6-12 reps, rest 60-90 seconds.",
 "easier": "Bend your knees and keep your feet close to the bench.",
 "harder": "Straighten your legs, then raise your feet onto a second surface."},
{"id": "overhead-tricep-extension", "name": "The overhead tricep extension", "cat": PUSH,
 "muscles": "Triceps", "equip": "One dumbbell (or a filled bottle)",
 "cues": ["Hold one dumbbell with both hands straight overhead.",
          "Bend your elbows to lower the weight behind your head.",
          "Keep your upper arms still and vertical - only the elbows move.",
          "Press back up and squeeze the triceps at the top."],
 "mistake": "Elbows drifting wide. They stay pointing up and close together.",
 "sets": "3 sets of 10-15 reps, rest 60 seconds.",
 "easier": "Do it one arm at a time with a lighter weight.",
 "harder": "Pause one second at the bottom of the movement."},
{"id": "band-chest-press", "name": "The band chest press", "cat": PUSH,
 "muscles": "Chest, shoulders, triceps", "equip": "A resistance band and a door anchor (or a pole)",
 "cues": ["Anchor the band at chest height behind you, one end in each hand.",
          "Step forward so the band is already slightly tight.",
          "Press your hands forward until your arms are straight.",
          "Return slowly, resisting the band the whole way."],
 "mistake": "Letting the band snap you back. The way back is half the exercise.",
 "sets": "3 sets of 10-15 reps, rest 60 seconds.",
 "easier": "Step closer to the anchor so the band is slacker.",
 "harder": "Step further away, or use a thicker band."},
{"id": "wall-handstand-hold", "name": "The wall handstand hold", "cat": PUSH,
 "muscles": "Shoulders, arms, midsection", "equip": "A clear wall",
 "cues": ["Place your hands a foot from the wall, shoulder-width.",
          "Walk your feet up the wall until your body is close to vertical.",
          "Push the floor away and squeeze your stomach.",
          "Breathe. Hold, then walk down with control."],
 "mistake": "Arching the lower back and letting the ribs lead. Tuck the ribs; think about a straight line from wrists to hips.",
 "sets": "3 holds of 10-30 seconds. Advanced: skip this until push-ups and pike push-ups feel easy.",
 "easier": "pike push-ups on the floor build the same strength with far less risk.",
 "harder": "Chest-to-wall handstands, or add small shoulder taps."},
# ---------------- PULL: back, biceps ----------------
{"id": "towel-row", "name": "The towel row", "cat": PULL,
 "muscles": "Upper back, biceps", "equip": "A towel and a sturdy door or pole",
 "cues": ["Loop a towel around a fixed pole or door handle at waist height.",
          "Hold both ends, lean back with your arms straight, body rigid.",
          "Pull your chest toward your hands, elbows brushing your sides.",
          "Lower yourself slowly - do not let go of the tension."],
 "mistake": "Shrugging your shoulders up to your ears. Pull them down and back as you row.",
 "sets": "3 sets of 8-12 reps, rest 60-90 seconds.",
 "easier": "Stand more upright - less of your bodyweight is on the arms.",
 "harder": "Lean further back, or walk your feet forward."},
{"id": "doorway-row", "name": "The doorway row", "cat": PULL,
 "muscles": "Upper back, biceps", "equip": "A sturdy door frame",
 "cues": ["Hold both sides of an open door frame at chest height.",
          "Lean back, arms straight, feet close to the frame.",
          "Pull your chest to the frame, squeezing your shoulder blades.",
          "Lower yourself with control."],
 "mistake": "Using your legs to do the rowing. The legs stay still; the arms and back work.",
 "sets": "3 sets of 8-12 reps, rest 60-90 seconds.",
 "easier": "Stand more upright.",
 "harder": "Move your feet further from the frame, or try one arm at a time."},
{"id": "one-arm-dumbbell-row", "name": "The one-arm dumbbell row", "cat": PULL,
 "muscles": "Upper back, lats, biceps", "equip": "One dumbbell (a filled bag works too)",
 "cues": ["One hand and knee on a bench or chair, back flat like a table.",
          "Let the weight hang straight down from your shoulder.",
          "Pull your elbow up and back, close to your body.",
          "Lower slowly. Finish the set, then switch sides."],
 "mistake": "Twisting the torso to heave the weight up. If you have to twist, the weight is too heavy.",
 "sets": "3 sets of 8-12 reps per side, rest 60 seconds between sides.",
 "easier": "Do it with both knees on the bench for stability, lighter weight.",
 "harder": "Pause one second at the top of every rep."},
{"id": "band-pulldown", "name": "The band pulldown", "cat": PULL,
 "muscles": "Lats, upper back, biceps", "equip": "A resistance band and a high anchor",
 "cues": ["Anchor the band above head height (top of a door works).",
          "Kneel or sit, arms straight overhead holding the band.",
          "Pull your elbows down to your sides.",
          "Rise slowly, letting your arms fully extend at the top."],
 "mistake": "Leaning way back and turning it into a row. Stay upright and let the lats pull.",
 "sets": "3 sets of 10-15 reps, rest 60 seconds.",
 "easier": "Kneel closer to the anchor, or use a lighter band.",
 "harder": "Slow the return to three seconds, or pause at your chest."},
{"id": "band-pull-apart", "name": "The band pull-apart", "cat": PULL,
 "muscles": "Upper back, rear shoulders", "equip": "A light resistance band",
 "cues": ["Hold a band at shoulder height, hands shoulder-width, arms straight.",
          "Pull the band apart until it touches your chest.",
          "Squeeze your shoulder blades together at the front.",
          "Return slowly with control."],
 "mistake": "Bending the elbows and shrugging. Arms stay long; shoulders stay down.",
 "sets": "3 sets of 12-20 reps, rest 45 seconds. Great as a warm-up too.",
 "easier": "Hold wider for less tension.",
 "harder": "Narrow your grip or step on the middle of a longer band."},
{"id": "band-face-pull", "name": "The band face pull", "cat": PULL,
 "muscles": "Rear shoulders, upper back", "equip": "A resistance band and a face-height anchor",
 "cues": ["Anchor the band at eye level, hold it with thumbs pointing back at you.",
          "Pull the band toward your face, elbows high and wide.",
          "Finish in a double-biceps pose, knuckles by your ears.",
          "Return slowly."],
 "mistake": "Pulling to your chest with low elbows. The elbows stay high - it is a face pull, not a row.",
 "sets": "3 sets of 12-15 reps, rest 60 seconds. The posture move most programmes are missing.",
 "easier": "Use a lighter band or step closer.",
 "harder": "Pause one second at your face each rep."},
{"id": "dumbbell-curl", "name": "The dumbbell curl", "cat": PULL,
 "muscles": "Biceps", "equip": "Two dumbbells",
 "cues": ["Stand tall, dumbbells at your sides, palms forward.",
          "Curl both weights up without swinging your hips.",
          "Squeeze at the top, elbows pinned to your ribs.",
          "Lower for two to three seconds."],
 "mistake": "Using your lower back to swing the first rep. If the body moves, the weight is too heavy.",
 "sets": "3 sets of 10-15 reps, rest 60 seconds.",
 "easier": "Alternate arms, or sit down to remove any swing.",
 "harder": "Three-second lowering, or curl both at once without pausing between reps."},
{"id": "hammer-curl", "name": "The hammer curl", "cat": PULL,
 "muscles": "Biceps, forearms", "equip": "Two dumbbells",
 "cues": ["Same as the curl, but palms face each other all the way.",
          "Curl the weights up as if hammering a nail.",
          "Keep the elbows still at your sides.",
          "Lower slowly."],
 "mistake": "Letting the elbows drift forward as you fatigue. Pin them to your ribs.",
 "sets": "3 sets of 10-15 reps, rest 60 seconds.",
 "easier": "One arm at a time.",
 "harder": "Slow the lowering, or add a small pause halfway up."},
{"id": "reverse-fly", "name": "The reverse fly", "cat": PULL,
 "muscles": "Rear shoulders, upper back", "equip": "Two light dumbbells",
 "cues": ["Hinge forward at the hips, back flat, light dumbbells hanging down.",
          "With soft elbows, raise both arms out to the sides.",
          "Stop at shoulder height and squeeze the shoulder blades.",
          "Lower slowly."],
 "mistake": "Going heavy. This is a small muscle with a small lever - the lightest dumbbells you own are plenty.",
 "sets": "3 sets of 12-15 reps, rest 45-60 seconds.",
 "easier": "Sit down and hinge over your knees, or lie chest-down on a bench.",
 "harder": "Pause one second at the top."},
{"id": "dead-hang", "name": "The dead hang", "cat": PULL,
 "muscles": "Grip, lats, shoulders", "equip": "A pull-up bar or sturdy overhead bar",
 "cues": ["Grip the bar just outside shoulder width.",
          "Hang with straight arms, shoulders active (not up at your ears).",
          "Keep your body still - no swinging.",
          "Hold, breathe, and step down before your grip dies completely."],
 "mistake": "Holding your breath. Slow nasal breaths keep the hang calm and long.",
 "sets": "3 hangs of 15-40 seconds, rest 90 seconds.",
 "easier": "Keep one foot on a chair to take part of your weight.",
 "harder": "This is step one of your first pull-up. Add seconds each week, then try slow negatives."},
{"id": "superman-hold", "name": "The superman hold", "cat": PULL,
 "muscles": "Lower back, glutes, upper back", "equip": "None",
 "cues": ["Lie face down, arms stretched ahead of you.",
          "Lift your chest, arms and legs a few centimetres off the floor.",
          "Reach long - not high. Squeeze the shoulder blades.",
          "Hold, then lower with control."],
 "mistake": "Cranking the neck up. Keep it long, in line with your spine, eyes on the floor.",
 "sets": "3 holds of 15-30 seconds, rest 45 seconds.",
 "easier": "Lift arms only, or legs only.",
 "harder": "Add small arm paddles (swimming) while holding the lift."},
# ---------------- LEGS ----------------
{"id": "bodyweight-squat", "name": "The bodyweight squat", "cat": LEGS,
 "muscles": "Quads, glutes, core", "equip": "None",
 "cues": ["Feet shoulder-width, toes slightly out.",
          "Sit back and down as if toward a chair, chest proud.",
          "Go as deep as you can with a flat back and heels down.",
          "Drive the floor away to stand tall."],
 "mistake": "Heels lifting and knees caving inward. Knees track over the toes; weight stays mid-foot.",
 "sets": "3 sets of 8-20 reps, rest 60-90 seconds.",
 "easier": "Squat down to an actual chair and let it catch you lightly.",
 "harder": "Slow the lowering to three seconds, pause at the bottom, or hold a weight (see the goblet squat)."},
{"id": "reverse-lunge", "name": "The reverse lunge", "cat": LEGS,
 "muscles": "Quads, glutes, balance", "equip": "None",
 "cues": ["Stand tall, then step one foot straight back.",
          "Lower until both knees are about 90 degrees.",
          "The front shin stays roughly vertical; weight through the front heel.",
          "Push through the front heel to return."],
 "mistake": "Short steps that ram the front knee forward. Take a genuinely long step back.",
 "sets": "3 sets of 6-10 reps per leg, rest 60-90 seconds.",
 "easier": "Hold a wall or chair for balance; shorten the range.",
 "harder": "Walking lunges, or hold dumbbells at your sides."},
{"id": "glute-bridge", "name": "The glute bridge", "cat": LEGS,
 "muscles": "Glutes, hamstrings", "equip": "None",
 "cues": ["Lie on your back, knees bent, feet flat and close to your hips.",
          "Tuck your pelvis slightly, then push through the heels.",
          "Lift your hips until your body is one line from knees to shoulders.",
          "Squeeze the glutes hard at the top for one second, then lower."],
 "mistake": "Lifting with the lower back instead of the glutes - you will feel it in the spine. Tuck first, then lift.",
 "sets": "3 sets of 10-15 reps, rest 60 seconds.",
 "easier": "Smaller range: lift only a few centimetres, focusing on the squeeze.",
 "harder": "One leg at a time, or feet on a step."},
{"id": "calf-raise", "name": "The calf raise", "cat": LEGS,
 "muscles": "Calves", "equip": "None (a step adds range)",
 "cues": ["Stand tall, feet hip-width near a wall for balance.",
          "Rise onto the balls of your feet as high as you can.",
          "Pause one second at the top.",
          "Lower slowly until your heels drop below the step edge if you can."],
 "mistake": "Fast bouncy reps. Calves respond to full range and a pause at the top.",
 "sets": "3 sets of 12-20 reps, rest 45 seconds.",
 "easier": "Two legs, flat floor, hold the wall.",
 "harder": "One leg at a time, or heels-off-a-step for extra range."},
{"id": "wall-sit", "name": "The wall sit", "cat": LEGS,
 "muscles": "Quads, glutes", "equip": "A wall",
 "cues": ["Slide down a wall until your thighs are parallel to the floor.",
          "Knees directly over your ankles, not your toes.",
          "Back flat against the wall, hands off the thighs.",
          "Breathe steadily and hold."],
 "mistake": "Sliding the hands onto the thighs for help. Hands on your head or crossed at the chest.",
 "sets": "3 holds of 20-45 seconds, rest 60 seconds.",
 "easier": "Slide less deep - a higher squat angle.",
 "harder": "Hold a weight on your lap or extend one leg at a time."},
{"id": "goblet-squat", "name": "The goblet squat", "cat": LEGS,
 "muscles": "Quads, glutes, core", "equip": "One dumbbell (or a filled bag)",
 "cues": ["Hold one weight vertically at your chest, like a goblet, elbows down.",
          "Feet shoulder-width. Sit straight down between your feet.",
          "The weight against your chest keeps your torso upright - let it.",
          "Drive up through mid-foot."],
 "mistake": "Letting the chest fall forward. The weight hugs the chest the entire time.",
 "sets": "3 sets of 8-12 reps, rest 90 seconds.",
 "easier": "Use no weight first and copy the same upright torso.",
 "harder": "Add weight slowly, or pause three seconds in the bottom position."},
{"id": "romanian-deadlift", "name": "The dumbbell Romanian deadlift", "cat": LEGS,
 "muscles": "Hamstrings, glutes, lower back", "equip": "Two dumbbells (or one, or bags)",
 "cues": ["Stand tall, weights at your sides, knees softly bent.",
          "Push your hips straight back and slide the weights down your thighs.",
          "Feel the stretch in the hamstrings; stop when the back starts to round.",
          "Drive the hips forward to stand, squeezing the glutes."],
 "mistake": "Squatting instead of hinging, or rounding the back to chase the floor. The weights stop at shin level if that is where your hamstrings end.",
 "sets": "3 sets of 8-12 reps, rest 90 seconds.",
 "easier": "Practice the hinge without weight, hands sliding down your legs.",
 "harder": "Pause two seconds at the bottom stretch, or go single-leg."},
{"id": "step-up", "name": "The step-up", "cat": LEGS,
 "muscles": "Quads, glutes", "equip": "A step, stair or sturdy bench",
 "cues": ["Place one whole foot on a knee-height step.",
          "Push through the top foot only - no push-off from the bottom leg.",
          "Stand fully tall at the top without leaning forward.",
          "Lower slowly, kissing the floor with the trailing toe, then repeat."],
 "mistake": "Bouncing off the bottom leg. The working leg does all of it, up and down.",
 "sets": "3 sets of 6-10 reps per leg, rest 60-90 seconds.",
 "easier": "Lower step, or hold a rail lightly.",
 "harder": "Higher step, dumbbells in hand, or a slow three-second lowering."},
{"id": "single-leg-glute-bridge", "name": "The single-leg glute bridge", "cat": LEGS,
 "muscles": "Glutes, hamstrings", "equip": "None",
 "cues": ["Lie on your back, one foot flat, the other leg straight.",
          "Tuck the pelvis, then push through the single heel.",
          "Lift until the thighs are level, hips square to the ceiling.",
          "Lower slowly and repeat before switching sides."],
 "mistake": "Letting the hips tip to one side. Imagine a glass of water balanced on your hip bones.",
 "sets": "3 sets of 8-12 reps per side, rest 60 seconds.",
 "easier": "Two-leg glute bridge first until 15 clean reps feel easy.",
 "harder": "Pause two seconds at the top, or rest your working heel on a bench."},
{"id": "walking-lunge", "name": "The walking lunge", "cat": LEGS,
 "muscles": "Quads, glutes, balance", "equip": "Space to walk (dumbbells optional)",
 "cues": ["Step forward into a long stride and lower until both knees are about 90 degrees.",
          "Push through the front heel and bring the back leg through.",
          "Step straight into the next lunge.",
          "Torso tall the whole walk."],
 "mistake": "Short steps and a forward-falling torso. Long stride, proud chest.",
 "sets": "3 sets of 10-14 steps total, rest 90 seconds.",
 "easier": "Stationary reverse lunges in place.",
 "harder": "Hold dumbbells at your sides."},
{"id": "sumo-squat", "name": "The sumo squat", "cat": LEGS,
 "muscles": "Inner thighs, glutes, quads", "equip": "None (one dumbbell optional)",
 "cues": ["Stand with a wide stance, toes turned out about 30-45 degrees.",
          "Sit straight down, knees tracking over the toes.",
          "Keep your chest tall; hands can hang between your legs.",
          "Drive through the whole foot to stand."],
 "mistake": "Letting the knees collapse inward. They follow the toes outward the whole way.",
 "sets": "3 sets of 10-15 reps, rest 60-90 seconds.",
 "easier": "Hold a chair back for balance and reduce depth.",
 "harder": "Hold one dumbbell vertically at your chest, goblet-style."},
# ---------------- CORE ----------------
{"id": "forearm-plank", "name": "The forearm plank", "cat": CORE,
 "muscles": "Deep core, shoulders", "equip": "None",
 "cues": ["Elbows under shoulders, forearms flat, feet hip-width.",
          "One straight line: ears, shoulders, hips, heels.",
          "Squeeze the stomach and glutes; tuck the pelvis slightly.",
          "Breathe shallow and steady - do not hold your breath."],
 "mistake": "Sagging hips or a piked tent. If a straight line is impossible, drop to the knees.",
 "sets": "3 holds of 20-45 seconds, rest 60 seconds.",
 "easier": "Knees down, or hands on a bench (incline plank).",
 "harder": "Longer holds past 45 seconds are less useful - try shoulder taps or a weighted vest instead."},
{"id": "dead-bug", "name": "The dead bug", "cat": CORE,
 "muscles": "Deep core", "equip": "None",
 "cues": ["Lie on your back, arms straight up, knees bent at 90 degrees.",
          "Press your lower back gently into the floor.",
          "Slowly lower the opposite arm and leg toward the floor.",
          "Return and switch sides. The back never arches."],
 "mistake": "Rushing. The lower back peels off the floor and the exercise is lost. Slow is the whole point.",
 "sets": "3 sets of 6-10 slow reps per side, rest 45 seconds.",
 "easier": "Move legs only, hands braced on the floor.",
 "harder": "Hold a light weight in the moving hand."},
{"id": "bird-dog", "name": "The bird dog", "cat": CORE,
 "muscles": "Deep core, lower back, balance", "equip": "None",
 "cues": ["On hands and knees, back flat like a table.",
          "Reach one arm forward and the opposite leg back, both at hip height.",
          "Hold two seconds without tilting the hips.",
          "Return and switch. Imagine a cup of coffee on your lower back."],
 "mistake": "Letting the hips rotate or the lower back arch as the leg lifts. Height does not matter - steadiness does.",
 "sets": "3 sets of 6-8 reps per side, rest 45 seconds.",
 "easier": "Move the arm only, then the leg only.",
 "harder": "Pause five seconds per rep, or do it elbow-to-knee under the body between reaches."},
{"id": "side-plank", "name": "The side plank", "cat": CORE,
 "muscles": "Obliques, hips", "equip": "None",
 "cues": ["Lie on your side, elbow under shoulder, feet stacked or staggered.",
          "Lift your hips until your body is one straight line.",
          "Top hand on the hip or reaching to the ceiling.",
          "Hold, breathe, then switch sides."],
 "mistake": "Hips drifting back or sagging down. A mirror or phone camera is honest feedback here.",
 "sets": "3 holds of 15-40 seconds per side, rest 45 seconds.",
 "easier": "Bottom knee bent and down on the floor.",
 "harder": "Raise the top leg, or thread the top arm under your body each rep."},
{"id": "hollow-hold", "name": "The hollow hold", "cat": CORE,
 "muscles": "Deep core", "equip": "None",
 "cues": ["Lie on your back, press the lower into the floor.",
          "Lift shoulders and legs a few centimetres, arms by the ears.",
          "The lower back stays glued to the floor - that is the whole exercise.",
          "Hold, breathing steadily."],
 "mistake": "Letting the lower back arch off the floor. Bend the knees or lift the legs higher to fix it.",
 "sets": "3 holds of 10-30 seconds, rest 60 seconds.",
 "easier": "Tuck position: knees bent, arms by your sides.",
 "harder": "Longer arms and lower legs - but only while the back stays flat."},
{"id": "bicycle-crunch", "name": "The bicycle crunch", "cat": CORE,
 "muscles": "Obliques, abs", "equip": "None",
 "cues": ["Lie on your back, hands lightly behind the ears (no pulling).",
          "Lift the shoulders, bring one elbow toward the opposite knee as the other leg extends.",
          "Rotate from the ribs, not the elbows.",
          "Switch sides in a slow, steady rhythm."],
 "mistake": "Cranking the neck and racing. Slow rotations with the belly doing the work beat fifty fast ones.",
 "sets": "3 sets of 10-16 slow rotations, rest 45 seconds.",
 "easier": "Keep both feet on the floor and rotate the shoulders only.",
 "harder": "Pause one second at each rotation."},
{"id": "lying-leg-raise", "name": "The lying leg raise", "cat": CORE,
 "muscles": "Lower abs, hip flexors", "equip": "None",
 "cues": ["Lie flat, hands at your sides or under the hips for support.",
          "Press the lower back down, then raise straight legs to vertical.",
          "Lower slowly - stop the moment the back wants to arch.",
          "That stopping point is your real range today."],
 "mistake": "Lowering past the arch point. The back arching means the abs have quit; shorten the range.",
 "sets": "3 sets of 8-12 reps, rest 60 seconds.",
 "easier": "Bent knees, or one leg at a time.",
 "harder": "Slow five-second lowering, or pause two inches off the floor."},
{"id": "pallof-press", "name": "The band Pallof press", "cat": CORE,
 "muscles": "Deep core (anti-rotation), obliques", "equip": "A band and a chest-height anchor",
 "cues": ["Stand side-on to the anchor, band held at the chest with both hands.",
          "Step away so the band pulls you toward it.",
          "Press your hands straight out and resist the twist.",
          "Hold two seconds, return, finish the set, and turn around."],
 "mistake": "Letting the shoulders rotate toward the anchor. The press should look like a straight punch away from the sternum.",
 "sets": "3 sets of 8-10 presses per side, rest 45 seconds.",
 "easier": "Stand closer to the anchor, lighter band.",
 "harder": "Step further away, or press and hold five seconds."},
{"id": "cat-cow", "name": "The cat-cow", "cat": CORE,
 "muscles": "Spine mobility, core awareness", "equip": "None",
 "cues": ["On hands and knees, start with a flat back.",
          "Exhale and round the spine up toward the ceiling, chin tucked.",
          "Inhale and let the belly drop, chest forward, gently.",
          "Move slowly with the breath for the whole set."],
 "mistake": "Rushing through it like a stretch to get over with. This is a mobility drill - slow rounds are the reps.",
 "sets": "2 sets of 8-10 slow rounds. A perfect warm-up first thing.",
 "easier": "Do it seated in a chair with hands on the knees.",
 "harder": "Add a slow breath hold at each end position."},
{"id": "suitcase-carry", "name": "The suitcase carry", "cat": CORE,
 "muscles": "Core, grip, shoulders", "equip": "One dumbbell or a heavy bag",
 "cues": ["Hold the weight in one hand like a suitcase.",
          "Stand tall - shoulders level, do not lean away from the weight.",
          "Walk 30-40 slow steps, staying perfectly upright.",
          "Set it down, switch hands, repeat."],
 "mistake": "Tilting toward or away from the weight. A mirror or window reflection tells the truth.",
 "sets": "3 carries per side, rest 60 seconds.",
 "easier": "Lighter weight, shorter walk.",
 "harder": "Heavier weight - this move rewards load more than distance."},
# ---------------- CONDITIONING ----------------
{"id": "marching-in-place", "name": "Marching in place", "cat": COND,
 "muscles": "Heart, legs", "equip": "None",
 "cues": ["Stand tall and march, lifting each knee to hip height.",
          "Swing the arms naturally, like walking with intent.",
          "Stay light on your feet.",
          "Breathe rhythmically; this should feel like a 4-6 out of 10 effort."],
 "mistake": "Treating it as nothing. Knees genuinely high and arms genuinely swinging make it real cardio.",
 "sets": "3-10 minutes continuous, or 3 rounds of 2 minutes between strength moves.",
 "easier": "Slow the pace, hold a chair.",
 "harder": "Speed up into high knees, or add light hand weights."},
{"id": "jumping-jack", "name": "The jumping jack", "cat": COND,
 "muscles": "Heart, full body", "equip": "None",
 "cues": ["Jump the feet wide as the hands sweep overhead.",
          "Jump them back together as the arms come down.",
          "Land softly, knees bent.",
          "Find a rhythm you can hold for a full minute."],
 "mistake": "Stiff landings. Quiet feet are kind feet - land through the balls of the feet.",
 "sets": "3 rounds of 30-60 seconds, rest 30-60 seconds.",
 "easier": "Step-jacks: step one foot out at a time, no jumping.",
 "harder": "Squat-jacks: land into a shallow squat each rep."},
{"id": "high-knees", "name": "High knees", "cat": COND,
 "muscles": "Heart, hip flexors, legs", "equip": "None",
 "cues": ["Run in place, driving each knee to hip height.",
          "Stay on the balls of your feet, quick contacts.",
          "Pump the arms hard.",
          "Lean slightly forward from the ankles, not the waist."],
 "mistake": "Leaning back and flicking the heels instead of lifting the knees. Knees up, chest tall.",
 "sets": "3 rounds of 20-40 seconds, rest 60 seconds.",
 "easier": "March in place with high knees instead of running them.",
 "harder": "Sprint the knees faster for 20 seconds - a genuine interval."},
{"id": "mountain-climber", "name": "The mountain climber", "cat": COND,
 "muscles": "Heart, core, shoulders", "equip": "None",
 "cues": ["Start in a strong plank, hands under shoulders.",
          "Drive one knee toward your chest, then switch quickly.",
          "Hips stay level and low - no piking up.",
          "Shoulders stay stacked over the hands."],
 "mistake": "Bouncing hips up and down. Lock the hips in place; only the legs move.",
 "sets": "3 rounds of 20-40 seconds, rest 60 seconds.",
 "easier": "Slow it to a deliberate plank knee-tuck, hands on a bench.",
 "harder": "Cross-crawlers: drive each knee toward the opposite elbow."},
{"id": "squat-to-stand", "name": "The squat-to-stand", "cat": COND,
 "muscles": "Heart, legs, hips", "equip": "None",
 "cues": ["Stand tall, then hinge and grab your toes (or shins).",
          "Drop your hips into a deep squat, keeping the grip.",
          "Lift the hips first, then walk the hands back toward the feet.",
          "Stand up and repeat. A flowing warm-up that wakes the whole back line."],
 "mistake": "Forcing depth on day one. Bend the knees as much as needed; the range opens up over weeks.",
 "sets": "2-3 rounds of 8-10 slow reps. Ideal as warm-up move one.",
 "easier": "Grab the shins or knees instead of the toes.",
 "harder": "Full grip on the toes with straighter legs each time."},
{"id": "skater-bound", "name": "The skater bound", "cat": COND,
 "muscles": "Heart, glutes, balance", "equip": "None",
 "cues": ["Bound sideways from one foot to the other.",
          "Land softly on one leg, opposite leg sweeping behind.",
          "Absorb the landing with a bent knee and hip.",
          "Pause briefly on each landing to own the balance."],
 "mistake": "Landing on a straight leg with a hard knee. Every landing is a small squat.",
 "sets": "3 rounds of 20-30 seconds, rest 60 seconds.",
 "easier": "Step side-to-side without leaving the floor.",
 "harder": "Bound further and hold each landing for two seconds."},
{"id": "step-through-burpee", "name": "The step-through burpee", "cat": COND,
 "muscles": "Heart, full body", "equip": "None",
 "cues": ["Squat, place your hands on the floor.",
          "Step the feet back to a plank (no jump needed).",
          "Step the feet back in and stand tall - add a small hop if you like.",
          "That is one. Smooth beats frantic."],
 "mistake": "Letting the hips sag in the plank phase. The plank in the middle is part of the rep, not a rest.",
 "sets": "3 rounds of 5-10 reps, rest 60-90 seconds.",
 "easier": "Walk the hands out on an incline (bench) instead of the floor.",
 "harder": "Jump back and jump up, or add a push-up in the plank."},
{"id": "jump-rope", "name": "Jump rope", "cat": COND,
 "muscles": "Heart, calves, coordination", "equip": "A skipping rope (or an invisible one)",
 "cues": ["Small hops, barely leaving the floor - an inch is plenty.",
          "Wrists turn the rope; the arms stay quiet.",
          "Land on the balls of the feet with soft knees.",
          "Start with 30-second rounds and build."],
 "mistake": "Jumping too high and tiring the calves in a minute. Small, fast, relaxed hops.",
 "sets": "3-5 rounds of 30-60 seconds, rest 30-60 seconds.",
 "easier": "Mime the rope and do the same small hops.",
 "harder": "Alternate feet as if jogging, or try 20 fast skips each round."},
{"id": "shadow-boxing", "name": "Shadow boxing", "cat": COND,
 "muscles": "Heart, shoulders, core", "equip": "None",
 "cues": ["Stand staggered, hands up, weight on the balls of the feet.",
          "Throw straight punches, turning the hip with each one.",
          "Keep moving - small steps, slight slips, hands returning to guard.",
          "Stay relaxed; tension kills the pace."],
 "mistake": "Fully straightening and snapping the elbows. Punch with control - stop just short of lockout.",
 "sets": "3 rounds of 1-2 minutes, rest 60 seconds.",
 "easier": "Punch slower with feet still.",
 "harder": "Add a squat each time the hands reset, or hold light weights (under 1 kg)."},
{"id": "stair-climb", "name": "Stair climbing", "cat": COND,
 "muscles": "Heart, glutes, quads", "equip": "A staircase",
 "cues": ["Climb at a steady pace, whole foot on each step where you can.",
          "Use the rails lightly for balance, not for lifting.",
          "Walk down slowly - the way down is the braking work.",
          "Steady beats sprinting for most people."],
 "mistake": "Sprinting up and then skipping the descents to rest. Down-walks are part of the set.",
 "sets": "5-10 minutes of up-and-down, or 3 rounds of 2 minutes.",
 "easier": "One flight at a time with full rests.",
 "harder": "Two steps at a time, or add a light backpack."},
]

CATS = [
    (PUSH, "Push day, taught: 16 chest, shoulder and tricep moves",
     "Every push exercise in the library - from wall push-ups to handstand holds - with setup, the one cue that matters, the common mistake, and the sets.",
     ["Pushing is half of all upper-body strength: pressing a door, lifting a box overhead, getting up off the floor. This page collects every pushing exercise in the library, ordered roughly from easiest to hardest within each family of kit.",
      "New here? Start with the incline push-up and the bench dip. Own those for two weeks, then work down this page. Each move lists its muscles, the kit you need, the setup cues a coach would give you, the mistake everyone makes, and the sets to aim for."]),
    (PULL, "Pull day, taught: 16 back and bicep moves",
     "Rows, pulldowns and curls for a strong back - the postural half of training that most home programmes skip.",
     ["Pulling balances all the pushing in your week, and it is the half that fixes desk posture: rows open the chest, strengthen the shoulder blades, and build the arms honestly. Most home programmes skip it because it is harder to train without a gym. This page fixes that with towels, door frames and bands.",
      "No equipment at all? The towel row and doorway row need neither dumbbells nor bands. If you have one resistance band, the pulldown, pull-apart and face pull cover the whole back. If you have one dumbbell, the one-arm row is your bread and butter."]),
    (LEGS, "Leg day, taught: 16 squat, lunge and hinge moves",
     "Squats, lunges, bridges and hinges - the biggest muscles in the body, trained with nothing more than a floor, a wall and a step.",
     ["Legs are more than half the muscle in your body, and they respond to surprisingly little kit: a squat, a lunge, a bridge and a hinge cover everything. This page teaches each one the way a good coach would - setup, cue, mistake, sets.",
      "The pattern to learn first is the squat. The pattern most people skip is the hinge (the Romanian deadlift teaches it). Train both weekly and the rest of this page is refinement."]),
    (CORE, "Core, taught: 14 ab and stability moves",
     "Planks, dead bugs, carries and anti-rotation - a midsection that carries groceries and protects the back, not one that only does crunches.",
     ["A useful core does three jobs: it resists arching, it resists twisting, and it transfers force between your legs and arms. Crunches train almost none of that. This page is built around what actually works - planks and their cousins, slow leg work, and carries.",
      "The honest rule: abs are revealed by the kitchen and built by the library. These ten moves build the muscle; the calculators page helps with the arithmetic around it."]),
    (COND, "Conditioning, taught: 13 heart-pumping moves",
     "Marching, jacks, climbers, ropes and stairs - cardio you can do in a living room, no treadmill required.",
     ["Conditioning is the third pillar: strength makes you capable, and conditioning makes you tireless. You do not need a treadmill - you need sixty seconds and a patch of floor. These ten moves scale from a gentle march to genuinely hard intervals.",
      "Use them three ways: as a warm-up before strength work, as finishers after it, or as standalone 15-20 minute sessions when a full workout is not happening today."]),
]

TITLES = {
    PUSH: "Exercise library: push moves",
    PULL: "Exercise library: pull moves",
    LEGS: "Exercise library: leg moves",
    CORE: "Exercise library: core moves",
    COND: "Exercise library: conditioning moves",
}


def moves_for(cat):
    return [x for x in EXERCISES if x["cat"] == cat]


LIB_TITLE = "The exercise library: 75 moves, taught honestly"
LIB_DEK = ("A real coach's card for every move: muscles, kit, setup cues, the common mistake, "
           "the sets, and an easier and harder version. The gym in your pocket.")
LIB_BODY = """<p>This is the desk's gym: 75 moves across five taught pages, covering every session on this site. Each move is taught the way a good coach cues it - the muscles it works, the kit it needs, the setup, the one line of technique that matters most, the mistake everyone makes, and the sets to aim for. Every move also carries an easier and a harder version, so the page grows with you instead of expiring.</p>
<h2>Pick your page</h2>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px">
<a class="btn secondary" style="display:block;padding:18px 16px;text-align:left" href="/exercise-library-push/"><b>Push - 16 moves</b><small style="display:block;color:var(--dim);margin-top:6px;text-transform:none;letter-spacing:0;font-size:13px">Chest, shoulders, triceps: from wall push-ups toward handstand holds.</small></a>
<a class="btn secondary" style="display:block;padding:18px 16px;text-align:left" href="/exercise-library-pull/"><b>Pull - 16 moves</b><small style="display:block;color:var(--dim);margin-top:6px;text-transform:none;letter-spacing:0;font-size:13px">Rows, pulldowns and curls: the postural half most home programmes skip.</small></a>
<a class="btn secondary" style="display:block;padding:18px 16px;text-align:left" href="/exercise-library-legs/"><b>Legs - 16 moves</b><small style="display:block;color:var(--dim);margin-top:6px;text-transform:none;letter-spacing:0;font-size:13px">Squats, lunges and hinges: more than half the muscle you own.</small></a>
<a class="btn secondary" style="display:block;padding:18px 16px;text-align:left" href="/exercise-library-core/"><b>Core - 14 moves</b><small style="display:block;color:var(--dim);margin-top:6px;text-transform:none;letter-spacing:0;font-size:13px">Planks, carries and anti-rotation: a midsection that works, not one that only crunches.</small></a>
<a class="btn secondary" style="display:block;padding:18px 16px;text-align:left" href="/exercise-library-cond/"><b>Conditioning - 13 moves</b><small style="display:block;color:var(--dim);margin-top:6px;text-transform:none;letter-spacing:0;font-size:13px">Living-room cardio: marching, jacks, climbers, ropes and stairs.</small></a>
</div>
<h2>If you learn only eight moves</h2>
<p>Start here. These eight cover the whole body and every one of them has an easier version on its page:</p>
<ul>
<li><a href="/exercise-library-legs/#bodyweight-squat">The bodyweight squat</a> - legs, the foundation</li>
<li><a href="/exercise-library-push/#incline-push-up">The incline push-up</a> - the push that meets you at your level</li>
<li><a href="/exercise-library-pull/#doorway-row">The doorway row</a> - the pull a door frame can give you</li>
<li><a href="/exercise-library-legs/#glute-bridge">The glute bridge</a> - the hinge, learned lying down</li>
<li><a href="/exercise-library-core/#forearm-plank">The forearm plank</a> - the brace everything else stands on</li>
<li><a href="/exercise-library-core/#dead-bug">The dead bug</a> - the deep core, taught slowly</li>
<li><a href="/exercise-library-cond/#marching-in-place">Marching in place</a> - the heart, honest and gentle</li>
<li><a href="/exercise-library-core/#suitcase-carry">The suitcase carry</a> - strength you can feel the next day</li>
</ul>
<h2>Three ways to use the library</h2>
<p><b>Learn first, train second.</b> Read a move's cues, do one easy set, and check yourself in a mirror or phone camera. The mistake notes exist because they are what coaches correct a hundred times.</p>
<p><b>Let the builder assemble your week.</b> The <a href="/workout-builder/">workout builder</a> turns this library into a three- or four-day plan for your goal, with links back to every move it prescribes.</p>
<p><b>Progress on purpose.</b> When the top of a rep range feels easy for two sessions in a row, move to that exercise's harder version - that is the whole game. Numbers stay approximate: this is guidance, not a medical plan, and results are not guaranteed.</p>
<p><b>Counting calories too?</b> The <a href="/fitness-calculators/">fitness calculators</a> do BMI, water, protein and barbell plate maths in ten seconds.</p>"""


import os as _os
_IMG_DIR = _os.path.join(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))), "assets", "fitness", "img")


def _img_html(x):
    """Form illustration when one exists at assets/fitness/img/<id>.png."""
    if _os.path.isfile(_os.path.join(_IMG_DIR, x["id"] + ".png")):
        return ('<img class="lib-img" src="/assets/fitness/img/' + x["id"] + '.png" '
                'alt="Form illustration: ' + x["name"].replace("The ", "") + ', side view" loading="lazy" width="1408" height="768">')
    return ""


def missing_illustrations():
    """Every move id whose assets/fitness/img/<id>.png is absent."""
    return [x["id"] for x in EXERCISES
            if not _os.path.isfile(_os.path.join(_IMG_DIR, x["id"] + ".png"))]


def assert_illustrations_complete():
    """Gate the build on the 75 form illustrations actually being present.

    _img_html() returns "" for a missing PNG, so a build run anywhere the
    assets are absent used to emit every exercise card with no illustration
    and no error at all - and package.json's "|| echo ... using committed
    static output" would swallow it. Deployed, that silently strips all 75
    images from the library.

    Loud by default. Set BRYME_ALLOW_MISSING_ILLUSTRATIONS=1 to downgrade to a
    warning for environments that legitimately hold no binary assets (CI
    caches, partial checkouts); that variable is an explicit opt-out, so a
    green build can never mean "images quietly dropped".
    """
    missing = missing_illustrations()
    if not missing:
        return
    detail = (f"{len(missing)} of {len(EXERCISES)} exercise illustrations missing from "
              f"{_IMG_DIR}\n  " + ", ".join(missing))
    if _os.environ.get("BRYME_ALLOW_MISSING_ILLUSTRATIONS") == "1":
        print("fitness-library: WARNING - " + detail)
        return
    raise SystemExit("fitness-library: refusing to build - " + detail + "\n"
                     "Every exercise card must ship illustrated. Restore the PNGs, or set "
                     "BRYME_ALLOW_MISSING_ILLUSTRATIONS=1 to build without them deliberately.")


def library_pages():
    """B71: the 5 category pages, in FIT_MORE tuple shape (slug, kind, title, dek, body)."""
    assert_illustrations_complete()
    pages = []
    for cid, ctitle, cdek, cintro in CATS:
        ms = moves_for(cid)
        body = "<p>" + cintro[0] + "</p><p>" + cintro[1] + "</p>"
        body += ('<p class="lib-meta"><b>On this page:</b> '
                 + " &middot; ".join('<a href="#' + x["id"] + '">' + x["name"].replace("The ", "") + "</a>" for x in ms)
                 + "</p>")
        for x in ms:
            cues = "".join("<li>" + c + "</li>" for c in x["cues"])
            body += ('<div class="lib-move" id="' + x["id"] + '">'
                     "<h3>" + x["name"] + "</h3>" + _img_html(x)
                     + '<p class="lib-meta"><b>Works:</b> ' + x["muscles"]
                     + " &middot; <b>Kit:</b> " + x["equip"] + "</p>"
                     "<p><b>Setup and cues:</b></p><ul>" + cues + "</ul>"
                     "<p><b>The mistake everyone makes:</b> " + x["mistake"] + "</p>"
                     "<p><b>Sets:</b> " + x["sets"] + "</p>"
                     "<p><b>Easier:</b> " + x["easier"] + "<br><b>Harder:</b> " + x["harder"] + "</p>"
                     "</div>")
        body += ('<p><b>Form beats everything.</b> Stop short of sharp pain, leave 1-2 reps in the tank, '
                 "and add a rep or a little load when the top of the range feels easy two sessions running. "
                 "Numbers on this page are approximate starting points, not medical advice.</p>")
        sibs = [c for c, _, _, _ in CATS if c != cid]
        body += "<h2>Keep going</h2><ul>"
        for sc in sibs[:3]:
            body += ('<li><a href="/exercise-library-' + sc + '/">'
                     + [t for c, t, _, _ in CATS if c == sc][0] + "</a></li>")
        body += ('<li><a href="/workout-builder/">The workout builder - turn these moves into a weekly plan</a></li>'
                 '<li><a href="/1rm-calculator/">The one-rep max calculator - what your reps say about your strength</a></li>'
                 "</ul>")
        pages.append(("exercise-library-" + cid, "guide", ctitle, cdek, body))
    return pages


def hub_override():
    """B71: (title, dek, body) that replaces the old 15-move exercise-library page."""
    return (LIB_TITLE, LIB_DEK, LIB_BODY)


# ---- batch 77: the deepening loop, round one. 22 more moves - the dumbbell,
# band and harder-bodyweight layer. Every move same card structure, same laws.
EXTRA_EXERCISES = [
{"id": "diamond-push-up", "name": "The diamond push-up", "cat": PUSH,
 "muscles": "Triceps, chest", "equip": "None",
 "cues": ["Hands close together under your chest, thumbs and index fingers forming a diamond.",
          "Body one straight line, as with every push-up.",
          "Lower your chest to your hands, elbows brushing your ribs.",
          "Press up without letting the elbows flare out."],
 "mistake": "Hands too high, toward the face - that wrecks the wrists. The diamond sits under the sternum.",
 "sets": "3 sets of 4-10 reps, rest 60-90 seconds.",
 "easier": "Do them from the knees first; keep the same diamond under the chest.",
 "harder": "Feet on a step, or a slow three-second lowering."},
{"id": "decline-push-up", "name": "The decline push-up", "cat": PUSH,
 "muscles": "Upper chest, shoulders", "equip": "A step, bench or sturdy chair",
 "cues": ["Feet on the step, hands on the floor, body one straight line.",
          "The higher the feet, the more the shoulders work - start low.",
          "Lower your chest to just above the floor.",
          "Press up and keep the hips from sagging."],
 "mistake": "Feet too high too soon - past knee height this becomes a shoulder press with wrist strain. Low steps first.",
 "sets": "3 sets of 5-12 reps, rest 60-90 seconds.",
 "easier": "A low step, or fewer reps than your floor push-ups.",
 "harder": "Raise the feet, or add a slow lowering phase."},
{"id": "band-shoulder-press", "name": "The band shoulder press", "cat": PUSH,
 "muscles": "Shoulders, triceps", "equip": "A resistance band",
 "cues": ["Stand on the middle of the band, feet hip-width.",
          "Bring the ends to shoulder height, palms forward, elbows down.",
          "Press straight up until your arms are overhead.",
          "Lower slowly, resisting the band all the way down."],
 "mistake": "Leaning back to press. Ribs stay down; if you cannot stay tall, shorten the band.",
 "sets": "3 sets of 10-15 reps, rest 60-90 seconds.",
 "easier": "Press one arm at a time, other hand anchoring the band at your shoulder.",
 "harder": "Shorten the band under your feet for more tension."},
{"id": "arnold-press", "name": "The Arnold press", "cat": PUSH,
 "muscles": "Shoulders (all three heads)", "equip": "Two dumbbells",
 "cues": ["Start with dumbbells at shoulder height, palms facing you.",
          "Press up while rotating your palms to face forward.",
          "Finish with arms overhead, palms forward.",
          "Reverse the rotation on the way down - a smooth circle."],
 "mistake": "Rushing the rotation. The turn is the exercise - half speed is full value.",
 "sets": "3 sets of 8-12 reps, rest 90 seconds. Lighter than a normal press.",
 "easier": "Seated with a back support, one arm at a time.",
 "harder": "A one-second pause at the top of each rep."},
{"id": "dumbbell-floor-press", "name": "The dumbbell floor press", "cat": PUSH,
 "muscles": "Chest, triceps", "equip": "Two dumbbells",
 "cues": ["Lie on your back on the floor, knees bent, dumbbells at your chest.",
          "Press the dumbbells up until your arms are straight.",
          "Lower until your upper arms gently touch the floor.",
          "Pause, then press again - the floor is your spotter."],
 "mistake": "Dropping the elbows hard onto the floor. Lower with control and let them kiss the ground.",
 "sets": "3 sets of 8-12 reps, rest 90 seconds.",
 "easier": "One dumbbell, both hands.",
 "harder": "A slow three-second lowering, or a pause on the floor each rep."},
{"id": "band-row", "name": "The seated band row", "cat": PULL,
 "muscles": "Upper back, lats, biceps", "equip": "A resistance band",
 "cues": ["Sit tall with legs extended, band looped around both feet, held at each end.",
          "Sit up straight - the band should already be slightly tight.",
          "Row your elbows back past your ribs, squeezing the shoulder blades.",
          "Return slowly; do not let the band snap you forward."],
 "mistake": "Rocking your torso to move the band. The back stays tall and still - the arms and shoulder blades do the work.",
 "sets": "3 sets of 10-15 reps, rest 60 seconds.",
 "easier": "Hold the band closer to the feet for less tension.",
 "harder": "A thicker band, or a one-second squeeze at the end of every rep."},
{"id": "inverted-row", "name": "The inverted row", "cat": PULL,
 "muscles": "Upper back, lats, biceps", "equip": "A sturdy table (or a bar at hip height)",
 "cues": ["Lie under a sturdy table, hands on its edge, arms straight.",
          "Walk your feet forward until your body is one straight line at an angle.",
          "Pull your chest to the table edge, elbows tight to your sides.",
          "Lower yourself slowly. Test the table does not tip before the first rep."],
 "mistake": "Letting the hips sag - the body is one plank throughout. Bend the knees and shorten the lever if needed.",
 "sets": "3 sets of 6-12 reps, rest 60-90 seconds.",
 "easier": "Stand more upright - a steeper angle is easier.",
 "harder": "Walk the feet further forward, elevate the feet, or try one arm at a time."},
{"id": "dumbbell-shrug", "name": "The dumbbell shrug", "cat": PULL,
 "muscles": "Traps (upper back, neck)", "equip": "Two dumbbells",
 "cues": ["Stand tall, a dumbbell in each hand at your sides.",
          "Raise both shoulders straight up toward your ears.",
          "Pause one second at the top.",
          "Lower slowly - never roll the shoulders."],
 "mistake": "Rolling the shoulders in circles. The shrug is a straight up-and-down; rolling adds nothing and strains.",
 "sets": "3 sets of 12-15 reps, rest 60 seconds.",
 "easier": "One arm at a time, holding a rail for posture.",
 "harder": "Heavier dumbbells with the same one-second pause."},
{"id": "concentration-curl", "name": "The concentration curl", "cat": PULL,
 "muscles": "Biceps", "equip": "One dumbbell",
 "cues": ["Sit on a bench or chair, feet wide, elbow braced inside your thigh.",
          "Curl the dumbbell up, keeping the arm pinned to the inner leg.",
          "Squeeze at the top for one second.",
          "Lower slowly - this isolation tolerates no cheating, which is the point."],
 "mistake": "Swinging the torso to start the rep. If the weight needs a swing, it needs to be lighter.",
 "sets": "3 sets of 10-12 reps per arm, rest 45-60 seconds.",
 "easier": "Lighter weight - isolation moves reveal exactly how strong the muscle is.",
 "harder": "A three-second lowering on every rep."},
{"id": "band-curl", "name": "The band curl", "cat": PULL,
 "muscles": "Biceps", "equip": "A resistance band",
 "cues": ["Stand on the middle of the band, an end in each hand.",
          "Curl the hands up to shoulder height, elbows pinned to your ribs.",
          "Squeeze at the top - the band peaks there, so work hardest where it is hardest.",
          "Lower slowly."],
 "mistake": "Walking your feet wider mid-set to slacken the band. Set the tension honestly before the first rep.",
 "sets": "3 sets of 12-15 reps, rest 60 seconds.",
 "easier": "Stand wider on the band, or curl one arm at a time.",
 "harder": "Narrow stance on the band for more tension."},
{"id": "bulgarian-split-squat", "name": "The Bulgarian split squat", "cat": LEGS,
 "muscles": "Quads, glutes, balance", "equip": "A bench, chair or step",
 "cues": ["Stand about two foot-lengths in front of the bench, one foot's lace resting on it.",
          "Lower straight down until the front thigh is parallel to the floor.",
          "The front shin stays roughly vertical; the weight is on the front heel.",
          "Drive up through the front leg. Finish the set, then switch."],
 "mistake": "Standing too close to the bench - the back knee rams forward. Distance comes out first, depth comes second.",
 "sets": "3 sets of 6-10 reps per leg, rest 90 seconds.",
 "easier": "Hold a wall or chair for balance; reduce the depth.",
 "harder": "Dumbbells at your sides, or a slow three-second lowering."},
{"id": "cossack-squat", "name": "The cossack squat", "cat": LEGS,
 "muscles": "Quads, glutes, inner thighs, balance", "equip": "None",
 "cues": ["Stand wide, toes slightly out.",
          "Shift your weight over one foot and sit down sideways, the other leg straight with the heel down.",
          "Keep the working heel flat and the chest as tall as you can.",
          "Return to centre and switch sides."],
 "mistake": "Letting the working heel lift. Depth follows mobility - squat only as low as the heel allows, and let the range grow over weeks.",
 "sets": "3 sets of 5-8 reps per side, rest 60-90 seconds.",
 "easier": "Hold a door frame for balance and stop at any depth.",
 "harder": "Deeper squats, or hold a weight at your chest."},
{"id": "hip-thrust", "name": "The hip thrust", "cat": LEGS,
 "muscles": "Glutes, hamstrings", "equip": "A bench or sofa edge (dumbbell optional)",
 "cues": ["Sit on the floor with your upper back against the bench edge, knees bent.",
          "Drive through the heels and push the hips up until your body is one line.",
          "Squeeze the glutes hard for one second at the top.",
          "Lower with control. Chin stays tucked; the movement is a hinge, not a neck exercise."],
 "mistake": "Overextending - arching the lower back past the top line. The hips stop when the body is straight.",
 "sets": "3 sets of 8-15 reps, rest 60-90 seconds.",
 "easier": "A glute bridge on the floor (no bench) with the same squeeze.",
 "harder": "A dumbbell or bag across the hips."},
{"id": "band-good-morning", "name": "The band good morning", "cat": LEGS,
 "muscles": "Hamstrings, glutes, lower back", "equip": "A resistance band",
 "cues": ["Stand on the band, ends over your shoulders (or held at your chest).",
          "Soft knees, tall chest - then push the hips straight back.",
          "Hinge until you feel the hamstrings load, back flat the whole way.",
          "Drive the hips forward to stand, squeezing the glutes."],
 "mistake": "Rounding the back to chase depth. The hinge stops where the hamstrings end - the range is honest, not maximal.",
 "sets": "3 sets of 10-15 reps, rest 60-90 seconds. Start light: this move teaches the hinge.",
 "easier": "Unweighted hinge with hands sliding down the thighs.",
 "harder": "A slow three-second hinge, or a thicker band."},
{"id": "donkey-calf-raise", "name": "The donkey calf raise", "cat": LEGS,
 "muscles": "Calves", "equip": "A step (a dumbbell optional)",
 "cues": ["Stand on a step with your heels hanging off the edge; hold a rail.",
          "Hinge slightly forward at the hips - the stretch is the difference.",
          "Rise onto the balls of your feet as high as you can.",
          "Lower slowly until the heels drop below the step edge."],
 "mistake": "Bouncing out of the bottom. The stretched pause and the slow lift are where calves actually grow.",
 "sets": "3 sets of 10-15 reps, rest 45-60 seconds.",
 "easier": "Flat-floor calf raises first (see the classic calf raise).",
 "harder": "One leg at a time, or a dumbbell held at your side."},
{"id": "hollow-rock", "name": "The hollow rock", "cat": CORE,
 "muscles": "Deep core", "equip": "None",
 "cues": ["Start in the hollow hold: lower back pressed down, shoulders and legs a few centimetres up.",
          "Rock gently - shoulders forward, legs back - keeping the shape rigid.",
          "The lower back never leaves the floor.",
          "Rock like a banana, not a seesaw: the shape bends nothing."],
 "mistake": "Kicking from the knees to make the rock happen. The rock comes from the whole rigid shape moving, core braced.",
 "sets": "3 sets of 15-30 seconds of rocking, rest 60 seconds.",
 "easier": "The hollow hold (no rocking) - or tucked knees.",
 "harder": "Longer arms, or small hand weights."},
{"id": "plank-shoulder-tap", "name": "The plank shoulder tap", "cat": CORE,
 "muscles": "Deep core (anti-rotation), shoulders", "equip": "None",
 "cues": ["Start in a strong high plank, feet slightly wider than hip-width.",
          "Tap your left shoulder with your right hand.",
          "Place it down slowly, then tap with the left.",
          "The hips stay perfectly still - that stillness is the entire exercise."],
 "mistake": "Letting the hips sway side to side with each tap. Widen the feet; the wider the base, the quieter the hips.",
 "sets": "3 sets of 10-16 slow taps, rest 45-60 seconds.",
 "easier": "From the knees, same still hips.",
 "harder": "Narrow the feet to hip-width, or slow every tap to two seconds."},
{"id": "side-plank-dip", "name": "The side plank dip", "cat": CORE,
 "muscles": "Obliques, hips", "equip": "None",
 "cues": ["Set a strong side plank: elbow under shoulder, body one line.",
          "Lower the hip a few centimetres toward the floor with control.",
          "Lift the hip back up slightly past straight - a small, honest range.",
          "Finish the set, then switch sides."],
 "mistake": "Rushing big dips. Small ranges with the ribs stacked beat big swings with a collapsing shoulder.",
 "sets": "3 sets of 8-12 dips per side, rest 45-60 seconds.",
 "easier": "Bottom knee down (the kneeling side plank) with the same dip.",
 "harder": "Top foot raised on a low step, or a five-second hover at the bottom."},
{"id": "bear-crawl", "name": "The bear crawl", "cat": CORE,
 "muscles": "Core, shoulders, coordination", "equip": "A few metres of floor",
 "cues": ["Start on hands and knees, knees a centimetre off the floor - that hover is the position.",
          "Crawl forward moving the opposite hand and foot together.",
          "Hips stay low and level; back stays flat.",
          "Breathe. Slow, quiet crawls are the honest ones."],
 "mistake": "Hips piking up high. The knees-hover position is uncomfortable for a reason - that is where the core works.",
 "sets": "3 sets of 20-40 seconds, rest 60 seconds.",
 "easier": "Crawl forward only, short distances, pauses allowed.",
 "harder": "Crawl sideways and backwards, or add a push-up every four steps."},
{"id": "jump-burpee", "name": "The full burpee", "cat": COND,
 "muscles": "Heart, full body", "equip": "None",
 "cues": ["Squat, hands down, jump the feet back to a strong plank.",
          "Lower the chest to the floor - a full push-up, chest to the ground.",
          "Jump the feet back in and explode up into a genuine jump, arms overhead.",
          "Land soft, reset, repeat. The pace you can hold is the right pace."],
 "mistake": "Skipping the chest-to-floor to go faster - that is a hop, not a burpee. Own every phase or slow down.",
 "sets": "3 sets of 5-12 reps, rest 60-90 seconds.",
 "easier": "The step-through burpee (no jump, step back) - it is on this page's conditioning list.",
 "harder": "A tuck jump at the top, or a 20-second sprint of perfect reps."},
{"id": "jumping-lunge", "name": "The jumping lunge", "cat": COND,
 "muscles": "Heart, quads, glutes", "equip": "None",
 "cues": ["Drop into a lunge - both knees about 90 degrees.",
          "Explode up and switch legs in the air.",
          "Land soft into the next lunge, front shin vertical.",
          "Find a rhythm; the landing is the skill."],
 "mistake": "Landing on a straight leg with a stiff knee. Every landing is a soft, quiet squat.",
 "sets": "3 sets of 10-20 total jumps, rest 60-90 seconds.",
 "easier": "Alternating reverse lunges (no jump) - same pattern, no impact.",
 "harder": "Fewer, higher jumps with a mid-air pause."},
{"id": "sprint-intervals", "name": "Sprint intervals", "cat": COND,
 "muscles": "Heart, legs", "equip": "Open ground and honest effort",
 "cues": ["Warm up properly first - five easy minutes and a few strides.",
          "Run hard for 15-30 seconds: not all-out panic, but a pace you could not hold for a minute.",
          "Walk for 60-90 seconds until your breathing settles.",
          "Repeat 4-8 rounds. Done. That is the whole session."],
 "mistake": "Sprinting cold - hamstrings hate it - or turning every interval into a race against yesterday. Consistent hard beats heroic once.",
 "sets": "4-8 rounds of 15-30 seconds hard, 60-90 easy, once or twice a week at most.",
 "easier": "Hill walking with fast effort on the ups, or shorter sprints.",
 "harder": "Longer work intervals (45-60 seconds) or an extra round - never both at once."},
]
EXERCISES.extend(EXTRA_EXERCISES)
