#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch 14: evidence, minimal-kit and health-questions fitness articles.

Tuples: (slug, kind, title, dek, body)
Sources appended to ART_SOURCES via the build hook.
"""

FIT_MORE_14 = [

("posture-exercises-what-evidence-says", "Understand", "Posture exercises: what the evidence actually says",
"Desk posture advice is everywhere and evidence is thinner \u2014 what movement, strength and habit change can and cannot do for how you sit and stand.",
"""<p>If you have ever searched for posture help, you have seen the formula: chin tucks, wall angels, open your chest, stop slouching. Some of it is sensible, some is marketing dressed as medicine, and almost none of it is delivered with the caveat that matters most &mdash; the evidence base for "correcting posture" is far weaker than the confidence of the advice. Here is what is actually supported.</p>
<h2>The problem with "correct posture"</h2>
<p>First conceptual problem: there is no single correct posture. Spines vary enormously between healthy, pain-free people, and the "ideal alignment" diagrams describe one common shape, not a medical standard. Second: posture is not a fixed trait &mdash; everyone shifts positions constantly, and researchers increasingly frame the issue as <em>postural variety</em> rather than postural correctness. The most consistently supported advice in the ergonomic literature is embarrassingly simple: your best posture is your next posture &mdash; frequent position changes beat any single "correct" arrangement. Third: the popular claim that slouching <em>causes</em> back and neck pain is not well supported &mdash; studies find weak and inconsistent links between measured posture and pain. Pain has many contributors, from load tolerance and sleep to stress, and treating a desk shape as the villain oversimplifies a complex picture.</p>
<h2>What exercise does show</h2>
<p>That said, exercise has genuine support &mdash; just not via the mechanism the advice implies. For neck pain, systematic reviews including Cochrane evidence support <b>strengthening and motor-control exercise</b> over passive treatments, with scapular and deep-neck training reducing pain and improving function. For non-specific back pain, general exercise therapy is a first-line recommendation &mdash; and notably, the evidence does not crown any one method: strength training, motor control and general aerobic exercise perform comparably. The mechanism is not "straightening" the spine; it is building tolerance, capacity and confidence in movement. A spine that can handle load in many positions is a more comfortable spine, whatever angle it prefers at rest.</p>
<h2>So what should a desk-bound person do?</h2>
<p>The evidence-honest programme is unglamorous. <b>Move often</b>: break up sitting every 30&ndash;60 minutes &mdash; the variety principle, supported across ergonomic guidance. <b>Strengthen the whole upper back and neck</b>: rows, carries and light neck work &mdash; capacity, not correction; the <a href="/fitness/bodyweight-moves-that-matter/">bodyweight movement guide</a> already contains most of it. <b>Build general fitness</b>: walking, cardio, whatever you will sustain. <b>Ergonomics as comfort, not correction</b>: screen height and chair support matter because comfort enables variety, not because they install a correct shape. And treat persistent pain as a medical question &mdash; the <a href="/fitness/muscle-soreness-vs-injury/">soreness-versus-injury guide</a> sets the boundary &mdash; rather than a project for a posture app.</p>
<p>The honest summary: posture exercises do not straighten spines into a standard shape, because no standard shape exists. What exercise reliably does is make the spine you have stronger, more tolerant and less symptomatic &mdash; and the single best "posture correction" remains the one no app can sell you: standing up more often than is convenient.</p>"""),

("dumbbell-only-home-programme-explained", "Train", "The dumbbell-only home programme: a complete strength plan from one pair",
"One adjustable pair is enough for serious training \u2014 the movement patterns, progression rules and a week-by-week structure.",
"""<p>The dumbbell-only setup gets treated as a compromise. It is not &mdash; for most people's goals it is a complete training system, and arguably a better teaching tool than a barbell because each side must do its own work. The constraint is not the equipment; it is knowing how to build a programme. This is the full structure.</p>
<h2>The six patterns one pair can cover</h2>
<p>Complete strength training is six movement patterns, and dumbbells load all of them. <b>Squat</b>: goblet squats, then dumbbell squats at the sides. <b>Hinge</b>: Romanian deadlifts &mdash; the best single dumbbell lift, hamstrings and glutes loaded deeply. <b>Push horizontal</b>: floor or bench press, push-ups with dumbbells for deficit. <b>Push vertical</b>: overhead press, standing or seated. <b>Pull horizontal</b>: one-arm rows &mdash; and this is where dumbbells beat machines, since each arm pulls independently through a full range. <b>Pull vertical</b>: the one genuine gap; pulldowns or a pull-up bar fills it, or heavy dumbbell pullovers as a compromise. Add loaded carries &mdash; farmer's walks with the heaviest dumbbells you own &mdash; and you have core, grip and posture work the barbell world barely matches.</p>
<h2>The light-dumbbell problem and its three answers</h2>
<p>If your dumbbells are fixed and light, the barbell answer &mdash; add weight &mdash; is unavailable, but the progression science has three substitutes, all with evidence behind them. <b>Reps</b>: light loads taken close to failure build muscle nearly as well as heavy ones &mdash; the <a href="/fitness/how-many-reps-for-muscle/">reps-for-muscle guide</a> covers the equivalence. <b>Tempo and pauses</b>: slow eccentrics and paused reps make a light weight behave like a heavy one. <b>Density</b>: shorter rests, more single-arm work, supersets. The rule that replaces "add 2.5 kg": every week, add one rep per set, one slower tempo, or one shorter rest &mdash; progression is mandatory, its currency is flexible.</p>
<h2>The week</h2>
<p>Three sessions, full-body, alternating emphasis. <b>Day A</b>: goblet squat 3&times;8&ndash;12, DB bench or push-up 3&times;8&ndash;12, one-arm row 3&times;10&ndash;12/side, Romanian deadlift 3&times;10, farmer's carry 3&times;30s. <b>Day B</b>: DB Romanian deadlift 3&times;8, overhead press 3&times;8&ndash;10, DB row 3&times;10/side, goblet squat 3&times;12 (lighter), plank or loaded carry finisher. <b>Day C</b>: whatever pattern lagged, plus lunges, pullovers and single-arm press work. Warm-ups follow the <a href="/fitness/how-to-warm-up/">warm-up guide</a>; sessions land in 45&ndash;60 minutes. Deload every fifth or sixth week as described in the <a href="/fitness/deload-weeks-explained/">deload guide</a>.</p>
<p>The honest summary: dumbbells are not beginner equipment that serious training graduates from &mdash; the single-arm loading is a feature, the range of motion is superior on presses and rows, and the progression ladder of reps, tempo and density is fully research-backed. Buy one adjustable pair, learn the six patterns, and you own a programme that scales from first month to genuinely strong. The only equipment upgrade worth making later is something to hang from.</p>"""),

("rest-between-sets-explained", "Understand", "Rest between sets: the most ignored variable in training",
"Long rest builds strength, short rest saves time \u2014 what rest-interval research actually shows, by goal.",
"""<p>Everyone tracks sets, reps and weight. Almost nobody tracks the minutes in between &mdash; and the research says that gap is a genuine training variable, with different lengths doing measurably different things. It is also the easiest variable to manipulate when time is short.</p>
<h2>Why rest matters mechanically</h2>
<p>Between sets, three things recover: the immediate energy system (phosphocreatine, largely restored within a few minutes), neuromuscular drive, and the clearance of metabolic by-products. Rest length therefore determines what the next set is actually training. A set taken after full recovery is a <b>strength-quality set</b> &mdash; high force, high intent. A set taken into partial fatigue is a <b>metabolic set</b> &mdash; more fatigue signalling per minute spent. Neither is wrong; they are different stimuli with different price tags.</p>
<h2>What the studies show, by goal</h2>
<p>For <b>strength</b>, longer rest wins consistently: classic work (Schoenfeld's 2016 meta-adjacent trials and follow-ups) found 3-minute rests produced greater strength and, notably, similar or better muscle growth than 1-minute rests in trained lifters &mdash; the old "short rest for size" rule did not survive replication. For <b>muscle growth</b>, the honest read is that volume-quality matters most: rest long enough that each set is hard for the right reasons (load, not accumulated junk fatigue), which for most people means 2&ndash;3 minutes on compounds. For <b>endurance and metabolic work</b>, deliberately short rests (30&ndash;60 seconds) are the point. The <a href="/fitness/how-many-reps-for-muscle/">reps-for-muscle guide</a> covers the loading side; rest is its partner variable &mdash; together they define whether a set trains force or tolerance.</p>
<h2>Practical rules</h2>
<p><b>Main compound lifts: 2&ndash;4 minutes</b> &mdash; judged by readiness, not the clock; when the next set feels like a true top set, go. <b>Isolation and accessory work: 60&ndash;120 seconds</b> &mdash; full neural recovery matters less. <b>Short on time: superset non-competing movements</b> &mdash; pair a push with a pull and total rest doubles without any set suffering; the <a href="/fitness/dumbbell-only-home-programme-explained/">dumbbell programme</a> is built for this. <b>Track it loosely</b>: if your lifts stall and your sessions run long, your rests are probably accidental &mdash; phone-scroll drift adds silent minutes and dilutes intensity judgement. One caveat from the literature: the 3-minute superiority was demonstrated mostly in trained lifters on big lifts; beginners progress on nearly any structured rest because everything is novel.</p>
<p>The honest summary: rest is not downtime between training, it is part of the prescription &mdash; long rest buys set quality and strength, short rest buys density, and the research now favours erring longer on the lifts that matter. The gym's most underrated skill is knowing when the next set will be good, and the clock is just a proxy for that answer.</p>"""),

("muscle-imbalances-explained", "Understand", "Muscle imbalances: what they are, which ones matter and how to fix them",
"Left-versus-right and front-versus-back asymmetries decoded \u2014 which are cosmetic, which predict problems, and the training rules that close the gaps.",
"""<p>"I have a muscle imbalance" is one of the most common self-diagnoses in fitness &mdash; one arm bigger, one hip higher, one side that "doesn't fire." Some asymmetries are real problems, some are normal variation, and the difference between them is rarely what gym folklore says. Here is the honest map.</p>
<h2>First: everyone is asymmetrical</h2>
<p>Perfect symmetry does not exist in living humans. Dominant-side differences in size and strength of 5&ndash;10% are normal findings in healthy, pain-free people; organs, handedness and a lifetime of asymmetric habits guarantee it. The literature's consistent message: asymmetry per se is not pathology. What earns attention is <b>large asymmetry</b> (commonly cited thresholds around 10&ndash;15% side-to-side strength differences), <b>asymmetry plus pain or injury history</b>, and asymmetries that visibly change how a movement is performed &mdash; a hip shift under load, a bar path that curves. Cosmetic size differences without those markers are, honestly, cosmetic.</p>
<h2>Which imbalances the evidence links to problems</h2>
<p>Two families have real research attention. <b>Left-right strength asymmetry</b>, especially in the lower body, is associated in multiple studies with higher injury risk and is used in return-to-play testing after ACL injury &mdash; athletes are typically cleared on limb-symmetry benchmarks. <b>Large strength deficits at the hip and trunk</b> relative to sport demands show up repeatedly in injury literature for runners and field athletes. The popular "tight hip flexors cause anterior pelvic tilt which causes back pain" chain, by contrast, has weak direct support &mdash; posture-to-pain causation is the same overclaimed territory the <a href="/fitness/posture-exercises-what-evidence-says/">posture evidence guide</a> covers.</p>
<h2>How to close the gaps that matter</h2>
<p>The fix protocol is uncontroversial. <b>Train unilaterally</b>: single-leg squats, single-arm presses and rows, single-leg deadlifts &mdash; the <a href="/fitness/dumbbell-only-home-programme-explained/">dumbbell programme</a> is mostly unilateral by nature. <b>Let the weak side set the load</b>: it goes first, the strong side matches its reps and never exceeds &mdash; the standard coaching rule for convergence. <b>Don't over-prescribe</b>: one or two unilateral movements per session plus normal bilateral training outperforms elaborate corrective circuits; most "corrective exercise" has not demonstrated superiority over getting stronger generally. <b>Test, don't guess</b>: simple benchmarks &mdash; single-leg count, single-arm row load for reps &mdash; every few months beat mirror assessments. And when asymmetry comes with pain, that is the <a href="/fitness/muscle-soreness-vs-injury/">soreness-versus-injury guide's</a> domain: assessment first, not a corrective programme.</p>
<p>The honest summary: your body was never symmetrical and does not need to be. The imbalances worth fixing are the measurable ones &mdash; big side-to-side strength gaps, especially in the legs, and any asymmetry that travels with pain. The fix is not exotic: train one side at a time, let the weak side lead, and get generally stronger. Symmetry, in the end, is a by-product of good training &mdash; not its target.</p>"""),

("exercise-when-sick-explained", "Recover", "Should you exercise when you're sick? The honest answer",
"The neck-check rule, what fever really means, myocarditis risk, and how to rebuild after an illness without undoing your training.",
"""<p>Every committed exerciser hits the dilemma: symptoms, a training plan, and the fear of losing fitness either way. The honest answer has real structure &mdash; a few clear rules, one genuine danger, and a rebuild protocol that protects the training you are worried about.</p>
<h2>The rules with actual support</h2>
<p>The widely cited <b>neck check</b> is a reasonable rule of thumb, not law: symptoms above the neck (runny nose, sore throat, mild congestion) generally permit light-to-moderate exercise if you feel up to it &mdash; studies of exercisers with common colds found no harm and no meaningful effect on recovery. Symptoms below the neck &mdash; chest congestion, hacking cough, body aches, stomach illness &mdash; mean rest. And one symptom overrides everything: <b>fever means no exercise, full stop</b>. Fever raises core temperature and heart rate already; training on top adds cardiac strain, dehydrates, and &mdash; per sports-cardiology guidance from bodies including the American College of Sports Medicine &mdash; raises the stakes of the one real danger below.</p>
<h2>The one genuine danger: myocarditis</h2>
<p>Viral infections can inflame the heart muscle &mdash; myocarditis &mdash; and exercise during active infection is a documented risk multiplier; sports-medicine guidance is explicit that athletes with fever and systemic symptoms stay out until cleared, and return is graded and often medically supervised after confirmed cases. This is rare relative to millions of colds, which is exactly why it is easy to dismiss &mdash; and why the guidance is unambiguous anyway. Chest pain, palpitations, disproportionate breathlessness or unusual fatigue during or after illness: stop and get assessed. That is the <a href="/fitness/muscle-soreness-vs-injury/">soreness-versus-injury guide</a> territory, and it applies with extra force here.</p>
<h2>The rebuild protocol</h2>
<p>The fitness fear is exaggerated &mdash; measurable detraining takes roughly two weeks to begin, and a lost week returns faster than it was built (muscle memory is real). The rebuild that avoids the classic mistake &mdash; resuming at pre-illness load and immediately re-crashing &mdash; is graded: <b>day 1&ndash;2 after symptom resolution</b>: easy walks, mobility, nothing that raises breathlessness uncomfortably. <b>Next 3&ndash;5 days</b>: light sessions at roughly half normal volume, RPE kept low. <b>Week 2</b>: normal programme minus the top sets. Full intensity returns when normal sessions feel normal &mdash; usually within a week or two of a routine illness. After anything with fever, add several days to every step, and after confirmed cardiac involvement, only on medical clearance. Meanwhile, protect the recovery basics: the <a href="/fitness/sleep-and-exercise-performance/">sleep guide</a> matters double during illness, because sleep is when immune work happens.</p>
<p>The honest summary: a head cold need not cancel a walk, and missing a week costs less than a relapse costs. Fever, chest symptoms and body-wide illness are rest signals with cardiac reasoning behind them. The plan that protects your training is not training through illness &mdash; it is resting fully, then rebuilding deliberately, and being back to normal a few days later than the impatient version of you wanted.</p>"""),

("exercise-and-longevity-explained", "Understand", "Exercise and longevity: what the research actually shows",
"The single best-evidenced health intervention decoded \u2014 how much movement moves mortality, what the dose-response looks like, and why strength matters more than the headlines say.",
"""<p>Few claims in health science carry the evidence that physical activity does: across hundreds of thousands of participants and decades of follow-up, more activity associates with longer life, and the association survives adjustment for nearly everything. But "exercise is good for you" hides the interesting structure &mdash; the dose-response curve, the specific things movement prevents, and the strength signal most coverage skips.</p>
<h2>The dose-response curve</h2>
<p>The consistent findings, from WHO guidance to the large cohort studies: <b>150&ndash;300 minutes of moderate activity weekly</b> (or 75&ndash;150 vigorous) associates with substantially lower all-cause mortality &mdash; commonly reported around a 20&ndash;35% reduction versus inactivity. The curve's shape matters more than the number: the steepest gain is from <b>nothing to something</b> &mdash; even half the guideline shows meaningful benefit &mdash; and returns flatten above the guideline range, with no mortality penalty observed even at several times the recommendation. Sitting time modifies the picture: high sedentary hours blunt some benefit, which is why the "movement snacks" advice from the <a href="/fitness/desk-stretches-office-workers/">desk guide</a> has epidemiological backing.</p>
<h2>What it specifically protects</h2>
<p>The mortality headline aggregates distinct effects: lower incidence of cardiovascular disease, type 2 diabetes (activity improves insulin sensitivity directly and immediately), several cancers (colon and breast have the strongest evidence), depression and cognitive decline. Mechanisms are concrete &mdash; blood pressure, lipid handling, inflammation markers, endothelial function all move with regular activity. And the effects are not only preventive but functional: the strongest predictor of how well people age is not disease absence but <b>capacity</b> &mdash; cardiorespiratory fitness and muscle strength &mdash; and VO&#8322;max in midlife is among the better predictors of independent living decades later.</p>
<h2>The strength signal</h2>
<p>The part the walking headlines miss: <b>muscle-strengthening activity</b> shows independent mortality associations &mdash; cohort analyses find meaningful risk reduction at roughly 30&ndash;60 minutes of strength training weekly, with the best combined outcomes in people who both lift and do aerobic work. The physiology explains why: muscle is the body's largest glucose sink, its scaffolding against falls (the leading injury-cause spiral in older age), and the reserve that makes illness survivable. Which is the research case for the <a href="/fitness/strength-training-for-beginners/">strength-training guide</a>'s modest prescription being a longevity intervention, not just an aesthetics one &mdash; and for the <a href="/fitness/restarting-exercise-after-a-break/">restart guide</a>'s insistence that starting late still counts: the nothing-to-something step is the biggest one on the curve, at every age studied.</p>
<p>The honest summary: exercise is the closest thing medicine has to a broad-spectrum intervention &mdash; it moves every risk marker that matters for how long and how well people live, and the required dose is smaller and the ceiling higher than the headlines suggest. Walk most days, lift twice a week, sit less, and do it imperfectly rather than not at all: the evidence says the biggest return in all of health science belongs to the person who starts.</p>"""),

]


FIT_SOURCES_14 = {
    "posture-exercises-what-evidence-says": [
        ("Cochrane Library \u2014 exercise reviews for neck and back pain", "https://www.cochranelibrary.com/"),
        ("Harvard Health Publishing \u2014 back pain and posture", "https://www.health.harvard.edu/")],
    "dumbbell-only-home-programme-explained": [
        ("ACE \u2014 resistance training guidance", "https://www.acefitness.org/"),
        ("PubMed \u2014 light-load training near failure and hypertrophy", "https://pubmed.ncbi.nlm.nih.gov/")],
    "rest-between-sets-explained": [
        ("Schoenfeld et al. (2016), J Strength Cond Res \u2014 longer between-set rest", "https://pubmed.ncbi.nlm.nih.gov/26605807/"),
        ("PubMed \u2014 rest interval research", "https://pubmed.ncbi.nlm.nih.gov/")],
    "muscle-imbalances-explained": [
        ("PubMed \u2014 inter-limb asymmetry and injury risk", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("British Journal of Sports Medicine \u2014 return-to-play criteria", "https://bjsm.bmj.com/")],
    "exercise-when-sick-explained": [
        ("American College of Sports Medicine \u2014 exercise and infection", "https://www.acsm.org/"),
        ("PubMed \u2014 myocarditis in athletes", "https://pubmed.ncbi.nlm.nih.gov/")],
    "exercise-and-longevity-explained": [
        ("WHO \u2014 physical activity guidelines", "https://www.who.int/news-room/fact-sheets/detail/physical-activity"),
        ("PubMed \u2014 muscle-strengthening activity and mortality", "https://pubmed.ncbi.nlm.nih.gov/")],
}
