"""BRYME Fitness - batch 8 (Sept 2026, tier-1 focus): the GLP-1 muscle cluster.
Four guides on keeping muscle while losing weight on Ozempic/Wegovy/Mounjaro -
the year's biggest fitness search wave. Desk rules: general information, never
medical advice, prescriber leads on all medication questions; figures only
where multiple sources agree (trial lean-mass shares, protein ranges, training
frequency); claims hedged honestly. Body links are root-level by convention;
build-routing prefixes them with /fitness/."""

FIT_MORE_8 = [
("muscle-on-glp1-weight-loss-drugs", "understand",
"Keeping muscle on Ozempic and Wegovy: what the evidence says",
"A quarter or more of the weight lost on GLP-1 drugs can be lean mass in trial measurements. The honest numbers, why it happens, and the protection protocol research keeps pointing to.",
"""<p>The GLP-1 medications - Ozempic, Wegovy, Mounjaro, Zepbound - are the most effective weight-loss tools most people have ever seen, and they work largely by quieting appetite. That is also where their main catch lives: when intake drops sharply, the body burns muscle along with fat. Trial measurements suggest roughly a quarter to two-fifths of the weight lost can be lean mass rather than fat, though the share varies by drug, dose, study and measurement method - and analyses suggest it is broadly similar to other steep weight loss, not a unique property of these drugs. This is general information, not medical advice: your prescriber leads every medication decision.</p>
<h2>Why muscle is the thing to protect</h2>
<p>Muscle is not just looks. It is the tissue that burns calories around the clock, the strength you stand up with, and the reservoir that makes weight maintenance possible later. A large 2026 analysis of activity-tracker data added a twist worth knowing: people tended to move <i>less</i> after starting these medications, not more - losing weight without training and protein can quietly shrink the engine that keeps it off.</p>
<h2>The protection protocol research points to</h2>
<p>Three levers come up in essentially every serious review. <b>Resistance training two to three times a week</b> - and a controlled trial on semaglutide found participants doing supervised aerobic and resistance exercise (over 150 minutes a week) preserved notably more lean mass than medication alone; older dieting-adult studies found resistance training preserved nearly all lean mass during restriction. <b>Protein above about 1.2 grams per kilo of body weight daily</b>, spread across the day - more on the practical side in <a href="/protein-when-appetite-is-gone/">protein when appetite is gone</a>. <b>Not over-restricting beyond what the medication already does</b> - the appetite suppression is the deficit; piling a crash diet on top is what turns weight loss into muscle loss. The training itself is ordinary beginner-friendly work: <a href="/strength-training-for-beginners/">the beginner's plan</a> is exactly the right starting dose.</p>
<h2>How to tell it is working</h2>
<p>Scales cannot separate fat from muscle, so track simple strength and function markers instead: your carrying capacity, stair comfort, how reps feel at a given weight. If strength holds through months of losing, the loss is mostly fat - <a href="/how-long-to-see-gym-results/">progress you can feel usually shows up before the mirror agrees</a>. If strength slides steadily and fatigue lingers, that is prescriber conversation material, along with dizziness, hair shedding or exhaustion that a normal week does not touch.</p>
<h2>The honest caveats</h2>
<p>People with kidney conditions and older adults need individual advice on protein targets - that is a dietitian conversation, not an internet one. Some lean-mass loss happens in essentially all significant weight loss; the goal is not zero, it is keeping the share small while the fat goes. And the habits that protect muscle on the medication are the same ones that keep weight off after it - <a href="/keeping-weight-off-after-glp1/">the after-the-medication guide</a> covers that bridge, while <a href="/strength-training-while-losing-weight/">strength training in a deficit</a> covers the lifting specifics.</p>"""),

("protein-when-appetite-is-gone", "maintain",
"Protein when your appetite is gone: the practical playbook",
"Weight-loss medications shrink appetite exactly when protein needs go up. The target, the protein-first ordering, and what to do when solid food will not fit.",
"""<p>Appetite-suppressing medications create an odd problem: the days you most need protein are the days food least appeals. Research on keeping muscle during weight loss converges on roughly 1.2 to 1.6 grams per kilo of body weight daily (about 0.55 to 0.7 grams per pound) for people in an active deficit - well above the ordinary baseline, and hard to hit when a few bites feel like a feast. General information, not medical advice; kidney conditions and individual situations change the target, so your prescriber or dietitian leads.</p>
<h2>Protein first, every meal</h2>
<p>The single most useful habit: eat the protein portion <b>before</b> anything else on the plate. Small stomachs fill fast, and the bites that matter most should not be the ones left over. Anchor breakfast especially - it is the meal people skip protein at, and the meal where the day's tally is won or lost.</p>
<h2>Think 25-30 grams at a time</h2>
<p>The body handles protein best in repeated doses, and studies of meal distribution favour roughly 25-30 grams at each of three or four eating occasions over one giant dinner. Practically: eggs or Greek yogurt at breakfast, fish or chicken or tofu at lunch, the same again at dinner, cottage cheese or a shake to close gaps. The everyday version of this arithmetic - with food tables - lives in <a href="/how-much-protein-do-you-need/">how much protein you actually need</a>.</p>
<h2>When solid food will not fit</h2>
<p>This is where shakes and powders earn their shelf space: liquid protein slides past a suppressed appetite in a way a chicken breast will not. Whey or plant isolate in water or milk, stirred into yogurt or porridge, counts exactly the same as food. High-protein yogurt drinks and cottage cheese do the same job cheaply. Supplements are the gap-filler, not the foundation - but on these medications they are often the difference between hitting the target and quietly missing it for weeks.</p>
<h2>The honest difficulties</h2>
<p>Some days the target will not be met, and one low-protein day is not a failure - the pattern over weeks is what matters. Food aversions and nausea deserve respect: cold, bland, dense options (yogurt, milk, smoothies) usually survive better than hot rich ones. And protein drinks still carry calories, so they are part of the intake picture, not a free extra. Pair the whole effort with <a href="/muscle-on-glp1-weight-loss-drugs/">the muscle-protection plan</a> - protein is the material, training is the signal, and neither works alone. For the training table itself, <a href="/creatine-explained/">the creatine explainer</a> covers the one supplement with real muscle-preserving evidence behind it.</p>"""),

("strength-training-while-losing-weight", "guide",
"Strength training in a calorie deficit: what changes, what doesn't",
"You can absolutely lift meaningfully while losing weight - with adjusted expectations, preserved intensity, and a different definition of a good session.",
"""<p>Losing weight and getting stronger at the same time is not the contradiction it is often painted as - beginners and returning lifters do it routinely, and trial data on dieters doing resistance training shows lean mass held almost entirely while fat came off. But the deficit does change the texture of training: recovery is thinner, progress is slower, and the goals shift. Here is what changes and what must not.</p>
<h2>What does not change: the stimulus</h2>
<p>Muscle is kept by asking it to do meaningful work - sets taken close to fatigue with honest effort. In a deficit, that signal matters <i>more</i>, not less, because the body decides what to keep based on what gets used. The evidence-backed rep ranges from <a href="/how-many-reps-for-muscle/">how many reps build muscle</a> apply unchanged: effort near the end of the set is the driver, whether the load is a barbell or <a href="/workout-at-home-no-equipment/">your own bodyweight</a>. Two to three sessions a week covering the whole body is the working dose.</p>
<h2>What changes: the expectations and the recovery</h2>
<p>Personal records are rare in a deficit, and chasing them is how joints and weeks get wrecked. The realistic win is <b>holding</b> your loads and reps while the scale falls - on the gym floor that is winning. Recovery needs sharpen too: sleep stops being optional (<a href="/rest-days-and-recovery/">rest days do real work</a>), session volume is better kept moderate than heroic, and the week you feel flattened is the week to halve the session rather than skip - the habit matters more than the numbers that week. Persistent joint aches and flatness across weeks are a deload signal: <a href="/deload-weeks-explained/">the deload guide</a> covers the planned light week.</p>
<h2>Fuel around the sessions</h2>
<p>Protein is the priority - the deficit is already handled by the diet, so training nutrition means protein timing and enough of it, covered in <a href="/how-much-protein-do-you-need/">the protein guide</a>. Training fasted or fed is a preference question, not a law; what is not a preference is consistent protein across the day and not stacking your hardest sessions onto your emptiest days. Creatine is the one ergogenic aid with strong evidence for exactly this situation: <a href="/creatine-explained/">what it does and does not do</a>.</p>
<h2>The scale will lie to you</h2>
<p>Lifting while losing can hold scale weight steady for weeks while measurements and fit change favourably - muscle is dense, and water shifts with new training. Judge the process on strength markers, photos and measurements, not the morning number. This is the same arithmetic that makes the GLP-1 era's <a href="/muscle-on-glp1-weight-loss-drugs/">muscle-protection problem</a> solvable: the deficit does the losing, the training does the keeping. For the equipment question, <a href="/dumbbell-vs-barbell/">dumbbells versus barbells</a> has a boring answer - whichever you will load honestly.</p>"""),

("keeping-weight-off-after-glp1", "guide",
"After the weight-loss medication: the keeping-it-off plan",
"Regain after stopping GLP-1 drugs is common enough to be expected - which means the exit plan matters as much as the start. Muscle, movement and the honest timeline.",
"""<p>The hardest part of medication-assisted weight loss is not losing the weight - the medication is genuinely good at that. It is the stretch after, when appetite comes back and the structure disappears. Studies following people who stop GLP-1 medications find much of the loss commonly returns within a year or two. That is not a verdict on anyone's character; it is what happens when appetite and habits revert while the lessons never got installed. General information - every stop, taper and dose decision belongs to you and your prescriber.</p>
<h2>Why the weight wants to come back</h2>
<p>Three forces stack up after discontinuation: appetite returns toward (sometimes past) its old level, the body's energy needs run lower at the new lighter weight, and muscle lost during the fast phase - often a quarter or more of the total loss, as covered in <a href="/muscle-on-glp1-weight-loss-drugs/">the muscle guide</a> - quietly lowered the daily burn. None of that is reversible by willpower alone. It is reversible by structure.</p>
<h2>The plan: build the engine while the medication helps</h2>
<p>The single best predictor stories keep repeating: people who trained through the weight-loss phase maintain better than those who dieted through it. If you are still on the medication, now is the easy time to install the habits - <a href="/strength-training-while-losing-weight/">lifting two to three times a week</a> builds the engine that burns the maintenance calories, and every week of practice while appetite is suppressed is a week the habits set without hunger fighting them.</p>
<h2>The three habits that carry the maintenance</h2>
<p><b>Strength training stays non-negotiable</b> - it is the maintenance metabolism and the posture of the whole plan. <b>Protein stays high</b> - it feeds the muscle and happens to be the most filling calorie you can eat, the same <a href="/protein-when-appetite-is-gone/">protein-first ordering</a> that worked on the medication. <b>Movement stays daily</b> - the step habit, walked through in <a href="/30-day-walking-plan/">the 30-day walking plan</a>, is the quiet difference between maintainers and regainers in nearly every follow-up study. None of it is dramatic; all of it is daily.</p>
<h2>The honest timeline</h2>
<p>Expect appetite to return, expect the scale to drift up a little as muscle, water and food volume come back - those are not failure, some of it is repair. Weigh in weekly rather than daily, set a personal action threshold (a few kilos up, not a bad week), and treat crossing it as the cue to tighten the same three habits for a month - not to start anything new. The fitness you built is the asset: <a href="/how-long-to-see-gym-results/">months of training show up as capability</a>, and capability is what a weight-maintained life actually runs on.</p>"""),
]
