"""BRYME Fitness - batch 9 (Sept 2026, tier-1 focus): GLP-1 cluster expansion
(beginner plan, strength over 50, loose skin) plus the is-it-normal
reassurance series (8 short guides). Desk rules: general information, never
medical advice; red-flag symptoms point to professional care without
exception; figures only where sources support them. Body links are
root-level by convention; build-routing prefixes them /fitness/."""

FIT_MORE_9 = [
("glp1-workout-plan-for-beginners", "guide",
"The beginner workout plan for life on a GLP-1",
"Two or three short full-body sessions a week is the evidence-backed dose for protecting muscle on weight-loss medication. The exact plan, the honest effort levels, and the first-month expectations.",
"""<p>The muscle-protection evidence on GLP-1 medications keeps pointing to the same dose: resistance training two to three times a week, full-body, at an honest effort - covered in the science part in <a href="/muscle-on-glp1-weight-loss-drugs/">the muscle guide</a>. This is the doing part: a beginner plan that fits a low-energy week, needs no gym confidence, and survives the days appetite and drive both run low.</p>
<h2>The plan: two exercises, three times, thirty minutes</h2>
<p>Every session is the same shape, which is the point - no decisions on tired days. <b>Warm-up:</b> five easy minutes walking or cycling. <b>Lower body:</b> sit-to-stands from a chair (or box squats) - three sets of eight to twelve. <b>Push:</b> wall or incline push-ups, or a machine chest press - three sets of eight to twelve. <b>Pull:</b> a resistance-band row or dumbbell row - three sets of ten to fifteen. <b>Hinge:</b> a gentle hip hinge pattern with a light dumbbell - two sets of ten. <b>Finish:</b> a five-minute walk. Session one or two of the week adds a carry (shopping-bag in each hand, thirty seconds) and a plank attempt. That is it - the whole plan fits in half an hour, and the machine and dumbbell versions are interchangeable: <a href="/strength-training-for-beginners/">the beginner's guide</a> covers form for each pattern.</p>
<h2>The effort level that works</h2>
<p>End each set feeling you could manage two or three more good reps - close to fatigue, not at failure. That "close-but-not-empty" effort is what signals muscle to stay, and it leaves energy for tomorrow, which matters when medication already dips the tank. If a week comes where everything feels heavy, halve the sets and keep the appointments - the habit is the asset being protected.</p>
<h2>The first month, honestly</h2>
<p>Expect heavy legs after session one (<a href="/sore-two-days-after-workout/">two-day soreness is normal</a>), easier sessions by week three, and no visible change yet - the win is the strength you can feel and the routine that exists. Protein is the other half of the plan: <a href="/protein-when-appetite-is-gone/">the appetite playbook</a> handles the hardest part. And every dose, symptom and medication question belongs to the prescriber - the plan supports the treatment, it never adjusts it.</p>"""),

("strength-training-over-50", "guide",
"Strength training over 50: the case, and the sane start",
"Muscle is lost faster with age unless it is asked for - and it is askable at any age. The two-day-a-week plan, the joint-friendly loads, and the markers that matter more than the mirror.",
"""<p>From the fifties onward, muscle and strength decline faster each year unless training asks the body to keep them - the research framing is blunt about that. The good news is equally blunt: the muscle responds at any starting age, and the largest gains in trials of older adults come from the previously untrained. Two modest sessions a week is the working dose, and nothing here requires a medical check for healthy adults - anyone with a diagnosed condition or long-inactive starts lighter and tells their doctor they are training, which is different from asking permission.</p>
<h2>The plan: two full-body sessions</h2>
<p>Same skeleton at every age: sit-to-stands from a chair progressing toward squats, a push (wall to incline to floor push-ups, or a press), a pull (band or dumbbell row), a hip hinge with a light load, and a carry. Two to three sets, ending each set with two or three reps in reserve - close to fatigue, never grinding. Balance work rides along free: stand on one foot while the kettle boils. Walk on the days between. The full pattern is <a href="/strength-training-for-beginners/">the beginner plan</a> exactly - age changes the starting load, not the structure.</p>
<h2>What changes after fifty</h2>
<p>Three adjustments, all small. <b>Warm-ups get longer</b> - ten honest minutes; the first set of every exercise is a lighter rehearsal. <b>Recovery gets respected</b> - forty-eight hours between sessions stops being optional (<a href="/rest-days-and-recovery/">rest days do the building</a>), and sleep earns its place as training. <b>Progress is tracked in function</b> - stairs, carrying, getting off the floor - because those are the markers that predict independence, and they respond before the mirror does. Soreness behaves the same as at any age (<a href="/sore-two-days-after-workout/">the normal-soreness guide</a>); pain in joints, not muscles, gets looked at rather than trained through.</p>
<h2>Why this page sits on the GLP-1 cluster</h2>
<p>Because the two questions collide: weight-loss medication plus an older muscle mass is the exact scenario where lean-mass loss does the most damage - trials and reviews of muscle on GLP-1s keep singling out older adults as the group for whom the training-and-protein protocol matters most. If that is your situation, this plan and <a href="/protein-when-appetite-is-gone/">the protein playbook</a> are the protection, and <a href="/how-long-to-see-gym-results/">the results timeline</a> is the realistic calendar. Strength at fifty-plus is not fitness vanity - it is the down payment on every independent year that follows.</p>"""),

("loose-skin-and-muscle-after-weight-loss", "understand",
"Loose skin after big weight loss: what actually helps",
"Skin follows the fat on large losses, and the internet sells miracles that do not exist. What genuinely influences it, what muscle does for the shape of it, and the honest timescales.",
"""<p>After a large weight loss - and medication-assisted losses can be large - the question nobody feels prepared for arrives in the mirror. Loose skin is not a failure of the diet or a sign anything went wrong: skin that was stretched for years retracts slowly, partially, and at its own pace set by genetics, age, how long it was stretched and how much was lost. General information only - individual cases are individual.</p>
<h2>What genuinely influences it</h2>
<p><b>Time first:</b> retraction continues for many months - often a year or two - after weight stabilises; judging skin at month three misreads a moving picture. <b>The pace of loss:</b> slower losses give skin more time to follow; there is no re-do button, but it matters for anyone early in the process. <b>Muscle, honestly:</b> building muscle does not remove skin, but it fills the frame underneath it - shoulders, back, glutes and legs change what the silhouette actually is, which is why the training plan in <a href="/muscle-on-glp1-weight-loss-drugs/">the muscle-preservation guide</a> is also the shape plan. <b>Smoking and sun</b> worsen elasticity - the boring levers again.</p>
<h2>What the evidence does not support</h2>
<p>Creams, collagens and supplements marketed for skin tightening have weak evidence at best. Very slow additional loss does not "tighten" skin - losing more when the loss is done tends to worsen the look. And do not let anyone sell urgency: any surgical options exist, vary enormously in appropriateness, and are a much-later, specialist-consultation conversation - months after weight stabilises, never mid-loss.</p>
<h2>The part that is in your hands</h2>
<p>The strength work does double duty here: it is the muscle-preservation protocol <i>and</i> the thing that makes the post-loss body capable and filled-out rather than just smaller. The protein that feeds it - <a href="/protein-when-appetite-is-gone/">especially with a suppressed appetite</a> - supports skin from the inside the honest way: as part of feeding the body you are keeping. And the maintenance habits in <a href="/keeping-weight-off-after-glp1/">the after-the-medication plan</a> protect the loss itself, which is the achievement the skin question too often eclipses: the body that works, carries, and showed up every week - that one is yours regardless.</p>"""),

("sore-two-days-after-workout", "understand",
"Sore two days after a workout? That is how soreness actually works",
"Delayed soreness peaks at 24-72 hours and says nothing about fitness. What causes it, what actually helps, and the line where soreness becomes a check-it-out.",
"""<p>The classic shock: Monday's workout felt fine, Tuesday was fine, and Wednesday morning the stairs have opinions. Delayed-onset muscle soreness - DOMS - routinely peaks one to two days after training, which is precisely why it feels alarming: the delay makes it seem like something went wrong overnight. Nothing did. The soreness is the normal aftermath of muscles doing work they are not used to - especially the lowering, stretching half of movements - and it fades over a day or three.</p>
<h2>What it means, and what it does not</h2>
<p>Soreness means the session was new or harder than recent sessions. It does <b>not</b> score the workout's quality, and its absence does not mean a session failed - the fitter you get, the less a normal session hurts, which is adaptation, not decline (the full confusion unwound in <a href="/not-sore-anymore-did-it-stop-working/">the not-sore-anymore guide</a>). Chasing soreness is the classic beginner error: it selects for reckless sessions, not effective ones.</p>
<h2>What actually helps</h2>
<p>Gentle movement - an easy walk, light cycling, the movements that hurt done small and slow - beats stillness; blood flow is the relief. Sleep, food (including enough <a href="/how-much-protein-do-you-need/">protein</a>), and time do the rest. Light stretching feels good without shortening anything meaningfully. Painkillers are a blunt tool for ordinary soreness and better saved for genuine need. The full toolbox, evidence-ranked, lives in <a href="/doms-relief-what-works/">the DOMS relief guide</a>.</p>
<h2>Training around it</h2>
<p>Mild soreness does not cancel the next session - warm up honestly and train; the movement usually loosens it. Very sore muscles get a different day: train other areas, or take the walk - forty-eight hours before hammering the same muscle group is the sane rhythm anyway (<a href="/rest-days-and-recovery/">why rest days matter</a>). The check-it-out line: pain that is sharp, one-sided and localised (a pulled muscle, not general soreness), soreness that worsens past day three, very dark urine with heavy soreness after an extreme first session - that last one urgently - are find-out-more territory, not push-through territory. Everything else is just the body filing its paperwork.</p>"""),

("not-sore-anymore-did-it-stop-working", "understand",
"Not sore anymore - did my workouts stop working?",
"The opposite worry, equally common and equally wrong: soreness fades because the body adapted, not because results stopped. What to track instead, and when variety actually helps.",
"""<p>First the soreness arrives and you worry it is too much; a few weeks later it stops arriving and you worry that was the good part. Both worries are the same misunderstanding: soreness is a novelty signal, not a results signal. Muscles that get sore from a new stimulus adapt to it remarkably fast - the repeated-bout effect, one of the most reliable findings in exercise science - so the same workout that wrecked week-one-you simply registers as Tuesday by week six. The training still works.</p>
<h2>What to track instead of soreness</h2>
<p>The logbook is the truth: are the weights, reps or sets edging up over weeks? Is the same hill easier? Can the carry go heavier, the plank last longer, the stairs get quieter? That is progress, recorded in units that do not lie - <a href="/how-long-to-see-gym-results/">the results timeline</a> explains the lag between feeling stronger and seeing it. A logbook-less beginner judging by soreness is reading tea leaves; the notebook (or notes app) replaces the tea leaves with data.</p>
<h2>When changing things up genuinely helps</h2>
<p>Variety is not required to keep progress alive - progressive overload is: adding a rep here, a kilo there, a slower lowering phase (<a href="/how-progressive-overload-works/">the whole mechanism</a>). What variety genuinely does is keep motivation fresh and cover movement gaps - so rotate exercises every few months for interest, not because the current ones "stopped shocking the muscles", a phrase fitness marketing invented to sell programmes. Soreness will return whenever a session is genuinely new or much harder; treat it as information about novelty, never as the point.</p>
<h2>The honest exception</h2>
<p>Weeks of no soreness <i>and</i> a stalled logbook <i>and</i> flat effort usually mean the sessions have quietly become ceremony - same weights, same reps, same comfort. That is not adaptation failing; it is the plan needing the next small step up. The fix is one variable, nudged honestly: <a href="/how-many-reps-for-muscle/">effort near the end of sets</a>, then weight, then a new variation. The mirror-and-scale panic version of this question usually dissolves on contact with <a href="/strength-training-while-losing-weight/">what the scale does to lifters</a> - the logbook is kinder and more accurate than both.</p>"""),

("shaking-during-plank-or-lunges", "understand",
"Shaking during a plank or lunges: normal effort, not a malfunction",
"The tremble at the end of a hard hold is motor units firing in shifts - standard-issue muscle behaviour. When it is just effort, when it is fuel, and when to stop.",
"""<p>Thirty seconds into a plank and the arms start broadcasting: a fine tremor, then a wobble, then the full shake. It looks like failure and feels embarrassing, and it is neither - the shake is what a muscle working near its limit looks like from the outside. Muscles fire motor units in rotating shifts; near fatigue, the coordination between those shifts gets ragged and the limb trembles while the muscle keeps producing effort. It is one of the most normal sights in any gym, beginner or otherwise, and it fades with training just like soreness does (<a href="/sore-two-days-after-workout/">the same adaptation story</a>).</p>
<h2>The fuel version of the shake</h2>
<p>Not every tremble is local effort. Whole-body shakiness, especially early in a session, after a big change in eating, or on medication that changes appetite, points at fuel: training hard on an empty system produces a different, less localised shake - the too-low-fuel kind. That version is a signal to eat, not to push: the session ends, something with carbohydrate and protein goes in, and next time the pre-training meal gets a little more respect. Anyone training on appetite-suppressing medication should treat this version seriously - the <a href="/protein-when-appetite-is-gone/">protein-first habit</a> doubles as the anti-shake protocol, and persistent wobbly sessions belong in a prescriber conversation.</p>
<h2>The stop line</h2>
<p>Local muscle trembling at the end of a hard hold: keep going if the form holds, end the set when it does not - form, not the shake, is the limit. Shaking with any of the following is a stop-now signal: dizziness, chest discomfort, sudden breathlessness out of proportion to effort, or feeling faint - those get sat down, fuelled, and if they persist, checked by a professional. Everything else about the plank-shake is boring and good news: it means the effort landed where it should. The plank's own progression, including how long is actually worth holding, is part of <a href="/30-day-plank-challenge/">the plank programme</a>, and the same effort-not-panic logic powers <a href="/how-many-reps-for-muscle/">the rep-range guide</a>.</p>"""),

("heart-pounding-during-workout", "understand",
"Heart pounding during a workout: what is normal, what is not",
"A pounding heart during hard effort is the design working. The honest normal range, the harmless amplifiers, and the short list of signals that mean stop and get checked.",
"""<p>Halfway up a hill or into the third hard interval, the heart is hammering - and for anyone new to training, the sensation itself can scare more than the effort. The reassurance first: a heart that pounds during hard work is doing exactly what it was built to do, moving blood to match demand; effort that never raises the heart rate is effort that is not training anything. A pounding that rises with effort, plateaus with it, and settles within minutes of stopping is the ordinary signature of a working cardiovascular system - and it improves with fitness, which is the whole point of <a href="/cardio-machine-worth-buying/">the cardio work</a>.</p>
<h2>The harmless amplifiers</h2>
<p>Several ordinary things make the same effort feel like more heartbeat: caffeine pre-workout (a real amplifier - <a href="/caffeine-side-effects/">the dose and timing guide</a>), heat and dehydration, training fasted on a rough night's sleep, anxiety about training itself, and being new or returning (<a href="/how-to-start-working-out/">starting from zero</a> legitimately feels like a lot at first). Illness raises resting heart rate for days - the session after a cold feels cardiac at half the effort; that is pacing information, not danger.</p>
<h2>The stop-and-get-checked list</h2>
<p>Short, serious, non-negotiable: chest pain or pressure; pain radiating to jaw or arm; fainting or near-fainting during exercise; a heartbeat that feels irregular or skittering rather than strong; severe breathlessness wildly out of proportion to the effort; or palpitations that persist long after stopping. Any of those - the session ends, and a professional hears about it before the next one. This is general information, not a clearance certificate: anyone with a heart condition, on medication affecting the heart, or simply worried about a specific episode, takes that specific episode to their doctor rather than to an internet page.</p>
<h2>Training inside the normal</h2>
<p>For ordinary pounding: warm up so the ramp is gradual, breathe with the effort instead of holding it, and pace by the talk test - able to speak short sentences means working hard but sane. The fitness adaptation compounds quickly: within weeks the same hill produces less hammering, which is both the proof of progress and, conveniently, <a href="/how-long-to-see-gym-results/">the first result most people actually feel</a>.</p>"""),

("gaining-weight-first-week-of-exercise", "understand",
"Put on weight the first week of exercise? It is not fat",
"New training stores water and glycogen before it burns anything - a two-to-four-pound jump that panics exactly the wrong people. The mechanism, the timeline, and what to do about it.",
"""<p>Week one of the new programme, full of honest effort and sore everything - and the scale is <i>up</i>. Few fitness moments demoralise beginners more reliably, and few are more harmless: several pounds of the jump are water and fuel storage, not fat, and the mechanism is well understood. Muscle restocks glycogen - the carbohydrate it burns - and every gram of glycogen holds roughly three grams of water with it. Add the water response to new training stress, plus (honestly) a possibly heartier appetite, and the first-fortnight scale can drift up two to four pounds while actual body fat is quietly heading down.</p>
<h2>The timeline</h2>
<p>The water jump typically shows in week one or two and settles over the following few weeks as the body adapts to the new normal. Meanwhile the fat-loss arithmetic - if the eating side is in a deficit - continues underneath it. The two signals are running on different clocks, which is why week-one weigh-ins mislead so efficiently. Judging any new programme inside a month is reading a book by its cover; <a href="/how-long-to-see-gym-results/">the realistic results timeline</a> gives the honest calendar.</p>
<h2>What to do about it</h2>
<p>Almost nothing - which is the hard instruction. Keep the sessions, keep the food honest (<a href="/protein-when-appetite-is-gone/">protein-first</a> if appetite-reduction is part of the picture), and weigh weekly rather than daily, same conditions each time. Better: let the tape measure and the fit of one honest pair of trousers co-sign the scale, because recomposition weeks - the ones covered in <a href="/strength-training-while-losing-weight/">strength training in a deficit</a> - are exactly when the scale lies most fluently. If hunger genuinely surged with the new training, that is information about fuel, not weakness: feed the sessions, keep the deficit modest.</p>
<h2>The one caveat</h2>
<p>Rapid weight gain over days with visible swelling in the ankles or legs is a different phenomenon entirely - fluid retention of that pattern is a chat-with-a-doctor matter, not a fitness-page matter. Ordinary first-week scale creep - a couple of pounds, no swelling, following new hard training - is physiology doing its setup work. The programme is working; the scale is just announcing it in the wrong language.</p>"""),

("workout-makes-me-sleepy-not-energised", "understand",
"Workouts make you sleepy instead of energised: the honest causes",
"Exercise is sold as energy; for many it delivers a nap request. The normal physiology, the fixable causes - under-fuelled sessions, timing, sleep debt - and when fatigue is a pattern worth a check.",
"""<p>The marketing says energised; the reality for plenty of people is a session followed by a two-hour couch negotiation. The first part is simply physiology: hard training shifts the body toward recovery mode - parasympathetic rebound after a big effort, blood redirected, repair beginning. A post-workout dip, especially after something genuinely hard or new, is normal and even a sign the session was real. But when every session flattens the whole day, the causes are usually findable and fixable.</p>
<h2>The fixable causes, most common first</h2>
<p><b>Under-fuelled sessions:</b> training fasted or under-eating through the day makes the post-session crash dramatic - a carbohydrate-plus-protein meal within a couple of hours of training is the standard repair (protein-first if appetite is the issue: <a href="/protein-when-appetite-is-gone/">the playbook</a>). <b>Sleep debt:</b> training on five hours feels like training on five hours; the session spends a resource the night never refilled. <b>The session outgrew the base:</b> new programmes and week-one enthusiasm write cheques the current fitness cannot cash - the honest dose is the one that leaves function for the rest of the day (<a href="/strength-training-for-beginners/">beginner doses exist</a> for exactly this reason). <b>Timing:</b> a maximal session at a natural circadian dip (mid-afternoon for many) stacks two sleepinesses; moving it earlier or gentler fixes the arithmetic. <b>Heat and dehydration</b> - the invisible session tax.</p>
<h2>When it is a pattern worth a check</h2>
<p>Fatigue that persists despite decent sleep and food, exhaustion that a rest day does not touch, or tiredness joined by other changes - mood, appetite, breathlessness on easy effort - is worth raising with a doctor rather than out-training. This page is general information, not diagnosis; persistent whole-life fatigue has medical causes that exercise pages cannot rule out. And for the training-side version - weeks of heavy legs and flat sessions from doing too much - that is the overtraining end of the continuum, and the planned fix is <a href="/deload-weeks-explained/">the deload week</a>.</p>
<h2>The honest reframe</h2>
<p>A training session that buys a good night's sleep is not a failure - sleep is where the adaptations happen (<a href="/benefits-of-sleeping-well/">the sleep guide</a>). The afternoon slump after a morning session, once fuelled and hydrated, usually fades within weeks as fitness grows - the same compounding that makes hills quieter, covered in <a href="/how-long-to-see-gym-results/">the results timeline</a>.</p>"""),

("cracking-joints-during-exercise", "understand",
"Cracking and popping joints during exercise: when it is fine",
"Gas bubbles, tendons gliding, and the ordinary sounds of a working body - plus the short list of sounds that come with a check-up.",
"""<p>Squats announce themselves in the knees, press-ups in the shoulders, and every rep of deadlifts has a soundtrack in some bodies. The reassurance first: painless cracking, popping and clicking during exercise is overwhelmingly normal, and it is not the sound of joints wearing out. The usual sources are mundane - gas bubbles forming or collapsing in the joint fluid (the classic knuckle-crack mechanism), tendons sliding over bony ridges as joints move through their arc, and ligaments settling after a position change. Bodies creak the way floorboards do: more with age, mostly harmlessly.</p>
<h2>The sounds that are fine</h2>
<p>Painless noises that have been there for years, appear once per movement cycle, and come with full, smooth movement: file under body sounds. Noisy joints without pain do not predict future arthritis in the research, and they are not a reason to stop training - the stronger the muscles around a joint, the better that joint's long-term odds, which makes skipping training the worse answer to a harmless pop. The squat-depth and form questions that sometimes ride along with knee noise are covered in <a href="/squat-form-beginners/">the squat guide</a>.</p>
<h2>The check-up list</h2>
<p>Sounds are information when they arrive with company. Pain alongside the noise - especially sharp pain at the same moment as a pop - is a stop-and-get-it-looked-at. Swelling, locking (the joint genuinely catching or refusing to straighten), giving way, or a noise that appears suddenly during a specific incident (a twist, a misstep) each earn a professional opinion soon rather than eventually. Noisy joints with warmth or after an injury - same. None of the fine noises qualify; the line is pain, swelling, or function, not sound.</p>
<h2>Training noisy joints</h2>
<p>Warm up properly - creaky-first-thing and smooth-by-rep-three is the classic pattern; full range through comfortable arcs; and build the muscles around the noisy joint rather than guarding it forever. The reassurance logic is the same as the other great desensitisers on this desk: <a href="/shaking-during-plank-or-lunges/">the plank shake</a> and <a href="/sore-two-days-after-workout/">the two-day sore</a> - most training-time sensations are the sound of work, and the body's actual alarm system is far more specific than the internet's.</p>"""),

("hungry-all-day-after-workout", "understand",
"Ravenous the day after a workout: the appetite aftermath",
"Hard sessions can turn appetite up a day later - which is physiology working, not willpower failing. Why it happens a day after, how to feed it without undoing the session.",
"""<p>The session was Tuesday; the hunger arrived Wednesday and brought friends. The day-after appetite surge is a well-known training phenomenon: hard or new exercise raises appetite hormones on a delay, and the body's bookkeeping runs on a lag - the request arrives roughly a day after the withdrawal. For anyone training inside a weight-loss plan, this is the moment the plan is actually tested, and the honest news is that the hunger is legitimate: the body is asking for repair material, and answering it well is part of training, not a betrayal of it.</p>
<h2>Feeding it without erasing the session</h2>
<p>The difference between refuelling and undoing is structure. <b>Protein first</b> at the meals after the big session - the repair request is mostly for protein anyway (<a href="/how-much-protein-do-you-need/">the daily target</a> covers the arithmetic). <b>Fibre and volume</b> - potatoes, vegetables, fruit, soups - answer the "more" request at low calorie cost. <b>Do not skip meals to punish the hunger:</b> the restriction-then-rampage cycle costs more than the meals ever would; a solid breakfast after a heavy training day is the anti-rampage. And the snacks that arrive at 9 pm get planned rather than fought - yoghurt, fruit, a shake: the same gap-filler logic as <a href="/protein-when-appetite-is-gone/">the appetite playbook</a>, pointed at the day after instead.</p>
<h2>Why it matters more on medication-assisted loss</h2>
<p>For readers on appetite-suppressing treatment, the day-after surge can feel like the medication "stopped working" - it usually has not; the training request arrived and the treatment is quieter about it. The answer is the same structure with a lower noise floor: protein-first meals, planned evening snacks, and if hunger genuinely breaks through repeatedly on training days, that is a prescriber conversation, not a willpower project - the plan in <a href="/muscle-on-glp1-weight-loss-drugs/">the muscle guide</a> assumes you are eating enough to protect muscle, not less.</p>
<h2>When hunger is the whole story</h2>
<p>A ravenous day after a genuinely hard session is bookkeeping. Ravenous <i>every</i> day usually means the sessions are few and the walking is low - everyday movement, the kind in <a href="/30-day-walking-plan/">the walking plan</a>, is what steadies appetite between training days - or that sleep is short, which raises hunger hormones all by itself (<a href="/benefits-of-sleeping-well/">the sleep guide</a>). Feed the training honestly, structure the day around protein and fibre, and the day-after appetite becomes what it should be: the sound of the session being converted into something.</p>"""),
]
