#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Batch 15: nutrition myths and evidence articles.

Tuples: (slug, kind, title, dek, body)
Sources in FIT_SOURCES_15, wired via the build hook.
"""

FIT_MORE_15 = [

("detox-diets-what-evidence-says", "Understand", "Detox diets: what the evidence actually says",
"Juice cleanses, tea toxes and elimination protocols decoded \u2014 what detox marketing claims, what your liver already does, and the honest verdict.",
"""<p>The detox industry sells a story with three acts: your body accumulates toxins, a product or protocol flushes them, and you emerge renewed. It is a multi-billion-dollar narrative with one persistent problem &mdash; none of its three acts survives contact with physiology. Here is the honest audit.</p>
<h2>What "toxins" are we talking about?</h2>
<p>Ask any detox brand which specific compounds their protocol removes, at what concentration, measured how &mdash; the question ends the conversation, because the answer does not exist in published research. The word "toxin" in marketing is deliberately unspecified: not a named chemical with a named removal mechanism, but a feeling of uncleanliness that the product promises to resolve. Actual toxicology deals with specific substances at specific doses, and for the substances that genuinely threaten you &mdash; heavy metals, say &mdash; treatment is chelation therapy in a hospital, not a juice aisle. Your body meanwhile runs a genuinely impressive detoxification system: the liver transforms waste products into excretable forms, the kidneys filter continuously, the lungs and gut handle the rest. The <a href="/fitness/what-water-does-to-your-body/">water guide</a> covers the kidneys' side; none of it requires a supplement.</p>
<h2>What the trials actually find</h2>
<p>Systematic reviews of commercial detox diets have repeatedly concluded the evidence base is absent &mdash; not negative, absent: almost no rigorous trials, and the few that exist do not test the marketed claims. What trials do consistently find is why people report feeling better during cleanses: they are low-calorie, low-alcohol, low-ultra-processed-food protocols that come with sleep advice and structure. In other words, a week of eating vegetables and not drinking reads as magical if the comparison is an ordinary week. The weight lost is water, glycogen and gut contents &mdash; returning within days of normal eating, which is the pattern the <a href="/fitness/how-to-lose-belly-fat-honestly/">honest fat-loss guide</a> documents for every crash protocol.</p>
<h2>The honest verdict, including the nuance</h2>
<p>Detox products do not detoxify. But could the underlying behaviour &mdash; more whole plants, less alcohol and ultra-processed food &mdash; help? Obviously yes, and that is the twist worth keeping: the habit is sound, the story and the price tag are not. Everything the cleanse promises, you can run permanently and free: vegetables, water, fibre, sleep. One genuine caution on the other side: aggressive cleanses carry real risks &mdash; electrolyte disturbance from laxative teas (the stimulant kind are the worst offenders), muscle loss from severe restriction, and rebound bingeing after the protocol ends. And the marketing pattern itself &mdash; invented problems with proprietary solutions &mdash; is the same one the <a href="/fitness/supplements-waste-of-money/">supplements audit</a> finds across the industry.</p>
<p>The honest summary: your liver is not behind on its work and cannot be upgraded by a product. Detox diets are an expensive week of eating well dressed in physiology that does not exist &mdash; keep the vegetables, skip the story, and spend nothing.</p>"""),

("is-breakfast-really-important-explained", "Understand", "Is breakfast really the most important meal? What evidence says",
"The slogan's marketing origin, what breakfast trials actually show, who genuinely benefits, and who does fine without it.",
"""<p>"Breakfast is the most important meal of the day" is quoted like scripture and sourced like advertising &mdash; because it largely was advertising. The honest question is narrower and more interesting: what does skipping or eating breakfast actually change?</p>
<h2>Where the slogan came from</h2>
<p>The phrase traces to nineteenth-century health reformers and, decisively, to early twentieth-century cereal marketing campaigns &mdash; it entered the culture as a slogan with commercial backing, not as a research finding. Mid-century observational studies then appeared to support it: breakfast eaters were leaner and healthier. But observational data carries a confound the studies could not remove &mdash; people who eat breakfast reliably also tend to sleep regularly, smoke less and hold steadier routines; the meal was largely tagging the lifestyle. When randomised trials finally tested the advice directly, the effect mostly evaporated: the large 2019 meta-analysis of breakfast trials found no consistent metabolism or weight advantage to eating breakfast, and no reliable penalty for skipping it.</p>
<h2>Who genuinely benefits</h2>
<p>The evidence-free slogan still points at three real cases. <b>Some athletes and labourers</b> perform better fuelled &mdash; morning training quality improves for many with carbohydrates on board, as the <a href="/fitness/what-to-eat-before-a-workout/">pre-workout guide</a> sets out. <b>Some people with blood-sugar conditions</b> need medically advised meal patterns &mdash; individualised, not slogan-shaped. And <b>people who overeat later</b> when they skip: if skipping breakfast reliably produces a 3pm vending-machine spiral, breakfast is a useful lever for that person &mdash; not because the meal is magic but because the pattern is. Children and adolescents are the fourth case with genuinely more supportive evidence, where regular breakfast associates with better attention and school performance.</p>
<h2>And who does fine without it</h2>
<p>Skipping breakfast is, structurally, intermittent fasting &mdash; the same window-shifting the <a href="/fitness/intermittent-fasting-explained/">fasting explainer</a> covers neutrally. The trials find no metabolic harm in healthy adults who skip it and eat sensibly later; many simply prefer two good meals to three ordinary ones. The metabolism-fear version &mdash; "skipping breakfast slows your metabolism" &mdash; has no trial support at ordinary skipping durations; resting metabolic rate does not crater because you ate at 11am instead of 7am. What matters across every pattern, as the <a href="/fitness/metabolism-explained/">metabolism guide</a> shows, is total intake, protein adequacy and consistency &mdash; not the clock position of meal one.</p>
<p>The honest summary: breakfast is not a metabolic switch; it is a meal. Eat it if you are hungry, performing better with it, or it protects your afternoon &mdash; skip it without guilt if you are not. The only breakfast crime is believing any version of the slogan strongly enough to eat foods you would not otherwise touch, at a time of day you were not hungry, because a cereal box from 1944 told you to.</p>"""),

("artificial-sweeteners-what-evidence-says", "Understand", "Artificial sweeteners: what the evidence actually says",
"Aspartame, sucralose, stevia decoded \u2014 the cancer headlines, the WHO position, the gut and appetite questions, and the honest bottom line.",
"""<p>Few ingredients generate headlines like artificial sweeteners: cancer scares, metabolism claims, gut-microbiome studies, each seemingly reversing the last. The evidence is messier than either the panic or the marketing &mdash; but messier is not the same as unknowable.</p>
<h2>The cancer question, settled carefully</h2>
<p>The recurring scare concerns aspartame, and the authoritative read is specific: when the WHO's cancer-research arm classified aspartame as "possibly carcinogenic" in 2023, it meant the <em>strength of evidence was limited</em> &mdash; the same category as aloe vera extract and pickled vegetables &mdash; not that a diet soda causes cancer. Crucially, the companion risk assessment kept the established <b>acceptable daily intake</b> unchanged: an adult would need roughly a dozen-plus cans of diet soda daily, every day, to exceed it. Regulatory bodies across tier-1 markets reviewed the same data and changed no advice. "Possibly carcinogenic" is a statement about research gaps, not a hazard verdict, and the headlines routinely drop that distinction.</p>
<h2>The real open questions</h2>
<p>Two live debates are more interesting than the cancer cycle. <b>Appetite and weight</b>: sweet taste without calories could, in theory, dysregulate appetite &mdash; trial evidence is mixed; short-term trials show no compensation overeating, while the WHO's 2023 guidance advised against using non-sugar sweeteners for <em>long-term weight control</em>, citing observational signals that habitual users are not leaner (confounded, but not reassuring either). The honest reading: sweeteners neither meaningfully cause nor cure weight gain &mdash; total intake governs, as the <a href="/fitness/metabolism-explained/">metabolism guide</a> grounds. <b>The microbiome</b>: small studies show some sweeteners (saccharin, sucralose) shift gut bacteria and can alter glucose responses in some people &mdash; real signals, tiny samples, no established health consequence yet. This is genuinely unsettled science, and anyone selling certainty in either direction is selling something.</p>
<h2>The honest bottom line</h2>
<p>At ordinary consumption, approved sweeteners are among the most heavily studied food additives in history, with no consistent evidence of harm at realistic doses &mdash; the <a href="/fitness/supplements-waste-of-money/">supplements audit</a> applies the same evidence hierarchy to the other end of the nutrition aisle. But "harmless at current evidence" is not the same as "health food": the better move for most people is not maximising sweetener intake but reducing the sweetness expectation itself &mdash; palates adapt downward in weeks. For the specific job &mdash; replacing sugar-sweetened drinks while the habit shifts &mdash; they are a legitimate tool with a genuine harm-reduction case, because the comparator they replace is the one ingredient with unambiguous, dose-dependent metabolic evidence against it.</p>
<p>The honest summary: not poison, not health food &mdash; a well-studied compromise. Use them if they help you drink less sugar; do not treat them as free passes or fear them as toxins; and remember the dose question cuts both ways &mdash; a diet soda is unremarkable, a dozen a day is a research gap you are personally volunteering for.</p>"""),

("eating-late-at-night-myth-explained", "Understand", "Does eating late make you gain weight? The honest answer",
"The 8pm cutoff myth examined: what trials find about meal timing, the real mechanism behind late-night eating, and who should actually care about the clock.",
"""<p>"Do not eat after 8pm" is the most repeated rule in casual diet culture, and it has a strange evidence profile: mostly unsupported as stated, yet pointing at a real behavioural problem worth understanding. Here is the honest split.</p>
<h2>What the controlled trials find</h2>
<p>Feed people identical calories and identical food at different times of day under controlled conditions, and the weight outcomes are remarkably similar &mdash; the metabolism-penalty version of the rule (calories "turn to fat" at night) does not survive isocaloric trials. There are small circadian signals: insulin sensitivity is genuinely somewhat lower in the evening, and very late eating shifts some metabolic markers modestly. But modest markers are not the claimed effect &mdash; a calorie at 9pm is not a different calorie. The <a href="/fitness/metabolism-explained/">metabolism guide</a> covers why total energy balance dominates timing effects by an order of magnitude.</p>
<h2>So why does the advice persist? Because it accidentally works</h2>
<p>Observational data is unambiguous that heavy late eaters tend to weigh more &mdash; and the mechanism is behavioural, not metabolic. For most people, "eating late" is not dinner at 9; it is the <em>second</em> eating window: evening snacks, takeaways, screens and salt &mdash; calorie-dense food consumed mindlessly after the day's eating was supposedly finished. The 8pm rule works not by changing how calories behave but by closing the easiest over-consumption window of the day. It is a guardrail mislabelled as metabolism &mdash; and like the breakfast slogan, right more often than its reasoning. The same guardrail logic is why time-restricted eating shows modest benefits in trials: shrinking the window usually shrinks the intake, as the <a href="/fitness/intermittent-fasting-explained/">fasting explainer</a> sets out neutrally.</p>
<h2>Who should genuinely care about timing</h2>
<p>Three real cases. <b>Reflux sufferers</b>: lying down soon after a full meal reliably worsens symptoms &mdash; a two-to-three-hour gap is standard clinical advice, and it is mechanical, not dietary folklore. <b>Shift workers</b>: eating against the body clock disrupts glucose handling measurably &mdash; circadian misalignment is a documented occupational health issue, and meal anchoring helps. <b>Athletes eating for recovery</b>: post-evening-training protein is not just permitted but useful &mdash; the <a href="/fitness/protein-before-bed/">protein-before-bed guide</a> covers that specific, evidence-backed case where late eating is the plan.</p>
<p>The honest summary: the clock does not fatten you; the extra unplanned eating that tends to live after the clock does. If a cutoff time keeps the snack window shut, use it &mdash; as the behavioural tool it actually is. If your evenings are calm and your intake is sound, a 9pm dinner is metabolically unremarkable, and the rule was never about you.</p>"""),

("superfoods-marketing-vs-evidence", "Understand", "Superfoods: the marketing word versus the evidence",
"Acai, goji, kale and chia decoded \u2014 what 'superfood' legally means (nothing), what the real nutrient science says, and the cheap equivalents nobody brands.",
"""<p>"Superfood" appears on packaging, menus and health columns with the authority of a scientific classification. It is worth stating the foundational fact plainly: the word has no scientific definition, no regulatory meaning in most markets, and no agreed criteria. It is a marketing term &mdash; and understanding its mechanics immunises you against the entire category.</p>
<h2>How the label gets made</h2>
<p>The superfood pipeline runs the same cycle every time: a food is found to contain a nutrient class with promising cell-study or animal results &mdash; antioxidants, polyphenols, omega-3s &mdash; the gap between "active in a petri dish at isolated concentrations" and "meaningful in a human eating a normal amount" is quietly skipped, and the food is crowned. Acai, goji, noni, teff: each wave follows the script. Some jurisdictions have acted &mdash; the EU banned "superfood" on labels unless backed by an authorised specific health claim, and courts elsewhere have treated it as the advertising puffery it is. No nutrition scientist uses the term in papers; check any review and the vocabulary is "nutrient-dense," which means something entirely different and far more boring.</p>
<h2>The honest science underneath</h2>
<p>Strip the branding and the underlying advice is sound &mdash; which is exactly why the marketing works. Dark leafy greens, berries, oily fish, legumes, nuts: these foods genuinely associate with better health outcomes, and the mechanism is pattern-level &mdash; fibre, micronutrient density, unsaturated fats and phytochemicals working across a whole diet, not one heroic ingredient. The evidence rewards the <em>pattern</em>; the marketing sells the single item at a markup. A berry mix's benefit does not require the specific exotic berry on the label, at the price on the label &mdash; local, frozen and ordinary versions carry comparable nutrient profiles, as the <a href="/fitness/what-fruit-does-to-your-body/">fruit guide</a> details, and the frozen-versus-fresh evidence in the <a href="/fitness/is-fresh-always-better-than-frozen-explained/">frozen-food explainer</a> makes the economics worse for the exotic version.</p>
<h2>The cheap equivalents nobody brands</h2>
<p>The category's dirty secret: the "super" nutrients are commodity nutrients. Kale's headline profile is shared with ordinary cabbage and spinach at a fraction of the price. Chia's omega-3 story sits in flaxseed and walnuts. Quinoa's protein-and-mineral case is matched by lentils with more fibre. The honest shopping rule from the <a href="/fitness/supplements-waste-of-money/">supplements audit</a> applies verbatim: pay for nutrients, not narratives &mdash; and the cheapest nutrient density in most markets is frozen vegetables, tinned legumes, eggs, oats and whatever leafy green is in season.</p>
<p>The honest summary: no food is super; some foods are dense, and patterns beat ingredients. Eat the boring list &mdash; plants mostly, variety often, processed rarely &mdash; and let the superfood aisle keep its markup. The only genuinely super thing about the category is how effectively a meaningless word convinced a market to pay more for vegetables.</p>"""),

("is-fresh-always-better-than-frozen-explained", "Fuel", "Is fresh always better than frozen? The honest evidence",
"The fresh-versus-frozen comparison run properly: nutrient science, the timing problem nobody mentions, and when each actually wins.",
"""<p>Fresh versus frozen carries a settled cultural verdict &mdash; fresh wins &mdash; and an evidence profile that keeps contradicting it. The comparison done properly is more interesting: in the categories where it matters, frozen frequently ties or wins, for one unglamorous reason &mdash; time.</p>
<h2>The nutrient science</h2>
<p>Vegetables begin losing nutrients the moment they are harvested &mdash; vitamin C and some B vitamins degrade steadily with time, light and warmth. Commercial freezing happens within hours of harvest: produce is picked ripe, blanched briefly (which costs some water-soluble vitamins) and flash-frozen, locking what is there. "Fresh" supermarket produce, by contrast, may have spent days in transit and more on the shelf, degrading gently the whole way. Analyses comparing the two consistently find small differences in both directions depending on the nutrient and the vegetable &mdash; frozen peas often beat week-old "fresh" peas outright; fresh-from-the-market beats frozen for texture-sensitive vitamins. The honest verdict from the literature: nutritionally, they are close enough that the differences are dwarfed by the difference between eating vegetables and not eating them.</p>
<h2>Where each genuinely wins</h2>
<p><b>Frozen wins</b> on cost stability, waste (portion what you use; the rest waits), availability out of season, and nutrient retention for anything that would otherwise travel far &mdash; which in most markets is most things most of the year. <b>Fresh wins</b> on texture (freezing ruptures cell walls &mdash; salads and anything you want crisp stay fresh), on genuinely local and seasonal produce (picked yesterday beats frozen anything), and on culinary range. The practical split is almost food-type-specific: frozen for peas, corn, spinach, berries and cooking bases; fresh for salads, roasting vegetables and anything within a day or two of a good market.</p>
<h2>The behavioural point that decides everything</h2>
<p>The nutrition literature's punchline is behavioural, not biochemical: frozen vegetables are eaten in measurably larger quantities by households that keep them, because they remove the spoilage deadline that turns good intentions into compost. For the practical goal &mdash; more vegetables, more often, at lower cost &mdash; the freezer is not the compromise; it is infrastructure. The same logic runs through the whole honest-eating stack: the <a href="/fitness/what-fruit-does-to-your-body/">fruit guide</a> makes the case for volume and variety over prestige varieties, and the protein-shelf planning in the <a href="/fitness/how-much-protein-do-you-need/">protein guide</a> treats frozen fish and chicken as first-class options for exactly this reason.</p>
<p>The honest summary: fresh is a quality ceiling; frozen is a reliability floor &mdash; and reliability feeds people. Buy fresh when it is local, seasonal and imminent; buy frozen for everything else and eat twice as many vegetables without thinking about it. The fresh-versus-frozen debate is, in the end, a luxury argument &mdash; the real divide is between the vegetables that get eaten and the ones that get binned.</p>"""),

]

FIT_SOURCES_15 = {
    "detox-diets-what-evidence-says": [
        ("PubMed \u2014 detox diets systematic review (Klein & Kiat, 2015)", "https://pubmed.ncbi.nlm.nih.gov/25522674/"),
        ("Harvard Health Publishing \u2014 the dubious practice of detox", "https://www.health.harvard.edu/")],
    "is-breakfast-really-important-explained": [
        ("PubMed \u2014 breakfast and body weight meta-analysis (Sievert et al., 2019)", "https://pubmed.ncbi.nlm.nih.gov/30722446/"),
        ("Harvard Health Publishing \u2014 breakfast research", "https://www.health.harvard.edu/")],
    "artificial-sweeteners-what-evidence-says": [
        ("WHO \u2014 aspartame hazard classification and risk assessment (2023)", "https://www.who.int/news/item/14-07-2023-aspartame-hazard-and-risk-assessments-released"),
        ("WHO \u2014 non-sugar sweeteners guideline (2023)", "https://www.who.int/publications/i/item/9789240073616")],
    "eating-late-at-night-myth-explained": [
        ("PubMed \u2014 meal timing and body weight trials", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("Harvard Health Publishing \u2014 late eating and reflux", "https://www.health.harvard.edu/")],
    "superfoods-marketing-vs-evidence": [
        ("PubMed \u2014 dietary patterns and health outcomes", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("WHO \u2014 healthy diet fact sheet", "https://www.who.int/news-room/fact-sheets/detail/healthy-diet")],
    "is-fresh-always-better-than-frozen-explained": [
        ("PubMed \u2014 nutrient retention in fresh versus frozen produce", "https://pubmed.ncbi.nlm.nih.gov/"),
        ("Harvard Health Publishing \u2014 frozen vegetables and nutrition", "https://www.health.harvard.edu/")],
}
