# -*- coding: utf-8 -*-
"""BRYME Fitness growth batch #13 (2026-09-26): six evergreen guides.

Tuple shape matches the more2..more12 modules:
    (slug, kind, title, dek, body)
Every page also carries the desk's two base sources (WHO + CDC) applied by
the build. General information only; anything symptomatic points to a
professional.
"""

FIT_MORE_13 = [
    (
        "running-form-explained",
        "train",
        "Running form, explained: the four fixes that actually matter",
        "Cadence, footstrike, posture and the overstriding trap: the running-form changes the evidence supports, and the ones that are fashion.",
        """<p>Running form advice is a swamp of contradictions &mdash; forefoot! midfoot! land however feels natural! The research picture is calmer than the debates: most runners do not need a new style, they need four specific fixes. Change them and efficiency and injury risk both improve; ignore the rest of the noise.</p>
<h2>Fix one: stop overstriding</h2>
<p>The most common and most costly error: the foot lands well <b>ahead of the body</b>, straight-legged, acting as a brake every step. The fix is not about the foot &mdash; it is about landing with the foot <b>under the hips</b>, which happens automatically when you lean slightly from the ankles (not the waist) and let the legs cycle beneath you. Overstriding is why many heel-strikers get hurt and many midfoot-strikers don't: the strike pattern gets the blame for what the landing position actually causes.</p>
<h2>Fix two: cadence over stride length</h2>
<p>Speed is cadence &times; stride length, and the trainable, safer lever is <b>cadence</b> &mdash; steps per minute. Most recreational runners sit well below the 170&ndash;180 range that efficient runners cluster around; a modest increase (five to ten percent is enough &mdash; the "180 or you're wrong" version is fashion) shortens each stride, pulls the landing under the hips and reduces the braking and impact spikes per step. Check yours once: count steps for 30 seconds on an easy run and double it. The <a href="/fitness/heart-rate-zones-explained/">zones guide</a> pairs with this &mdash; cadence work happens at easy paces first.</p>
<h2>Fixes three and four: posture and relaxation</h2>
<p><b>Posture:</b> tall through the spine, eyes on the horizon, hips under the shoulders &mdash; the slouched, hips-behind runner shortens the stride and loads the lower back. <b>Relaxation:</b> shoulders down, hands loose, jaw unclenched; tension you carry in the upper body is energy not going forward. Both are fatigue-sensitive &mdash; form degrades late in runs, which is when injuries cluster, so occasional form check-ins late in a session are a genuine injury-prevention tool.</p>
<h2>What the evidence says not to bother with</h2>
<p>The honest counterweight to all form advice: studies of strike-pattern conversion &mdash; forcing habitual heel-strikers onto the forefoot &mdash; generally find <b>no injury reduction</b> and an economy cost during adaptation, plus new injury risk in calves and Achilles from the loading change. Shoes, surfaces and <a href="/fitness/how-to-choose-running-shoes/">shoe choice</a> matter less than load management: the <a href="/fitness/beginner-running-plan/">beginner plan</a> exists because the biggest injury predictor is doing too much too soon, not landing wrong. The summary that survives the research: land under the body, nudge the cadence up, stay tall and loose, progress mileage slowly &mdash; and treat anyone selling a total style overhaul as selling a style.</p>""",
    ),
    (
        "how-to-measure-fitness-progress-explained",
        "plans",
        "How to measure fitness progress: beyond the bathroom scale",
        "The scale is one noisy instrument among many. Strength benchmarks, performance tests, measurements and photos: the honest dashboard.",
        """<p>The scale is the most available and least reliable single measure of progress &mdash; it cannot distinguish muscle from water, and it moves daily for reasons that have nothing to do with fitness. The solution is not a better scale; it is a dashboard, where several noisy instruments average into a signal.</p>
<h2>Performance: the numbers that cannot lie</h2>
<p>What the body <b>does</b> is the most honest evidence of what it can do. Pick three or four benchmarks and retest monthly: a <b>strength pair</b> &mdash; the same lift at the same reps and weight, or your working weights trending up, the progressive-overload record from the <a href="/fitness/how-progressive-overload-works/">overload guide</a> in its purest form; a <b>cardio marker</b> &mdash; the same route at the same heart rate getting faster, or the same pace at a lower heart rate, the drift test that <a href="/fitness/zone-2-cardio-explained/">zone 2 training</a> lives on; and a <b>capacity marker</b> &mdash; max push-ups, a plank time, the pull-up count from the <a href="/fitness/pull-up-progression-explained/">progression guide</a>. Performance tests need consistency more than intensity: same time of day, same warm-up, same course.</p>
<h2>Body measures and photos</h2>
<p>Where composition matters, the scale alone is the worst instrument available. <b>Tape measurements</b> &mdash; waist at the navel, hips, chest, arms &mdash; taken monthly under the same conditions track recomposition the scale hides: waist down while weight holds is fat loss plus muscle gain, the outcome everyone wants and the scale refuses to show. <b>Photos</b> every four to six weeks, same light and pose, catch what daily mirror-checking cannot: changes are invisible day-to-day and undeniable month-to-month. Body-fat devices vary in accuracy &mdash; treat trends, not numbers, as the signal.</p>
<h2>The quiet metrics</h2>
<p>Three markers with no equipment: <b>recovery</b> &mdash; resting heart rate on waking, which drifts down as fitness builds and spikes with overreach or illness; <b>sleep quality</b> and daily energy, both of which improve with well-dosed training; and <b>how the same workout feels</b> &mdash; perceived effort on a familiar session is a legitimate, research-backed metric, not a vibe. If the familiar run feels easier at the same pace, that is progress, whatever the scale says.</p>
<h2>Building the dashboard</h2>
<p>The workable version: performance benchmarks monthly, measurements monthly, photos every four to six weeks, resting heart rate daily if convenient, scale weekly at most &mdash; same morning, same conditions, and averaged over weeks rather than read daily. Then the interpretation rule that makes it all bearable: <b>trust trends over months, never single data points</b>. Progress in fitness is real, gradual and noisy; the dashboard's job is not to hand you a verdict each day but to make the direction undeniable each quarter &mdash; which, for a process measured in years, is exactly often enough.</p>""",
    ),
    (
        "pre-workout-supplements-explained",
        "understand",
        "Pre-workout supplements: what works, what is theatre",
        "Caffeine, citrulline, creatine timing and the proprietary-blend problem: an honest audit of the pre-workout tub.",
        """<p>The pre-workout tub is fitness marketing's loudest product: neon powder, aggressive branding, and an ingredient list that reads like a chemistry exam. Audited honestly, most tubs contain one or two proven ingredients at effective doses, several at fairy-dusting levels, and a fair amount of sensation engineered to feel like efficacy.</p>
<h2>What actually has the evidence</h2>
<p><b>Caffeine</b> is the whole show: performance benefits across endurance and strength are among the most replicated in sports science, at roughly 3&ndash;6mg per kg of body weight, taken 30&ndash;60 minutes before. A typical scoop delivers 150&ndash;300mg &mdash; a large coffee to a strong one. That means the honest version of pre-workout is often a coffee plus change. The <a href="/fitness/caffeine-side-effects/">caffeine guide</a> covers the individual variation and the sleep math that caps the dose. <b>Citrulline malate</b> (6&ndash;8g) has genuine support for high-rep endurance and reduced soreness; <b>creatine</b> works &mdash; but as a daily supplement, not a pre-workout one, and the <a href="/fitness/creatine-explained/">creatine guide</a> covers it properly. <b>Beta-alanine</b> helps efforts of one to four minutes specifically, with the famous tingles being a harmless side effect doing a lot of marketing work.</p>
<h2>The theatre layer</h2>
<p>Several ingredients exist mainly to be felt rather than to perform: high-dose niacin flushes, tingle-inducing compounds, stimulants that raise heart rate so the product announces itself. Feeling altered is not evidence of training benefit &mdash; it is evidence of a dose of something. The structural problem is the <b>proprietary blend</b>: a total weight for a mix without per-ingredient amounts, which makes under-dosing invisible and is why independent testing of pre-workouts routinely finds label drift. The <a href="/fitness/supplements-waste-of-money/">supplements audit</a> applies its general rule here: if the label won't tell you the dose, assume there isn't one.</p>
<h2>The honest verdict</h2>
<p>For most trainees the effective stack is boring and cheap: caffeine from coffee or tablets, dosed sensibly and never near bedtime; creatine monohydrate daily if you want it at all; food as fuel, per the <a href="/fitness/what-to-eat-before-a-workout/">pre-workout eating guide</a>, which matters more than any powder. If a tub still appeals, read it as a label audit: named doses for citrulline and caffeine, no proprietary blends, and a stimulant level you can sleep over. What no pre-workout fixes is the thing that actually limits sessions &mdash; under-recovery and under-fuelling &mdash; which is why the best-performing pre-workout in every study remains the unmarketable one: sleep, breakfast and a plan.</p>""",
    ),
    (
        "heart-rate-variability-explained",
        "understand",
        "Heart-rate variability, explained: what your HRV number actually means",
        "The metric every tracker now sells: what HRV measures, why higher isn't simply better, and how to use it without letting it run your training.",
        """<p>Heart-rate variability arrived in consumer trackers and immediately became the most quoted and least understood number in fitness. It measures something real and useful &mdash; and almost everything popularly said about it needs a caveat attached.</p>
<h2>What HRV actually is</h2>
<p>Even at rest, your heart does not beat like a metronome &mdash; the gaps between beats vary by milliseconds, and that variation is <b>HRV</b>. The variation is driven by the tug-of-war between the sympathetic (fight-or-flight) and parasympathetic (rest-and-digest) branches of the autonomic nervous system. Broadly, higher variability reflects a nervous system with room to respond; suppressed variability reflects accumulated stress &mdash; training load, illness brewing, poor sleep, life. The measurement caveat comes first: a single reading is noisy, which is why the only meaningful use is a <b>personal rolling baseline</b>, usually from morning readings over weeks, not a number compared to anyone else's.</p>
<h2>What the evidence supports</h2>
<p>The strongest applied use is <b>HRV-guided training</b>: studies across endurance and team sports find that adjusting intensity to HRV signals &mdash; hard sessions when variability is at or above baseline, easy when suppressed &mdash; can match or beat fixed plans for fitness gains with less strain. As a <b>illness and overreaching early-warning</b>, sustained multi-day suppression reliably precedes what you feel coming. Those are real, modest, useful effects. What the evidence does not support: HRV as a general health oracle, a daily score whose every wiggle means something, or cross-person comparisons &mdash; baseline HRV varies enormously with age, genetics and measurement conditions, which is why "my HRV is 45" without a personal trend means nothing at all.</p>
<h2>Using it without being used by it</h2>
<p>The workable protocol: measure under identical conditions (waking, before anything), build four-plus weeks of baseline, and act only on <b>sustained deviations</b> &mdash; two or three days well below your norm, alongside how you actually feel. One low reading after a late night is information about the late night. And the honest hierarchy: HRV is a supporting actor behind the metrics that already work &mdash; resting heart rate trends, sleep, and perceived readiness, all covered from the recovery side in the <a href="/fitness/rest-days-why-muscles-grow/">rest-days guide</a>. The <a href="/fitness/fitness-trackers-worth-it/">trackers verdict</a> applies the desk's general rule: a tracker that turns one noisy signal into a daily verdict is selling certainty it does not have; used as a trend instrument with a personal baseline, HRV earns its place on the dashboard from the <a href="/fitness/how-to-measure-fitness-progress-explained/">progress-measurement guide</a>.</p>""",
    ),
    (
        "fasted-cardio-explained",
        "understand",
        "Fasted cardio: does training on empty actually burn more fat?",
        "The mechanism, the trials, and the verdict: why fasted cardio burns more fat during the session and no more over the month.",
        """<p>Fasted cardio &mdash; training before eating, typically before breakfast &mdash; persists as fitness gospel with a real mechanism behind it and a research record that refuses to cooperate. Both halves deserve the honest telling.</p>
<h2>The mechanism is real</h2>
<p>After an overnight fast, glycogen stores are lowered and insulin is low, so the body shifts fuel mix toward <b>fat oxidation</b> during exercise. Measured during the session, fasted training does burn proportionally more fat. That much of the claim is physiology, not myth &mdash; and it is where the argument usually stops, which is exactly where it goes wrong.</p>
<h2>The trials say: over time, no difference</h2>
<p>Fat loss is decided not by the fuel mix during one session but by the <b>total energy balance across weeks</b>. Controlled trials comparing fasted versus fed cardio &mdash; matched for calories burned &mdash; consistently find <b>no difference in fat loss</b> over weeks of training. The body compensates: what is oxidised during the fasted session is replenished from the day's intake, and the ledger balances by the month. Secondary effects mostly favour fed training: performance on intense sessions is worse fasted, which reduces the total work done; some people eat more afterwards; and the <a href="/fitness/intermittent-fasting-explained/">fasting guide</a> makes the same point from the diet side &mdash; timing arrangements succeed or fail on adherence and total intake, never on metabolic magic.</p>
<h2>When it is fine, and when it is not</h2>
<p>Fasted <b>easy</b> cardio &mdash; a walk or an easy zone-2 run before breakfast &mdash; is harmless for most people and fits some schedules beautifully; if it is the version of training that actually happens, it is the right version, full stop. The caveats are specific: hard intervals and long sessions performed fasted suffer in quality; anyone prone to dizziness or light-headedness should eat first; people with diabetes or blood-sugar conditions need medical guidance rather than blog logic; and for muscle preservation in a deficit, the protein and training priorities in the <a href="/fitness/strength-training-while-losing-weight/">cutting guide</a> matter far more than breakfast timing.</p>
<p>The honest verdict: fasted cardio burns more fat at 7am and the same amount of fat by August. Choose it for the schedule, not the science &mdash; and if you choose it for the science, the science is asking you to stop. The variables that actually move fat loss remain total intake, total activity, protein and patience: none of which care what your breakfast did that morning.</p>""",
    ),
    (
        "plant-based-protein-explained",
        "fuel",
        "Plant-based protein, explained: the honest guide to getting enough",
        "Protein density, the amino-acid question, combining myths and practical daily templates for vegetarian and vegan training diets.",
        """<p>The question every plant-based trainee gets &mdash; usually unsolicited &mdash; is where the protein comes from. The honest answer: everywhere, in sufficient quantity, with two genuine caveats that deserve better treatment than either the scare stories or the dismissals give them.</p>
<h2>The density caveat, honestly</h2>
<p>Plant proteins are real proteins; the difference is <b>density</b>. Animal sources deliver protein with minimal accompanying calories; plant sources bundle it with fibre, carbohydrate or fat. Getting 100g of protein from lentils alone is possible and a lot of lentils. The practical response is arithmetic, not anxiety: plant-based eaters target the same ranges as everyone &mdash; the <a href="/fitness/how-much-protein-do-you-need/">protein guide</a>'s numbers hold &mdash; but budget more deliberate protein <b>anchors</b> per meal: tofu and tempeh, seitan (the density champion), lentils and beans, edamame, soya milk, nuts and seeds, and &mdash; the plant-based athlete's best friend &mdash; protein powders, where pea-and-rice blends close any gap completely.</p>
<h2>The amino-acid question, defused</h2>
<p>Plant proteins are often "incomplete" &mdash; lower in one or more essential amino acids, typically leucine, the trigger for muscle-building. The old "protein combining" doctrine (rice and beans at every meal) is obsolete: eating a <b>variety</b> across the day covers the profile completely. The leucine point has one practical edge: plant meals sometimes sit below the threshold that maximally stimulates muscle synthesis, which is fixed by portioning protein toward 30&ndash;40g at training-adjacent meals &mdash; or by the soya content doing what soya does, since soya is the one plant protein with a near-complete profile on its own.</p>
<h2>A practical day, and the extras</h2>
<p>A worked template at roughly 120&ndash;140g: soya-milk oats with peanut butter and seeds; a tofu scramble; lentil or bean-based lunch with a grain; edamame or roasted chickpea snack; tempeh or seitan dinner with a side of quinoa; casein-or-pea shake if the day ran short. Two nutrients genuinely warrant attention on fully plant-based diets &mdash; not protein: <b>B12</b>, which requires supplementation because no plant source is reliable, and <b>creatine</b>, naturally absent from plants and cheap to supplement, the one place the <a href="/fitness/creatine-explained/">creatine evidence</a> intersects with diet. Iron and omega-3s reward planning but rarely require products.</p>
<p>The honest summary: a well-planned plant-based diet supports training at every level &mdash; the elite-athlete examples are too numerous to list and the position statements say so plainly. The planning is real but small: protein anchors at each meal, variety across the day, B12 covered, and the same training and recovery rules as everyone else. The protein question has been settled for decades; the interesting questions &mdash; how much, how often, alongside what &mdash; are the ones this guide and the <a href="/fitness/protein-timing-anabolic-window/">timing guide</a> actually argue about.</p>""",
    ),
]
