# BRYME Home & DIY — roadmap batch 6: Garden & outdoor (4, new "Outside" section) +
# Windows & doors (2) + Flooring (2) + Cleaning (1). Lighter YMYL batch; energy figures
# kept as EST-attributed ranges (aggregator numbers conflicted), warranty claims grounded
# in actual manufacturer warranty text (Mohawk/Pergo/Shaw), fire figures NFPA 2026.

HOME_ROADMAP_6 = [
("gutter-cleaning-damage", "guide",
"Gutter cleaning: why skipping it causes damage years later",
"Gutters are the roof's drainage system. Blocked, they quietly redirect water at the fascia, the wall and the foundations — the exact failures this desk keeps tracing back.",
"""<p>Gutters have one job: take the water off the roof and deliver it away from the house. When they block with leaves, moss and grit, the water doesn't stop falling — it just chooses worse places to land. Gutter neglect is the quiet kind of maintenance debt this desk keeps finding behind big bills: nothing fails for months, and then several things fail at once.</p>
<h2>What a blocked gutter actually does</h2>
<p><strong>To the roof edge:</strong> standing water in a gutter sits against the fascia board and the roof's lowest edge, rotting timber and working into the roof felt — the leak that appears on a bedroom ceiling often starts at the gutter line, not the ridge. <strong>To the walls:</strong> an overflowing gutter pours down the wall face, and the damp it produces is the textbook case of <a href="/home/condensation-vs-rising-vs-penetrating-damp/">penetrating damp — patches that grow with the rain</a>. <strong>To the ground:</strong> the worst of it. Water dumped at the base of the wall soaks the ground around the foundations, and in the UK — where much of the housing stock is older masonry — it feeds both damp courses and, in frost, the freeze-thaw that cracks renders and brickwork. The damage is always downstream and never looks like a gutter problem.</p>
<h2>The habit and the method</h2>
<p>Twice a year is the standard rhythm — late autumn after the leaves are down, and spring — plus a check after any serious storm. Clear by hand or with a plastic scoop into a bucket, working along the run; flush with a hose toward the downpipe; and confirm the water actually exits, because a cleared gutter with a blocked downpipe is still a full gutter. Ground-level safety rules apply: stable ladder, someone aware, never overreach — roofline and upper-storey work at height belongs to a professional, the same boundary as everything else on this desk. While you're up there: look for sagging runs (failed brackets), leaking joints (rubber seals perish — replaceable by hand) and moss growth in the channel itself.</p>
<h2>The signs from the ground</h2>
<p>You don't need a ladder to monitor gutters — the evidence shows itself: water pouring over the edges in rain that isn't torrential; plants growing in the gutter line; damp streaks down the wall below the joints; paint peeling on the fascia; and the downpipe gurgling or splitting. Each is a "this season, not next year" sign — and each is cheapest to answer the week you spot it, like everything else in the <a href="/home/seasonal-home-maintenance-checklist/">once-a-season checklist</a>.</p>
<h2>When it's a pro job</h2>
<p>Two storeys and up, conservatory roofs, gutter runs over extensions, and anything that needs a tower or roof access — a gutter-clearing service costs a fraction of one ceiling repair, and professionals carry the vacuum rigs and access gear that make it quick. The homeowner's territory is the ground-floor runs you can reach safely and the monitoring of everything else. The repair-vs-neglect arithmetic here is the same one behind <a href="/home/small-leak-ripple-effect/">the small-leak rule</a>: water always wins, the only variable is when you stop it.</p>
<p><em>Reviewed September 2026 · general information, not professional advice — work at height belongs to professionals.</em></p>"""),

("fence-shed-insurance", "guide",
"Fence and shed mistakes that quietly void insurance claims",
"Outbuildings and boundaries live in the small print — covered differently, capped lower, and the easiest claims to lose to a maintenance argument.",
"""<p>The shed, the fence and the garage are the part of the property people insure least and assume most about. They're usually covered — but under different rules than the house, with their own limits, and with the exclusions that bite exactly when a claim is made: rot, poor maintenance and storms at the edge of the policy's definitions. This page is the honest tour — not legal advice, and your policy document beats every generalisation here.</p>
<h2>How outbuildings are actually covered (US)</h2>
<p>Standard US home policies cover detached structures under "other structures" coverage — typically set at around ten percent of the dwelling limit by default. That default is the first surprise: a $400,000 dwelling carries roughly $40,000 for <em>everything</em> detached combined — the shed, the fence, the garage, the gazebo — which a serious outbuildings setup can exceed. Flood and earthquake are excluded entirely (separate policies), and business use of a shed usually needs an endorsement. If your outbuildings would cost real money to rebuild, the declarations page tells you your actual limit, and insurers will raise it.</p>
<h2>The UK conventions</h2>
<p>UK buildings policies typically include garages, sheds and garden walls within or alongside buildings cover, often with a per-item or per-outbuilding cap set in the schedule, and contents in a shed usually need explicit cover — garden tools and bikes are a favourite theft line item with low standard limits. The famous UK quirk: fences, gates and garden walls are commonly <em>excluded from storm damage</em> cover — they're the first thing to fall in a gale and the first thing insurers carve out. Check that line in your own policy before the autumn, not after it.</p>
<h2>The maintenance trap that voids claims</h2>
<p>The classic denial pattern — both countries: the loss isn't the storm, it's the <em>condition</em> the storm found. A shed that collapses because posts had rotted for years is a maintenance failure, not an insured event; a fence blown down whose posts were already loose gets reduced or refused on the same logic. Policies cover sudden damage, not accumulated neglect — exactly the <a href="/home/small-leak-ripple-effect/">gradual-versus-sudden line the leak guide explains</a>, wearing a timber costume. The practical shield is a photo record: date-stamped pictures of the shed roof, the fence posts, the garage door each spring prove condition <em>before</em> any event, and they cost nothing.</p>
<h2>The mistakes, collected</h2>
<p>Building without checking boundaries and planning rules first (a shed over the size limit can face enforcement — <a href="/home/building-regs-vs-planning-permission/">the approvals guide covers the UK split</a>; <a href="/home/us-home-permits/">the US permit guide covers thresholds</a>); storing value in a shed the policy doesn't know about; ignoring the shed roof for years and calling the collapse "storm damage"; power tools daisy-chained on an extension lead in a wooden box (<a href="/home/outlet-overloading-danger/">the socket-arithmetic applies in the garden too</a>); and never photographing anything until after the damage. The garden buildings get one spring check a year — roof, posts, security, photo — and that's the whole discipline.</p>
<p><em>Sources: US standard-policy other-structures mechanics (Coverage B conventions); UK policy conventions on outbuildings, shed contents and storm exclusions for boundary structures. Reviewed September 2026 · general information — policy documents vary; yours is the authority.</em></p>"""),

("outdoor-cooking-safety", "guide",
"Outdoor cooking: the mistakes behind most summer grill fires",
"NFPA's data is blunt: July is the peak month, gas does most of it, and failure to clean is the leading factor — all three are controllable.",
"""<p>Grilling feels like the safest cooking there is — outdoors, open air, no kitchen grease fire near the curtains. The US fire data disagrees, politely but firmly: NFPA's latest analysis puts home grilling fires at over ten thousand a year, with <strong>July the peak month</strong> (June, May and August following), <strong>gas grills involved in 76%</strong> of them, and <strong>failure to clean</strong> — grease and fat buildup — the single leading contributing factor at a fifth of all fires. Roughly a quarter of grill <em>structure</em> fires started on an exterior balcony or porch, right against the house.</p>
<h2>The mistakes, in data order</h2>
<p><strong>Not cleaning</strong>: the grease layer in the tray and down inside the grill body is the fuel; fires starting during the cook or right after are usually the tray igniting. Clean trays and grates regularly — the habit costs minutes. <strong>Placement</strong>: grills belong well away from the wall, railings, eaves and overhanging branches — never on a balcony or porch against the house, which is precisely where the structure fires start. <strong>Gas discipline</strong>: leaks and breaks caused six percent of gas grill structure fires and thirteen of outdoor ones — check the hose and connections each season with soapy water (bubbles mean gas, replace the part), and never turn a gas grill on with the lid closed. <strong>Leaving it attended</strong>: a lit grill is an open flame with a fuel supply; the "just stepping inside" fires are the ones that meet the fence.</p>
<h2>Charcoal's separate rulebook</h2>
<p>Charcoal carries about 13% of grilling fires, with its own failure mode: disposal. Coals stay hot for hours and ignite bins, decks and sheds overnight — the classic charcoal fire is the morning after. Coals go out fully, soaked and stirred, into a metal container, never a plastic bin or against the house. And lighter fluid never goes onto an already-lit fire — the flame travels up the stream faster than anyone's reflexes.</p>
<h2>The house rules worth adopting</h2>
<p>Grill at a distance: a metre-plus from anything combustible, on a stable surface, never under an awning. Keep a hose or bucket of sand within reach — water on a gas fire is the wrong tool; turn the gas off first. Keep kids and pets at arm's length of the cooking zone. And check the <a href="/home/test-alarms-monthly/">smoke alarms</a> near the kitchen door — the grill fire that reaches the house arrives as a house fire, and the <a href="/home/electrical-fire-warning-signs/">same early-response logic</a> applies: minutes matter. The UK adds one more: carbon monoxide — never take any burning fuel into a tent, gazebo or summerhouse with closed sides, <a href="/home/mistakes/co-alarm-wrong-place/">CO gives no warning of its own</a>.</p>
<p><em>Sources: NFPA grilling-fire analysis (latest: ~10,600 home grilling fires/yr; July peak; 76% gas; 20% failure-to-clean; ~25% of structure fires from balconies/porches). Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("inspection-checklist-gaps", "guide",
"The home inspection most owners skip — and what gets missed every year",
"You don't need a professional survey to catch the slow failures. You need one honest hour, four times a year, looking at the places you never look.",
"""<p>This desk already ships the <a href="/home/seasonal-home-maintenance-checklist/">once-a-season checklist product</a> — ten checks, progress saved in your browser. This page is the complement: the honest guide to <em>what gets missed</em>, the inspection angles no checklist quite captures, and the reasoning that makes you your own best inspector. The professional surveys — full structural, electrical condition reports, roof inspections — have their place, and the links below say where the line sits.</p>
<h2>The blind spots, by elevation</h2>
<p><strong>The loft/attic</strong> is the most-skipped room in any house, and it's the archive of everything the roof has been doing: daylight where it shouldn't be, water staining on rafters or the insulation matting down where a leak has run, wasp or rodent traffic, and insulation that's been moved by someone standing in the wrong place. One look per season, with a torch, takes ten minutes. <strong>The ground outside</strong> is the second archive: the ground should slope <em>away</em> from the walls; puddles that sit against the house after rain are writing next winter's damp ticket (<a href="/home/gutter-cleaning-damage/">gutters feed this story</a>). <strong>Behind and under</strong> — behind the washing machine (<a href="/home/small-leak-ripple-effect/">where slow leaks live</a>), under every sink, inside the meter cupboard, behind the fridge (<a href="/home/fridge-coils-twice-a-year/">where the coils live</a>). Water and heat damage announce themselves early in exactly these places, and never anywhere convenient.</p>
<h2>The senses, used properly</h2>
<p><strong>Smell</strong> is the most underrated inspection tool: mustiness means moisture somewhere you haven't found (<a href="/home/condensation-ventilation-that-works/">start with airflow</a>); the hot-plastic or fish smell means electrics (<a href="/home/electrical-fire-warning-signs/">stop and take it seriously</a>); gas smells mean out and call, immediately. <strong>Sound</strong>: the running-meter test (<a href="/home/small-leak-ripple-effect/">the EPA's two-hour method</a>), new rattles in the boiler cupboard, the toilet that refills when nobody used it. <strong>Touch</strong>: warm faceplates, cold patches on walls in heated rooms (<a href="/home/condensation-vs-rising-vs-penetrating-damp/">cold walls are where condensation lands</a>), and the door that's started to catch where it never did — houses move slowly, and skin notices before eyes do.</p>
<h2>What genuinely needs a professional</h2>
<p>The self-inspection has a boundary, and pretending otherwise is how people get hurt: the consumer unit and anything electrical beyond the visible (<a href="/home/part-p-explained/">UK electrics are regulated for a reason</a>); the roof slope and anything at height; gas appliances beyond the flame check (<a href="/home/uk-boiler-servicing/">the annual service exists</a>); structural movement beyond hairline; and drainage that backs up. The rhythm that works: your hour, four times a year, feeds the small fixes list — and the professionals' visits (boiler service, electrical check on its cycle, chimney sweep if you have one) sit on top of it.</p>
<h2>Make it a habit that survives</h2>
<p>Attach the walk to a date that already exists — the clocks changing, the boiler service, the first warm weekend — and take photos of everything you checked. The photo archive is the quiet superpower: when something <em>does</em> go wrong, dated pictures of the before-state win arguments with <a href="/home/fence-shed-insurance/">insurers</a> and buyers' surveyors alike. Ten checks are waiting in the <a href="/home/seasonal-home-maintenance-checklist/">checklist product</a>; the misses on this page are the eleventh through fifteenth.</p>
<p><em>Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("draught-proofing-mistakes", "guide",
"Draught-proofing mistakes that can leave you colder, damper — or no better off",
"Sealing a home is genuinely one of the cheapest energy upgrades there is — unless you seal the wrong things, or seal the house so tight it can't breathe.",
"""<p>Draught-proofing is the poster child of cheap energy fixes — brush strips, compression seals and a tube of sealant against heat that the Energy Saving Trust's published estimates put at meaningful money off a typical bill (figures vary by property and year — roughly in the £50-£125 annual band for a thorough job on windows and doors). Done well, it's the best hours-to-savings ratio in the house. Done badly, it either does nothing, or worse, seals in moisture and starves heaters of air. Here is where it goes wrong.</p>
<h2>Mistake one: sealing the ventilation that's there on purpose</h2>
<p>Some gaps are load-bearing for the house's health. <strong>Air bricks and underfloor vents</strong> keep the timber floor structure dry — blocking them trades a draught for <a href="/home/condensation-vs-rising-vs-penetrating-damp/">the damp diagnosis guide</a>. <strong>Trickle vents</strong> in modern window frames are the ventilation system of a sealed house — <a href="/home/condensation-ventilation-that-works/">the condensation guide explains what happens when homes stop exchanging air</a>. And the non-negotiable: <strong>vents serving fuel-burning appliances</strong> — boilers, gas fires, stoves — exist because combustion needs air and exhaust needs somewhere to go; blocking one is how you manufacture <a href="/home/mistakes/co-alarm-wrong-place/">a CO problem</a>. Gas Safe engineers flag sealed appliance vents on every visit, and they're right to.</p>
<h2>Mistake two: the chimney</h2>
<p>An open chimney can pull heat out of a room like an open window — and capping or blocking it without thought creates both of mistake one's problems: no airflow for the structure, and if anything is ever burned or the boiler's flue shares the stack, a safety failure. The workable middle: a chimney balloon or vented cap for disused flues, professionally fitted caps where any doubt exists, and a ventilation route deliberately kept.</p>
<h2>Mistake three: sealing the wrong gaps, leaving the real ones</h2>
<p>The obvious offenders — letterbox, keyhole, loft hatch (the hatch is routinely the biggest single leak in the ceiling), door bottoms — are cheap and worth it. The bigger losses hide in the boring places: gaps around pipe penetrations under sinks, the skirting-to-floor junction in older homes, and — the classic — drafty sash windows treated with foam strips that fall out in a season instead of proper brush seals. Draught-proofing old sashes correctly is a known, cheap win (EST has long put sash draught-proofing among the best value retrofit moves); doing it with the wrong kit twice is more expensive than doing it right once. And if a room feels cold despite the work, check the heating itself — <a href="/home/gas-heaters-damp/">some heaters work against the room</a>, and <a href="/home/uk-boiler-servicing/">an unserviced boiler works against the bill</a>.</p>
<h2>Mistake four: over-sealing a home that needs to breathe</h2>
<p>Homes — older UK ones especially — were built to leak deliberately; moisture from living leaves the way draughts enter. Seal every gap without providing ventilation and the moisture stays: condensation on windows, mould behind furniture, the whole <a href="/home/condensation-ventilation-that-works/">ventilation-guide problem</a>. The rule of thumb professionals use: draught-proof the <em>planned</em> openings — doors, windows, hatches, letterbox — and never the <em>designed</em> ventilation — vents, air bricks, trickle vents, flues. If whole-house sealing is the ambition (insulation, membranes, mechanical ventilation), that's a proper retrofit project with professional design, not a tube of sealant.</p>
<p><em>Sources: Energy Saving Trust draught-proofing guidance (savings estimates vary by property and publication year); Gas Safe ventilation requirements for fuel-burning appliances. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("single-glazing-payback", "guide",
"Single-glazing upgrades don't always pay off the way they're marketed",
"New windows are a comfort and a cost — but 'it pays for itself in energy savings' is the claim that survives least contact with the arithmetic.",
"""<p>The double-glazing pitch is one of the oldest in home improvement: new windows slash your bills and pay for themselves. The comfort case is real — warmer glass, no condensation running down the panes, quieter rooms. The energy-payback case is where the marketing and the arithmetic part company, and anyone with single glazing deserves the honest version before spending four figures per window.</p>
<h2>What the savings actually are</h2>
<p>Published estimates (Energy Saving Trust figures are the standard reference, and they vary by property and fuel year to year) put replacing <em>all</em> the single glazing in a typical home with modern double glazing at something on the order of £100-£250 a year off heating bills — meaningful money, and honest. Set that against the installed cost of whole-house double glazing — thousands upon thousands of pounds — and the simple payback runs to decades, usually beyond the warranty of the windows themselves. "Pays for itself" is doing enormous work in that sentence, and salespeople rarely volunteer the timescale.</p>
<h2>The alternatives that change the maths</h2>
<p>Before full replacement, three cheaper routes deliver much of the comfort at a fraction of the cost. <strong>Draught-proofing the sashes and frames</strong> — often the single-glazing complaint is air movement, and proper brush-seal draught-proofing is one of the best-value retrofits in the industry (<a href="/home/draught-proofing-mistakes/">done right, not with foam strips</a>). <strong>Secondary glazing</strong> — a discrete inner pane fitted to the existing window — suits conservation areas and listed buildings where replacement isn't allowed, and its published savings estimates (EST: on the order of £195/yr for a single-glazed semi) land close to full replacement for a small fraction of the cost, with better acoustic results in many cases. <strong>Heavy curtains and shutters</strong> — the oldest technology on the list, and still worth real degrees of comfort on winter nights.</p>
<h2>When full replacement <em>is</em> the answer</h2>
<p>That said, the honest case for full replacement exists, and it's not mainly the energy bill: windows that are rotting, beyond repair, or letting <a href="/home/gutter-cleaning-damage/">water into the wall around them</a> need doing regardless; doing them once, properly, while already paying for remediation is efficient. Comfort has a value the spreadsheet doesn't capture — a warm-edge room in January is a real good. And if the windows are being replaced anyway, specifying the best glazing the frame allows (thin-profile triple or high-spec double) is worth the delta. The claim to refuse is only the payback one: replace the windows for comfort, condition and quiet — and know the energy savings are a modest dividend, not the return of capital.</p>
<h2>The questions to ask any installer</h2>
<p>What's the honest whole-house cost, and what's the published savings estimate for <em>my</em> house type — not "up to"? Which parts are draught, which are glass? Would secondary glazing or sash renovation achieve the comfort target? Are the windows you're replacing actually failing? And what guarantee accompanies the frames, sealed units and installation — and for how long? A good installer answers all five comfortably; the one who can't has told you something.</p>
<p><em>Sources: Energy Saving Trust glazing and secondary-glazing savings estimates (ranges vary by property type and publication year); heritage/conservation retrofit guidance. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("wet-mop-floor-warranty", "guide",
"Why wet-mopping certain floors voids the warranty",
"Manufacturers say it in plain words — 'damp mop only, never wet or steam' — and the exclusion is written into the warranty you're standing on.",
"""<p>The wet-mop habit dies hard because it worked for generations of linoleum and tile. Modern flooring — laminate, engineered wood, luxury vinyl plank — is a different material wearing a wood-look costume, and its manufacturers are unusually blunt about water: Pergo's and Mohawk's warranty texts state that the flooring is <strong>"not designed for wet or steam mopping"</strong>; spills left longer than 30 minutes can void coverage outright; and damage from "jet mops, steam mops, buffers or similar products" is explicitly excluded. The mop that feels like diligence is, contractually, the excluded behaviour.</p>
<h2>What water actually does to each floor</h2>
<p><strong>Laminate</strong> is a fibreboard core with a photographic layer under a clear wear layer — water that finds a seam swells the core, and swollen fibreboard never shrinks back: the lifting edges and peaking joints are permanent. <strong>Engineered wood</strong> tolerates more than solid in some directions and less in others — standing water blackens edges and delaminates the ply. <strong>Vinyl plank (LVP)</strong> is marketed waterproof, and the core genuinely resists spills — but "waterproof" isn't "steam-proof": Shaw's and Armstrong's care documents prohibit steam cleaners outright, because the failure mode is heat and pressurised moisture breaking down adhesives and seams, not the water alone. Manufacturers' logic is consistent across all three: topical spills wiped promptly are life; standing water and steam are damage, and damage from excluded maintenance isn't covered.</p>
<h2>The steam mop, specifically</h2>
<p>Steam mops deserve their own paragraph because they're marketed <em>as</em> the hygienic, chemical-free option — and they are the fastest warranty-voiding device in the cupboard. Hot pressurised vapour drives into seams by design; no major manufacturer of laminate, engineered wood or LVP approves it, and the warranties name it. Tile and sealed stone are its legitimate territory. If the floor under your feet says laminate, engineered or vinyl on the receipt, the steam mop belongs to the bathroom.</p>
<h2>The care that keeps the warranty real</h2>
<p>The manufacturer-approved routine is simpler than the marketing: sweep or vacuum (hard setting, beater bar off — the warranties name those too), then a <em>damp</em>-well-wrung flat microfibre mop with a pH-neutral cleaner — the floor should look dry within a minute of mopping, not wet. Wipe spills promptly — the 30-minute rules are real. Felt pads under furniture (scratching is another named exclusion), and never flood-mop a floor after mopping the one above it. The warranty document for your specific floor — usually on the manufacturer's site — is a five-minute read that names exactly what's excluded; read it once, the day the floor goes down (<a href="/home/unpermitted-work-home-sale/">paperwork in the file wins arguments later</a>).</p>
<p><em>Sources: manufacturer warranty and care documentation — Pergo laminate ("not designed for wet or steam mopping"; 30-minute spill rule), Mohawk engineered wood (steam/jet-mop exclusion), Shaw and Armstrong resilient-flooring care guides ("do not use steam cleaners"). Reviewed September 2026 · general information — your floor's own warranty text is the authority.</em></p>"""),

("underfloor-heating-mistakes", "guide",
"Underfloor heating mistakes that cost more than the installation",
"The system itself is superb and low-maintenance — the mistakes are almost all made on top of it: the coverings, the furniture, the thermostat and the screed.",
"""<p>Underfloor heating has a paradoxical reputation: sold as the luxury that removes radiators, feared as the system that's expensive to fix. The truth is friendlier than both — modern wet or electric UFH is genuinely low-maintenance, and the expensive problems are almost never inside the system. They're on <em>top</em> of it: what covers it, what stands on it, and what gets drilled into it. Each mistake below is common, avoidable, and usually permanent.</p>
<h2>Mistake one: insulating the floor back</h2>
<p>UFH warms the floor surface, which warms the room — put dense, insulating layers over the top and the system works harder to heat the wrong thing. The named offenders: thick rugs with rubber or heavy felt backs (manufacturers publish maximum TOG values for a reason), solidly packed furniture that blankets whole zones, and beds or sofas with flat, closed bases sitting flush on the floor. None breaks anything — the room just never gets warm and the bill climbs. The fix is layout: breathable rugs, furniture with air under it, and zones that are allowed to be furniture-dense left at lower settings.</p>
<h2>Mistake two: flooring choices that fight the system</h2>
<p>Every floor covering has a thermal resistance and a temperature limit, and the Manufacturers' Association guidance on both is real: thick solid wood boards that were never conditioned for UFH gap and cup; adhesive and vinyl have maximum surface-temperature ratings; and the <a href="/home/wet-mop-floor-warranty/">warranty logic cuts both ways</a> — a floor damaged by running hotter than its rating is usually not covered. The quiet killer is thermostat placement: a thermostat in sun, near a kitchen, or behind a door reads the wrong room and runs the system against its own limits.</p>
<h2>Mistake three: drilling and fixing into a live floor</h2>
<p>The single most expensive mistake on this page: fixing a TV bracket, kitchen island or stair rail through a live pipe or cable. Wet systems run pipes in the screed; electric systems run cables in it — and neither is visible from above. Scan before every drill, the way this desk preaches for walls (<a href="/home/mistakes/drilling-without-checking/">the wall version is a mistakes-shelf classic</a>), keep the system's layout photos from the installation file forever, and treat any puncture — a sudden pressure drop on a wet system, a tripped circuit on electric — as an immediate professional call, not a watch-and-see.</p>
<h2>Mistake four: operating it like radiators</h2>
<p>UFH responds slowly — a screeded wet floor takes hours to change temperature — and the people who "boost" it to 27° for a cold morning get neither a warm morning nor a cheap one: the floor overshoots and heats an empty room all afternoon. The system wants steady low setpoints (18-21° typical for comfort), gentle setbacks rather than deep on/off swings, and the commissioning engineer's run-in schedule respected the first weeks (a screed drying too fast cracks — that first-month regime is not bureaucracy). Radiator habits, radiator results; this system rewards patience the way <a href="/home/condensation-ventilation-that-works/">ventilation rewards consistency</a>.</p>
<h2>When it stops working</h2>
<p>Before calling it broken: check the obvious — zone valve positions, thermostat batteries, whether one room or the whole system, whether the floor was recently covered with something new (mistake one, wearing a disguise). Then the professionals — a punctured pipe in screed is a floor-opening job, and the installation file with its layout photos is the difference between a targeted repair and exploratory surgery.</p>
<p><em>Sources: manufacturer and trade association guidance on floor coverings, TOG limits and commissioning schedules. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("deep-clean-schedule", "guide",
"The deep-clean schedule most homeowners get wrong",
"Deep cleaning fails as a calendar event and works as a rotation — and the schedule everyone copies online optimises the wrong things.",
"""<p>Search "deep cleaning schedule" and you'll find the same artefact: a beautiful grid assigning every corner of the house to a day, a week, a season. It survives about a fortnight in real homes, and its failure isn't weakness — the design is wrong. Deep cleaning isn't an event that happens <em>to</em> a house on a schedule; it's a rotation that happens <em>within</em> a maintenance habit. Homes that stay genuinely clean run a fraction of the listed tasks, more often, in the right order.</p>
<h2>Why the calendar grid fails</h2>
<p>Three design flaws. It treats every room as equal — the kitchen and bathroom carry most of the hygiene load and get one grid cell each. It front-loads effort into sessions that exhaust — four-hour Saturday deep-cleans are a subscription to dreading Saturdays. And it separates deep cleaning from maintenance, so the "quick tidy" and the "deep clean" never compound. The deeper truth the grids miss: most of a home's hygiene is decided by <em>daily and weekly</em> habits in <em>two rooms</em> — everything else is rotation.</p>
<h2>The two rooms that carry the house</h2>
<p><strong>Kitchen:</strong> the hygiene-critical sequence is daily — dishes not left standing, surfaces wiped after cooking, the sink drained and rinsed (<a href="/home/garbage-disposal-mistakes/">and the disposal flushed cold if you have one</a>) — weekly: the floor, the fridge check (<a href="/home/fridge-coils-twice-a-year/">whose coils deserve the quarterly half of this habit</a>), the bin cleaned rather than just emptied. <strong>Bathroom:</strong> daily ventilation is the real cleaning — <a href="/home/condensation-ventilation-that-works/">moisture out, or mould in</a> — plus a weekly pass on the actual germ reservoirs: the toilet, the tap handles, the shower head line. Between them, these two rooms are ninety percent of what "clean house" means to health; the bedroom shelves can wait, honestly.</p>
<h2>The rotation that replaces the grid</h2>
<p>Attach one deep task to an existing weekly anchor — the bin day, the sheet change — and rotate through the house's actual needs: month one, skirting and door frames; month two, windows (<a href="/home/mistakes/streaky-windows-sunlight/">not in sunlight</a>); month three, appliances inside (<a href="/home/how-to-clean-a-washing-machine/">the washing machine</a>, <a href="/home/vinegar-in-the-dishwasher/">the dishwasher — no vinegar routine</a>, the <a href="/home/fridge-coils-twice-a-year/">coils</a>); month four, under and behind furniture. Twelve anchors a year, each fifteen-to-thirty minutes, beats the grand Saturday — and it self-corrects, because the rotation visibly pauses where it matters and skips where it doesn't.</p>
<h2>The honest principles underneath any schedule</h2>
<p>Top to bottom, back to front — dust falls and you walk out, not through. Clean for dry before wet — the vacuum does more hygiene work than any spray. Product contact time beats scrubbing — the spray needs its listed minute to work. And the deepest one: a home that's <em>maintained</em> rarely needs the mythic deep clean at all — the season checklist (<a href="/home/seasonal-home-maintenance-checklist/">the product version lives here</a>) and the rotation <em>are</em> the deep clean, happening quietly all year.</p>
<p><em>Reviewed September 2026 · general information.</em></p>"""),
]
