# BRYME Home & DIY — roadmap batch 7: Pest control (5, new "Pests" section) +
# Kitchen & bathroom (3). Verified 2026-09-10: EPA IPM / Do's-and-Don'ts (food-water-shelter,
# clutter incl. cardboard, check packages); pesticide label = legally binding directions (FIFRA);
# UK Approved Document F extract rates (kitchen 30 l/s ducted / 60 l/s elsewhere, bathroom 15 l/s,
# recirculating hoods don't count); sanitary silicone 2-5 yr replacement trade guidance.

HOME_ROADMAP_7 = [
("clean-home-pests-myth", "guide",
"Why 'a clean home doesn't get pests' is a myth",
"Cleanliness helps, but pests are negotiating for three things — water, shelter and entry — and a spotless home can offer all three.",
"""<p>The most harmful pest myth is the moral one: that an infestation is evidence of bad housekeeping. Real homes get pests because pests are negotiating for three things — <strong>water, shelter and a way in</strong> — and a spotless kitchen can still offer all three. The US EPA's pest-management guidance lists the actual attractants, and food residue is only one line among many: leaking plumbing, standing water in plant trays, gaps around pipes, clutter to hide in.</p>
<h2>Why clean homes get pests too</h2>
<p><strong>Water beats food.</strong> Cockroaches can live weeks without food but not without moisture; the drip under the sink, the tray under the plant pot and the pet bowl left out overnight are buffets no bleach can cancel — <a href="/home/small-leak-ripple-effect/">the small-leak guide</a> is also a pest-prevention guide. <strong>Shelter is structural.</strong> Gaps around pipe penetrations, unsealed skirting, the void behind the kitchen plinth: pests don't judge décor. <strong>Entry is geography.</strong> Terrace rows, flats and shared walls move infestations between homes regardless of who's tidy — you can be doing everything right and inherit a neighbour's problem through a shared void. <strong>And some pests don't want your food at all:</strong> bed bugs want you; silverfish want the glue in wallpaper and book bindings.</p>
<h2>What cleaning genuinely does</h2>
<p>This isn't a licence to stop cleaning — it's a targeting exercise. Cleaning works where it removes the <em>first</em> two legs of the table: crumbs and open food (sealed containers, covered bins — the EPA's baseline), grease films that feed insects you never see, and the cardboard-and-newspaper clutter that EPA guidance names as prime hiding and breeding space. What cleaning can't do is fix water and structure — which is why the same housekeeping can produce a pest-free decade in one home and a recurring problem in another.</p>
<h2>The honest prevention list</h2>
<p>The EPA's integrated-pest-management version of a clean home: fix leaks and don't let water stand anywhere; seal food in glass or plastic; close off entry points — caulk the cracks, steel wool around pipes, mesh over gaps; de-clutter, especially stacked paper and card; and check anything coming into the house (<a href="/home/moving-cardboard-pests/">packages, boxes and secondhand furniture get their own guide</a>). Notice the shape: half of it is maintenance, not housekeeping. The <a href="/home/seasonal-home-maintenance-checklist/">once-a-season checklist</a> covers the leak-and-gap half for exactly this reason.</p>
<h2>If they arrive anyway</h2>
<p>Drop the shame — it costs time, and time is what an infestation multiplies with (<a href="/home/ignore-single-pest-sighting/">the costliest response is waiting</a>). Identify what you're dealing with, start with the water and the entry points, and use bait-and-monitor approaches before sprays — <a href="/home/diy-vs-professional-pests/">the DIY-versus-professional guide draws the line</a>. The neighbours don't need to know; the pest control operator doesn't care; and the house doesn't either. Pests are a maintenance event, not a moral one.</p>
<p><em>Sources: US EPA, Do's and Don'ts of Pest Control and Integrated Pest Management guidance (food, water, shelter; clutter; entry-sealing). Reviewed September 2026 · general information.</em></p>"""),

("ignore-single-pest-sighting", "guide",
"Ignoring one pest sighting is the costliest response in the house",
"One cockroach is rarely one cockroach. The arithmetic of egg cases, litters and hiding distances is why 'wait and see' always loses.",
"""<p>Here's the scenario this page exists for: one cockroach crosses the floor at midnight. The options are to deal with it now or to sleep and see. The second option is human and costs almost nothing tonight — and it's the most expensive habit on this desk, because pest populations don't add, they multiply, and the multiplication happens out of sight.</p>
<h2>The arithmetic of waiting</h2>
<p>Keep it qualitative but honest, because the numbers are grim enough without exaggeration: a German cockroach egg case carries <em>dozens</em> of nymphs, development from egg to breeding adult runs weeks in a warm kitchen, and populations go exponential once that cycle overlaps itself. House mice mature in weeks and produce litter after litter through the year — a single pair, well fed and unbothered, is a colony inside months. Rat pairs, wasp queens, Pharaoh ants: the pattern repeats. The one cockroach you saw is also the wrong unit of measurement — by the time any of these animals is visible in daylight, the population behind the plinth is usually established.</p>
<h2>Why "just one" is usually a squad</h2>
<p>Cockroaches, silverfish, bed bugs and rodents are nocturnal and thigmotactic — they hug edges and hide in voids, engineered by evolution to be uncountable. Daylight sightings typically mean crowding or foraging failure — both signs the hidden population is pressing on its boundaries. The exceptions are real (a lone fly, a beetle that flew in a window, a spider being a spider), and the guide to that judgement is: <em>what kind, where, and how many legs of the prevention table is it getting?</em> One woodlouse by the door is weather; a roach in the bathroom at 2am is a census result.</p>
<h2>The 48-hour protocol</h2>
<p>Within two days of any credible sighting: <strong>identify</strong> (photo, or a professional ID — many councils and firms do this cheaply); <strong>inspect the triangle</strong> — water sources, food sources, and the room's edges at night with a torch; <strong>deploy monitors</strong> — sticky monitors cost pennies and convert guessing into data within a week; <strong>close the buffet</strong> — <a href="/home/clean-home-pests-myth/">the food-water-shelter list</a>, done properly. If the monitors come back active, escalate immediately rather than after another month: <a href="/home/diy-vs-professional-pests/">the DIY-versus-pro decision</a> is now about arithmetic, not squeamishness. And log the dates — treatment follow-ups and, in rentals, evidence trails (<a href="/home/uk-landlord-damp-mould-duties/">the reporting discipline</a>, applied to pests) both run on records.</p>
<h2>What "deal with it now" means for rodents</h2>
<p>Mice get one extra warning because of what they chew: wiring. Gnawed cables are a recognised fire risk — electricians and insurers see the aftermath — and a mouse problem inside a wall is an <a href="/home/electrical-fire-warning-signs/">electrical-safety</a> problem whether or not anyone hears scratching. Traps beat poison indoors (poisoned rodents die in voids, and the smell is the receipt), snap traps along edges, and the entry points sealed after — never before — the population is cleared, or you seal them in.</p>
<p><em>Sources: US EPA pest-prevention guidance; extension-service and professional-association pest biology (cockroach egg-case and mouse breeding patterns, qualitative). Reviewed September 2026 · general information.</em></p>"""),

("moving-cardboard-pests", "guide",
"Moving house? The cardboard box is a pest vehicle",
"Cardboard is the perfect pest luggage: warm, dark, fibrous, glue-fed — and it travels from the worst warehouses in the world straight into your new hallway.",
"""<p>Nobody inspects a cardboard box. It's the one object we carry into our homes without a thought, from supermarket stockrooms, online-retail warehouses, office clearances, friends' garages — precisely the places pests commute from. The US EPA's pest guidance names the habit directly: check packages and boxes before carrying them in, and treat cardboard clutter as prime pest harborage. A move, when dozens of boxes cross a threshold in one day, is the single biggest pest-introduction event in most households' year.</p>
<h2>Why cardboard specifically</h2>
<p>Cardboard is engineered to be three things pests love: <strong>dark</strong> (flutes and corrugations are ready-made corridors), <strong>warm</strong> (stacked boxes insulate), and <strong>edible-adjacent</strong> — the glue is starch-based, and silverfish, booklice and cockroach nymphs graze on it. Bed bugs don't eat cardboard, but they ride in it: the corrugations are ideal daytime harbourage within reach of a host, which is why secondhand furniture and boxes that slept in storage units are the classic <a href="/home/diy-vs-professional-pests/">bed-bug introduction route</a>. And cardboard absorbs moisture — the damp box in a garage corner is a three-star pest hotel with no questions asked.</p>
<h2>The moving protocol, start to finish</h2>
<p><strong>At packing:</strong> use plastic totes where you can — they don't harbour, and they're inspectable. Boxes that must be cardboard get sealed, not folded; open flaps are doorways. <strong>Before anything crosses the threshold of the new home:</strong> inspect on the driveway or in the lobby — torch along seams and flutes, look for egg cases (small, brown, purse-shaped along box seams), droppings (like black grains of rice), shed skins, or the tell-tale blood-and-faecal spotting of bed bugs along tape lines. <strong>The secondhand trap:</strong> that free sofa or wardrobe is the highest-risk object that will ever enter your home — inspect seams, screw holes and dust covers, or leave it. Mattresses especially: no secondhand mattresses, full stop. <strong>On arrival:</strong> unpack boxes completely and get the cardboard out of the house within days — stacked, empty boxes in a utility room are the exact <a href="/home/clean-home-pests-myth/">clutter-harbourage the EPA warns about</a>, and they undo the clean start.</p>
<h2>If you've already moved the problem in</h2>
<p>Nothing here is a diagnosis of doom — it's an inspection habit. Signs after a move (bites in a line, droppings under the sink, night-time tickling in walls) get the <a href="/home/ignore-single-pest-sighting/">48-hour protocol</a>: identify, monitor, escalate. Caught in the first weeks, an introduced infestation is small and localised; caught after a year of "we should probably do something about that garage", it's a <a href="/home/diy-vs-professional-pests/">professional's</a> job. The boxes were never the problem — the not-looking was.</p>
<p><em>Sources: US EPA pest-prevention guidance (check packages and boxes; cardboard as harborage; bed-bug caution with secondhand items). Reviewed September 2026 · general information.</em></p>"""),

("after-pest-treatment", "guide",
"What not to do in the days after a pest treatment",
"The treatment keeps working on the edges you can't see — and the most common way people undo it is by cleaning exactly the wrong things, exactly on time.",
"""<p>A pest treatment is expensive, slightly disruptive and easy to sabotage. Not deliberately — the sabotage is nearly always tidiness: the mopping of skirting boards, the wiping of gel dots, the urge to have the house back to normal the next morning. The product doing the work is sitting in a thin band along the edges of your rooms, and the instructions that follow are about protecting it.</p>
<h2>First: re-entry, ventilation, the label</h2>
<p>Follow the technician's stated re-entry time — commonly a few hours until surfaces are dry, longer for specific treatments (fogging, fumigation) — and ventilate on return as instructed. The label on any professional product is not a suggestion: in the US, pesticide label directions carry the force of law, and in the UK amateur and professional products are regulated the same way. If children or pets are in the house, they stay out until the stated time, and treated zones stay off-limits to crawling family members for the day. Dead insects appearing over the following days are the system working, not a failure — remove them with gloves and a vacuum, not a eulogy.</p>
<h2>The cleaning rules that make or break the treatment</h2>
<p><strong>Clean food-preparation surfaces as normal</strong> — counters, tables, anything that touches plates. That was never the treatment zone. <strong>Leave the treated edges alone</strong> — skirting boards, corner lines, under-sink cabinet floors, the backs of appliances — typically for around two weeks or as your technician specified: mopping and scrubbing that band strips the residual product before it's finished its job, and it's the most common reason a treatment "fails". <strong>Never wipe the gel bait</strong> — those small dots in hinge creases and cabinet corners are poison-by-design, placed where insects forage; wash them away and you've removed the actual treatment. <strong>Vacuuming open floors is fine and useful</strong> — especially after bed-bug work, where daily vacuuming is part of the protocol. The rule of thumb: clean <em>before</em> the treatment (that's when the deep clean belongs — <a href="/home/deep-clean-schedule/">the rotation makes that cheap</a>), and be surgical afterwards.</p>
<h2>What else undoes treatments</h2>
<p><strong>Spraying over a professional job.</strong> Retail insecticide over treated edges seals or strips the professional residual and scatters insects into new territory — the opposite of baiting's whole design. If you must act, act on the <a href="/home/clean-home-pests-myth/">water-and-food conditions</a> instead. <strong>Blocking the trails.</strong> Insects follow each other along pheromone lines to bait; bleaching the trail the day after treatment cuts the supply chain. <strong>Sealing the exits too early.</strong> Entry-point sealing is part of the plan, but only after the population is down — seal a wall void mid-treatment and the problem dies indoors, out of reach (<a href="/home/ignore-single-pest-sighting/">the same void logic as rodent work</a>). <strong>Judging it in three days.</strong> Bait strategies work through the population over one to three weeks; increased daytime sightings early on are crowding, not victory. Judge at the interval the technician stated.</p>
<h2>The follow-up is the treatment</h2>
<p>Reputable operators book follow-ups because single-visit eradication of an established infestation is close to a contradiction in terms — <a href="/home/diy-vs-professional-pests/">the multi-visit expectation is how you tell good operators from bad</a>. Keep the follow-up even when things look quiet: the quiet is the point, and confirming it is what closes the job.</p>
<p><em>Sources: professional pest-control aftercare conventions (re-entry windows, residual and gel-bait protection); US EPA pesticide-label direction guidance (label directions legally binding). Reviewed September 2026 · general information — your operator's written aftercare instructions override any general guide.</em></p>"""),

("diy-vs-professional-pests", "guide",
"DIY pest control vs professional: when a spray bottle isn't enough",
"The honest split isn't about bravery or budget — it's about which pests respond to retail products and which have biology on their side.",
"""<p>The pest-control aisle sells confidence, and to be fair, it sometimes delivers: ants on a worktop, a wasp in a window, a mouse in a cupboard — retail products and traps genuinely close these cases. The same aisle also sells the belief that a spray bottle is a solution to everything, and that belief is how three-week-old infestations become three-month ones. The skill is knowing which problem you have before you spend.</p>
<h2>Where DIY genuinely works</h2>
<p><strong>Early and localised.</strong> A scout line of ants (bait — they carry it home), a single wasp, a mouse or two caught early on monitors (<a href="/home/ignore-single-pest-sighting/">which is why monitors exist</a>). <strong>Prevention itself.</strong> Sealants, brushes, mesh, steel wool, and the <a href="/home/clean-home-pests-myth/">food-water-shelter discipline</a> — most pest control that matters is done with no spray at all. <strong>Traps over poison indoors</strong> for rodents — you can count what you catch, and nothing dies in a wall.</p>
<h2>Where DIY loses, predictably</h2>
<p><strong>Bed bugs.</strong> The definitive call-a-professional pest: they hide beyond spray reach, resist most retail chemistry, and need integrated treatment — inspection, heat or targeted chemistry, encasements, follow-ups — with the household doing protocol work between visits. Retail "bed bug spray" mostly spreads them along skirting boards into new rooms. <strong>Established cockroach infestations.</strong> German cockroaches in a kitchen are a baiting-and-monitoring campaign with professional products and placement knowledge; the tell-tale that you've crossed the line is three to six weeks of honest DIY without the population falling. <strong>Anything at height or enclosed.</strong> Wasp nests in eaves, wall voids, chimney stacks — the nest is treatable, the ladder and the swarm are the problem. <strong>Multi-unit buildings.</strong> Flats and terraces re-infest through shared voids; treating one unit of five is arithmetic done wrong. <strong>Health-pressure cases.</strong> Cockroach-allergic asthma, a child's bedroom, an elderly relative's home — the tolerance for slow elimination drops to zero, and that's the right call.</p>
<h2>Why the professional versions of products differ</h2>
<p>It's not one secret ingredient. Professionals bring regulated products unavailable on retail shelves in the UK (professional-use insecticides are restricted), yes — but the bigger advantages are diagnostic and procedural: identifying the actual species (treatment differs by species more than most people believe), placing bait where the population actually travels, having the equipment for voids and heat, and — decisively — the follow-up structure that sees the job through. A good operator explains what they're doing and why; an operator who guarantees everything in one visit is selling reassurance, <a href="/home/after-pest-treatment/">because established infestations are almost never one-visit jobs</a>.</p>
<h2>The decision rule</h2>
<p>Identify the pest first (photo, or a cheap professional ID). Ask: is this localised, early, and a species retail tools actually address? Then DIY with baits and monitors, honestly, for a defined window — a few weeks for cockroaches, immediately and always for anything in food areas. If the window closes without results, or the pest is on the bed-bug/wasp-nest/void/multi-unit list, book the professional without another round of retail spray — the money the second round of bottles costs is the deposit on the professional call you'll make anyway, one population explosion later.</p>
<p><em>Sources: professional-association treatment guidance (bed bugs, cockroaches, wasps as professional-territory pests; 3-6 week DIY-failure threshold convention); UK restrictions on professional-use-only insecticides; US EPA integrated pest management. Reviewed September 2026 · general information.</em></p>"""),

("bathroom-remodel-mistakes", "guide",
"Bathroom remodelling mistakes to avoid before you start",
"The expensive bathroom failures are decided before the first tile: in the sequence, the waterproofing, the ventilation and the paperwork.",
"""<p>Bathrooms concentrate more failure modes per square metre than any other room — water, electricity, steam, structure and money all in one space, and none of them forgiving. The expensive mistakes aren't taste mistakes (tiles are re-tileable); they're sequence and systems mistakes, made before anything visible happens. Here is the pre-start list, ordered by how much each one costs when skipped.</p>
<h2>Mistake one: no waterproofing plan</h2>
<p>Tiles and grout are decoration, not waterproofing — water gets through both happily. What keeps a wet room dry is the system beneath: proper tanking or boards in the wet zones, formed falls to the drain, and sealed penetrations. A bathroom that "leaks through the floor" is almost never a plumbing leak; it's moisture migrating through an unbuilt or badly built waterproofing layer into the joists — the slow kind of damage this desk keeps tracing (<a href="/home/small-leak-ripple-effect/">gradual damage, and how insurers treat it</a>). Decide the waterproofing spec before tiling, not after the first damp ceiling below.</p>
<h2>Mistake two: ventilation as an afterthought</h2>
<p>The single most common post-remodel complaint: a beautiful bathroom that steams like a kettle and grows mould by month three. Extraction is a specified system, not a fan-shaped object: UK Building Regulations (Approved Document F) put intermittent extract at <strong>15 litres per second minimum for a bathroom</strong>, with run-over timers so it keeps working after the light goes off — and it needs a real duct route to outside, not a ceiling-void recluse. A kitchen teaches the same lesson at 30-60 l/s (<a href="/home/kitchen-ventilation-damp/">the kitchen ventilation guide has the numbers</a>); the bathroom version of the mistake is the same shape: fitting the room out while forgetting to give its moisture an exit (<a href="/home/condensation-ventilation-that-works/">ventilation is a system</a>).</p>
<h2>Mistake three: the sequence errors</h2>
<p><strong>First fix before second fix, always:</strong> pipework and cables before wall coverings, wall coverings before fittings, and the <em>choosing</em> of every fitting before the first-fix stage — the plumber tiling around a shower valve that hasn't been bought is how walls get opened twice. <strong>Falls and levels before finishes:</strong> the shower tray, wet-room slope and door thresholds are geometry; discovering the tray sits 20mm proud of the finished floor plan is a whole re-order. <strong>Silicone last, and correctly:</strong> sanitary sealant goes on fully cured, dry surfaces, and gets replaced on a schedule forever (<a href="/home/grout-sealant-neglect/">the sealant guide has the regime</a>) — sealing over unfinished or damp substrate buys you the redo immediately.</p>
<h2>Mistake four: paperwork and permission skip</h2>
<p>In the UK, bathrooms sit inside real regulatory territory: electrical work in a bathroom is <a href="/home/part-p-explained/">notifiable in almost every form</a>; drainage and structural changes need <a href="/home/building-regs-vs-planning-permission/">Building Regulations sign-off</a>; and if you're changing a home's layout or use, the US requires <a href="/home/us-home-permits/">the permits to match</a>. Certificates obtained now are sale assets later (<a href="/home/unpermitted-work-home-sale/">the missing kind becomes a discount</a>). And the quiet one: tell your home insurer about a significant remodel — coverage assumptions don't update themselves.</p>
<h2>The pre-start checklist</h2>
<p>Every fitting chosen and on site. Waterproofing spec written. Extraction specified with a duct route to outside. Trades sequenced: first fix, waterproof, tile, seal, second fix. Notifications and permits applied for. Budget with the customary contingency for what a stripped bathroom reveals — because it always reveals something. A bathroom done in this order is boring in the best way: nothing dramatic ever happens to it again.</p>
<p><em>Sources: UK Approved Document F (bathroom extract 15 l/s minimum, intermittent); Part P notification rules; waterproofing trade conventions. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("kitchen-ventilation-damp", "guide",
"Kitchen ventilation mistakes that cause long-term damp and mould",
"The recirculating hood is the polite lie of kitchen design — it removes smells, not steam, and the steam has to live somewhere.",
"""<p>Cooking is the biggest moisture factory in the house — a working gas hob alone can put roughly a litre of water vapour into the air in an hour of use, before the kettle and the pasta pot weigh in. Where that vapour goes decides whether the kitchen stays fresh or slowly grows its own ecosystem. The most common answer, in millions of kitchens, is "nowhere in particular" — because the appliance that looks like ventilation isn't one.</p>
<h2>Mistake one: trusting a recirculating hood</h2>
<p>A recirculating (ductless) hood filters grease and odours through carbon, then blows the air — moisture and all — straight back into the room. UK Building Regulations say the quiet part in numbers: under Approved Document F, a cooker hood ducted to outside counts as extract ventilation at <strong>30 litres per second</strong> (mounted over the hob); a recirculating hood <em>doesn't count as extract ventilation at all</em> — which is why a kitchen relying on one needs a 60 l/s extract fan elsewhere in the room to reach the same standard. The taste-and-smell improvement is real; the moisture removal is zero. Steam that stays in the kitchen condenses on the coldest surfaces — the window, the external wall — and that's the daily breadcrumb trail to <a href="/home/condensation-vs-rising-vs-penetrating-damp/">black mould and the damp-diagnosis guide</a>.</p>
<h2>Mistake two: the fan that exists but doesn't work</h2>
<p>Ducted extraction fails quietly too. Grease filters clog until the hood hums without moving air — clean them monthly (most pop in a dishwasher). Ducting that's crushed, longer than designed, or — the classic — venting into the loft instead of outside moves the problem upstairs and out of mind. And the fan switched on <em>after</em> cooking starts the extraction ten minutes too late: the discipline is on before the pan, off ten minutes after — the kitchen cousin of <a href="/home/condensation-ventilation-that-works/">the whole-house ventilation rules</a>.</p>
<h2>Mistake three: no make-up air</h2>
<p>Extraction needs replacement air; a sealed kitchen can't give the hood anything to extract. Trickle vents closed, vents blocked, door sealed — and the 30 l/s fan becomes a 5 l/s disappointment. Leave the air route open (that's <a href="/home/draught-proofing-mistakes/">deliberate ventilation — never seal it</a>), and crack a window when the hob is working hard.</p>
<h2>Mistake four: ignoring what combustion adds</h2>
<p>A gas hob adds combustion by-products to the steam — water vapour plus nitrogen dioxide and, when a flame is misbehaving, the quiet risk this desk keeps flagging (<a href="/home/gas-heaters-damp/">unflued combustion belongs outside the moisture story too</a>). Ducted extraction is the only setup that removes combustion products from the room, which is why it's the specification the regulations prefer — and why an <a href="/home/mistakes/co-alarm-wrong-place/">audible, in-date CO alarm near a gas kitchen</a> isn't paranoia. Electrical note for remodels: new kitchen circuits and extracts are <a href="/home/part-p-explained/">notifiable work in the UK</a> — the same rule as <a href="/home/induction-hob-wiring/">the induction guide</a>.</p>
<h2>The five-minute audit</h2>
<p>Turn the hood on and hold a sheet of toilet paper at the filter: it should cling. Check the duct actually exits (go outside and look for the vent in operation). Look at the window and external-wall corners after a week of cooking: dry, or beading? And match what you find to the standard — 30 l/s ducted over the hob, or 60 l/s extracted from the room — because the regulation number is genuinely a good proxy for "this kitchen will not grow mould".</p>
<p><em>Sources: UK Approved Document F (2021): intermittent extract — kitchen 30 l/s (ducted hood over hob) / 60 l/s (elsewhere or recirculating); recirculating hoods not classed as extract ventilation; GGF moisture-production figures. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("grout-sealant-neglect", "guide",
"Grout and sealant neglect: the slow, expensive bathroom mistake",
"Silicone is a consumable with a two-to-five-year life. Nobody replaces it on schedule — until a ceiling below explains the schedule's purpose.",
"""<p>Between every tile and every sanitary fitting is a material doing a job it will do for years without thanks: grout in the joints, silicone at the movement joints and edges. Both are consumables — they wear, they age, they fail — and bathroom failures the size of a ceiling repair usually trace back to the £5 tube that nobody considered for half a decade.</p>
<h2>What actually fails, and when</h2>
<p><strong>Silicone</strong> is the moving part: it flexes where surfaces move — bath rim, shower tray edge, wall corners. Sanitary silicone carries mould inhibitors that deplete, and trade guidance puts its working life at <strong>roughly two to five years</strong> depending on use, ventilation and cleaning. The failure signs: black mould <em>inside</em> the bead (not on the surface — inside it, which no cleaning reaches), shrinking away from the tile, cracks, or a bead that's gone stiff and lets go at the edge. <strong>Grout</strong> is the slower failure: porous, it absorbs water when its sealant layer wears, darkening as it stays damp; hairline cracks open where movement exceeds what grout tolerates (which is why corners get silicone, not grout, in the first place).</p>
<h2>Why the neglect compounds</h2>
<p>A failed silicone bead isn't a cosmetic defect — it's an open seam between a wet room and the building. Water walks through it into the floor structure and the wall substrate: swollen boards, rotting timber, darkened tile lines (<a href="/home/small-leak-ripple-effect/">the gradual-damage arithmetic</a>), and the damp stain on the ceiling below that gets diagnosed as a plumbing problem when the shower above is the culprit. Insurers class it exactly as this desk expects — maintenance, gradual, frequently excluded (<a href="/home/fence-shed-insurance/">the same condition-versus-event line</a>). The five-minute tube versus the four-figure floor: that's the entire trade.</p>
<h2>The maintenance regime</h2>
<p><strong>Inspect the beads twice a year</strong> — spring and autumn, or piggybacked on the <a href="/home/inspection-checklist-gaps/">seasonal walk</a>: press gently, look for movement, check the bottom edge of the shower screen and tray line hardest. <strong>Clean with non-abrasive products</strong> — aggressive bleaching shortens silicone's life even as it whitens it. <strong>Replace on evidence, not on a decade:</strong> mould inside the bead, shrinkage, or cracks mean out with the old — and the replacement rule is absolute: <strong>all of the old bead comes out</strong> (a proper removal tool, then a degrease and a full dry), because new silicone over old re-shows the mould within months and never bonds for long. Tool the fresh bead neat, keep the room un-used and ventilated for the cure time on the cartridge, and write the date on the wall calendar — the new bead's clock started today.</p>
<h2>When it's already gone further</h2>
<p>If tiles sound hollow, if the wall behind the shower feels soft, if grout lines re-darken within days of cleaning — water is past the sealant and into the substrate, and that's diagnosis territory: strip-and-rebuild conversation, not sealant conversation (<a href="/home/condensation-vs-rising-vs-penetrating-damp/">confirm what kind of damp you're meeting</a>), and if you're renting, it's a written report to the landlord rather than a DIY tube (<a href="/home/uk-landlord-damp-mould-duties/">whose duties are tightening</a>). For owners planning work: <a href="/home/bathroom-remodel-mistakes/">the remodel guide puts sealant in the right sequence</a> — last on, on dry, cured surfaces, and on a schedule from day one.</p>
<p><em>Sources: sanitary-sealant trade guidance (2-5 year replacement window; full-removal-before-replacement; mould-in-bead as terminal). Reviewed September 2026 · general information, not professional advice.</em></p>"""),
]
