# BRYME Home & DIY — roadmap batch 9 (finale): Moving house (3) + Budget/insurance (4) +
# Resale (1). All in the new "Owning it" section. Verified 2026-09-10: Bankrate 2026
# Emergency Savings Report (30% could cover a $1,000 emergency; 24% zero savings) + HomeServe
# USA survey (~48% of homeowners face an emergency repair in a year); US insurance mechanics
# via adjuster/III guidance (faulty-workmanship exclusion ≠ blanket denial; misrepresentation
# is the claim-killer; code-upgrade caps); NAR Remodeling Impact Report recovered-cost bands
# (hardwood refinish 147%; roof/garage door 100%; windows 63-67%; doors 60-63%; bathroom
# addition among least recommended). The roadmap's "7 in 10 homeowners" stat DOES NOT CHECK
# OUT — dropped, replaced with the verified numbers below.

HOME_ROADMAP_9 = [
("pre-move-inspection", "guide",
"The pre-move inspection most people skip",
"The day you get the keys is the one day your new home owes you honesty — an hour of looking, testing and photographing that pays for itself for years.",
"""<p>Everyone inspects a house they're buying; almost nobody inspects the house they've just bought. The difference: before purchase you're looking at value, and on day one you should be looking at <em>state</em> — where things are, what condition they're in, and what the last owner didn't tell you. One hour, a torch, a phone camera, and this list.</p>
<h2>Locate the four emergency controls</h2>
<p>Day one, before the boxes: <strong>the main water stopcock</strong> (usually under the kitchen sink or in the hall — turn it once so you know it turns; a seized stopcock discovered during a leak is a <a href="/home/small-leak-ripple-effect/">disaster multiplier</a>); <strong>the consumer unit / breaker panel</strong> — and read the labels, which are usually wrong (<a href="/home/why-does-my-circuit-breaker-keep-tripping/">know what trips what</a>); <strong>the gas isolation valve</strong> at the meter; <strong>the water meter</strong> if there is one — note the reading, because the <a href="/home/small-leak-ripple-effect/">two-hour no-use meter test</a> in week one tells you whether the house has a hidden leak before it tells you expensively.</p>
<h2>The condition walk</h2>
<p>With a torch: the loft (daylight, staining, compressed insulation — <a href="/home/inspection-checklist-gaps/">the blind-spot list applies doubly to an unknown house</a>), under every sink, behind the washing machine, the boiler's service record on the wall (missing? <a href="/home/uk-boiler-servicing/">book the service</a>), and every window and door opening fully — sticking now is information, not character. Check the smoke and CO alarms immediately: they may be expired, absent, or missing entirely — <a href="/home/how-many-smoke-co-alarms/">count what should be there</a>, <a href="/home/co-smoke-alarm-expiry/">read the dates</a>, and treat new alarms as the first thing you buy, not the fifth.</p>
<h2>Photograph everything, dated</h2>
<p>The baseline photo set is the quiet superpower of a new build-to-owner relationship: every wall, ceiling, floor, the meter readings, the boiler serial, the roof from the garden, the fences and outbuildings. Anything the survey flagged gets its own dated close-up. When something fails in year two, you'll know whether it was <em>you</em> or the house — and when you eventually sell, the file becomes the certificates-and-condition pack buyers fall in love with (<a href="/home/unpermitted-work-home-sale/">paperwork wins arguments</a>).</p>
<h2>The legal-adjacent half hour</h2>
<p><strong>Change the locks.</strong> You have no idea how many copies of the previous keys exist — previous owners, their family, dog walkers, cleaners. This is the one job almost universally worth paying a locksmith for on day one (renters: <a href="/home/renter-security/">the permission-first version</a>). Check the certificates you were promised actually exist and chase what's missing. And meet the neighbours — they know where the bins go, when the boiler was replaced, and what that drain does in heavy rain. The best inspection report in the country doesn't know the house like the person next door does.</p>
<p><em>Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("moving-week-by-week", "guide",
"Moving checklist: the week-by-week version nobody follows but should",
"Every moving disaster is a decision postponed past its deadline. This is the timeline that keeps the decisions in front of you.",
"""<p>Every moving story has the same villain: not the movers, not the weather — the week that was supposed to be four weeks. Packing that compressed into two days, utilities that transferred five days late, the deep clean that never happened. The fix isn't more effort; it's the timeline, spread out where you can see it.</p>
<h2>Weeks 6 to 4: the decisions window</h2>
<p><strong>Book the movers or van now</strong> — this is the deadline that gates everything else, and prices only climb. <strong>Declutter ruthlessly:</strong> every box you don't pack is a box you don't pay to move, store or unpack; sell and give away on a deadline, not a whim. <strong>Start the box discipline:</strong> labelled by room and contents-listed on the side (not the top — boxes stack), and read <a href="/home/moving-cardboard-pests/">the cardboard guide before you source free boxes from anywhere questionable</a>. <strong>Notify:</strong> utilities with move-out/move-in dates, and the address changes that have lead times — banks, GP, DVLA/licences, subscriptions, insurers (the buildings policy moves with the date — get that one exactly right; <a href="/home/fence-shed-insurance/">small print follows the house</a>).</p>
<h2>Weeks 3 to 1: the packing rotation</h2>
<p>Pack in reverse order of use: storage rooms and books first, kitchen and daily kit last. One <strong>"open first"</strong> box per person: bedding, toiletries, chargers, kettle, mugs, a pan, toilet paper — the survival kit that makes night one civilised. Photograph the back of the TV and the meter readings at both ends of the move (meter photos are how deposits and final bills get settled without argument). Book any <a href="/home/deep-clean-schedule/">deep clean</a> for the empty-house day — it takes a third of the time it would around furniture — and if you're renting, the deposit inventory is the fight you win with photographs (<a href="/home/renter-security/">the written-record habit</a>, applied to moving).</p>
<h2>Moving day and week one</h2>
<p>Day: walk the old place empty — loft, cupboards, garden, the dishwasher drawer where chargers go to die. At the new place: meters read and photographed, water in, boiler on, and run the <a href="/home/pre-move-inspection/">day-one inspection</a> before the boxes bury the house. Week one: locks changed (<a href="/home/renter-security/">or permission asked</a>), alarms checked and replaced as needed, the stopcock and consumer unit located, the boiler's service history chased, and the neighbours met. Week two: the cardboard leaves the house entirely (<a href="/home/moving-cardboard-pests/">the pest-vehicle rule</a>), and the picture hooks go up — because a house starts being home the moment the walls say so.</p>
<p><em>Reviewed September 2026 · general information.</em></p>"""),

("secondhand-furniture-mistakes", "guide",
"Secondhand furniture: what to check before it enters your home",
"The free sofa is the most expensive thing you'll never buy. A five-minute inspection protocol protects you from the four risks it actually carries.",
"""<p>Secondhand furniture is one of the great bargains of domestic life — and one of the great pest-and-safety vectors. The same object can be a £400 wardrobe for £40 or a bed-bug delivery, a tip-over hazard, or a fire-safety gamble. The difference isn't luck; it's a five-minute inspection that most people skip because the seller is standing right there. This page gives you permission to be that person.</p>
<h2>Risk one: bed bugs — the inspection that matters</h2>
<p>Upholstered furniture is the classic bed-bug vehicle, and the inspection is physical: seams, piping, the dust cover underneath, screw holes, and any joint where fabric meets frame. You're looking for the evidence trail — small dark faecal spots that smear, shed skins, eggs (tiny, pale, rice-shaped) — not the bugs themselves, which hide. A torch and a credit card to run along seams. Any doubt at all: walk away, no matter the price, <em>especially</em> if the price is free. Mattresses and beds are the highest-risk category in existence — <a href="/home/moving-cardboard-pests/">the moving-guide rule applies doubly</a>: no secondhand mattresses, full stop, no exceptions at any price.</p>
<h2>Risk two: fire safety — the label check (UK)</h2>
<p>UK law requires upholstered furniture sold new to meet fire-resistance standards, marked with a permanent label. Secondhand goods don't have to comply when resold — which makes the label the buyer's only evidence. No permanent fire label on a sofa, armchair or mattress: you're buying pre-regulation foam, and the honest move is to decline it. It's also the one check sellers respect instantly when you explain it.</p>
<h2>Risks three and four: structure and recalls</h2>
<p><strong>Structure:</strong> open and close every drawer (runners and joints tell the truth), sit on it with your full weight, rock it, check the legs and the wall fixings — and for anything tall, know the tip-over reality: furniture and TVs falling onto children are a persistent injury statistic, and secondhand dressers often lack the anti-tip straps modern ones ship with (cheap to add; add them). <strong>Recalls:</strong> a quick search of the brand and product before buying catches the known-dangerous items — cots, high chairs and anything child-adjacent especially, because safety standards moved on and old doesn't mean fine.</p>
<h2>The protocol, pocket-sized</h2>
<p>Inspect in daylight, in person, before paying. Bed bugs: seams, under-cover, joints, torch. Fire label: present and legible. Structure: drawers, weight, rock, wobble. Recalls: one search. Bring: a torch, a tape measure (the doorway at home is the real final inspection), and the willingness to walk away — which is the entire superpower of buying secondhand: the one you leave behind costs you nothing, including its bugs (<a href="/home/ignore-single-pest-sighting/">and if something slipped through, the 48-hour protocol catches it early</a>).</p>
<p><em>Sources: US EPA bed-bug precautions with secondhand furniture; UK furniture fire-safety labelling regulations. Reviewed September 2026 · general information.</em></p>"""),

("emergency-repair-fund", "guide",
"The emergency repair fund most homes don't have",
"The average year brings emergency repairs to nearly half of all homeowners — and most households would borrow to meet one. Here's the honest sizing and the building plan.",
"""<p>The roadmap version of this article claimed a neat "7 in 10 homeowners" statistic. It didn't check out — so here are the numbers that do, which are arguably worse. <strong>Bankrate's 2026 emergency-savings report:</strong> only about 30% of Americans could cover a $1,000 emergency from savings, with roughly a quarter holding no emergency savings at all. <strong>HomeServe's homeowner survey:</strong> nearly half of homeowners face an emergency home repair in a given year. Put those together and the arithmetic is blunt: the emergency repair is a <em>when</em>, and the fund for it is an <em>if</em> — for most households, the when arrives while the if never existed.</p>
<h2>What the emergencies actually cost</h2>
<p>The desk's own pages size it better than any statistic: a boiler replacement runs to the low thousands; a roof repair or partial replacement spans a wide band well above that; a water heater or <a href="/home/hvac-diy-warranty-rules/">a heat-pump job</a> is hundreds to low thousands; a bearing-failed washing machine is a replacement (<a href="/home/washing-machine-heavy-items/">see: the mat that killed it</a>); and the slow-leak family of disasters — the rotted cabinet, the flooded floor — lands wherever it likes (<a href="/home/small-leak-ripple-effect/">which is exactly how leaks work</a>). The honest shape of the number: not one dramatic bill but a drumbeat of £200-£2,000 events, two or three a decade, arriving without appointments.</p>
<h2>How much is enough — the honest bands</h2>
<p>Full financial advice this is not; published guidance this is. The practical bands most consumer-finance guidance converges on: <strong>start at one emergency</strong> — the cost of your single most expensive critical system failing (for a gas-heated UK house, think boiler-and-installation money; for a US forced-air house, the HVAC replacement) — then grow toward <strong>1-2% of the home's value per decade of ownership</strong> as the steady-state maintenance-and-repair float, on top of, not instead of, the personal emergency fund. If that sounds impossible, remember what the alternative costs: the same bills, plus interest, at the worst possible moment — the <a href="/home/energy-bill-high-unchanged/">legible-bill principle</a> applied to savings.</p>
<h2>Building it without heroics</h2>
<p>Automatic, small, separate: a standing transfer on payday to an account you don't touch, sized at whatever survives contact with your real budget — £25 or $30 a month is a better fund than the heroic £200 that never happens. Feed it windfalls (tax refunds, the insurance rebate) before they evaporate. And define "emergency" in writing before you need to: boiler dead in January is the fund; the kitchen you've always wanted is a savings goal with a different name.</p>
<h2>The other half of the protection</h2>
<p>The fund pays for failures; the maintenance budget prevents them — and it's the better ROI by every account on this desk: the <a href="/home/uk-boiler-servicing/">annual service</a>, the <a href="/home/seasonal-home-maintenance-checklist/">seasonal checks</a>, the <a href="/home/gutter-cleaning-damage/">gutter habit</a>, the <a href="/home/grout-sealant-neglect/">£5 tube of silicone</a>. The two together are the whole strategy: prevention shrinks the emergencies; the fund absorbs the ones that come anyway. And when one does come — <a href="/home/someday-maintenance-cost/">the someday-cost guide explains why waiting never once turned out cheaper</a>.</p>
<p><em>Sources: Bankrate Emergency Savings Report 2026 (30% could cover a $1,000 emergency; ~24% no savings); HomeServe USA homeowner-repair survey (~48% of homeowners/yr). Reviewed September 2026 · general information, not financial advice.</em></p>"""),

("someday-maintenance-cost", "guide",
"The real cost of 'someday' home maintenance projects",
"Every house has a list called someday. This is what the word costs — measured not in money, but in the gap between the fix and the repair.",
"""<p>Walk any house with its owner and you'll hear it: the loose tile ("someday"), the gutter that overflows ("when we get round to it"), the sealant going black ("we should really..."). Someday is the most expensive word in homeownership, and this page prices it — not with scare statistics, but with the cost mechanism every example on this desk shares: <strong>the fix and the repair are the same job at different prices, and the gap between them compounds.</strong></p>
<h2>The mechanism: failures don't add, they chain</h2>
<p>Home maintenance failures are rarely single events; they recruit. The dripping tap recruits the valve seat, then the cabinet base (<a href="/home/small-leak-ripple-effect/">the ripple-effect guide is literally about this</a>). The blocked gutter recruits the fascia, then the wall, then the foundations (<a href="/home/gutter-cleaning-damage/">years later, and never blamed</a>). The grey silicone recruits the floor under the shower tray (<a href="/home/grout-sealant-neglect/">a £5 job becoming a floor job</a>). The dusty coils recruit the compressor (<a href="/home/fridge-coils-twice-a-year/">the fridge's whole future</a>). The skipped service recruits the boiler (<a href="/home/uk-boiler-servicing/">and always in the first cold week</a>). The chain is the cost: someday's price isn't today's price — it's today's price plus whatever the chain adds, plus the interest of living inside the problem.</p>
<h2>Why the brain prices someday at zero</h2>
<p>Three psychological mechanisms, worth naming because they're the actual enemy. <strong>Invisibility:</strong> working is the default; the gutter that functions looks identical to the one that doesn't, until it doesn't. <strong>No feedback:</strong> the skipped maintenance never sends a bill — the cost arrives disguised as a different problem, years later, in a different trade. <strong>The someday discount:</strong> a task that costs £5 now and £500 in three years feels free today — the same arithmetic that makes the <a href="/home/emergency-repair-fund/">repair fund so hard to start</a>. Knowing the mechanisms doesn't cure them. Designing around them does.</p>
<h2>The design that works</h2>
<p><strong>One list, visible.</strong> Every someday gets written on a single list — fridge door, notes app — because an unwritten someday is a wish, not a project. <strong>Price everything once.</strong> A week of honest quotes turns vague dread into numbers, and numbers compete: the £40 gutter clear beats the £90 flowers once they're on the same page. <strong>The season anchor:</strong> one item per season, attached to the <a href="/home/inspection-checklist-gaps/">inspection walk you already do</a>, keeps the list shrinking at exactly the rate the house produces new items. <strong>The trade-off rule:</strong> if a someday sits on the list past a year, either schedule it or consciously retire it — a decision, made once, beats a nagging indefinitely.</p>
<h2>The reframe that pays</h2>
<p>Here's the arithmetic nobody enjoys and everybody needs: the average someday item — tap washer, gutter clear, sealant bead, coil vacuum, alarm battery — costs tens. The average repair it prevents costs hundreds to thousands, plus the disruption, plus the insurance argument (<a href="/home/fence-shed-insurance/">which maintenance neglect usually loses</a>). Someday isn't a schedule. It's a loan — the house lends you the money now and collects with interest later, and unlike every other loan, you set the repayment date. Set it this season.</p>
<p><em>Reviewed September 2026 · general information.</em></p>"""),

("unpermitted-work-insurance", "guide",
"Does unpermitted work void your insurance claim? The honest answer (US)",
"The internet says unpermitted work automatically voids coverage. Working adjusters say that's mostly wrong — and the real risks are different and sneakier.",
"""<p>Search this question and you'll find one confident answer: "insurers deny claims over unpermitted work." Working adjusters, interestingly, push back on it — the blanket-denial story is mostly internet folklore. But the honest answer is worse than the myth in one specific way: the real risks aren't a single dramatic denial, they're several narrower, sneakier mechanisms that homeowners don't see coming. This is general information, not insurance advice — your policy wording and your state's rules govern — but here's the honest map.</p>
<h2>Myth first: the automatic denial</h2>
<p>Homeowners policies cover "sudden and accidental" damage from named perils — fire, burst pipes, storm. If an unpermitted <em>deck</em> catches lightning damage, there is no automatic exclusion that voids the claim because the deck lacked a permit; negligence, per se, isn't an exclusion in standard policies, and adjusters are quick to correct the folklore. What policies <em>do</em> contain is narrower language, and that's where the honest risks live.</p>
<h2>The real mechanisms, in order of pain</h2>
<p><strong>One: the faulty-workmanship exclusion.</strong> Standard policies exclude damage <em>caused by</em> defective design, materials or construction — and unpermitted work that skipped inspection is, by definition, unverified work. The uninspected wiring that starts a fire: the fire's damage may be argued over; the cost of the wiring is coming out of your pocket. The line isn't "unpermitted work voids everything" — it's "damage the unpermitted work itself caused is on you."</p>
<p><strong>Two: misrepresentation — the claim-killer.</strong> This is the one that can genuinely void coverage entirely, and it's about honesty, not permits. Applications and renewals ask about renovations and improvements; concealing a finished basement, a new circuit, an ADU — and having that surface during a claim investigation — hands the insurer a misrepresentation argument that can void the <em>whole</em> policy, not just the unpermitted corner. The unpermitted work wasn't the problem; the lying was.</p>
<p><strong>Three: code upgrades.</strong> When a covered loss forces repair, policies commonly exclude or cap the cost of bringing undamaged parts of the house up to <em>current</em> code — sometimes capped at a small percentage of coverage. Unpermitted work discovered mid-repair invites exactly this cascade: the inspector-sized hole in your budget (<a href="/home/us-home-permits/">the retroactive-permit cascade</a>).</p>
<p><strong>Four: underwriting consequences.</strong> Unpermitted work that surfaces can trigger non-renewal, higher premiums, or a demand to remedy before renewal — quiet, expensive, and it follows the house.</p>
<h2>What to actually do</h2>
<p><strong>Going forward:</strong> permit what needs permitting (<a href="/home/us-home-permits/">the categories guide</a>) — the inspections are, among other things, an insurance asset. <strong>With existing work:</strong> disclose it honestly at application and renewal; ask your insurer specifically how it affects coverage (in writing, for the file). <strong>Inherited work:</strong> you're responsible for what you knew or disclosed; a seller who concealed known unpermitted work may carry liability — <a href="/home/unpermitted-work-home-sale/">the sale-side guide covers that dispute</a>. The one-sentence version: permits don't buy insurance coverage — honesty keeps it, workmanship keeps it, and the folklore version of the risk is both wrong and smaller than the real one.</p>
<p><em>Sources: standard HO-3 policy structures and faulty-workmanship exclusion language (Insurance Information Institute); working-adjuster commentary on denial folklore; policy-disclosure conventions. Reviewed September 2026 · general information, not legal or insurance advice — your policy wording governs.</em></p>"""),

("renter-vs-owner-repairs", "guide",
"Renter vs homeowner: who's actually responsible for what (UK and US differ)",
"The split is more logical than either side assumes — landlords carry the fabric and the systems, tenants carry their own living. Mostly. With named exceptions.",
"""<p>Every flat-share argument and every landlord-tenant standoff eventually reaches the same question: whose problem is this? The answer is more systematic than either side assumes — and genuinely different across the Atlantic. Here's the map, with the honest caveats: this is general information, tenancy law is detailed, and your lease and local law are the authorities.</p>
<h2>The UK: the law draws the line for you</h2>
<p>England and Wales have an unusually clear statutory split. <strong>The landlord's repairing duty</strong> (Landlord and Tenant Act 1985, section 11) covers, by law and regardless of what the tenancy says: the <strong>structure and exterior</strong> — walls, roof, chimneys, gutters, windows; and the <strong>installations for water, heating and sanitation</strong> — boilers, pipes, wiring, basins, sinks, baths, toilets. <strong>The tenant's duties</strong> are the mirror: use the home reasonably (the "tenant-like manner" standard), report problems promptly, avoid damage, and handle the genuinely minor — light bulbs, smoke-alarm batteries where the tenancy assigns them, small fittings, garden upkeep if the agreement says so. Scotland runs the same logic through the Repairing Standard (the landlord must ensure the home meets it — <a href="/home/uk-landlord-damp-mould-duties/">with Awaab-style timescales from October 2026</a>), and damp and mould sit squarely in landlord territory wherever a building defect or inadequate ventilation capability is the cause — the tenant's duty is reasonable ventilation and reporting, not fixing (<a href="/home/condensation-vs-rising-vs-penetrating-damp/">the diagnosis decides whose problem it is</a>).</p>
<h2>The US: same shape, state-drawn lines</h2>
<p>American law reaches the same destination by a different route: state landlord-tenant and housing codes impose a <strong>habitability</strong> duty on landlords — heat, water, weather-tightness, safe wiring, working plumbing — while tenants owe reasonable use, cleanliness and prompt reporting. The differences are in enforcement and detail: repair-and-deduct remedies exist in some states and not others; deposit rules vary widely; and some leases try to shift statutory landlord duties onto tenants — clauses that are frequently unenforceable for the core habitability items. The practical US rule mirrors the UK: fabric and systems belong to the property owner; living belongs to the tenant; and the lease can't lawfully make you the landlord of someone else's boiler.</p>
<h2>The grey zone, named</h2>
<p>Four areas generate almost all the disputes: <strong>condensation mould</strong> (cause decides — defect or unventilated living; the landlord must investigate either way, <a href="/home/condensation-ventilation-that-works/">and the ventilation guide helps both sides</a>); <strong>appliances</strong> (provided by the landlord: their repair usually; brought by the tenant: theirs); <strong>gardens and boundaries</strong> (lease-dependent, with fences and hedges the classic grey — <a href="/home/fence-shed-insurance/">and the insurance angle differs too</a>); and <strong>decorating</strong> (tenants: only with permission, and painting over damp is never the answer — <a href="/home/painting-over-damp/">it hides the evidence that protects you</a>).</p>
<h2>The protocol that prevents the dispute</h2>
<p>Report in writing, immediately, with photographs — dated. Keep the thread; escalate to the local authority's housing team if the landlord is unresponsive (both countries have enforcement routes, and the UK's just got teeth — <a href="/home/uk-landlord-damp-mould-duties/">the duties guide has the dates</a>). Tenants: never stop paying rent over unrepaired maintenance — withholding rent is the move that turns a strong position into a weak one, in every jurisdiction. Owners: the repair you fund promptly is the dispute you never have.</p>
<p><em>Sources: Landlord and Tenant Act 1985 s.11; Scottish Repairing Standard guidance; US state habitability-code patterns. Reviewed September 2026 · general information, not legal advice — your tenancy agreement and local law govern.</em></p>"""),

("improvements-no-resale-value", "guide",
"Home improvements that don't add resale value (despite what TV says)",
"Refinishing floors returns more than remodelling a kitchen, per the industry's own numbers. Here's what the data actually ranks — and how to spend on purpose.",
"""<p>Renovation television sells a folktale: remodel the kitchen, add the ensuite, and the house "pays for itself" at sale. The industry's own data disagrees, quietly and consistently — the National Association of Realtors' Remodeling Impact Report (with the National Association of the Remodeling Industry) ranks projects by <em>recovered project cost</em>, and the rankings embarrass the TV canon. The numbers change year to year and market to market, but the shape doesn't. Here's the honest leaderboard, with the report's recent bands.</p>
<h2>The leaderboard, honestly</h2>
<p><strong>The quiet winner:</strong> refinishing hardwood floors — the 2022 report put cost recovery at <strong>147%</strong>, the only project in the report's history to clear the bar by that margin. <strong>Full recovery:</strong> new roofing and garage-door replacement, both at <strong>100%</strong> — unglamorous, functional, exactly the things buyers can't assess themselves, so they price them generously. <strong>The middle:</strong> fibre-cement siding (~86%), vinyl siding (~82%), new vinyl windows (~67%), wood windows (~63%), steel and fibreglass front doors (~60-63%). <strong>The sobering ones:</strong> kitchen remodels and bathroom renovations — beloved, transformative, and consistently <em>below full cost recovery</em> — with adding a whole new bathroom among the projects agents least recommend for resale; the rooms sell houses, but rarely for what they cost to build.</p>
<h2>Why the intuition fails</h2>
<p>The TV version assumes buyers pay for what you spent. Buyers don't buy your costs; they buy the house <em>as a whole</em>, against alternatives. Work that makes the house feel maintained and fundamentally sound — floors, roof, doors, paint — moves what buyers will pay because it removes their doubts. Work that makes the house match <em>your</em> taste — the statement kitchen, the luxury suite, the pool (a recurring, famous non-recoverer), the elaborate garden, the converted-for-you garage — prices the next owner's renovation of your renovation. And anything time-stamped (the colour-scheme-2026 kitchen) depreciates like a car. The UK estate-agent convention agrees in shape: kitchens and bathrooms sell homes, energy upgrades barely register in offers, and loft conversions more often pay for themselves than pools or garden buildings ever do (<a href="/home/fence-shed-insurance/">and some garden buildings live in the insurance small print too</a>).</p>
<h2>The decision that actually matters</h2>
<p>None of this says don't improve — it says know which game you're playing. <strong>Playing for you:</strong> remodel the kitchen, add the ensuite, build the garden office — and enjoy them for the years that pay the investment back in daily use, because resale will refund a fraction and that's fine. <strong>Playing for sale:</strong> fix what's broken, refinish what's tired, paint everything neutral — the 147%-and-100% row of the leaderboard — and resist the urge to renovate taste. <strong>Playing both:</strong> do the sound-and-maintained work always, the taste work only where the years ahead will pay you daily. The one genuinely wrong move is the TV move: spending kitchen money expecting sale money back, on a schedule and a budget set by someone who was never measuring (<a href="/home/someday-maintenance-cost/">the someday-cost mechanism, wearing a makeover costume</a>).</p>
<p><em>Sources: NAR/NARI Remodeling Impact Report (recovered-project-cost bands: refinish 147%; roof and garage door 100%; siding 82-86%; windows 63-67%; doors 60-63%; bathroom addition among least recommended) — bands shift year to year; treat as shape, not price. Reviewed September 2026 · general information, not valuation advice.</em></p>"""),
]
