# -*- coding: utf-8 -*-
"""BRYME Home & DIY desk — the Nigeria moat (Phase 1 T11, 21 Sep 2026).

Uncontested territory: harmattan, rainy season, borehole water, generator and
inverter maths, wiring red flags, mould after a flood — written for how homes
here actually behave. Tuple shape mirrors the other HOME_* modules:
(slug, kicker, title, dek, body-html). House rule: safety boundaries stated
without apology; no prices; anything that needs a licensed professional says so.
"""

HOME_LOCAL = [
 ("generator-vs-inverter-nigeria",
  "power",
  "Generator or inverter? The decision is a spreadsheet, not a brand",
  "Before you spend on either, run the arithmetic your salesperson skipped: your real watt-hours, your surge loads, and the one battery rule that decides whether the system survives year two.",
  """<p>Every power quote you receive is priced by kVA and Ah. What your house actually consumes is measured in watt-hours, and that arithmetic - five minutes with a notebook - decides whether your next power purchase feels like freedom or like a rented disappointment.</p>
<h2>Step one: write your real load</h2>
<p>For one honest week, list what you actually run during an outage and for how long: fridge (compressor cycles roughly a third of the hour, not full-time), fans, TV and decoder, router, lights, laptops, water pump. Nameplate watts are on each appliance's sticker; multiply by hours and add up - that's your watt-hour demand per outage. Most homes discover their "big generator instinct" is three times the actual need, and their "small inverter shortcut" is half the real one.</p>
<h2>Step two: surges, not averages</h2>
<p>Motors - fridge compressor, pumping jack, freezer, any borehole pump - pull two to three times their running watts for a few seconds on start. An inverter or generator sized to the sum of running watts will brown out on the evening the pump and fridge decide to wake up together. Sum the running watts, add the largest single motor's surge headroom, and buy against that number. This is the spec salespeople round down.</p>
<h2>Step three: the battery rule</h2>
<p>If you go inverter: usable capacity is roughly half your nominal kWh for lead-acid chemistry (deep cycling a car battery daily kills it in months - the "tubular" upgrade buys time, not immunity), and lithium tolerates much deeper cycles but still ages by heat. Nigerian roof-space heat is the silent budget-killer: a battery in a hot cupboard in year one is a replacement quote in year three. Ventilate the battery room, keep it off the floor, and ask for the installation's battery temperature story before you ask about warranty paper.</p>
<h2>Where each one genuinely wins</h2>
<ul><li><b>Generator:</b> cheap energy per hour while you burn fuel, tireless through long outages, tolerant of a full house running at once. Its true costs are fuel price volatility, service intervals you must actually keep, and noise your neighbours are pricing into their own patience.</li>
<li><b>Inverter + batteries:</b> silent, instant, phone-charging-friendly, and the only option that becomes <em>cheaper</em> over time once solar panels join it. Its true cost is capacity bought upfront: you cannot "borrow" extra stored sunlight on a harmattan week.</li>
<li><b>The hybrid answer almost everyone wants:</b> a small generator wired to charge a real battery bank (changeover done by a licensed electrician with a proper changeover switch and earthing - the death-avoidance part of the diagram), so the generator runs at its efficient steady load to fill batteries instead of babysitting every bulb.</li></ul>
<h2>The check before you buy anything</h2>
<p>Whatever the quote says, make it write: running watts covered, surge watts covered, battery chemistry and usable depth, and - if solar-ready - whether the inverter accepts panels today or needs a replacement later. A vendor who can answer those four questions in writing is selling a system. One who answers "trust me, it'll carry your house" is selling tomorrow's phone call.</p>"""),

 ("harmattan-and-your-electronics",
  "seasonal",
  "Harmattan is hard on screens, laptops and printers - the five-minute fixes that work",
  "Dry air and suspended dust are a chemistry set your devices were not shipped with. Nothing here needs a technician: it needs a calendar and a microfibre cloth.",
  """<p>For six to ten weeks a year, the air in your house is carrying fine mineral dust and holding almost no humidity, and your electronics pay for it in three currencies: heat, static and jammed moving parts. Every fix below is prevention; the cure, once dust has cooked onto a fan blade or paper has curled in a tray, is service fees.</p>
<h2>What actually happens to your devices</h2>
<ul><li><b>Fan intakes cake first.</b> Laptops on beds and sofas - where the intakes are blocked <em>and</em> the fabric is shedding - build a felt layer on the fan within one season. That layer is insulation with a motor attached.</li>
<li><b>Static stops chips slowly.</b> A dry room with synthetic carpet and a nylon chair is a charge generator. Sudden laptop death with no warning is usually not the dry air itself - it's the discharge that happened when someone reached across the desk to touch the open chassis.</li>
<li><b>Screens abrade.</b> Dust on a panel isn't dirt, it's grit; wiping a dry screen with a tissue is sandpaper with confidence.</li>
<li><b>Printers jam on paper mood.</b> Low humidity makes sheet edges curl and static-hold to each other; the top sheet of an old ream is where all the feed failures start.</li></ul>
<h2>The season kit (ten minutes a week)</h2>
<p>One: laptops onto hard trays or lap-desks, off textiles, intakes facing air they can steal - a cheap hard tray works. Two: open the printer cover, fan the stacked paper before loading, and keep the ream in its wrapper with a folded flap when idle. Three: wipe screens <em>after</em> blowing loose dust off (a camera blower or the keyboard trick: short bursts from the far edge), cloth barely damp, never sprayed on the panel. Four: before touching any open chassis - desktop case, TV back, console - touch a grounded metal part of it first, and keep the humidifier on the desk, not the floor. Five: once, mid-season, take the laptop to a shaded table and blow the vents out from the exhaust side while it runs off charge; a year's felt, in ten seconds.</p>
<h2>The humidifier trap nobody warns you about</h2>
<ul><li>Ultrasonic misters scatter whatever is in their water - including salt - onto everything within reach as a fine conductive film. Near electronics, use distilled or boiled-and-cooled water without exception, and point the mist away from desks. A "humidified" desk under a hard-water mister is a corrosion experiment you're funding.</li></ul>
<h2>When to call the professional</h2>
<p>Anything that involves opening a sealed power supply, a TV that clicks and won't light, or a laptop that runs hot <em>after</em> a dust clear - that's the desk's boundary, stated without apology: capacitor charge and glued panels are where YouTube lessons end and burnt mains begin. Fans, filters, paper and cloth are entirely yours.</p>"""),

 ("rainy-season-home-checklist",
  "seasonal",
  "The pre-rains home checklist that Lagos roofs actually need",
  "Gutters, sealant, ceiling pencil-marks, drainage fall and the weep holes nobody remembers: a Saturday of small inspections that turns a leaking ceiling into a paragraph in this checklist instead.",
  """<p>Water does not attack a house all at once; it queues. Every rainy-season emergency on a Nigerian roof has a dry-season version - a half-blocked gutter, a cracked seal, a downpipe pointed at the wall - and each one costs an hour before the rains to fix and a month of repainting after. This is that hour, ordered so the ladder work happens once.</p>
<h2>Roof and gutters (dry boots, two people, morning light)</h2>
<ul><li><b>The bucket test.</b> Clear every gutter and downpipe by hand, then pour two full buckets into the far end of each run. It should leave the downpipe at the ground in seconds, in a steady stream. Anything that backs up, drips at a joint or exits slower than the next bucket proves is a blockage or a fall problem - fix it before the first storm decides for you.</li>
<li><b>Sealant and screws.</b> Walk the parapet and flashings: sheet-to-wall junctions, vent pipes, the screw lines on every roof sheet. Sealant that crumbles to powder under a fingernail is gone, whatever the colour says. Re-bed it; missing screws get replaced with the same neoprene-washer type, not a smaller one.</li>
<li><b>The pencil habit.</b> Mark the corners of every ceiling stain with a dated pencil note on the floorboard behind furniture, not the wall. After the first heavy rain, a stain that grew or a new mark is an active leak with a postcode; a stain that sat unchanged for a season is history. This one pencil is the difference between "repaint" and "find the sheet first."</li></ul>
<h2>Windows and walls</h2>
<p>Slide-frame aluminium windows have weep holes in the outer track - small slots meant to let wind-blown rain out. Construction cement and years of neglect seal them shut, and then the frame becomes a fish tank for your wall. Clear every one with a cocktail stick and a damp rag before the rains. Outside: confirm the ground <em>falls away</em> from the foundation on all sides; a flat apron that puddles against the wall is rising damp on a payment plan. Check the paint at skirting height - chalky, bubbling or crumbling there means the ground, not the roof.</p>
<h2>Power and water, the parts people forget</h2>
<ul><li>Generator and inverter: outdoor units get a raised, drained, roofed position <em>and</em> an exhaust that points away from every window - the rain-storm habit of closing windows around a running generator is how carbon monoxide gets invited indoors; keep the intake side of the house clear and the machine outside, always. (This is the desk's hard line, not a suggestion.)</li>
<li>Water tanks: covers sealed gap-free - storm water pooling on top of an open tank is a mosquito nursery with a maintenance schedule; flush the sediment from the bottom tap before the rains dilute what you're storing.</li></ul>
<h2>The ten-minute wrap</h2>
<p>Photograph the cleared gutters, the pencil marks, the fresh sealant lines, and the dated note goes in the house file. Not for anyone else: when a leak appears next year, your photo set tells a roofer where to look first, and that sentence is worth more than the gutter itself.</p>"""),

 ("borehole-water-and-your-kettle",
  "water",
  "Borehole water, kettle scale and your filter: what actually needs solving",
  "Why white flakes are chemistry, not poison; which problems a boil fixes and which it makes worse; and the filter order that makes sense for a Nigerian borehole.",
  """<p>Nigerian borehole water arrives with three completely different problems that everyone solves as if they were one: hardness, sediment and the occasional biological surprise. A kettle tells you about the first, a white towel about the second, and - for the third - nothing visible does anything at all, which is why the boring test matters.</p>
<h2>Scale is not dirt</h2>
<p>White flakes in a boiled kettle, grey film on a stainless sink, laundry that needs more soap than the packet swears: that's dissolved calcium and magnesium - temporary hardness - precipitating when heated. It is a plumbing-and-appliance issue, not a health one, and boiling <em>concentrates</em> the visible part of it into your kettle element instead of removing it from your glass. What you do about it is engineering, not anxiety: a water softener (salt-dosed, regenerates, needs a drain point) for whole-house appliance protection, or nothing but descaling ritual for the kettle if scale is your only complaint. Magnetic "conditioners" are a cheap science-fair toy at best; don't fund one.</p>
<h2>Sediment, and the order filters go in</h2>
<p>If the towel test turns brown after a minute of cold tap water - fine silt, laterite cloud after rain, or a silty run after the pump kicks - you have suspended solids, and the solution is not expensive, it is ordered: <b>sediment first, carbon second, anything finer third.</b> A spun polypropylene sock (changed when flow visibly drops, not by calendar) eats the silt that would choke every downstream cartridge and scratch every tap valve. Carbon after it improves taste, chlorine where any exists, and the organics that make water "off" without making it dangerous. Skipping to an RO unit as your first move is how homes buy a machine that its own prefilter would have protected - and pay for the waste water RO rejects to fix a problem a cheap sediment sock solved.</p>
<h2>The test no filter can smell</h2>
<p>Boiling is a treatment, not a verdict: it kills germs if given a proper rolling minute, but it destroys nothing - it doesn't remove nitrate, salt, metals or the agricultural cocktail that shallow wells near soak-aways can carry. So once a year, for a small lab fee at a university or state water lab, hand them a bottle of your water <em>after</em> your filters and ask for the two-line answer that matters at home: bacterial contamination indicators, and the dissolved-solids/salt figure. That sheet, kept with the house file, is what "our water is fine" should mean - instead of an opinion about clarity.</p>
<h2>And the tank, always</h2>
<p>Everything above assumes the storage tank is honest: lid sealed against birds and leaves, vent meshed, no sunlit wall for algae, and drained-scrushed-flushed on a rhythm you actually keep (most homes: once a year, before the rains refill everything you stored). The treatment plant is the tank, first - every filter you buy is really insurance you didn't want to need.</p>"""),

 ("wiring-red-flags-in-your-home",
  "safety",
  "Eight wiring signs in a finished Nigerian home that mean call a professional",
  "Warm sockets, dimming lights, daisy-changed breakers, the missing earth - the visible symptoms of problems that become fires at 2 a.m., and the exact sentence to say to an electrician.",
  """<p>Most houses in this country carry wiring installed by the seat of someone's pants - competent in their habit, not in your standards. The reassuring part of electrical faults is that almost every serious one announces itself visibly and early. This page is a translation guide for those announcements, plus the boundary: what you may tighten, what you must hire.</p>
<h2>Call-a-professional signs, ranked by how fast they matter</h2>
<ul><li><b>A socket or plug that is warm, smells of hot plastic, or has brown ghost-marks around the pins.</b> That's resistance heating at a loose connection - a fire that has begun its paperwork. Stop using the socket today, and "today" is the entire warning.</li>
<li><b>Lights dim or bulbs surge when a large appliance starts.</b> Classic loose neutral or overloaded joint - the supply is being shared through a connection smaller than it should be. This one is not cosmetic and not "old houses do that."</li>
<li><b>No earth wire at three-pin sockets.</b> A strip of green-yellow is not decoration; without it an appliance fault makes the metal case - the fridge, the water heater - the live conductor through whoever touches it. Any socket cover you open to find bare copper ends and no earth is a rewiring conversation, not a repair.</li>
<li><b>Twisted tape joins inside walls or above ceilings.</b> Where a junction box should be, a "handled with tape and confidence" splice waits. Tape dries; joints oxidise; faults don't. Every hidden join should sit in an accessible box with a proper connector.</li>
<li><b>One breaker that won't stay in, or trips when the kettle <em>and</em> anything else run.</b> Either the circuit is overloaded past its cable's rating - breakers protect cables, so a breaker that's fighting its job means the cable is losing it - or the breaker itself is tired. Neither is a swap-shop job; both need an actual load check.</li>
<li><b>A board where circuits are shared by improvisation:</b> kitchen on the lights' breaker, AC on a "twin" slot crammed into a space for one device, the spare ways stacked double. Every legitimate panel spare that got two breakers where one sat is how this list begins.</li>
<li><b>Burnt, blackened or "melted-sweet" plastic at the meter tails or changeover.</b> Supply side: hands off, notify the service provider and get a licensed contractor with their paperwork for anything ahead of your main switch.</li>
<li><b>An RCD that has never been tested or never trips on test.</b> The little test button exists for one ritual: press it every quarter. No trip from a live safety device is no safety device.</li></ul>
<h2>What you may actually fix yourself</h2>
<p>With the breaker off and a confirmed dead with your own tester: re-clip a faceplate, replace a switch on the same terminals, swap a flex on a lamp. Anything that runs <em>inside</em> a wall, spans a joint, touches the board, or involves the meter - professional. This desk states its boundary without apology: water, aluminium mains and "small corrections at night" are the three words nearest every tragedy in the news.</p>
<h2>The sentence to say when you hire</h2>
<p>"Test first, quote second, certificate with the work." A real electrician can explain load and circuit for every breaker in your board, will never laugh at the warm-socket question, and expects you to ask for what the wiring in your house is actually made of. If the conversation starts with "how much for me to just add a socket here," the correct answer is a different electrician.</p>"""),

 ("mould-after-a-flooded-room",
  "safety",
  "Mould after a flood or a leaking roof: the 48-hour window and the cut line",
  "What can be saved, what belongs in a bin bag, why bleach on drywall is theatre, and the two moves in the first two days that decide the rest of the room's life.",
  """<p>Mould after a flood is not a cleaning job; it's a race - the first forty-eight hours belong to you, after that the wall chooses. Everything on this page is boring on purpose, because the proven wins here are dehumidifiers, plastic sheeting and judgement calls about what is porous.</p>
<h2>The two moves that come before scrubbing</h2>
<p>One: stop the source. A "cleaned" ceiling above an unsealed roof sheet is a cleaning subscription. Two: get the room <em>dry with force</em> - cross-draft fans, any dehumidifier you can borrow, nothing left damp for the weather to finish the job the flood started. Within 48 hours of wetting, most materials are recoverable; beyond it, porous ones are already colonised. Rush the drying; delay the cosmetics.</p>
<h2>Keep, bin, or cut: the honest rule</h2>
<ul><li><b>Bin list, no debate:</b> anything porous that was under floodwater - mattresses, upholstered furniture that absorbed it, carpet underlay, compressed-board furniture that swelled, any ceiling tile. Floodwater is not rain; what it carried into foam is why the bin is the answer. Seal each item in its own bag on the way out of the room - mould dry-scraped off a mattress is the spore cloud that becomes your lungs.</li>
<li><b>Keep list:</b> solid timber (scrub, then dry slowly out of sun), metal, glass, hard plastics, and concrete block - all cleanable once the water they met was clean-ish. Salvageable with work: rugs and clothing that met <em>rain</em> water, washed hot within the day.</li>
<li><b>The cut line for drywall/plasterboard:</b> board that wicked water above 300 mm from the floor, or that sounds hollow and soft, doesn't dry "back to new" - it dries as a sandwich with a damp core. The professional rule the pros actually follow: cut out affected board <em>up to a line about 300 mm above the highest tide mark</em>, bag from the room, and leave the cavity open and blowing air until everything behind your cut is measurably dry. Patching paint over wet board is how a clean-up becomes a re-build.</li></ul>
<h2>Bleach is theatre on the wrong surface</h2>
<p>On tile, glass and sealed metal: dilute household bleach, scrub, rinse, dry - fine. On plasterboard, wood or grout behind furniture, bleach mostly delivers water to a porous surface while the smell theatrically announces "done" - roots of mould below paint survive spraying. What actually works on surfaces is: HEPA-vacuum dry growth first, scrub with detergent solution, dry thoroughly, then and only then decide whether paint is the last step of dryness, not the first lie. Wear an N95 and gloves for all of it; seal the room off from the house with a taped plastic sheet in the doorway, and if the affected area is bigger than roughly a square metre of wall, that's the size where professional remediation pays for itself in not breathing your own repair.</p>
<h2>The week after: keep it from returning</h2>
<p>Furniture off walls, wardrobes angled to breathe (the corner of a built-in against an external wall is this country's favourite mould colony), bathroom door open after every bath, kitchen extraction while cooking, and the humidity gauge you can buy cheaply learning to read 60 percent in a tropical ground floor as "act now, not smell later." A flooded room that stays mould-free is won with airflow for the rest of its life, not with the one bottle of anti-mould wash. This desk's boundary, stated plainly: structural cracks, sewage water at any scale, and any room where your family includes an asthma attack or a compromised immune system - those start at the professional, not the checklist.</p>"""),

 ("circuit-breaker-tripped-not-mystery",
  "FIX",
  "The breaker keeps tripping and no one is touching anything",
  "Breakers do not trip out of malice. Five causes in order of how fast you can test them, and the one that means stop touching the panel.",
  """<p>A breaker that trips once is an event. A breaker that trips daily is a message - and the message is almost never "the breaker is weak," which is what most advice on the street concludes first and fastest, usually because it is the cheapest thing to replace. Work through the causes in test order before buying anything.</p>
<h2>Test five minutes first</h2>
<ul><li><b>One circuit, one appliance.</b> Reset, then use nothing on that circuit. If it holds, add appliances one at a time until it trips: you have just found the fault, and it is the appliance - usually a heating element in an iron, kettle or water heater whose insulation has started leaking to the chassis.</li>
<li><b>The trip timing tells the story.</b> Trips the instant you switch on = a short or a dead element. Trips after minutes of running = overload or heat creeping into a loose connection. Trips at random, nothing running = the panel or the wiring itself, and the next two bullets are why you call someone.</li>
<li><b>Sniff the panel safely.</b> Open it only by daylight, touch nothing: a warm or fishy smell from breakers or busbar, discoloured plastic, an arc scar on a breaker window - any of these is a loose-connection burn starting, which is the only thing on this list that means stop and call before you read the rest of this page.</li>
<li><b>RCD/GFCI outlets or a breaker with a test button?</b> Press the test button: if it does not click open, your earth-leakage protection is decorative - a separate problem, and an important one in a house where the earth rod may have rusted out of the loop years ago.</li>
<li><b>Two breakers, one appliance, same trip.</b> The appliance is fine and the circuit is shared or mislabelled - someone extended a ring and never told the panel. Map it honestly and move the load.</li></ul>
<h2>What not to accept</h2>
<p>The fix that is "a bigger breaker": upsizing the breaker to stop the trips when the wire is the undersized thing is how houses burn politely, months later inside the wall. The wire gauge is the limit, the breaker is the referee - a referee who refuses to send anyone off is not the solution. If the electrician's whole answer is "change the breaker" and the panel is otherwise quiet, get the second opinion this article was researched to justify.</p>
<h2>What this desk cannot see for you</h2>
<p>Which of the five is yours is a diagnosis of your wiring, your appliances and your panel, made by a competent person with a meter and, for anything inside the wall, a licence. This page is the language to arrive with - and the test list that means you pay for a repair, not a guess.</p>"""),

 ("harmattan-fire-safety-house",
  "MAINTAIN",
  "Harmattan is also a fire season: eleven checks before the dry nights peak",
  "Dry air turns ordinary faults into flame faster than any other month does. The walk-through that takes twenty minutes and the habits that cost nothing.",
  """<p>Between December and February the humidity collapses, everything in the house becomes tinder-grade, and the same faults that shrug off risk in the wet months stop shrugging. This is the harmattan fire walk-through - not fear, inventory.</p>
<h2>Twenty minutes, top to bottom</h2>
<ul><li><b>Charging things off the floor.</b> Phone and torch chargers on a mattress, a curtain's reach, or a plastic surface: move them to a hard, clear spot - and never leave a battery charging on a bed while the room is empty, whatever the month.</li>
<li><b>The heater's one-metre rule.</b> Anything electric that glows or blows heat gets one metre of empty air on every side, away from the curtain that has started pooling near it, and off the rug. The dryer rack is not a heater.</li>
<li><b>Extension bars and their daisy-chain.</b> One heater on one bar, on its own, and check the bar's rating while you're there - a chain of bars feeding a heating load through a thin cable is how harmattan house-fires start in a room that felt tidy.</li>
<li><b>Cooking with windows open, the burn risk of.</b> Harmattan wind plus a small flame behind a window someone closed means a draught moving a curtain; tie the curtain, move the curtain, or cook with the window the other room opens to.</li>
<li><b>Candles and torches - the season's own habit.</b> Outages mean light that has a flame in it. Every candle needs a metal or ceramic base on a shelf nothing above can fall onto; a candle in a jar of water on a windowsill is free and wind-proof. The rechargeable torch with a fresh bulb is the whole solution, so make sure it has one.</li>
<li><b>The ceiling fan's dust.</b> Thick dust on fan blades is fuel with a motor attached - in the dry months it can burn just from heat and friction; wipe the blades and listen for the smell of a warming motor while you're on the ladder.</li>
<li><b>Stored dry goods and paper.</b> Cardboard corners, newsprint for wrapping, the kerosene lamp fuel (if you keep one) - all of it moves away from the electrical panel, the heater's corner and the kitchen stove line. Kerosene lives outside the kitchen, sealed, in a container with a lid.</li>
<li><b>Smoke alarm, if you own one: test it. If you don't:</b> a battery alarm in the corridor outside the bedrooms is the cheapest protective device any house can hold. Put it on the wall tonight, not next month.</li>
<li><b>Exit rehearsal, two minutes:</b> where does everyone come out, where is the key to the gate at night (locked courtyard doors turn a small fire into a big one - keep a torch and the key on the same hook), and who calls the responder; learn the number of the nearest station with the response vehicle, not the one with the best map position.</li>
<li><b>Bikes, gens and fuel:</b> no generator in an enclosed space even in the cold - the same carbon monoxide that no smell warns you about is deadlier in a closed harmattan house - and no fuelling a hot engine; the residual heat finds the vapour.</li>
<li><b>Roof-space lamp and the solar-rig charge controller:</b> dusty connections and a controller cooking in the sun room; check both by daylight, hands off the bare terminals, eyes on the colour of the plastic.</li></ul>
<h2>The habit list (free, daily)</h2>
<p>Switches off at the wall at night - the standby light on an appliance is current that never gets a holiday; heaters are off when the room is empty, chargers when people sleep. And the one sentence to repeat in a house with a courtyard gate: <em>the way out must open faster than the fire grows.</em> No page replaces a working alarm, a rehearsed exit, and a fire you have not started.</p>"""),

 ("ceiling-water-stain-removal",
  "FIX",
  "The brown stain on your ceiling is a map: read it before you paint over it",
  "Active leak versus old scar, how to test in five minutes with kitchen paper, and the stain sequence that actually stops the ghost coming back.",
  """<p>A ceiling stain is a record of water, and like any record it has a date. The date decides whether you are cleaning or investigating - and the worst habit in Nigerian home maintenance is the roller of white paint across a stain that was trying to tell you something.</p>
<h2>Active or archive? Five minutes with kitchen paper</h2>
<p>Press a folded paper towel flat on the darkest part of the stain for a minute, then feel it: damp or warped = water is present now, and the conversation is with the roof or the bathroom above, not the paint aisle. Dry, but the stain has a ring with a darker edge like a tree's ring - that's a tide mark, meaning it is <em>still moving</em>, seasonally, slowly - investigate too. Bone dry with a soft crusty bloom = an old scar; safe to clean and seal. If the ceiling is soft anywhere - press a knuckle gently - skip everything below and go to the leak itself; a spongy board is already part of the structure's future decision.</p>
<h2>Fix the water, then the cosmetic</h2>
<p>The source list for upstairs-or-over-ceiling water: the bathroom-above floor junctions and the grout lines around the shower wall, the trap under any sink on that floor, a toilet seal that fails only on flush (watch the stain for the hour after use - that is the whole diagnostic), and for the top floor: slab cracks, the parapet edge where the waterproofing has gone chalky, and plumbing vents. The pencil-test trick from the rain season - mark the stain's edge - works here too: an edge advancing without rain means an indoor source.</p>
<h2>The stain-removal sequence (after the leak is dead certain)</h2>
<ul><li><b>Wash the halo:</b> warm water with a little detergent, sponge, two passes - ceiling paint is soft and scrubbing it to a shine is its own failure; the water ring lives in the surface, so get the ring, not the centre first.</li>
<li><b>Kill what's left under the paint:</b> water stains bleed through ordinary emulsion, because the stain is tannin - the same chemistry as tea - and emulsion is water-based. A shellac-type or stain-blocking primer, painted only on the stain's area like a spot-weld, is the product; every shop sells one under some brand - ask for exactly "stain blocker," not "sealer."</li>
<li><b>Paint the panel, not the spot:</b> once primed, roll the ceiling's own paint across the whole panel between its corners - a spot-painted ceiling shows its repair under raking light forever, and the raking light is the window you forgot.</li>
<li><b>Black specks with the stain?</b> That is soot from a kerosene lamp or candle below, not water; a degreasing wash handles it and no primer drama is needed. And a stain that smells musty three days after the rain stopped needs the anti-mould wipe in the leak article's playbook before it becomes the next one.</li></ul>
<h2>One-line house rule</h2>
<p>Any stain you seal must be a stain you have tested. Paint over the active one and you have bought yourself eighteen months of watching it reappear in the same shape, bigger - and an estimate next year for the ceiling that sagged while you weren't looking.</p>"""),

 ("compound-mosquito-control-night",
  "MAINTAIN",
  "Mosquito control that works on a compound: the four-hour rule beats the fogger",
  "Why spraying the air is theatre, the standing-water audit nobody does, and the screen-and-fan strategy that cuts the night bite count properly.",
  """<p>The evening mosquito on a Nigerian compound is not an air problem to spray away - it is a breeding problem with an address, and the females that bite you were made within fifty metres of where you sit. Foggers kill some of the flying generation tonight and zero of next week's. Here is the audit that actually lowers the bite count, ordered by payoff.</p>
<h2>The standing-water audit (the whole ballgame)</h2>
<ul><li><b>Walk the compound after dark with a torch:</b> every vessel that can hold water an adult female can raise children in - blocked gutter and its channel against the wall, tyres, the saucers under pots (the most beautiful garden in the city is a hatchery), buckets left outside, the water storage without a lid clamped down, a discarded carton in the corner the wind blew behind the fence. Tip, scrub, cover, drain - the larvae need calm water and the eggs need the vessel to stay damp between rains, so <em>scrubbing</em> the inside matters as much as pouring.</li>
<li><b>The one-a-week rhythm:</b> mosquitoes are faster than seasons - seven days is roughly the water-to-biter schedule, so the audit lives or dies on its calendar, not its thoroughness.</li>
<li><b>Ornaments and the obvious:</b> the birdbath gets scrubbed, the vase water changes weekly, the AC's drip tray is the quietest breeding tank in the city's homes - check it, and clear its drain where it runs into the wall.</li>
</ul>
<h2>Barriers that do the real night work</h2>
<p>Sleep under a treated net, because the dawn and dusk feeders do their damage when you are unconscious and no spray survives a whole night of fans. Window screens on the bedrooms - mesh costs money once and screens keep the house breathable with the lights on, which is the difference between a compound you can sit in and a house you retreat inside. The door you leave open for the evening breeze is the road in: the fan in a doorway blows harder than any insect's flight speed and costs nothing but a socket - the airflow barrier is the one trick renters and owners can both do tonight.</p>
<h2>The things that are theatre</h2>
<ul><li><b>Coils and plug-in liquid vaporisers</b> push the numbers down in a closed room and lose most of it the moment a window is open - use them in the bedroom before you enter, with the door shut, not as an invisible force field for the sitting area. <b>Herb-burn smokes</b> repel by making the room unpleasant for everything including you, and the larvae stay happy downstairs. <b>Ultrasound apps and wrist bands</b>: no measurable benefit at any honest dose of hope.</li>
<li><b>The estate fogger:</b> useful for the immediate swarm at the gate - it's an insecticide event, not control - and it will not reach what matters, the water no one emptied.</li>
</ul>
<h2>When to escalate</h2>
<p>A sustained bite load after all of the above means a source bigger than your compound: a neighbour's blocked plot, the vacant lot with its tyres, a shared tank with its lip - that is a block-level conversation and the vector-control people exist for the public end of it. On the personal side: a fever in the season with the bite count means the clinic and the test, not this page - this desk handles the mosquitoes; the illness is the doctor's desk.</p>
<h2>Two lines to remember</h2>
<p>Empty what holds water once a week; blow a fan across the places you cannot screen. Everything else is marketing with a nozzle - and the bite count will tell you which of these two was the one you needed.</p>"""),

 ("gentle-low-flow-fixes",
  "FIX",
  "The tap runs thin and nobody will blame the plumber: five gentle fixes",
  "The aerator that ruins everything, the sediment sock, the valve that never fully opened after the tank work - low flow is usually three minutes of your own time, not a pump.",
  """<p>A tap that sighs instead of running is one of the most misdiagnosed faults in a house with stored water - everyone reaches for the pump, the "pressure problem," the plumber's invoice. Most thin flow is mineral and grit, caught deliberately by the fixtures the engineers designed to catch it - and those traps are meant to be cleaned, not worshipped.</p>
<h2>Three minutes, in order</h2>
<ul><li><b>The aerator.</b> Every modern tap has a threaded mesh screen in its nose to mix air into the stream and meet water-efficiency rules - which also makes it a perfect sediment sieve. Unscrew it (a coin edge or fingers; cloth if it's chromed), soak the little insert in vinegar for twenty minutes, brush its mesh soft, refit. This single job fixes more "low-pressure taps" than any plumber in the city will admit to doing.</li>
<li><b>The shut-offs that were never reopened.</b> After any tank work, a tap under the sink, or the isolated fixture's own valve, someone turned and half-turned: check the tap's isolation valves and the fixture's inlet connections - and the storage tank's own outlet valve, which the handyman closes "while at it" and then never remembers. A main that is a quarter turn from open makes the whole house run thirsty - the same symptom as a failing pump, at the cost of a wrist.</li>
<li><b>The single-lever mixer's cartridge.</b> A mixer only hot or only cold or stubborn in the middle usually has debris in the cartridge - isolate both lines, undo the handle, pull the cartridge, flush the seat, check the little rubber seals and the flow-restrictor washer in the inlet for grit - then refit, and if it still runs the same, the same cartridge is a shelf item at any serious plumbing counter for less than a plumber's call-out.</li>
<li><b>Kitchen and bathroom taps are different animals:</b> the pull-out kitchen spray head has its own clog-prone face plate - soak its face in vinegar in a bag tied around the head for an hour; the showerhead with its rubber nubs is meant to be rubbed clean with a thumb while running - every nub that clears is a millilitre you got back.</li>
<li><b>Grit from the tank itself.</b> If the aerators keep clogging weekly, the problem is upstream - the sediment sock from the well article (change it; grey, not white, means it is doing its job), or the tank needs its own cleaning day - and that is a whole separate page on this desk.</li></ul>
<h2>When it is genuinely pressure</h2>
<p>Thin flow at <em>every</em> fixture at once, the tank full, the valves wide open, the aerators clean - then and only then is it a pump, a header height or a partially collapsed supply line. The order matters because each step above costs a few minutes, and the pump question costs money. A plumber who arrives and reaches for a new pump before the aerator list is the man this article exists to protect you from.</p>"""),

 ("wall-fan-making-noise",
  "FIX",
  "Your ceiling fan is wobbling, humming or grinding: the five-minute triage",
  "Tighten before you balance, balance before you buy: the order that fixes most fan complaints with a step stool and a screwdriver.",
  """<p>The sounds a fan makes are a short vocabulary, and learning it saves a replacement: each one names a specific part that is loose, dirty or dying. The triage below works in the order the fixes cost - a step stool, then a hand, then money.</p>
<h2>Identify the voice</h2>
<ul><li><b>Wobble (the blades trace an ellipse you can see):</b> first - are the blade screws tight and the down-rod's little clevis pin at the ceiling hook seated properly? Most wobbles are a rod joint that has rattled half out, not bent blades. Then balance: a cheap clip-on weight set or a coin taped blade-to-blade until the run smooths tells you which blade is the light one, and a follow-up tightening of its screws is half of all "my fan needs balancing" jobs.</li>
<li><b>Hum at low speed only:</b> usually electric - the speed controller or, on older fans, the capacitor's frequency against the motor; if the hum climbs with the speed and the fan spins free by hand, the diagnosis is the capacitor (a shelf-cheap part any fan technician carries) and not the motor.</li>
<li><b>Rumble that changes when you touch the housing lightly:</b> mechanical looseness - the motor's retaining ring, the housing screws into the mounting bracket, or the light kit's glass - press-test each with one hand at the stick, and the noise follows the culprit; nothing else in the house diagnoses by <em>touch</em> as beautifully.</li>
<li><b>Grinding or rasping, every rotation:</b> dust-caked blades hitting the tolerance, a wire inside the cowl, or the motor's bushings running dry on older motors. Power off at the wall, spin the blades by hand: a gritty feel and you have the bushing verdict, and bushings are the part "my motor's dead" shops quietly replace for less than a new fan's tenth.</li>
<li><b>Squeak that follows the switch-on, not the speed:</b> the mounting bracket at the ceiling box - the whole fan sags a millimetre when it spins and the bracket's screws creak. The fix is re-tightening with the bracket pushed up, so undo its ceiling-box screws, lift, tighten - and if the ceiling box itself is the flexing part, that is the one fan job to call someone for, because the ceiling box holding a spinning weight is the house's problem, not the fan's.</li></ul>
<h2>What to do while you're on the stool</h2>
<p>Dust the blades top and bottom with a pillowcase over each one (the cloth traps the harmattan load instead of the room's lungs - the same trick the harmattan-fire page recommends twice a month); look at the down-rod's cotter and the safety wire in the bracket for anything frayed; and with the fan off, give it a push and watch the coast: a fan that stops within a second or two twice in a row is telling you about the bearings before it stops politely mid-heat.</p>
<h2>Skip the theatre</h2>
<p>Balancing kits sold without checking the screws first; "silent" replacement fans bought while the old one's housing screws were never tried; and oil ports that modern sealed motors do not have - if the guide you read says to inject sewing-machine oil and there's no port on your motor, the advice is thirty years stale and the answer is the bushing or a new motor head, not a drip. The five-minute order - tighten, balance, clean, listen, then decide - resolves the majority of everything written here without opening a wallet.</p>"""),

 ("water-heater-no-hot-water",
  "FIX",
  "The shower is cold and the heater light is on: five checks before anyone quotes you",
  "Element, thermostat, cut-out, connection, tank - the water heater's fault ladder in the order a technician would climb it, with the safe version for you.",
  """<p>An electric water heater is a kettle with ambition: a tank, an element that is a stove coil in disguise, a thermostat that is a switch on a spring, and a cut-out that gives up before the fire does. Cold water means one of five things failed, and the ladder from simplest to final is worth knowing - because half of "element failures" are the cheap switch having done exactly its job.</p>
<h2>The five, in order</h2>
<ul><li><b>Isolation and breaker first, always.</b> The heater has its own switch on the wall or its own breaker; both get looked at before both get reset, and the panel gets sniffed for the warm-fishy smell from this desk's breaker article before any reset happens at all. Power off at the wall before touching anything else in this list - the honest version of "unplug it" for a hardwired box is the breaker, with the neighbours' lights off so you can see the tell-tale glow die.</li>
<li><b>The high-limit cut-out.</b> Inside the thermostat cover sits a reset button on most units: it fires when the tank overheats - which is what a dying thermostat does before it dies, and it is also what a heater does when it ran empty during a supply cut. With power OFF, remove the access cover (screwdriver, one panel), find the little red or black button, press it. Heater lives, hot water returns in an hour: the fault was the safety, and you still owe the unit a thermostat check - a cut-out that fires once was brave, a cut-out that fires monthly is a witness.</li>
<li><b>The thermostat itself.</b> Set to maximum as a test - a thermostat stuck below the cut-out never lights the element, and the dial being down is the cheapest cold shower in the trade. A multimeter continuity check across its terminals, power off, is five minutes for anyone who owns the meter; if the reading contradicts the dial, the part is the invoice.</li>
<li><b>The element.</b> The classic: continuity through the element should be a low, real number, and continuity from either terminal to the copper tank should be nothing at all. A reading between a terminal and the tank means the element's sheath has cracked and it is leaking current into the water - which is the failure mode that makes "the RCD trips in the bathroom" the last warning you get before the shower becomes a conductor. That one is not a DIY swap; that one is the electrician's call, tonight.</li>
<li><b>The tank, and the year it is at.</b> A heater past its element's designed life in hard water area throws the element, the anode and eventually the seam all in the same season. A weep at the flange, rust bloom at the seam, a tank that has clearly never been descaled in the house's ownership: quote the whole unit, not the part - this desk has watched people buy elements for a coffin.</li></ul>
<h2>The two minutes of prevention that cost nothing</h2>
<p>Set the thermostat to what the manual calls its lower band - a hotter tank scales faster and scalds the children's bath, and no comfort is purchased above "properly hot"; and if the area is hard-water, a drain-and-flush habit at the annual maintenance day moves the grit out before it becomes the element's burial shroud. The gas instant heaters get their own short line here too: no spark means the batteries first - the water-flow switch second - never the gas - and a flame that lifts off its burner is a shut-down-and-call fault, not a tune-up.</p>
<h2>What this desk will not pretend</h2>
<p>Tank draining, element replacement in a wet cupboard, and any work on a leaking energised vessel are jobs for the qualified person with the right tools and the insurance - the value of this page is that you hand them the diagnosis instead of the shower-curtain rumour, and pay for the repair, not the guess.</p>"""),

 ("toilet-weak-flush-fixes",
  "FIX",
  "The toilet runs weak, runs forever, or won't refill: the cistern is four parts",
  "Flapper, float, fill valve, jet ports - the cistern's small anatomy, the five-minute tests for each, and the two jobs that mean call the plumber.",
  """<p>Every toilet complaint in the house lives inside the tank, and the tank holds four working parts, which makes every complaint a four-question interview. Plumbers call a cistern "easy money"; the reason is that nine times in ten the part that failed costs a wallet-swap and the tenth is the job they genuinely need. The interview below is how to know which ten you are in.</p>
<h2>Four parts, four symptoms</h2>
<ul><li><b>The flush is weak or dead: the flapper (or the tower seal).</b> Lift the lid; flush while watching. The seal should lift fully and stay up the whole flush. If it drops early, the chain is too long (adjust to a slack thumb's width - the whole fix, free) or the seal has gone soft and black from the chlorine tablets everyone drops in here (replace it; it is the most stocked toilet part in any hardware shop).</li>
<li><b>The tank barely fills: the water level, set by the float.</b> The mark on the back of the overflow tube is the target - the level should sit about an inch below it. A float set low gives a weak flush even when every part works, and a float set high sends all the excess down the tube while the tank "won't fill." One bend or one screw, depending on the era of the mechanism.</li>
<li><b>It runs forever after flushing: the fill valve not shutting.</b> Listening at the lid: a hissing tank that never quite stops is the valve's seal dying - and while you are there, the refill tube aimed into the overflow (it should trickle a stream down the tube; if it's detached, the bowl never refills to its smell-blocking level - which is why "my toilet smells after the flush" is a twenty-second fix you can find here).</li>
<li><b>Bubbling, glugging, slow drain after a good flush: the rim jets and the trap.</b> The small holes under the bowl's rim are what create the swirl; mineral crust closes them into a dribble - an old toothbrush and vinegar down the ports, held wet with paper towels for an hour, is the treatment. A toilet that flushes clean-but-then-refills-noise-like-a-drinking-animal is a partly blocked vent stack: that's the roof, and that's the plumber.</li></ul>
<h2>The two where you stop and call</h2>
<p>Water at the base of the toilet after flushing (the wax ring or the flange is failing under the floor, and the subfloor is learning about it) and sewage smell that no amount of scrubbing fixes with the tank's refill and the trap's water level both verified good - that smell is the drain system telling you it needs a professional camera, not a bucket of bleach. Everything above the two is a lid-up afternoon.</p>
<h2>The habit that prevents half of them</h2>
<p>No chlorine blocks in tanks with rubber seals - they eat the flapper from the soft side, and the shop selling them will not mention it; flush only what the trap was designed for, because the "flushable" wipe earns its name only in marketing; and when the house will be empty for weeks, close the isolation valve behind the toilet and flush the tank nearly dry - a seal that dries under a full tank cracks, and that is the whole story of toilets found dead after every festive-season trip.</p>"""),

 ("paint-peeling-walls-bathroom",
  "FIX",
  "The paint is coming off the bathroom wall in sheets: why, and the sequence that lasts",
  "Trapped moisture, skipped primer, and the alkali burn from cement render - the three causes, the dry-wall test, and the redo order that actually sticks.",
  """<p>Peeling paint is almost never a paint problem; it is a moisture or surface problem wearing paint's clothes. The bathroom is the house's champion at both, which is why the same wall re-peels through three expensive repaints until the sequence below is done in the right order, with the right patience for the drying step that everyone shortens.</p>
<h2>Diagnose in three minutes</h2>
<ul><li><b>Where it peels tells you the cause.</b> Peel at the bottom third, near the floor or outside-wall base: rising damp or a shower leak finding the low path. Peel behind the shower wall on the other side: water is crossing the wall and the paint is the membrane it escapes through - check the grout and the silicone bead around the tray first (the ripple article's logic, one wall away). Peel everywhere at once after a holiday with the windows shut: the room lived on its own steam - the condensation article's territory - and the paint just kept the score.</li>
<li><b>The foil test, overnight:</b> tape a square of kitchen foil to the wall, tape all edges, check in the morning - water on the room side, condensation; water behind the foil, the wall is carrying it from outside or within. The two answers need different fixes and no amount of paint distinguishes them.</li>
<li><b>White crust with the peel (efflorescence):</b> that is cement's salts arriving with the water and staying when it dries. It is the one that specifically punishes painting through: paint over salt and the new coat inherits the eviction.</li>
</ul>
<h2>The redo sequence, no shortcuts</h2>
<p>One: fix the water - the leak, the grout, the ventilation - or delete this list from your plans because you are repainting a clock. Two: scrape every loose edge to firm paint, sand the feather, and - this is the step everyone skips - wash the whole panel with detergent, rinse, and let the wall dry on its own for at least several days with the windows open; a wall that is dry to the paint tester's cheap meter can still be wet behind the render and the meter's numbers are what to watch, not the calendar. Three: prime - and the primer here has a name to ask for: an alkali-resistant or stain-blocking primer on cement render (ordinary emulsion on fresh render is eaten by the same salts above, and "it drank the paint" is that conversation), and a proper anti-mould primer where the bathroom black has lived. Four: two thin coats of bathroom-rated emulsion, not one heroic one, and the fan or window running for the week after - the coat cures against moisture, and a shower in a freshly painted box on day two is a shortcut that re-opens the cycle.</p>
<h2>What this desk won't pretend about ventilation</h2>
<p>A bathroom with no window and no extractor is a condensation machine no product fixes; an extractor door to the outside beats one dumped into the roof space, and a trickle vent kept open costs nothing and outperforms every "anti-mould paint" claim, which are sold as a coat and delivered as an excuse. If the peel keeps winning after a correct sequence done honestly, the wall is getting water you cannot see from a leak you have not found - that is the investigation this page sends you off to make, and the leak-detection people with their cameras are the last, right answer.</p>"""),

 ("solar-panel-care-nigeria",
  "MAINTAIN",
  "Your solar is producing a third of what it used to and the inverter isn't lying",
  "Dust, soot, shade and the hot-spot walk: the maintenance a panel actually wants, the cleaning rules that don't void anything, and the checks for the box in the sun.",
  """<p>Solar panels are famous for being maintenance-free, and the sentence everyone quotes skips the Nigerian addendum: dust, harmattan haze, cooking soot on the kitchen-side roof, and a mango that found its ambition at the panel's edge. A dirty panel loses output in silence - the system doesn't fault, it just earns less. This is the maintenance the marketing forgot.</p>
<h2>The output evidence, before any climbing</h2>
<p>Your inverter or charge controller is the instrument: log the same hour's production on three clear mornings, or read the app's history - a slow sawtooth decline with a rain-wash recovery is dirt; a hard step down after a storm is damage; the one-to-test is a partial shade pattern (a new shelf, the neighbour's antenna, the palm that was a seedling at installation). Dirt is a maintenance job; everything else on that list is a fault hunt. If the figures show nothing, the panel stays on the roof where the sun is keeping it honest and the inverter's history is the witness.</p>
<h2>The cleaning rules that keep the warranty intact</h2>
<ul><li><b>Rinse, then soft cloth or a sponge on a pole; mild detergent if there is grease; the glass is glass, not the paintwork of a car - but its edge seal is the vulnerable part: never high-pressure washers, which drive water past the frame into the laminate, and never a dry scrub of gritty glass, which sands the coating and the glass at once - grit plus water, cloth, glide.</b></li>
<li><b>Cool glass, early morning.</b> Panels straight-off-the-shelf at midday can crack under a cold pour - thermal shock is the one thing that breaks panel glass with no fault to show - and a wet panel in full sun dries into fresh water-spot mineral marks, so the dawn session is the only honest one.</li>
<li><b>From the ground when possible; from the roof only when the roof is safe:</b> the desk will not talk anyone onto a ladder - if the panels are beyond the eave-reach, the cleaning is a professional job with harnesses, and a good cleaning visit costs less than a single fall costs everyone. Walk the roof edge, check the feet: any rust bloom at a mounting foot or a lifted rail after a storm wind is a structural call, not a cleaning item.</li></ul>
<h2>The five-minute electrical glance (eyes off, hands off)</h2>
<p>Look, do not touch: cable glands and any visible wiring for cracks, rodent chews and UV-brittle insulation - a chewed cable is not a "tape it" job, it is the DC fault that has started a roof fire; MC4 connectors and the inverter's DC isolator for a discoloured plastic (heat at a loose connection shows its colour before it shows its fault code); the inverter itself for its own ventilation - a box cooking in the sun room throttles its output, which reads exactly like dirty panels on the app, and the shade board or vent slot that fixes it costs the price of a piece of plywood.</p>
<h2>The annual list</h2>
<p>Wash at the harmattan's end; check the mount bolt torque when it is safe to reach (vibration loosens what the installer tightened); trim the shade at the panel line; re-run the same-hour three-morning test and compare with the last year's same-month figures; and read the battery room's smell and colour - a swollen battery case or a sulfurous tang means the whole page becomes moot because the battery person is now the first call, on the day, not the week.</p>"""),

 ("gate-motor-solar-light-care",
  "MAINTAIN",
  "The gate motor and the solar security light: the small-service list that keeps both alive through harmattan",
  "Humming-but-dead gates, misaligned photocells, dim lights by January - the two outdoor devices live on the same three enemies, and a Sunday afternoon fixes most of it.",
  """<p>The gate motor and the solar pillar light are the house's two permanently-outdoor electrical devices, and they fail the same way for the same reasons: the sun cooks the electronics, the rain finds the cable entry, and the dust packs the moving parts. Both are serviced by one afternoon's walk with the same small kit - cloth, brush, a screwdriver, hose water, not the pressure washer.</p>
<h2>Gate motor: the four checks</h2>
<ul><li><b>Humming, no movement - the run capacitor.</b> The motor's starting capacitor is the part that loses its strength quietly; the gate stops, the buzz stays, and a push moves it free. A fan-repair shop tests and matches capacitors for the price of the call-out itself, and the matching list (microfarads and voltage on the label) is photographed in thirty seconds - that photo is the whole shopping trip.</li>
<li><b>Reverses for no reason - the photocells.</b> The eye-and-target pair by the floor is what makes the gate stop for a car; a dust film, a spider's Sunday architecture, or a millimetre knocked out of alignment and the gate "sees" an invisible car forever. Wipe the faces, sight the brackets (a phone camera at one end, the reflector at the other, the light on the motor board as the judge), realign, re-tighten.</li>
<li><b>The rack and the hinge line:</b> grit in a toothed rack is the sound of teeth dying - brush it, check every bolt on the bracket plates and the rack's fixings (the gate's own vibration walks them loose before anything else), and the swing gates' hinges take the same treatment with the grease nipple as the prize. A gate that drags at one point of its arc has a foundation, not a motor, problem - the post's concrete foot has shifted or the ground has moved with a drain washing under it, and that is the mason's job before the technician's.</li>
<li><b>Battery and board: the quarter-year glance:</b> the backup battery's terminals for the white or green bloom (clean, grease thin, retighten - the gate that "stopped working" is the voltage drop at a corroded terminal nine times out of ten at the end of the rains), and the board's little LEDs for the fault code the manual decodes; surge is the board's other killer - a proper earth at the controller cabinet is what makes a lightning season survivable, and if the cabinet's earth wire is decorative, that is the electrician's five-minute job on the next visit.</li></ul>
<h2>Solar security lights: the honest maintenance</h2>
<p>The panel face gets the cloth - a film of harmattan dust on a mini-panel is the difference between a full charge and a sensor that dims by 10pm; the lamp head's vent and PIR lens get the brush, because a wasp's nest and a dust lens are the two "the light is crazy now" faults before the electronics are ever accused. The sensor's false triggers - the cat, the shrub the wind moves, the parked car's engine heat - are aim-and-reach adjustments, not faults; most units carry the two dials (sensitivity, time) and the rule "aim low, across the path, not along it." The one real replacement decision: the battery. These lights charge a small lithium or NiMH cell every day, and after two harmattans the dim-by-midnight light is a battery, sold by theAh matching, not a new light - the solar-repair area stocks them and a solder tab swap is the whole job for the patient hands.</p>
<h2>What this desk will not promise</h2>
<p>Anything inside a sealed board, any gate that grinds from the gearbox itself, and the mains-voltage side of an installation with no isolation switch to prove the work was done right - those are the tradesperson's line, and the service list above exists to make sure you are paying them for the repair and not for the dust.</p>"""),

 ("musty-wardrobe-clothes-rainy",
  "MAINTAIN",
  "The wardrobe smells musty the week the rains end: the six-week fix, not the spray",
  "Mould lives where the wall is cold and the air is still. The reorganise, the desiccant maths, and the wash routine that saves the clothes you already mourned.",
  """<p>Mustiness is not dirt, it is farming: a closed cupboard with a cold outside wall, clothes packed against it, and the humid weeks of the rains gave the wardrobe its own weather. Sprays perfume the farm and leave the crop; the fix is to change the climate, and the clothes have their own rescue sequence.</p>
<h2>Move the farm's weather, in order</h2>
<ul><li><b>Empty it on a sunny day and open everything:</b> every door and drawer, the house windows too, and the wardrobe's back off the wall where the cold lives - the eight centimetres an inch of air gap buys is the whole free fix, and the packed-to-the-back wall is the reason the back row of clothes always spots first.</li>
<li><b>Wipe all inside surfaces</b> with the detergent-water-and-rinse cloth, not bleach on wood - then dry it fully, fan or sun, before anything returns; and look while you are in there: the dark bloom under shelf edges and the corner joints is the mould from the condensation article wearing different clothes, and the wall behind the unit gets the same inspection - a damp stain there is the leak investigation the paint article already told you to start.</li>
<li><b>Desiccant, with the maths:</b> the chalk-pots and silica trays work until they don't - most saturate within a rainy season and then sit there as decor; the calcium-chloride tubs with the collecting dish are the refillable honest version, and the box of loose silica beads is for cameras, not cupboards. Two pots, one near the floor (cold air pools) and one mid-shelf, checked and replaced on the rains' first week.</li>
<li><b>Wash the wearable load</b> - not the wash-day pile, the whole season's rotation: whites on the hottest the label allows with the detergent dose for soiling (not the aroma dose for scent), colours at the warm-with-vinegar-half-cup add that the older laundry hands already swear by, and the sun is the actual anti-must smell agent: the UV and the dry heat end what the wash only loosened. The leather and the suede are the specialists' - the sun that saves cotton is what cooks leather into shell.</li>
<li><b>Return the clothes with the gap discipline:</b> nothing touching the back wall, the heavy coats at the front where the air moves, and the "it can wait" dry-clean-only pile out of the cupboard entirely - a garment bag in a still wardrobe is a greenhouse with a zip.</li></ul>
<h2>The rhythm that prevents next year</h2>
<p>Open the doors an hour on harmattan afternoons - the season's dry air is free and it is the only time the walls themselves release what they stored; a solar fan in a top vent is the serious version of the same sentence and costs less than the clothes the last season taught you to value. And the one-line habit with the best ratio of all: no damp anything into the wardrobe - the half-dry towel, the gym shirt, "it's basically dry" - every one of them is a crop rotation for the next must.</p>"""),
]
