# BRYME Home & DIY — roadmap batch 3: HVAC / heating & cooling (5) + Plumbing (3).
# YMYL-verified 2026-09-10: EPA WaterSense leak figures; ENERGY STAR filter guidance;
# Clean Air Act Section 608 (refrigerant); UK Water Fittings Regs 1999 notification scope;
# UK boiler warranty/CP12 conventions. See docs/ecosystem/home-article-roadmap.md receipts.

HOME_ROADMAP_3 = [
("hvac-filter-change-habit", "guide",
"The HVAC filter habit that decides whether your system lasts (US)",
"ENERGY STAR puts it plainly: check monthly, change at least every three months — a clogged filter is how systems die early.",
"""<p>In a home with central heating and air (the standard US setup), there is one component you can service in thirty seconds that determines how hard every other component works: the air filter. ENERGY STAR's maintenance guidance is unusually blunt about it — check the filter every month, especially during heavy-use winter and summer months, change it when it looks dirty, and at a minimum change it every three months, because a dirty filter slows airflow, wastes energy, and can lead to "expensive maintenance and/or early system failure".</p>
<h2>What a clogged filter actually does</h2>
<p>The filter's job is to catch dust before it reaches the blower and the coil. As it loads up, air can't get through — so the blower works harder to move less air, runtimes stretch, and the system's heat exchange suffers. In cooling season, starved airflow can let the evaporator coil literally freeze over; in heating season, a furnace running against a blocked filter can trip its high-limit safety or overheat the exchanger. None of this is dramatic on day one, which is why the failure arrives as "the system died young" rather than as the filter's fault. It is the same slow-then-sudden pattern as <a href="/home/fridge-coils-twice-a-year/">dust on fridge coils</a>, at ten times the scale.</p>
<h2>The habit, done right</h2>
<p>Find the filter slot (in the return duct or the air handler itself), note the size printed on the frame — buy a multi-pack so the next change is already in the cupboard. Check it monthly during heavy use: hold it to a lamp; if no light comes through, it's done. The arrow on the frame points in the direction of airflow, toward the equipment. Homes with shedding pets or dusty rooms go through filters faster than the three-month minimum — that's the "check monthly" half of the guidance doing its job.</p>
<h2>Filtration: more is not always better</h2>
<p>Filters carry MERV ratings; higher numbers trap smaller particles but resist airflow more. A very high-MERV filter in a system not designed for it is the same problem as a dirty filter, permanently — restricted air, strained blower. Most residential systems are happiest in the moderate band, and the manual's stated rating range beats any marketing claim about "the best filter". If allergies are driving the choice, that's a conversation for the system's installer, not a bigger number bought blind.</p>
<h2>The two neighbours of this habit</h2>
<p>The filter is the indoor half of airflow; the <a href="/home/ac-outdoor-unit-care/">outdoor condenser unit is the other half</a>, and it wants a monthly glance in season too. And if you've inherited a system nobody maintained, don't jump straight to repairs — <a href="/home/hvac-diy-warranty-rules/">know what you're allowed to touch first</a>, because warranty terms and law draw lines here that surprise people. Readers outside the US: forced-air systems are rare in UK and Irish housing (radiators and boilers rule — <a href="/home/uk-boiler-servicing/">see the boiler-servicing guide</a>), but the principle travels to any filtered ventilation system in the house.</p>
<p><em>Sources: ENERGY STAR heating and cooling maintenance guidance (check monthly; change at least every 3 months). Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("hvac-noises-decoded", "guide",
"HVAC noises decoded: what rattling, buzzing, grinding and hissing actually mean",
"Your system announces most failures before they happen — the skill is telling 'loose screw' from 'stop and call'.",
"""<p>Heating and cooling systems get loud for a reason, and the reason is usually mechanical: something loose, something wearing, or something that shouldn't be there. You can't fix most of them yourself — but you can learn which noises mean "tighten a panel" and which mean "switch it off and call a technician", and that distinction is worth real money.</p>
<h2>The noises you can investigate safely</h2>
<p><strong>Rattling</strong> is usually physical: a loose access panel, an unscrewed cover, or debris — a twig, a screw — sitting in the outdoor unit or rattling in a duct. Power off at the breaker before you go looking inside anything, hand-tighten panels, clear visible debris, and listen again. A rattle that survives all that is internal and stops being your job. <strong>A single click at startup or shutdown</strong> is the relay doing its job — normal. Clicking repeatedly without the burner or fan answering is an ignition or relay problem, and that's a technician's visit.</p>
<h2>The noises that mean stop and call</h2>
<p><strong>Grinding</strong> — metal on metal, like a bad bearing in the blower motor — is a "stop using it" sound; running it on makes the repair bigger. <strong>Squealing</strong> points at a worn belt or motor bearings: not an emergency, but not something to ignore into winter either. <strong>Buzzing</strong> often means electrical — a contactor or loose component — and electrics inside HVAC equipment are professional territory, the same boundary as <a href="/home/induction-hob-wiring/">the induction-wiring guide</a>. <strong>Hissing</strong> has two flavors: air through a duct gap (annoying, worth sealing) or refrigerant escaping a line (professional only — refrigerant work is legally certified work in the US, see <a href="/home/hvac-diy-warranty-rules/">the warranty-and-law guide</a>). <strong>Banging or booming at ignition</strong> on a gas furnace — a small boom as it lights — can be delayed ignition from dirty burners, and on gas equipment you book that call immediately, never investigate it yourself. <strong>Gurgling</strong> points at a condensate drain that wants flushing — sometimes a homeowner fix, sometimes a tech's five minutes.</p>
<h2>How to be the customer techs love</h2>
<p>Before you call, write down: the noise, when it happens (startup, running, shutdown, always), what you were running (heat, cool, fan-only), and whether anything changed recently — a filter swap, a storm, a new thermostat. Take a fifteen-second video of the sound happening. That record turns a vague "it makes a noise" into a diagnosis on wheels, and it's the same evidence discipline this desk preaches everywhere — <a href="/home/uk-landlord-damp-mould-duties/">reports in writing, dated photos</a>, facts before opinions.</p>
<h2>The prevention half</h2>
<p>Most of the expensive noises trace back to the same small neglects: a filter left in too long starving the blower (<a href="/home/hvac-filter-change-habit/">the monthly habit</a>), an outdoor unit choked with leaves and grass (<a href="/home/ac-outdoor-unit-care/">the seasonal clean</a>), or years without the professional tune-up that catches a worn belt while it still only squeals. Noise is your system's early-warning system — it's free, and it's already installed.</p>
<p><em>Sources: HVAC manufacturer troubleshooting guidance and ENERGY STAR maintenance materials, synthesised; symptom→cause mapping is diagnostic convention, not certainty — a technician confirms. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("hvac-diy-warranty-rules", "guide",
"DIY and your HVAC: what's allowed, what voids the warranty, what's illegal",
"Three different lines run through this trade — what you may do, what costs you coverage, and what actually requires a certified technician by law.",
"""<p>People hear "don't DIY your heating and cooling" and assume it's all one rule. It isn't — three different lines run through this territory, and knowing which is which makes you a better owner: one is about skill, one is about paperwork, and one is federal law.</p>
<h2>Line one: what you may freely do</h2>
<p>The maintenance that keeps a system alive is deliberately homeowner-friendly: the <a href="/home/hvac-filter-change-habit/">monthly filter check and change</a>; keeping the <a href="/home/ac-outdoor-unit-care/">outdoor unit clear and gently rinsed</a> with a garden hose (never a pressure washer); pouring a cup of white-vinegar-and-water down the condensate drain line to keep it clear; thermostat battery changes; and keeping two feet of clearance around the equipment. None of this voids anything — it's the routine the warranty assumes you're doing, and manufacturers' own guides describe it.</p>
<h2>Line two: what quietly voids coverage</h2>
<p>HVAC warranties carry conditions, and the big ones are documentation and qualification: repairs and replacements to the sealed system and internal components are expected to be done by a licensed technician, and annual professional maintenance is the condition most warranties hang on — an unbroken service record, like the UK boiler world's <a href="/home/uk-boiler-servicing/">Benchmark-and-Gas-Safe convention</a>. A DIY repair inside the equipment — electrical work, a new capacitor, anything touching the blower or control board — can void the coverage on that component and sometimes the whole unit, and "it broke while I was fixing it" is not a claim. Before any repair you're considering, the warranty booklet (or the manufacturer's site) beats any forum; if the unit is young, the maths is almost always "call the warranty tech".</p>
<h2>Line three: what is illegal to DIY in the US</h2>
<p>Refrigerant is where DIY crosses from warranty territory into federal law. Under Clean Air Act Section 608, anyone who maintains, services, repairs or disposes of equipment containing regulated refrigerant must be EPA-certified in refrigerant handling; the sale of refrigerant is restricted to certified people; and knowingly venting refrigerant is illegal, with five-figure federal penalties attached. Opening the refrigerant circuit — "just topping it up" — is certified-person work, full stop, and it's also the fix for that <a href="/home/hvac-noises-decoded/">hiss that isn't a duct</a>. The parallel UK line is gas: any work on a gas appliance or its flue legally requires a Gas Safe registered engineer (<a href="/home/uk-carbon-monoxide-alarm-law/">and the alarm law sits on top</a>). Gas furnace internals in the US belong to a licensed gas technician for the same reason — <a href="/home/mistakes/co-alarm-wrong-place/">the CO alarm is your last line of defence</a>, and it only stays last if nobody disables it.</p>
<h2>The decision rule</h2>
<p>If the job's entry point is a filter slot, a garden hose, or a battery door — it's yours. If it's a screwdriver into the equipment, check the warranty first. If it's refrigerant, gas, or the electrical innards — it's a licensed professional's, and no amount of YouTube changes what the law says. That's not gatekeeping; it's the same boundary this desk draws on <a href="/home/why-does-my-circuit-breaker-keep-tripping/">every</a> electrical page: know the line, respect the line.</p>
<p><em>Sources: EPA Clean Air Act Section 608 (certification, sales restriction, venting prohibition); manufacturer warranty-term conventions; ENERGY STAR maintenance guidance. Reviewed September 2026 · general information, not legal advice.</em></p>"""),

("uk-boiler-servicing", "guide",
"Boiler servicing: what UK homeowners skip, and what it costs later (UK)",
"The annual service is cheap, it's the warranty's condition, and it's the CO safety check nobody thinks they need — until the winter it fails.",
"""<p>UK homes run on boilers the way US homes run on furnaces, and the British habit with them is the same as everywhere: ignore the thing until the first cold week of the year, when every heating engineer in the county is booked solid. The annual service is the habit that breaks that cycle — and in most cases it isn't optional at all.</p>
<h2>Three reasons the annual service matters</h2>
<p>First, <strong>warranty</strong>: the major manufacturers — Worcester Bosch, Vaillant, Ideal, Baxi, Glow-worm, Viessmann — condition their warranties on an annual service by a Gas Safe registered engineer, recorded in the benchmark service checklist. Miss a year and the cover can be void even for a fault unrelated to the service — with warranties now running five to twelve years, that's real money riding on a roughly hour-long visit. Second, <strong>safety</strong>: a boiler burns fuel and makes exhaust; the service checks the heat exchanger, flue and combustion, which is exactly the machinery that produces carbon monoxide when it fails — <a href="/home/mistakes/co-alarm-wrong-place/">the alarm catches what slips through</a>, the service stops most of it. Third, <strong>cost</strong>: an annual service is typically advertised around the £60–£125 mark (varies by region and provider — check current local prices), while an emergency winter callout with parts runs several times that, and a failed heat exchanger usually retires the boiler entirely.</p>
<h2>A service is not a landlord's gas safety check</h2>
<p>This is the most common confusion on the subject. Landlords are legally required (Gas Safety Regulations 1998) to have gas appliances checked annually and to give tenants the record — the CP12. That check is a safety inspection, not a service: booking a CP12 and assuming the boiler has been serviced is, as heating engineers put it, a common and expensive mistake. The two can be done in one visit by the same engineer, and for rental properties that's the sensible arrangement — but they are two jobs, and only one of them keeps the warranty alive. Tenants: you're entitled to the CP12 record, and to a landlord who takes a reported boiler seriously — <a href="/home/uk-landlord-damp-mould-duties/">the duties are tightening across the UK</a>, and boilers are the model for it.</p>
<h2>What a proper service includes</h2>
<p>A real service — not a glance through the casing — includes: casing off, visual inspection of the flue route, combustion analysis with a flue gas analyser, checks on seals, pressures and the expansion vessel, safety-device testing, a condensate check, and the record updated in the benchmark checklist. Ask for the combustion reading: an engineer who measures and explains beats one who doesn't. Any Gas Safe registered engineer qualified on domestic boilers can do it — registration is the legal requirement for anyone working on gas in the UK (<a href="/home/uk-carbon-monoxide-alarm-law/">see the alarm-law guide for the enforcement side</a>); you can verify any engineer's card on the Gas Safe Register site.</p>
<h2>Timing and the honest bottom line</h2>
<p>Book for late summer or early autumn: engineers are available, the weather isn't against you, and a fault found in September is an appointment, while the same fault in January is a cold house in a queue. If your boiler is over fifteen years old, service it by all means — but start an honest parallel conversation with yourself about replacement timing, because the same efficiency and safety logic that makes the annual service cheap makes an ancient boiler expensive.</p>
<p><em>Sources: UK manufacturer warranty conventions (Worcester Bosch, Vaillant, Ideal, Baxi and peers require annual Gas Safe servicing); Gas Safety (Installation and Use) Regulations 1998 (landlord annual gas safety check); Gas Safe Register. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("ac-outdoor-unit-care", "guide",
"The outdoor AC unit needs attention too — not just the indoor system (US)",
"The condenser is a radiator with a fan, and it lives outside collecting everything the wind brings — ten minutes a month keeps it breathing.",
"""<p>Half of your air-conditioning system lives outside, on a concrete pad, quietly gathering cottonwood fluff, grass clippings, leaves and dust. The indoor half gets the filter changes; the outdoor condenser gets ignored until the bill climbs or the cooling fades. It's the same physics as <a href="/home/fridge-coils-twice-a-year/">fridge coils</a> — a radiator can only dump heat if air can move through it — and the fix is equally cheap.</p>
<h2>What the unit is trying to do</h2>
<p>The outdoor unit doesn't make cold; it throws heat out of your home. The refrigerant carries the heat outside, the coil sheds it, and the fan pulls air through the fins to carry it away. When those aluminum fins are matted with debris, the heat has nowhere to go: the system runs longer for less cooling, the compressor runs hot — and the compressor is the part whose replacement costs enough that people replace the whole unit instead. ENERGY STAR's guidance treats this as basic monthly upkeep, alongside the <a href="/home/hvac-filter-change-habit/">indoor filter</a>.</p>
<h2>The monthly ten minutes, in season</h2>
<p>Kill the power at the outdoor disconnect before you touch anything inside the unit. Clear leaves, grass and fluff from around and inside the top guard by hand. Gently rinse the coil fins from the inside out or top down with a garden hose — the debris should wash out the way it came in. Never use a pressure washer: the fins bend at the slightest provocation, and bent fins choke the same airflow you're restoring (a fin comb straightens minor damage). Then keep the machine's airspace: two feet of clear space all round, no mulch, no stored items, vegetation trimmed, and nothing stacked on top.</p>
<h2>Season-by-season</h2>
<p><strong>Spring, before first run:</strong> rinse the coil, clear the pad, check the unit hasn't shifted out of level (a leaning condenser wears its compressor bearings), and remove any winter covers — <strong>don't run the unit with a cover on</strong>. <strong>Summer, monthly:</strong> the ten-minute clear-and-rinse, plus a glance at the insulated refrigerant line — insulation that's crumbling wants replacing, and there's where you stop and call, because everything beyond insulation is <a href="/home/hvac-diy-warranty-rules/">certified-person territory</a>. <strong>Autumn and winter:</strong> clear leaves out of the top, and resist the full tarp wrap — a sealed cover traps moisture and invites rodents; a breathable top cover against falling icicles and leaves is the useful version. <strong>First run in spring:</strong> listen — <a href="/home/hvac-noises-decoded/">grinding, screaming or buzzing mean call, not hope</a>.</p>
<p><em>Sources: ENERGY STAR heating and cooling maintenance guidance (coil cleaning, clearance); manufacturer condenser-care conventions. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("small-leak-ripple-effect", "guide",
"Why a small leak never stays small",
"The EPA counts 10,000 gallons a year of household leak waste — and the drip is the cheapest part of what a slow leak does to a house.",
"""<p>A dripping tap or a slow weep from a pipe joint is easy to live with: it's quiet, it's small, and it isn't flooding anything — yet. The US EPA's WaterSense programme put hard numbers on "small": the average household's leaks waste more than 10,000 gallons a year, a faucet dripping once per second alone wastes more than 3,000 gallons — about 180 showers' worth — and one home in ten has leaks running 90+ gallons a day. And the water bill is the smallest of the leak's costs.</p>
<h2>Why leaks escalate</h2>
<p>A leak is a mechanism, not a state. The worn washer that lets a tap drip also lets water work on the valve seat, so the drip sharpens; the weeping joint corrodes the very metal it touches; the loosened flapper in the cistern lets water run silently for months — toilet flappers are the EPA's most-cited household leak for exactly that reason. Water follows gravity through whatever it reaches: a slow leak under a sink first swells the board floor, then rots it, then feeds the mould that turns a £4 washer into a cabinet rebuild. Out of sight behind a wall, a pinhole supply leak is how you meet <a href="/home/condensation-vs-rising-vs-penetrating-damp/">the damp-diagnosis guide</a> from the worst possible direction.</p>
<h2>The insurance wrinkle nobody mentions</h2>
<p>Most home policies draw a hard line between <em>sudden</em> water damage (a burst pipe — typically covered) and <em>gradual</em> damage (a leak that's been seeping for months — often excluded, and insurers look for exactly that evidence). That's not legal advice and policies differ, but the asymmetry is real: the slow leak you mean to fix next month can land entirely on you, structure and all, while the same leak caught this week is a small claim or no claim at all. Check your own policy's wording once — it's five minutes that can be worth thousands.</p>
<h2>Finding the silent ones: the meter test</h2>
<p>The EPA's own method: read your water meter, don't use any water for two hours, read it again. Movement means a leak you haven't met yet. For toilets — the classic silent runner — a drop of food colouring in the tank that appears in the bowl without flushing means the flapper's gone. Then walk the house: under every sink, around the boiler/water heater, behind the washing machine (<a href="/home/washing-machine-heavy-items/">whose hoses deserve their own respect</a>), and under every rug you never move.</p>
<h2>The response rule</h2>
<p>Fix what's plainly homeowner-territory — <a href="/home/leaky-faucet-diy/">a tap washer, a flapper, a showerhead connection are genuinely DIY jobs</a>. Anything inside a wall, under a floor, on the supply pipe itself, or recurring after repair goes to a plumber promptly — and "promptly" is the whole point of this page: the leak's bill compounds daily, and unlike most bills on this desk, interest never stops accruing. The <a href="/home/seasonal-home-maintenance-checklist/">once-a-season checklist</a> includes a look under the sinks for exactly this reason.</p>
<p><em>Sources: US EPA WaterSense, Fix a Leak Week facts (10,000+ gal/household/year; 3,000+ gal for a 1-drip/second faucet; meter test). Reviewed September 2026 · general information; insurance outcomes vary by policy and jurisdiction.</em></p>"""),

("leaky-faucet-diy", "guide",
"Fixing a leaky faucet yourself: what's safe, and when to call a plumber",
"A dripping tap is the classic first DIY job — it's genuinely safe, genuinely cheap, and it teaches the three habits every water repair uses.",
"""<p>Every household should fix a dripping tap once, because it teaches everything about safe water work in one afternoon: isolate the supply, take it apart slowly, replace the worn part, put it back. It's low-risk, needs no tools you shouldn't own (<a href="/home/basic-toolkit-checklist/">they're on the toolkit list</a>), and the water it saves is real — <a href="/home/small-leak-ripple-effect/">one drip a second is 3,000-plus gallons a year</a>.</p>
<h2>First, isolate — the rule that makes it safe</h2>
<p>Close the small isolation valves on the pipes under the tap (or the mains stopcock if there are none), then open the tap to let the standing water out and confirm it's dead. Plug the waste outlet with a cloth — not for water, but because a dropped screw down an open drain is how a ten-minute job becomes an hour. Lay parts out left to right in the order they came off: reassembly is just the film run backwards.</p>
<h2>Identify which tap you own</h2>
<p>Traditional <strong>compression</strong> taps (separate hot and cold, stiff turns) have a washer on the end of a spindle — unscrew the coloured cap, loosen the spindle, lift the headgear out, swap the washer and (while you're there) check the seat for scoring. <strong>Single-lever mixers</strong> hide a cartridge: the whole cartridge lifts out and a new one drops in — take the old one to the hardware shop and match it exactly. <strong>Ceramic-disc</strong> taps swap the disc unit the same way. <strong>Ball</strong> faucets (common in the US) use a rebuild kit with seals and springs. One trip with the old part in your pocket beats three trips with a phone photo.</p>
<h2>When to stop and call a plumber</h2>
<p>Stop when: there's no working isolation valve and the stopcock won't close either (a plumbing fault in itself — that's a call, not a wrestling match); fittings are corroded or seized (sheared spindles turn small jobs into big ones); the drip survives a full rebuild (the seat or body may be worn past repair); or the leak is from anything that isn't a visible fixture — a stain spreading on a ceiling or wall is <a href="/home/small-leak-ripple-effect/">not a tap problem, and it's on the clock</a>. And anything involving the boiler, the supply pipe coming into the house, or work inside walls belongs to a professional — the same boundary discipline as every page on this desk. (UK readers: repairing an existing tap is ordinary DIY and needs no notification — <a href="/home/uk-us-plumber-rules/">the UK/US rules guide covers the few jobs that do</a>.)</p>
<h2>The habit this job builds</h2>
<p>The sequence — isolate, open-and-verify, dismantle with your eyes, replace like-for-like, test slowly — is the same for a tap, a showerhead, a cistern flapper and most of the safe end of home plumbing. Do it once and you'll stop fearing water; fear water the right amount, and it never gets to surprise you.</p>
<p><em>Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("uk-us-plumber-rules", "guide",
"Why 'just call a plumber' means different rules in the UK and the US",
"Same trade, two countries, two completely different rulebooks — here's what each side legally expects before work starts.",
"""<p>Advice travels badly across the Atlantic. "Any handy homeowner can swap a water heater" and "you must notify the water supplier before touching a pipe" are both wrong — each in the other country. The UK and US regulate plumbing in genuinely different ways, and if you've moved, or you read forums from both sides, this is the map.</p>
<h2>The United Kingdom: a duty of compliance, notification for the big jobs</h2>
<p>England and Wales run plumbing under the Water Supply (Water Fittings) Regulations 1999 (Scotland and NI have close cousins). The legal duty sits on the owner, occupier <em>and</em> installer to ensure fittings and work comply — that applies to everything, always. What surprises people is the <strong>advance-notification</strong> list: it's narrower than rumour. Ordinary domestic work — replacing taps, a shower mixer, an outside tap, a bath under 230 litres, wash-basin taps — needs <em>no</em> notification in an existing home. The categories that do require telling your water supplier in advance include: pumps or boosters drawing more than 12 litres a minute, reverse-osmosis and some water-treatment units, bidets with ascending spray or flexible hose, RPZ backflow devices, non-household system work, new premises, and changes of a building's use. A plumber registered with a WaterSafe-approved scheme can self-certify some of those categories; failing to notify where required is enforceable. Two more hard lines: <strong>anything on gas is Gas Safe-only by law</strong> (<a href="/home/uk-boiler-servicing/">servicing, law and the CP12 are covered here</a>), and electrical work in kitchens and bathrooms falls under the wiring regulations' notification rules — <a href="/home/induction-hob-wiring/">the same notifiable-work logic as circuits</a>.</p>
<h2>The United States: licensing and permits, locally decided</h2>
<p>The US has no national plumbing rulebook — licensing and permits are set state by state and city by city. The pattern, though, is consistent: significant plumbing work requires a licensed plumber, and certain jobs require a <em>permit and inspection</em> — water-heater replacement is the classic example, required in many jurisdictions because a mis-installed heater is an explosion, scald and CO risk. Homeowner DIY on your own home is permitted in many places, often still with the permit for the big fixtures; what varies is how much the locality lets you do without a licence. Because there's no single answer, the honest rule is: before a major fixture job, one call or web check with your city's building department settles what your address requires. The federal line that <em>does</em> apply everywhere is refrigerant — <a href="/home/hvac-diy-warranty-rules/">certified people only, by law</a>.</p>
<h2>What travels, what doesn't</h2>
<p>The DIY-safe end is nearly identical in both countries: taps, showerheads, cistern flappers, visible fixtures with the water off (<a href="/home/leaky-faucet-diy/">the tap-repair guide works on both sides of the ocean</a>). The regulated end differs in mechanism but agrees in spirit: gas and major supply work belong to qualified, registered or licensed people, and the paperwork exists because water systems — like electrical ones — fail quietly and dangerously when done wrong. If you've read US advice about replacing a water heater over a weekend in the UK, or UK advice about notifying the council for a new kitchen tap in the US: now you know which forum to unfollow.</p>
<p><em>Sources: Water Supply (Water Fittings) Regulations 1999 and water-supplier guidance (including WaterSafe and Affinity Water's published notification lists); UK Gas Safety regime; US state/city licensing and permit conventions. Reviewed September 2026 · general information, not legal advice — local rules vary; check your own jurisdiction before major work.</em></p>"""),
]
