"""BRYME Home & DIY - expansion batch 19 (Sept 2026, tier-1 focus, volume 4):
six guides for NEW topics verified absent from the desk (overlap check against
live pages done pre-write): caulk vs grout, lawn-mower spring service, wasp
nest first response, pressure washer safe use, dishwasher not draining,
baby/toddler home proofing. Desk rules: general information, never
professional advice, figures only where sources support them. Body links are
root-level by convention; build-routing prefixes them with /home/."""

HOME_ROADMAP_19 = [
("caulk-vs-grout-explained", "guide",
"Caulk or grout? The rule that settles it for every bathroom joint",
"Grout is mortar and caulk is a gasket - which is why corners always crack when they are grouted. Where each belongs, which caulk to buy, and when to replace rather than patch.",
"""<p>There is one sentence that settles almost every tile-joint question in a bathroom: <b>grout is mortar, caulk is a gasket.</b> Grout is a rigid cement product that fills the gaps between tiles and takes compression. Caulk is a flexible sealant that stretches. Nearly every mistake with bathroom joints traces back to forgetting which is which.</p>
<h2>The rule: change of plane means caulk</h2>
<p>Wherever two surfaces meet at an angle - wall to wall in a corner, wall to floor, tub to wall, shower tray to tile - the joint moves. The house flexes, the tub fills and flexes, thermal expansion nudges everything. Grout in those joints has no give, so it cracks, and a cracked grout corner in a shower is a slow leak into the wall. Flexible silicone caulk is designed for exactly these joints: it moves with the surfaces and keeps the seal. Out in the field - flat tile to flat tile, mid-wall, mid-floor - nothing moves much, and that is grout's job.</p>
<h2>Which caulk, and how to apply it</h2>
<p>For wet areas buy caulk labelled <b>100% silicone</b>, or a kitchen-and-bath acrylic-latex with silicone, with mildew resistance for showers. Silicone lasts longer and flexes better but cannot be painted and needs mineral spirits for cleanup; acrylic-latex cleans with water and paints over - a fair trade where looks matter. Application matters more than brand: remove all the old, failing material first, dry the joint, wipe it down - fresh caulk over crumbling filler seals nothing. Lay one continuous bead, tool it with a fingertip within minutes, and keep it thin: a fat rope of caulk looks bad and does not adhere better. Then respect the cure time on the tube - usually about a day - before the first shower.</p>
<h2>Repair or redo</h2>
<p>Small cracked patches of field grout can be raked out and refilled to match. But hairline crack networks along a line, grout that sounds hollow under a tap, or a corner that has cracked twice before: patching is decorating a problem - the joint keeps moving, so it needs to be caulked, or something underneath needs attention. Water behind tile does not announce itself; by the time you can see staining or smell it, the repair has grown. That chain - failed seal, damp wall, mould - is why a cheap tube of caulk earns its keep, and the same logic <a href="/home/bathroom-remodel-mistakes/">the bathroom-remodel mistakes guide</a> leads with: sealing and waterproofing outrank tile choices.</p>
<h2>The maintenance habit</h2>
<p>Check the tub rim and shower corners a couple of times a year. Healthy caulk looks continuous and slightly springy; cracked, shrunken or pitted sections get removed fully - a caulk-removal tool makes this quick - cleaned, dried and re-beaded. And because a bathroom that stays damp after every shower never gives sealants a chance, pair the habit with <a href="/home/condensation-ventilation-that-works/">ventilation that actually clears the moisture</a> and walls finished in <a href="/home/humidity-and-paint/">paint that survives humid rooms</a>. Any damp that does get behind a seal needs fast attention - <a href="/home/mould-after-a-flooded-room/">the mould timeline explains why the clock starts immediately</a>.</p>"""),

("lawn-mower-care-spring-service", "maintain",
"The spring mower service: an hour that decides the whole lawn season",
"Blade sharpening, fresh fuel, a clean filter - the annual tune-up that stops most mid-summer mower failures, and the cutting-height rule that decides lawn health.",
"""<p>The first mow of the year tells you everything about how the mower was stored. The machine that sat over winter with stale fuel and a dull blade bogs down, tears the grass and spends May in a repair shop - while an hour of spring service makes the same machine boring and reliable for a whole season.</p>
<h2>The tune-up, in order</h2>
<p><b>Fuel first.</b> Old petrol is the number one spring failure: fuel left in the tank over winter gums the carburettor. Drain or run out last season's fuel (petrol storage has real rules - never indoors, and only in approved cans), fill fresh, and use fuel stabiliser if the machine will sit again. <b>Oil:</b> four-stroke engines get an oil change per season or per the manual's hours; check the level on the dipstick every few fills. <b>Air filter:</b> foam or paper, dusty after a season - wash foam, replace paper; it costs little and a choked filter mimics every other engine problem. <b>Spark plug:</b> a new one each spring is cheap insurance on a petrol mower. <b>Blade:</b> the piece that actually decides your lawn's looks - a dull blade tears rather than cuts, leaving ragged silver-tipped grass that dries out and invites disease. Remove, sharpen, and balance the blade (or swap to the spare while one is sharpened); disconnect the spark plug lead first so the engine cannot turn over while hands are near the blade.</p>
<h2>The cutting rule that matters more than the machine</h2>
<p>Turf guidance across every gardening authority converges on one rule: never remove more than about a third of the grass height in one cut. Scalping the lawn weakens the roots, invites moss and weeds, and browns the yard exactly when you want it green - and the higher summer cut shades the soil, which slows the evaporation that thins a lawn in hot weeks. Mow dry grass where possible - wet cuts tear and clump - and sweep the lawn of stones and sticks first, for the lawn's sake and the blade's.</p>
<h2>Battery and corded mowers</h2>
<p>The same spring hour applies minus the fuel: charge and inspect the battery (store batteries cool and partly charged over winter, per the manual), check the cable and plug on corded machines, and sharpen the blade - electric mowers cut cleanly when sharp and tear exactly like petrol ones when not. Corded machines get an RCD/residual-current plug in damp gardens as a matter of course. And whatever the power source, the routine still earns its slot in <a href="/home/spring-home-reset/">the spring home reset</a>, alongside the year's first <a href="/home/gutter-cleaning-damage/">gutter check</a>.</p>
<p>Close the season the same way: run the fuel out or add stabiliser before the machine goes to the shed, wipe the deck clean of clippings, and the spring hour gets shorter every year. The mower and the <a href="/home/outdoor-cooking-safety/">barbecue</a> then wake up together each summer - both inspected, both boring - and the yard looks after itself, all the way into <a href="/home/autumn-home-preparation/">the autumn wind-down</a>.</p>"""),

("wasp-nest-first-response", "guide",
"A wasp nest appeared: the calm first response",
"The size-and-location sorting that decides between a foam spray at dusk and a professional call, why you never seal the entrance, and the allergy line that ends all debate.",
"""<p>Wasp season starts with a queen in spring and builds to a full colony by late summer - and the paper golf ball under the eaves in June is a small problem, while the same nest in August is a small city. Which is why the right first response is mostly about timing and honesty about scale.</p>
<h2>First, the sorting questions</h2>
<p><b>Where is it?</b> A nest hanging in the open - under an eave, in a hedge, on a shed beam - is the only kind a homeowner should ever consider treating, and only while it is small (roughly tennis-ball size or less, early in the season). A nest in a wall cavity, a loft deep beyond view, underground in a lawn, or inside anything with an entrance you cannot see fully out of is professional territory, full stop. <b>How big?</b> Anything beyond the early golf-to-tennis-ball stage has hundreds of workers and a defence response to match. <b>Who lives nearby?</b> Anyone with a known wasp or bee-sting allergy changes the entire calculation: do not attempt anything yourself - the treatment is professional, urgently, and the household learns where the nest is from a safe distance. A sting in the mouth or throat, or any breathing difficulty after a sting, is an emergency call, not a watch-and-wait.</p>
<h2>If it is genuinely small, open, and early</h2>
<p>Wasp-nest foam sprays exist for exactly this case, and the label is the law: treat at dusk or dawn when the colony is inside and slow, from a measured distance, with an exit route behind you and nobody else in the garden. One treatment usually clears a small nest; leave it for a day, watch from a distance, and repeat once if activity persists. Never stand on a ladder to reach a nest - a startled colony and a wobbly ladder is the worst possible combination; if you cannot reach it from the ground, it is a professional's job. Wear covered clothing, not shorts and sandals.</p>
<h2>What never to do</h2>
<p><b>Never seal the entrance while the nest is alive.</b> Block a wall-cavity entrance and the colony chews a new exit - inward, through plasterboard, into the house. <b>Never flood it with a hose or set it alight</b> - the classics both end with a swarm and a story you do not want. <b>Do not knock it down</b> "to see what happens": the colony rebuilds, angrier, somewhere worse. And leave autumn nests alone altogether: a nest that has gone quiet by late autumn is finished forever - wasps never reuse a paper nest - and it can be removed casually in winter.</p>
<h2>After, and prevention</h2>
<p>Once a nest is dead, it can be scraped off and binned; the spot gets a wash. Prevention next spring is mostly about inspection - queens probe eaves, shed corners and airbricks in April, and a tennis-ball nest found in May is a five-minute job while the same nest in August is a professional's afternoon. Walk the outside line the way <a href="/home/ignore-single-pest-sighting/">the calm one-sighting rule</a> suggests, keep bins lidded and fruit fallen (wasps are sugar hunters by late summer - the <a href="/home/ants-in-the-kitchen/">kitchen ant discipline</a> works on them too), and let the honest sorting in <a href="/home/diy-vs-professional-pests/">the DIY-or-professional guide</a> make the call whenever the nest is more than a decoration-sized paper ball. If a treatment has already happened, <a href="/home/after-pest-treatment/">what to expect afterwards</a> covers the cleanup and the re-entry timetable.</p>"""),

("pressure-washer-safe-use", "understand",
"Pressure washers: what they clean well, and what they quietly destroy",
"The nozzle-distance rules that stop a washer carving concrete and stripping render, the surfaces to keep the machine away from, and the prep that makes the job fast.",
"""<p>A pressure washer is the most misused tool in the garden shed, and the damage it does is quiet: mortar joints grooved by a narrow jet, render stripped to patches, deck boards furred into splinters, window seals blown. The machine is genuinely excellent - within a narrow set of rules about distance, angle and nozzle. Those rules are all one idea: the jet's cutting power falls off explosively with distance, and everything about safe use is staying on the right side of that curve.</p>
<h2>The nozzle-distance discipline</h2>
<p>Start every job with the widest fan nozzle and the nozzle at arm's length from the surface, then work closer only until the dirt lifts. The narrow red pencil jets are for metal and stone stains at point-blank range in expert hands - they will carve grooves into concrete, gouge timber and shatter mortar, so treat them as tools you own but do not use. Hold the jet at a shallow-ish angle to the surface rather than dead-on: it gets under dirt instead of drilling into the material. Keep the jet always moving - a stationary jet in one spot for three seconds is how stripes and scars happen - and never wash downward across a joint you do not want water forced into.</p>
<h2>What stays off the list</h2>
<p>Painted render and aged pointing (the jet strips or blasts out what took a tradesman hours), asphalt roofs - loose granules gone for good - car paint at close range, anything electrical, and window glazing seals. Old soft deck timber washes into fuzz; use the widest fan, the right deck cleaner, and accept a gentle touch. And never operate the machine from a ladder: the kick when the trigger pulls, aimed wrong, is a fall waiting to happen - wash ground-level surfaces and use a telescopic lance for the rest, feet on the ground.</p>
<h2>The prep that makes it fast and safe</h2>
<p>Close windows and doors on the wall being washed; sweep first so the jet is not firing grit like sandpaper; cover soft plants and give the lawn a pre-soak so detergent does not burn roots; and keep detergents to the washer's own low-pressure detergent nozzle, applied then rinsed - never through the high-pressure jet. After any pre-paint wash, the clock matters more than the shine: timber and masonry must dry fully before paint or stain goes on, which is the whole subject of <a href="/home/painting-over-damp/">painting over damp</a> - wash in dry weather, wait the honest number of dry days, then paint.</p>
<p>Used this way the washer earns its garage space twice a year: paths and patios in spring, walls and fences before winter - slots that fit naturally into <a href="/home/spring-home-reset/">the spring reset</a> and <a href="/home/autumn-home-preparation/">the autumn checklist</a>. For anything the jet cannot reach or should not touch - high walls, fragile roofs, anything structural - the professional-window has the same logic as <a href="/home/fence-shed-insurance/">the fence-and-shed maintenance questions</a>: the machine is for surfaces you can stand next to, and everything else is a ladder-and-expertise problem.</p>"""),

("dishwasher-not-draining-first-checks", "guide",
"Dishwasher not draining? The five checks before you call anyone",
"From the filter full of graveyard debris to the disposal plug nobody knocked out, most standing-water calls are owner-fixable in twenty minutes.",
"""<p>Opening the dishwasher to a inch of yesterday's water is a grim moment, but it is usually a twenty-minute fix with a towel and a torch. Work the checks in order - they run from most-likely-and-free to call-a-technician.</p>
<h2>The five checks, in order</h2>
<p><b>1. The filter.</b> The basket in the floor of the machine is the number one cause: twist it out, rinse it under a hot tap with an old toothbrush, and be honest about how long it has been - a filter clogged past recognition slows drainage for weeks before it stops it. This is a monthly habit, not an emergency move (the same discipline as the machine's other consumables - <a href="/home/dishwasher-loading-mistakes/">loading it right</a> prevents half of these clogs in the first place, and <a href="/home/vinegar-in-the-dishwasher/">the vinegar clean</a> handles the grease film a filter cannot reach).</p>
<p><b>2. The drain hose.</b> Pull the machine out enough to see the corrugated hose running to the sink plumbing: kinks happen when a machine is pushed back after cleaning. Straighten it and run a rinse cycle.</p>
<p><b>3. The sink side.</b> If the sink drains slowly too, the blockage is downstream of both - the sink trap or the standpipe, not the dishwasher. Clear the sink first (the machine often "recovers" instantly once its exit is open). If the machine drains into a waste disposal, run the disposal fully first - a blocked disposal backs the dishwasher up, and on a brand-new installation check the metal knockout plug inside the disposal's inlet was actually knocked out: it is the classic "new dishwasher doesn't drain at all" cause.</p>
<p><b>4. The air gap or high loop.</b> Some installs have a small cylinder beside the tap (the air gap) that clogs with debris - unscrew the cap and rinse it. Installations without one rely on the drain hose looping high under the sink; a hose that has sagged lets sink water flow back in, which looks exactly like a drainage failure.</p>
<p><b>5. Listen at the end of a cycle.</b> A hum with no drain action, grinding, or clicking-then-nothing points at the drain pump - genuinely a technician's part. Note the sound and the cycle stage; that description is worth more than the model number when booking.</p>
<h2>While the water is standing</h2>
<p>Scoop or towel out the worst rather than running another cycle over it, and skip the temptation to chemical-flood the machine with harsh drain unblockers - they sit in the sump with your dishes' next cycle. And keep perspective on urgency: a dishwasher standing full is an inconvenience, not a flood - the same cannot be said of its sibling failure, <a href="/home/washing-machine-wont-drain/">a washer that will not drain mid-cycle</a>, where the water volume is ten times bigger. When the machine is old and the pump is the verdict, that is exactly the moment for <a href="/home/repair-or-replace-appliances/">the repair-or-replace arithmetic</a> - pump repairs on a fifteen-year-old machine rarely make sense.</p>
<p>Twenty minutes, in order, and the machine either runs clean again for free or you hand the technician a one-line diagnosis instead of a mystery.</p>"""),

("baby-toddler-home-proofing", "guide",
"Baby-proofing the honest way: the six fixes that matter most",
"Anchors before gadgets: the small set of home changes that safety agencies keep repeating, the ages each matters from, and what is genuinely skippable.",
"""<p>Baby-proofing is sold as an aisle of gadgets, but the effective version is closer to a building inspection than a shopping trip. Safety agencies' guidance converges on a short list of big-ticket hazards - falls, tip-overs, poisoning, burning, strangulation, drowning - and the home changes that address them are mostly hardware-store cheap. Work top to bottom while thinking at crawling and climbing height.</p>
<h2>The six that matter most</h2>
<p><b>1. Anchor the furniture and the TV.</b> Chests of drawers, bookcases and old televisions are the heavyweight of home child-injury statistics - climbers pull drawers open as a ladder, and a tipping dresser does not give a toddler a second chance. Anchor straps into studs cost little and take twenty minutes per piece; the TV goes low or strapped. This is the single most important item on the list, and the one gadgets cannot substitute for.</p>
<p><b>2. Gates on the stairs.</b> Wall-mounted (pressure-fit) gates at top and bottom, closed, every time - the stair fall is the classic nursery-ward admission. <b>3. Window and blind cords.</b> Looped cords are a silent strangulation hazard: cut the loops or hook cords high and short, and move cots, chairs and climbable furniture away from windows.</p>
<p><b>4. Locks where the poisons live.</b> Cleaning products, dishwasher and laundry tablets (the colourful ones look like sweets), medicines, and vitamins all move up, high, and behind a latch - and the garage and shed count. <b>5. Heat, on both ends.</b> Turn the water-heater temperature down to the level safety agencies recommend so a tap cannot scald, and put a kettle-to-the-back habit in place alongside pan handles turned in - <a href="/home/water-heater-explained/">the water heater's temperature setting</a> is a two-minute check with real upside.</p>
<p><b>6. The electrical layer, properly.</b> Socket covers to current safety standards are fine, but the bigger electrical risks are trailing leads a climber can yank (they pull lamps and appliances down) and overloaded extension blocks behind the sofa - the household's own <a href="/home/outlet-overloading-danger/">outlet-overloading check</a> and a walk through <a href="/home/electrical-fire-warning-signs/">the electrical warning signs</a> do double duty for small hands. Test the smoke and carbon-monoxide alarms while you are in safety mode - expiry dates are real, and <a href="/home/co-smoke-alarm-expiry/">the alarm-expiry guide</a> covers what to look for.</p>
<h2>What is genuinely skippable</h2>
<p>Every family is different, but the honest pattern: cupboard latches everywhere is a low-yield buy compared to one good lock on the poison cabinet; "smart" gadgets that alarm after contact solve problems the layout could have avoided; and a spotless house proves little - supervision beats gadgets, and the layout does the supervising when you cannot. Water is the standing exception to every schedule: a baby or toddler and an open bathroom, bucket, or paddling pool is a same-second hazard, always. And keep a <a href="/home/basic-toolkit-checklist/">basic toolkit</a> in the house - the anchoring, gating and latching jobs are all twenty-minute screws-and-drill work, and a home that gets small fixes done fast stays a step ahead of a child who gets faster every week.</p>"""),
]
