# BRYME Home & DIY — roadmap batch 12: appliance intelligence (3). Batch 32, 11 Sep 2026.
# Master Pack §3.2.3 six-part spec: what the machine does · common symptoms · maintenance ·
# energy considerations · warning signs · when repair is unsafe. Safety stops stated absolutely.

HOME_ROADMAP_12 = [
("microwave-oven-care-and-safety", "guide",
"The microwave: how it works, what the symptoms mean, and the one line you never cross",
"Sparks, weak heat, a cold plate and a damaged door — the honest diagnostics, plus the repair boundary that keeps the one dangerous appliance honest.",
"""<p>The microwave is the most-used and least-understood machine in the kitchen. It works by a magnetron generating radio waves that make water molecules vibrate — heating the food, not the air around it — which is why plates stay cool and why the machine cares so much about its door. General information only: microwaves are one of the few household appliances this desk treats as <b>never DIY-repairable</b>, and this page keeps that line visible.</p>
<h2>Common symptoms, read honestly</h2>
<p><b>Weak or uneven heating:</b> first suspect is the user, not the machine — lower wattage than a recipe assumes, single portion in the middle of a big plate, or the stirrer/turntable stuck. Clean the roller ring and confirm the plate turns; if heating is still weak across tests, the magnetron is fading, and the economics point to replacement. <b>The plate doesn't turn:</b> roller ring mis-seated or motor worn — the first is a ten-second fix, the second a cheap-part repair only worth it on a good machine. <b>Loud then quiet:</b> the cooling fan or the turntable motor, not the magnetron; a microwave that runs hot-smelling is telling you something else.</p>
<h2>Maintenance that is genuinely yours</h2>
<p>Clean spills when they happen — carbonised food absorbs energy and creates hot spots that damage the interior. Wipe the door seal and check it visually: the seal and hinge are the safety-critical parts. Never run it empty (the energy has nowhere to go), and never in metal or foil. A bowl of water with lemon steamed for two minutes, then a wipe, is the whole deep-clean.</p>
<h2>Energy considerations</h2>
<p>Microwaves are efficient for their job — small portions and reheat beat the oven on energy by a wide margin because they heat the food directly and don't preheat a cavity. The honest comparison and the wider bill logic live in <a href="/home/energy-bill-high-unchanged/">why the bill is high when nothing changed</a>.</p>
<h2>Warning signs and the absolute line</h2>
<p><b>Sparking or arcing inside, a burnt smell, scorch marks on the interior, or a door that is bent, dropped, or doesn't close flush:</b> stop using the machine. Those are the warning signs — and this page's hard line follows them: <b>never open or repair a microwave yourself.</b> The capacitor inside can hold a lethal charge long after unplugging; this is the clearest "call a professional or replace it" case in the home, up there with the boundaries in <a href="/home/us-diy-electrical-rules/">DIY electrical rules</a> and <a href="/home/why-does-my-circuit-breaker-keep-tripping/">what a tripping breaker means</a>. The machine is cheap; you are not.</p>"""),
("water-heater-explained", "guide",
"The water heater, explained before it fails",
"Tank vs tankless, the symptoms that forecast failure, the two safe maintenance moves, and the checks that belong to professionals only.",
"""<p>The water heater hides in a cupboard or a basement and is ignored until a cold shower announces it. General information only — and this page is upfront that almost everything beyond observation and two safe settings belongs to licensed professionals, especially on gas.</p>
<h2>What the machine does</h2>
<p>A tank heater stores and reheats a reservoir (typically 100–300 litres / 30–80 gallons) against a thermostat; a tankless unit heats on flow. Tanks fail the way batteries do — slowly, then suddenly — because sediment accumulates and the tank corrodes from the inside. Tankless units shift the failure points to scale on the heat exchanger and flow sensors.</p>
<h2>Symptoms that forecast failure</h2>
<p><b>Rumbling or popping</b> during heating = sediment layer hardening on the tank floor. <b>Rusty or metallic hot water</b> = the anode rod is spent and the tank is corroding. <b>Hot water running out faster each month</b> = sediment displacing capacity or a failing element. <b>Moisture or rust streaks at the tank base</b> = the end stage; a leaking tank is not repaired, it is replaced. Any of these deserve a professional look — scheduling one on your calendar beats an emergency callout, which is the whole thesis of <a href="/home/someday-maintenance-cost/">the someday-cost rule</a>.</p>
<h2>The two moves that are safely yours</h2>
<p>One: <b>check the thermostat setting</b> — around 49&nbsp;°C / 120&nbsp;°F is the widely advised balance of scald-safety and efficiency (checked 11 September 2026; US DOE guidance) — higher settings burn money and skin. Two: <b>the annual-ish flush</b> — draining a few litres from the drain valve until it runs clear, per your unit's manual — slows sediment honestly. Anything inside the machine — elements, anodes, gas valves, the temperature-and-pressure relief valve — is professional territory, full stop: gas work legally requires a registered engineer (UK readers: <a href="/home/uk-boiler-servicing/">what a proper service includes</a>), and the T&amp;P valve is a safety device, not a maintenance item.</p>
<h2>Energy and the honest verdict</h2>
<p>Water heating is one of a home's largest energy uses, so the setting check alone pays. Tankless suits low-to-moderate simultaneous demand; tanks suit simple replacement budgets. And if the heater lives where a leak would be expensive — above living space, near electrics — a catch pan and a checked drain are cheap insurance in the spirit of <a href="/home/small-leak-ripple-effect/">the ripple-effect guide</a>. Bottom line: observe yearly, set the temperature once, flush gently, and let a licensed professional touch everything else.</p>"""),
("vacuum-cleaner-care-guide", "guide",
"Vacuum cleaners: why yours lost suction, and how to keep the next one strong",
"The clog-path diagnostic, the filter-drying rule, the brush-roll haircut, and the honest buy-it-once argument.",
"""<p>Vacuum cleaners rarely die; they are usually suffocated. Loss of suction is a blocked air path, not a broken motor — which makes the vacuum the most repairable machine in the house and the easiest to keep running for a decade. General information; unplug before any of it.</p>
<h2>What the machine does, briefly</h2>
<p>A fan creates negative pressure; air rushes in through the head, carrying dirt to a bag or cyclone, and out through filters. Every problem a vacuum has is one of those three stations: air in (the head and hose), dirt out (the bag/bin), or filters.</p>
<h2>Symptoms: the clog-path diagnostic, in order</h2>
<p><b>Loss of suction:</b> 1) bin or bag full — empty early, not at the brim (cyclones need headroom to spin); 2) filters clogged — wash foam filters per the manual and let them dry <b>completely</b> (24 hours; a damp filter is how motors get ruined and mould gets a home — the drying discipline from <a href="/home/condensation-ventilation-that-works/">the condensation guide</a> applies); 3) brush roll choked — scissors along the groove for wrapped hair and thread (the sixty-second haircut that fixes "the vacuum pushes but doesn't pick up"); 4) hose blockage — a broom handle gently through, working from both ends; 5) head height set wrong for bare floors. Nine losses in ten die somewhere on that list.</p>
<h2>Warning signs and the stop line</h2>
<p><b>A burning smell, or the motor cutting out on its own</b> (thermal cutoff): stop, unplug, clear every blockage and filter, and let it cool — if the smell returns on a clean machine, the motor is done; weigh repair against the <a href="/home/someday-maintenance-cost/">someday-cost rule</a>. A damaged cord or plug is a replacement or professional repair, never a tape job — the same hard line as <a href="/home/us-diy-electrical-rules/">the electrical rules</a>.</p>
<h2>Energy and the buy-it-once case</h2>
<p>Vacuums cost little to run but the buying logic matters: bags hold filtration advantage, bagless cost nothing in consumables, robots need their brushes and sensors pampered weekly. The honest case — buy a modest, repairable machine and service it yearly — is the appliance version of <a href="/home/season-cast-iron-pan/">the cast-iron philosophy</a>: maintained, the good one outlives three cheap ones, which is also the quiet argument in <a href="/home/emergency-repair-fund/">the repair-fund rule</a>.</p>"""),
]
