# BRYME Home & DIY — roadmap batch 4: Painting & interior (3) + Electrical safety (2).
# YMYL-verified 2026-09-10: NFPA electrical-fire estimate (32,620/yr, 2015-2019); Electrical
# Safety First socket-overload guidance (13A rule, danger signs); paint manufacturer humidity
# bands (40-50% RH ideal; >60-70% slows cure). See docs/ecosystem/home-article-roadmap.md.

HOME_ROADMAP_4 = [
("interior-painting-mistakes", "guide",
"Interior painting mistakes: the full list, and what each one really costs",
"Beyond the prep everyone skips: the roller, the coat timing, the tape and the lighting — every mistake here costs a redo, and redos cost double.",
"""<p>Painting is the most attempted and least respected trade in the home — it looks like none of the skill matters right up until the lap marks show in evening light. This is the full tour of the mistakes that separate a job you're proud of from one you repaint in two years. The deepest one — skipping prep entirely — has <a href="/home/mistakes/painting-without-prep/">its own piece on the common-mistakes shelf</a>; start there if you only read one.</p>
<h2>The coat-timing mistakes</h2>
<p><strong>Recoating too soon</strong> is the classic. The surface can feel dry hours before the film underneath has cured; a second coat laid on soft first paint drags, peels the edges of coat one, and can stay tacky for days. The tin's recoat time is a real specification, not a suggestion — and in a humid or cold room, stretch it (<a href="/home/humidity-and-paint/">humidity is its own chapter</a>). <strong>Painting at night and judging nothing</strong> is the quiet cousin: artificial light hides lap marks, thin spots and misses that daylight exposes ruthlessly. Check your work with a bright light raked across the wall before the second coat, not after the third.</p>
<h2>The roller mistakes</h2>
<p>A cheap or wrong-nap roller sheds fuzz into the finish and skips texture; a half-loaded roller paints streaks and forces extra coats. Load the roller properly (a ridged tray, not a puddle), work in a W pattern to spread, then fill it without lifting — and keep a wet edge, overlapping each pass before the last one dries. Lap marks are the fingerprint of working too slowly over too large an area, one wall at a time beats one corner of four walls. And press lightly: leaning on a roller squeezes paint into ridges and drips that sanding later won't excuse.</p>
<h2>The tape, the cutting-in, the thinning</h2>
<p><strong>Masking tape left on too long</strong> becomes part of the wall — remove it while the final coat is still slightly tacky, pulling back on itself at a shallow angle, or score the edge with a blade first. <strong>Cutting-in with too much paint</strong> leaves a thick, uneven border that flashes differently from the rolled field; less paint on the brush, steady hand, and cut in one wall at a time so edges stay wet when you roll. <strong>Over-thinning</strong> to make paint go further produces a film too thin to hide or protect — if the paint needs thinning at all, the tin says by how much, and "more water, more coats" is the opposite of economy.</p>
<h2>The room mistakes</h2>
<p>Skip the degreasing in a kitchen and the paint lifts where hands touch the wall. Paint a bathroom without checking the extraction and the steam undoes the finish within months — <a href="/home/condensation-ventilation-that-works/">ventilation is a system, not a window</a>. Paint over a damp patch and watch the new paint blister off with the old — <a href="/home/painting-over-damp/">why that never works is its own guide</a>. And move the furniture out, not to the middle: dust settles on drying paint, and a room you can walk around is a room you can cut in properly.</p>
<h2>The honest cost</h2>
<p>Every mistake on this page has the same price: doing it twice. Two weekend days and a second tin versus one careful hour of prep, a decent roller, and patience between coats — that arithmetic is the whole argument. The <a href="/home/basic-toolkit-checklist/">toolkit list</a> covers what actually earns its place, and if the job keeps revealing problems bigger than paint — stains that bleed through, walls that crumble — that's the house telling you the job isn't paint.</p>
<p><em>Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("humidity-and-paint", "guide",
"Why humidity ruins paint jobs (and what to check before you start)",
"Humidity decides whether paint cures into a film or stays a sticky compromise — and the check costs less than the redo.",
"""<p>Paint doesn't dry by magic — water or solvent has to leave the film for the resin to knit into a proper surface. Humidity is the variable that controls that exit, which is why the same paint, same wall and same painter produce a beautiful finish in October and a tacky disappointment in August. Professional painters check humidity the way sailors check tide tables.</p>
<h2>What high humidity actually does</h2>
<p>When the air is already full of moisture, evaporation slows to a crawl — and slow drying is not just slower, it's weaker. The film stays open and soft longer, collecting dust; water-based paints can blush (a milky haze); and recoat windows stretch enormously — working guidance puts a latex recoat at around four hours in moderate conditions but a day or more when relative humidity climbs past 60-70%. The finish that results from a rush in those conditions is the failure painters know best: poor adhesion, lap marks set in permanently, and a surface that scuffs a year early. Manufacturer guidance generally lands in the same band: aim for roughly 40-50% relative humidity and the 10-29°C (50-85°F) range the tin specifies, and treat anything much above 70% RH as a "postpone" sign.</p>
<h2>The check before you start</h2>
<p>Buy a small hygrometer — a few pounds or dollars — and put it in the room an hour before you open the tin. If you're mid-<a href="/home/condensation-ventilation-that-works/">ventilation problems</a> or the room was recently a <a href="/home/condensation-vs-rising-vs-penetrating-damp/">damp diagnosis</a>, measure again on the wall itself: a cold, damp wall reads worse than the room air, and <a href="/home/painting-over-damp/">painting over it fails no matter what the weather is doing</a>. Outdoors, check the dew point too — condensation forms on surfaces at or near it even on dry-feeling days, and pro guidance says keep surface temperature comfortably above the dew point.</p>
<h2>If the day isn't cooperating</h2>
<p>Indoors, you can make the air cooperate instead: heating the room gently (a cold room is a humid room at the surface) and running a dehumidifier or the HVAC pulls the room into the workable band; air movement from a fan — not pointed at the wet paint, but moving the room's air — helps evaporation keep pace. Outdoors, the honest move is scheduling: morning after the dew has burned off, or wait. Paint additive can rescue borderline days, but it's medicine, not a weather machine.</p>
<h2>The low-humidity footnote</h2>
<p>Very dry air (below ~30% RH) fails from the other side — the surface skins over before the film underneath has levelled, trapping solvent and telegraphing brush marks. The lesson isn't "moisture bad"; it's that paint wants the middle of the range, and the hygrometer tells you where you are. Ten seconds with one instrument beats a weekend of arguing with a finish that never asked to be applied that day.</p>
<p><em>Sources: paint manufacturer application guidance (temperature/RH windows, recoat times) and professional-painter working guidance, converging on 40-50% RH ideal, >60-70%RH problem territory. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("painting-over-damp", "guide",
"Painting over damp: why it never actually works",
"Damp under paint isn't hidden — it's pressurised. The moisture pushes the film off the wall, and it takes your weekend with it.",
"""<p>There's a specific moment every painter of an old house meets: a patch of wall that looks stained or powdery, and the overwhelming temptation to let the paint — maybe two coats, maybe stain-block — deal with it. Painting over damp is the most reliably failed job in decorating, and the failure isn't bad luck. It's physics, working slowly.</p>
<h2>Why the paint can't stay</h2>
<p>Paint forms a film that clings to the surface beneath it. Damp in a wall is water <em>moving</em> — from the masonry toward the air — and a paint film is exactly the barrier that movement doesn't want. Pressure builds behind the film: moisture pushes from the inside, adhesion loses from the outside, and the result is the familiar menu of blistering, flaking, peeling in sheets, and dark patches blooming through within months. The paint didn't fail; it was assigned a job that isn't paint's — <a href="/home/condensation-vs-rising-vs-penetrating-damp/">and the damp itself has a diagnosis</a> that matters more than any tin.</p>
<h2>The worse problem: damp you've sealed in</h2>
<p>Blistering paint is the cosmetic bill. The structural one is slower: a sealed surface traps moisture in the wall, where it salts, crumbles plaster and feeds mould out of sight. In older solid-wall homes especially, walls were designed to breathe — moisture arriving gets out through permeable plaster and finishes. Modern impermeable paint over a damp wall stops the breathing and turns a damp problem into a rotting problem. That's why heritage guidance leans on breathable finishes (limewash, mineral paints) for old solid walls — and why "just seal it" is advice that should be charged for, never followed free.</p>
<h2>The order that works</h2>
<p>Diagnose first (<a href="/home/condensation-vs-rising-vs-penetrating-damp/">condensation, rising or penetrating — the foil test picks</a>), fix the cause — <a href="/home/condensation-ventilation-that-works/">ventilation and heating for condensation</a>, a builder or roofer for the leaks — let the wall dry properly, <em>then</em> decorate with a finish appropriate to the wall. If you're renting, don't decorate over it at all: damp from a building defect is the landlord's repair, and painting over it can genuinely complicate your position — report it in writing instead (<a href="/home/uk-landlord-damp-mould-duties/">the duties guide has the current law</a>).</p>
<h2>And the patch that isn't damp at all</h2>
<p>Sometimes the stain is water's history, not its present — an old leak long repaired leaves a brown halo that bleeds through every coat. That <em>is</em> paint's job: a stain-blocking primer seals it, then decorate. The distinction is the test: a dry, stable, repaired stain can be sealed over; anything that grows, returns with rain, or sits cold to the touch is live, and paint on it is money in a fountain.</p>
<p><em>Sources: property-preservation trade guidance and heritage/conservation breathable-finish conventions. Reviewed September 2026 · general information, not professional advice.</em></p>"""),

("electrical-fire-warning-signs", "guide",
"Electrical fires: the warning signs your house is already showing you",
"US homes average more than 32,000 electrical-distribution fires a year — and the failures announce themselves weeks early to anyone who knows the signs.",
"""<p>Electrical failure is one of the leading causes of home structure fires. The US Fire Administration's and NFPA's national estimates put home fires involving electrical distribution or lighting equipment at an average of roughly 32,600 a year — about 430 deaths and $1.3 billion in damage annually, with wiring and related equipment the majority of it, and cords and plugs — just a tenth of the fires — causing more than a quarter of the deaths. The number behind all of this that matters most: these failures almost never arrive unannounced. The warning signs are on show for weeks, and knowing them is the whole difference.</p>
<h2>The signs, from subtle to urgent</h2>
<p><strong>A burning or fishy smell</strong> near a socket, switch or appliance with no obvious source is the classic early one — overheating plastic and insulation smell distinctly chemical (that fishy odour is real, and fire services repeatedly warn about it). <strong>Discolouration, scorch marks or blackening</strong> around outlets, switch plates or plugs: the arcing has already started. <strong>Warm or hot faceplates, plugs or cords</strong> — a socket that's anything beyond room temperature is working beyond what it was designed for. <strong>Flickering or dimming lights</strong>, especially when large appliances cut in, say a circuit is strained or a connection is loose. <strong>Buzzing</strong> from a socket, switch or the consumer unit is electricity going somewhere it shouldn't. <strong>Breakers tripping repeatedly</strong> — <a href="/home/why-does-my-circuit-breaker-keep-tripping/">the breaker is doing its job; a breaker that keeps doing it is a message</a>.</p>
<h2>What to do when you find one</h2>
<p>The safe part is genuinely DIY: stop using the socket, switch or appliance immediately and unplug what you safely can at the wall (never pull a hot or sparking plug by the cord — switch off at the breaker first if there's any heat or sparking). Feel warmth through the cover? Don't pull it apart — turn the circuit off at the consumer unit/breaker panel and leave it off. Then it's electrician territory, every time — <a href="/home/induction-hob-wiring/">the same line this desk draws on all wiring work</a>. If you ever see smoke or sparks: people out first, then the emergency services. Smoke alarms are the backstop for the ones nobody catches — <a href="/home/how-many-smoke-co-alarms/">count them</a> and <a href="/home/test-alarms-monthly/">test them</a>.</p>
<h2>Why these signs exist at all</h2>
<p>Nearly all of them are versions of one event: current meeting resistance it wasn't designed for — a loose terminal, a degraded insulation, an overloaded conductor (<a href="/home/outlet-overloading-danger/">often a load the household added, one plug at a time</a>). The heat builds where the metal is imperfect, and plastic, dust and wood are nearby. This is also why the "it's worked for years" defence fails: insulation ages, connections loosen, and the socket that's been warm all winter is not behaving normally.</p>
<h2>The cheap prevention stack</h2>
<p>Have the electrics of any home older than a few decades inspected by a qualified electrician on a sensible cycle (UK: the wiring regulations suggest owner-occupied homes checked at most every 10 years; rentals every 5 — your electrician confirms for your home). Don't run cords under rugs or pinched behind furniture. Replace damaged leads rather than taping them. And treat every sign above as the electrical system's courtesy — it is telling you before the fire, in the only language it has.</p>
<p><em>Sources: NFPA, Home Fires Involving Electrical Distribution and Lighting Equipment (2015-2019 averages: ~32,620 fires/yr, 430 deaths, $1.3B); UK fire-service and Electrical Safety First warning-sign guidance; UK IET Wiring Regulations inspection intervals. Reviewed September 2026 · general information, not professional advice — any suspected electrical fault belongs to a qualified electrician.</em></p>"""),

("outlet-overloading-danger", "guide",
"Why overloading a single outlet is more dangerous than it looks",
"An overloaded outlet doesn't trip, spark or shout — it warms up quietly, ages the insulation, and repeats until it doesn't get away with it.",
"""<p>Overloading an outlet is uniquely dangerous among home mistakes because it gives you almost nothing to notice. No drama, no trip, sometimes not even warmth at first — just current doing more than the conductors behind the wall were sized for, night after night. The UK's Electrical Safety First and US fire bodies put socket and lead overload high on their fire-prevention lists for exactly this reason: the failure mode is silent, cumulative, and entirely preventable by arithmetic.</p>
<h2>The arithmetic, both sides of the Atlantic</h2>
<p><strong>UK:</strong> a standard socket is rated at 13 amps — about 3,000 watts — and that budget includes everything plugged into it, including everything on an extension lead (most leads are rated 13A, older ones 10A: the rating is marked on the lead). A kettle (~3kW), a tumble dryer (~2.5-3kW) or a fan heater (~2kW) eats most or all of one socket's budget alone. <strong>US:</strong> a standard household circuit is 15 or 20 amps at 120 volts — about 1,800-2,400 watts <em>for the entire circuit</em>, which might serve six outlets in two rooms. A typical space heater draws 1,500 watts — most of a 15A circuit by itself, even before anything else joins.</p>
<h2>Why the danger hides</h2>
<p>Current through more resistance than designed makes conductors and connections warm — slowly, inside the wall or inside the lead, where nobody checks. Heat ages insulation; aged insulation leaks; leaking current makes more heat. Meanwhile the products keep working, which teaches the household that it's fine. Extension leads are the multiplier: daisy-chaining lead into lead stacks unknown load onto the thinnest cable in the chain; block adaptors without fuses do the same to a single socket. The safe forms: one lead per socket, never lead-into-lead, bar adaptors rather than blocks, and high-wattage appliances — heaters, kettles, dryers, irons, microwaves — straight into the wall on their own, the one rule worth tattooing.</p>
<h2>The danger signs (check yours tonight)</h2>
<p>Electrical Safety First's list, and every one of these is "stop now": a smell of hot plastic near a socket or appliance; scorch marks or blackening around outlets or plugs; sparks when plugging in; leads that are frayed or show coloured wire; plugs that run warm; fuses blowing or breakers tripping "for no reason" (<a href="/home/why-does-my-circuit-breaker-keep-tripping/">there is always a reason</a>). Any of these on an overloaded socket means stop using it today, and any of them at all means <a href="/home/electrical-fire-warning-signs/">the electrician conversation is no longer optional</a>.</p>
<h2>The fix is sockets, not discipline</h2>
<p>If a corner of the house only works through a nest of extension leads, that's the house saying it needs more outlets — and installing them is registered-electrician work (<a href="/home/mistakes/drilling-without-checking/">cables and pipes hide exactly where new sockets go</a>; in the UK new circuits are notifiable, <a href="/home/induction-hob-wiring/">same rule as the induction guide</a>). Rearranging what's plugged where costs nothing tonight: heaters and kettles get their own wall sockets, IT and AV share the multi-way bar, and the daisy chain retires. The load a socket can carry was decided by an engineer; arithmetic keeps you inside it, and nobody in the house has to be lucky.</p>
<p><em>Sources: Electrical Safety First overloading-sockets guidance (13A ratings, no daisy-chaining, block vs bar adaptors, danger signs); NFPA/USFA electrical-fire prevention materials; standard US circuit ratings (15/20A @ 120V). Reviewed September 2026 · general information, not professional advice.</em></p>"""),
]
