# BRYME Home & DIY — roadmap batch 2: CO & smoke safety + Damp, mould & condensation.
# YMYL batch: legal/regulatory claims verified against named sources (see each piece's
# source line and docs/ecosystem/home-article-roadmap.md batch-2 receipts).

HOME_ROADMAP_2 = [
("uk-carbon-monoxide-alarm-law", "guide",
"UK carbon monoxide alarm law, explained without the legalese",
"England's rules since October 2022, the £5,000 penalty and how it actually triggers, and where Scotland and Wales go further.",
"""<p>Carbon monoxide law in the UK is a patchwork — England, Scotland and Wales each set their own minimums, and most summaries blur them together. Here is what is actually required, what happens if a landlord ignores it, and where the law is stricter than most people assume. (Northern Ireland's position is noted at the end.) This is general information, not legal advice — the live sources are the regulations themselves and GOV.UK.</p>
<h2>England: the rules since 1 October 2022</h2>
<p>The Smoke and Carbon Monoxide Alarm (England) Regulations 2015, as amended in 2022, put three duties on landlords of specified tenancies. First, at least one smoke alarm on every storey of the property that has a room used as living accommodation — hallways and landings count as living accommodation, storage cupboards don't. Second, a carbon monoxide alarm in any room used as living accommodation that contains a fixed combustion appliance — boiler, gas fire, wood burner — with one specific exception: a gas cooker alone doesn't trigger the requirement. Third, alarms must be tested on the day a new tenancy begins, and once a tenant reports an alarm faulty, the landlord must repair or replace it. CO alarms are expected to meet BS 50291; smoke alarms BS 5839-6. These duties apply to social landlords too since the 2022 amendment — previously the CO rule only covered solid-fuel appliances and private tenancies.</p>
<h2>The £5,000 penalty — and the step before it</h2>
<p>The fine everyone quotes has a step in front of it that most summaries skip. A council that finds a breach serves a remedial notice giving the landlord 28 days to fix it. Only if the landlord fails to comply does the council do the work itself and levy a penalty of up to £5,000 — per breach, not per portfolio. In other words: fixing a missing alarm within the notice window avoids the fine, which is exactly as it should be, but the notice itself is enforcement on the record. And no fine is the only thing at stake — the civil liability after a CO incident in a non-compliant property dwarfs any penalty.</p>
<h2>What the law does not ask — but fire services do</h2>
<p>The regulations are a floor, not a target. Nothing in the English rules requires an alarm in a room with only a gas cooker, yet cookers are a genuine CO source. Nothing requires a CO alarm near sleeping areas on every level, which is what US guidance and plain prudence suggest. And nothing stops a landlord from meeting the letter of the law with a three-year-old alarm whose sensor is nearing the end of its life — <a href="/home/co-smoke-alarm-expiry/">which is a whole subject of its own</a>.</p>
<h2>Scotland and Wales: stricter still</h2>
<p>Scotland has required interlinked alarms since February 2022 — smoke alarms in circulation spaces and the room most frequently used as a living room, a heat alarm in the kitchen, all sounding together, plus CO alarms where there is any fixed combustion appliance or flue. Wales, under the Renting Homes (Fitness for Human Habitation) requirements in force since December 2022, also goes beyond England — including where gas cookers are concerned. Check the current Welsh government guidance for the detail; the direction of travel across the UK is unmistakably toward more alarms, better interconnection, and landlord duties that bite. Northern Ireland has no equivalent landlord alarm statute — building regulations and general duties of care apply — which makes following the other nations' guidance the sensible voluntary baseline.</p>
<h2>What this means for everyone else</h2>
<p>Owner-occupiers in England have no statutory alarm duty — but building-regulations guidance expects smoke alarms in circulation spaces on each storey and a heat alarm in new or rewired kitchens, and every fire service in the country recommends CO alarms wherever fuel burns. The <a href="/home/how-many-smoke-co-alarms/">how-many-alarms guide</a> covers the recommended standard room by room, <a href="/home/mistakes/co-alarm-wrong-place/">the common-mistakes shelf</a> covers placement and expiry, and the <a href="/home/test-alarms-monthly/">monthly habit</a> makes any of it worth having. Landlords weighing up damp duties too — which are changing around the UK right now — should read <a href="/home/uk-landlord-damp-mould-duties/">the damp-and-mould duties guide</a> alongside this one.</p>
<p><em>Sources: The Smoke and Carbon Monoxide Alarm (England) Regulations 2015 and the 2022 Amendment Regulations (SI 2022/626); GOV.UK landlord guidance; Scottish Government fire and smoke alarm requirements. Last reviewed September 2026 · general information, not legal advice.</em></p>"""),

("how-many-smoke-co-alarms", "guide",
"How many smoke and CO alarms your home actually needs (US and UK)",
"The legal minimum and the recommended standard are different numbers — here is both, side by side, for the US and the UK.",
"""<p>Ask how many smoke alarms a home needs and you'll get the landlord's minimum, the fire service's recommendation, and the neighbour's opinion — all different. This page keeps the two real answers separate: what the law requires, and what fire-safety bodies actually recommend, in both the US and the UK, because they're genuinely different systems rather than the same advice with a flag swapped.</p>
<h2>The United States: the NFPA standard</h2>
<p>US guidance from the National Fire Protection Association is the most explicit in the world, and it counts by rooms, not floors: a smoke alarm <strong>inside every sleeping room</strong>, one <strong>outside each separate sleeping area</strong> (the hallway that serves the bedrooms), and <strong>at least one on every level</strong> of the home including the basement — in the living room or near the stairway on levels without bedrooms. A typical three-bedroom house lands on five or six alarms. Carbon monoxide alarms follow the same sleeping-area logic: one near where people sleep, on each level, per manufacturer placement. Dozens of US states and cities layer legal minimums on top for new builds and rentals, but the NFPA layout is what fire services actually campaign for — the inside-the-bedroom alarm is repeatedly called the most overlooked placement in the country.</p>
<h2>England: the minimum, then the standard</h2>
<p>English law for private and social rented homes is the floor: <strong>a smoke alarm on every storey</strong> used as living accommodation, a CO alarm in any room with a fixed combustion appliance (boiler, gas fire, wood burner — gas cookers excepted), tested at each new tenancy. Owner-occupiers have no statutory minimum, but building-regulations guidance for new or refurbished homes expects alarms in the circulation spaces of each storey, a heat alarm in the kitchen, and alarms powered from the mains with battery backup. The British standard for domestic systems (BS 5839-6) grades what "properly covered" means — and under it, the modern recommendation for most homes looks a lot like the NFPA's: detection on every level, in the escape routes, and in the rooms where fires actually start, with the kitchen protected by a heat alarm rather than a smoke alarm so it doesn't cry wolf.</p>
<h2>Scotland: the strictest in the UK</h2>
<p>Since February 2022 every Scottish home — owned or rented — has been expected to meet one standard: <strong>interlinked</strong> smoke alarms in hallways and landings (every circulation space), one in the room most often used as a living room, a heat alarm in the kitchen, all sounding together so one fire alerts the whole house, plus a CO alarm where there is a fixed combustion appliance or flue. If you upgrade anywhere in the UK, the Scottish layout is the benchmark worth copying — interconnection is the single feature that changes outcomes, because a fire at night in the kitchen reaches sleeping bedrooms as an alarm, not as smoke.</p>
<h2>The shared principle</h2>
<p>Every one of these systems is converging on the same idea: put an alarm between the likely fire and the sleeping people, and make them all shout together. Count yours tonight — one per storey is the legal minimum in English rentals and the wrong answer for a family home. Then check the dates on their backs (<a href="/home/co-smoke-alarm-expiry/">alarms expire — here's how to read them</a>), test what you have (<a href="/home/test-alarms-monthly/">the monthly habit</a>), and place the CO units where they can actually work (<a href="/home/mistakes/co-alarm-wrong-place/">placement is its own mistake piece</a>). Landlords in England wanting the exact legal wording should read <a href="/home/uk-carbon-monoxide-alarm-law/">the alarm-law guide</a>.</p>
<p><em>Sources: NFPA smoke and CO alarm guidance; GOV.UK landlord guidance (England); Scottish Government fire and smoke alarms requirements; BS 5839-6 grading as summarised by fire-safety bodies. Last reviewed September 2026 · general information, not professional advice.</em></p>"""),

("co-smoke-alarm-expiry", "guide",
"The expiry date nobody reads: your alarms have a shelf life",
"Smoke alarms retire at ten years, CO sensors often sooner — and the test button can't tell you any of it.",
"""<p>There is a date printed on the back of every smoke and CO alarm in your home, and almost nobody has ever read it. Not an installation date — a retire-by date. Alarms are sensors, sensors are consumables, and an alarm past its life can chirp cheerfully on test while detecting progressively less every year.</p>
<h2>Smoke alarms: ten years, from manufacture</h2>
<p>Fire-safety guidance across the US and UK converges on the same number: replace smoke alarms after <strong>ten years from the date of manufacture</strong> — which is printed or stamped on the base, and can be years before you bought it. Warehouse stock sits on shelves; a "new" alarm can already be two or three years into its life. Inside the chamber, dust and contaminants degrade the sensor's sensitivity even in an alarm that has never once gone off. The failure mode is the cruel one: the alarm still beeps on test, so it feels reliable, while the margin it would need to wake you at 3am has quietly eroded.</p>
<h2>CO sensors: the shorter clock</h2>
<p>Carbon monoxide alarms use electrochemical cells that deplete by design — the sensor is a chemical reaction running down, and its working life is typically in the five-to-ten-year band depending on the maker. The replace-by or replace-on date is printed on the body; when it passes, the whole unit is replaced, because on domestic alarms the sensor isn't a serviceable part. Combination smoke-plus-CO units follow the shorter of the two lives — which means a "10-year" combination alarm is usually governed by its CO cell, not its smoke side. If yours has never been opened from its box... it still expires: the clock runs from manufacture.</p>
<h2>The signs you've already left it late</h2>
<p>An end-of-life chirp is different from a low-battery chirp — three beeps repeating means smoke or CO and everyone gets out; a single periodic chirp usually means battery; but a chirp that persists after a fresh battery on an older unit is the end-of-life signal on many models. Yellowing plastic, a manufacture date you have to squint at, or any alarm that survived an actual fire event should simply be retired. Sealed long-life battery alarms chirp end-of-life too — the difference is the answer is a new alarm, not a new battery.</p>
<h2>The five-minute audit</h2>
<p>Tonight, twist each alarm off its bracket and read the date. Manufactured more than ten years ago (smoke) or past its printed replace-by (CO): replace it — and count how many you actually need while you're up there (<a href="/home/how-many-smoke-co-alarms/">the counting guide</a>). When you buy, put the new retire-by date in your phone with a reminder a month ahead. And put the test in your calendar too, because expiry is only half the story — <a href="/home/test-alarms-monthly/">the monthly habit</a> is the other half, <a href="/home/mistakes/co-alarm-wrong-place/">placement</a> is the rest, and for UK landlords the legal minimums are in <a href="/home/uk-carbon-monoxide-alarm-law/">the law guide</a>. Ten minutes, once, and every date in the house is on your side.</p>
<p><em>Sources: NFPA and US state fire-marshal replacement guidance (10-year smoke alarm rule); manufacturer replace-by labelling conventions for electrochemical CO sensors. Last reviewed September 2026 · general information, not professional advice.</em></p>"""),

("test-alarms-monthly", "guide",
"The monthly five-minute habit that makes every other safety guide work",
"Testing every alarm in the house takes five minutes a month — and it's the one habit fire services ask for by name.",
"""<p>Nearly every guide on this desk ends the same way: check it, test it, don't assume. This one is the habit that carries the others. Fire services in the US and UK ask for the same thing by name — <strong>test your smoke and CO alarms at least once a month</strong> — because an alarm that fails silently is exactly as useless as no alarm, and failures are common: flat batteries pulled for a nuisance trip, chirps ignored, units knocked loose by a dusting, sensors quietly past their life.</p>
<h2>The routine, all five minutes of it</h2>
<p>Pick a day with an anchor — the first Saturday of the month, payday, the first of the month — and walk the house. Press and hold the test button on every alarm until it sounds, fully and loudly; not a weak squawk. If an alarm is out of reach from the floor, use a broom handle — never climb on chairs or furniture, which is how the falls happen. Listen from the far end of the house: if you can't hear a bedroom alarm from the kitchen with the door shut, interconnection or an extra unit belongs on your list. Count the alarms against the count you should have — one per storey is the legal floor in English rentals, but the recommended standard is room-based (<a href="/home/how-many-smoke-co-alarms/">here's the room-by-room version</a>).</p>
<h2>What the button does and doesn't prove</h2>
<p>The test button proves the battery, the electronics and the sounder. It does not prove the sensor still has full sensitivity — sensors degrade with age, which is why alarms carry expiry dates that the button can't override (<a href="/home/co-smoke-alarm-expiry/">read the dates once a year</a>; smoke alarms retire at ten years, CO sensors often sooner). Test is the monthly check; expiry is the annual one; together they're the whole system.</p>
<h2>The failures the test catches</h2>
<p>The battery someone silenced after a burnt toast false alarm and never restored — the single most common finding in fires where alarms were present but didn't sound. The alarm unscrewed for decorating and never reattached. The cell corrosion in a damp hallway unit. The combination unit that lost its CO side years ago. Every one of these looks fine from across the room; none survives a five-second button press. When you find a dead one, deal with it the same day — battery or replacement — because the gap between "noticed" and "fixed" is exactly where the risk lives.</p>
<h2>Make it carry the rest of the house</h2>
<p>Anchor two more minutes to the same walk, quarterly: glance at the dryer lint screen and vent flap (<a href="/home/dryer-lint-every-load/">the fire-prevention pair</a>), and check the CO alarm's position hasn't drifted behind furniture (<a href="/home/mistakes/co-alarm-wrong-place/">placement matters as much as power</a>). Or let the <a href="/home/seasonal-home-maintenance-checklist/">once-a-season checklist</a> carry the bigger sweep and keep this one for alarms alone. Everyone in the house should know the sound and what it means: three loud beeps, get out, stay out — the one fire-safety lesson with no substitute.</p>
<p><em>Sources: NFPA and USFA monthly-testing guidance; UK fire-and-resistance services' public campaigns. Last reviewed September 2026 · general information, not professional advice.</em></p>"""),

("condensation-vs-rising-vs-penetrating-damp", "guide",
"Condensation, rising damp or penetrating damp: how to tell which one you have",
"Three different damp problems, three different fixes — and treating the wrong one is how people spend money for nothing.",
"""<p>"We've got damp" is like saying "the car's making a noise" — the diagnosis is everything, and the three most common damp diagnoses are treated with three completely different fixes. Condensation is a moisture-and-airflow problem; rising damp is ground water climbing the wall; penetrating damp is water leaking in from outside. Spend on the wrong one and nothing improves. Here is how the pros tell them apart, using nothing more than your eyes, the weather, and a square of kitchen foil.</p>
<h2>Condensation: the cold-surface problem</h2>
<p>The tell-tales: black mould and water droplets on the coldest surfaces — window glass and frames, external corners, the wall behind the wardrobe or bed where air never moves. It's worst in winter, when warm moist air meets cold walls, and it wipes off... and comes back within days. Condensation is produced by living in the house — cooking, bathing, breathing, drying laundry (<a href="/home/mistakes/drying-laundry-indoors/">that's its own mistake piece</a>) — meeting surfaces too cold to hold the moisture. It is by far the most common of the three, it is not a building defect in itself, and its fix is ventilation and surface temperature, not builders (<a href="/home/condensation-ventilation-that-works/">the ventilation guide</a> has the method).</p>
<h2>Rising damp: the ground-floor tide mark</h2>
<p>The tell-tales: dampness confined to the ground floor, climbing the wall evenly to a roughly horizontal line — the "tide mark" — usually no higher than about a metre, often with white salt crystals blooming at its edge (ground water carries salts that crystallise as the wall dries). Skirting boards rot, paint peels in that band, and it barely changes with the weather or your lifestyle. Rising damp is a building-fabric problem — a failed or bridged damp-proof course — and it is the rarest of the three <em>and</em> the most often diagnosed, because treatments are lucrative. An honest word the industry rarely gives: get an independent surveyor's opinion before anyone sells you an injected damp-proof course, and treat "rising damp" diagnosed from a single photo as a sales claim, not a finding.</p>
<h2>Penetrating damp: the leak that moves with the weather</h2>
<p>The tell-tales: irregular patches — not a horizontal line, not corners — that grow noticeably during or after rain, on walls near obvious external defects: cracked render, faulty guttering, a downpipe joint, window seals, a roof tile, a chimney. It can appear at any height, including ceilings, and it doesn't respond to ventilation because it isn't moisture in the air — it's water in the building. The fix is external: find the defect, fix the defect, let the wall dry. That's roofer and gutter territory, and it's also exactly the disrepair that landlord repair duties cover (<a href="/home/uk-landlord-damp-mould-duties/">the duties guide</a> has who-pays-what).</p>
<h2>The foil test, and when to stop diagnosing</h2>
<p>Tape a square of kitchen foil flat over the damp patch, seal the edges, leave it 48 hours. Water on the <em>room side</em> of the foil means moisture is arriving in the air and condensing — condensation. Water <em>behind</em> it, between foil and wall, means the wall itself is wet — rising or penetrating, and the location rules above pick between them. Stop diagnosing and call a professional when: the patch grows fast, ceilings are involved, timber is soft or crumbling, mould covers more than about a square metre (health territory — treat remediation as a job for specialists), or you're in a rental and the building is implicated — report it in writing and let the duties machinery work.</p>
<p><em>Sources: UK property-preservation industry diagnostic guidance (PCA-member firms' published methods); Glass and Glazing Federation condensation guidance. Last reviewed September 2026 · general information, not a substitute for a survey.</em></p>"""),

("uk-landlord-damp-mould-duties", "guide",
"Damp and mould: the landlord duties changing across the UK — and what's already law",
"Awaab's Law reaches social housing in England now, Scotland's timescales land in October 2026 for social and private landlords — and private landlords in England are already bound by duties that predate all of it.",
"""<p>Damp and mould have moved from "maintenance issue" to statutory duty across the UK, in a wave of rules named for Awaab Ishak, the two-year-old who died in 2020 from exposure to mould in a socially rented flat. The changes land differently in each nation, and the dates matter — here is what is law now, what arrives in October 2026, and what is promised but not yet commenced. This is general information, not legal advice; the sources are named at the end and the review date matters.</p>
<h2>England: social housing now, private sector pending</h2>
<p>Awaab's Law has applied to social landlords in England since <strong>27 October 2025</strong>: emergency hazards must be investigated and made safe within 24 hours; significant hazards — damp and mould are the named headline — must be investigated within 10 working days, with a written summary to the tenant within 3 further working days, and required works begun within set timescales. For <strong>private landlords in England</strong>, the same framework is enabled by the Renters' Rights Act 2025 but has <em>not</em> been commenced — no date has been confirmed, with legal commentary pointing to 2027 at the earliest. What binds private landlords today is older and broader than most assume: the repairing duty for structure and exterior (including gutters and downpipes — the machinery behind penetrating damp), the duty that homes be fit for human habitation (damp and mould expressly relevant), and council enforcement under the housing health and safety rating system, which carries improvement notices and civil penalties.</p>
<h2>Scotland: the October 2026 moment</h2>
<p>The Scottish Parliament has approved regulations bringing Awaab-style timescales into force from <strong>October 2026</strong> — notably for <strong>both social and private rented housing</strong>. Landlords must investigate reports of damp and mould within 10 working days, give the tenant a written summary within 3 working days of completing it, and begin necessary repairs within 5 working days after that — unless delay is genuinely outside their control. Social landlords also face completion deadlines and compensation where qualifying repairs overrun; private tenants enforce through the Repairing Standard tribunal route instead. If you let property in Scotland, 2026 is the year to get reporting, investigation and paper-trail processes in order <em>before</em> the duties bite.</p>
<h2>Wales and Northern Ireland, briefly</h2>
<p>Wales' fitness-for-human-habitation requirements (in force since December 2022) already require rented homes to be free from serious damp and mould hazards, with enforceable timescales via the local authority. Northern Ireland has no equivalent statutory framework yet — the general fitness and repair duties apply — making it the laggard of the four nations.</p>
<h2>What it means if you own, let, or rent</h2>
<p><strong>If you rent out</strong>: the diagnosis-first discipline matters more than ever — <a href="/home/condensation-vs-rising-vs-penetrating-damp/">knowing condensation from penetrating damp</a> decides whether the duty is advice and ventilation or a repair with a clock on it, and the evidence file (written reports, dated photos, response dates) is now half the compliance. <strong>If you're a tenant</strong>: report in writing, keep dated photos, note whether patches worsen after rain — that record is what the new timescales run on. <strong>If you own your home</strong>: no statutory deadlines, but the health logic is identical, and the prevention side — <a href="/home/condensation-ventilation-that-works/">ventilation that actually works</a>, and <a href="/home/gas-heaters-damp/">knowing which heaters make damp worse</a> — is the same work either way.</p>
<p><em>Sources: Scottish Parliament SPICe briefing on dampness and mould duties (2026); UK Government guidance on Awaab's Law and the Renters' Rights Act 2025; Homes (Fitness for Human Habitation) Act 2018. Last reviewed September 2026 · general information, not legal advice — commencement dates move; check gov.uk and gov.scot before relying on any date.</em></p>"""),

("condensation-ventilation-that-works", "guide",
"The ventilation mistake behind most condensation problems",
"Homes are moisture factories — roughly a litre per night from two sleepers alone. Sealing that in and airing in short bursts is exactly backwards.",
"""<p>Most UK condensation isn't a building defect — it's an airflow strategy failure. The mistake takes two forms: sealing the house tight in the name of efficiency, and airing it in short bursts that feel virtuous and change almost nothing. Fix the strategy and the window streaming, the black mould behind the wardrobe and the musty spare room mostly resolve without a builder.</p>
<h2>How much water a normal day makes</h2>
<p>The glass industry's condensation research puts numbers on ordinary life: two sleeping adults release roughly a litre of moisture into the air in eight hours; a gas cooker cooking adds on the order of a litre an hour while it works; showers, kettles and drying laundry add their own — an indoor clothes horse alone can put litres into a day's air (<a href="/home/mistakes/drying-laundry-indoors/">why that habit made the mistakes shelf</a>). That vapour only stays harmless while it can leave the building. Modern homes — draught-proofed, double-glazed, chimney blocked — have removed most of the accidental escape routes older houses relied on, without adding deliberate ones.</p>
<h2>Why short bursts don't work</h2>
<p>Opening a window for five minutes in a cold room mostly cools the room: the surfaces get colder, and colder surfaces condense <em>more</em> of the moisture the next hour of living produces. Ventilation works on volume and time — the point is to exchange the moist air for dry outside air, not to briefly shock a single room. The workable version: a deliberate cross-flow of ten to fifteen minutes — windows open at opposite ends of the house — once or twice a day, while keeping the background trickle going all the time: trickle vents left open on modern windows, wall vents unblocked, extract fans actually switched on (and their run-on timers left at the setting the installer chose — the fan that stops two minutes after you leave the shower hasn't finished the job). Moist air moves through the whole house; leave internal doors ajar so the bathroom and kitchen can actually purge.</p>
<h2>The heating half of the fix</h2>
<p>Condensation lands on cold surfaces, so the other lever is keeping surfaces warm — which is why steady low-level background heating produces less condensation than sharp hot bursts in a cold house. A room heated for two hours at night is a cold room for the other twenty-two, and every cold surface is a trap. Cost reality bites here, and the honest version is: prioritise the rooms you sleep in, keep air moving everywhere, and treat persistent problems in unheated rooms as insulation questions rather than mould questions. While you're at it, check what's heating the room — <a href="/home/gas-heaters-damp/">some heaters add litres of moisture a day all by themselves</a>.</p>
<h2>When it isn't you, it's the building</h2>
<p>If patches grow after rain, if a tide mark climbs the ground-floor wall, if mould returns despite genuine airflow — stop buying sprays and read <a href="/home/condensation-vs-rising-vs-penetrating-damp/">the diagnosis guide</a>: penetrating and rising damp are building defects, and in a rental they're the landlord's repair duty, with new statutory timescales arriving around the UK (<a href="/home/uk-landlord-damp-mould-duties/">the duties guide has the dates</a>). A dehumidifier is the honest short-term bridge while the real fix happens — not a permanent tenant of the hallway.</p>
<p><em>Sources: Glass and Glazing Federation condensation guidance (moisture-production figures); UK ventilation and building-regulations background guidance. Last reviewed September 2026 · general information, not professional advice.</em></p>"""),

("gas-heaters-damp", "guide",
"Why unflued gas heaters make damp worse, not better",
"Burning gas indoors makes water — half a litre to a litre an hour that lands straight in your room, along with everything else combustion produces.",
"""<p>It feels like the obvious fix for a cold, damp room: a portable gas or paraffin heater, cheap to buy, instant heat. The irony is physical law — burning fuel makes water vapour, and a heater with no flue dumps every gram of it, along with everything else combustion produces, directly into the room it's warming. The heater that promises to dry the room out is measurably humidifying it.</p>
<h2>The chemistry, briefly</h2>
<p>Combustion turns hydrocarbon fuel into carbon dioxide and water vapour — the cloud you see above a flame is literally the exhaust. Measurements collected by condensation researchers and air-quality bodies put an unflued gas heater at roughly a third of a litre to a litre of water vapour an hour of use (figures vary by heater and study: 0.35 litres per hour in glass-industry guidance, 0.5–1 litres per hour in building-science measurements). Paraffin is worse still — the classic figure is about four litres of moisture for every three and a half litres of fuel burned. Run a portable heater through a cold evening and you have added several litres of water to the air of a house that was already struggling — which then condenses on the coldest surfaces exactly as usual (<a href="/home/condensation-ventilation-that-works/">the ventilation guide explains where it goes</a>).</p>
<h2>The part that matters more than damp</h2>
<p>An unflued heater has no pipe to the outside, which means the rest of the exhaust stays in the room too: carbon monoxide and nitrogen dioxide among them. Building-science testing has found nitrogen dioxide from an hour of unflued-gas use can exceed health guideline levels, and CO is exactly as dangerous as this desk keeps saying — colourless, odourless, and only ever announced by an alarm. If there is a flame-burning appliance without a flue in your home, a working, in-date, correctly placed CO alarm is not optional (<a href="/home/mistakes/co-alarm-wrong-place/">placement and expiry decide whether it works</a>), and UK rental duties already require one in rooms with fixed combustion appliances (<a href="/home/uk-carbon-monoxide-alarm-law/">the law guide</a>).</p>
<h2>The distinction the whole page turns on</h2>
<p>This is not an anti-gas-heating page. A <strong>flued</strong> gas boiler or gas fire sends its exhaust — water vapour included — up the flue and out of the building; that's the entire job of the flue. The problem is specifically <strong>unflued</strong> appliances: portable LPG cabinets heaters, flueless gas fires, paraffin heaters. Those are the devices that heat the room while humidifying it and dosing it. Some countries have restricted or effectively phased them out of new sale for exactly this reason; where they persist, they persist because the purchase price looks like the whole cost, and it never is — the hidden bill is paid in condensation on the windows, mould behind the furniture, and a dehumidifier running to undo the heater's work.</p>
<h2>If you're using one now</h2>
<p>Stop using it as primary heat. Ventilate deliberately while any combustion appliance runs (<a href="/home/condensation-ventilation-that-works/">the cross-flow method</a>), keep the CO alarm in the room, and plan the exit: any heater with a flue, or electric heat, costs more to run than the sticker suggested and delivers a dry warm room instead of a warm damp one. If mould has already taken hold behind where the heater sat, treat it as a symptom that outlives the cause — the <a href="/home/condensation-vs-rising-vs-penetrating-damp/">diagnosis guide</a> tells you what you're looking at.</p>
<p><em>Sources: Glass and Glazing Federation condensation guidance (moisture-per-hour figures); building-science and air-quality measurements of unflued gas heater emissions (NZ Beacon Pathway and published studies). Last reviewed September 2026 · general information, not professional advice.</em></p>"""),
]
