"""BRYME Home & DIY - expansion batch 20 (Sept 2026, tier-1 focus, volume 5):
the energy-bills cluster, anchored on the year's defining home query ("why is
my electric bill so high") with the bill-diagnoser, the appliance power
rankings, the one-room-heating question, the old second fridge, and off-peak
tariffs. Figures: US average residential rate about 18-19 cents/kWh (EIA-
derived, September 2026), up roughly a quarter since 2022; UK Ofgem cap unit
rate 26.11p July-September 2026, a step up from the spring; fridge figures
follow long-established efficiency-agency guidance. Desk rules: general
information, figures hedged, your own bill always wins. Body links are
root-level by convention; build-routing prefixes them with /home/."""

HOME_ROADMAP_20 = [
("why-is-my-electric-bill-so-high", "understand",
"Why is my electric bill so high? The eight causes, ranked",
"Before blaming the boiler or the kids' consoles: rates rose first, then the water heater, the old fridge and the small always-on loads. The ranked diagnosis, and the meter test that finds your personal answer.",
"""<p>The bill that arrives shouting is usually two stories tangled into one: the price of electricity rose, and the house used a little more of it. National averages climbed steeply through 2025-26 in the US and UK alike - average US residential rates are up roughly a quarter since 2022, and the UK's capped unit rate stepped up sharply in July 2026 - so some of your increase is arithmetic you cannot control. The rest is findable. General information; your own bill's unit rate is the only number that matters for your maths.</p>
<h2>Step one: separate price from usage</h2>
<p>Take the bill's total and divide by its kWh figure. If your rate per kWh jumped, the story is mostly the market - and the fixes are tariff-shaped (below). If the rate barely moved but the kWh climbed, the house changed, and the diagnosis starts: new appliance, new habit, new leak of energy somewhere.</p>
<h2>The usual suspects, roughly in order</h2>
<p><b>1. Heating and cooling</b> - the biggest single user in most homes; every degree of extra ambition in winter or extra cool in summer prints money on the bill (<a href="/thermostat-settings-that-save-money/">the setback schedule</a> is the highest-value habit in the house). <b>2. Water heating</b> - tanks age, sediments build, and a tank working overtime shows up monthly (<a href="/water-heater-explained/">the water heater guide</a>). <b>3. The old second fridge</b> - a 1990s garage freezer can draw two to three times what a modern efficient one does, every hour of every day (<a href="/second-fridge-freezer-cost/">the dedicated maths</a>). <b>4. Always-on small loads</b> - consoles, set-top boxes, old routers, chargers, the amp on standby: individually trivial, collectively a visible base-load line (<a href="/standby-power-real-numbers-your-meter/">measured with a meter here</a>). <b>5. Drying laundry</b> - a 3,000 W dryer an hour a day is one of the largest single lines in an all-electric house. <b>6. Lighting</b> - only if halogens remain. <b>7. A failing appliance</b> - a struggling fridge compressor or a heating element on its way out runs long and hard. <b>8. Seasonality</b> - summer AC and winter heating make the "same usage" bills swing hugely; compare kWh to the same month last year, not to last month.</p>
<h2>The meter test that finds your base load</h2>
<p>Everything off - lights, appliances at the wall, heating off - then read the meter. A modern home's acceptable dormant draw is small: if the meter keeps visibly ticking with the house "off", something is running that should not be, and walking the house switching circuits off at the consumer unit finds it in twenty minutes. That base-load number is also the cleanest way to see whether <a href="/standby-power-real-numbers-your-meter/">the standby cleanup</a> is worth an evening.</p>
<h2>If it is the price, not the house</h2>
<p>Rate-driven bills respond to tariff strategy rather than appliance discipline: check whether a time-of-use plan fits your routine (<a href="/off-peak-electricity-tariffs-explained/">how off-peak tariffs work</a>), whether your provider's cheaper fixed or online tariffs are available to you, and whether the big structural levers - <a href="/attic-insulation-basics/">insulation</a>, <a href="/draught-proofing-mistakes/">draught-proofing</a> - have been pulled, because they cut usage at any price. And for the appliance-level arithmetic, the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a> prices any appliance at your own rate in your own currency.</p>"""),

("appliances-that-use-the-most-electricity", "understand",
"The appliances that use the most electricity, ranked",
"From the heating system to the games console: the honest kWh rankings, what each costs to run at an average rate, and the levers that actually move each one.",
"""<p>Every appliance's cost is the same three-factor sum: watts, hours, and your rate per kWh. The rankings below use typical household figures and an average rate near 18-19 cents per kWh (about 26p in the UK) - treat them as shapes, not quotes, and price your own with the bill's rate using the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a>.</p>
<h2>The heavy line-up</h2>
<p><b>1. Electric heating and cooling (2,000-3,500 W running).</b> A few hours a day in season dwarfs everything else - which is why thermostat habits and insulation outclass all appliance advice (<a href="/thermostat-settings-that-save-money/">the setback schedule</a>, <a href="/attic-insulation-basics/">the attic</a>). Heat pumps move three or four units of heat per unit of electricity; plain resistance heating does not, so the same comfort costs a fraction of the power. <b>2. Water heating (2,000-4,500 W while heating).</b> Every shower, dishwasher cycle and laundry load draws on it; a tank holding temperature all day multiplies the draw (<a href="/water-heater-explained/">care and settings</a>). <b>3. Tumble dryer (about 3,000 W).</b> An hour a day is roughly 90 kWh a month - the single most expensive plug-in appliance in most homes, and the reason a drying rack or a covered line is a payrise. <b>4. EV charging (7,200 W typical home unit).</b> The newest heavyweight: a meaningful overnight charge can rival the rest of the day combined, which is exactly why off-peak tariffs were invented (<a href="/off-peak-electricity-tariffs-explained/">the tariff guide</a>). <b>5. The fridge-freezer (100-400 W, all year).</b> It never sleeps, so a 20-year-old unit drawing two to three times a modern one matters - see <a href="/second-fridge-freezer-cost/">the second-fridge maths</a>, and keep coils clean (<a href="/fridge-temperature-setting/">settings here</a>). <b>6. Space heaters (1,500 W).</b> One heater, five evening hours, every winter day: a bill line disguised as a bargain (<a href="/is-it-cheaper-to-heat-one-room/">the one-room question answered honestly</a>). <b>7. Washing machine, dishwasher (500-1,500 W, cycles)</b> - modest per run, meaningful in frequency; wash cold where you can (<a href="/how-to-clean-a-washing-machine/">keep the machine efficient</a>). <b>8. Everything small</b> - TVs, consoles, routers - adds up as a base-load line rather than a single villain (<a href="/standby-power-real-numbers-your-meter/">the measured audit</a>).</p>
<h2>How to use the ranking</h2>
<p>Find your house's top two and attack those first - a dryer habit changed beats a decade of lamp guilt. Efficiency upgrades compound: every appliance above has a lazy mode (clogged coils, wrong temperature, standby draw) that costs nothing to fix, and the <a href="/repair-or-replace-appliances/">repair-or-replace framework</a> tells you when an old energy hog has priced itself out of repairs. And when a bill spikes, the ranked diagnosis in <a href="/why-is-my-electric-bill-so-high/">why is my bill so high</a> walks the list in evidence order.</p>"""),

("is-it-cheaper-to-heat-one-room", "understand",
"Is it cheaper to heat one room? The honest answer",
"The space-heater maths works - for one person, in one room, for a few hours. Here is where the boundary sits, and why 'turn off the heating and huddle' can cost more than it saves.",
"""<p>The question arrives every winter with the first cold week: leave the heating off and run a 1,500 W space heater in whichever room you are in - or heat the whole house? The honest answer has a narrow true zone, and most households drift outside it without noticing.</p>
<h2>Where the space heater genuinely wins</h2>
<p>The heater draws 1.5 kW, so each hour costs one-and-a-half times your rate per kWh - around 27 cents at an average US rate, 40p at the UK cap rate. If you would otherwise heat the whole house for those hours, one occupied room at 27-40 cents an evening-hour is dramatically cheaper, because the alternative is heating rooms nobody is in. The win zone: <b>one or two people, one room, a few hours, doors closed</b> - the classic evening in the sitting room while the bedrooms stay cold until bedtime.</p>
<h2>Where the maths turns</h2>
<p>Three drifts erase the saving. <b>Time:</b> run the heater all day, or in two rooms, and its total approaches or passes what the central heating would have cost for the same comfort. <b>Fuel:</b> electric resistance is the most expensive heat per unit there is - if your central system is a heat pump or a gas boiler, one electric heater's "cheap" evening can cost more than hours of the whole-house system it replaced. <b>Damp:</b> a permanently cold house accumulates condensation and mould on cold walls, and that repair dwarfs any heating saving - the moisture chain runs through <a href="/condensation-ventilation-that-works/">ventilation that works</a> and <a href="/humidity-and-paint/">paint that survives damp rooms</a>.</p>
<h2>The hybrid that actually saves</h2>
<p>Use the heater for the sharp edges of the day - the morning kitchen, the evening sitting room - and let the central system hold a lower background temperature so the house never gets genuinely cold. That is the setback principle from <a href="/thermostat-settings-that-save-money/">the thermostat guide</a> with a heater filling the peaks, and it is how the one-room trick keeps its maths honest. Support it the boring way: doors closed on the heated room, curtains closed on the dark side of the house, and the <a href="/ceiling-fan-direction-summer-winter/">fan on winter mode</a> pushing warm air back down. If the whole house needs heat all day anyway, the space heater is only adding an expensive layer - the real levers are <a href="/attic-insulation-basics/">insulation</a> and <a href="/draught-proofing-mistakes/">draughts</a>, which cut the bill at every setting.</p>"""),

("second-fridge-freezer-cost", "understand",
"The garage fridge: what your second fridge or freezer really costs",
"The spare fridge in the utility room is often the most expensive appliance per hour of usefulness in the house. The maths by decade, the garage factor, and when to unplug it.",
"""<p>The second fridge has a way of never appearing on any mental list of household costs - it hums in the utility room holding a few bottles and a bag of peas, and it has been doing it for twenty years. Run the actual numbers and it is often the most expensive appliance per hour of usefulness in the house: an old unit can draw two to three times what a modern efficient fridge does for the same job, every hour of every day, and it does that maths at your current rate - roughly 18-19 cents a kWh in the US, about 26p in the UK on the capped rate.</p>
<h2>The decade maths</h2>
<p>A 1990s fridge-freezer commonly draws several hundred watts-year in - say 800-1,400 kWh a year where a modern efficient unit does 200-350 kWh. At an average rate that is roughly the difference between twenty and a couple of hundred in annual running cost, depending on rates and the unit's age - plug your own figures into the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a> and let the real numbers argue. A decade-old mid-range unit sits between those poles; a five-year-old efficient one is cheap enough to stop thinking about.</p>
<h2>The garage factor</h2>
<p>Fridges and freezers are rated for ambient temperature ranges, and an unheated garage or utility room in a cold winter can send an old fridge's thermostat into confusion (it "thinks" it is cold enough and runs oddly or not at all), while a hot summer garage makes the compressor run near-continuously. Cold-weather ratings matter most for fridges (freezers cope better in cool spaces); a garage fridge in a hot climate is the worst of both worlds - the 1990s unit in the Arizona garage is the poster child of this article.</p>
<h2>The decision framework</h2>
<p><b>Unplug it if</b> it is mostly empty, pre-2010, and holding nothing you would miss - an empty fridge costs nearly as much as a full one, and the plug test costs nothing: unplug, note the meter difference over a week, and decide with evidence. <b>Replace it if</b> it genuinely earns its keep but is pre-2005 - one efficient replacement typically pays for itself in a few years of savings at average rates, the same arithmetic as <a href="/repair-or-replace-appliances/">the repair-or-replace framework</a>. <b>Keep it if</b> it is modern, reasonably full, and doing a real job - and then maintain it: coils cleaned yearly, door seal tested with the banknote trick from <a href="/fridge-temperature-setting/">the temperature guide</a>, a hand's width of air behind it. And when a unit does retire, the failed-appliance dance is already covered in <a href="/fridge-not-cooling/">the fridge-not-cooling checklist</a>.</p>"""),

("off-peak-electricity-tariffs-explained", "maintain",
"Off-peak electricity: how time-of-use tariffs save money",
"Economy 7, EV plans and smart time-of-use deals pay you for moving the same laundry to the night. Who benefits, who does not, and the household shifts that make the tariff work.",
"""<p>Most homes pay one flat rate for every kWh, but generating electricity is not flat-cost: power at 3 am is far cheaper than power at 6 pm. Time-of-use tariffs pass some of that difference to you - a cheap overnight window (Economy 7's seven night hours in the UK, overnight EV and off-peak plans in the US and Australia, smart-tariff half-hour pricing where smart meters allow) and a pricier daytime rate to balance it. Whether that trade suits the house depends entirely on when the house can use its power.</p>
<h2>Who wins immediately</h2>
<p>Homes with a <b>big shiftable load</b>: an EV charging overnight is the textbook case - the same miles cost a fraction at night rates. Close behind: households with a night storage heater, a <b>timer-capable washer, dryer or dishwasher</b>, or anyone whose <a href="/water-heater-explained/">water heater</a> can heat its tank in the cheap window for the next day. A smart plug or the machine's own delay button is the whole technology required for the laundry-class wins.</p>
<h2>Who should stay flat-rate</h2>
<p>The all-evening household: dinner cooked at 7, laundry dried at 8, heating and lights through the peak - on a time-of-use tariff those exact hours are the expensive ones, and a rate plan cannot rescue a usage pattern that lives on the peak. If nothing in the house can run unattended at night, the cheap window earns nothing while the expensive hours carry the whole bill. The honest test is a week of noting <i>when</i> the house actually draws power (the meter test in <a href="/why-is-my-electric-bill-so-high/">the bill diagnosis</a> doubles as the survey) and checking what share could move.</p>
<h2>The shifts that make it work</h2>
<p>Run the washer, dryer and dishwasher on delay timers overnight; heat the water tank in the cheap window; charge everything with a battery - phones, laptops, the EV - while you sleep; and where the plan prices it sensibly, pre-heat or pre-cool the house slightly before the peak and let the <a href="/attic-insulation-basics/">insulation</a> hold it through the expensive hours. Pair the tariff with the habits that work at any rate - <a href="/standby-power-real-numbers-your-meter/">the standby cleanup</a> and the thermostat discipline from <a href="/smart-thermostat-payback/">the smart-thermostat payback maths</a> (many smart models automate the peak-shifting for you). Read any tariff's small print for its peak-window definition and its standing charge - the cheap night rate means little if the day rate or fixed fees swallow the savings.</p>"""),
]
