# BRYME Home & DIY — roadmap batch 5: Permits & legal (5).
# Heaviest YMYL cluster: government/legislation-grounded, framed as general information
# with jurisdiction caveats. Verified 2026-09-10 — see docs/ecosystem/home-article-roadmap.md.

HOME_ROADMAP_5 = [
("us-home-permits", "guide",
"What requires a permit in the US — and what happens if you skip one",
"There's no national permit rulebook: cities and counties decide. But the categories that almost always need one are consistent — and so are the consequences of guessing wrong.",
"""<p>Ask "does this need a permit?" online and someone will answer with confidence, for your city, without living there. The honest answer is that building permits in the US are set locally — state codes adopted and enforced by cities and counties, each with its own list. What makes this manageable is that the categories are remarkably consistent across jurisdictions, and the logic is easy to carry: <em>anything that changes the structure, the systems, or the safety of the house</em> is a permit candidate. Cosmetic work isn't.</p>
<h2>The categories that almost always need one</h2>
<p><strong>Electrical</strong> — beyond swapping a like fixture: new circuits, new outlets, panel upgrades or replacement, new wiring, EV-charger circuits. <strong>Plumbing</strong> — beyond a faucet swap: moving or adding fixtures, replacing a water heater (yes, even a like-for-like swap, in many jurisdictions — gas and scald risk make it a classic permit job), re-piping, sewer work. <strong>Structural</strong> — removing or altering walls (even some non-load-bearing, because "is it?" is exactly what the inspection establishes), new openings in exterior walls, foundations, additions, roof structure changes, decks (height thresholds vary), often fences over a set height and sheds over a size threshold. <strong>Mechanical</strong> — HVAC replacements, new heating or cooling equipment, ventilation changes, and frequently roofing and siding. The consistent exemptions: paint, flooring, like-for-like interior doors, cabinets and counters, minor repairs. When a project mixes categories — a bathroom remodel that moves plumbing — each trade's permit typically applies.</p>
<h2>What happens if you skip one</h2>
<p>The consequences arrive on a delay, which is why they surprise people. <strong>Now:</strong> if the authority discovers active unpermitted work, a stop-work order halts the project, and fines set locally follow. <strong>Later:</strong> a future permit application on the same house can surface the old one, and retroactive permitting runs the "code cascade" — the inspector evaluates the old work against <em>current</em> code, and related systems can be dragged in with it; a small permit becomes an open-ended compliance project. <strong>Insurance:</strong> damage traced to unpermitted work — the fire from the DIY wiring, the flood from the DIY plumbing — is a classic claim-denial scenario; <a href="/home/small-leak-ripple-effect/">the slow-leak guide's insurance section</a> covers the gradual-damage cousin. <strong>Sale:</strong> unpermitted work surfaces at inspection, complicates lender financing, and becomes a price negotiation — <a href="/home/unpermitted-work-home-sale/">it gets its own guide, because it's the consequence that arrives years later</a>. And if work can't be brought to code, authorities can require removal — at the owner's expense.</p>
<h2>The process, stripped down</h2>
<p>Permits are applied for at your city or county building department (increasingly online), with a description or plans depending on scope; fees for typical residential projects commonly run in the tens-to-hundreds-of-dollars range, set locally. Inspections happen at defined stages — rough-in before walls close, final at completion — and the signed-off permit goes in your house file, which is exactly where you want it the day you sell. If a licensed contractor does the work, they typically pull the trade permits; if you DIY, you pull the homeowner permit, and <a href="/home/us-diy-electrical-rules/">whether you're allowed to do the work yourself at all is its own question</a>.</p>
<h2>The two-minute habit</h2>
<p>Before any project beyond decoration, one call or web check with your local building department settles it — and the same instinct generalises: <a href="/home/hvac-diy-warranty-rules/">warranty lines</a>, <a href="/home/uk-us-plumber-rules/">notification rules</a> and permit rules are all versions of the same question — <em>who needs to know about this work before it happens?</em> Asking costs a phone call. Not asking has a paper trail that follows the house.</p>
<p><em>Sources: consistent permit-category patterns across municipal building departments and code-council guidance; consequences documented by building departments and insurer/consumer guidance. Reviewed September 2026 · general information, not legal advice — your city or county's rules are the ones that apply.</em></p>"""),

("building-regs-vs-planning-permission", "guide",
"Building Regulations vs Planning Permission: the UK distinction homeowners confuse",
"Two different questions, two different bodies, two different fees — and 'I don't need planning' is not the same sentence as 'I don't need Building Regs'.",
"""<p>The most expensive sentence in UK home improvement is "the council said it's fine" — because there are two councils-that-say, and they answer different questions. <strong>Planning permission</strong> asks whether you may build it at all: land use, size, appearance, neighbours, the street. <strong>Building Regulations</strong> ask whether it's built properly: structure, fire, ventilation, energy, electrics, drainage. A project can need neither, either, or both — and assuming one answer covers both questions is the confusion this page exists to fix.</p>
<h2>Planning permission: the whether-and-where</h2>
<p>Decided by your local planning authority, planning concerns the principle of development: is a new building or extension allowed here, how big, what it looks like, what it's used for. Much ordinary home improvement falls under <strong>permitted development</strong> — rights to build certain limits of extension, loft conversion or outbuilding without a planning application — with the rules tightening for listed buildings, conservation areas and homes that have already used their allowances. What planning does <em>not</em> do is check a single technical detail of construction.</p>
<h2>Building Regulations: the how</h2>
<p>Building Regs apply to most "building work" — the legal definition (Regulation 3) reaches further than people expect: extensions, structural alterations (removing a wall), most window and door replacements (through FENSA/CERTASS-style certification), new or rewired electrics (<a href="/home/part-p-explained/">Part P — its own guide</a>), new boilers and heating work, bathrooms moved or newly created, drainage. Compliance is checked by building control — your council's team or a private approved inspector — with inspections at stages and a completion certificate at the end. Cosmetic work — paint, wallpaper, like-for-like kitchen units, floor coverings — sits outside both systems.</p>
<h2>The four combinations, with examples</h2>
<p><strong>Both:</strong> a large extension beyond permitted-development limits — planning for size and appearance, Building Regs for construction. <strong>Building Regs only:</strong> the classic — a rear extension <em>within</em> permitted development needs no planning application and still needs full Building Regs approval; so do a structural wall removal (no planning at all, and the completion certificate is essential) and most electrical work. <strong>Planning only:</strong> rare for householders, mostly land-use changes. <strong>Neither:</strong> decoration and like-for-like repairs. The everyday trap is the second row: the homeowner who checked planning, found permitted development, and never heard of building control until a buyer's solicitor asked for the certificate a decade later (<a href="/home/unpermitted-work-home-sale/">that conversation has its own guide</a>).</p>
<h2>Why the distinction bites</h2>
<p>The enforcement teeth differ: unauthorised planning breaches face enforcement notices with time limits; non-compliant Building Regs work is enforceable through the courts as a criminal matter, with powers to require work to be opened up or fixed — and either way, the missing paperwork is found by every surveyor, solicitor and lender a property passes through. The healthy habit is two parallel checklists for any project beyond decoration: <em>do I need planning (or am I within permitted development)?</em> and <em>does this is building work that needs Building Regs sign-off — and which parts need a registered installer?</em> Your council's planning and building control teams answer the first and second respectively — asking each team its own question is half the battle.</p>
<p><em>Sources: GOV.UK planning portal and Building Regulations guidance; local-authority building control explanations (Regulation 3 "building work"); Approved Document P for electrical notification. Reviewed September 2026 · general information, not legal advice — permitted-development limits and guidance differ across England, Scotland, Wales and NI.</em></p>"""),

("unpermitted-work-home-sale", "guide",
"Why unpermitted work can derail a home sale years later",
"The work itself often survives inspection fine. It's the missing paperwork that costs — and the bill lands on whoever owns the house when it's found.",
"""<p>Here's the pattern conveyancers see constantly: an extension, loft conversion or rewire done years ago — work that may be perfectly sound — but the certificates were never obtained. The owner sells; the buyer's surveyor notes the work; the buyer's solicitor asks for the completion certificate that doesn't exist; and suddenly a straightforward sale has a price negotiation attached. Unpermitted work rarely stops a sale outright. What it does is worse, in a way: it transfers leverage to the buyer, years after the decision that created it.</p>
<h2>Why it surfaces exactly when it hurts most</h2>
<p>Sales are paperwork audits. Surveyors report building work and ask whether approvals exist; solicitors run searches and questionnaires (in England, the property information form asks about alterations and certificates — answering untruthfully creates misrepresentation exposure that outlives the sale); mortgage lenders want the certificates before releasing funds. In the US the same discovery runs through inspection, disclosure obligations and lender underwriting. The obligation to have obtained approval sat with whoever did the work — but the burden of <em>proving</em> compliance falls on whoever owns the house when the question is asked. That's the "years later" of this title: the problem is dormant until the house changes hands.</p>
<h2>The UK resolution menu</h2>
<p>Four routes, in rough order of preference. <strong>Regularisation:</strong> a retrospective application to building control (available in England/Wales for work carried out after November 1985) — an inspector assesses the work against the standards of its time, may require elements opened up, may require remedial work, and is under no obligation to issue the certificate. It's the real fix, and the open-ended one: fees typically run from hundreds into the low thousands of pounds, and what the inspector finds is unknowable until they look. <strong>Indemnity insurance:</strong> a cheap, fast policy against local-authority enforcement — with sharp limits that sellers must understand: it certifies nothing about the work's safety, it's void if the council is already aware of the issue (which is why you don't "just ask them a question" before deciding your route), and void once a regularisation application has been made. <strong>Price:</strong> the buyer discounts instead of requiring paperwork. <strong>Speed:</strong> cash buyers who absorb the risk, below market value. Since certificates can't be manufactured retroactively for work done properly-but-unrecorded (electrics can sometimes be certified post-hoc; an <a href="/home/part-p-explained/">electrical certification discussion is here</a>), the route is usually insurance-plus-price.</p>
<h2>The US version of the same trap</h2>
<p>American sales hit the same wall through inspection and disclosure: unpermitted work discovered mid-escrow triggers demands for retroactive permits — and retroactive permitting is where the <a href="/home/us-home-permits/">code cascade lives</a>: current-code evaluation, possible exposure of covered work, and costs that scale unpredictably. Insurers add their version: damage traced to unpermitted work is a denial scenario on both sides of the Atlantic (<a href="/home/small-leak-ripple-effect/">the gradual-damage principle</a> applies here too).</p>
<h2>The prevention, for the work you haven't done yet</h2>
<p>Every certificate obtained at the time — completion certificate, FENSA-style window certification, <a href="/home/part-p-explained/">Part P electrical certificate</a>, Gas Safe record — is money already sitting in the sale file of the future. For work already done: gather what exists (old approvals, guarantees, installer certificates), be honest on the forms early, and choose your route deliberately before listing rather than mid-negotiation. The one bad option is concealment — the discount is inevitable, and the misrepresentation claim is optional only if you tell the truth.</p>
<p><em>Sources: local-authority building control regularisation guidance (post-November 1985 eligibility); conveyancing and consumer-protection guidance on disclosure and indemnity insurance; US inspection/disclosure practice. Reviewed September 2026 · general information, not legal advice.</em></p>"""),

("part-p-explained", "guide",
"Part P explained: what UK homeowners legally can't DIY on their own wiring",
"Part P doesn't ban DIY electrics — it divides them. Some jobs are yours to do; the rest need a registered electrician or building control before you start.",
"""<p>Part P of the Building Regulations (England and Wales) is the electrical-safety rule most UK homeowners have heard of and few understand. The confusion is binary: some believe all home electrics must be done by an electrician (false), others believe none of it is regulated (dangerously false). Part P actually splits the work into two lists — <strong>notifiable</strong> and <strong>non-notifiable</strong> — and the split follows risk: rooms with water, the great outdoors, and anything involving new circuits or the fuse board.</p>
<h2>What you can legally do yourself</h2>
<p>Three groups sit on the DIY side. <strong>Like-for-like replacement anywhere</strong> — swapping a damaged socket, switch or light fitting for the same kind, in any room including a kitchen or bathroom. <strong>Additions to existing circuits outside special locations</strong> — adding a socket or spur to an existing ring in a living room or bedroom, wiring a new ceiling light from an existing lighting point. <strong>Minor maintenance and repair</strong> anywhere. The catch that makes it honest: even non-notifiable work must still meet BS 7671, the wiring standard — correct cable, correct connections, RCD protection as required. "Legal to do" and "done competently" are two different bars, and the first doesn't excuse missing the second.</p>
<h2>What's notifiable — the other list</h2>
<p><strong>All new circuits</strong>, anywhere, for any purpose. <strong>Consumer unit replacement or upgrade</strong> — the board is the safety brain of the house. <strong>Any addition or alteration to existing circuits in "special locations"</strong> — rooms containing a bath or shower, and by the same logic of the schedules, kitchens: adding a socket, moving a light, wiring an electric shower or hob in a kitchen or bathroom is notifiable, the only exceptions being like-for-like swaps. <strong>Everything outdoors</strong> — garden lighting from new wiring, power to sheds, garages and outbuildings, EV chargers, pond pumps. The routes to compliance: a <strong>registered electrician</strong> (NICEIC, NAPIT and similar government-approved schemes) self-certifies and notifies the council for you — usually the cheapest and simplest path; or you <strong>DIY with building control approval</strong> — apply before starting, pay the inspection fee (commonly a few hundred pounds), have the work inspected at first and second fix, and provide test results to BS 7671. If that sounds like a lot, it is: it's the price of doing electrician work without being one.</p>
<h2>What happens if you ignore it</h2>
<p>Non-compliant notifiable work is a building-regulations breach — enforceable as a criminal matter, with powers to require work to be opened up, altered or removed, at the owner's cost. And the quieter penalty is the one that arrives at <a href="/home/unpermitted-work-home-sale/">sale time: no certificate, no paperwork, buyer's solicitor asking questions</a> — the regularisation-and-indemnity dance, in its most awkward variant, because uncertified electrics are the first thing every surveyor and lender probes.</p>
<h2>The honest safety framing</h2>
<p>The legal map above is the floor. The <a href="/home/mistakes/drilling-without-checking/">cables-behind-the-wall guide</a> and <a href="/home/outlet-overloading-danger/">the overloading piece</a> cover the physical dangers, and <a href="/home/electrical-fire-warning-signs/">the warning-signs guide</a> covers what failing electrics smell, look and sound like. Our desk's standing rule holds whether or not law requires it: everything past like-for-like swapping belongs to a registered electrician, and everything near the consumer unit belongs there always — <a href="/home/induction-hob-wiring/">the same line the induction guide draws</a>. Scotland and Northern Ireland run different arrangements (Scotland via building standards, NI via its own regulations) — check locally before any notifiable-scale project.</p>
<p><em>Sources: The Building Regulations 2010, Approved Document P (electrical safety) and its notification schedules; BS 7671 as the technical standard; government-approved competent-person scheme guidance. Reviewed September 2026 · general information, not legal advice.</em></p>"""),

("us-diy-electrical-rules", "guide",
"What DIY electrical work is actually legal in the US — without a licence",
"There's no single answer — states run three different systems. Here's the honest map, and the parts that are the same everywhere.",
"""<p>"Can I wire my own house in the US?" has no national answer, and anyone who gives you one flat answer is describing their state, not the country. What actually exists is three patterns, and the honest way to write this guide is to show all three — then the parts of the answer that <em>are</em> the same everywhere, which happen to be the parts that matter most for safety.</p>
<h2>Pattern one: the explicit homeowner exemption</h2>
<p>Some states write the right into licensing law. Oklahoma's electrical licensing act, for example, states plainly that no licence is required for an individual doing electrical work "on his own property or residence" — with local ordinances able to add requirements, and with the exemption explicitly <em>not</em> covering rental property, other people's homes, or any work for compensation. Minnesota runs a close cousin: a homeowner may do electrical work on their own owner-occupied, single-family homestead, must personally do the work, and must pull a homeowner permit and pass state inspection. Notice the shared skeleton already: <strong>your own home, where you live, nobody else's — and permits and inspections still apply</strong>.</p>
<h2>Pattern two: inspector discretion</h2>
<p>Other states leave it to local electrical inspectors. Massachusetts is the classic example often cited: there's no statutory homeowner right to do electrical work, and state law doesn't clearly grant one — some inspectors will issue a homeowner permit for an owner-occupied single-family house, others decline, and both are acting within their authority. Practically: in these states the answer is decided by the conversation at your local building department, not by a statute you can cite at them. Walking in with the attitude that you have a "right" is how homeowners end up refused.</p>
<h2>Pattern three: licensed-only in practice</h2>
<p>Some jurisdictions require a licence for electrical work of any scale, homeowner or not — the owner-occupied exemption is narrow or absent. The only honest instruction for this pattern is the one that applies everywhere anyway: before touching wiring, one call to your city or county building department settles which pattern you live in. Because the map is genuinely three-colored, no honest guide will publish a fifty-state list without quoting each state's statute — this one won't either.</p>
<h2>The parts that are the same everywhere</h2>
<p>Where homeowner work <em>is</em> allowed: permits and inspections are required for real electrical work — new circuits, outlets, panels — the same as for contractors. Rentals and other people's property are never covered by homeowner exemptions; the licence rules apply in full. And the safety floor is universal regardless of law: the panel and meter are professional territory always (<a href="/home/why-does-my-circuit-breaker-keep-tripping/">the breaker guide explains what that box is actually doing</a>); every job starts with killing the circuit and verifying it dead; load arithmetic applies whether or not anyone inspects it (<a href="/home/outlet-overloading-danger/">the overloading guide does the math</a>); and the failure signs — warmth, scorch marks, the fish smell — mean stop (<a href="/home/electrical-fire-warning-signs/">the warning-signs guide</a>). Refrigerant and gas lines have their own hard legal lines entirely (<a href="/home/hvac-diy-warranty-rules/">covered here</a>).</p>
<h2>The decision, in order</h2>
<p>One: is this my owner-occupied home? (If not — licensed electrician, full stop.) Two: does my state/city allow homeowner electrical work, and at what scale? (Building department's answer is final.) Three: does this specific job need a permit, and will I pass inspection — including the parts of the code most DIYers have never read, like box fill and bonding? Four, and most important: is the honest answer to three "I don't know"? Then the work belongs to an electrician — not because the law said so, but because the law's silence is not a competence certificate, and <a href="/home/electrical-fire-warning-signs/">electrical failures have a way of testifying later</a>.</p>
<p><em>Sources: state licensing statutes (e.g. Oklahoma Title 59 homeowner exemption; Minnesota homeowner electrical permit rules), local inspector discretion practice (e.g. Massachusetts), NEC adoption as the technical baseline. Reviewed September 2026 · general information, not legal advice — your state statute and local building department are the only authorities for your address.</em></p>"""),
]
