# BRYME Home & DIY — roadmap batch 11: the seasonal system (4). Batch 29, 11 Sep 2026.
# Master Pack §3.2.5: Spring Reset · Summer Cooling · Autumn Preparation · Winter Preparation.
# Each: interior, exterior, appliances, energy, safety. Northern-hemisphere calendar framing with an
# explicit six-month offset note for southern-hemisphere readers (both hemispheres, no duplicate pages).
# Only links to pages that exist on the desk (verified against public/home at write time).

HOME_ROADMAP_11 = [
("spring-home-reset", "guide",
"The spring home reset: the order that works",
"Winter's damage first, the cooling second, the deep clean last — a sane sequence for the season of catching up.",
"""<p>Spring resets fail when they start with the fun part. The working order is: <b>inspect what winter damaged, service what summer will demand, then clean.</b> Do it in that sequence and nothing gets cleaned twice.</p>
<h2>Exterior first — winter just audited your house for free</h2>
<p>Winter is a stress test, and spring is reading the results. Walk the outside once: roofline and gutters (anything sagging, leaking or growing green is a job for <a href="/home/gutter-cleaning-damage/">the gutter routine</a> before the spring rains make it expensive), outside walls and renders for cracks, seals around doors and windows, and the <a href="/home/ac-outdoor-unit-care/">AC outdoor unit</a> — clear winter debris off the coil and its airflow path <em>before</em> the first hot day, not during the first heatwave. This is also the honest moment for the year's roof-and-drama check from the ground with binoculars: slipped tiles, lifted flashing.</p>
<h2>Service what summer will demand</h2>
<p>Cooling fails on the first day you need it, because that is the first day it has run since last summer. Filters in (or out and washed), outdoor unit clear, and a thermostat test run in cooling mode now — the twenty minutes that prevent the July emergency. If the unit struggles, that is a May problem you can schedule calmly; the guide to <a href="/home/hvac-noises-decoded/">what HVAC noises mean</a> tells you which ones can wait and which cannot.</p>
<h2>Interior: the reset in honest order</h2>
<p>Smoke and CO alarms first — test every one, and note that expired units get replaced, not forgiven (<a href="/home/co-smoke-alarm-expiry/">expiry dates, explained</a> and <a href="/home/how-many-smoke-co-alarms/">how many a home needs</a>). Then the moisture check: winter condensation season leaves its signature as mould speckle in the same corners every year — treat the cause with <a href="/home/condensation-ventilation-that-works/">ventilation that works</a>, not just the stain. Then the deep clean itself, kitchen and appliances on a rotation (<a href="/home/deep-clean-schedule/">the schedule that keeps it real</a>), and the bedding-and-mattress refresh from <a href="/home/how-to-clean-and-care-for-a-mattress/">the mattress guide</a>.</p>
<h2>Energy, before the bills argue</h2>
<p>Spring is the cheap season for energy work: no heating running, no cooling yet. Draughts found now get fixed casually (<a href="/home/draught-proofing-mistakes/">the mistakes that waste the effort</a>), and if insulation or grants are on your list, the lead times are shortest exactly now — UK readers, <a href="/home/uk-insulation-grants/">the grants guide</a>.</p>
<p><em>Southern-hemisphere readers: run this list six months out of phase. The calendar label changes; the jobs do not.</em> And the whole system fits the in-browser <a href="/home/seasonal-home-maintenance-checklist/">seasonal checklist</a> — tick it there, not on paper you will lose.</p>"""),
("summer-cooling-checklist", "guide",
"The summer cooling checklist (before the heat arrives)",
"Shade and airflow strategy, the filter habit, the outdoor unit, and the honest limits of every option — including when a fan beats an aircon.",
"""<p>Summer comfort is mostly preparation with a calendar. Every item below works better done in late spring than in the first hot week — when every technician, and every air-conditioning unit, is already booked.</p>
<h2>The strategy before the hardware</h2>
<p>Cooling has an order of operations that saves money: <b>keep heat out, then move air, then cool air</b>. Keeping heat out is shading and timing — close east-facing blinds before you leave for work, open windows at night only while the outside air is genuinely cooler than in. Moving air is fans: a fan does not lower the temperature, it raises the rate your skin loses heat — which is why a fan plus an open night window often beats an aircon set two degrees lower. Only then does the aircon run, and it runs cheaper when the first two layers already did their work. If bills still shock you, the diagnosis lives in <a href="/home/energy-bill-high-unchanged/">why the bill is high when nothing changed</a>.</p>
<h2>The aircon service, honestly small</h2>
<p>Three things keep a split system or central AC honest through summer: a clean filter (check monthly in heavy use — the habit from <a href="/home/hvac-filter-change-habit/">the filter guide</a>), a clear outdoor unit (<a href="/home/ac-outdoor-unit-care/">the coil and clearance routine</a>), and vents that are actually open — closing most of them to "push air elsewhere" is a myth that raises pressure and costs. Strange sounds before the season's first run are worth ten minutes of <a href="/home/hvac-noises-decoded/">decoding</a>; grinding and squealing are not "character".</p>
<h2>Heat, cooking and the outside</h2>
<p>Every oven hour is an aircon hour. Summer kitchens move outside where the setup is safe — <a href="/home/outdoor-cooking-safety/">the outdoor cooking rules</a> exist because every one of them was broken somewhere first. Inside, pressure cookers, lids, and the grill on the balcony done properly make the kitchen's contribution to the heatwave a rounding error.</p>
<h2>Safety items that matter more in summer</h2>
<p>Window locks that let you sleep with airflow <em>and</em> security (<a href="/home/renter-security/">renter-friendly options</a> included); the bbq gas bottle stored upright and outside; and the dryer's lint habit — summer laundry loads climb, and <a href="/home/dryer-lint-every-load/">lint is the fire risk</a> that only ever needed sixty seconds.</p>
<p><em>Southern-hemisphere readers: six-month offset as always — this list is your December.</em> The interactive version lives on the <a href="/home/seasonal-home-maintenance-checklist/">seasonal checklist</a>.</p>"""),
("autumn-home-preparation", "guide",
"Autumn preparation: the month that decides your winter",
"Gutters, heating, seals and alarms — the four checks that turn winter from an emergency season into a season.",
"""<p>Autumn is the maintenance season disguised as a pretty one. Everything on this list is cheaper in October than in January, and every item exists because winter punishes its neglect. The working order: <b>water first, heat second, air third, alarms always.</b></p>
<h2>Water: the exterior harvest</h2>
<p>Clear the gutters after most leaves have fallen — a twice-over in leafy streets is normal, not obsessive (<a href="/home/gutter-cleaning-damage/">what clogged gutters actually damage</a>). Downpipes should gush in a storm, not trickle at the joint. Outside taps: in freeze-prone areas, disconnect hoses and insulate the tap. And walk the drains: a slow gully now is a <a href="/home/how-to-clear-a-slow-shower-drain/">ten-minute clear</a>; the same gully in December is a callout.</p>
<h2>Heat: service, then seal</h2>
<p>The boiler or furnace service belongs in autumn — engineers have open calendars, and a serviced boiler is a safe boiler; UK gas work is legally a Gas Safe-registered job (<a href="/home/uk-boiler-servicing/">what the service should include</a>). Then seal the envelope: draughts found on a windy October day are fixed in minutes with the right kit (<a href="/home/draught-proofing-mistakes/">the mistakes that undo it</a>), radiators bled cold-top-hot-bottom (<a href="/home/how-to-bleed-a-radiator/">the two-minute method</a>), and the thermostat schedule set for the season — a smart thermostat pays for itself fastest when it is programmed once, properly (<a href="/home/smart-thermostat-payback/">the honest payback math</a>).</p>
<h2>Air: condensation season opens</h2>
<p>Windows close for good now, and indoor moisture has nowhere to go — which is why mould seasons follow the heating season. Ventilation that actually works (short, sharp, whole-house rather than one cracked window) is the habit (<a href="/home/condensation-ventilation-that-works/">the system</a>), kitchen and bathroom extraction its helpers (<a href="/home/kitchen-ventilation-damp/">the kitchen specifics</a>). The washing machine gets its autumn attention too — <a href="/home/washing-machine-mould-door-seal/">the door-seal routine</a> — because closed-house months are mould's prime months.</p>
<h2>Alarms and the freeze plan</h2>
<p>Test every smoke and CO alarm the day the clocks change — heating season is CO season (<a href="/home/uk-carbon-monoxide-alarm-law/">the UK CO alarm rules</a>, and <a href="/home/how-many-smoke-co-alarms/">how many is right</a>). Then write the freeze plan on one note: where the main stopcock is, where the pipe lagging is weakest, and who shuts off the water if you are away when the freeze comes. A pipe burst is a five-minute emergency if the stopcock is known and a <a href="/home/small-leak-ripple-effect/">small-leak</a> attitude prevails all season.</p>
<p><em>Southern-hemisphere readers: your autumn lands around March — same list.</em> Tick it on the <a href="/home/seasonal-home-maintenance-checklist/">seasonal checklist</a>.</p>"""),
("winter-home-preparation", "guide",
"Winter preparation: the late-autumn final pass",
"The freeze plan, the 18-degree baseline, the rooms that pipe-burst first, and the habits that carry the season.",
"""<p>This is the last-call list — everything that must be true before the first hard freeze, and the small habits that carry the weeks after it. Most of it takes one weekend.</p>
<h2>The freeze plan, on one card</h2>
<p>Know three things by heart: where the main stopcock is and that it turns freely (a seized stopcock is a discovery nobody wants mid-burst); which pipes run through cold, unheated spaces — lofts, garages, cupboards on outside walls — and whether they are lagged; and where your stop-tap/exclusion valve is if the meter is outside. Lagging is cheap, but its real cost is the burst it prevents: a frozen-burst pipe releases more water in an afternoon than the household uses in a month, which is the arithmetic behind the whole <a href="/home/small-leak-ripple-effect/">ripple-effect guide</a>. Travelling over the freeze? Leave heating on low and a cupboard door open at the sink on the coldest nights.</p>
<h2>The temperature baseline, honestly</h2>
<p>Public-health guidance has long pointed to roughly <b>18&nbsp;°C (64&nbsp;°F)</b> as a healthy indoor baseline for living rooms — cold homes cost more than money (checked 11 September 2026; World Health Organization housing guidance and UK public-health advice). The savings live in heating <em>smart</em>, not cold: a programmed schedule that warms the rooms you use and lets the empty ones drift is what the <a href="/home/smart-thermostat-payback/">thermostat payback</a> math rewards. Rooms you close for winter get their water systems considered too — an unused bathroom is a freeze candidate.</p>
<h2>The season's quiet risks</h2>
<p>Heating season is CO season: alarms tested, and none past expiry (<a href="/home/co-smoke-alarm-expiry/">the expiry guide</a>; <a href="/home/uk-carbon-monoxide-alarm-law/">the UK rules</a>). Electric heaters get space and hard outlets — never an extension lead, which is also the rule behind <a href="/home/outlet-overloading-danger/">socket-overloading dangers</a> and the reason a breaker that keeps tripping is saying something (<a href="/home/why-does-my-circuit-breaker-keep-tripping/">what it is saying</a>). Dryer loads and electric blankets follow their labels. And the fridge works hardest in a hot kitchen but suffers most in a freezing one — garages and outbuildings in deep cold are no place for a fridge not rated for it (<a href="/home/fridge-temperature-setting/">the temperature logic</a>).</p>
<h2>The interior rhythm</h2>
<p>Short, sharp ventilation against condensation — the winter mould fight is won in ten minutes a day (<a href="/home/condensation-ventilation-that-works/">the method</a>) — radiators bled and unobstructed (sofa pressed against a radiator heats the sofa), and the freezer given its annual attention before the worst storms threaten outages (<a href="/home/how-to-defrost-a-freezer-properly/">defrost and the frozen-food clock</a>). If the budget for all this is tight, the honest order is: freeze plan, alarms, then everything else — the <a href="/home/emergency-repair-fund/">repair-fund rule</a> exists for exactly this season.</p>
<p><em>Southern-hemisphere readers: your winter list is the mirror image — run it in your autumn.</em> The <a href="/home/seasonal-home-maintenance-checklist/">seasonal checklist</a> holds the whole year.</p>"""),
]
