"""BRYME Home & DIY - expansion batch 22 (Sept 2026, tier-1 UK-winter focus):
the boiler-and-radiators cluster, shipped early so it is indexed before the
November-January search wave - low/high boiler pressure, radiators cold in
patterns, pipe lagging, EPC ratings, storage heaters, frozen condensate pipe.
Gas-work red line throughout: a Gas Safe registered engineer (UK) / licensed
technician (elsewhere) owns anything inside the boiler casing. Desk rules:
general information, never professional advice. Body links are root-level by
convention; build-routing prefixes them with /home/."""

HOME_ROADMAP_22 = [
("boiler-pressure-low-or-high", "fix",
"Boiler pressure too low or too high: the gauge, the filling loop, the line",
"The dial should sit near 1-1.5 bar cold. The safe top-up, the safe bleed-down, and the honest line: a boiler that keeps losing pressure belongs to an engineer.",
"""<p>Most UK combi boilers carry a small pressure gauge, and most winter boiler panics are that gauge reading wrong in one direction or the other. The healthy resting figure with the system cold is around 1 to 1.5 bar; when heating runs it rises a little, and that is normal. General information first, and the standing red line: anything involving the boiler's casing, the gas supply or a recurring fault belongs to a Gas Safe registered engineer - the steps below are the owner-level moves only.</p>
<h2>Too low (below about 1 bar): the usual winter complaint</h2>
<p>Systems lose small amounts of water over months - through micro-leaks at radiator valves and the bleed events that winter invites. The fix is the filling loop: the braided flexible connection under the boiler with one or two small valves. Boiler off or idle, slowly open the valve(s) and watch the gauge climb; close at 1.2 to 1.4 bar, and check the loop is fully closed afterwards (a cracked-open loop silently over-pressurises). Every boiler's loop looks slightly different - the manual's diagram wins over memory. Then run the heating and confirm the gauge settles back near where you set it.</p>
<h2>Too high (above about 2.5-3 bar): release, then think</h2>
<p>Bleed a radiator slightly with the system cold and the pressure falls as water leaves. If pressure climbs high when the heating runs and the safety discharge pipe drips outside, the expansion vessel may have lost its charge - that is an engineer visit, not a DIY item. And never leave a boiler sitting in the red zone; the pressure relief valve does its job once too often and weeps forever after.</p>
<h2>The pattern that matters</h2>
<p>One top-up before winter is maintenance. A boiler that needs re-pressurising weekly - or daily - has a leak somewhere: a radiator valve, a hidden pipe, or inside the boiler itself. Keep topping up and you are feeding a problem; that recurring-loss pattern is the point where the owner's job ends and <a href="/uk-boiler-servicing/">the annual-service discipline</a> becomes a repair call. Slot the gauge check into <a href="/winter-home-preparation/">the winter preparation routine</a> - two minutes in October that prevents the coldest morning in January.</p>"""),

("radiators-cold-top-or-bottom", "fix",
"Radiators cold at the top, bottom or middle: what each pattern means",
"Cold tops want bleeding, cold bottoms want flushing, one cold radiator wants a valve check. The pattern-by-pattern diagnosis before you spend anything.",
"""<p>Radiators fail in patterns, and each pattern points at a different five-pound fix. Read the pattern before touching a wrench - it is the difference between a ten-minute bleed and an unnecessary power-flush quote.</p>
<h2>Cold at the top, warm at the bottom</h2>
<p>The classic: hydrogen and air have collected at the top of the radiator, and hot water cannot fill it. The fix is a two-minute bleed with a radiator key - the full walkthrough is in <a href="/how-to-bleed-a-radiator/">the bleeding guide</a> (key, towel, half-turn, hiss-then-drip, and check the <a href="/boiler-pressure-low-or-high/">boiler pressure afterwards</a>, because bleeding lowers it). If the top goes cold again within weeks, either the system keeps taking in air or it is due the deeper clean below.</p>
<h2>Cold at the bottom, warm at the top</h2>
<p>The opposite pattern means sludge: years of iron oxide sediment have settled into the bottom of the radiator, and hot water is flowing over a mud bank. Bleeding does nothing here. The homeowner-scale move is a radiator flush (isolate, remove, hose out in the garden - heavy but doable) or, for a whole house of sludgy radiators, a professional power flush. Blackish water when you bleed is the sludge signature; an inhibitor top-up at the service prevents its return.</p>
<h2>One radiator cold all over</h2>
<p>First check its valves: a thermostatic valve that has not moved in months can stick closed - remove the head and free the pin with a gentle push. Both valves open and still cold: the radiator has stopped being invited to the party (a balancing question - the upstairs rooms pinching the flow), and gentle valve adjustments around the house even it out.</p>
<h2>Several radiators cold, or the whole system sulking</h2>
<p>That is the pattern that leads back to the boiler itself - check the <a href="/boiler-pressure-low-or-high/">pressure gauge first</a>, and if pressure is fine and the pump and timer behave, the repair conversation has begun. Slot the whole walk-through into <a href="/winter-home-preparation/">the October winter routine</a> - every radiator tested before the first cold week is the cheap version of this job. And for the money side of the same system, <a href="/smart-thermostat-payback/">the thermostat maths</a> and <a href="/draught-proofing-mistakes/">the draught work</a> cut the bill the radiators generate.</p>"""),

("pipe-lagging-winter-guide", "maintain",
"Pipe lagging: the winter job that costs pennies and prevents floods",
"Exposed pipes in lofts and outbuildings freeze before the pipes in walls. Foam sleeves, the outdoor tap, and the seams everyone misses.",
"""<p>The pipes most likely to freeze are the ones you can see: loft runs, garage and outbuilding feeds, and everything outdoors. Water sits still in a cold snap, the pipe in an unheated space hits freezing, and the ice quietly blocks the line until the pressure between blockage and tap splits it somewhere else - the whole failure chain is in <a href="/frozen-pipe-prevention/">the frozen-pipe guide</a>. Lagging is the prevention, it costs a few pounds a run, and an October afternoon finishes the whole house.</p>
<h2>The job</h2>
<p>Clamp-on foam sleeves come in diameters to match copper and plastic pipe; cut to length with scissors and slip them on, sealing the longitudinal seam and the joints with lagging tape. Cover the full run in unheated spaces - the loft run from tank to bathroom, the garage feed, anything within a foot of an external wall or vent. bends and elbows get cut sleeves or tape wraps; a corner left bare is the weak link. While you are up there: check the loft hatch, tank insulation and any draughts blowing across pipes - moving cold air freezes pipes faster than still cold, the same air-sealing logic as <a href="/draught-proofing-mistakes/">the draught guide</a>.</p>
<h2>The outside jobs</h2>
<p>The outdoor tap gets an insulated tap jacket - a pound or two - and its indoor shut-off gets identified so the line can be drained before a hard freeze. Any exposed waste pipes and the boiler's condensate run (a modern boiler essential) get the same sleeves; a frozen condensate pipe is the most common winter boiler stoppage of all, with its own fix in <a href="/frozen-condensate-pipe-fix/">the condensate guide</a>.</p>
<h2>The honest limits</h2>
<p>Lagging slows heat loss; it cannot heat a pipe. A pipe in a genuinely freezing loft needs the loft warmer (more <a href="/attic-insulation-basics/">insulation under it</a>, less draught over it) or a trace-heating cable on the worst runs. And lagging is the second line of defence after knowing where the stopcock is - <a href="/how-to-shut-off-water-main/">the shut-off walkthrough</a> is the ten-minute read that pays for every winter job on this page. Fold the whole afternoon into <a href="/autumn-home-preparation/">the autumn checklist</a> and the pipes go into every winter bored and ready.</p>"""),

("epc-rating-explained", "understand",
"The EPC rating explained: what the letters mean for your home",
"A to G, the 92-point scale of the same energy you are already paying for. What moves a rating, why sellers and landlords care, and the upgrades that genuinely shift the letter.",
"""<p>An Energy Performance Certificate grades a UK home's energy efficiency from A (the exceptional few) down to G, on a points scale where the mid bands are the national normal. Every sale and letting needs one, the certificate lists the home's rated features and a cost estimate, and the letter quietly prices itself into offers and rentability. The useful reframe: an EPC is a heat-leak report on the same energy your bill already measures - the two documents tell the same story from opposite ends.</p>
<h2>What actually moves the rating</h2>
<p>The assessor scores the fabric and systems: wall and loft insulation (<a href="/attic-insulation-basics/">the attic-first rule</a> again), glazing (with the honest maths in <a href="/single-glazing-payback/">the single-glazing payback</a>), heating system type and controls (a heat pump scores handsomely; an old electric-resistance system does not - <a href="/heat-pump-vs-gas-furnace/">the comparison</a>), boiler age and efficiency, renewable kit like solar, and draughts (<a href="/draught-proofing-mistakes/">the cheap wins</a>). Lighting contributes a little. The certificate's own "recommended improvements" list is genuine free advice: work through it roughly in cost order and the band follows.</p>
<h2>Who needs to care beyond the bill</h2>
<p>Sellers: a poor band shows up in every listing and gives buyers a negotiation line - the pre-sale insulation sprint is often money directly returned in the price. Landlords: rental minimums apply (the band floor has been tightening over time, and the exact current requirement is check-current-government-guidance territory rather than internet-forever territory - rules here have changed more than once and will again). Everyone else: the rating is a to-do list with a letter grade attached.</p>
<h2>The honest limits</h2>
<p>EPCs are standardised assumptions - occupancy, tariffs and real behaviour vary, so two identical-band homes can bill very differently (the meter knows things the assessor does not - <a href="/why-is-my-electric-bill-so-high/">the bill diagnosis</a> tells that half). Assessment details also lag the property: improvements made after the certificate only show on the next one. Book the reassessment after the work, not before the sale.</p>"""),

("storage-heaters-explained", "understand",
"Storage heaters explained: the night-charging way to heat",
"Bricks charged on cheap night electricity, warmed out all day. How they work, the tariff they require, the modern replacements, and the honest verdict.",
"""<p>Storage heaters are the heating system of the all-electric home: heavy insulated blocks of bricks that quietly drink cheap electricity overnight, then breathe that heat back out through the day. They only make economic sense paired with a night-cheap tariff - the pairing is the entire concept, and the tariff mechanics live in <a href="/off-peak-electricity-tariffs-explained/">the off-peak guide</a>. Get the tariff wrong and storage heaters are among the most expensive heat in the country; get it right and they are a sensible, silent, maintenance-free system.</p>
<h2>The controls, in order of importance</h2>
<p><b>Input (charge):</b> set in the evening for how cold tomorrow will be - high on a forecast freeze, low in mild weather. This is the single habit that decides the bill: charging full every night regardless of weather is the classic storage-heater money leak. <b>Output (boost/damper):</b> how much stored heat releases during the day - closed through the working day, opened for the evening. The modern learning models automate both and hold heat far better; 1990s manual units reward a disciplined human. The <a href="/smart-thermostat-payback/">thermostat-habit logic</a> applies exactly: consistency is the saving.</p>
<h2>The honest trade-offs</h2>
<p>Heat runs out by evening if the day turns colder than the forecast - storage, not on-demand. The bricks are heavy and the units chunky on the wall. And daytime top-up boosting on the expensive rate erases the economics - the daytime meter reading is where the complaints come from (<a href="/why-is-my-electric-bill-so-high/">the bill autopsy</a> applies). The modern replacements - high heat-retention models and the heat-pump-style units - charge the same way and release far more controllably; when old units die, replacement beats repair, the <a href="/repair-or-replace-appliances/">framework</a> applied to a wall.</p>
<h2>The verdict</h2>
<p>For an all-electric home with a night tariff and a predictable routine, storage heat remains a rational system - and the routine is learnable in a week. For everyone else, the same night-cheap electricity is better banked by the devices that can use it on demand. Either way, the bricks are only half the system: the tariff is the other half, and the two must be bought together.</p>"""),

("frozen-condensate-pipe-fix", "fix",
"Frozen condensate pipe: the boiler's winter stoppage and the safe thaw",
"The error code, the gurgling, the locked-out boiler on the coldest day. The 20-minute safe thaw, the prevention, and the line where the engineer takes over.",
"""<p>Modern condensing boilers produce a little acidic waste water - the condensate - which drains through a plastic pipe to a drain outside. On the coldest days of a British winter, that exposed pipe freezes solid; the boiler senses the blockage, locks out for safety, and the household loses heating and hot water on precisely the day it needs them. It is the most common winter boiler stoppage there is, and often the most fixable.</p>
<h2>Recognising it</h2>
<p>The signs stack neatly: the boiler will not fire or keeps cutting out, shows an error code (each brand's code differs - the manual's fault table names the condensate fault), gurgles or bubbles when it tries, and outside there is a plastic pipe - usually white, 32mm, running from the boiler through the wall to a drain - that is iced, bulged or visibly blocked. Confirmed pattern, safe thaw follows.</p>
<h2>The safe thaw, in order</h2>
<p>Warm water - hot from the tap, never boiling - poured slowly along the exposed pipe from the top works in most cases; a hot-water bottle or microwaveable pack held along the pipe does the same job gently. Give it twenty minutes and reset the boiler per the manual. Never boiling water (cracks plastic and wastes heat), never a naked flame, never salt or chemicals. The pipe thawed, the boiler reboots, and the system is back - subject to the pattern check below.</p>
<h2>The prevention that ends it</h2>
<p>Lag the exposed run with proper pipe insulation - the <a href="/pipe-lagging-winter-guide/">lagging guide</a> covers the whole routine - and if the pipe is the notorious external-over-a-drain layout that freezes annually, the permanent fix is rerouting internally or a wider insulated pipe: a small engineer job that pays for itself in one un-prevented lockout. And because the condensate freeze is a symptom of the same cold snap that splits water pipes, run the <a href="/frozen-pipe-prevention/">prevention checklist</a> the same afternoon.</p>
<h2>The line</h2>
<p>The thaw failed after an honest try, the error returns despite a clear pipe, or anything beyond the plastic pipe is suspected - internal blockages, pump faults, repeated lockouts: engineer territory, and in the UK that means Gas Safe registered, always. Fold the check into <a href="/winter-home-preparation/">the winter routine</a> - five minutes identifying which pipe is the condensate, in October, turns January's emergency into a non-event.</p>"""),
]
