# BRYME Home & DIY — roadmap batch 10: the kitchen & bedroom classics (8). Batch 21, 11 Sep 2026.
# House domain: researched-behavior guidance — mechanism first, brand-neutral, no invented figures.
# YMYL care: chemical-safety lines stated (never mix chlorine bleach with acids/ammonia;
# ventilation; appliance-manual overrides). General information, not professional advice.

HOME_ROADMAP_10 = [
("how-to-deep-clean-an-oven", "guide",
"How to deep clean an oven without ruining it",
"The self-clean vs manual decision, the rack trick that does the work overnight, and the safety lines that matter with oven cleaners.",
"""<p>An oven cleans itself about as much as a pan does — the baked-on layer builds quietly until smoke announces it. The good news: oven cleaning is patience work, not scrubbing work, if you let time do the chemistry.</p>
<h2>First decision: self-clean or manual</h2>
<p>Self-cleaning cycles burn residue to ash at very high temperatures — effective, but they lock the door for hours, smoke the kitchen, stress components near the end of an oven's life, and are best run when the house can ventilate and nobody needs the kitchen. The manual method is gentler on the machine and on the air: it is what this guide covers. Either way, pull the oven racks out first.</p>
<h2>The overnight soak method</h2>
<p>Racks soak in a bathtub or large sink in hot water with a generous dose of dish detergent (a dissolved dishwasher tablet works too) — by morning most grease wipes off with no fight. Inside the oven: remove loose crumbs, then paste a cleaning product or a strong soda-crystal solution onto the baked areas, close the door, and give it hours — dwell time, not elbow grease, is the active ingredient. Wipe thoroughly with clean water afterwards; cleaner residue smokes on the first preheat, so run the oven hot and empty for a short cycle before cooking food.</p>
<h2>The safety lines, stated plainly</h2>
<p>Never mix chemical cleaners — in particular, never combine chlorine bleach with anything acidic (vinegar included) or with ammonia; the reactions release dangerous gases. Ventilate while cleaning. Never use caustic oven cleaner on self-cleaning interiors or on aluminium parts, and follow your oven's manual where it disagrees with any internet advice, this page included. And skip the foil-on-the-floor trick: it can block airflow and damage the enamel — a real example of a hack that costs more than it saves, in the same family as <a href="/home/vinegar-in-the-dishwasher/">the dishwasher vinegar question</a>.</p>
<h2>Keeping it clean</h2>
<p>A sheet of foil on the rack <em>below</em> the one you cook on (not the floor), a wipe while the oven is barely warm but not hot, and an annual deep clean is a routine most kitchens genuinely keep. Pair the habit with the rest of the desk's appliance work — <a href="/home/how-to-clean-a-washing-machine/">washing machine care</a> and <a href="/home/fridge-coils-twice-a-year/">fridge coils</a> — and the whole kitchen ages slower.</p>"""),
("how-to-clear-a-slow-shower-drain", "guide",
"How to clear a slow shower drain, in order of effort",
"Pull, don't push: the hair mat, the zip tool, the safe flush — and when a slow drain is a job for a professional.",
"""<p>A shower that ankle-pools is almost always one thing: hair knit with soap scum into a plug a few inches below the grate. The fix is removal, in that order — pulling beats pushing every time, because pushing (drain cleaners, plungers before pulling) packs the plug deeper.</p>
<h2>Stage one: the hook and the torch</h2>
<p>Shine a light into the drain. Most showers show you the problem directly: a mat of hair over the first bend. Pull it with a bent wire hook, a barbed plastic strip (a few pounds at any hardware shop) or a firm twisting motion with gloved fingers. This alone clears a large share of slow showers. Run hot water; if the pool drains freely, you are done.</p>
<h2>Stage two: the flush</h2>
<p>If flow is better but still lazy, flush the remaining film: a kettle's worth of hot (not boiling-standing) water, then a few minutes of very hot tap water. The classic soda-crystal or enzymatic treatments work on soap buildup with dwell time — follow the product's own instructions and ventilate. <b>The safety line this desk keeps drawing:</b> never mix drain chemicals, and never plunge a drain you have just chemically treated — splashback is genuinely dangerous. If chemical approaches and mechanical pulling have both failed, stop; the remaining fixes belong to a professional or at least a proper drain auger and the patience to read the room.</p>
<h2>When it is not the grate</h2>
<p>If multiple fixtures slow at once, or water gurgles elsewhere when the shower drains, the blockage is downstream in the shared pipe or there is a venting issue — that is stage four, and stage four is a plumber. The same judgement ladder as <a href="/home/how-to-fix-a-slow-draining-sink/">the slow sink guide</a> and <a href="/home/how-to-unblock-a-toilet/">the toilet method</a>: remove what you can see, flush gently, and know where your competence ends. For the pattern behind all three, see <a href="/home/small-leak-ripple-effect/">why small plumbing symptoms ripple</a>.</p>
<h2>Keeping it clear</h2>
<p>A mesh drain cover costs almost nothing and catches the hair before the pipe does — empty it into the bin, rinse, done. Sixty seconds a week buys back all the Sunday afternoons this guide describes.</p>"""),
("how-to-defrost-a-freezer-properly", "guide",
"How to defrost a freezer properly (and when not to bother)",
"Frost is insulation: when ice is thick enough to cost you money, the safe defrost method, and the food-safety clock that runs during it.",
"""<p>Frost looks harmless. It is not: it is insulation where insulation does not belong, forcing the compressor to run longer for the same cold. A thin dusty layer is normal for modern frost-free models — but if you can measure the ice in centimetres on an older manual-defrost freezer, the machine is working overtime and the fix is an afternoon.</p>
<h2>The food-safety clock comes first</h2>
<p>Before anything unplugs, plan the food: a full freezer holds temperature longest — keep the door shut right up to the moment you start; frozen food grouped together in bags or under blankets stays frozen for hours; and anything that thaws is used-cooked-or-discarded, not refrozen raw. Cool bags with ice packs from the fridge section buy margin for the genuinely loaded freezer. This is the same discipline as <a href="/home/fridge-not-cold-enough/">diagnosing a warm fridge</a>: food safety outranks convenience, always.</p>
<h2>The method that works</h2>
<p>Unplug, shelves out, towels on the floor and in the base, bowls of hot water inside on a board with the door closed — the steam does the work in an hour or two; open periodically and lift loosened sheets of ice out by hand. Never chip at ice with knives or screwdrivers: punctured evaporator lines kill freezers more surely than any frost ever did. A hairdryer can help at a distance, standing clear of meltwater — electricity and water share this project, so respect the geometry.</p>
<h2>Restarting right</h2>
<p>Dry the interior, restart, and let the freezer reach temperature before restocking — hours, not minutes — then run the honest maintenance loop: check the door seal (the <a href="/home/fridge-door-seal-test/">paper test</a>), keep the <a href="/home/fridge-coils-twice-a-year/">coils dusted</a>, and set a calendar reminder for next year. Frost that returns unusually fast usually means the seal, not the freezer — the same first-suspect logic as the <a href="/home/small-leak-ripple-effect/">ripple-effect guide</a>.</p>"""),
("how-to-clean-and-care-for-a-mattress", "guide",
"How to clean a mattress, and the habits that double its life",
"Vacuum, spot, air, rotate: the annual ritual, the stain rules, and the honest signs it is replacement time.",
"""<p>You spend a third of your life on it and probably clean it never. A mattress needs surprisingly little — one honest session a year plus two cheap habits — and the reward is years of extra life for the most expensive thing in the bedroom.</p>
<h2>The annual session</h2>
<p>Strip everything and wash the bedding hot per its labels while the mattress breathes. Vacuum the whole surface — seams, tufts, piping — with the upholstery tool; the dust-mite material and skin flakes leave with the airflow. Spot-clean stains with a barely-damp cloth and a small amount of mild detergent, dabbing never soaking: a wet mattress is a mould problem waiting for a calendar slot, so let it dry fully — hours by an open window or a fan — before anything touches the bed again. Memory foam especially drinks water and resents it; damp-cloth-only is the foam rule.</p>
<h2>The two habits that actually matter</h2>
<p><b>Rotate head-to-foot every few months</b> (flip only if the manufacturer says the mattress is double-sided — most modern ones are one-sided and flipping damages them). Rotation spreads the compression so the surface ages evenly. <b>Use a washable protector.</b> The cheapest insurance in homecare: sweat is the slow killer of foams and fabrics, and a protector launders what the mattress otherwise absorbs. Pair with the bedding rhythm in <a href="/home/how-to-clean-a-washing-machine/">the washing-machine guide</a> and the bedroom moisture context in <a href="/home/condensation-ventilation-that-works/">condensation and ventilation</a> — a damp bedroom ages a mattress from beneath.</p>
<h2>Replacement, honestly</h2>
<p>Sag you can see, dips that swallow a rolled tennis ball, springs announcing themselves, or mornings that hurt in beds you did not hurt in elsewhere — those are replacement signals, not cleaning failures. A mattress that has simply aged clean but tired is a budget decision; a mattress with structural sag is a health decision. Everything else on this page is how you push that decision years into the future.</p>"""),
("washing-machine-mould-door-seal", "guide",
"The washing machine door seal: mould's favourite apartment",
"Why front-loader gaskets grow the black ring, the cleaning routine that actually works, and the two habits that keep it away.",
"""<p>The black speckling on a front-loader's rubber door seal is not dirt arriving from your clothes — it is mould growing in the gasket's design: a warm, dark, perpetually damp fold that the machine's own cycles barely reach. You cannot disinfect your way out of a moisture problem; the fix is a routine plus two habits.</p>
<h2>The cleaning routine that works</h2>
<p>Pull the seal's fold back gently with a cloth — most of the black material lives inside the fold, along with the hair, coins and biofilm the machine thanks you for. Clean the fold with hot water and detergent first; where speckling persists, a dilute bleach wipe used strictly per the product label (gloves, ventilation, never mixed with anything) clears the surface growth — then run the machine's hottest cycle empty to rinse the whole drum and the insides of the gasket. Clean the detergent drawer and its slot while you are there: the same biofilm, one shelf over — the fuller method is in <a href="/home/how-to-clean-a-washing-machine/">the washing-machine guide</a>.</p>
<h2>The two habits that keep it away</h2>
<p><b>Leave the door and drawer open between washes.</b> The single highest-impact habit in front-loader ownership: the gasket dries, the mould starves. <b>Use less detergent, and skip most softener.</b> Excess detergent does not clean harder — it deposits biofilm that mould eats; modern machines with modern detergents need far less than the cap's biggest line, and softener is a film in search of a surface. Under-dosing feels wrong and works right.</p>
<h2>When the seal has lost</h2>
<p>If growth keeps returning despite the routine, or the rubber has hardened, cracked or smells past rescue, the gasket is replaceable on most models — sometimes a straightforward DIY job, sometimes a service call depending on the machine. Check the manual and parts availability before deciding; and if the machine itself is the kind that frames every repair decision, the desk's <a href="/home/renter-vs-owner-repairs/">renter-versus-owner repair guide</a> and <a href="/home/someday-maintenance-cost/">the someday-cost rule</a> are the honest frame for replace-versus-restore.</p>"""),
("how-to-descale-a-kettle", "guide",
"How to descale a kettle (and why it keeps coming back)",
"Limescale explained in one paragraph, the descale method that respects your kettle, and the habit that halves the problem.",
"""<p>That chalky crust inside the kettle is limescale — calcium carbonate left behind when hard water boils. It is harmless to drink, ugly to look at, and expensive to ignore: scale insulates the heating plate, so the kettle works longer for the same boil and dies younger. Descaling is the rare appliance chore that takes ten active minutes and pays back visibly.</p>
<h2>The method</h2>
<p>Half water, half white vinegar, up to about the scale line — or a dedicated descaler per its own instructions, if you prefer the odourless route. Bring to the boil, switch off, and let it sit for an hour or so; heavy scale gets a second gentle warm pass rather than a harder scrub. Empty, rinse thoroughly, then boil-and-discard two full kettles of fresh water so the next cup of tea tastes like tea. Wipe the filter spout with a cloth while you are there. What you should never do: scrape enamel or heating plates with metal, or mix descalers — the vinegar method alone, patiently repeated, wins.</p>
<h2>Why it keeps coming back, and the honest fixes</h2>
<p>Scale returns because hard water is the tap's nature, not the kettle's fault. The habit that halves it: empty the kettle after use instead of letting last night's water evaporate onto the plate, and descale on a calendar rhythm — monthly in hard-water areas, quarterly elsewhere — before the crust becomes a geology. A boiling-water tap or filter jug changes the arithmetic but not the principle. This is the same slow-then-sudden appliance logic as <a href="/home/fridge-coils-twice-a-year/">dust on fridge coils</a> and <a href="/home/washing-machine-heavy-items/">load discipline in washers</a>: small chemistry, ignored, becomes the repair bill later — the house rule the <a href="/home/someday-maintenance-cost/">someday-cost guide</a> is built on.</p>"""),
("season-cast-iron-pan", "guide",
"Seasoning a cast-iron pan: the honest, small version",
"What seasoning actually is, the stovetop routine that fixes a sticky or rusty pan, and the two things that undo it.",
"""<p>Cast iron's mystique is oversold; its chemistry is not. Seasoning is just oil baked onto the metal until it polymerises into a hard, slick, rust-blocking layer. It is not a fragile butterfly — it is plastic, essentially — and it repairs in minutes, which is why generations of cooks kept one pan for a lifetime.</p>
<h2>The routine, small and honest</h2>
<p>Start clean and dry: scrub off any rust with steel wool or a scouring pad (rust is a repair, not a funeral), wash with washing-up liquid like a normal object — the "never use soap" myth predates modern mild detergents and can retire. Dry the pan on the heat. Rub a thin, almost stingy film of a neutral high-smoke-point oil over every surface, then wipe it with a paper towel as if you changed your mind — the layer should look nearly dry. Heat the pan (oven, upside down, or stovetop on medium) until it passes through smoky and settles past it, then cool. That is one round; three rounds build a cooking surface. Every sauté that follows adds another invisible coat — this is why daily use is the real seasoning programme.</p>
<h2>The two things that undo it</h2>
<p>Soaking — water is cast iron's only real enemy, and a pan left in the sink overnight arrives at morning rusty (the rescue is the steel-wool step above, not regret). And dishwasher cycles, which strip months of polymer in an hour. Sticky, patchy surfaces mean too much oil per round — strip back with hot water and a scrub, and restart thinner. That is the entire art. For the wider keep-things-working philosophy, the desk's <a href="/home/basic-toolkit-checklist/">toolkit checklist</a> and <a href="/home/emergency-repair-fund/">repair-fund rule</a> apply to cookware too: maintain the good one, and it outlives three non-stick replacements.</p>"""),
("fridge-temperature-setting", "guide",
"The fridge temperature setting you should actually use",
"The food-safety target, the thermometer test most fridges fail, and why the dial numbers are lying to you.",
"""<p>The dial in your fridge says 1 to 5 and tells you nothing, because dial numbers are settings, not temperatures — the same fridge on the same number is colder in January, fuller behaves differently, and the coldest spot is rarely where the salad lives. Food safety does not care about the dial; it cares about one number.</p>
<h2>The target</h2>
<p>Food-safety guidance is consistent on the target: keep the fridge <b>at or below 4°C (40°F)</b> — cold enough to slow the bacteria that spoil food and cause illness, warm enough not to freeze the lettuce. Freezers belong at roughly −18°C (0°F). Those two numbers are the whole assignment; public-health agencies repeat them because most households have never measured either.</p>
<h2>The test that settles it</h2>
<p>Buy or borrow a fridge thermometer — inexpensive and permanent. Place it mid-shelf (not the door, which swings warm; not pressed to the back wall, which is the coldest plate), leave it overnight with the door shut, and read the truth in the morning. Adjust the dial a notch, wait a full day, read again — one notch at a time, because overcorrection is how salads freeze. Check where your fridge's cold and warm zones actually are once, then store accordingly: dairy and raw meat toward the back and bottom (coldest, and raw meat belongs lowest so it cannot drip onto ready-to-eat food), condiments in the door, herbs and tender produce in the warmest safe shelf.</p>
<h2>The maintenance that keeps the number true</h2>
<p>A fridge holding 4°C efficiently is a fridge with clean coils and a working seal — the two services this desk keeps returning to (<a href="/home/fridge-coils-twice-a-year/">the coil ritual</a>, <a href="/home/fridge-door-seal-test/">the seal test</a>). Overpacked shelves block the airflow that distributes cold, which is why the fridge after a big shop runs warm for a day — and why <a href="/home/fridge-not-cold-enough/">the warm-fridge triage</a> starts with airflow and door habits before it ever suspects the machine. One thermometer, fifteen minutes a year, and the most important appliance in the house stops being a guess.</p>"""),
]
