"""BRYME Home & DIY - expansion batch 21 (Sept 2026, tier-1 focus, volume 6):
the cost-to-run series (8 appliance pages feeding the electricity calculator
cluster) plus the heat-pump-vs-gas-furnace decision page. Rates hedged
throughout: US average residential about 18-19 cents/kWh (EIA-derived, Sept
2026), UK Ofgem cap unit rate 26.11p Jul-Sep 2026 - your bill wins. Desk
rules: general information, figures only where sources support them. Body
links are root-level by convention; build-routing prefixes them /home/."""

HOME_ROADMAP_21 = [
("cost-to-run-a-dehumidifier", "understand",
"Cost to run a dehumidifier: the damp solution that costs less than you think",
"A 300-watt dehumidifier left on all day costs roughly 40-60p or 50-70 cents. The per-day and per-month maths, the laundry-mode exception, and when the machine pays for itself.",
"""<p>The dehumidifier sounds expensive - a box working all day in the hallway - but it is one of the cheapest appliances in the house per hour of usefulness. A typical home unit draws 200-400 watts, so at an average US rate near 18-19 cents per kWh (about 26p in the UK) an eight-hour day costs roughly 50-70 cents or 40-60p, and most damp problems need far less than eight hours. Run your own model's wattage through the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a> for the exact figure.</p>
<h2>What moves the cost</h2>
<p>Size and mode. A small 200 W unit in a bedroom costs pennies; a whole-house 500 W+ machine costs several times that. The laundry-drying mode (aiming at a rack of wet clothes) runs the machine hard for 4-6 hours - often still cheaper than a dryer load, and gentler on the clothes. And the target matters: a machine set to keep chasing bone-dry air works constantly, while one set to a sensible humidity (around 50-55%) cycles off most of the time.</p>
<h2>When it pays for itself</h2>
<p>Three ways. First, comfort at lower heating cost: dry air feels warmer, so the dehumidifier can let the thermostat sit lower - the <a href="/thermostat-settings-that-save-money/">setback principle</a> in reverse. Second, protection: condensation on windows, mould blooms behind furniture and peeling paint are expensive repairs, and the machine prevents them - the moisture chain runs through <a href="/condensation-ventilation-that-works/">ventilation that works</a> and <a href="/mould-after-a-flooded-room/">the mould clock</a>. Third, drying laundry indoors without firing the tumble dryer: the rack-and-dehumidifier combo costs a fraction per load (see <a href="/cost-to-run-a-tumble-dryer/">the dryer maths</a> for the contrast).</p>
<h2>The honest limits</h2>
<p>A dehumidifier treats the symptom - if the damp enters through a wall, a leaking pipe or a life-without-ventilation routine, fix that first (<a href="/hidden-water-leak-meter-test/">the meter test</a> finds the pipe version). And if the machine runs constantly yet the room never dries, the source is bigger than the box - that is a surveyor conversation, not an appliance one.</p>"""),

("cost-to-run-a-tumble-dryer", "understand",
"Cost to run a tumble dryer: per load, per month, per year",
"At roughly 3,000 W, a dryer hour costs around 55 cents or 55p. The per-load maths, the heat-pump exception, and the rack combo that costs pennies.",
"""<p>The tumble dryer is usually the most expensive plug-in appliance in the home, and it earns the title honestly: about 3,000 watts for an hour-plus per load. At an average US rate near 18-19 cents per kWh (about 26p on the UK cap rate), one load costs roughly 55-65 cents or 55-60p in electricity - and a household doing a load a day spends in the region of 16-20 dollars or pounds a month, every month. Run your dryer's cycle time and your own rate through the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a> for the precise figure.</p>
<h2>The dryer ladder</h2>
<p><b>Vented (cheapest to buy, dearest to run):</b> a 3 kW element dumping warm damp air outside. <b>Condenser:</b> similar power, slightly less efficient. <b>Heat-pump dryer (the modern answer):</b> it recycles its own heat, using roughly half to a third of the power per load - and since dryers are replaced rarely, the running-cost saving usually repays the higher price over the machine's life, the same long-arithmetic as <a href="/repair-or-replace-appliances/">repair-or-replace</a>. Check the energy label's kWh per cycle rather than trusting a category.</p>
<h2>Cutting the cost without buying anything</h2>
<p>Spin harder first: an extra spin cycle removes water for pennies and shortens dryer time substantially. Dry full (but not overloaded) loads back-to-back so the drum stays warm. Clean the lint filter every load and the vent annually - a choked vent adds time and is also the fire-risk subject of proper dryer maintenance. And in any month where the bills shout, the rack-and-dehumidifier combo dries a load for pennies: <a href="/cost-to-run-a-dehumidifier/">the dehumidifier maths</a> shows the contrast. Line-drying in season stays free - <a href="/indoor-drying-rainy-season/">the indoor-drying guide</a> covers the damp-weather version.</p>
<h2>The honest comparison</h2>
<p>The dryer is a convenience appliance, and there is no shame in convenience - but price it honestly: it is often the single largest electricity line after heating, cooling and water heating, right up there with the <a href="/cost-to-run-air-conditioning/">air-conditioning maths</a>. Knowing the per-load figure turns "just one more cycle" into a decision instead of a habit.</p>"""),

("cost-to-run-air-conditioning", "understand",
"Cost to run air conditioning: per hour, per day, per summer",
"A window unit costs roughly 15 cents or 20p an hour; central air five times that. The honest ranges, the settings that slash them, and the fan partnership.",
"""<p>Air conditioning is the biggest summer line on the bill, and its range is enormous because the machines range from a 900 W bedroom portable to a 3,500 W central system. The honest anchor figures: a window or portable unit around 1,000-1,500 W costs roughly 18-28 cents or 20-35p per hour at average US/UK rates; central air near 3,500 W costs roughly 60-70 cents or up to a pound an hour while actually running (it cycles off at temperature, so real hourly averages land lower). Eight hot hours a night, every night of a hot month: anywhere from 45 to 170 dollars - which is why the settings matter more than the machine. Price your own unit through the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a>.</p>
<h2>The levers, biggest first</h2>
<p><b>Thermostat discipline:</b> every degree cooler adds real cost; a setpoint around 24-25 C (75-77 F) with a fan for the wind-chill effect is the efficiency sweet spot - <a href="/ceiling-fan-direction-summer-winter/">fans on summer mode</a> make a higher setpoint feel fine, and fans cool people, not rooms, so they go off when you leave. <b>Block the sun before it enters:</b> blinds closed on the sunny side, awnings or <a href="/window-film-for-heat/">window film</a> on the worst windows - preventing heat beats removing it. <b>Maintenance:</b> a choked filter makes the machine run long and hard; check it monthly in season. <b>Timing:</b> pre-cool before the peak-price hours if you are on a time-of-use plan (<a href="/off-peak-electricity-tariffs-explained/">the tariff guide</a>), and let the <a href="/attic-insulation-basics/">insulation</a> hold the cool.</p>
<h2>The sizing sanity check</h2>
<p>An oversized unit cools fast, shuts off damp, and leaves a clammy room; an undersized one runs forever without getting there. The right size for a bedroom is far smaller than the sales floor suggests - and for many Tier-1 homes, the honest cheapest summer is one right-sized unit in the room you actually sleep in, not the whole-house default.</p>"""),

("cost-to-charge-an-ev-at-home", "understand",
"Cost to charge an EV at home: the per-mile maths",
"A full home charge costs roughly 7-11 dollars or pounds at average rates - about a fifth to a tenth of petrol miles. The maths, the off-peak halving, and the honesty about public rapid charging.",
"""<p>Home charging is where electric cars earn their keep. The arithmetic is simple: a typical EV does roughly 4 miles per kWh, so a 40 kWh charge (about 160 miles) at an average US residential rate near 18-19 cents per kWh costs around 7-8 dollars - call it 5 cents or so per mile. In the UK at the 26p cap rate the same charge is about 10 pounds, roughly 6p a mile. Compare petrol at the same miles and the home-charged EV usually wins by a factor of three to five. Your own tariff and consumption vary - the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a> prices your exact rate per charge.</p>
<h2>The overnight upgrade</h2>
<p>On a time-of-use tariff the maths improves again: overnight rates commonly land at a third to a half of daytime rates, which drags the per-mile cost down toward 2-3p - the reason <a href="/off-peak-electricity-tariffs-explained/">off-peak tariffs</a> and EVs are sold together. A 7 kW home wallbox adds about 25-30 miles of range per hour, so a nightly plug-in covers a typical commute comfortably; a normal socket (2.3 kW) manages too, just slower.</p>
<h2>The honest caveats</h2>
<p><b>Public rapid charging</b> is the exception that erases the saving - per-kWh prices at motorway chargers can rival or beat petrol per mile, which is fine as an occasional booster and expensive as a habit: home charging is the financial case. <b>The charger itself</b> costs real money installed (varies wildly by country and grant schemes - check what currently applies where you live). <b>And the bill timing:</b> an EV adds a visible new line to the electricity bill even as the petrol line vanishes; households sometimes double-count and panic. Track kWh, not vibes.</p>
<h2>When home charging does not apply</h2>
<p>Street-parked households charging on public networks live on different maths entirely - for them the EV case rests on charger availability and workplace charging, not the home rate. For everyone with a driveway, though, the pairing of night rates and a plug is the quietest ongoing saving in motoring - and a good companion to the whole-house tariff strategy in <a href="/why-is-my-electric-bill-so-high/">the bill diagnosis</a>.</p>"""),

("cost-to-run-a-hot-tub", "understand",
"Cost to run a hot tub: the honest monthly figure",
"Realistic running costs range from about 25 to 90 a month depending on season, use and insulation. Where the money actually goes, and the habits that halve it.",
"""<p>Nobody regrets buying a hot tub like they regret heating one. The honest running-cost answer: a well-insulated modern tub costs roughly 25-50 a month in use, an older or poorly-insulated one in a cold climate can pass 90, and a lightly-used summer-only tub lands far below - wide ranges because climate, electricity price and habits swing the number more than the tub does. The <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a> prices your own rate against the components below.</p>
<h2>Where the money goes</h2>
<p><b>The heater</b> (typically 2-3 kW) is the headline, but it mostly replenishes losses: a well-insulated tub in mild weather heats an hour a day; a windy-deck tub at freezing temperatures can heat six. <b>The circulation pump</b> runs nearly continuously on many models (150-300 W - a real base-load line, the same arithmetic as <a href="/standby-power-real-numbers-your-meter/">the standby audit</a>). <b>The jets</b> (1-3 kW) cost pennies per soak. Add the water-treatment chemicals and the odd filter, and the true monthly figure is electricity plus a modest extras line.</p>
<h2>The habits that halve it</h2>
<p><b>Keep the cover on and the cover good</b> - a waterlogged, sagging cover is the number one cost multiplier; heat escapes through it like an open window. <b>Hold 37-38 C rather than hotter</b> - every degree adds standing cost. <b>Windbreak the tub</b> (fence, hedge, spa enclosure) - wind strips heat from a cover faster than cold does. <b>Check the tariff:</b> heating overnight on an off-peak plan where the tub tolerates it suits the <a href="/off-peak-electricity-tariffs-explained/">time-of-use logic</a>. And in long absences, draining and shutting down beats heating an empty tub for nobody.</p>
<h2>Before you buy one</h2>
<p>Ask the seller for the heater wattage, the circulation pump's draw and an honest estimate of daily heating hours in your climate - those three numbers times your rate is the real cost of ownership, and the difference between tubs is bigger than the difference between price tags. The running cost, not the sticker, decides whether a hot tub is a luxury you use or a bill you resent.</p>"""),

("cost-to-run-a-dishwasher", "understand",
"Cost to run a dishwasher: per cycle, and versus washing up",
"A modern cycle uses about 1 kWh - roughly 20 cents or 20p - and a full machine usually beats hand-washing on energy and water. The maths, and the habits that keep it true.",
"""<p>The dishwasher has a reputation for expense that the numbers do not support. A modern machine on an eco cycle uses roughly 0.8-1.5 kWh per cycle - about 15-30 cents or 15-30p at average US/UK rates - plus a small amount for water heating if your machine draws hot water from the tank. A daily-dishwashers household spends in the region of 5-9 a month on cycles. Price your own machine's label figure at your own rate with the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a>.</p>
<h2>The hand-washing comparison</h2>
<p>Done honestly - hot tap running, rinsing under the stream - hand-washing a full load's worth of dishes typically uses markedly more hot water and energy than the machine, which is why efficiency agencies keep concluding that a <b>full</b> dishwasher usually wins on both energy and water. The caveats decide it: the machine wins when it is full (halving the loads halves the cost), when you skip the pre-rinse (modern detergents want dirty plates; rinsing first just doubles the water), and when the machine is the modern efficient kind - a 25-year-old dishwasher is a different animal, the <a href="/repair-or-replace-appliances/">repair-or-replace arithmetic</a> applies.</p>
<h2>The cheap wins</h2>
<p>Run eco mode as the default - it stretches cycle time to cut energy, which is the right trade for most households. Keep the filter clean and the spray arms clear (a machine quietly choking costs more per cycle - <a href="/dishwasher-not-draining-first-checks/">the drainage checks</a> cover the failure mode). Load it properly so you never re-wash: <a href="/dishwasher-loading-mistakes/">the loading guide</a> is the highest-yield five minutes here. And if you are on a time-of-use tariff, the delay button moves the cycle into the cheap hours - <a href="/off-peak-electricity-tariffs-explained/">the tariff logic</a> applied to the easiest appliance in the house.</p>"""),

("cost-to-run-a-fan", "understand",
"Cost to run a fan: the summer bargain hiding in plain sight",
"A pedestal or ceiling fan costs around a penny or a cent for eight hours. The full maths, and the fan-plus-AC partnership that cuts the summer bill.",
"""<p>The fan is the cheapest comfort in the house by a wide margin, and the numbers are almost comic: a typical pedestal fan draws 40-60 W and a ceiling fan similar, so eight hours overnight costs around 6-8 US cents or 5-7p at average rates - roughly a penny an hour. Even a chunky tower fan at 80-100 W stays in single-digit pence per night. Run any model's wattage through the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a> and watch the annual figure refuse to be scary.</p>
<h2>Why the pennies matter</h2>
<p>Because the fan's job is to make the expensive machines unnecessary. Moving air strips heat off skin, so a room that felt 25 C stuffy feels comfortable with a breeze - the wind-chill effect means the thermostat can sit 2-3 degrees higher with no loss of comfort. That is the whole efficiency play: <a href="/ceiling-fan-direction-summer-winter/">fans on summer mode (counterclockwise)</a> paired with the air-conditioning setpoint from <a href="/cost-to-run-air-conditioning/">the AC cost page</a> typically trims the cooling bill by more than the fans cost in a decade. In milder climates and spring shoulder-seasons, the fan alone often carries the entire summer.</p>
<h2>The one rule that keeps it free</h2>
<p>Fans cool people, not rooms - the breeze works on skin, not on the air. A fan spinning in an empty room is paying to stir nothing, which is why energy agencies put "off when you leave" in every fan guidance ever written. The standing exception: an extractor fan in a hot kitchen or bathroom is removing heat and moisture, so it can legitimately run after you leave - <a href="/condensation-ventilation-that-works/">the ventilation guide</a> covers that job.</p>
<h2>Choosing between them</h2>
<p>Ceiling fans beat pedestals for whole-room comfort and win the year-round prize with the winter reverse switch; pedestals win on price, portability and bedrooms; towers win on looks and lose slightly on noise-per-airflow. All three cost pennies - the wrong fan is not an expense problem, it is just an uncomfortable one. For the full comparison of the two domestic champions, <a href="/ceiling-fan-vs-standing-fan/">the ceiling-versus-pedestal rundown</a> settles it.</p>"""),

("cost-to-run-a-gaming-pc", "understand",
"Cost to run a gaming PC (and console): per hour, per year",
"A gaming PC under load costs roughly 7-12 cents or 7-10p an hour; a console about half that. The honest session maths, the idle problem, and the settings that trim it.",
"""<p>Gaming hardware is a mid-weight appliance: a gaming PC drawing 350-500 W under load costs roughly 7-12 US cents or 7-10p per hour at average rates, a games console at 150-250 W costs about half that, and either way a serious 3-hour-a-day habit lands in the region of 8-14 dollars or pounds a month - less than the household's <a href="/second-fridge-freezer-cost/">second fridge</a>, more than its <a href="/cost-to-run-a-fan/">fans</a>. Price your own rig through the <a href="https://thebryme.com/tech/tool/electricity-cost-calculator/">electricity cost calculator</a> - wattage shows in the GPU's spec or any monitoring tool.</p>
<h2>The honest session maths</h2>
<p>Not all gaming hours are equal: competitive shooters and ray-traced blockbusters push the whole system, while strategy and indie titles may draw half. Monitors and peripherals add 20-50 W. The console's fixed hardware makes it the cheaper per-hour machine by design - it also throttles less and idles better, which matters more than most players expect (below).</p>
<h2>The idle problem</h2>
<p>The real cost leak is not the gaming hours - it is the other 21. A rig left on overnight, monitors awake on the desk, the PC on but "resting" at 80-150 W: that base load can quietly match the gaming load itself. Sleep settings (display off at 10 minutes, sleep at 30), shutting down for the night, and checking what the machine draws at idle are the whole fix - the meter-test method in <a href="/standby-power-real-numbers-your-meter/">the standby audit</a> works identically on a desk. Consoles: enable their rest-mode power caps rather than leaving them fully on.</p>
<h2>Trimming without losing frames</h2>
<p>Frame-rate caps (capping at 60 or 120 rather than uncapped) cut GPU draw substantially for a barely-noticeable trade; quality presets that drop 10% of the visuals save double-digit watts; and undervolting - for the comfortable - reduces power at the same performance. None of this turns gaming expensive or free: at pennies an hour, the hobby remains one of the cheaper ways to spend an evening - the point of the maths is that the idle hours, not the play hours, are the ones worth fixing. For the summer footnote, a hard-gaming room in a heatwave adds to the cooling load in <a href="/cost-to-run-air-conditioning/">the AC maths</a>.</p>"""),

("heat-pump-vs-gas-furnace", "understand",
"Heat pump or gas furnace? The honest 2026 comparison",
"A heat pump moves three or four units of heat per unit of electricity; a furnace burns gas at 80-95% efficiency. The running-cost comparison, the installation reality, and who each one actually suits.",
"""<p>The heating decision of the decade, reduced to one sentence: a heat pump delivers warmth at a fraction of the electricity a furnace's resistance equivalent would need, while a gas furnace delivers heat from cheaper fuel with simpler technology - and which wins your bill depends on your local prices, your climate and your house. Both keep a home equally warm; the differences are cost, carbon and installation.</p>
<h2>The efficiency maths, honestly</h2>
<p>A gas furnace burns fuel at roughly 80-95% efficiency (that is the AFUE rating). A heat pump does not burn anything - it moves existing heat, delivering roughly three to four units of heat per unit of electricity in mild conditions (the COP), dropping toward two in hard freezes. Comparing bills therefore needs prices: at average US rates (electricity near 18-19 cents/kWh, gas around a dollar-or-so per therm), a good heat pump usually matches or beats a mid-efficiency furnace for running cost, and it wins by miles against electric resistance heating. Where gas is cheap and electricity dear, the furnace can still win the annual bill. UK readers: with the cap-priced electricity at 26p and gas at about 7p, the running-cost race is genuinely close - which is why schemes subsidising heat-pump installs exist, and why any decision starts with your actual tariffs.</p>
<h2>The installation reality</h2>
<p>A furnace swap into existing flues and ducts is a days-long job. An air-source heat pump is also usually a one-to-three-day retrofit for homes with ducts (or ductless mini-splits without), but it costs several times a furnace replacement up front, and the honest answer on price is: it varies too much to quote - get local quotes and check the incentive schemes that currently apply (US federal and state credits; the UK's Boiler Upgrade Scheme grant). Sizing and insulation matter as much as the box: the <a href="/attic-insulation-basics/">insulation-first rule</a> is what lets a smaller, cheaper system heat the same house.</p>
<h2>Who each actually suits</h2>
<p><b>Heat pump:</b> homes without a gas connection (all-electric houses have the most to gain), households replacing both heating <i>and</i> cooling (it is the AC too), moderate climates - and cold-climate models now handle hard winters, at reduced efficiency in the worst weeks. <b>Furnace:</b> homes with existing ducts, cheap gas, and a working furnace near end-of-life where a like-for-like swap is the low-drama option; pairing it with good <a href="/draught-proofing-mistakes/">draught-proofing</a> and the <a href="/thermostat-settings-that-save-money/">setback habit</a> matters whichever way you go. The honest tiebreaker for most households: if the furnace dies mid-winter, the emergency replacement is a furnace; if you are planning ahead, price the heat pump with incentives before deciding - and for the smaller-room version of the same question, <a href="/is-it-cheaper-to-heat-one-room/">the one-room maths</a> handles the space-heater end of the market.</p>"""),
]
