# BRYME Home & DIY — roadmap batch 8: Energy bills (3) + Home security (3, new "Secure it" section).
# UPDATE-class batch: energy figures dated precisely (Ofgem cap Oct-Dec 2026 quarter; scheme
# status checked 2026-09-10 — GBIS closed 31 Mar 2026, ECO4 to 31 Dec 2026); security framed
# as published police/insurer prevention guidance, non-tactical. Verified 2026-09-10.

HOME_ROADMAP_8 = [
("energy-bill-high-unchanged", "guide",
"Why your energy bill is high even though nothing changed",
"Nothing changed — and everything changed. The seven mechanisms behind a bill that creeps up on a household that's done nothing wrong.",
"""<p>The most disorienting letter of the year is the one saying your direct debit is rising when your habits, your house and your family are identical to last year. It feels like an error. It almost never is — it's seven different mechanisms, most of them invisible, compounding quietly. Here they are, with the checks that separate "that's the market" from "that's fixable in my house".</p>
<h2>One: the price behind the bill moved</h2>
<p>In Great Britain, most households sit on the regulated price cap, which resets <em>every quarter</em>. To date this guide: for the October-to-December 2026 quarter, Ofgem set the cap at £1,723 a year for a typical dual-fuel household paying by direct debit (roughly 26p per kWh of electricity and 8p per kWh of gas), up from £1,663 the quarter before — and the quarter before that was lower again. That's the background radiation of energy bills: you can use exactly the same and owe more. <strong>Checked September 2026 — the cap resets quarterly, so treat any figure here as a snapshot and check Ofgem's current level.</strong> Outside the cap (prepayment exceptions, fixed deals, Northern Ireland's different market), your own tariff's unit rates are the first thing to read, not the total.</p>
<h2>Two and three: estimates and standing charges</h2>
<p><strong>Estimated readings</strong> are the classic "sudden" bill: months of guesses corrected by one real reading, in whichever direction reality lands. Submitting meter readings monthly (or letting a smart meter do it) converts the bill from an event into a steady line. <strong>Standing charges</strong> — the daily fee for being connected, now on the order of 50-85p a day across both fuels — bill like a subscription whether you use nothing or everything, and they've been drifting up. You can't escape them by using less, which is exactly why they feel so unfair on a low-usage month.</p>
<h2>Four: the season you're billed for isn't the season you remember</h2>
<p>Gas bills lag the weather: a cold December arrives as a painful February reconciliation, and direct-debit reviews annualise it. Compare like with like — this month against the <em>same month last year, adjusted for the unit rate</em> — not against July. Households that never change a thermostat still swing 20-30% between a mild and a hard winter; the house is doing what houses do (<a href="/home/condensation-ventilation-that-works/">steady low heat beats bursts, for warmth and for damp alike</a>).</p>
<h2>Five: the appliances drifted, not you</h2>
<p>No habit changed — the machines changed underneath you. The fridge compressor worn by years of coil dust runs longer every month (<a href="/home/fridge-coils-twice-a-year/">the twice-a-year habit exists for this</a>); a boiler two services overdue loses efficiency quietly (<a href="/home/uk-boiler-servicing/">the annual service is partly an efficiency check</a>); a dryer with a choked vent takes longer per load (<a href="/home/dryer-lint-every-load/">the lint habit</a>); and a new large TV, a second fridge in the garage, or a home-office week that became permanent all add real kWh without feeling like a "change". The fix is an audit: one week of reading the meter daily tells you more than a year of guessing.</p>
<h2>Six: the tariff quietly lapsed</h2>
<p>Fixed deals end and roll onto the default capped rate — usually fine, occasionally worse; discounts expire; and loyalty is, in energy as elsewhere, rarely rewarded. One evening a year, on the same date, is enough: check your unit rates against the current cap, and check the market. Switching is a form-filling exercise now, not the baroque ordeal of memory.</p>
<h2>Seven — and the honest one: it's the fabric</h2>
<p>The long-term mechanism is the house itself: uninsulated lofts, single glazing, draughts and cold floors are the difference between two identical families' bills being £300 or £900 apart in winter. The good news is that the fabric is also the part with help attached — <a href="/home/uk-insulation-grants/">the UK grant guide covers what's currently funded and for whom</a> — and the habits that stretch whatever heat you buy (<a href="/home/smart-thermostat-payback/">thermostat discipline</a>, <a href="/home/draught-proofing-mistakes/">draught-proofing done right</a>, <a href="/home/single-glazing-payback/">the honest window maths</a>). Nothing on this page makes the bill fun. All of it makes the bill legible — and legible is where the levers are.</p>
<p><em>Sources: Ofgem price-cap level for Oct-Dec 2026 (confirmed 26 August 2026) and published standing-charge/rate breakdowns. Figures are snapshots — the cap resets quarterly. Reviewed September 2026 · general information, not financial advice.</em></p>"""),

("uk-insulation-grants", "guide",
"Loft and wall insulation: what UK government help actually covers (2026 state of play)",
"The scheme landscape just changed underneath everyone: one flagship closed, others run on — here is what's live, for whom, and until when.",
"""<p>UK insulation funding is the part of home improvement where the internet is most reliably out of date: schemes close, get extended, and rename themselves, while old articles keep advertising the dead ones. This page is dated deliberately — <strong>checked September 2026</strong> — and the first thing a dated page has to say is the one most haven't caught up with: <strong>the Great British Insulation Scheme (GBIS) closed to new applications on 31 March 2026</strong>. If a website is still promising "free GBIS insulation", it's selling you a closed door. Here's what's actually live.</p>
<h2>ECO4 — the main route, until 31 December 2026</h2>
<p>The Energy Company Obligation (ECO4) obliges large energy suppliers to fund efficiency measures in homes that need them. The core eligibility: <strong>households on qualifying benefits</strong> (Universal Credit, Pension Credit, income-related ESA/JSA, Housing Benefit, and similar — the full list is on gov.uk) living in homes with an <strong>EPC rating of D or below</strong>. ECO4 takes a "whole house" approach: loft insulation, cavity wall, solid wall, boiler replacement and first-time central heating are the named measures, and the work can be fully funded — suppliers recoup the cost through the levy that sits on everyone's bill, which is why it isn't charity, it's infrastructure. Two honest warnings: ECO4 ends in its current form on <strong>31 December 2026</strong> (successor schemes are periodically announced — check before assuming), and the scheme's quality regime exists because badly installed insulation caused real damp problems — use registered installers, and get certificates.</p>
<h2>Without benefits: LA Flex and the Warm Homes: Local Grant</h2>
<p><strong>ECO4 LA Flex</strong> (local authority flexibility) lets councils widen eligibility using their own criteria — typically household income below a local threshold (a common figure is around £31,000 gross) or health conditions made worse by cold homes — without requiring named benefits. <strong>The Warm Homes: Local Grant</strong> (England) funds efficiency upgrades for lower-income households not on benefits, delivered through councils, scheduled to run to March 2028. Application is through your council; criteria genuinely vary by area, so your council's own page is the source of truth.</p>
<h2>The adjacent money</h2>
<p>Three more lines worth knowing: the <strong>Warm Home Discount</strong> takes a fixed amount (£150 in recent years) off eligible households' electricity bills each winter — automatic for some, application for others. The <strong>Boiler Upgrade Scheme</strong> offers £7,500 toward a heat pump — not insulation, but part of the same bill-reduction project. And <strong>devolved nations differ</strong>: Scotland and Wales run their own schemes alongside (Scotland's area-based schemes and Warmer Homes Scotland have their own criteria), and Northern Ireland's provision is separate again. The devolution point is the one national articles most often fudge.</p>
<h2>Before you apply — and after</h2>
<p>Check your EPC (free, online, by address) — the grade gates everything. Gather benefit paperwork if applicable. Apply through gov.uk or your council, never through a cold caller; unsolicited "government scheme" salesmen are the industry's persistent scam vector, and genuine schemes never need your bank details to "release" funding. After installation: the paperwork (warranties, guarantees — <a href="/home/unpermitted-work-home-sale/">paperwork wins arguments later</a>) and the physics — <a href="/home/condensation-ventilation-that-works/">an insulated, sealed-up house needs deliberate ventilation or it trades a heat problem for a damp one</a>, and <a href="/home/smart-thermostat-payback/">insulation changes what your heating schedule should be</a>. Insulation is the best-value energy measure in most homes — the unglamorous part is that the value arrives as a smaller number, twelve months running.</p>
<p><em>Sources: Ofgem GBIS and ECO4 scheme pages; gov.uk Warm Homes: Local Grant and Warm Home Discount guidance; scheme status checked 10 September 2026 — these programmes close and rename; verify current status on gov.uk before acting. General information, not financial advice.</em></p>"""),

("smart-thermostat-payback", "guide",
"The real payback time on a smart thermostat (US and UK, honestly)",
"Between the manufacturer claims and the cynics sits a narrow, honest band: real savings for real people, but only for some habits — here's the arithmetic.",
"""<p>Smart thermostats are the rare gadget whose sales pitch includes a savings claim — and the rare savings claim that independent studies partly back. Between the marketing ("save up to 30%!") and the cynicism ("they pay for themselves never") is a defensible middle. This page does the arithmetic for both sides of the Atlantic and names the one variable that decides everything: how you were heating before.</p>
<h2>What the studies actually found</h2>
<p>The best-known independent work is on the Nest: two utility-sponsored studies (an Oregon energy trust and an Indiana utility) found averages of <strong>10-12% savings on heating and about 15% on cooling</strong>, worth roughly $130-145 a year for US households. Ecobee's manufacturer data claims similar (around 9% heating, 12% cooling). ENERGY STAR's verification work puts the typical figure closer to <strong>8% on heating and cooling combined</strong> — and, crucially, the studies agree the spread is enormous: households that never touched their old thermostat save the most; disciplined programmers save the least, because the smart thermostat is automating what they already did. UK estimates (Energy Saving Trust-derived) land in the same shape: on the order of £75-£150 a year for a gas-heated semi, skewed by exactly the same habit variable.</p>
<h2>The payback arithmetic</h2>
<p>Device costs: roughly $60-80 for the entry tier (Amazon's basic smart thermostats), $180-280 for the learning tier (Nest, Ecobee premium models) in the US; £90-200 in the UK, plus installation where a system needs a professional (a consideration the US mostly escapes with standard 24V systems, and the UK meets with combi-boiler compatibility questions — check your boiler type before buying). Against the honest savings band: <strong>the entry tier pays back in under a year to about 18 months</strong>; <strong>the premium tier in roughly two to three years</strong> — faster where energy prices are high, slower for the already-disciplined. Any utility rebate (common in US states, occasional in the UK) cuts the timeline proportionally. Nobody honest promises faster.</p>
<h2>What actually generates the savings</h2>
<p>Not the app. The savings come from three behaviours the device automates: <strong>setbacks</strong> — heating or cooling less while you're out or asleep, consistently, which humans are terrible at doing manually; <strong>responsiveness</strong> — not "pre-heating for hours because we might be cold"; and <strong>feedback</strong> — the energy-history screen that makes usage visible for the first time. If you already programme a schedule and keep it, a smart thermostat buys convenience, not kilowatt-hours — the honest answer for that household is often a £20 programmable thermostat doing the same job. UK heating-specific note: combi-boiler households get the full benefit; system boilers with hot-water tanks benefit less, because a chunk of the bill is water the thermostat doesn't manage (<a href="/home/uk-boiler-servicing/">the service matters more there</a>).</p>
<h2>The verdict, in one paragraph</h2>
<p>If your heating runs on habit rather than schedule — on when people remember — a smart thermostat is one of the few gadgets with a defensible two-to-three-year payback and a better life after that. If your heating is already scheduled, spend the money on fabric instead: <a href="/home/uk-insulation-grants/">insulation, where the UK government may even fund it</a>, <a href="/home/draught-proofing-mistakes/">draught-proofing done right</a>, or the <a href="/home/fridge-coils-twice-a-year/">maintenance habits that stop machines wasting what you buy</a>. The device doesn't save energy. It saves the energy your habits were leaking.</p>
<p><em>Sources: independent Nest utility studies (10-12% heating / ~15% cooling, $131-145/yr); ENERGY STAR verification (~8% typical); Ecobee manufacturer data; UK Energy Saving Trust-derived estimates (£75-150/yr band). Reviewed September 2026 · savings depend on prior habits, climate and tariff; figures are ranges, not promises.</em></p>"""),

("entry-point-mistakes", "guide",
"The entry-point mistakes that make a house an easy target",
"Burglary prevention is mostly the same short list police forces have published for decades — and most of it is free. The expensive part is the assumptions.",
"""<p>Police crime-prevention advice on burglary converges, force after force, on a short list of weaknesses — and almost none of them cost money to fix. They cost assumption. The house that gets entered through an unlocked door while the family watches television in the back room wasn't unlucky; it was, in the police phrase, an opportunity. This page is that official list, organised by where it happens — no tactics, just the published prevention side.</p>
<h2>Doors: the unlocked problem</h2>
<p>The single most consistent finding in domestic burglary is the simplest: a significant share of entries are through <strong>unlocked doors</strong> — daytime, evening, sometimes while someone is home. The prevention list from police guidance: keep external doors locked even when you're in (they're describing habit, not paranoia); if the final exit door is wooden, a <strong>five-lever mortice deadlock to BS 3621</strong> is the standard police and insurers cite — and note it's usually an <strong>insurance condition</strong>, not a preference (check your policy's security wording; <a href="/home/fence-shed-insurance/">the small-print mechanics are the same as outbuildings'</a>); uPVC multipoint doors are only locked when the handle has been lifted and the key turned — thousands of households never lift the handle. Spare keys go to a neighbour or a proper key safe, never under the mat, in the pot, or visible through the letterbox — and keys out of sight of the letterbox entirely, because fishing is in every police list.</p>
<h2>Windows: the accessible ones</h2>
<p>Ground-floor windows, and any window reachable from a flat roof, ledge or downpipe, are the second classic entry. Key-operated locks on accessible windows are the standard — and, again, usually an insurance requirement. The habit half is the harder one: windows left open overnight in summer, upstairs windows open with a easy route (bins, extensions, drainpipes), and ladders left out in the garden — police guidance groups ladders and tools with unlocked windows for a reason. Close and lock what's accessible; ventilate with locked-open vents rather than wide sashes (<a href="/home/condensation-ventilation-that-works/">ventilation is a system — and most of it works locked</a>).</p>
<h2>The approach: sightlines, light and the side gate</h2>
<p>The rest of the published list is about removing privacy and opportunity: valuables and keys not visible from windows; the side gate closed and latched (rear access is where police say most assessed entries happen); hedges trimmed below window height so the house isn't screened; motion or timer lighting on the approach; and the garage or shed locked — because the tools there are the ones used on the house (<a href="/home/fence-shed-insurance/">and the shed's own insurance line has quirks</a>). None of it is high-tech. All of it is the difference between "an opportunity" and "a house that looks like effort".</p>
<h2>The two habits worth stealing</h2>
<p><strong>The once-over:</strong> the same nightly walk as the <a href="/home/test-alarms-monthly/">alarm test</a> — doors, windows, gate, keys away, lights where you want them. Thirty seconds. <strong>The away-routine:</strong> insurers commonly require everything closed and locked when the property is left unattended — a burglary claim with an open window is the <a href="/home/small-leak-ripple-effect/">condition-versus-event argument</a> in another costume. And if you come home to signs of entry: don't go in — call the police from outside. The house is replaceable; the habit of safety is what this page is actually installing.</p>
<p><em>Sources: UK police force crime-prevention guidance (West Yorkshire Police door and window advice; consistent with Secured by Design and metropolitan-force equivalents); insurer security-condition conventions (BS 3621 final-exit-door requirements). Reviewed September 2026 · general information, not professional security or insurance advice.</em></p>"""),

("smart-locks-cameras-worth-it", "guide",
"Smart locks and cameras: what's worth the money and what's marketing",
"The genuinely useful version of the smart home security pitch is small: keyless doors, codes for people you trust, and a doorbell that answers. The rest is a subscription sales funnel.",
"""<p>Smart security is sold as one product — the secure, monitored, app-wrapped home. It's actually three purchases wearing one box: locks, cameras, and monitoring. Two of them earn their keep in ordinary households. The third is mostly a recurring-revenue business. Here's the honest sorting, with the catch that almost nobody mentions until their insurer does.</p>
<h2>Smart locks: the genuinely useful one</h2>
<p>What a good smart lock actually delivers: no keys to lose, copy or hide under the mat (<a href="/home/entry-point-mistakes/">the mat-spare-key habit is on every police list</a>); codes for people you trust — cleaners, dog walkers, visiting relatives — created and revoked in seconds; auto-lock for the household member who has never once locked the door; and the remote check, from a taxi, that the door is locked at all. That's a real quality-of-life upgrade, and the safety logic is defensible: fewer spare keys in the world is fewer ways in. The honest limitations: it's another powered device (batteries die — put the change on a schedule), another app that needs updates and eventually support (<a href="/home/smart-appliances-worth-it/">the twelve-year software question applies</a>), and — the catch — <strong>insurers specify standards, and in the UK that usually means BS 3621: a keyed lock</strong>. Replacing the mortice deadlock with a smart lock can technically leave your policy's security condition unmet; the workable pattern most households land on is smart on the night latch, standard five-lever deadlock staying in the door. Check your policy wording before, not after.</p>
<h2>Cameras and doorbells: useful, bounded</h2>
<p>The video doorbell is the honest success story of the category: it answers the door from anywhere, keeps the parcel footage that resolves disputes, and — police guidance is broadly positive here — adds deterrence and evidence at the entry point, which is where opportunistic crime happens. Fixed cameras covering your own boundaries add the same for the driveway and garden. The limits: footage is for <em>evidence and awareness</em>, not prevention of the determined; battery models need charging like everything else; and privacy law has teeth — in the UK, cameras covering pavement, road or a neighbour's property pull you into data-protection obligations, and footage of shared space can be contested. Aim your camera at your own property; the law and your neighbours both simplify.</p>
<h2>The monitoring subscription: the actual product being sold</h2>
<p>The kit is the advertisement; the subscription is the business. Professional monitoring (a service that calls you and, at the top tier, the police when an alarm triggers) has a real use case — households frequently away, vulnerable residents, insurance discounts that offset the fee. For most households, self-monitoring — the app notifying you, you deciding what's real — does the meaningful work at zero monthly cost. The pattern to recognise: kit priced cheap against a contract that carries the margin, features paywalled behind tiers, and hardware that degrades when the subscription lapses (<a href="/home/small-leak-ripple-effect/">the same compounding logic, in a billing costume</a>). Price the total over five years, not the doorbell.</p>
<h2>The verdict, in the shape this desk uses</h2>
<p><strong>Worth it:</strong> keyless entry with codes, the video doorbell, one or two well-aimed cameras, self-monitoring, and — the cheapest security on this page — <a href="/home/entry-point-mistakes/">the locked-doors-and-sightlines habits police publish for free</a>. <strong>Be sceptical of:</strong> multi-year monitoring contracts, feature-gated basics, any lock that removes the insurer's specified standard, and the general implication that gadgets substitute for habits. The house that's hard to enter is hard to enter because of what its people do nightly; the gadgets document and remind — they don't replace.</p>
<p><em>Sources: UK police door/window prevention guidance; insurer lock-standard conventions (BS 3621); UK data-protection guidance on domestic cameras (ICO household CCTV guidance). Reviewed September 2026 · general information — your insurer's wording and your jurisdiction's camera rules are the authorities.</em></p>"""),

("renter-security", "guide",
"Home security for renters: what you can do without breaking your lease",
"Renters get told to 'ask the landlord' — true, and useless as a strategy. Here's what's genuinely in your power, what needs permission, and how to ask well.",
"""<p>Most security advice assumes you own the doors you're securing. Renters don't — but the property is still where you live, and the published prevention list applies to you more than anyone: renters move more often, change keys more often, and rarely know who holds copies of the old ones. The good news: most of the effective list is either reversible, removable, or already your right. This is general information — your lease and your jurisdiction's tenancy law are the authorities — but here is the practical map.</p>
<h2>What's yours to do without asking</h2>
<p>Everything that doesn't alter the fabric: <strong>habits</strong> — the whole <a href="/home/entry-point-mistakes/">locked-doors, closed-windows, keys-away list</a> is tenant-territory by definition. <strong>Removable kit</strong> — a door security bar or jammer that braces the door from inside (no screws, leaves no mark); window locks that clamp sashes without drilling (check they don't damage finishes); battery alarm systems with peel-and-stick sensors (no wiring); a video doorbell on your own door where the lease allows (see below); light-timer plugs; and the <a href="/home/test-alarms-monthly/">monthly test habit</a>, which no landlord has ever objected to. The test for "reversible": does it come out with no trace? Then it's yours.</p>
<h2>Locks: the UK position, honestly framed</h2>
<p>The general position under UK tenancy law is that tenants have a right to quiet enjoyment of the home, and it's widely accepted that a tenant may change the cylinder on the final-exit door — particularly given nobody can be sure how many copies of the existing key circulate from previous tenancies — <em>provided the original lock is kept and refitted at the end of the tenancy</em>, and the landlord isn't left unable to access in a genuine emergency. Tenancy agreements sometimes say otherwise; commentary (including from housing charity Shelter's guidance) treats blanket lock-change bans as difficult to enforce against quiet enjoyment, but the low-friction route is the smart one: tell the landlord in writing what you're doing and why, offer to refit the original at move-out, and keep every part. Two boundaries stay absolute: never lock the landlord out of access they're legally entitled to with proper notice, and fire escapes and communal final exits are never yours to modify.</p>
<h2>Locks: the US position, briefly</h2>
<p>US rules are lease-and-state specific: some states give tenants an explicit right to change locks or require rekeying between tenancies (a handful of states mandate rekeying on turnover); most leases require landlord permission for alterations, which a lock swap technically is. The universal play is the written request: name the reason (previous tenants may hold keys — landlords rarely disagree), offer a licensed locksmith at your cost, offer to restore at move-out, and keep the original. A reasonable request in writing is hard to refuse and creates the paper trail that resolves any later disagreement (<a href="/home/uk-landlord-damp-mould-duties/">the report-in-writing discipline works in every jurisdiction</a>).</p>
<h2>The asking-well template</h2>
<p>For anything bolted to the fabric — better final-door lock, window locks where none exist, exterior lighting — the request that works is short: <em>what</em> (one improvement), <em>why</em> (the accessible window / the failing lock), <em>who pays</em> (you, usually), <em>who installs</em> (an insured tradesperson), and <em>what's left behind</em> (an improvement to their property). Landlords say yes to upkeep-shaped requests and no to holes. And the quiet heavyweight on your side: <strong>renters insurance</strong> — inexpensive in both markets, covering belongings against theft as well as fire and water — with one check first: some policies carry the same lock-standard conditions as homeowners' (<a href="/home/fence-shed-insurance/">the small-print habit</a>), so read the security wording once.</p>
<p><em>Sources: UK tenancy guidance (Shelter-style quiet-enjoyment and lock-change conventions); US state/lease variation summarised as practice, not law. Reviewed September 2026 · general information, not legal advice — your tenancy agreement and local tenancy law govern.</em></p>"""),
]
