"""BRYME Home & DIY - roadmap batch 14 (Sept 2026): the gaps the desk had not
filled yet - generator sizing, kitchen ants, the home office, the fan
comparison, the power-cut first hour and drain flies. Same boundaries as every
batch: general information, never professional advice; the electrical and gas
rules stay absolute."""

HOME_ROADMAP_14 = [
("what-size-generator-do-i-need", "power",
"What size generator do you actually need? The wattage worksheet",
"Running watts versus starting surge, the appliance list that settles the argument, and why the biggest generator is usually the wrong answer.",
"""<p>Most generator mistakes happen at the point of sale, not in the service bay: people buy big (wasteful fuel, abusive noise) or small (an overload every time the fridge kicks in). The fix is ten minutes of arithmetic before you shop - and one concept: running watts versus starting surge.</p>
<h2>The one concept that settles everything</h2>
<p>Every appliance has a <b>running wattage</b> - what it draws while working - and some have a <b>starting surge</b>, a brief spike two to three times higher when motors kick in. Fridges, freezers, pumps, fans, air conditioners and anything else with a compressor or motor surge; lights, TVs, laptops and phone chargers barely do. Your generator must carry everything running <em>plus</em> the single largest surge likely to start - not the sum of all surges, which almost never start at once.</p>
<h2>The worksheet</h2>
<p>List what must run during an outage, honestly. Typical rough figures to plan with - the nameplate sticker on each appliance wins ties: <b>fridge:</b> 150-300 W running, surging toward 600-1,000; <b>chest freezer:</b> similar; <b>half-HP water pump:</b> 750-1,100 W running with a hard surge; <b>1.5 hp AC:</b> 1,100-1,600 W running with a surge well beyond that - the item that changes the whole plan; <b>standing fan:</b> 60-90 W each; <b>TV + decoder:</b> 100-200 W; <b>laptops, lights, router:</b> 150-250 W all together. Add your running column, add the largest surge on top, and buy the next size up - roughly: <b>1.5-2 kVA</b> carries lights, fans, TV and the fridge; <b>2.5-3.5 kVA</b> adds the pump; <b>anything feeding an AC</b> starts at 3.5-5 kVA and honesty about fuel bills.</p>
<h2>Load-shedding beats size</h2>
<p>The cheapest upgrade is a plan, not kVA: decide the outage hierarchy before it happens (fridge and one light bay first, luxury appliances queue behind) and label the changeover switch accordingly. A generator running at 30 per cent load wastes fuel and carbon-fouls itself; one at 90 per cent lives on a cliff edge every time the compressor kicks. See <a href="/home/generator-vs-inverter-nigeria/">generator versus inverter</a> for where a battery inverter should cover the small loads, <a href="/home/changeover-switch-care/">changeover switch care</a> for the wiring side, and <a href="/home/outlet-overloading-danger/">outlet overloading</a> for the fires this whole exercise prevents.</p>
<h2>The rules that are not negotiable</h2>
<p>Generators run <b>outside</b>, several metres from windows and doors - exhaust carbon monoxide kills quietly indoors and on balconies (the alarms exist for this: <a href="/home/how-many-smoke-co-alarms/">how many alarms and where</a>). Refuel only after a cool-down - the cap-off-a-hot-generator fire is a classic (fuel storage itself has rules: <a href="/home/jerrycan-fuel-storage-safely/">jerrycan safety</a>). And anything wired into the house circuits belongs to a licensed electrician - the generator stays a plug-in appliance until a professional says otherwise (<a href="/home/wiring-red-flags-in-your-home/">the wiring red flags</a> tell you why).</p>
<p>General information, not professional advice. Nameplate figures beat every number on this page; the electrician beats both.</p>"""),
("ants-in-the-kitchen", "guide",
"Ants in the kitchen: the protocol that actually ends the trail",
"Why wiping the visible ants invites more, how bait works when spray fails, and the sanitation loop that closes the door for good.",
"""<p>The kitchen ant invasion feels random and is not: it is a supply chain. Worker ants found your counter, laid a chemical trail for their sisters, and the line you see is logistics, not the problem. That is why the two instinctive responses - squash the scouts, spray the column - reliably fail, and what to do instead.</p>
<h2>Why spraying makes it worse</h2>
<p>Repellent sprays kill the visible hundred and scatter the colony - which then fragments into multiple new colonies (a known response called budding in the common indoor species), and next week there are three trails. Squashing scouts does nothing: the trail chemistry is already on your skirting board, and the colony replaces workers faster than you can clap.</p>
<h2>What works: bait, patience, sanitation</h2>
<p><b>Bait:</b> gel or liquid ant baits - sweet or protein depending on what the trail is eating that week - are carried back and fed to the colony, including the queen. Put small dabs <em>directly on the trail</em> where ants already travel, resist spraying near the bait, and let the line look busier for a few days - that is the bait working. Replace dried bait; move it a metre if ignored after two days, switching flavour (sweet to protein). <b>Sanitation:</b> the bait needs the pantry to stop competing - sealed containers for sugar, honey and cereals, the bin lid closed, dishes out of the sink overnight, and the floor line under the kickboards wiped (grease films feed ants that ignore sugar). <b>Seal:</b> follow each trail to its entry point - window frames, pipe penetrations under the sink, wall cracks behind the cooker - and close it with caulk or filler (<a href="/home/external-wall-crack-seal/">wall crack sealing</a> is the same skill outdoors).</p>
<h2>The water and weather factor</h2>
<p>Ants often invade chasing water, not food - during dry spells they raid the kitchen sink trap, in the rains they flee flooded nests. Dry the sink overnight, fix the dripping tap (<a href="/home/how-to-fix-a-dripping-tap/">the cartridge fix</a>), and expect seasonal waves rather than one battle.</p>
<h2>When professionals earn the call</h2>
<p>Trails returning for weeks despite correct baiting, ants nesting in wall voids or behind tiles, or carpenter ants (large, and they excavate damp wood - different beast, real damage) mean the colony is inside the structure: that is the <a href="/home/diy-vs-professional-pests/">professional line</a>, and crossing it is cheaper than the joinery. One scout in the evening, calmly walked back out, is nothing - <a href="/home/ignore-single-pest-sighting/">do not panic a sighting</a>.</p>
<p>General information, not professional pest advice. Keep baits away from children and pets, and follow the label - the label outranks this page.</p>"""),
("home-office-setup", "understand",
"The home office that survives load-shedding: a setup guide",
"Screen height, chair depth, light direction and the power-backup math for a desk that works when the grid does not.",
"""<p>A home office is not a laptop on a dining table - your neck knows it within a fortnight, and your output knows it within a month. The fix costs less than you fear and mostly involves geometry, one lamp and honest maths about your power.</p>
<h2>The geometry that matters (in order)</h2>
<p><b>Screen top at eye level.</b> Stack books under a laptop or raise the monitor; looking down twenty degrees all day is the single most reliable way to grow a neck ache. External keyboard and mouse the moment the screen is raised - the laptop-on-a-box with laptop keyboard below is the classic beginner trap. <b>Chair depth:</b> seat edge a hand-width from the back of your knees, feet flat (a box underfoot beats dangling all day). <b>Desk height:</b> elbows at roughly ninety degrees when typing - most tables are too high, which is what the chair height is for. <b>Light from the side:</b> a window to your side, never behind the screen (glare) and never behind you at night with the screen dark (the torch-in-a-cave effect). One desk lamp on the writing side finishes the job.</p>
<h2>The power reality, planned honestly</h2>
<p>A work setup draws little - laptop 45-90 W, router 10 W, phone 20 W, lamp 10 W - which is exactly why it belongs on the inverter/battery side of the house plan, not the generator side: an inverter that would never carry an iron happily carries your entire office for hours (the sizing logic lives in <a href="/home/generator-vs-inverter-nigeria/">generator versus inverter</a> and <a href="/home/the-battery-room/">the battery room</a>). The router on backup is the quiet win - your data connection often survives the grid if the router does. Everything still runs through the switchboard rules: no daisy-chained extension blocks under the desk (<a href="/home/outlet-overloading-danger/">outlet overloading</a>, <a href="/home/extension-cords-temporary-power/">cords are temporary</a>).</p>
<h2>The habits that make it humane</h2>
<p>Stand or walk for five minutes every hour - the best chair cannot out-engineer stillness. Files and papers off the working surface at day's end; the office that packs away keeps the bedroom from becoming the office. And cables: one power strip, mounted or taped flat, nothing trailing across a walkway - the same trip-and-pull logic that protects the TV (<a href="/home/tv-mount-on-block-wall/">mounted is safer</a>).</p>
<p>General information, not medical or professional advice. Persistent wrist, neck or back trouble belongs with a professional - the setup prevents; it does not treat.</p>"""),
("ceiling-fan-vs-standing-fan", "understand",
"Ceiling fan or standing fan? The honest room-by-room answer",
"Airflow direction, real power draws, noise physics and care - which fan belongs in which room, and why the answer is usually both.",
"""<p>The fan argument is a household fixture in more ways than one. Here is the honest engineering: neither fan makes a room cooler - both make <em>you</em> cooler by moving air off your skin. That single fact decides everything: what matters is where the air moves, how much it costs to move, and what the room is used for.</p>
<h2>The numbers that decide it</h2>
<p>A typical <b>ceiling fan</b> draws 50-75 W and moves a large column of air across the whole room, silently and out of the way - it is the whole-room solution. A <b>standing fan</b> draws 45-90 W on full speed and moves a focused beam - it is the personal solution, aimed at whoever is in it, and it goes wherever the heat goes. Per person cooled, the standing fan is staggeringly efficient; per room comfort, the ceiling wins. On the meter they are near-equals, and both are an order of magnitude kinder than an AC (<a href="/home/standby-power-real-numbers-your-meter/">what things really cost at the meter</a>).</p>
<h2>The room-by-room verdict</h2>
<p><b>Bedroom:</b> ceiling fan on low, aimed at gentle whole-room circulation - a standing fan's beam on your all night is how throats complain, and the ceiling keeps floor space free. <b>Living room:</b> ceiling fan for the room, one standing fan aimed at the sofa's evening occupants - the pair costs less to run than the AC they postpone. <b>Kitchen:</b> standing fan only - grease and steam film a ceiling fan's blades and balance within months (<a href="/home/ceiling-fan-mounting-right/">mounting it right</a> matters more in kitchens for the same reason). <b>Home office:</b> the standing fan, aimed past you rather than at your papers; the quieter the better on calls.</p>
<h2>Care decides the second year</h2>
<p>A wobbling ceiling fan is a dust-balance problem as much as a fitting one - blade cleaning is real maintenance, and a fan pulled tight to the right mounting stops singing (<a href="/home/wall-fan-making-noise/">the noisy-fan diagnosis</a> covers the standing fan's rattles). Dust both types monthly in the dry season; the harmattan films everything (<a href="/home/harmattan-and-your-electronics/">harmattan and electronics</a>).</p>
<h2>The buying rules, briefly</h2>
<p>Ceiling: 1.2 m (48 in) for ordinary bedrooms, 1.4 m (56 in) for living rooms, downrod length so the blades sit roughly 2.3-2.7 m above the floor. Standing: choose by noise on low (if you can hear it across a quiet room, you will hate it by midnight), by a base you cannot tip, and by a tilt that aims high as well as low. Buy the fan for the room you have, not the showroom.</p>
<p>General information, not professional advice. Any new fan circuit or ceiling point belongs to a licensed electrician (<a href="/home/wiring-red-flags-in-your-home/">the red flags explain why</a>).</p>"""),
("power-cut-first-hour", "safety",
"The first hour of a power cut: the playbook worth rehearsing",
"The safety sequence - unplug, light, fridge, generator protocol - written for the dark, worth reading before you need it.",
"""<p>A power cut is rarely dangerous in the first minute and often dangerous by the twentieth, because the dark invites rushed decisions: candles near curtains, generators started inside, fridges flung open. The fix costs one read and ten minutes of preparation. Here is the first hour, in order.</p>
<h2>Minute 0-5: make it safe before making it bright</h2>
<p><b>Unplug the sensitive things</b> - TVs, computers, decoders - or switch the socket outlets off: the surge when power returns is the real hazard, not the blackout (<a href="/home/burning-plastic-smell-socket/">the socket that smells hot</a> explains what surging does to tired wiring). <b>Leave one light switched on</b> so you can see the return, and know where your torch is in the dark, not theoretically. Candles are last resort, never in a room with sleeping children, never near curtains - a torch per room beats every candle argument (<a href="/home/cooking-oil-fire-plan/">the fire plan</a> assumes you already chose light badly; choose better).</p>
<h2>Minute 5-15: the fridge decision and the neighbour check</h2>
<p><b>Keep the fridge and freezer shut.</b> A closed fridge holds its cold for hours and a full freezer for a day or more - the food-safety clock and the when-to-discard rules live in <a href="/home/fridge-food-safety-power-cut/">fridge safety in a power cut</a>. Check whether the outage is yours alone (a tripped breaker has a different playbook: <a href="/home/why-does-my-circuit-breaker-keep-tripping/">the breaker page</a>); if neighbours are dark too, it is the grid, and the plan proceeds.</p>
<h2>Minute 15 onward: the generator protocol, or the quiet hour</h2>
<p><b>Generator rules in one breath:</b> it runs outside, metres from windows; you start it, let it run two minutes, then connect loads one at a time, biggest surge last; and you <em>never</em> refuel a hot engine - shut down, wait, then fill (<a href="/home/gas-cylinder-safety/">the fuel-and-flame rules</a> apply to storage: <a href="/home/jerrycan-fuel-storage-safely/">jerrycans</a>). If the cut is long, run it in scheduled blocks for the fridge and freezer rather than all evening. <b>No generator?</b> The quiet hour is the oldest technology: close the fridge, open the windows, charge what you can from the power bank, and let the inverter carry the lights and the router if you have one (<a href="/home/generator-vs-inverter-nigeria/">generator versus inverter</a> explains why the small loads belong there anyway).</p>
<h2>The ten minutes that make this easy</h2>
<p>Tonight, while the lights are on: one torch per room with live batteries, the changeover switch labelled (<a href="/home/changeover-switch-care/">its care page</a>), the generator's fuel level known, the power bank charged, and this page remembered rather than needed. That is the whole playbook - rehearsed once, it becomes the calmest hour in your month (<a href="/home/rainy-season-home-checklist/">the seasonal checklist</a> has the rest of the house covered).</p>
<p>General information, not professional advice. Downed lines, burning smells or anything electrical that behaves strangely after power returns: leave it to the professionals (<a href="/home/electric-shock-first-response/">shock response</a> is worth knowing before you ever need it).</p>"""),
("drain-flies-bathroom", "guide",
"Drain flies: the tiny moths are not from the window - they are from the trap",
"Identify the fuzzy drain fly, find the breeding film, break the cycle mechanically, and know when the trap itself has failed.",
"""<p>Those tiny, fuzzy, moth-like insects hovering in ones and twos around the bathroom are drain flies (moth flies), and the window you keep opening is not the problem. They breed in the soft gel film that lines slow, slimy drains - and they will keep hatching there for weeks until the film goes. This is a cleaning problem wearing a pest costume.</p>
<h2>Confirm it in one minute</h2>
<p>Tape a clear plastic cup upside-down over the suspect drain overnight (tape one edge so air escapes). In the morning, adults stuck inside the cup confirm the breeding site - and if two drains are suspects, test both, because the answer is often not the one you watch them land on. They also breed in the overflow channel, under a loose toilet seat base, or in that forgotten mop bucket - anywhere wet, slow and gunky.</p>
<h2>Break the cycle mechanically</h2>
<p>Chemicals mostly bounce off the gel film; mechanics win. <b>Clear the drain first</b> - hair and sludge are the film's foundation (<a href="/home/how-to-clear-a-slow-shower-drain/">the slow shower drain method</a>). <b>Scrub the pipe walls:</b> a drain brush, or a bent bottle brush, worked up and down the visible throat of the trap - you are physically removing the nursery. <b>Flush with very hot water and finish with the trap:</b> several kettles' worth over a few minutes, then the <a href="/home/sink-trap-clean-smell/">trap-clean routine</a> (that page's smells and these flies share one root cause). Repeat the hot flush every couple of days for two weeks - eggs laid before the first scrub keep hatching, and the repeat is what outlasts their cycle.</p>
<h2>The traps that help while you work</h2>
<p>A shallow dish of water with a drop of washing-up liquid near the hover zone catches adults all day; the window-and-cup trick catches them at source. Neither matters unless the film dies - adults live about two weeks, which is exactly why a single deep clean feels like failure and a fortnightly rhythm feels like magic.</p>
<h2>When it is not a cleaning problem</h2>
<p>Flies returning immediately after a proper scrub, a sewer smell that will not leave (<a href="/home/sewer-smell-after-trip/">the post-trip smell</a>), or gurgling with backflow points to a dried-out or broken trap, or a venting issue - the <a href="/home/floor-drain-backflow/">floor drain backflow page</a> covers the drain side, and persistent cases earn the plumber (the <a href="/home/diy-vs-professional-pests/">DIY versus professional line</a> applies to the drains too). And if the source turns out to be the septic or soakaway breathing back, that is a bigger conversation: <a href="/home/soakaway-filling-up-signs/">the soakaway signs</a>.</p>
<p>General information, not professional advice. Drain flies are nuisance pests, not hygiene emergencies - but a bathroom that grows its own wildlife deserves the fortnight of hot flushes.</p>"""),
]
