"use strict";
/* Send the BRYME Indexing API queue to the deployed notify endpoint.
 *
 * Reads content/index-queue.json (generated by scripts/build-index-queue.py)
 * and POSTs each item to the guarded endpoint at:
 *   INDEXING_ENDPOINT  (default http://localhost:8787/api/index/notify)
 * using bearer token  INDEXING_API_TOKEN.
 *
 * The endpoint is dry-run until a Google service account is configured
 * (GOOGLE_INDEXING_CREDENTIALS). A 202/dry-run/duplicate response is a success;
 * any network/HTTP error is logged and does not fail the build (it is an
 * optional notification, never a release gate).
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ENDPOINT = (process.env.INDEXING_ENDPOINT || "http://localhost:8787/api/index/notify").replace(/\/+$/, "");
const TOKEN = process.env.INDEXING_API_TOKEN || "";

async function post(url, type) {
  const res = await fetch(ENDPOINT, {
    method: "POST",
    headers: { "content-type": "application/json", authorization: "Bearer " + TOKEN },
    body: JSON.stringify({ url, type }),
  });
  let json = {};
  try { json = await res.json(); } catch (_) {}
  return { status: res.status, ok: res.ok, json };
}

async function main() {
  let queue;
  try {
    queue = JSON.parse(fs.readFileSync(path.join(ROOT, "content/index-queue.json"), "utf8"));
  } catch (err) {
    console.log("No index queue to send (content/index-queue.json not found). Nothing to do.", err.message);
    return 0;
  }
  const items = queue.items || [];
  if (!items.length) { console.log("Indexing queue is empty."); return 0; }

  let sent = 0, errors = 0;
  for (const item of items) {
    try {
      const r = await post(item.url, item.type);
      const label = r.json.dryRun ? "dry-run (not sent to Google)" :
                    r.json.deduplicated ? "duplicate (skipped)" :
                    r.ok ? "sent" : "error " + r.status;
      console.log(`  ${item.type.padEnd(9)} ${item.url} -> ${label}`);
      if (r.ok) sent++; else errors++;
    } catch (err) {
      errors++;
      console.log(`  ${item.type.padEnd(9)} ${item.url} -> FAILED ${err.message}`);
    }
  }
  console.log(`Indexing notification: ${sent} accepted, ${errors} failed.`);
  // Never fail the pipeline on a notification error.
  return 0;
}

main().then((c) => process.exit(c)).catch((e) => { console.error(e); process.exit(0); });
