#!/usr/bin/env python3
"""A10 (corrected): AdSense Funding Choices loader only.

The repo already ships Consent Mode v2 defaults (assets/gtag-init.js, generated by
scripts/analytics_head.py, EEA/UK/CH-scoped) and the site CSP is script-src 'self' https:
with no unsafe-inline, so any inline consent banner is blocked and dead. Google's own CMP
(AdSense > Privacy & messaging) is the designed consent UI and sends the consent updates;
this injector adds the standard FC bootstrap loader that lights it up once the console
side is enabled. Idempotent via static marker <!--gfc-->; noindex pages skip.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
PUB = ROOT / "public"
NOINDEX = re.compile(r'<meta[^>]+name="robots"[^>]+content="noindex')
MARK = "<!--gfc-->"

HEAD = ('<!--gfc--><script async src="https://fundingchoicesmessages.google.com/'
        'i/pub-1881426210393009?ers=1"></script>')

applied = skipped = 0
# public/ is the page index (3,903 routes); mirror the same paths in the root tree.
# Never rglob the repo root: ecosystem/ holds SOURCE index.html copies and must stay pristine.
for f in sorted(PUB.rglob("index.html")):
    rel = f.relative_to(PUB)
    for target in (f, ROOT / rel):
        if not target.is_file():
            continue
        t = target.read_text(encoding="utf-8")
        if MARK in t or NOINDEX.search(t) or "</head>" not in t:
            skipped += 1
            continue
        t = t.replace("</head>", HEAD + "\n</head>", 1)
        target.write_text(t, encoding="utf-8")
        applied += 1
print(f"consent: {applied} wired, {skipped} skipped")
