# BRYME Money desk — taxonomy for the living-machine hub (batch 1).
# Mirrors fitness_hub_data.py: CATS drive the section shelves and section
# pages; MAP assigns every content page a (section, need); TOOLS are the
# on-device calculators; NEEDS are the job tiles; CADENCE sets per-section
# re-verification windows in days (fees/brokers move fastest).

MONEY_CATS = {
    "save": ("Save and grow",
             "The foundations before any trade: emergency funds, budgeting, debt payoff, compound interest, house deposits and insurance — evergreen saving, jurisdiction-honest."),
    "start": ("Start here",
              "What trading actually is, which market suits you, the trade types and the market environments — the map before the money."),
    "risk": ("Risk and sizing",
             "Position sizing, pre-trade checklists, leverage and order mechanics — the survival layer that comes before any strategy."),
    "charts": ("Charts and indicators",
               "What indicators measure and what they cannot: RSI, ATR, moving averages — with the marketing claims stripped out."),
    "costs": ("Costs, brokers and platforms",
              "The maths of fees, spreads, swaps and pips, plus how to verify a broker and choose a platform in your own country."),
    "method": ("Method and evidence",
               "How to test an idea honestly before risking money: backtesting discipline and the public QUANTLAB research record."),
}

# slug -> (section, need)
MONEY_MAP = {
    "how-insurance-premiums-are-calculated-explained": ("save", "save"),
    "insurance-deductibles-and-excess-explained": ("save", "save"),
    "how-insurance-claims-work-explained": ("save", "save"),
    "travel-insurance-explained": ("save", "save"),
    "income-protection-insurance-explained": ("save", "save"),
    "critical-illness-insurance-explained": ("save", "save"),
    "mortgage-types-explained": ("save", "save"),
    "mortgage-ltv-and-deposits-explained": ("save", "save"),
    "mortgage-vs-renting-explained": ("save", "save"),
    "how-mortgage-approval-works-explained": ("save", "save"),
    "mortgage-fees-and-closing-costs-explained": ("save", "save"),
    "how-to-remortgage-explained": ("save", "save"),
    "trading-for-beginners": ("start", "start"),
    "stocks-forex-futures-and-cfds": ("start", "start"),
    "trade-types-explained": ("start", "start"),
    "trading-environments-explained": ("start", "read"),
    "position-sizing-101": ("risk", "size"),
    "trading-risk-checklist": ("risk", "size"),
    "leverage-and-margin-explained": ("risk", "size"),
    "order-types-and-slippage": ("risk", "size"),
    "technical-indicators-explained": ("charts", "read"),
    "rsi-indicator-guide": ("charts", "read"),
    "atr-indicator-guide": ("charts", "read"),
    "moving-averages-sma-vs-ema": ("charts", "read"),
    "trading-fees-explained": ("costs", "vet"),
    "forex-spreads-and-pips": ("costs", "vet"),
    "how-to-check-a-trading-broker": ("costs", "vet"),
    "how-to-choose-a-trading-platform": ("costs", "vet"),
    "backtesting-101": ("method", "test"),
    "quantlab-explained": ("method", "test"),
    # Growth batch (2026-09-25): six new guides, high-demand clusters.
    "trading-taxes-explained": ("costs", "vet"),
    "zero-commission-trading-truth": ("costs", "vet"),
    "risk-of-ruin-explained": ("risk", "size"),
    "demo-accounts-what-they-cant-teach": ("method", "test"),
    "signal-sellers-and-copy-trading": ("risk", "vet"),
    "day-trading-vs-swing-vs-investing": ("start", "start"),
    # Saving batch (2026-09-25): evergreen personal-finance foundations —
    # emergency funds, budgeting, debt payoff, compounding, deposits, insurance.
    "emergency-fund-guide": ("save", "save"),
    "budget-50-30-20-explained": ("save", "save"),
    "debt-snowball-vs-avalanche": ("save", "save"),
    "compound-interest-explained": ("save", "save"),
    "how-to-save-for-a-house-deposit": ("save", "save"),
    "how-mortgages-work-explained": ("save", "save"),
    "high-yield-savings-accounts-explained": ("save", "save"),
    "where-to-put-your-money-explained": ("save", "save"),
    "buy-now-pay-later-explained": ("save", "save"),
    "dollar-cost-averaging-explained": ("save", "save"),
    "money-scams-how-to-spot-and-recover": ("save", "save"),
    "health-insurance-basics-explained": ("save", "save"),
    "how-car-insurance-works": ("save", "save"),
    "index-funds-explained": ("save", "save"),
    "how-to-budget-with-irregular-income": ("save", "save"),
    "sinking-funds-explained": ("save", "save"),
    "marginal-tax-rates-explained": ("save", "save"),
    "401k-explained": ("save", "save"),
    "ira-and-roth-ira-explained": ("save", "save"),
    "how-state-pensions-work": ("save", "save"),
    "wills-and-estate-basics-explained": ("save", "save"),
    "how-much-to-save-for-retirement-explained": ("save", "save"),
    "fire-financial-independence-explained": ("save", "save"),
    "capital-gains-tax-explained": ("save", "save"),
    "tax-deductions-and-credits-explained": ("save", "save"),
    "inheritance-tax-explained": ("save", "save"),
    "how-payslips-work-explained": ("save", "save"),
    "your-first-tax-return-explained": ("save", "save"),
    "how-interest-rates-work-explained": ("save", "save"),
    "checking-and-savings-accounts-explained": ("save", "save"),
    "how-deposit-insurance-works-explained": ("save", "save"),
    "home-insurance-explained": ("save", "save"),
    "renters-insurance-explained": ("save", "save"),
    "joint-bank-accounts-explained": ("save", "save"),
    "debt-consolidation-explained": ("save", "save"),
    "how-personal-loans-work-explained": ("save", "save"),
    "how-loan-amortisation-works-explained": ("save", "save"),
    "good-debt-vs-bad-debt-explained": ("save", "save"),
    "how-to-negotiate-with-creditors-explained": ("save", "save"),
    "debt-relief-options-explained": ("save", "save"),
    "life-insurance-basics-explained": ("save", "save"),
    # Credit & retirement batch (2026-09-25): high-CPC evergreen clusters.
    "how-credit-scores-work": ("save", "save"),
    "how-to-improve-your-credit-score": ("save", "save"),
    "how-credit-card-interest-works": ("save", "save"),
    "retirement-savings-basics-explained": ("save", "save"),
    "student-loans-explained": ("save", "save"),
    "inflation-and-your-money-explained": ("save", "save"),
}

# (slug, title, blurb, related_slug)
MONEY_TOOLS = [
    ("position-size-calculator", "Position size calculator",
     "Account, risk % and stop distance in — lot or unit size out. Any market, any account currency, the working shown.",
     "position-sizing-101"),
    ("expectancy-calculator", "Trading expectancy calculator",
     "Win rate and average win/loss in — expectancy per trade out. See why the ratio matters more than being right.",
     "backtesting-101"),
    ("savings-goal-calculator", "Savings goal calculator",
     "Goal, timeline, rate and monthly contribution in — future value and the monthly number you actually need out. Formula shown.",
     "compound-interest-explained"),
    ("credit-card-payoff-calculator", "Credit card payoff calculator",
     "Balance, APR and payment style in — months to zero and total interest out, fixed versus minimum payment side by side. Working shown.",
     "how-credit-card-interest-works"),
    ("mortgage-payment-calculator", "Mortgage payment calculator",
     "Loan, rate and term in — monthly payment, the first-month interest/principal split and total interest out. Working shown.",
     "how-mortgages-work-explained"),
    ("marginal-tax-calculator", "Marginal tax calculator",
     "Income and editable bands in — tax slice by slice, the effective rate and the marginal rate out. Working shown.",
     "marginal-tax-rates-explained"),
]

# (key, label, blurb)
MONEY_NEEDS = [
    ("save", "Build the base",
     "Before any market: emergency funds, budgeting that sticks, debt payoff strategy and the compounding maths underneath it all."),
    ("start", "Start from zero",
     "New to markets. What trading is, what the instruments are, and the risk-first way in."),
    ("size", "Size the trade",
     "How big should this position be? Sizing, leverage, checklists and the maths that keeps one loss survivable."),
    ("read", "Read the chart",
     "Indicators and market environments — what the lines actually measure, and the claims they cannot support."),
    ("vet", "Vet the broker",
     "Before you deposit: verifying a broker in your country, and the true cost of spreads, fees and swaps."),
    ("test", "Test the method",
     "An idea is not a strategy until it survives an honest test. Backtesting discipline and public research."),
]

# days between re-verifications per section
MONEY_CADENCE = {"save": 365, "start": 365, "risk": 365, "charts": 365, "costs": 180, "method": 365}
