#!/usr/bin/env python3
"""BRYME v10 · Full NetMirror catalog for /entertainment/.
Rows + cards exactly from the user's catalog export. Each entry:
  (title, slug, typeDir, rating_or_None, year, cert)
Slugs reuse existing BRYME pages where present; new pages are created by the builder.
"""
CATALOG = {
 '🔥 Top 10 Today': [
   ('Reacher', 'reacher', 'series', 8.1, 2022, 'TV-MA'),
   ('The Traitors', 'the-traitors', 'series', 5.7, 2024, 'A 18+'),
   ('Spider-Man: Brand New Day', 'spider-man-brand-new-day', 'movie', 7.9, 2026, 'U/A 13+'),
   ('Adaalat', 'adaalat', 'series', 7.7, 2024, 'U/A 13+'),
   ('The Mentalist', 'the-mentalist', 'series', 8.4, 2008, 'U'),
   ('The Odyssey', 'the-odyssey-2026', 'movie', 8.0, 2026, 'A 18+'),
   ('Outer Banks', 'outer-banks', 'series', 8.2, 2020, 'A 18+'),
   ('Game of Thrones', 'game-of-thrones', 'series', 8.5, 2011, 'A 18+'),
   ('Awarapan', 'awarapan', 'movie', None, 2007, 'U/A 16+'),
   ('Spider-Man: No Way Home', 'spider-man-no-way-home', 'movie', 7.9, 2021, None),
 ],
 'Trending Now': [
   ('Lanterns', 'lanterns', 'series', 8.1, 2026, 'U/A 16+'),
   ('Toy Story 5', 'toy-story-5', 'movie', 8.0, 2026, 'U'),
   ('The Odyssey', 'the-odyssey-2026', 'movie', 8.0, 2026, None),
   ('Reacher', 'reacher', 'series', 8.1, 2022, None),
   ('Silo', 'silo', 'series', 8.2, 2023, None),
   ('Minions & Monsters', 'minions-monsters', 'movie', 7.5, 2026, None),
   ('Obsession', 'obsession-2026', 'movie', 8.2, 2026, None),
   ('Lucky', 'lucky-2026', 'series', 7.2, 2026, None),
   ('House of the Dragon', 'house-of-the-dragon', 'series', 8.4, 2022, None),
   ('Backrooms', 'backrooms', 'movie', 7.1, 2026, None),
   ('The Invite', 'the-invite', 'movie', 7.4, 2026, None),
   ('Outer Banks', 'outer-banks', 'series', 8.2, 2020, None),
   ('Ted Lasso', 'ted-lasso', 'series', 8.4, 2020, None),
 ],
 'Latest Release': [
   ('Dhurandhar', 'dhurandhar', 'movie', 7.1, 2025, 'A 18+'),
   ('Superman', 'superman-2025', 'movie', 7.3, 2025, 'U/A 13+'),
   ('Avatar: Fire and Ash', 'avatar-fire-and-ash', 'movie', 7.6, 2025, None),
   ('Zootopia 2', 'zootopia-2', 'movie', 7.7, 2025, None),
   ('Demon Slayer: Infinity Castle', 'demon-slayer-infinity-castle', 'movie', 7.7, 2025, None),
   ('Predator: Badlands', 'predator-badlands', 'movie', 7.8, 2025, None),
   ('The Housemaid', 'the-housemaid-2025', 'movie', 7.3, 2025, None),
   ('Scream 7', 'scream-7', 'movie', 6.2, 2026, None),
 ],
 'Hot New Releases': [
   ('Kalki 2898-AD', 'kalki-2898-ad', 'movie', 6.4, 2024, 'U/A 13+'),
   ('Pushpa 2 — The Rule', 'pushpa-2', 'movie', 6.3, 2024, None),
   ('Stree 2', 'stree-2', 'movie', 6.6, 2024, None),
   ('Deadpool & Wolverine', 'deadpool-wolverine', 'movie', 7.6, 2024, None),
   ('Inside Out 2', 'inside-out-2', 'movie', 7.5, 2024, None),
   ('Wicked', 'wicked', 'movie', 6.9, 2024, None),
   ('Gladiator II', 'gladiator-ii', 'movie', 6.6, 2024, None),
   ('Devara: Part 1', 'devara-part-1', 'movie', 6.9, 2024, None),
   ('Furiosa: A Mad Max Saga', 'furiosa', 'movie', 7.5, 2024, None),
   ('Civil War', 'civil-war-2024', 'movie', 6.9, 2024, None),
 ],
 'Bollywood': [
   ('Dhurandhar', 'dhurandhar', 'movie', 7.1, 2025, 'A 18+'),
   ('Stree 2', 'stree-2', 'movie', 6.6, 2024, 'U/A 13+'),
   ('Singham Again', 'singham-again', 'movie', 5.0, 2024, None),
   ('Bhool Bhulaiyaa 3', 'bhool-bhulaiyaa-3', 'movie', 5.5, 2024, None),
   ('Bad Newz', 'bad-newz', 'movie', 5.0, 2024, None),
   ('Article 370', 'article-370', 'movie', 6.9, 2024, None),
   ('Yodha', 'yodha', 'movie', 6.6, 2024, None),
   ('Munjya', 'munjya', 'movie', 6.1, 2024, None),
   ('Jawan', 'jawan', 'movie', 7.1, 2023, None),
   ('Animal', 'animal', 'movie', 6.1, 2023, None),
 ],
 'South Indian Hits': [
   ('Kalki 2898-AD', 'kalki-2898-ad', 'movie', 6.4, 2024, 'U/A 13+'),
   ('Pushpa 2 — The Rule', 'pushpa-2', 'movie', 6.3, 2024, None),
   ('Devara: Part 1', 'devara-part-1', 'movie', 6.9, 2024, None),
   ('RRR', 'rrr', 'movie', 7.7, 2022, None),
   ('Pushpa: The Rise', 'pushpa-the-rise', 'movie', 6.8, 2021, None),
   ('Vikram', 'vikram', 'movie', 7.5, 2022, None),
 ],
 'Indian Originals': [
   ('Welcome to the Jungle', 'welcome-to-the-jungle', 'movie', None, 2026, None),
   ('Elle', 'elle', 'series', None, 2026, None),
   ('Blast', 'blast', 'movie', None, 2026, None),
   ('Cocktail 2', 'cocktail-2', 'movie', None, 2026, None),
   ('Resort', 'resort', 'series', None, 2026, None),
   ('Notes from the Last Row', 'notes-from-the-last-row', 'series', None, 2026, None),
   ('Enola Holmes 3', 'enola-holmes-3', 'movie', None, 2026, None),
   ('See You at Work Tomorrow!', 'see-you-at-work-tomorrow', 'series', None, 2026, None),
   ('Masters of the Universe', 'masters-of-the-universe', 'movie', 7.2, 2026, None),
   ('The Sheep Detectives', 'the-sheep-detectives', 'movie', 7.9, 2026, None),
   ('Obsess', 'obsess', 'movie', None, 2026, None),
   ('Shree Baba Neeb Karori Maharaj', 'shree-baba-neeb-karori-maharaj', 'movie', None, 2026, None),
   ('Indian Institute of Zombies', 'indian-institute-of-zombies', 'movie', None, 2026, None),
   ('Gaayapadda Simham', 'gaayapadda-simham', 'movie', None, 2026, None),
   ('Main Actor Nahin Hoon', 'main-actor-nahin-hoon', 'movie', None, 2026, None),
   ('Deep Water', 'deep-water', 'movie', 7.1, 2026, None),
   ('Desert Warrior', 'desert-warrior', 'movie', None, 2026, None),
   ('Ginny Wedss Sunny 2', 'ginny-wedss-sunny-2', 'movie', None, 2026, None),
   ('Star Wars: The Mandalorian and Grogu', 'star-wars-the-mandalorian-and-grogu', 'movie', None, 2026, None),
   ('In the Grey', 'in-the-grey', 'movie', None, 2026, None),
   ("O' Romeo", 'o-romeo', 'movie', None, 2026, None),
   ('Subedaar', 'subedaar', 'movie', None, 2026, None),
   ('The Legend of Udham Singh', 'the-legend-of-udham-singh', 'movie', None, 2026, None),
   ('Ramyaa', 'ramyaa', 'movie', None, 2026, None),
   ('Kissa Court Kachahari Ka', 'kissa-court-kachahari-ka', 'movie', None, 2026, None),
   ('Na Jaane Kaun Aa Gaya', 'na-jaane-kaun-aa-gaya', 'movie', None, 2026, None),
   ('Made in Korea', 'made-in-korea', 'movie', None, 2026, None),
   ('Vishnu Vinyasam', 'vishnu-vinyasam', 'movie', None, 2026, None),
   ('Lockdown', 'lockdown', 'movie', None, 2026, None),
   ('War Machine', 'war-machine', 'movie', None, 2026, None),
 ],
 'Hollywood': [
   ('Avatar: Fire and Ash', 'avatar-fire-and-ash', 'movie', 7.5, 2025, 'U/A 16+'),
   ('Deadpool & Wolverine', 'deadpool-wolverine', 'movie', 7.6, 2024, None),
   ('Mission: Impossible — The Final Reckoning', 'mission-impossible-the-final-reckoning', 'movie', 7.2, 2025, None),
   ('Inside Out 2', 'inside-out-2', 'movie', 7.5, 2024, None),
   ('Wicked', 'wicked', 'movie', 6.9, 2024, None),
   ('Gladiator II', 'gladiator-ii', 'movie', 6.6, 2024, None),
   ('Furiosa: A Mad Max Saga', 'furiosa', 'movie', 7.5, 2024, None),
   ('Civil War', 'civil-war-2024', 'movie', 6.9, 2024, None),
   ('Twisters', 'twisters', 'movie', 6.8, 2024, None),
   ('Captain America: Brave New World', 'captain-america-brave-new-world', 'movie', 6.0, 2025, None),
   ('Jurassic World Rebirth', 'jurassic-world-rebirth', 'movie', 6.3, 2025, None),
 ],
 'Action Movies': [
   ('The Odyssey', 'the-odyssey-2026', 'movie', 8.0, 2026, 'A 18+'),
   ('Spider-Man: No Way Home', 'spider-man-no-way-home', 'movie', 7.9, 2021, None),
   ('Colony', 'colony-2026', 'movie', 8.1, 2026, None),
   ('The Death of Robin Hood', 'the-death-of-robin-hood', 'movie', 6.3, 2026, None),
   ('Supergirl', 'supergirl-2026', 'movie', 6.7, 2026, None),
   ('Spider-Man: Homecoming', 'spider-man-homecoming', 'movie', 7.3, 2017, None),
   ('Avatar Aang: The Last Airbender', 'avatar-aang-2026', 'movie', 9.2, 2026, None),
   ('Lucky Strike', 'lucky-strike', 'movie', 7.3, 2026, None),
   ('Masters of the Universe', 'masters-of-the-universe', 'movie', 7.2, 2026, None),
   ('Jackass: Best and Last', 'jackass-best-and-last', 'movie', 7.5, 2026, None),
   ('Spider-Man', 'spider-man-2002', 'movie', 7.3, 2002, None),
   ('Demon Slayer: Infinity Castle', 'demon-slayer-infinity-castle', 'movie', 8.7, 2025, None),
   ('Avengers: Infinity War', 'avengers-infinity-war', 'movie', 8.2, 2018, None),
   ('The Furious', 'the-furious', 'movie', 8.1, 2026, None),
   ('The Avengers', 'the-avengers-2012', 'movie', 8.1, 2012, None),
   ('The Amazing Spider-Man', 'the-amazing-spider-man', 'movie', 6.8, 2012, None),
   ('The Punisher: One Last Kill', 'the-punisher-one-last-kill', 'movie', 8.3, 2026, None),
 ],
 'Drama Series': [
   ('Lioness', 'lioness', 'series', 8.1, 2023, 'TV-MA'),
   ('House of the Dragon', 'house-of-the-dragon', 'series', 8.4, 2022, None),
   ('Lanterns', 'lanterns', 'series', 8.1, 2026, None),
   ('Law & Order: SVU', 'law-order-svu', 'series', 8.0, 1999, None),
   ('Silo', 'silo', 'series', 8.2, 2023, None),
   ('The Rookie', 'the-rookie', 'series', 8.5, 2018, None),
   ("Grey's Anatomy", 'greys-anatomy', 'series', 8.2, 2005, None),
   ('Law & Order', 'law-order', 'series', 7.3, 1990, None),
   ('NCIS', 'ncis', 'series', 7.6, 2003, None),
   ('CSI: Crime Scene Investigation', 'csi', 'series', 7.6, 2000, None),
   ('Supernatural', 'supernatural', 'series', 8.3, 2005, None),
   ('Ted Lasso', 'ted-lasso', 'series', 8.4, 2020, None),
   ('Game of Thrones', 'game-of-thrones', 'series', 8.5, 2011, None),
   ('FROM', 'from', 'series', 8.5, 2022, None),
   ('Criminal Minds', 'criminal-minds', 'series', 8.3, 2005, None),
   ('The Walking Dead', 'the-walking-dead', 'series', 8.1, 2010, None),
   ('Shameless', 'shameless', 'series', 8.2, 2011, None),
 ],
 'Comedy': [
   ('Toy Story 5', 'toy-story-5', 'movie', 8.0, 2026, 'U'),
   ('Minions & Monsters', 'minions-monsters', 'movie', 7.5, 2026, None),
   ('Moana', 'moana-2026', 'movie', 6.1, 2026, None),
   ('Scary Movie', 'scary-movie-2026', 'movie', 6.4, 2026, None),
   ('Jackass: Best and Last', 'jackass-best-and-last', 'movie', 7.5, 2026, None),
   ('The Invite', 'the-invite', 'movie', 7.4, 2026, None),
   ('The Devil Wears Prada 2', 'the-devil-wears-prada-2', 'movie', 7.1, 2026, None),
   ('Zootopia 2', 'zootopia-2', 'movie', 7.7, 2025, None),
   ('The Super Mario Galaxy Movie', 'the-super-mario-galaxy-movie', 'movie', 8.2, 2026, None),
   ('Deadpool & Wolverine', 'deadpool-wolverine', 'movie', 7.6, 2024, None),
   ('Hoppers', 'hoppers', 'movie', 8.2, 2026, None),
   ('K-Pop Demon Hunters', 'kpop-demon-hunters', 'movie', 8.0, 2025, None),
   ('Back to the Future', 'back-to-the-future', 'movie', 8.3, 1985, None),
   ('The Sheep Detectives', 'the-sheep-detectives', 'movie', 7.9, 2026, None),
   ('Thor: Ragnarok', 'thor-ragnarok', 'movie', 7.6, 2017, None),
   ('Freakier Friday', 'freakier-friday', 'movie', 6.8, 2025, None),
 ],
 'Thrillers': [
   ('Obsession', 'obsession-2026', 'movie', 8.2, 2026, None),
   ('Disclosure Day', 'disclosure-day', 'movie', 7.5, 2026, None),
   ("The Devil's Mouth", 'the-devils-mouth', 'movie', 6.6, 2026, None),
   ('War of the Worlds', 'war-of-the-worlds-2025', 'movie', 4.1, 2025, None),
   ('The Furious', 'the-furious', 'movie', 8.1, 2026, None),
   ('The Debt Collector', 'the-debt-collector', 'movie', 8.0, 2026, None),
   ('Deep Water', 'deep-water', 'movie', 7.1, 2026, None),
   ('Kraken', 'kraken-2026', 'movie', 6.3, 2026, None),
   ("The Shadow's Edge", 'the-shadows-edge', 'movie', 8.1, 2025, None),
   ('Captain America: Brave New World', 'captain-america-brave-new-world', 'movie', 5.9, 2025, None),
   ('Shelter', 'shelter-2026', 'movie', 7.8, 2026, None),
   ('The Housemaid', 'the-housemaid-2025', 'movie', 7.3, 2025, None),
   ('Greenland 2: Migration', 'greenland-2', 'movie', 6.4, 2026, None),
   ('Citizen Vigilante', 'citizen-vigilante', 'movie', 6.4, 2026, None),
 ],
 'Sci-Fi': [
   ('Spider-Man: No Way Home', 'spider-man-no-way-home', 'movie', 7.9, 2021, None),
   ('Colony', 'colony-2026', 'movie', 8.1, 2026, 'A 18+'),
   ('Disclosure Day', 'disclosure-day', 'movie', 7.5, 2026, None),
   ('Backrooms', 'backrooms', 'movie', 7.1, 2026, None),
   ('Supergirl', 'supergirl-2026', 'movie', 6.7, 2026, None),
   ('Project Hail Mary', 'project-hail-mary', 'movie', 8.7, 2026, None),
   ('Spider-Man: Homecoming', 'spider-man-homecoming', 'movie', 7.3, 2017, None),
   ('Masters of the Universe', 'masters-of-the-universe', 'movie', 7.2, 2026, None),
   ('Spider-Man', 'spider-man-2002', 'movie', 7.3, 2002, None),
   ('War of the Worlds', 'war-of-the-worlds-2025', 'movie', 4.1, 2025, None),
   ('Avengers: Infinity War', 'avengers-infinity-war', 'movie', 8.2, 2018, None),
   ('Avatar: Fire and Ash', 'avatar-fire-and-ash', 'movie', 7.6, 2025, None),
   ('The Avengers', 'the-avengers-2012', 'movie', 8.1, 2012, None),
   ('The Amazing Spider-Man', 'the-amazing-spider-man', 'movie', 6.8, 2012, None),
   ('Spider-Man: Far From Home', 'spider-man-far-from-home', 'movie', 7.4, 2019, None),
 ],
 'Romance': [
   ('Hotel Desire', 'hotel-desire', 'movie', 6.2, 2011, None),
   ('Your Heart Will Be Broken', 'your-heart-will-be-broken', 'movie', 7.1, 2026, None),
   ('The Invite', 'the-invite', 'movie', 7.4, 2026, None),
   ('Leviticus', 'leviticus', 'movie', 6.7, 2026, None),
   ('Forrest Gump', 'forrest-gump', 'movie', 8.5, 1994, None),
   ('Wicked: For Good', 'wicked-for-good', 'movie', 6.6, 2025, None),
   ('The Drama', 'the-drama', 'movie', 6.9, 2026, None),
   ('My Fault', 'my-fault', 'movie', 7.7, 2023, None),
   ('Chainsaw Man: Reze Arc', 'chainsaw-man-reze', 'movie', 8.5, 2025, None),
   ('Your Name.', 'your-name', 'anime', 8.5, 2016, None),
   ('The Gorge', 'the-gorge', 'movie', 7.7, 2025, None),
   ('The Notebook', 'the-notebook', 'movie', 7.9, 2004, None),
   ('One Night Only', 'one-night-only', 'movie', 6.8, 2026, None),
   ('Our Fault', 'our-fault', 'movie', 7.4, 2025, None),
   ('Fifty Shades of Grey', 'fifty-shades-of-grey', 'movie', 5.9, 2015, None),
   ('Teenage Sex and Death at Camp Miasma', 'teenage-sex-and-death-at-camp-miasma', 'movie', 7.0, 2026, None),
   ('Fifty Shades Freed', 'fifty-shades-freed', 'movie', 6.7, 2018, None),
 ],
 'Horror': [
   ('Colony', 'colony-2026', 'movie', 8.1, 2026, None),
   ('Obsession', 'obsession-2026', 'movie', 8.2, 2026, 'A 18+'),
   ('Backrooms', 'backrooms', 'movie', 7.1, 2026, None),
   ("The Devil's Mouth", 'the-devils-mouth', 'movie', 6.6, 2026, None),
   ('Leviticus', 'leviticus', 'movie', 6.7, 2026, None),
   ('Deep Water', 'deep-water', 'movie', 7.1, 2026, None),
   ('Kraken', 'kraken-2026', 'movie', 6.3, 2026, None),
   ("Lee Cronin's The Mummy", 'lee-cronins-the-mummy', 'movie', 7.9, 2026, None),
   ('28 Years Later: The Bone Temple', '28-years-later-the-bone-temple', 'movie', 7.1, 2026, None),
   ('Hungry', 'hungry', 'movie', 7.2, 2026, None),
   ('The Substance', 'the-substance', 'movie', 7.1, 2024, None),
   ('Sinners', 'sinners-2025', 'movie', 7.5, 2025, None),
   ('Her Private Hell', 'her-private-hell', 'movie', 5.2, 2026, None),
   ('Insidious', 'insidious', 'movie', 6.9, 2011, None),
   ('28 Years Later', '28-years-later', 'movie', 6.6, 2025, None),
 ],
 'Animation & Family': [
   ('Toy Story 5', 'toy-story-5', 'movie', 8.0, 2026, None),
   ('Minions & Monsters', 'minions-monsters', 'movie', 7.5, 2026, 'U/A 7+'),
   ('Avatar Aang: The Last Airbender', 'avatar-aang-2026', 'movie', 9.2, 2026, None),
   ('Demon Slayer: Infinity Castle', 'demon-slayer-infinity-castle', 'movie', 8.7, 2025, None),
   ('Zootopia 2', 'zootopia-2', 'movie', 7.7, 2025, None),
   ('Spider-Man: Across the Spider-Verse', 'spider-man-across-spider-verse', 'movie', 8.3, 2023, None),
   ('The Super Mario Galaxy Movie', 'the-super-mario-galaxy-movie', 'movie', 8.2, 2026, None),
   ('Spider-Man: Into the Spider-Verse', 'spider-man-into-spider-verse', 'movie', 8.4, 2018, None),
   ('The Wild Robot', 'the-wild-robot', 'movie', 8.3, 2024, None),
   ('Hoppers', 'hoppers', 'movie', 8.2, 2026, None),
   ('Swapped', 'swapped', 'movie', 8.9, 2026, None),
   ('K-Pop Demon Hunters', 'kpop-demon-hunters', 'movie', 8.0, 2025, None),
   ('Coraline', 'coraline', 'movie', 7.9, 2009, None),
   ('Coco', 'coco', 'movie', 8.2, 2017, None),
   ('Toy Story', 'toy-story-1995', 'movie', 8.0, 1995, None),
   ('Spirited Away', 'spirited-away', 'anime', 8.5, 2001, None),
   ('GOAT', 'goat-2026', 'movie', 8.1, 2026, None),
   ('Chainsaw Man: Reze Arc', 'chainsaw-man-reze', 'movie', 8.5, 2025, None),
   ('Inside Out 2', 'inside-out-2', 'movie', 7.5, 2024, None),
 ],
 'Trending Globally — Coming Soon': [
   ('Mutiny', 'mutiny-2026', 'movie', 6.9, 2026, 'R'),
   ('Spider-Man: Brand New Day', 'spider-man-brand-new-day', 'movie', 7.9, 2026, 'U/A 13+'),
   ('The End of Oak Street', 'the-end-of-oak-street', 'movie', 6.5, 2026, None),
   ('Insidious: Out of the Further', 'insidious-out-of-further', 'movie', 6.3, 2026, None),
   ('Avengers: Doomsday', 'avengers-doomsday', 'movie', None, 2026, None),
   ('Camp Rock 3', 'camp-rock-3', 'movie', 6.3, 2026, None),
   ('The Last House', 'the-last-house', 'movie', 6.9, 2026, None),
 ],
}

# unique titles -> (title, slug, td, rating, year, cert)
def unique():
    seen = {}
    for row, entries in CATALOG.items():
        for e in entries:
            t, s, td, r, y, c = e
            if s not in seen:
                seen[s] = (t, td, r, y, c)
    return seen
