#!/usr/bin/env python3
"""Bump lastVerified ONLY for records a human actually re-read today.

37 further records passed an automated string-match (their stated figure
still appears on their live page). They are deliberately NOT bumped: a
machine finding "100" in a page is not the same as someone reading the
guidelines, and on this site lastVerified means the latter.
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
P = ROOT / "content/opportunities.json"
V = "2026-09-06"

# Each of these was fetched and read in full today.
READ_TODAY = {
    "listverse":         "Author's Guide Appendix II re-read: '$100 USD minus Paypal fees' within 30 days, full rights transfer including moral rights. Unchanged.",
    "adi-essays":        "Submissions page re-read: still states no essay fee. Record already said so.",
    "noema":             "Contact page re-read: still no per-word or per-piece fee published.",
    "mcsweeneys":        "Web submission guidelines re-read: payment still described as modest with no figure.",
    "new-lines":         "Pitch page re-read: still no fee published.",
    "african-arguments": "Write-for-us re-read: 'limited budget', prioritises African journalists based in Africa, 'fees vary'. Creative Commons republication terms confirmed.",
    "the-tyee":          "Submissions page re-read: explicit AI ban confirmed - 'We do not publish journalism that is written or generated by AI'. Record already held prohibited.",
}

data = json.loads(P.read_text(encoding="utf-8"))
recs = {r["slug"]: r for r in data["opportunities"]}
missing = [s for s in READ_TODAY if s not in recs]
if missing:
    sys.exit(f"missing: {missing}")

for slug in READ_TODAY:
    recs[slug]["lastVerified"] = V

data["updatedAt"] = V
P.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"lastVerified bumped for {len(READ_TODAY)} records actually re-read today:")
for s, note in READ_TODAY.items():
    print(f"  {s:<20} {note[:82]}")
