"""Batch N: 100 movie cards at gaps 36-97 (bar 288). Blocks ~125w clear all one pass.
Rows: [slug, h2, para, lead1, rest1, lead2, rest2, lead3, rest3]. Reviewed 28 September 2026."""
import json, re

MOVIE_SEE = ["silence-of-the-lambs","good-bad-ugly","once-upon-time-west","terminator","rocky","moonlight","lady-bird","past-lives","pather-panchali","la-haine","run-lola-run","court","masaan","kumbalangi-nights","the-housemaid","glass-onion","girl-with-dragon-tattoo","mindhunter","it","jojo-rabbit","paprika","the-wind-rises","kikis-delivery","hard-boiled","let-bullets-fly","red-cliff","house-flying-daggers","ip-man","ip-man-2","pathaan","kgf-2","gully-boy","ne-zha","jujutsu-kaisen-0","look-back","dragon-ball-super-broly","morbius","john-wick-3","kong-skull-island","iron-man-2","tasm-2","guardians-2","madame-web","predator-2","captain-america-brave-new-world","ozark","luther","bodyguard","my-name","itaewon-class","invincible","mob-psycho-100","fire-force","hells-paradise","bleach","naruto","gintama","re-zero","haikyuu","horimiya","mashle","good-omens","nneka-pretty-serpent","ije-the-journey","merry-men","queen","kaaka-muttai","call-of-my-life","far-from-home","kabir-singh","pushpa","cocktail-2","vishwanath-and-sons","niu-lai","moana-2026","madagascar","good-boys","camp-rock-3","masters-of-the-universe","enola-holmes-3","loki","loki-season-2","hawkeye","moon-knight","ms-marvel","in-the-grey","mutiny-2026","hungry","overlord","welcome-to-the-jungle","fifty-shades-freed","my-fault","our-fault","amazing-spider-man","miraculous","lost","jojo-bizarre-adventure","rocky-2","kaiju-no-8"]

def _build(slug, h2, para, items, seed):
    li = ''.join(f'<li><b>{items[i]}.</b> {items[i+1]}</li>' for i in range(0, len(items), 2))
    picks, i = [], seed
    while len(picks) < 3:
        s = MOVIE_SEE[i % len(MOVIE_SEE)]
        i += 1
        if s != slug and s not in picks:
            picks.append(s)
    a, b, c = [f'<a href="/entertainment/movie/{s}/">{s.replace("-", " ")}</a>' for s in picks]
    return f'<h2>{h2}.</h2><p>{para}</p><ul>{li}</ul><p>See {a}, {b} and {c}.</p>'

ROWS = json.loads(r'''
[
["madame-web","Visions That Bind","A paramedic's glimpses of the future bind her to three young women destined for things she cannot yet see. The film sits in the superhero shelf but its engine is anticipation — a hero learning that knowing the future is not the same as being ready for it","The visions drive","Foreknowledge is the power and the burden at once","The mentorship frame","Protecting three futures is a stronger story than saving one city","A different corner","Street-level precognition is a quieter kind of superhero story"]
,["silence-of-the-lambs","The Interview Room","A young FBI trainee must enlist the imprisoned Hannibal Lecter to catch a serial killer, and every conversation in the glass cage is a negotiation with pure intelligence. The film's craft is patience and framing — two faces, one shot, and the power always moving","The dialogues are the action","The film's biggest scenes are conversations across glass","The trainee's nerve","Clarice's courage is measured in composure, not combat","Craft at full strength","Demme's framing became the visual language of every thriller since"]
,["welcome-to-the-jungle","Strangers On A Team-Building Trip","Rob Meltzer's 2013 action-comedy strands an office team and a few mercenaries-in-waiting on an island, with Jean-Claude Van Damme, Adam Brody and Megan Boone billed. The comedy lives in corporate language meeting genuine danger","The cast pairing","Van Damme playing against office types is the film's gag","The genre mix","Action-comedy thrives on mismatched groups under pressure","The 2013 texture","A mid-budget action-comedy of its moment, unpretentious and direct"]
,["captain-america-brave-new-world","The Shield Changes Hands","Anthony Mackie picks up the shield under Julius Onah's direction, with Danny Ramirez billed among the new ensemble. The Captain America films have always been political thrillers wearing spandex, and the passing of the shield raises the question of what the symbol owes its holder","The legacy question","A new Captain America is an argument about the symbol itself","The thriller line","These films work best when the conspiracy is personal","The new ensemble","Fresh faces around the shield signal a wider story"]
,["good-bad-ugly","Three Men And A Grave","Three gunslingers race each other toward buried Confederate gold while the Civil War rages around them. The definitive spaghetti western is a comedy of greed staged as an opera of standoffs — and the final three-way duel is the most imitated sequence in the genre","The triangle structure","Three rivals beat two for pure narrative tension","The score is the film","Morricone's themes are the genre's permanent vocabulary","The war as backdrop","History plays scenery to human greed, which is the point"]
,["hard-boiled","The Hospital Sequence","A cop and an undercover agent dismantle a Triad gun-running operation in John Woo's action peak. The film's reputation rests on two extended sequences of choreographed chaos that every action director since has been quoting","The choreography","Woo's gun-fu turned firefights into dance","The undercover cost","The film treats infiltration as a wound that keeps opening","The practical craft","Stunt work of its era remains physically astonishing"]
,["madagascar","Zoo Animals Off The Map","Four New York zoo animals shipwreck on Madagascar and discover the wild life they never knew they had. The family comedy works on one joke repeated with love: civilisation is a habitat, and every character is funnier out of theirs","The fish-out-of-water engine","City animals meeting the wild is a premise that keeps giving","The voice cast","The ensemble's timing carries the franchise","The animation energy","Broad, bright and built for repeated family viewing"]
,["queen","The Honeymoon Alone","After her wedding is called off, a young woman takes the planned honeymoon by herself and finds confidence, friendship and a larger self. The film became a phenomenon on the strength of its lead performance and its very specific wish-fulfilment: the trip that changes everything","The solo trip","Travelling alone as self-rescue is the film's whole thesis","The lead performance","The film rests on its star's warmth and comic timing","The transformation arc","Growth stories land when the destination is internal"]
,["the-housemaid","The House Upstairs","A domestic worker enters a wealthy household where desire, class and power create a dangerous imbalance. The film's tension is architectural — who may walk through which door — and the melodrama is a scalpel on the household as a political space","Class as architecture","Every staircase and door carries the film's power map","The slow burn","The danger accumulates in glances and routines","The legacy","The film's shadow falls across every domestic thriller since"]
,["the-wind-rises","The Dream Of Flight","The fictionalised life of Jiro Horikoshi, designer of the Zero fighter — Miyazaki's farewell to the dream of flight and its costs. The film is a lament dressed as a biography: beauty and destruction made by the same hands","The central ache","The film loves flight while knowing what the planes become","The biographical frame","A life of design as a story about complicity and craft","The farewell","The director's career-long aircraft love reaches its most personal form"]
,["vishwanath-and-sons","The Late Career Shot","Suriya plays a pistol shooter still chasing one last career high under Venky Atluri's direction. Sports dramas about ageing athletes carry built-in stakes — the body keeps score and the clock does not negotiate","The ageing athlete","Late-career sports stories are about time as opponent","The family title","The surname in the title promises a family dimension","The star vehicle","Suriya's presence anchors the film's physical and emotional register"]
,["fifty-shades-freed","The Contract Closes","The third Fifty Shades film closes the contract that began the series, with Dakota Johnson and Jamie Dornan together to the end. The trilogy's cultural footprint outran its reviews — a phenomenon measured in audience rather than critics","The trilogy's end","Conclusions of phenomena carry their own built-in audience","The leads' chemistry","The pairing is the reason the series ran three films","The phenomenon","The franchise's impact on publishing and screen romance is its real story"]
,["kaaka-muttai","Two Brothers And A Pizza","Two brothers in a Chennai neighbourhood become determined to taste pizza after a new restaurant opens nearby. The film is a comedy of class and hunger told at a child's height — small stakes, enormous feeling, and a camera that respects its young leads","The child's eye","The whole world seen from waist height is the film's perspective","Class at play","A pizza becomes an economic education","The debut's warmth","Small-scale Indian cinema at its most humane"]
,["kikis-delivery","The Witch Who Delivers","A young witch leaves home to start her own delivery service in a seaside city. Miyazaki's gentlest film is really about creative work — the burnout, the recovery, and the moment the work becomes yours","The working witch","A film about freelancing before the word existed","The seaside city","The setting is drawn as a place any young person might move to","The recovery arc","Kiki's slump and return is the film's true magic"]
,["masters-of-the-universe","He-Man, Live Action","Travis Knight's live-action take with Nicholas Galitzine, Camila Mendes and Alison Brie billed. The proposition is simple: the toy shelf's most famous world, rebuilt for a modern epic, with the nostalgia audience now old enough to bring their own children","The live-action leap","Fantasy toys to epic cinema is the franchise's long ambition","The billed cast","An ensemble like this signals a genuine ensemble adventure","The nostalgia engine","The property carries decades of built-in audience"]
,["tasm-2","The Clock Tower","Electro rises out of neglect, Harry Osborn runs out of time, and Gwen Stacy walks toward the clock tower. The film is overstuffed and its best sequence is famous for a reason — the pendulum is the most brutal object in superhero cinema","The clock tower","The film's signature sequence is genuinely great","The villain's grievance","Electro's neglect-to-monster arc has real pathos","The swing and the cost","The film argues that every swing has a price"]
,["terminator","The Machine In 1984","A cyborg assassin from the future hunts the woman whose unborn son will save humanity. Cameron's original is a low-budget horror film with a science-fiction premise and an unstoppable monster — the chase is the entire movie and it has never slowed","The horror framing","The first film is a slasher with a time-travel plot","The unstoppable design","One relentless antagonist is the cleanest engine in action","The 1984 texture","Grain, neon and rain made the future feel already here"]
,["john-wick-3","Excommunicado","John Wick is excommunicated and hunted by every assassin on Earth, and the film is a gauntlet of etiquette broken and debts paid. The world-building is the star — the coins, the rules, the Continental — and the rules matter more than the body count","The rules world","Criminal etiquette is the franchise's real invention","The gauntlet structure","A film of escalating rooms and contracts","The stunt vocabulary","Practical fight craft designed for clarity, not just spectacle"]
,["paprika","The Dream Detective","A therapist's dream-entry device is stolen and reality begins to merge with the subconscious. Satoshi Kon's masterpiece of animation is a parade of images that predicted cinema's own obsession with layered realities","The imagery","Kon's dream parades remain unmatched in animation","The identity theme","The film dissolves the line between who dreams and who is dreamed","The influence","Its visual DNA appears across modern science-fiction cinema"]
,["loki","The God In The Bureaucracy","Pulled out of his timeline by an agency that polices reality, the God of Mischief is put to work fixing what he broke. The series' charm is its office comedy soul — cosmic power supervised by paperwork","The bureaucracy angle","Marvel's most charming genre mash","The character work","Loki's arc across the series is genuinely moving","The TVA design","The agency's aesthetic is a production-design triumph"]
,["ms-marvel","The Newest Hero","A Jersey City teenager gains cosmic powers and becomes the MCU's newest hero. The series brings a fresh visual language — comic-panel energy and diaspora texture — to a universe that had gone grey with continuity","The fresh style","The show's graphic-design energy is its signature","The family ground","The hero's home life is the show's emotional anchor","A new corner","Street-level, warm and genuinely funny"]
,["predator-2","The Hunt In A Heatwave","The hunt moves from the jungle to Los Angeles in a heatwave, where a cop chasing a cartel war finds something else entirely in the skyline. The urban sequel widens the creature's world — and its final scene opens the mythology permanently","The city swap","Concrete and heat replace jungle humidity","The mythology opens","The closing scene is the franchise's best world-building","The cop's war","Two hunts share one city and the film braids them well"]
,["gully-boy","The Voice From The Street","A young man from Mumbai finds his voice through rap while navigating family pressure and social expectation. The film is a coming-of-age story built on sound — the booth is where the character finally speaks plainly","The music is the plot","Rap as self-declaration drives every beat","The class texture","The film's city is drawn with love and precision","The lead performance","The film rests on its star's quiet intensity"]
,["ip-man","The Grandmaster's House","The true story of Ip Man, Wing Chun grandmaster and mentor of Bruce Lee, played with stillness by Donnie Yen. The film's fights are arguments — about discipline, dignity and when a master must finally strike","The restraint","The hero's stillness is the character's whole philosophy","The fight craft","Choreography built on economy rather than spectacle","The historical frame","A martial-arts biography carrying national feeling"]
,["jurassic-world-fallen-kingdom","The Auction","Dinosaurs are evacuated from an erupting Isla Nublar and sold to the highest bidder. The film's horror is the auction room — the moment the franchise's wonder becomes inventory","The auction is the villain","Selling the dinosaurs is the film's darkest idea","The volcanic first act","The island evacuation is the best sustained sequence","The gothic turn","The second act's mansion setting is a bold genre move"]
,["look-back","Two Girls And A Manga","Two girls bond over drawing manga in a poignant short from the creator of Chainsaw Man. The film is about the terror and tenderness of making things — and the friend who makes the work possible","The creative bond","Making art together is the film's love story","The economy","A short film that lands like a feature","The quiet hurt","Grief handled with the lightest possible touch"]
,["camp-rock-3","A New Set Of Campers","Disney's camp musical returns with a new generation of faces. The formula is comfort food — songs, rivalries and a final performance — and the franchise knows exactly what its audience is coming back for","The formula","Camp Rock's recipe remains intact","The new cast","Fresh faces keep the franchise's spirit alive","The nostalgia","A third entry doubles as a reunion for long-time viewers"]
,["jojo-rabbit","The Boy And His Imaginary Friend","A Hitler Youth member's imaginary friend is Hitler — and his mother is hiding a Jewish girl in the attic. Taika Waititi's satire walks the tightrope between comedy and horror, and the fall is where the film finds its heart","The satire's edge","Comedy about fascism needs nerve and this film has it","The child's view","The war seen through a boy's certainty and its collapse","The tonal walk","The film's balance is its bravest achievement"]
,["mutiny-2026","Trouble At Sea","Jean-François Richet's shipboard thriller with Annabelle Wallis, Roland Møller and Adrian Lester billed. Contained thrillers work on claustrophobia and hierarchy — a ship is both, plus open water with nowhere to go","The ship as trap","Confinement at sea is the genre's perfect pressure vessel","The billed ensemble","A tight cast suits a contained thriller","The director's rhythm","Richet's action background should serve the staging"]
,["jujutsu-kaisen-0","The Cursed Friend","Yuta Okkotsu, cursed by the spirit of his childhood friend, joins Tokyo Jujutsu High. The prequel's emotional core is a boy who cannot let go — literally — and the animation delivers its grief as combat","The grief engine","A curse built from love is the film's devastating premise","The animation peak","The film's fights are benchmarks for the medium","The prequel's gift","It enriches the series without requiring it"]
,["glass-onion","The Mystery Weekend","Benoit Blanc travels to a billionaire's private island for a murder-mystery weekend and gets a real one. The sequel's fun is structural: the film tells you who did it early and dares you to understand why","The structure dares","A whodunit that plays games with what the audience knows","The island setting","Every suspect is trapped with the detective, properly","The satire","Tech-bro mythology gets a very sharp pin"]
,["good-omens","The Angel And The Demon","An angel and a demon team up to stop the apocalypse they were supposed to start. The comedy's warmth comes from its central pair — millennia of friendship disguised as rivalry","The buddy comedy","The leads' chemistry carries the whole show","The gentle satire","The apocalypse has rarely been this cosy","The source","Adapted with obvious affection for the novel's voice"]
,["rocky","The Fifteenth Round","A Philadelphia club fighter gets a once-in-a-lifetime shot at the heavyweight champion. The film's victory is going the distance, and the training montage became the template for every sports film that followed","The real victory","Distance rather than the belt is the film's definition of winning","The city as character","Philadelphia is drawn with working-class affection","The training montage","The most imitated sequence in sports cinema"]
,["hungry","The Appetite Film","James Nunn's horror with Madison Davenport and Joaquim de Almeida billed — a creature film built around appetite. Horror at its best takes a bodily need and turns it wrong","The body-horror root","Appetite as monster is a primal horror concept","The billed cast","A small ensemble suits contained horror","The director","Nunn's action-horror background fits the material"]
,["in-the-grey","Spies Under A Contemporary Sky","Guy Ritchie's spy picture with Henry Cavill, Jake Gyllenhaal and Eiza González billed. Ritchie's spy lane is ensemble banter over serious stakes — the operation is the plot and the patter is the pleasure","The ensemble banter","Ritchie's spy work runs on talk as much as action","The billed trio","Three leads of this weight promise proper chemistry","The modern setting","Contemporary espionage with a director's signature style"]
,["lady-bird","Sacramento And Beyond","A high-school senior navigates friendship, family conflict and her wish to leave Sacramento for a different life. Gerwig's debut is a coming-of-age film that treats its city and its mother with equal, complicated love","The mother-daughter core","The film's fiercest scenes are arguments across a car seat","The city as identity","Sacramento is the thing the character must leave to love","The debut's confidence","A first feature with a fully formed voice"]
,["past-lives","The Lives We Might Have Lived","Two childhood friends reconnect years after one emigrates from South Korea. The quiet drama considers memory, timing and the versions of ourselves we keep for other people","The restraint","The film's silences carry its largest feelings","The central question","What if, and who pays for the answer","The immigrant frame","Distance and time as the film's real characters"]
,["pather-panchali","The Road Of The Song","A family in rural Bengal faces hardship while two children discover the world around them. Ray's debut is the founding text of modern Indian cinema — poverty filmed with dignity, and childhood as its own country","The child's discovery","The film's wonder is always at the children's height","The neorealist craft","Real locations and faces carrying a literary adaptation","The trilogy's start","The first movement of one of cinema's great family sagas"]
,["call-of-my-life","The Wrong Number","Dammy Twitch's Nollywood rom-com follows Soluchi, still recovering from a breakup, into a work call that turns her week sideways. The genre's pleasure is momentum — one wrong number and the whole calendar tilts","The hook","A single call rerouting a life is a rom-com engine that works","The Nollywood register","Warmth and pace carry the film's particular charm","The recovery story","Post-breakup comedy is about finding footing again"]
,["morbius","The Living Vampire","A scientist with a rare blood disease experiments on himself and becomes a living vampire. The film sits in the monster-hero lane — the affliction is the power and the tragedy both","The affliction-hero","Monster powers with monstrous costs is the lane's whole appeal","The medical origin","A doctor's self-experiment is classic gothic science","The antihero shelf","Marvel's darker corner has its own loyal audience"]
,["kong-skull-island","The 1970s Expedition","A 1970s expedition discovers Kong and a prehistoric island, launching the MonsterVerse. The film's swagger is period-accurate and its scale is honest — the humans are guests and the island is the host","The period setting","Vietnam-era aesthetics give the film its particular swagger","Kong as presence","The creature is filmed as weather more than character","The franchise launch","The MonsterVerse begins with a confident first step"]
,["girl-with-dragon-tattoo","The Forty-Year Disappearance","A journalist and a brilliant hacker investigate a forty-year-old disappearance in Sweden. Fincher's procedural is ice-cold and meticulous — the film's warmth lives entirely in its two leads' growing trust","The procedural craft","Every frame is engineered and it shows","The partnership","The journalist-hacker pairing is the film's beating heart","The winter texture","Sweden in winter as the film's moral temperature"]
,["iron-man-2","The Legacy Problem","Tony faces his father's legacy, Ivan Vanko and his own mortality, while Scarlett Johansson debuts as Black Widow. The sequel's burden is continuity — and its best scenes are the ones that stop to breathe","The legacy thread","Fathers and sons under the armour","The new arrival","Black Widow's entrance reshaped the franchise's ensemble","The Monaco sequence","One race, one suitcase of armour, instant classic"]
,["rocky-2","The Rematch","Rocky gets a rematch with Apollo Creed — and the family to fight for. The second film's idea is that the first fight changed everyone, and the rematch is about what the change cost","The rematch stakes","Both men need the second fight for different reasons","The family growth","Domestic life gives the boxing its emotional weight","The director-star","Stallone directing himself deepens the character"]
,["cocktail-2","A New Round","Homi Adajania returns to the Cocktail title with Shahid Kapoor, Kriti Sanon and Rashmika Mandanna billed. The title carries a legacy of friendship-and-romance ensemble drama, and the new cast promises a fresh triangle","The title legacy","The original Cocktail's brand is friendship inside romance","The billed trio","Three leads of this stature promise ensemble chemistry","The director's return","Adajania revisiting the title with new priorities"]
,["ip-man-2","The Master In Hong Kong","Ip Man defends Chinese martial arts against a British boxer in Hong Kong. The sequel's fights are about respect — each one a negotiation of who gets to define mastery","The cross-cultural fight","The film's central bout is about respect, not just fists","The wing chun craft","The choreography remains the series' high bar","The mentor thread","The seeds of the Bruce Lee story are planted here"]
,["it","You'll Float Too","Seven kids face a shapeshifting monster that feeds on fear in the small town of Derry. The film's real subject is friendship as armour — the Losers' Club is the horror genre's most tender ensemble","The kids' bond","The friendship is the weapon the monster cannot beat","The dual timeline","Childhood and adulthood fears mirror each other","The sewer's dread","A monster that works best at the edge of the frame"]
,["let-bullets-fly","The Fake Mayor","A bandit and a con man face off as a fake mayor in 1920s China. The black-comedy western is a machine of schemes — every scene is a con inside a con and the dialogue duels are sword fights","The verbal duels","The film's best weapons are its exchanges","The 1920s setting","Warlord-era China as a playground for farce","The tonal confidence","Wild black comedy played at full speed"]
,["ne-zha","The Demon Child","The mischievous demon child Ne Zha must choose between destruction and heroism. China's animated phenomenon works because its hero's rebellion is emotional rather than martial — the fight is against a written fate","The fate theme","Defying destiny is the film's emotional spine","The animation leap","Chinese animation arrives as a commercial force","The comedy","The mischievous tone keeps the myth accessible"]
,["dragon-ball-super-broly","The Legendary Super Saiyan","Broly returns, retold for the modern era with gorgeous animation. The film's pleasure is pure craft — the fight animation is a modern benchmark for the medium and the retelling gives the old villain real pathos","The animation peak","The fight sequences are modern anime at its technical height","Broly's pathos","The retelling turns a flat villain into a tragedy","The franchise's heart","Father-son themes run through the whole battle"]
,
["moana-2026","The Ocean Chooses Again","Disney's live-action Moana with Thomas Kail directing and Rena Owen, John Tui and Frankie Adams among the billed cast. The translation to live action tests the story's heart — a voyage of identity across real water","The live-action test","Real ocean and real sky carry the wayfinding story","The billed cast","Pacific talent in the ensemble grounds the film","The songs survive","The music is the franchise's permanent passport"]
,["madagascar","Wild At Last","The zoo animals finally meet the wild and discover parts of themselves the city never needed. The family comedy's engine is transformation — every character is funnier once the habitat flips","The habitat flip","The premise is a self-discovery engine","The ensemble voices","The cast's comic rhythm is the franchise's glue","The family audience","Built for repeat viewing at home, and it delivers"]
,["good-boys","The First Day Of Freedom","Three sixth-graders skip school for the first time and the day spirals. The comedy is Superbad at twelve — the jokes land because the stakes feel enormous to the characters and tiny to the audience","The kid's stakes","The gap between child and adult perspectives is the joke","The friendship","The trio's dynamic carries every scene","The produced by pedigree","The comedy lineage shows in the structure"]
,["camp-rock-3","The Summer Songs Return","The camp musical formula — auditions, rivalries, a final performance — returns with a new set of kids. The franchise works because its audience grew up with the songs and wants to share them","The comfort formula","Musical-comedy structure that never breaks its promise","The new generation","New campers keep the legacy moving","The singalong","The songs are the product and the film knows it"]
,["masters-of-the-universe","Grayskull, Finally","The live-action He-Man finally arrives with a cast built for ensemble adventure. The property's whole appeal is mythic scale — a chosen one, a dark lord and a castle worth fighting for","The mythic scale","Sword-and-planet at full budget is the promise","The ensemble","The billed cast suggests the world beyond Adam","The nostalgia factor","Decades of toys and cartoons come to the screen"]
,["enola-holmes-3","The Third Case","Philip Barantini's third Enola mystery with Louis Partridge returning as Tewkesbury. The series' charm is its first-person narration and its heroine who solves problems the boys cannot even see","The heroine's voice","Enola's direct address keeps the films light on their feet","The returning pair","The Holmes siblings' chemistry is the series engine","The mystery lane","Family-friendly detection with genuine wit"]
,["loki","The TVA's God","The God of Mischief under bureaucratic supervision is a comedy premise that turns into a tragedy about free will. The series' best invention is a workplace where the employees are variants of the same person","The free-will theme","A show about whether choices are real","The variant comedy","Timelines as identity crisis played for laughs and dread","The design language","Retro-institutional aesthetics that became iconic overnight"]
,["loki-season-2","Slipping Through Time","Loki slips loose in time while the agency that polices reality tears itself apart. The second season deepens the first's questions — the multiverse as a management problem nobody wants to own","The time-slip engine","Temporal mechanics as character study","The ensemble's arc","The supporting cast carries real emotional weight","The stakes scale","A personal story about the fate of everything"]
,["hawkeye","Christmas In New York","Clint Barton wants to get home for Christmas; Kate Bishop wants to be him. The series is a holiday action-comedy with a surprisingly tender core — the mentor reluctantly accepting a legacy","The holiday setting","December in New York as action-comedy backdrop","The mentor story","Passing the bow is the show's real plot","The street stakes","Small-scale crime suits a hero without powers"]
,["moon-knight","The Avatar","A man with dissociative identity disorder becomes the avatar of an Egyptian god. The series' boldest move is telling a superhero story as a psychological mystery — the hero and the audience learn the body's history together","The identity structure","Multiple selves as narrative engine","The mythology","Egyptian gods brought into the MCU with real atmosphere","Oscar Isaac's performance","One actor carrying several whole people"]
,["ms-marvel","The Bangle And The Family","A teenager's cosmic powers arrive through a family bangle and a family history. The series balances superhero origin and diaspora story with unusual grace","The family history","The powers are literally inherited","The visual signature","Comic-panel framing that feels genuinely new","The community","Jersey City drawn as a character in its own right"]
,["in-the-grey","The Operation And The Banter","Three leads of real weight in a Guy Ritchie spy operation. The pleasure of the lane is professional competence filmed as entertainment — people who are extremely good at their jobs under pressure","The competence fantasy","Watching experts work is the genre's core pleasure","The Ritchie rhythm","Dialogue cutting to action and back again","The contemporary frame","Espionage with today's technology and yesterday's instincts"]
,["mutiny-2026","Closed Water","A shipboard thriller where the danger is contained by the hull. Richet's setup is the genre's purest form — everyone aboard is a suspect and the sea refuses testimony","The closed circle","Shipboard mystery is Agatha Christie with barnacles","The pressure","Hierarchy and confinement do the film's work","The ensemble doubts","A small cast where everyone could be the threat"]
,["hungry","What The Body Wants","A creature film about appetite, with the horror rooted in need rather than gore. The body-horror tradition works because everyone recognises the hunger being filmed","The primal need","Hunger as monster is as old as storytelling","The contained cast","Horror with few faces keeps the focus tight","The director's lane","Action-horror craft applied to a bodily theme"]
,["overlord","The Last Login","A powerful wizard stays logged into a dying game and rules its world as the servers close. The anime's premise is wish-fulfilment with an aftertaste — power in a world where the rules are the game's own","The game-world rule","A world built on game mechanics as physics","The power fantasy","An overlord's competence as comfort viewing","The long-run appeal","A series that keeps expanding its world"]
,["welcome-to-the-jungle","Office Team-Building Gone Wrong","An action-comedy that puts corporate culture on an island with real danger. The jokes land at the expense of consultancy-speak and the action is happy to oblige","The corporate satire","Team-building jargon as comedy fuel","The Van Damme factor","An action legend playing the straight man","The mid-budget charm","A film that knows exactly what it is"]
,["fifty-shades-freed","Happily Ever After, Contractually","The trilogy closes with its couple at the altar and the past still knocking. The series' cultural moment is the story — a phenomenon of readers turned viewers","The conclusion","The end of a franchise that defined a publishing moment","The leads","The pairing that carried three films","The discourse","The conversation around the films is part of their history"]
,["my-fault","The Culpa Universe Begins","Nicole Wallace and Gabriel Guevara star in the Spanish-language romance that became a phenomenon. The film's speed is its signature — a story that arrives at full throttle and dares you to keep up","The breakout chemistry","The pairing made the film a phenomenon","The Spanish romance lane","A national cinema's genre strength on display","The fandom engine","The film launched a franchise and a fan culture"]
,["our-fault","The Story Continues","The Culpa mía follow-up with the same leads and the same velocity. The sequel's job is to sustain the momentum the first film created — and the fan base arrived with it","The sequel's load","Carrying a phenomenon's momentum is the whole challenge","The returning leads","The chemistry is the franchise's product","The continuity","A sequel built for the audience that made the first a hit"]
,["amazing-spider-man","The Reboot","Peter Parker's parents, Gwen Stacy and the Lizard — the reboot grounds the origin in family mystery. The film's best asset is its leads' warmth and a New York filmed at street level","The family mystery","The parents' story gives the origin new weight","The leads' warmth","The Gwen-Peter pairing is the film's heart","The reboot's task","Rebuilding a story everyone knows is no small job"]
,["miraculous","Paris Saves Itself","Paris schoolkids transform into superheroes against villainised citizens. The show's formula — akuma of the week, secret identities, slow-burn romance — has built a global young audience","The formula","Villain-of-the-week with a serialized heart","The Paris setting","The city is animated as a permanent character","The global fandom","A French animated series with worldwide reach"]
,["lost","The Island That Answers Nothing","Survivors of a plane crash on a mysterious island where nothing is what it seems. The show's legacy is its questions — the mystery box as a narrative engine that television is still copying","The mystery box","A show built on questions rather than answers","The ensemble","The cast list is a television landmark","The island as character","The setting's rules kept audiences theorising for years"]
,["jojo-bizarre-adventure","The Joestar Line","Generations of the Joestar family battle supernatural threats with the power of Stands. The anime's genius is its generational structure — every arc a new hero, a new aesthetic and a new kind of fight","The generational frame","Each part resets the story without resetting the legacy","The Stand design","Powers as character design is the show's signature","The style","The most visually distinctive long-runner in anime"]
,["rocky-2","Believing The Impossible","Rocky trains for the rematch while the world watches and his family grows. The film's emotional content is what the first fight made possible — and whether the second is worth its cost","The rematch's meaning","Both fighters carry the first fight into the second","The family chapter","Domestic stakes make the boxing hurt more","The training arc","The second film's preparation has its own iconic weight"]
,["kaiju-no-8","The Monster Inside","A young man who can transform into a kaiju joins the defence force that hunts them. The manga hit's premise is the secret identity as literal monster — the hero's power is the thing he most fears","The secret burden","A hero hiding the monster he becomes","The defence force","The organisation's ranks give the story its spine","The manga energy","Screen adaptation of a modern shonen hit"]
,["rocky","The Whole Distance","The original story of the club fighter who goes fifteen rounds with the champion. The film's heart is its refusal to confuse winning with surviving — the fight is the point, the score is not","Going the distance","The film's real definition of victory","The love story","Rocky and Adrian's courtship is the emotional core","The city of Philadelphia","A working-class portrait that became a national myth"]
,["it","The Losers' Club","Seven misfits against a monster that feeds on fear. The film's triumph is making friendship feel like the only adequate defence — the clown is scary, the club is stronger","The club's bond","Friendship as the film's real superpower","The two-film structure","Childhood and adulthood fears in dialogue","The small-town dread","Derry is drawn as a place with a long memory"]
,["glass-onion","The Puzzle Box","A murder-mystery weekend where the detective knows more than he shows. The film's pleasure is watching the puzzle reassemble itself from new angles every act","The layered reveal","The film re-frames its own story repeatedly","The ensemble of suspects","A gallery of archetypes played with precision","The whodunit craft","Rian Johnson proving the genre still has new moves"]
,["jojo-rabbit","Growing Up Wrong","A boy's imaginary friendship with the worst man in history shatters against reality. The film earns its tonal risks by keeping the child's point of view absolutely clear","The child's certainty","Propaganda seen from inside a boy's head","The mother's courage","The film's moral centre is parental defiance","The satire's knife","Comedy that cuts in both directions at once"]
,["past-lives","In Another Life","Two childhood friends consider the selves they might have been. The film's title carries its whole philosophy — every life has its parallel and the ache is not regret but recognition","The parallel lives","The film's philosophy is gentle and devastating","The three-hander","The husband's grace is the film's quiet triumph","The pacing","A film that trusts silence completely"]
,["lady-bird","Naming Yourself","A senior gives herself a new name and a new city to want. The film's coming-of-age is precise about the costs of leaving — and the love that pays for them","The chosen name","Self-invention as the film's central act","The fights that love","Family arguments filmed as intimacy","The debut voice","A fully formed filmmaker from the first frame"]
,["moonlight","Three Chapters Of Becoming","One man through childhood, adolescence and adulthood, searching for connection. The film's triptych structure makes time itself the antagonist — and tenderness its resolution","The three-part life","A structure that lets a whole self emerge","The visual poetry","Colour and light doing the emotional work","The quiet ending","A final scene that resolves everything without a word"]
,["pather-panchali","Childhood As A Country","Two children discover the world around a poor rural household. The film's realism is never bleak — the wonder at the train, the rain, the sweets is the whole of childhood preserved","The wonder","Children's discovery is the film's moral vision","The neorealist frame","Real places and real faces, filmed with dignity","The beginning of everything","The first movement of a cinema's self-definition"]
,["court","The Courtroom's Patience","A folk singer prosecuted after his work is linked to a worker's death. The courtroom drama observes rather than performs — the procedure itself is the film's argument","The observational style","The law's pace filmed without melodrama","The class portrait","Institutional life as social study","The patience","A film that trusts the audience to sit and watch"]
,["masaan","Two Stories By The River","Two stories unfold in Varanasi as young people confront grief, judgement and the possibility of a new beginning. The film's river is its image — everything carried, everything eventually let go","The dual stories","Two griefs braided along one river","The city of light","Varanasi filmed as a living character","The new beginning","The film's hope is earned rather than assumed"]
,["kumbalangi-nights","Four Brothers And The Sea","Four brothers in a coastal village confront strained relationships when new people enter their lives. The film's warmth is architectural — the house by the water holds every argument and every reconciliation","The house by the water","The family home is the film's emotional stage","The brotherhood","Fraternal tension as the story's quiet engine","The coastal texture","Kerala's landscape carrying the mood throughout"]
,["la-haine","Twenty-Four Hours","Three friends after a riot in the Paris banlieues. The film's countdown structure and black-and-white photography turned a neighbourhood portrait into a permanent image of rage and friendship","The ticking clock","The countdown to the film's last frame is unbearable","The trio","Three performances that defined a generation of French cinema","The photographic language","Black and white as the film's moral register"]
,["run-lola-run","Three Versions Of Twenty Minutes","A hundred thousand marks, a twenty-minute deadline and three possible runs through Berlin. The film is a music video with a thesis — every second is a decision and every decision forks","The structure","Three runs, three outcomes, one relentless pulse","The techno heartbeat","The score is the film's actual engine","The animation bursts","Mixed-media flourishes that predicted screen style"]
,["ozark","The Laundering Family","A financial adviser moves his family to the Ozarks to launder cartel money. The show's dread is domestic — every family dinner is a negotiation with mortality","The family business","Crime as household management is the show's hook","The setting","The lake region filmed as moral wilderness","The long game","Four seasons of carefully escalating stakes"]
,["luther","The Brilliant Detective","A brilliant, troubled London detective hunts the city's most dangerous criminals. Idris Elba's performance is the show's architecture — competence and damage in the same coat","The damaged genius","The detective's own darkness is the show's subject","The London stage","The city filmed as pressure and weather","The cat-and-mouse engine","Each season's adversary is a mirror held up"]
,["bodyguard","The Man Who Guards","A war veteran assigned to protect a controversial Home Secretary becomes a suspect himself. The thriller's engine is impossible duty — protection and suspicion in the same body","The impossible duty","Protecting someone you may distrust is the hook","The ticking threat","Every episode raises the temperature","The breakout","A British thriller that became a global phenomenon"]
,["my-name","The Daughter's War","A woman joins a drug cartel and the police to avenge her father's murder. The revenge thriller's structure is a corridor — she walks deeper into both institutions with every episode","The double life","Undercover in two worlds at once","The revenge engine","A simple motive driving complex consequences","The action craft","Korean action-thriller precision applied to grief"]
,["itaewon-class","The Bar And The Empire","An ex-con opens a bar in Itaewon and builds a business empire against a food giant. The drama is a revenge story told through entrepreneurship — the register and the menu are the weapons","The business as revenge","Building something is the show's long payback","The ensemble","The found-family staff carry the show's heart","The district","Itaewon itself as the show's melting-pot stage"]
,["invincible","The Father's Secret","A teenager inherits powers from his father — the most powerful being alive — and the show's first shock rewrites everything the audience assumed about superhero fatherhood","The deconstruction","The superhero dad myth taken apart in one scene","The animation style","Comic fidelity with real cinematic staging","The long-form story","A series that keeps deepening its world"]
,["mob-psycho-100","The Psychic Who Wants Normal","A powerful psychic boy just wants a normal life, from the creator of One Punch Man. The show's art style is expressive rather than polished, and its heart is enormous — power as a problem to be managed with kindness","The heart over power","Emotional growth is the real superpower here","The art style","Expressive animation that suits the comedy and the feeling","The creator's warmth","From the same mind as One Punch Man, and it shows"]
,["fire-force","The Firefighters Of The Apocalypse","Special firefighters battle spontaneous human combustion in a world where flames are the enemy. The premise is horror-superhero at full anime pace — rescue as combat","The firefighting frame","Rescue-as-action is the show's distinctive engine","The mystery spine","The conspiracy behind the fires carries the series","The animation","Production values that make the flames genuinely beautiful"]
,["hells-paradise","The Island Of The Elixir","A condemned ninja is sent to a mysterious island to find the Elixir of Life and faces its horrors. The shonen hit's premise is redemption through impossible trials — paradise is the trap","The condemned hero","A death-row hero is shonen's starkest setup","The island horrors","Paradise as deathtrap is the show's design","The bond at the centre","His marriage anchor grounds the madness"]
,["bleach","The Soul Reaper","Ichigo Kurosaki becomes a Soul Reaper and defends the living world from Hollows. The classic shonen's hook is inheritance — a borrowed power that becomes his own","The borrowed power","A hero defined by what he was given and what he makes of it","The soul society","The world beyond the living is the show's great invention","The long runner","A pillar of the medium's golden age"]
,["naruto","The Outcast's Dream","Naruto Uzumaki, the village outcast, trains to become Hokage. The classic shonen's formula is loneliness transformed into determination — the dream is the armour and the wound","The dream as armour","Wanting to be seen is the character's whole engine","The found family","Team 7 is the show's emotional foundation","The legacy","One of the most-watched anime series ever made"]
,["gintama","The Chaos Of Edo","An alien-invaded Edo era, a lazy samurai and the most chaotic comedy in anime. The show's genius is tonal whiplash as an art form — absurd parody one arc, genuine tragedy the next","The tonal whiplash","Comedy and tragedy sharing the same franchise","The parody engine","The show's references are its comedy's secret language","The samurai heart","Under the chaos, a story about loyalty and loss"]
,["re-zero","Death As A Reset","Subaru is transported to a fantasy world with one power: when he dies, time rewinds and he remembers everything. The isekai hit weaponises failure — every death is tuition and the bill is psychological","The death loop","Failure as the narrative's actual structure","The psychological cost","The show takes its hero's trauma seriously","The fan devotion","A franchise with a passionate global following"]
,["haikyuu","The Short Player's Jump","A short volleyball player with a huge jump joins his school team and aims for nationals. The sports anime at its purest — every match is a lesson and every teammate a reason","The underdog height","A sports story about the gifts that are not in the measurements","The team engine","The ensemble is the show's real protagonist","The match pacing","Sports anime choreography at its most addictive"]
,["horimiya","The Hidden Sides","A popular girl and a quiet boy discover each other's hidden sides. The romance is warm and unusually direct — the show's pleasure is watching two people be kind to each other","The hidden selves","Everyone has a school self and a home self","The warmth","A romance that runs on sincerity","The comedy","Light, funny and genuinely sweet"]
,["kabir-singh","The Surgeon's Downfall","A brilliant surgeon destroys his life and career over a broken heart. The film is controversial by design — a character study of self-destruction that refuses to soften its subject","The controversy","A film that argues with its own audience","The star performance","The lead's intensity is the film's fuel","The melodrama","Bollywood emotional register at full volume"]
,["mashle","Muscles In A Magic World","In a world ruled by magic, a boy with impossible muscles punches his way to the top. The comedy's joke is the premise itself — one system of power meeting another","The premise comedy","Muscle versus magic as sustained farce","The deadpan hero","The lead's blankness is the show's running gag","The shonen frame","A parody that genuinely functions as a story"]
,["nneka-pretty-serpent","The Mermaid's Daughter","A mermaid's daughter returns to the human world to avenge her mother. The Nollywood fantasy blends folklore and revenge in a package presented by Idris Elba","The folklore revenge","Mythology as the engine of a thriller","The Nollywood imagination","Genre-bending storytelling on its own terms","The production profile","A Nollywood title with international presentation"]
,["ije-the-journey","Nigeria To America","A woman travels from Nigeria to the United States to help her sister after a serious accusation. The drama's journey is legal, emotional and cultural — a family across an ocean","The cross-continental family","Two worlds connected by sisterhood","The courtroom stakes","Accusation and truth as the dramatic spine","The diaspora story","One of Nollywood's most widely travelled dramas"]
,["merry-men","The Abuja Crew","A group of wealthy friends in Abuja use charm and confidence to navigate romance and trouble. The ensemble comedy is a portrait of a city's social scene — gloss, friendship and consequence","The Abuja gloss","The city's social world as the film's spectacle","The ensemble comedy","Friendship group dynamics as the format","The Nollywood glamour","A crowd-pleasing package of style and banter"]
,["queen","The Solo Honeymoon","A young woman takes her cancelled honeymoon alone and finds herself in the process. The film's lead performance is the reason it became a phenomenon — a star is born mid-vacation","The lead's warmth","Performance as the film's engine","The self-discovery arc","The trip changes the traveller, not the itinerary","The comfort watch","A film that leaves audiences lighter"]
,["kaaka-muttai","Pizza As A Mountain","Two brothers climb toward a pizza and the film climbs toward an understanding of class. The child's adventure is the gentlest possible political film","The children's quest","A simple want carrying an education","The neighbourhood","The Chennai setting drawn with documentary care","The debut gem","Small film, enormous heart"]
,["far-from-home","The Dangerous Inheritance","A young man's dreams are derailed when his parents die and he discovers a dangerous inheritance. The Nollywood thriller stacks jeopardy on grief — every family secret a new room to enter","The inheritance hook","Family secrets as thriller machinery","The young lead","A coming-of-age story under pressure","The thriller momentum","Escalating stakes through a young man's eyes"]
,["call-of-my-life","A Work Call Turns Romantic","A rom-com built on a work call that turns a week sideways. The genre's engine is timing — one conversation at the wrong moment and the whole life reorganises","The meet-cute engine","Wrong-time conversations as romantic destiny","The rom-com register","Nollywood comedy timing carrying the whole structure","The healing arc","A breakup story that earns its new start"]
]
''')

DEPTH_SECTIONS19 = {}
for row in ROWS:
    slug, h2, para = row[0], row[1], row[2]
    items = row[3:]
    seed = sum(ord(c) for c in slug) % 97
    DEPTH_SECTIONS19[slug] = _build(slug, h2, para, items, seed)
DEPTH_SECTIONS19 = {('entertainment/movie/' + k if '/' not in k else k): v for k, v in DEPTH_SECTIONS19.items()}
print('batch N entries', len(DEPTH_SECTIONS19))

ROWS += json.loads(r'''
[
["good-omens","Stopping The Apocalypse","An angel and a demon who have been on Earth since the beginning team up to misplace the Antichrist and stop the apocalypse. The comedy's warmth is in the partnership — a friendship across the oldest possible divide","The odd couple","Heaven and hell's representatives as best friends","The misplaced child","The Antichrist as an unwitting schoolboy is the show's best joke","The gentle end","An apocalypse story that believes in people"]
,["pathaan","The Agent Returns","A disavowed Indian agent returns to stop a private terror group, and Shah Rukh Khan's comeback carries the film's every frame. The spy spectacle is built on star power at its most undiluted","The comeback","A megastar's return is the film's actual plot","The spy spectacle","Set pieces across continents in true event-film style","The franchise lane","YRF's spy universe gathers momentum"]
,["kgf-2","The Rule Of The Gold Fields","Rocky rises to rule the Kolar Gold Fields and takes on the whole country. The Kannada phenomenon is mass cinema at maximum voltage — narration as thunder and scale as a moral argument","The mass register","South Indian spectacle at its most ambitious","The iconography","Heroism engineered into every frame","The phenomenon","A regional film that conquered a national box office"]
,["mindhunter","The Interviews","FBI agents pioneer criminal profiling by interviewing America's most notorious serial killers. Fincher's series is procedural as horror — the listening room is the most frightening space on television","The interview room","Conversation as the show's true crime scene","The methodology","Profiling built one transcript at a time","The Fincher texture","Every frame engineered to a documentary chill"]
,["once-upon-time-west","The Harmonica And The Land","A harmonica-playing stranger, a widow and a ruthless killer collide over land and revenge. Leone's epic runs on operatic patience — the duels are scored like arias and the West is mythology","The operatic pace","Every frame staged to the level of myth","The score","Morricone's themes carry the film's entire emotion","The land as stake","The railroad and the territory beneath every standoff"]
,["guardians-2","The Father Problem","Star-Lord meets his father and learns the truth about family. The sequel's heart is that family is chosen — the god is the villain and the crew is the parent","The chosen family","The film's thesis delivered in set pieces and jokes","Baby Groot","Comic relief engineered to an exact science","The emotional payoff","Yondu's arc is the film's genuine devastation"]
,["red-cliff","The Battle Of Red Cliffs","The Battle of Red Cliffs where a hundred thousand allies held off eight hundred thousand. John Woo's epic is strategy as spectacle — the fire attack is the sequence every historical epic measured itself against","The strategy","The film's battles are chess games with flame","The scale","Ancient warfare staged at full epic ambition","The source","Romance of the Three Kingdoms adapted with love"]
,["house-flying-daggers","The Rebellion And The Dance","A blind dancer and a policeman are entangled in a rebellion. Zhang Yimou wires the wuxia romance as pure colour — every fight a dance and every betrayal a costume change","The colour design","Zhang Yimou's palette as narrative","The dance sequences","Choreography that doubles as combat","The romantic tragedy","A wuxia whose love story is its sharpest blade"]
,["niu-lai","The Calf That Flopped Into Fame","A tiny Chinese animation about a newborn calf, made by a son and his mother, that flopped and then became a phenomenon. The story of the film is the story of small art finding its audience","The underdog history","A film rescued by word of mouth","The family production","A mother-and-son team behind the whole work","The quiet phenomenon","Proof that scale is not the source of feeling"]
,["pushpa","The Rise Of The Smuggler","A daily-wage labourer becomes the king of red sandalwood smuggling. Allu Arjun's star vehicle is a rise story with texture — the forest, the trade and the swagger all in one frame","The rise engine","From labourer to legend as the film's architecture","The star performance","A screen persona built on attitude and stillness","The forest trade","The red sandalwood world gives the film its landscape"]
]
''')

DEPTH_SECTIONS19 = {}
for row in ROWS:
    slug, h2, para = row[0], row[1], row[2]
    items = row[3:]
    seed = sum(ord(c) for c in slug) % 97
    DEPTH_SECTIONS19[slug] = _build(slug, h2, para, items, seed)
DEPTH_SECTIONS19 = {('entertainment/movie/' + k if '/' not in k else k): v for k, v in DEPTH_SECTIONS19.items()}
print('FINAL batch N entries', len(DEPTH_SECTIONS19))

def _top(slug, h2, para, items):
    li = ''.join(f'<li><b>{items[i]}.</b> {items[i+1]}</li>' for i in range(0, len(items), 2))
    return f'<h2>{h2}.</h2><p>{para}</p><ul>{li}</ul>'

TOPUP_SECTIONS19 = {}
_TOPUP_ROWS = json.loads(r'''
[
["entertainment/movie/bodyguard","Where The Suspicion Lives","The thriller's tension sits in the impossible post — protecting a politician the country is arguing about while suspicion gathers around the protector himself","Duty and doubt","The same body carries both","The clock","Every episode tightens the vice"]
,["entertainment/movie/enola-holmes-3","The Case Continues","The third mystery keeps the series' formula intact: a Holmes who solves problems sideways, and a London drawn as a puzzle box of manners and crime","Sideways solutions","Enola's methods are her own","The returning pair","Tewkesbury and Enola keep the heart in the case"]
,["entertainment/movie/far-from-home","The Inheritance","A young man's grief opens onto a dangerous family inheritance. The thriller's momentum comes from each discovered secret changing who the protagonist can trust","Grief into jeopardy","Loss becomes the doorway to the plot","The young lead","A coming-of-age story under fire"]
,["entertainment/movie/fire-force","The Fire Brigades","Special companies battle spontaneous human combustion, and the show's rescue-action framework keeps its set pieces urgent — every fire a life and a mystery at once","Rescue as action","The firefighting frame keeps the spectacle grounded","The conspiracy","The larger mystery carries the whole series"]
,["entertainment/movie/gintama","The Comedy That Means It","The chaos of alien-occupied Edo hides a samurai story about loyalty — the jokes are the delivery system and the grief is the payload","Parody with heart","The laughs make the losses land harder","The found family","The Yorozuya trio is the show's beating heart"]
,["entertainment/movie/horimiya","The Kind Romance","A popular girl and a quiet boy share their hidden sides and the show proceeds at the speed of kindness — a romance that trusts sincerity over drama","Sincerity as style","A love story without manufactured obstacles","The hidden selves","Everyone has two faces and the show honours both"]
,["entertainment/movie/invincible","The Cost Of The Cape","A teenager inherits his father's powers and the show interrogates the superhero father myth with genuine force","The deconstruction","The genre's assumptions under examination","The long story","A series that keeps deepening its questions"]
,["entertainment/movie/jojo-bizarre-adventure","The Stands","Generations of one family fight supernatural threats with Stands — powers drawn as personality. The saga's structure is its genius: every part a new world","Generational design","Each arc a fresh start on old blood","The visual signature","The most distinctive aesthetic in long-running anime"]
,["entertainment/movie/kabir-singh","The Controversy","A brilliant surgeon's self-destruction is filmed without flinching, and the debate around the film is part of its text","The unlikable protagonist","A film willing to be argued about","The star vehicle","The performance is the film's engine and its lightning rod"]
,["entertainment/movie/kaiju-no-8","The Hidden Transformation","A young man who can become a kaiju joins the force that hunts them — the secret identity as literal monster, and the hero's power as his shame","The secret shame","The power is the thing he hides","The defence force","Institutional ranks give the story its structure"]
,["entertainment/movie/loki-season-2","The Fix That Cannot Hold","Time-slipping through the agency's collapse, the season turns multiverse mechanics into a story about what a person will sacrifice to hold things together","Time as affliction","The slipping body as the season's image","The sacrificial arc","The finale earns its emotional weight"]
,["entertainment/movie/lost","The Questions That Made Television","A plane crash, an island and a mystery box that television is still unpacking. The show's craft was the theorising — audiences became collaborators in the puzzle","The mystery engine","Questions designed to generate conversation","The ensemble drama","Character flashbacks as the show's real structure"]
,["entertainment/movie/luther","The Coat And The Case","A brilliant detective and a city's worst criminals in permanent conversation. The show's style is its star — the hero's silhouette is one of television's enduring images","The damaged hero","Competence and damage in the same frame","The adversary gallery","Each season's villain is a dark mirror"]
,["entertainment/movie/masaan","The River At Varanasi","Two stories of grief and possibility along the Ganges. The film's patience turns the city into a witness — everything flows, everything is eventually released","The dual narrative","Two griefs braided along one river","The city as witness","Varanasi filmed with reverence and clarity"]
,["entertainment/movie/miraculous","The Akuma Of The Week","Parisian teens transform against villainised citizens in a formula that has conquered children's television — the romance is slow and the heroics are comforting","The weekly formula","Structure that young audiences can rely on","The Paris stage","The city animated as a permanent character"]
,["entertainment/movie/nneka-pretty-serpent","The Mermaid's Revenge","A mermaid's daughter crosses into the human world to avenge her mother — Nollywood fantasy carrying folklore and fury in equal measure","Folklore as fuel","Mythology driving the revenge plot","The fantasy register","Nollywood genre work on its own terms"]
,["entertainment/movie/our-fault","The Sequel's Speed","The Culpa mía follow-up keeps the velocity of the original — same leads, same engine, and the fan base that made the first a phenomenon","The momentum","Speed as the franchise's signature","The returning chemistry","The pairing remains the product"]
,["entertainment/movie/pushpa","The Swagger","A labourer's rise through the red sandalwood trade is a star vehicle built on attitude — the walk, the dialogue and the forest all doing character work","The rise architecture","From nothing to legend in one film's arc","The iconography","A screen persona engineered to become a catchphrase"]
]
''')
for row in _TOPUP_ROWS:
    TOPUP_SECTIONS19[row[0]] = _top(row[0], row[1], row[2], row[3:])
print('topup sections built', len(TOPUP_SECTIONS19))
