"""Batch M: 84 movie cards at gaps 1-36 (bar 288), FRESH. Blocks ~85 words clear all.
Rows are flat lists [slug, h2, para, lead1, rest1, lead2, rest2]. Reviewed 28 September 2026."""
import json, re

MOVIE_SEE = ["godfather-part-iii","in-the-line-of-fire","the-matrix-reloaded","bourne-ultimatum","insidious","lethal-weapon","war-of-the-worlds","it-follows","terminator-3","lost-in-translation","pan-labyrinth","shoplifters","skyfall","perfect-blue","singin-in-the-rain","nope","civil-war","longlegs","the-banshees-of-inisherin","challengers","the-brutalist","i-saw-the-devil","kantara","man-of-steel","john-wick-2","the-running-man","sinners","smile","hulk","solo-a-star-wars-story","star-wars-the-last-jedi","harry-potter-deathly-hallows-2","dune-part-three","the-odyssey","superman-2025","puss-in-boots-last-wish","inside-out-2","guardians-of-the-galaxy-vol-3","how-to-train-your-dragon-2025","nausicaa","porco-rosso","whisper-heart","poetry","pk","phone-swap","october-1","mami-wata","jallikattu","munjya","ijogbon","king-of-boys-2","rattle-snake-the-ahanna-story","pushpa-2","stree-2","singham-again","kaguya-sama","one-piece-film-red","dragon-ball-super-super-hero","the-fate-of-the-furious","predator-badlands","jurassic-world-rebirth","wicked-for-good","spider-man-brand-new-day","scream-7","sinister","mickey-17","silo","the-super-mario-galaxy-movie","paw-patrol-the-dino-movie","jackass-best-and-last","katseye-wild-hearts","disclosure-day","the-end-of-oak-street","greenland-2","phone-swap","the-shadows-edge","the-devils-mouth","the-last-house","shelter-2026","scary-movie-2026","hoppers","the-devil-wears-prada-2","article-370","backrooms","the-punisher-one-last-kill","hope-2026","lee-cronins-the-mummy","star-wars-the-mandalorian-and-grogu","the-100","insidious-out-of-further","minions-monsters","swapped","jana-nayagan","obsession-2026","toy-story-5","narcos","supergirl-2026","colony-2026","haider","omo-ghetto-the-saga"]

def _build(slug, h2, para, l1, r1, l2, r2, seed):
    me = slug
    picks, i = [], seed
    while len(picks) < 3:
        s = MOVIE_SEE[i % len(MOVIE_SEE)]
        i += 1
        if s != me and s not in picks:
            picks.append(s)
    a, b, c = [f'<a href="/entertainment/movie/{s}/">{s.replace("-", " ")}</a>' for s in picks]
    return (f'<h2>{h2}.</h2><p>{para}</p>'
            f'<ul><li><b>{l1}.</b> {r1}</li><li><b>{l2}.</b> {r2}</li></ul>'
            f'<p>See {a}, {b} and {c}.</p>')

ROWS = json.loads(r'''
[
["godfather-part-iii","The Long Shadow Of The Family","Michael Corleone is old and wants legitimacy for the family, but the third film argues that the ledgers of the past never close. Coppola returns to the saga's central question — whether power can ever be laundered clean — and the answer arrives in the only currency these films accept","Watch the eyes","Pacino plays exhaustion as much as menace across every meeting","Opera as mirror","The closing performance stages the whole tragedy in public"]
,["in-the-line-of-fire","The Man Who Was Not There","Clint Eastwood plays a Secret Service agent carrying the one failure of his career, and the film turns that guilt into a chess match with a would-be assassin. Wolfgang Petersen keeps the tension procedural rather than explosive, which is exactly why the final act lands","Guilt drives the guard","The agent's obsession with redemption is the real security system","The villain writes letters","John Malkovich's assassin treats the hunt as correspondence"]
,["the-matrix-reloaded","The Choice Expands","The second Matrix widens the war and deepens the philosophy: Neo meets the Architect and learns the prophecy has a price. The freeway chase remains a benchmark, but the film's real ambition is its argument that systems offer only choices the system designed","The Architect scene","The film's thesis arrives as a conversation about design","The freeway chase","Still one of the great sustained action sequences in cinema"]
,["colony-2026","Pressure At The Edge","Yeon Sang-ho builds a future colony under strain, with Jun Ji-hyun, Koo Kyo-hwan and Ji Chang-wook billed among the faces carrying the pressure. The director's filmography runs on social systems cracking under stress, and a closed colony is his kind of pressure vessel","The director's pattern","Yeon Sang-ho's films turn settings into social experiments","The cast carries scale","A large billed ensemble suggests a story with many fronts"]
,["haider","Grief In A Political Valley","Haider adapts Hamlet into the Kashmir of the 1990s, where a young man searching for his missing father finds grief braided into politics, family and betrayal. The transposition is the point: the play's questions about vengeance and conscience land differently inside a conflict that is still being argued about","The setting is the adaptation","Kashmir in the nineties gives Shakespeare a new and sharper register","Music of the valley","The score carries the region's own sounds through the drama"]
,["omo-ghetto-the-saga","Twins Across The Divide","Twins separated at birth grow up on opposite sides of the law — one a street queen, one polished and respectable — and the reunion plays both comedy and consequence. The film became a phenomenon on the strength of its lead performance and its willingness to play every register at once","One actor, two lives","The dual lead performance is the engine everyone remembers","Comedy with teeth","The laughs never fully let the social stakes off the hook"]
,["bourne-ultimatum","The Truth At The End Of The Program","Bourne finally reaches the centre of Treadstone and finds out who made him. Greengrass pushes the handheld, cut-fast style to its peak here, and the Waterloo station sequence remains a masterclass in suspense assembled from pure motion","Action with geography","You always know where everyone is, even at speed","The origin lands","The reveal reframes every memory the series has shown"]
,["insidious","The Further Waits","A family's son slips into a coma and something on the other side wants to keep him. James Wan stages the haunting as a slow inventory of a house's wrongness, and the film's best scares come from what sits still in the background of the frame","The house is the monster","Most of the dread lives in what the camera does not point at","Sound does the work","The score tells you when to fear before the image does"]
,["predator-badlands","The Hunt From The Other Side","Dan Trachtenberg follows a young Yautja on a hunt that goes wrong, with Elle Fanning billed in the mix. After Prey, the franchise's smart move is telling the hunt from the hunter's culture rather than the human survivors","The director's promise","Prey proved this franchise survives reinvention","The alien's story","Centering the Yautja flips the whole series' point of view"]
,["lethal-weapon","The Buddy-Cop Blueprint","A suicidal detective and a steady family man are partnered in Los Angeles, and every buddy-cop film since has been arguing with this one. The tonal trick — genuine darkness braided with real warmth — is harder than it looks and the reason the film still plays","The tonal balance","Danger and comedy share scenes without diluting each other","The partnership works","The casting is the template everyone copied"]
,["war-of-the-worlds","Tripods And Panic","Spielberg's invasion strips the story down to one family running while tripods harvest the cities. The film is at its best in its crowd scenes, where scale and panic meet and the hero's competence is reduced to keeping his children moving","Fear at ground level","The film works from inside the fleeing crowd","The sound design","Machines that roar across the skyline stay with you"]
,["guardians-of-the-galaxy-vol-3","The Team's Last Ride","The Guardians close their run with Rocket's origin finally told straight, a villain who despises creation itself, and a team saying goodbye in the only way they know — loudly. The emotion lands because the films earned it across a decade of banter","The origin lands","Rocket's backstory is the film's emotional centre","Goodbyes matter","The farewell works because the ensemble has history"]
,["poetry","A Quiet Curriculum","An older woman begins a poetry class while a painful truth in her family comes into focus, and the film builds its case softly: attention is a moral act. The performance at its centre never raises its voice and never lets go","The class becomes the frame","Learning to look becomes the film's argument about care","Patience is the craft","The film rewards viewers who match its quiet pace"]
,["pushpa-2","The Rule Begins","Pushpa Raj is no longer climbing — he is in open conflict with the state and rival syndicates, and the sequel turns the first film's rise into a war for control. The scale is bigger, and the star vehicle is now a genuine franchise","The escalation","Rise stories make way for rule stories","Style is strategy","The film's iconography is engineered for the crowd"]
,["inside-out-2","Anxiety Moves In","Riley turns thirteen and the console gets crowded as Anxiety, Envy, Embarrassment and Ennui arrive with opinions. The sequel's idea — that the emotions you gain in adolescence do not replace the ones you had — is as simple and true as the first film's","The new cast","Anxiety is a brilliant addition to the original five","Growing up is not replacing","The film argues emotions accumulate rather than swap"]
,["it-follows","The Slow Walk","A curse passes in the simplest way possible — one victim at a time, walking — and the film turns that into a mood of permanent surveillance. The camera never lets the corners of the frame rest, and the horror works because the rule is absolutely fixed","The rule is the horror","A simple, unbroken rule makes every background nervous","The camera stays wide","The frame is the device that keeps the threat alive"]
,["stree-2","Chanderi After Dark","The friends who survived the first Stree face a new night problem in Chanderi, and the sequel keeps the franchise's balance of folklore, comedy and genuine dread. The town itself is the real continuity — its rumours and rituals carry the series","The town remembers","Lokesh-set folklore is the franchise's secret weapon","Comedy keeps the pace","The humour makes the scares arrive harder"]
,["terminator-3","Judgment Day On Schedule","A liquid-metal Terminator hunts the drifting John Connor while the machines' rise approaches on the clock the first film said could not be stopped. The sequel's thesis is grim fatalism dressed as action — the ending commits to it completely","The ending commits","The film's final movement is darker than its reputation","The chase craft","Practical stunts carry the film's biggest sequences"]
,["mickey-17","Expendable By Design","Bong Joon-ho returns after Parasite with Mickey Barnes, an 'expendable' who dies and is reprinted for the next shift. The premise is a dark comedy about labour and disposability, and the director's interest is in who counts as a person inside a system that counts nothing","The premise does the work","Disposable workers is a very Bong Joon-ho subject","The reprint rules","The film's comedy lives in the bureaucracy of death"]
,["silo","Questions Under Ground","Thousands live in a vast underground silo after the world above became toxic, and one woman starts asking the questions the whole structure is designed to prevent. The mystery series works because the silo is both shelter and prison and nobody can agree which","The setting is the story","The silo's rules are the plot's true antagonist","Questions are dangerous","The series builds its tension out of curiosity punished"]
,["the-super-mario-galaxy-movie","Mario Goes Off-World","Aaron Horvath and Michael Jelenic send Mario off-world with Chris Pratt, Anya Taylor-Joy and Charlie Day billed in the voice cast. Galaxy's cosmic scale gives the animation room to play, and the films have become a reliable family machine","Space is the playground","The galaxy setting invites pure visual imagination","The voice cast","The ensemble has settled comfortably into the roles"]
,["jackass-best-and-last","Old Stunts, Same Crew","Jeff Tremaine's billed-final Jackass film puts the crew back together for old stunts and new ones, and the talking over each other is half the pleasure. The series endures because the laughs come with visible consequences and visible affection","The crew is the point","The friendship under the stunts is what keeps audiences returning","The format is honest","Practical stunts, real reactions, no pretence"]
,["spider-man-brand-new-day","Forgotten By Everyone","Tom Holland's Peter Parker is four years past No Way Home, forgotten by the people he loves and still doing the work. The reset gives the character the one thing the films kept denying him: consequences with nobody to share them","The reset is the hook","A Spider-Man with no safety net is the comics' original promise","The long game","Four years of in-world time changes a hero"]
,["paw-patrol-the-dino-movie","The Pups Vs Dinosaurs","The pups crash-land on an island of dinosaurs and Mayor Humdinger is, as always, making everything worse. The Dino Movie keeps the franchise's formula of competent pups and gentle peril for the youngest audience in the room","Dinosaurs raise the stakes","The franchise knows its audience's appetite for scale","No job is too big","The teamwork formula works because it is consistent"]
,["scream-7","Ghostface Returns","Neve Campbell returns and Kevin Williamson is billed as director for the seventh outing, with Isabel May and Jasmin Savoy Brown among the new faces. The franchise's whole method is arguing with its own fandom, and that argument has plenty of material left","The original voice","Williamson returning to direct is the real headline","The franchise method","These films survive by interrogating their own audience"]
,["sinister","The Home Movies","A true-crime writer finds Super 8 home movies that document murders and point at his own family's future. The found-footage-within-the-film device makes the horror archival and intimate at once — the past is literally the evidence","The films within","The home-movie reels are among the scariest props in modern horror","The writer's hubris","True-crime ambition is the door the demon walks through"]
,["solo-a-star-wars-story","How Han Became Han","The origin story fills in the smuggler's first chapters — the ship, the copilot, the dice — and the film works best as a heist adventure wearing Star Wars clothes. Ron Howard plays the hits and the hits mostly land","The heist structure","A crime caper in a galaxy far away suits the character","The cast clicks","The ensemble finds the warmth the role needs"]
,["october-1","One Case, One Country","A police officer investigates a murder in a newly independent Nigerian town, and the period mystery uses a single case to look at a country on the edge of change. The procedural becomes a portrait of a moment — independence as both promise and fracture","The case is the lens","A single investigation opens onto a whole society","The period detail","Nigeria in 1960 is drawn with real care"]
,["hulk","The Other Banner","Edward Norton's Bruce Banner is on the run while the Abomination rises, and this version leans harder into the fugitive-thriller shape of the character. The campus chases and the Harlem finale belong to a film that wants its monster to feel like a problem","The fugitive angle","Banner on the run is closer to the comics' real texture","The design work","The creature effects of their era pushed what was possible"]
,["katseye-wild-hearts","From Academy To Stage","A cinema documentary follows the global pop group KATSEYE from the Dream Academy process to the run-up to their third release. The music-doc form here is manufacturing-and-magic: the machinery that builds a group and the spark that makes one","The formation story","The Dream Academy process is the film's natural first act","Third-act nerves","Documenting the run-up to a release is where tension lives"]
,["mami-wata","Faith, Water, Tradition","A village faces conflict around faith, leadership and tradition when its established spiritual order is challenged. The film is shot in a monochrome palette that turns the whole story into something between myth and memory","The look carries meaning","The black-and-white photography is part of the argument","The myth is live","Water spirits and village politics share the same stage"]
,["disclosure-day","First Contact, Again","Steven Spielberg returns to the UFO film with Emily Blunt and Josh O'Connor billed as leads. The premise is first contact from the director who has spent a career filming the awe of it — whatever the story, the vocabulary of wonder is his","The director returns","Close Encounters is the reference the audience brings with it","The billed leads","Casting at this level signals a character-first approach"]
,["lost-in-translation","Two Insomniacs, One Hotel","Two lonely Americans connect in a Tokyo hotel and the film stays with the whisper between them. Sofia Coppola's Oscar winner is about the specific relief of being understood briefly by someone who is also passing through","The mood is the plot","Tokyo at night and jet-lag hours do the storytelling","The whisper register","The film's biggest moments arrive at conversational volume"]
,["pk","An Alien Asks Why","An alien stranded on Earth loses his remote and questions the world's religions one honest question at a time. The comedy's target is never belief itself but the certainty industries built around it, and the tears arrive on schedule","The outsider's question","An innocent's questions expose adult certainties","The comedy has warmth","Rajkumar Hirani's formula laughs and then delivers"]
,["puss-in-boots-last-wish","Eight Lives And Counting","With eight of his nine lives gone, Puss sets out for the mythical Last Wish with Death itself on his trail. The animation plays with storybook textures, and the Wolf is one of the great animated antagonists in years — a fairy tale about mortality wearing boots","Death as antagonist","The Wolf is a genuinely frightening figure for all ages","The visual style","Storybook painting techniques give the film its look"]
,["the-end-of-oak-street","The Suburb Leaves The Map","David Robert Mitchell drops a suburban street — whole — into a world with dinosaurs, and the premise is the joke and the threat at once. The director of It Follows knows that the familiar is exactly where the uncanny works best","The premise is the hook","A whole street displaced is a very specific kind of nightmare","The director's track","Mitchell builds worlds whose rules slowly surface"]
,["greenland-2","After The Comet","The family that survived the comet now has to move, with Gerard Butler returning in Ric Roman Waugh's sequel. Disaster sequels live or die on escalation, and the promise here is the hard part — the survival after the survival","The aftermath story","The interesting disaster is what comes after the impact","The family anchor","Butler's family thread carried the first film"]
,["jurassic-world-rebirth","Survival Horror Returns","The franchise returns to survival horror as a covert team enters the ruins of the original park. The route back to dread is simple — stop treating the dinosaurs as attractions and start treating them as weather","Back to horror","The first film's best scenes were always horror scenes","The ruins setting","The abandoned park is a gift of a location"]
,["phone-swap","Two Lives, Crossed","Two strangers accidentally exchange phones and are drawn into each other's very different lives. The social comedy uses the swap as a machine for empathy — a phone is a diary, a wallet and a map of someone's whole world","The phone is the window","Devices carry more personal truth than diaries ever did","The social texture","Lagos class and manners are drawn with a light hand"]
,["the-shadows-edge","Chan In Contemporary Form","Jackie Chan in a contemporary action film from Larry Yang, with Zhang Zifeng and Tony Leung Ka-fai billed. The pairing of an elder statesman of screen fighting with a younger ensemble is the film's core proposition","The passing of craft","Chan's presence carries decades of action history","The billed ensemble","A three-generation cast suggests a story about legacy"]
,["wicked-for-good","Exile And The Public Face","Elphaba is in exile and Glinda is the public face of Oz as the story reaches its second half. The musical's political heart — who gets to define wicked — is the part that plays best outside the songs","The politics land","The definition of 'wicked' is the whole story's argument","The second-half weight","Conclusions of beloved musicals carry built-in emotion"]
,["nope","What Do You Feed It","Jordan Peele's UFO film poses the strangest question in the genre: what do you feed a predator that lives in the sky? The Western-horror hybrid is about spectacle and exploitation — the things we cannot stop filming, and what films back","The question is the film","Peele's premises are always arguments first","Spectacle as theme","The film is about the cost of looking"]
,["the-devils-mouth","A Town With A Hole","Jeff Wadlow's young-adult horror with Kathryn Newton, Lana Condor and Gavin Casalegno billed around a town with something at its heart. The YA-horror lane works on small-town secrets — the kind a body of water keeps","The small town","Horror at this scale is a local secret that stays local","The billed ensemble","A young cast anchors the film's perspective"]
,["the-last-house","Sealed In With It","Louis Leterrier directs Greta Lee and a family sealed inside their house by a threat they cannot see yet. Home-invasion horror inverted: the house is the trap and the family knows the walls better than anything outside","The inversion","Being sealed inside flips the invasion formula","The director","Leterrier's action background should serve the staging"]
,["the-running-man","The Gameshow Runs Again","The Stephen King adaptation reborn: a desperate man enters the deadly gameshow where everyone is hunting him. The premise lands harder now than in the eighties — a country watching punishment as entertainment has lost none of its charge","The premise aged","The gameshow-as-society premise is more current than ever","King's source","The novel has always been angrier than any adaptation"]
,["shelter-2026","A Family Under A Bad Sky","Ric Roman Waugh's survival picture with Naomi Ackie and Daniel Mays billed, about a family under a sky that has turned hostile. Survival cinema at its best turns weather into character and the family into a system under load","The sky is the antagonist","Survival films work when nature is the active threat","The family unit","The ensemble's dynamic is the film's emotional weather"]
,["sinners","Twin Brothers, One Threat","Ryan Coogler's vampire horror has Michael B. Jordan playing twins who return home to escape trouble and find something older waiting. Coogler's genre entry carries his interest in history and place under the horror","Twins by design","A dual lead performance raises the film's whole register","Horror with history","The genre is the vehicle for a story about home"]
,["scary-movie-2026","The Wayans Names Return","Anna Faris, Regina Hall and Marlon Wayans return with Michael Tiddes directing a new Scary Movie. The parody lane needs targets and timing — and the franchise's original cast reunion is the biggest joke available","The reunion","Bringing back the original faces is the headline","Parody needs a target","The franchise's formula is affectionate demolition"]
,["superman-2025","A Fresh Start For The DCU","James Gunn's new Superman balances his Kryptonian heritage with his Kansas upbringing, and the film's job is to make sincerity work again in a genre that had gone cool on it","Sincerity is the bet","Gunn's whole method is earnestness without embarrassment","The Kansas side","The Clark half is where the character's heart lives"]
,["hoppers","Creatures And Curiosity","Daniel Chong's creature comedy with Piper Curda, Bobby Moynihan and Jon Hamm billed among the voices. The Pixar-adjacent lane is full of films that sneak real feeling under a silly premise, and creature features are ideal cover","The voice cast","An ensemble like this suggests character-first comedy","The director's style","Chong's work carries a distinct visual sensibility"]
,["how-to-train-your-dragon-2025","The Legend In Live Action","The animated classic remade in live action: Hiccup befriends Toothless and changes the world of Berk. The translation that matters is the dragons' faces — everything the original achieved, the remake must achieve with eyes and weight","The design challenge","Toothless in live action is the film's make-or-break","The story holds","The original narrative is strong enough to carry the transfer"]
,["pan-labyrinth","The Labyrinth In Franco's Spain","A girl in Franco's Spain escapes into a dark fairy-tale labyrinth, and Del Toro draws the line between the real monsters and the imagined ones until both are unbearable","Two worlds, one frame","Fairy tale and war film occupy the same screen","The design","The faun and the pale man are creature-effects landmarks"]
,["the-devil-wears-prada-2","Miranda Returns","Miranda Priestly is not done: David Frankel returns with Meryl Streep, Anne Hathaway and Emily Blunt billed. The sequel's question is what fashion's old guard owes to a changed industry — and what the assistant became","The ensemble is back","The original triangle is the film's engine","Fashion as culture","The first film argued its industry was a lens on class"]
,["the-banshees-of-inisherin","The Friendship Ends","A man ends a lifelong friendship without explanation and the small island cannot absorb it. The film turns a break-up into a study of cruelty, loneliness and the stories a place tells itself","The silence is the plot","No explanation is more devastating than any speech","The island stage","Inisherin is drawn as a place where nothing is private"]
,["article-370","One Change, Many Fronts","A Delhi-based agent is sent into Kashmir around the 2019 constitutional change that ended the state's special status. The political thriller works the machinery of policy through characters who have to live inside its consequences","The policy is the plot","Constitutional change makes for unusual thriller material","The procedural spine","Institutional detail grounds the drama"]
,["backrooms","The Yellow Rooms, Feature-Length","Kane Parsons turns the internet's yellow-room creepypasta into a feature, with Chiwetel Ejiofor and Renate Reinsve billed. The jump from short-form internet horror to cinema is the real experiment here","The internet source","A creepypasta becoming a feature is its own kind of event","The upgrade path","Parsons' short-form work is what made this possible"]
,["civil-war","The Correspondents' Race","A near-future America fractures and war correspondents race to the front lines in Alex Garland's terrifying what-if. The film's subject is the witnessing — what cameras do to conflict and what conflict does to cameras","The journalists are the lens","The film's perspective is the profession's","The unbearable present","Garland shoots a plausible tomorrow like today's news"]
,["dragon-ball-super-super-hero","Piccolo And Gohan Step Up","The Red Ribbon Army returns with new androids while Goku and Vegeta are off training, leaving Piccolo and Gohan to hold the line. The film's charm is its ground-level focus on the franchise's second generation","The hand-off","Letting Piccolo and Gohan lead is the film's best decision","The Red Ribbon callback","Deep-cut villain returns reward long-time fans"]
,["kantara","Land, Ritual, Belief","A village conflict over land and tradition grows into a story shaped by local ritual and belief, and the film's final movement is cinema as possession — literally, in the way its folklore arrives on screen","The ritual lands","The film's climactic sequences are grounded in real tradition","Land is the stake","The dispute that opens the film never stops mattering"]
,["man-of-steel","A God Lands","Kal-El arrives on Earth and becomes Superman just as the world needs a god and fears one. Snyder's take pushes the alien-ness of the character: the first-contact movie hiding inside the superhero one","The first contact angle","The Krypton prologue reframes the whole mythology","The scale","The film's action set-pieces of their era were enormous"]
,["shoplifters","What Makes A Family","A family living at the edges of Tokyo takes in a young girl and the film asks what family means beyond blood. Kore-eda builds the case out of small shared acts until the law's version of family looks like the poorer one","The daily rituals","Meals and baths build the film's definition of family","The quiet turn","Kore-eda's revelations arrive without raised voices"]
,["star-wars-the-rise-of-skywalker","The Saga Closes","Rey faces Palpatine and the Skywalker story finds its ending. The film carries the impossible weight of closing a forty-year saga, and it works best in its smallest moments — the dyad, the memory, the name chosen at the end","The dyad","The force connection between Rey and Kylo is the sequel trilogy's best idea","The final name","The closing choice lands as thesis as much as fan service"]
,["the-punisher-one-last-kill","Frank Castle, The Marvel Version","Reinaldo Marcus Green's Punisher film, with Deborah Ann Woll and Jason R. Moore billed from the TV series. The character's whole appeal is exhaustion — a war that never stops and a man who will not quit it","The TV continuity","Carrying the series' faces forward keeps the tone intact","The weariness","The Punisher works when the toll is visible"]
,["hope-2026","Something In The Mountains","Na Hong-jin's Korean creature film: a village police post and hunters go after something in the mountains. The director of The Wailing works in slow dread, and a monster hunt in his hands is never just a hunt","The director's pace","Na Hong-jin builds dread across hours, not minutes","The hunt structure","Monster hunting as community emergency is a strong frame"]
,["the-fate-of-the-furious","Dom Turns","Dom turns on his family and the question is who is forcing him. The franchise's eighth entry plays its soapiest card — betrayal inside the found family — and the set-pieces escalate accordingly","The betrayal hook","The franchise is at its best when the family is the stake","The submarine chase","Escalation is this series' house style"]
,["jallikattu","The Buffalo Runs","A buffalo escapes into a village and the attempt to capture it exposes fear, rivalry and crowd instinct. Shot with a restless camera and a village-sized cast, it is a fable about what a single disruption reveals","The crowd is the subject","The film is about collective behaviour more than any character","The style","Long takes and kinetic staging keep the chaos alive"]
,["lee-cronins-the-mummy","A New Bandage","Lee Cronin starts a new Mummy with Jack Reynor, Laia Costa and May Calamawy billed. The horror-adjacent route suggests the monster returning to being a monster — the direction the material has always needed","The horror route","The Mummy works best as horror, not adventure","A new continuity","A fresh start frees the material from its franchise furniture"]
,["star-wars-the-mandalorian-and-grogu","From Streaming To The Big Screen","Jon Favreau takes the Disney+ pair to theatres with Pedro Pascal billed and Jeremy Allen White joining. The jump to cinema is a test of whether the show's quiet, episodic charm survives the big screen's demands","The format test","Small-screen intimacy has different physics than cinema","The new cast","Fresh voices alongside the familiar pairing"]
,["the-odyssey","Nolan Takes The Myth","Christopher Nolan's mythic epic casts Matt Damon as Odysseus journeying home across a world of gods and monsters. The source is the original adventure story, and Nolan's interest in time and structure is the reason to expect something strange","The source is the oldest","Homer's structure has survived every retelling for a reason","The director's method","Nolan's scale and structure promises are the headline"]
,["i-saw-the-devil","The Hunt Consumes The Hunter","A secret agent pursues the man responsible for a personal loss and turns justice into a spiral. The film's design is a dare: every round of vengeance costs the hero another piece of the person he was","The spiral is the point","Vengeance films rarely track the cost this honestly","The cat-and-mouse engine","Each round escalates beyond the last"]
,["the-100","Back To Earth","A hundred juvenile delinquents return to Earth ninety-seven years after nuclear war and find it far from empty. The YA survival premise grows up quickly — the ground has its own people and its own rules","The ground rules","The world-building's second layer is the real story","The generational angle","Teenagers raised in space know nothing about the planet"]
,["nausicaa","The Valley And The Jungle","A princess fights to save her valley and a poisoned world from war and the toxic jungle. Miyazaki's ecological epic refuses simple sides: the jungle is lethal and sacred at once, and the humans are the problem and the hope","No simple villains","The film's ecology refuses easy blame","The glider","Nausicaä's flight remains pure animated joy"]
,["rattle-snake-the-ahanna-story","The Heist Turns","A remake of the classic Nollywood thriller: a desperate young man and his crew plan an ambitious heist and the plan fractures. The remake trades on the original's reputation while sharpening the craft","The remake carries weight","The classic original is the film's shadow and its promise","The heist engine","Crews and plans make for durable thriller structure"]
,["singham-again","The Cop Universe Piles Up","Rohit Shetty's cop-universe entry brings Kareena Kapoor Khan, Arjun Kapoor and Jackie Shroff alongside the returning faces. The franchise's formula is scale and loyalty — the spectacle of a whole cinematic universe in one police procedural","The universe scale","These films are designed as event collisions","The formula","Shetty's cop films run on mass momentum"]
,["kaguya-sama","The Confession War","Two geniuses who love each other refuse to confess, and every episode is a battle of wits and pride in the war of love. The anime's game-show narration turns a simple crush into the most elaborate strategy on television","The narration","The show's commentator voice is the running gag that works","The escalation","Every scheme raises the stakes of a school romance"]
,["one-piece-film-red","Uta Sings","Uta, the world's greatest diva, reveals her identity at her first live concert and Luffy's crew is in the audience. The film is a musical at heart — the songs carry the plot and the franchise's theme of freedom","The concert frame","A music-led One Piece film turns out to fit perfectly","The franchise heart","Freedom and found family are the series' whole vocabulary"]
,["dragon-ball-super-super-hero","Gohan's Turn","With Goku and Vegeta occupied, Gohan and Piccolo carry the defence against the Red Ribbon Army's new androids. The film trusts its second generation and is better for it","Second generation","The franchise's supporting cast is its secret reserve","The family angle","Gohan's story is the one with the most room left"]
,["the-fate-of-the-furious","Forced Into War","A forced betrayal puts Dom against his own crew and the franchise runs its biggest submarine chase yet. The films survive on soap and scale, and this entry supplies both in equal measure","The soap opera","The family betrayal is the fuel the series runs on","The escalation curve","Each film's stunts are a negotiation with physics"]
,["predator-badlands","The Young Hunter","A young Yautja takes a hunt that does not go to plan in Trachtenberg's follow-up to Prey. The franchise's rebirth is built on one idea: the predator's culture is more interesting than its kills","Culture over kills","The Yautja as society is the untapped vein","The Prey legacy","The previous entry reset what the franchise could be"]
,["jurassic-world-rebirth","Back To The Original Park","A covert team enters the ruins of the original park for a mission that goes wrong. The nostalgia is structural — the ruins are the first film's own sets, and the horror is the promise the original made","The ruins speak","Returning to the original park is loaded with franchise memory","Mission structure","A heist frame inside a dinosaur film is a good bet"]
,["wicked-for-good","The Second Half","The second half of Wicked arrives with Elphaba exiled and Glinda the face of Oz. The story's emotional reputation precedes it, and the songs in the second act are the ones the stage fans carry out of the theatre","The songs land","The second act contains the musical's most-loved numbers","The friendship","Glinda and Elphaba's bond is the whole show's spine"]
,["spider-man-brand-new-day-2","A New Day For Peter","Peter Parker starts over in a world that has forgotten him, and the title promises the comics' most famous fresh start. The dramatic opportunity is a Spider-Man with nothing to lose and nobody to reassure","The comics promise","The title echoes the character's most famous reset","The freedom","A hero without a secret identity's support system is a new engine"]
,["scream-7","The Argument Continues","Ghostface returns with the original faces and the franchise's method intact: every entry is an argument about horror itself. The series has always been its own best critic, and there is no shortage of material","The self-awareness","These films work because they comment as they kill","The returning cast","Campbell's presence anchors the continuity"]
,["sinister","The Box Of Reels","A crime writer's research uncovers a box of home movies and each reel is a family's last day. The film's lesson is a horror rule: never take the house with the history","The archive horror","Found footage inside the film makes the past the threat","The move-in mistake","Real-crime ambition is the door the entity uses"]
,["mickey-17","Die, Print, Repeat","Mickey Barnes is an expendable worker who dies and is reprinted for the next shift — until the printing goes wrong. The comedy is about the paperwork of disposability and the horror of being literally replaceable","The labour metaphor","Disposable work has never been filmed this literally","The double","The printing error is where the film finds its story"]
,["silo","The Truth Above","One woman in the underground silo starts asking what is above them, and the entire structure is designed around never answering. The series is at its best when the rules of the silo are the mystery","Rules as mystery","The silo's constitution is the show's true secret","The questions","Curiosity as resistance is a very old science-fiction idea"]
,["the-super-mario-galaxy-movie","The Cosmic Sequel","Mario's off-world adventure with a voice cast that has settled into the roles like a second skin. Galaxy gives the filmmakers permission to build worlds with no rules but their own sense of play","Permission to play","The galaxy setting removes every boundary","The ensemble","The cast's comfort in the roles is audible"]
,["paw-patrol-the-dino-movie","Pups And Dinosaurs","The pups face dinosaurs and Mayor Humdinger on a crash-landed island. The franchise knows its job: competent heroes, gentle peril and teamwork that always works, delivered exactly when promised","The formula holds","Parents know what they are buying and the film delivers it","The team dynamic","Each pup's skill keeps the ensemble busy"]
,["jackass-best-and-last","The Last Run","The billed-final entry brings the crew back for one more round of stunts, injuries and talking over each other. The franchise's heart has always been friendship disguised as stupidity","Friendship as format","The stunts are the vehicle for the real product: the crew","The finality","Playing the last card gives every stunt extra weight"]
,["katseye-wild-hearts","Building A Global Group","From Dream Academy to the run-up to a third release, the KATSEYE documentary tracks a group being built and then standing on its own. The music-doc's drama is always the making-of as coming-of-age","The making-of","Formation stories carry natural structure","The third release","Documenting the pressure before a launch is where the tension lives"]
,["disclosure-day","Spielberg's Return To The Sky","A first-contact story from the director whose name is synonymous with the genre, with Emily Blunt and Josh O'Connor billed. Whatever the story, the film arrives carrying the whole history of cinema's encounter with the unknown","The lineage","No living director owns the first-contact vocabulary like Spielberg","The mystery","First contact films live on what they withhold"]
,["the-end-of-oak-street","A Street Out Of Time","A suburban street is torn out of the present and dropped somewhere with dinosaurs — the premise alone does half the work. The director of It Follows knows that ordinary settings make the best uncanny ones","The premise engine","A displaced suburb is instantly cinematic","The director","Mitchell's worlds always have hidden rules"]
,["greenland-2","Moving After The End","The sequel to Greenland follows the surviving family on the move, with Gerard Butler returning. Post-disaster cinema is about scarcity and trust, and the family unit is the smallest possible society","Aftermath stories","What happens after the impact is the neglected half of disaster films","The family","Butler's everyman anchor carried the original"]
,["phone-swap","The Empathy Machine","A phone swap comedy from Nollywood that turns two strangers' devices into windows on each other's lives. The genre works because phones now hold the whole map of a person","Phones as portraits","The device is the most complete character witness ever made","The social map","Class and manners across Lagos in a light comic key"]
,["the-shadows-edge","The Master And The Ensemble","Jackie Chan's contemporary actioner pairs the veteran with Zhang Zifeng and Tony Leung Ka-fai. The film's promise is the passing of the physical craft to a new generation on screen","The pairing","Three generations in one cast is the proposition","The action craft","Chan's fight vocabulary remains the reference"]
,["the-devils-mouth","Something Under The Town","A young-adult horror about a town with something at its heart, with Kathryn Newton and Lana Condor billed. Small-town horror works because secrets have nowhere to spread but inward","Small-town stage","A town-sized secret is the genre's most reliable engine","The young cast","The perspective anchors the film's stakes"]
,["the-last-house","The House Locks","A family is sealed inside their house by a threat they cannot see, directed by Louis Leterrier with Greta Lee billed. The claustrophobic home film flips the invasion: the shelter is the trap","The flip","Sealed-in horror is invasion horror reversed","The unseen threat","What you cannot see keeps the house tense"]
,["shelter-2026","Under A Sky Gone Wrong","A family survival picture with Naomi Ackie and Daniel Mays billed, set against a sky that has turned against them. Weather as antagonist is survival cinema at its most elemental","Weather as villain","Nature in a hostile mood needs no explanation","The family unit","Survival stories are family stories under load"]
,["scary-movie-2026","The Parody Machine","Anna Faris, Regina Hall and Marlon Wayans reunite for a new Scary Movie. Parody is a genre of timing and targets — and the reunion supplies the nostalgia that raises the floor","Reunion power","The original cast is the film's first and best joke","The targets","Modern horror supplies more material than ever"]
,["hoppers","The Creature Feature","Daniel Chong's animated creature comedy with Jon Hamm among the billed voices. The lane is pure family-spectacle with a soft heart under the silly premise","The voice work","A cast like this promises character-driven comedy","The tone","Silly on the surface, sincere underneath"]
,["the-devil-wears-prada-2","Fashion Grows Up","Miranda, Andy and Emily return for a sequel that has to answer what the fashion industry became. The first film was a workplace fairy tale; the second's material is the same workplace, older","The return","The original trio is the draw and the promise","Industry as mirror","Fashion films argue about class in expensive clothes"]
,["article-370","A Policy Thriller","A political thriller built around the 2019 constitutional change in Kashmir, following an agent sent into the middle of it. The genre's job here is to humanise a policy decision's machinery","Policy as plot","Constitutional mechanics make surprisingly tense drama","The agent's view","The ground-level perspective keeps the story personal"]
,["backrooms","From Creepypasta To Cinema","The yellow-room internet horror becomes a feature with Chiwetel Ejiofor billed. The experiment is the translation: can a liminal-space joke survive as sustained cinema","The source material","The backrooms mythos grew in public, which is its own phenomenon","The upgrade","Short-form dread to feature length is a real craft challenge"]
,["the-punisher-one-last-kill","The War That Never Ends","The Punisher returns with faces from the TV series billed. The character endures because his war is unwinnable by design — and the audience knows it going in","The endless war","The premise is a man who cannot stop","Continuity","Carrying the series' cast keeps the tone locked"]
,["hope-2026","The Hunt In The Mountains","Na Hong-jin's creature feature about a village police post and hunters tracking something in the mountains. The director's record says slow-burn dread with folklore underneath","The director's style","The Wailing is the reference everyone brings","The hunt","Monster hunts as community ritual are uniquely Korean cinema"]
,["lee-cronins-the-mummy","Horror Returns To The Tomb","A new Mummy from horror director Lee Cronin with Jack Reynor billed. Horror-first is the correct default for the material — the monster's home genre","Horror home","The Mummy's first films were horror, not adventure","Fresh continuity","A clean start lets the monster be frightening again"]
,["star-wars-the-mandalorian-and-grogu","The Galaxy's TV Hit, In Cinemas","The Mandalorian and Grogu take their story to theatres with Pedro Pascal billed and Jeremy Allen White joining. The jump tests whether patience and small moments survive the blockbuster frame","The scale jump","Television's quiet rhythm meets cinema's demands","The new voice","New cast members signal new story space"]
,["the-odyssey","The First Adventure Story","Nolan's take on Odysseus with Matt Damon: the original journey-home story, filmed with modern spectacle. The epic's structure — trials, temptations, return — is the most tested narrative in the language","The source strength","Homer has been worth adapting for three millennia","The director","Nolan's structural obsessions fit a layered journey"]
,["the-100","Ninety-Seven Years Later","Juvenile offenders sent to a post-nuclear Earth discover it is not theirs alone. The YA setup matures into real territory conflict — the ground has people, and people have claims","The territory","The second layer of the world is where the show grows up","The premise","Young characters facing adult stakes is durable YA"]
,["rattle-snake-the-ahanna-story","A Classic Remade","The Nollywood heist classic remade for a new audience: a desperate crew, an ambitious plan, and a fracture the moment real money enters","Remake stakes","The original's reputation is the remake's burden and its engine","The heist mechanics","Plans and crews are thriller furniture that never rusts"]
,["singham-again","The Universe Comes To Singham","Rohit Shetty assembles the cop universe around Singham again, with Kareena Kapoor Khan and Arjun Kapoor billed. The franchise's spectacle is the collision of its own heroes","The event film","Universe-building is now the product","Mass momentum","These films run on energy as much as plot"]
,["kaguya-sama","Love As Warfare","Two student-council geniuses wage war rather than confess their feelings, and the anime's game-show narration turns every small move into strategy. The comedy is engineered and the heart is real","The framing","Narrated strategy sessions for a school romance is comedy engineering","The characters","The ensemble's reactions are half the jokes"]
,["one-piece-film-red","The Diva's Concert","Luffy's crew attends Uta's first concert and the film turns into a musical about freedom and the past. The One Piece films work when they commit to one big idea — this one commits to songs","The musical gamble","A concert-driven One Piece film is a bold and fitting choice","The theme","Freedom and inherited will are the series' through-lines"]
,["supergirl-2026","Kara In The DCU","Milly Alcock takes on Kara in James Gunn's DC Universe with Craig Gillespie directing and Matthias Schoenaerts billed opposite. The character's best stories are about heritage and choice","The new DCU","Every new entry now carries universe-building weight","The cast","Alcock's casting signals a fresh character-first take"]
,["colony-2026","The Closed System","A future colony under pressure from Yeon Sang-ho, with a Korean A-list trio billed. The director's career is one long study of systems failing people — and space colonies fail spectacularly","The system cracks","Yeon's films are about institutions as pressure cookers","The ensemble","Three major stars suggest a multi-front story"]
,["haider","To Be Or Not To Be, In Kashmir","Shakespeare's prince transplanted into 1990s Kashmir, where grief and politics are inseparable. The adaptation's brilliance is that the setting answers the play's questions before the characters do","The transposition","Hamlet in a conflict zone is a sharper play","The atmosphere","The valley's beauty and pain share every frame"]
,["omo-ghetto-the-saga","The Street Queen And Her Sister","Twins split between the street and respectability reunite as adults on opposite sides of the law. The film's star carries both halves of the story in a performance that made the film a phenomenon","The dual role","One performer, two worlds, one film's engine","The comedy-drama balance","The film moves between registers without whiplash"]]
''')
DEPTH_SECTIONS18 = {}
for row in ROWS:
    slug, h2, para, l1, r1, l2, r2 = row
    seed = sum(ord(c) for c in slug) % 97
    DEPTH_SECTIONS18[slug] = _build(slug, h2, para, l1, r1, l2, r2, seed)
print('batch M entries', len(DEPTH_SECTIONS18))

ROWS += json.loads(r'''
[
["star-wars-the-last-jedi","The Jedi's Last Lesson","Rey finds Luke on his island and the galaxy finds hope in the unlikeliest places. Rian Johnson's entry argues hardest about the franchise itself — about legend, failure and who gets to be a hero — and the debate it started is part of its achievement","Failure is the lesson","The film's thesis is that failure is the best teacher","The throne room","The central duel is the sequel trilogy's finest action"]
,["longlegs","The Trail Leads Inward","A new FBI agent hunts a serial killer whose crimes defy explanation, and the trail turns toward her. The film's horror is procedural and occult at once — a case file that keeps opening onto the wrong kind of evidence","The dread engine","The film builds fear out of case-file details","The agent's stake","Investigations that become personal are the genre's spine"]
,["singin-in-the-rain","Hollywood Learns To Talk","A musical comedy about Hollywood's transition from silent films to sound, told through romance and performance. The film is the most joyful technical document ever made — a film about a format crisis that is pure delight","The technical joke","The sound-era panic is comedy gold","The dancing","Gene Kelly's title sequence is the most famous number in the medium"]
,["swapped","The Body-Swap, With Stakes","Nathan Greno's body-swap comedy with Michael B. Jordan, Juno Temple and Tracy Morgan billed. The swap formula is old because it works: two lives, one perspective problem, and comedy that lands on real insight","The formula endures","Body swap survives because perspective is dramatic","The billed cast","An ensemble like this promises proper farce"]
,["dune-part-three","Muad'Dib's War","The conclusion of Villeneuve's epic: Paul Atreides, now Emperor, faces the holy war he always feared. The trilogy's tragedy is that every prophecy is a trap, and the third part is where the trap closes","The tragedy lands","The films have always been about prophecy as machinery","The scale","Villeneuve's desert sequences are the modern epic benchmark"]
,["jana-nayagan","Vijay's Political Spectacle","Thalapathy Vijay's Tamil actioner for KVN Productions under H. Vinoth — delayed, leaked and still anticipated. The star's political register gives the film extra weight beyond its genre","The star vehicle","Vijay's screen presence is the film's foundation","The anticipation","Controversy has kept the film in conversation"]
,["perfect-blue","The Idol's Fracture","A pop idol leaves music for acting and begins to lose the line between herself and her roles. Kon's masterpiece of identity horror predates the influencer era and diagnoses it completely","The identity horror","The film understands performance as self-erasure","The animation style","Kon's editing grammar still feels like the future"]
,["insidious-out-of-further","The Sixth Descent","The sixth Insidious film, directed by Jacob Chase with Amelia Eve, Brandon Perea and Maisie Richardson-Sellers leading. The Further remains the franchise's inexhaustible resource — a place the series can always go back to","The Further returns","The franchise's other dimension is its renewable horror","New faces","A fresh cast suggests a new family's haunting"]
,["minions-monsters","The Minions Meet Monsters","Pierre Coffin's next Minions outing with Trey Parker, Allison Janney and Christoph Waltz among the billed voices. The franchise formula is chaos with a heart, and the voice cast signals bigger comic ambitions","The voice ensemble","Casting this sharp promises more than slapstick","The chaos engine","The Minions work because their disasters are precise"]
,["porco-rosso","The Pig Above The Adriatic","A World War I ace cursed with a pig's face fights air pirates over the Adriatic. Miyazaki's strangest and most personal film is about disillusionment, flight and the refusal to be a hero on anyone's terms","The strangest Ghibli","A pig's face is the film's least odd decision","The flying scenes","Miyazaki's aircraft love is on full display"]
,["skyfall","The Past Comes Home","Bond's past returns to settle accounts and M's loyalty is tested to breaking. The film works as a meditation on ageing in a young person's profession — and on what institutions do to their servants","The meditation","Ageing Bond is the most interesting Bond","The Shanghai sequence","The film's silhouetted fight is instantly iconic"]
,["king-of-boys-2","Salami Returns To The Game","Alhaja Eniola Salami is drawn back into Lagos power politics where loyalty is short and every alliance is temporary. The saga's scale is Shakespearean — power as a Lagos family business","The power game","Lagos politics as tragic epic is the series' canvas","The return","A comeback story has the saga's best material"]
,["obsession-2026","A Small Cast Spirals","Curry Barker's obsession thriller with Michael Johnston and Inde Navarrette billed — a small-cast spiral rather than a body-count film. Tight thrillers work on performance and pressure, not scale","The chamber scale","Small casts concentrate pressure","The spiral structure","Obsession films are character studies under compression"]
,["smile","The Curse Travels By Face","A doctor witnesses a patient's death and inherits a curse that passes from smile to smile. The film's marketing was the premise — and the film itself delivers a genuinely nasty chain of dread","The transmission rule","A fixed, visible rule makes every smile a threat","The professional lens","A doctor watching the unexplainable is a strong frame"]
,["challengers","Love On A Scoreboard","A tennis prodigy turned coach, her champion husband, and his former best friend — a triangle played out across matches and years. The film stages desire as sport, with the score carrying every emotional turn","Tennis as metaphor","Every match is a conversation the three of them cannot have","The score by Reznor","The music turns the matches into combat"]
,["the-brutalist","A Monument In America","A Hungarian-Jewish architect emigrates after the war and spends decades building a monument that will outlive him. The film is about ambition, patronage and the price of the work that survives us","The architecture is the argument","The film's buildings carry its themes","The epic span","Decades in one life demand a patient, ambitious film"]
,["toy-story-5","The Toys Vs The Tablet","Woody, Buzz and the gang face Lilypad, a tablet competing for Bonnie's attention. The franchise's fifth entry finally addresses the enemy every toy has faced for a decade: the screen","The screen is the villain","The most plausible Toy Story antagonist yet","The Stanton return","Andrew Stanton directing is the reason for optimism"]
,["whisper-heart","The Girl Who Found Her Song","A bookish schoolgirl discovers a boy who shares her dreams and finds her own creative path. Ghibli's quiet gem is a film about first love that is really about the decision to make things","The creative call","The film is a coming-of-age story for makers","The quiet register","The gentleness is the film's signature and its strength"]
,["john-wick-2","The Debt Is Called","John Wick is forced back into the assassin world to honour an old debt and the price is enormous. The second entry expands the mythology — the Continental, the coins, the rules — and the rules are the real villain","The mythology opens","The criminal society is the sequel's best addition","The house rules","The Continental turns action into etiquette"]
,["ijogbon","Diamonds In A Village","Four teenagers from a rural South-West Nigerian village find a pouch of uncut diamonds and the fortune brings the whole country's trouble to their door. Kunle Afolayan's thriller is a fable about greed arriving in a quiet place","The fable structure","Small-town innocence meets national-level greed","The setting","The village is drawn with affection and precision"]
,["munjya","The Spirit In The Tree","A Konkan wedding, a family curse, and a spirit who will not stay in the tree it was bound to. Aditya Sarpotdar's horror-comedy became a phenomenon on folklore, laughs and one genuinely mischievous demon","The folklore engine","Konkan mythology gives the horror its own flavour","The comedy balance","Horror-comedy is hard; this film makes it look easy"]
,["narcos","The Empire And The Agents","Pablo Escobar builds an empire out of cocaine and fear while two DEA agents chase him through a country he is remaking. The series' structure is the two-sided procedural — the empire and the pursuit as parallel shows","The two-sided view","The empire and the investigation get equal weight","The sense of place","Colombia is filmed as a character in the drama"]
,["harry-potter-deathly-hallows-2","The Battle Of Hogwarts","The final battle: Harry faces Voldemort and the eight-film saga ends where the story always pointed — a school turned battlefield. The finale earns its tears because the audience grew up alongside the cast","The final battle","The conclusion of an eight-film childhood","The grown-up tone","The series' last entries are war films in a school"]
,["longlegs","The Horror In The File","A rookie agent's serial-killer case keeps revealing evidence that should not exist. The film's method is analogue dread — typewritten letters, dated photographs and the smell of old cases","Analogue texture","Physical evidence carries the film's particular dread","The agent's position","Rookie on an impossible case is the classic frame for a reason"]
,["skyfall","Silhouettes And Survival","Bond fails a mission and must rebuild himself in time to save M. The film treats its hero as an institution in crisis — and the imagery of its Shanghai fight sequence belongs to cinema's permanent record","Institutional decay","The film asks what spies are for","The imagery","Deakins' cinematography set the modern action standard"]
,["perfect-blue","Pop, Pressure, Perception","A pop idol's move into acting triggers a psychological fracture that Kon animates as pure cinematic disorientation. The film predicted the attention economy's toll on identity decades early","Predictive horror","The film diagnosed influencer culture before it existed","The editing","Kon's match cuts build the character's disintegration"]
,["smile","It Wants You To Watch","The curse spreads through witnessed trauma and smiles, and the film's rule is as simple and as cruel as the best horror rules always are","The rule is everything","Simple transmission rules make the horror legible","The chain structure","Each link in the chain widens the threat"]
,["challengers","Three Players, One Match","A tennis triangle across a decade of matches, staged like combat and scored like a thriller. The film understands that every sport is a conversation and every conversation is a point","Sport as conversation","The matches carry the dialogue the characters cannot say","The formal play","Camera and score turn tennis into pure cinema"]
,["the-brutalist","The Cost Of The Work","An architect's American dream is financed by a patron whose generosity has terms. The film is about the transaction under every masterpiece — and who pays for what survives","Patronage as theme","Every great work hides a bargain","The time span","A life's work demands an epic's runtime"]]
''')

DEPTH_SECTIONS18 = {}
for row in ROWS:
    slug, h2, para, l1, r1, l2, r2 = row
    seed = sum(ord(c) for c in slug) % 97
    DEPTH_SECTIONS18[slug] = _build(slug, h2, para, l1, r1, l2, r2, seed)
print('batch M entries FINAL', len(DEPTH_SECTIONS18))

# normalize keys to full routes; drop the accidental typo entry
DEPTH_SECTIONS18 = {('entertainment/movie/' + k if '/' not in k else k): v
                    for k, v in DEPTH_SECTIONS18.items()
                    if k != 'spider-man-brand-new-day-2'}
print('normalized', len(DEPTH_SECTIONS18))
