# BRYME Tech - roadmap batch T6: the acting-up layer. Batch 76, 14 Sep 2026.
# Symptom router + overheating + data diet + earbuds buying. Stable facts only;
# video data figures are the streaming industry's usual published rates, hedged
# as approximations; no model endorsements, no fabricated prices.

TECH_ROADMAP_T6 = [
("phone-acting-up-symptom-finder", "android", "guide",
"Phone acting up? Find the symptom, get the fix",
 "Battery draining fast, Wi-Fi dropping, apps crashing, storage full: match what your phone is doing to the page that fixes it - in the order a technician would check.",
"""<p>Phones rarely break all at once; they misbehave one symptom at a time. This page is the front desk for that: find what your phone is doing, and it walks you to the guide that actually fixes it - every link is a page on this desk, written to be followed with the phone in your hand.</p>
<h2>Find your symptom</h2>
<p><b>Battery dies by mid-afternoon:</b> usually habits and background apps, not a dying battery - start with <a href="/tech/android-battery-health/">battery health and what drains it</a>, then check whether the phone itself is aging: <a href="/tech/why-phones-slow-down/">why phones slow down</a>.</p>
<p><b>The phone gets hot:</b> warmth while charging or navigating is normal; heat with performance problems is not - <a href="/tech/phone-overheating-causes-and-fixes/">overheating, causes and fixes</a> (read the swollen-battery warning; it is the one stop-everything item on this page).</p>
<p><b>Wi-Fi keeps dropping:</b> the fix order matters - phone first, then router, then the internet itself: <a href="/tech/phone-wont-connect-to-wifi/">the Wi-Fi checklist</a> and <a href="/tech/wi-fi-router-placement/">where the router should sit</a>.</p>
<p><b>Bluetooth will not pair:</b> nine times out of ten it is the pairing memory, not the hardware - <a href="/tech/bluetooth-not-pairing/">the pairing fix</a>.</p>
<p><b>Apps crash on open:</b> one app or all apps tells you which side the problem is on - <a href="/tech/app-crashes-android/">crashing apps, diagnosed</a>.</p>
<p><b>Notifications arrive late or never:</b> almost always a battery-optimisation setting, not a broken phone - <a href="/tech/android-notifications-not-arriving/">the notification fix</a>.</p>
<p><b>Mobile data not working (or vanishing fast):</b> first make it work, then make it last - <a href="/tech/mobile-data-not-working/">data not working, fixed</a>, then <a href="/tech/use-less-mobile-data/">the data diet</a>.</p>
<p><b>Storage full and apps misbehaving:</b> a full storage chip breaks apps in weird ways - clear it properly with <a href="/tech/free-up-storage-android/">the storage cleanup</a> and understand the breakage in <a href="/tech/storage-full-breaking-apps/">what a full phone breaks</a>.</p>
<p><b>Everything is just slower than it was:</b> age, storage, updates or the lot - the honest version is on <a href="/tech/why-phones-slow-down/">why phones slow down</a>.</p>
<h2>Before any of it: the two-step ritual</h2>
<p>Restart the phone (the reason it works is on <a href="/tech/why-restarting-fixes-problems/">why restarting fixes things</a>), then check storage. Those two steps clear a remarkable share of acting-up tickets, and the pages above assume you have done them. And before anything goes badly wrong for good: the backup habit - <a href="/tech/android-backup-guide/">the Android backup guide</a> - is the difference between a fix and a funeral. Ask the desk that learned it the hard way: <a href="/tech/phone-died-no-backup/">phone died, no backup</a>.</p>""",
 [],
 [("android-battery-health", "Battery health, honestly"), ("why-phones-slow-down", "Why phones slow down"), ("android-backup-guide", "The backup habit")]),
("phone-overheating-causes-and-fixes", "android", "guide",
"Why your phone gets hot - and what actually fixes it",
 "Normal warm versus warning hot: the four honest causes, the fixes in order, and the one physical sign that means stop using the phone today.",
"""<p>A warm phone is a working phone - chips shed heat, and fast charging, navigation and camera work all make honest warmth. Trouble is when warm becomes hot, stays hot at idle, or comes with throttling: the phone slowing itself down on purpose to survive. Here is what actually causes it, in the order it actually happens.</p>
<h2>The four honest causes</h2>
<p><b>1. Sunlight and hot environments.</b> A phone on a car dash or in direct sun absorbs heat faster than it can shed it - the screen dims or a temperature warning appears. This is the phone protecting itself; shade and a pause fix it. <b>2. Charging while working hard.</b> Charging makes heat; gaming or navigating while charging makes more. Fast charging adds its share. The fix is order of operations, not a cooler: finish the charge, then play. <b>3. A thick case in a hot spell.</b> The phone sheds heat through its body; an insulating case turns a warm day into a hot phone. Case off for an hour in shade is a legitimate fix. <b>4. Background churn.</b> A misbehaving app, a stuck sync or malware-class behaviour keeps the chip busy at idle - if the phone is hot in your pocket doing nothing, check battery stats for the app that never sleeps (<a href="/tech/android-battery-health/">battery health shows the culprit</a>).</p>
<h2>The fixes, in order</h2>
<p>Get it out of the sun and out of the case. Stop charging until it cools. Close the heavy app. Drop the workload - lower the game settings, stop the hotspot if nothing is using it, turn the screen brightness down. Never put a hot phone in a fridge: rapid cooling condenses water inside, and that trades a warm afternoon for a dead logic board. Room temperature and ten minutes is the honest cure.</p>
<h2>The stop-everything sign</h2>
<p>If the back of the phone looks raised, the screen lifts at its edges, or the case no longer sits flush: <b>stop using the phone and do not charge it.</b> Those are the signs of a swelling battery - a chemistry problem, not a settings problem, and pressing on a swollen cell is genuinely dangerous. The phone goes to a repair service or a battery replacement, not back in your pocket. Battery aging itself is normal and honest to check: <a href="/tech/android-battery-health/">how healthy the battery really is</a>.</p>
<p>Heat and speed are cousins - a phone that runs cooler lasts longer, and the same habits that keep it cool keep it quick: <a href="/tech/why-phones-slow-down/">why phones slow down</a>. And if the heat has already cost you a phone, let the next one cost you nothing: <a href="/tech/android-backup-guide/">the backup habit</a>.</p>""",
 [],
 [("android-battery-health", "Battery health, honestly"), ("why-phones-slow-down", "Why phones slow down"), ("phone-died-no-backup", "Phone died, no backup")]),
("use-less-mobile-data", "android", "guide",
"Use less mobile data: the settings that quietly halve the bill",
 "Wi-Fi-only updates, video quality defaults, hotspot guards and offline habits - the honest data diet, no lunchmeat apps required.",
"""<p>Mobile data is the rare utility you can halve from a settings screen. The trick is not willpower - it is making the big eaters ask before they eat. Here is the whole diet, ordered by how much data each setting actually saves. Figures below are the usual rough rates (standard-definition video around 0.7 GB an hour, high definition around 3 GB an hour, music roughly 50-150 MB an hour) - approximations, not quotations.</p>
<h2>The big three</h2>
<p><b>1. Video quality defaults.</b> Video is 60-90 per cent of most data bills. In each video app's settings, set playback over mobile data to standard definition - on a phone screen the difference is barely visible and the saving is enormous. Download over Wi-Fi before travel instead of streaming on the road. The full quality ladder and what each rung costs is on <a href="/tech/streaming-quality-settings/">streaming quality settings</a>. <b>2. Wi-Fi-only updates and backups.</b> App stores and backup services both default to doing their heavy lifting whenever they like; flip both to Wi-Fi-only and an overnight update storm stops eating a gigabyte on the morning commute. <b>3. The hotspot guard.</b> A phone hotspot is the single fastest way to burn a bundle - one connected laptop updates everything at once. Give it a password you actually choose, turn it off the second it is not in use, and treat connected devices as trusted guests with their own update settings.</p>
<h2>The quiet middle</h2>
<p><b>Data Saver mode</b> (Android's built-in) stops background apps from feeding when you are not looking - the single best set-and-forget switch. <b>Browser data saving</b> and staying off auto-play feeds trims the social hours, which run roughly 100-200 MB an hour. <b>Offline first:</b> maps downloaded on Wi-Fi, playlists synced, podcasts queued - anything that can be pre-fetched on cheap data should never touch the bundle.</p>
<h2>Watch the meter, not your nerves</h2>
<p>Every phone has a data-usage screen; set the billing-cycle date to match when your bundle resets and set a warning at half. The meter turns the diet from guesswork to arithmetic. When the bundle still runs dry anyway, the estimator does the maths with you: <a href="/tech/tool/data-usage-estimator/">the data usage estimator</a>. And when data itself refuses to work - the other half of this problem - that is the fix list on <a href="/tech/mobile-data-not-working/">mobile data not working</a>.</p>""",
 [],
 [("mobile-data-not-working", "Mobile data not working"), ("streaming-quality-settings", "Streaming quality settings"), ("public-wifi-risks", "Public Wi-Fi risks")]),
("earbuds-buying-checklist", "buying", "guide",
"The earbuds buying checklist: what actually matters before the price tag",
 "Fit, isolation, codecs, battery honesty and the call-mic test - the seven checks that decide whether earbuds earn their keep, in the order to check them.",
"""<p>Earbuds are the most-bought and least-researched gadget in tech, which is why so many drawers hold a pair that almost worked. The marketing sells features; the daily experience is decided by seven unglamorous checks. None of them is the brand name.</p>
<h2>The seven checks, in order</h2>
<p><b>1. Fit and isolation come before everything.</b> Two identical earbuds can sound opposite on two ears - a bad seal eats bass first, so the "weak sound" complaint is usually a tip-size problem. Multiple tip sizes in the box, or a fit style you have worn happily before: that is check one, and it outranks everything below. <b>2. Battery honesty.</b> The headline number is the case; the earbuds alone matter more - four to six hours per charge is the honest modern range, and anything under four makes long days into socket-hunting. Check the claimed hours for the buds, not the case. <b>3. Codecs: baseline is enough.</b> SBC and AAC (the defaults on Android and iPhone respectively) carry the overwhelming majority of real listening; LDAC and aptX are nice on paper and audible on fewer occasions than the spec sheet implies. Do not pay a premium for a codec your phone cannot use - the same logic as <a href="/tech/phone-buying-specs-that-matter/">buying phones by the specs that matter</a>.</p>
<p><b>4. Noise cancelling: know what you are buying.</b> Active noise cancelling hushes steady droning - planes, trains, fans - and does remarkably little against voices and sudden sounds. For commutes it is genuine; for an open office it is partial. Passive isolation from a good fit does half the work for free. <b>5. The call microphone.</b> Music you hear is half the product; your voice on calls is the other half and almost never demoed. Look for reviews that test calls in wind and street noise - this is where cheap buds fail first. <b>6. Latency, if you watch video.</b> Sound lagging the picture is the classic budget-bud failure; any modern pair with a low-latency mode or Bluetooth 5-era chip is fine. <b>7. IP rating, if they will sweat.</b> The rating means exactly what it says and nothing more: IPX4 handles rain and workouts; nothing consumer-grade is for swimming.</p>
<h2>Then, and only then, the price</h2>
<p>Decide your three non-negotiables from the seven, ignore the rest of the sheet, and buy the cheapest pair that clears your three - the price bands move every season, but the checklist does not. The same discipline scales to bigger purchases: <a href="/tech/laptop-buying-ram-storage/">laptops by RAM and storage</a>, <a href="/tech/monitor-buying-specs/">monitors by the specs that matter</a>, and the honest middle path of <a href="/tech/refurbished-vs-new-tech/">refurbished versus new</a>.</p>""",
 [],
 [("phone-buying-specs-that-matter", "Phone specs that matter"), ("refurbished-vs-new-tech", "Refurbished vs new"), ("laptop-buying-ram-storage", "Laptops by RAM and storage")]),
]
