# -*- coding: utf-8 -*-
"""Batch 9 of the 10/10 brief: Tier 2 #20, Repair vs Replace.

One article, eight-field tuple, same shape as batches 1-8:
(slug, category, kind, title, dek, body_html, sources, related)

Every figure in the body is traceable to one of the thirteen sources listed at
the bottom of this file, each of which was fetched and read on 16 September 2026.
"""

BODY = """<p>Something breaks and the question arrives already packaged: repair it or replace it? The packaged version is the problem. It assumes both options are available, that they cost what they say they cost, and that the answer is the same in Lagos as in Los Angeles. None of those hold. Whether a repair is even purchasable is a matter of law and of a manufacturer's published parts window, and those two clocks disagree with each other more often than people expect.</p>

<p>This piece works from documents rather than from rules of thumb. The prices quoted are the ones Apple and Samsung publish on their own support pages, read on 16 September 2026. The windows quoted are the ones written into EU regulations, a UK statutory instrument, a French ministry page, a California regulator's advisory and Apple's own service policy. Where a number is a company's estimate rather than a law, it is labelled as such.</p>

<h2>The short answer: five checks, in the order that saves money</h2>

<p>The order matters more than the checks. Most people start at the price, which is the fourth question, and get talked into a repair that was never available to them or a replacement that a plan they already pay for would have covered.</p>

<div class="compare-scroll"><table class="compare-table"><caption class="sr-only">The five checks that decide repair versus replace, in the order to ask them, with the document that answers each one</caption>
<thead><tr><th>Check</th><th>The question</th><th>Where the answer is written down</th><th>What it decides</th></tr></thead>
<tbody>
<tr><td><strong>1. Guarantee window</strong></td><td>Is the failure inside a warranty or legal guarantee that already obliges somebody to fix it?</td><td>Apple's Limited Warranty runs one year from purchase and expressly does not cover accidental damage or batteries that wear down from normal use. In Nigeria, section 132(2) of the Federal Competition and Consumer Protection Act 2018 gives three months from delivery. In the EU the legal guarantee is two years, and from 31 July 2026 choosing repair as the remedy extends the liability period by twelve months.</td><td>Whether you have a decision at all. Inside the window, repair is not a purchase.</td></tr>
<tr><td><strong>2. Parts window</strong></td><td>Can the part still be ordered, and by whom — you, a shop, or only a registered professional?</td><td>Apple: a minimum of five years from when it last distributed the model, up to seven subject to availability, and nothing at all past seven. EU Regulation 2019/2023: ten years for washing-machine parts. UK SI 2021/745 Schedule 19: seven years for display parts. California SB 244: three years for goods wholesaling $50–$99.99, seven for $100 and up.</td><td>Whether repair is physically purchasable, and whether you are allowed to be the one buying it.</td></tr>
<tr><td><strong>3. Shape of the failure</strong></td><td>Is one component dead, or is the machine dying?</td><td>Samsung's self-repair guidance tells owners not to attempt a repair at all if they identify a safety issue, and warns that residual voltage inside certain printed circuit board assemblies can cause electric shock. Apple prices a single screen at $379 and "other damage" on the same model at $899 — the gap between one component and several.</td><td>Whether a quote is a price, or an opening bid.</td></tr>
<tr><td><strong>4. Price ratio</strong></td><td>What does the repair cost against a replacement that arrives with its own full parts window?</td><td>Apple's published estimates, per model, as rendered on 16 September 2026. France's reparability index scores a product partly on the ratio between spare-part prices and the product's own price, which is the same comparison formalised at the point of sale.</td><td>Whether the repair is an investment, or a down payment on the next failure.</td></tr>
<tr><td><strong>5. Who has already paid</strong></td><td>Is a plan, a service contract or an insurance policy already on the hook for this?</td><td>AppleCare+ turns the same model's $129 battery service into $0 and its $379 screen into $29. Samsung Care+ exists for the same reason. A home warranty contract pays for a trade service call fee and then applies its own per-item caps.</td><td>Whether the decision is yours to make, and whether you are paying twice for cover you already bought.</td></tr>
</tbody></table></div>

<p>Two of those five are legal facts and two are commercial ones, and mixing them up is the most common expensive mistake. A closed parts window is not a high quote — no quote can fix it. A high quote is not a closed window — the part may still be orderable by a professional even when it is not orderable by you.</p>

<h2>Two questions wearing one phrase</h2>

<p>"Repair or replace" collapses three separate decisions into one, and each has a different answer.</p>

<h3>The first: fix this object, or buy another object</h3>

<p>This is the question people mean. It is answered by checks one, two and four: is someone obliged to fix it, can the part be bought, and what does it cost against a replacement that starts its own clock. The uncomfortable part is the second half of that comparison. A replacement is not a fixed price; it is a fixed price plus a new five-to-ten-year parts window, a fresh guarantee and, for anything with a battery, a battery that has not yet spent its cycles. A repaired object keeps its remaining window, which may be shorter than the repair's own warranty.</p>

<p>Apple makes the asymmetry explicit in a sentence most people scroll past. Its warranty, it says, does not cover accidental damage or batteries that wear down from normal use, and if your issue is ineligible for service, you may need to pay the full value for a replacement device. Ineligible is a category, not a price: the same device that would cost $129 to fix can cost its full replacement value if the fault falls outside what the company will service.</p>

<h3>The second: do it yourself, or pay someone</h3>

<p>Self-repair is a real option now, and it is a different calculation with a different risk. Samsung states plainly that its Limited Warranty is not impacted by Self-Repair — but that if the self-repair attempt is the cause of damage, any subsequent repair may not be covered. In the same page's legal disclosures it goes further: it is not liable for damage caused by repair from a non-authorised provider, self-repair or non-professional repair, and any damage resulting from such an attempt will not be covered by the warranty. Both statements are true at once, and reading only the first one is how people end up with a £900 phone and a £40 part.</p>

<p>Samsung also sells its genuine parts with a 90-day limited warranty from the date of delivery, distributed through Encompass and through an iFixit collaboration, and notes that by using or retaining parts you accept its terms including an arbitration agreement. Apple guarantees its own service and replacement parts for 90 days or the remaining term of your warranty, whichever is longer. So the labour warranty on a self-repair and the labour warranty on a manufacturer repair are the same length — ninety days — while the exposure is not.</p>

<h3>The third: the leg nobody prices</h3>

<p>A repaired device can still be sold. A replaced one usually means the old one is sold, kept as a spare, or becomes waste, and those three outcomes have wildly different values. Nothing in this article can tell you what your specific device is worth second-hand, because that market moves weekly and varies by country; what the sources do tell you is that the repair itself may not have used new parts. Apple states that equipment it provides as part of a repair or replacement service may contain new or previously used genuine Apple parts that have been tested and pass its functional requirements. If the manufacturer's own repair may install a previously used component, the folk objection that "it won't be the same as new" applies to the authorised repair too.</p>

<h2>What the law now guarantees about parts</h2>

<p>This is the section that changed most recently, and the change is already in force. Directive (EU) 2024/1799 on common rules promoting the repair of goods was adopted on 13 June 2024, published in the Official Journal on 10 July 2024, and gave member states until <strong>31 July 2026</strong> to transpose and apply it. That date passed six weeks ago. The directive amends Regulation (EU) 2017/2394 and Directives (EU) 2019/771 and (EU) 2020/1828, and EUR-Lex now shows a consolidated version dated 31 July 2026.</p>

<p>What it does, in the parts that matter to a person holding a broken object: manufacturers of goods covered by the EU acts listed in its Annex II must repair them, may sub-contract the work, and have no obligation only where repair is impossible. Manufacturers that make spare parts and tools available must offer them at a reasonable price that does not deter repair. They must not use contractual clauses, or hardware or software techniques, that impede repair, unless justified by legitimate and objective factors including the protection of intellectual property. Article 6 requires the information to be provided free of charge, including a standardised repair information form before the consumer is bound by a repair contract. And because it amends the Sale of Goods Directive, choosing repair as the remedy extends the seller's liability period by twelve months.</p>

<p>It is a directive, not a regulation, so the operative text a consumer or repairer actually invokes is one of twenty-seven national laws. The product scope and the twelve-month extension are EU-wide; penalties and procedures are not.</p>

<p>Beneath the directive sit the older ecodesign regulations that set the concrete parts lists, and these are where the specific numbers come from. Commission Regulation (EU) 2019/2023 requires manufacturers, importers or authorised representatives of household washing machines and washer-dryers to make available to professional repairers, for a minimum of <strong>ten years</strong> after placing the last unit of the model on the market, the motor and motor brushes, the transmission between motor and drum, pumps, shock absorbers and springs, the washing drum, drum spider and related ball bearings, heaters and heating elements including heat pumps, piping and related equipment including hoses, valves, filters and aquastops, printed circuit boards, electronic displays, pressure switches, thermostats and sensors, and — worth pausing on — software and firmware including reset software. A shorter list is available to professional repairers <em>and</em> end users for the same ten years: the door, door hinge and seals, other seals, the door locking assembly and plastic peripherals such as detergent dispensers. The regulation also requires that these parts be replaceable with the use of commonly available tools and without permanent damage to the machine, and that delivery happen within fifteen working days of an order.</p>

<p>The UK kept equivalent requirements after leaving the EU. The Ecodesign for Energy-Related Products and Energy Information Regulations 2021 — SI 2021/745, which the House of Commons Library notes was made on 18 June 2021 with most provisions in force on 1 July 2021 — set them out product by product. Schedule 19, covering electronic displays, requires manufacturers, authorised representatives or importers to make available to professional repairers, for a minimum of <strong>seven years</strong> after placing the last unit of the model on the market, the internal power supply, connectors for external equipment including cable, antenna, USB, DVD and Blu-ray, capacitors above 400 microfarads together with batteries and accumulators, and where applicable the DVD or Blu-ray module and the hard drive or solid state drive module. External power supplies and remote controls must be available to professional repairers <em>and</em> end users. And no later than two years after the first unit of a model is placed on the market, the parts list and the ordering procedure must be published on a website accessible to the public without charge, and kept accessible for as long as the parts remain available. The Commons Library briefing records that manufacturers had a grace period of up to two years to make spare parts available.</p>

<p>France went a different route and put the comparison on the shelf-edge label. The indice de réparabilité, instituted by article 16-I of loi n° 2020-105 du 10 février 2020 and deployed since 1 January 2021, is a score out of ten calculated from five criteria: the documentation a producer commits to making available free of charge and for how many years; disassembly, access, tools and fixings; the availability of spare parts, scored on the producer's commitment to duration and delivery delay; the price of spare parts, scored as a ratio to the price of the product; and category-specific sub-criteria. As of the ministry page's July 2025 update it covers five categories — laptops, lawn mowers, dishwashers, vacuum cleaners and high-pressure cleaners — and is being replaced category by category by an indice de durabilité, which took over for televisions on 8 January 2025 and for front- and top-loading washing machines on 8 April 2025, adding criteria including the product's reliability over time. The ministry's own impact assessment, run by the CGDD and the DITP, found the index had shifted purchasing practice towards more repairable products.</p>

<p>The United States has no federal equivalent. It has states. California's SB 244, the Right to Repair Act, took effect on 1 July 2024, and the Bureau of Household Goods and Services published an industry advisory on 15 June 2024 explaining it. A product is covered when it was manufactured on or after 1 July 2021, sold or used in California on or after 1 July 2021, cost $50 or more wholesale, and falls within the definitions of electronic set, appliance, antenna or rotator in section 9801 of the Business and Professions Code. Manufacturers must make documentation, parts and tools available to owners, service and repair facilities and service dealers — and must provide them <em>even if no warranty was made</em>. The window depends on wholesale cost: at least three years after the last manufacturing date for goods wholesaling between $50 and $99.99, and at least seven years for goods wholesaling at $100 or more. "Fair and reasonable terms" means costs and terms equal to the most favourable the manufacturer offers an authorised repair provider; documentation must be free; tools must be free, with no barriers to access or use. Video game consoles, alarm systems, fire protection systems and agricultural, construction, industrial and outdoor power equipment are excluded, and a manufacturer escapes the obligation entirely if it provides, at no charge, a replacement product that is equivalent or better and readily available.</p>

<p>Nigeria has no right-to-repair statute, and it is important not to imply one. What exists is a consumer remedy and an environmental regime. Under section 132(2) of the Federal Competition and Consumer Protection Act 2018, as the Federal Competition and Consumer Protection Commission explained publicly in June 2022, a consumer may return goods that do not meet the required standards to the undertaking that supplied them within <strong>three months</strong> of delivery, and that undertaking shall repair or replace the failed, unsafe or defective goods or refund the price paid. The choice of remedy sits with the consumer, and the obligation sits with the seller rather than the manufacturer — which matters, because many shops will point a buyer at a manufacturer's service centre instead. Separately, the National Environmental Standards and Regulations Enforcement Agency, established in 2007, has governed electrical and electronic waste through the National Environmental (Electrical/Electronic Sector) Regulations approved in 2011, an environmental instrument covering imports of new and used equipment rather than a repair-access right.</p>

<div class="compare-scroll"><table class="compare-table"><caption class="sr-only">Parts and repair obligations by jurisdiction, with the window, who may buy the part, and the primary source</caption>
<thead><tr><th>Jurisdiction</th><th>What is guaranteed</th><th>Window</th><th>Who can get the part</th></tr></thead>
<tbody>
<tr><td><strong>European Union</strong></td><td>Directive (EU) 2024/1799: an obligation on manufacturers to repair Annex II goods, spare parts and tools at a reasonable price that does not deter repair, no contractual or hardware or software techniques that impede repair, free information including a standardised repair form, and a twelve-month extension of the liability period when repair is chosen</td><td>Applies from 31 July 2026, through 27 national laws</td><td>Consumers and independent repairers</td></tr>
<tr><td><strong>EU — appliances</strong></td><td>Regulation (EU) 2019/2023: named washing-machine and washer-dryer parts, replaceable with commonly available tools and without permanent damage, delivered within fifteen working days</td><td>Ten years after the last unit of the model is placed on the market</td><td>The long list: professional repairers. Doors, hinges, seals, locking assemblies and detergent dispensers: repairers and end users</td></tr>
<tr><td><strong>United Kingdom</strong></td><td>SI 2021/745 Schedule 19: named display parts, plus a free public parts list and ordering procedure published within two years of a model's first unit</td><td>Seven years after the last unit of the model is placed on the market</td><td>Internal power supplies, connectors, capacitors and drive modules: professional repairers. External power supply and remote control: repairers and end users</td></tr>
<tr><td><strong>France</strong></td><td>Reparability index out of ten at the point of sale, scored partly on spare-part price as a ratio to product price; being replaced by a durability index category by category</td><td>Since 1 January 2021; durability index for TVs from 8 January 2025 and washing machines from 8 April 2025</td><td>Information is public; the index does not itself compel a sale</td></tr>
<tr><td><strong>California</strong></td><td>SB 244: parts, tools and documentation on fair and reasonable terms, documentation and tools free, required even where no warranty was made</td><td>Three years (wholesale $50–$99.99) or seven years ($100 and up) after the last manufacturing date</td><td>Owners, service and repair facilities, and service dealers</td></tr>
<tr><td><strong>Nigeria</strong></td><td>No repair-access statute. FCCPA 2018 s.132(2): repair, replacement or refund of goods that fail required standards, at the consumer's election</td><td>Three months from delivery</td><td>The remedy runs against the seller, not the manufacturer</td></tr>
</tbody></table></div>

<p>Read across that table and one thing stands out: the clocks do not start at the same event. The EU and UK windows run from when the last unit of a model is placed on the market. California's runs from the last manufacturing date. Apple's runs from when it last distributed the product for sale. France's Apple-specific commitment runs from when the model was last supplied for distribution in France. If you bought a machine in the last year of its production run, every one of those clocks had already been running for years before you unpacked it.</p>

<h2>The service cliff, by age</h2>

<p>Manufacturers publish these windows too, and Apple's are unusually specific. Owners of iPhone, iPad, iPod, Mac, Apple TV, Apple Watch, AirPods, Apple Vision Pro and Beats products may obtain service and parts from Apple service providers for a minimum of five years from when Apple last distributed the product for sale, and for longer where the law requires it or up to seven years, subject to parts availability. Products are vintage when Apple stopped distributing them more than five and less than seven years ago. They are obsolete when it stopped distributing them more than seven years ago — and for obsolete products Apple discontinues all hardware service and service providers cannot order parts.</p>

<div class="compare-scroll"><table class="compare-table"><caption class="sr-only">Apple's published service and parts availability by product age, from its own support pages</caption>
<thead><tr><th>Time since Apple last distributed the model</th><th>Apple's classification</th><th>What you can get</th><th>What changes the answer</th></tr></thead>
<tbody>
<tr><td><strong>Under one year</strong></td><td>Covered</td><td>Repair or replacement of manufacturing defects under the Apple Limited Warranty</td><td>Accidental damage and batteries worn from normal use are excluded; an AppleCare plan re-prices the same services</td></tr>
<tr><td><strong>Up to five years</strong></td><td>Current</td><td>Service and parts — the published minimum, from Apple or from its network of more than 5,000 certified repair locations</td><td>Parts availability and location still vary; Apple says service options may vary on both counts</td></tr>
<tr><td><strong>More than five, fewer than seven years</strong></td><td>Vintage</td><td>Service and parts may be obtained, subject to parts availability</td><td>"May" is the operative word. Up to seven years where the law requires it</td></tr>
<tr><td><strong>More than seven years</strong></td><td>Obsolete</td><td>Nothing. All hardware service is discontinued and service providers cannot order parts</td><td>Mac laptops may still be eligible for battery-only repair for up to ten years, subject to parts availability</td></tr>
<tr><td><strong>Bought in France</strong></td><td>Statutory override</td><td>Service and parts for seven years from when the model was last supplied by Apple for distribution in France</td><td>New iPhones and Mac laptops bought after 31 December 2020; new iPads bought after 24 June 2024</td></tr>
</tbody></table></div>

<p>That last row is the whole argument for jurisdiction-specific answers in one line. The same object, bought in the same year, has a different guaranteed service life depending on which country's law the sale fell under — and Apple publishes the difference itself rather than leaving a consumer to discover it.</p>

<p>The cliff is not hypothetical. Apple's current list of vintage Mac laptops includes the MacBook Air (Retina, 13-inch, 2019) and the 2020 model, the MacBook Pro (13-inch, 2019) in both two- and four-port forms, the MacBook Pro (15-inch, 2019), the MacBook Pro (Retina, 15-inch, Mid 2015) and the MacBook (Retina, 12-inch, 2017). A 2019 MacBook Air is therefore inside the window where service and parts "may be obtained" — and a 2017 model of the same line is on the far side of it, except for its battery.</p>

<h2>The published prices, and what they are prices for</h2>

<p>Apple no longer publishes a per-model price table; it publishes an estimator, and the estimator needs a model before it will say anything. Read on 16 September 2026 with an iPhone 18 Pro Max selected, it returned these out-of-warranty estimates: battery service $129, back glass damage $159, rear camera damage $249, screen damage $379, screen and back glass damage $469, and other damage $899. Select the AppleCare tab for the same model and the numbers become $0 for battery service, $29 for screen damage, $29 for back glass damage, $99 for other accidental damage and $149 for theft or loss.</p>

<p>Three caveats are printed on that page and all three matter. Apple will inspect the device to determine the final fee. The estimates are for out-of-warranty service from Apple and may be subject to tax, and a shipping fee may be added if Apple needs to ship the device. Apple Authorized Service Providers can set their own service fees and provide their own estimate — so the number on Apple's page is not necessarily the number at the counter, and an independent shop is not bound by it either way.</p>

<p>The ratio between those two columns is the most useful single number on the page, and it is not a ratio a consumer chooses: $379 becomes $29 only if the plan was bought before the screen broke. That is check five, and it is why it belongs in the list at all — the difference between a $379 repair and a $29 repair is a decision made months earlier, not one available now.</p>

<p>The spread between $129 and $899 on one device is the same object's answer to check three. Battery service is a single component with a known part. "Other damage" is a category, and Apple's own wording says the device must be inspected before a final fee exists. If a quote comes back as "other damage", it is not a price yet; it is an invitation to authorise an investigation.</p>

<h2>Will a repair void the warranty?</h2>

<p>In the United States, mostly no — and the reason is a statute rather than a manufacturer's goodwill. The Federal Trade Commission's own consumer guidance on warranties, updated on 9 December 2025, makes two points that decide this. A service contract is not a warranty, so the two should not be conflated when comparing what cover you already have. And under the Magnuson-Moss Warranty Act a manufacturer cannot require you to use specific parts or specific services in order to keep a warranty valid, unless it provides those parts or services free of charge or the FTC has waived the requirement.</p>

<p>That is a narrower protection than it sounds, and Samsung's page shows exactly where the edge is. Self-repair does not impact the Limited Warranty. Damage caused by the attempt may not be covered. And in the legal disclosures, damage or defect determined to be caused by repair from a non-authorised provider, self-repair or non-professional repair is not covered at all, with Samsung disclaiming liability for resulting damage to the product, to a person or to property. The distinction that survives scrutiny is between <em>choosing</em> an independent repairer, which a warranty cannot lawfully punish in the US, and <em>breaking something while doing it</em>, which no warranty covers.</p>

<p>The EU has now written the other side of that distinction into law. Directive (EU) 2024/1799 prohibits contractual clauses and hardware or software techniques that impede repair unless they are justified by legitimate and objective factors, including intellectual property protection. That is aimed at the practices that make an otherwise-available part useless — the software check that refuses a third-party component, the fastener that requires a tool the manufacturer will not sell, the clause that voids cover for opening a case. Whether any given national transposition reaches a specific device is a question for that country's statute, and it is a question worth asking before paying for a repair rather than after.</p>

<h2>Ten failures, ten answers</h2>

<p>The same framework applied to the failures people actually search for. Every row cites the document that decides it rather than a general opinion about appliances.</p>

<div class="compare-scroll"><table class="compare-table"><caption class="sr-only">Ten common failures assessed against the primary sources: what each document says and which way the decision falls</caption>
<thead><tr><th>The failure</th><th>What the sources say</th><th>Which way it falls</th></tr></thead>
<tbody>
<tr><td><strong>Cracked phone screen, device three years old</strong></td><td>Apple's estimator quoted $379 for screen damage on one model and $29 for the same service under an AppleCare plan. The device is inside Apple's five-year minimum service window.</td><td>Repair, and check first whether a plan you already hold re-prices it</td></tr>
<tr><td><strong>Battery that will not hold a charge</strong></td><td>Apple's Limited Warranty excludes batteries that wear down from normal use, so this is a paid service; the estimator quoted $129 on one model, and $0 under AppleCare+. Mac laptops may be eligible for battery-only repair for up to ten years.</td><td>Repair — the cheapest single-component fix on the page, and the one with the longest published window</td></tr>
<tr><td><strong>Swollen battery, or any smell, heat or deformation</strong></td><td>Samsung's guidance says not to attempt a Self-Repair if you identify a safety issue, and warns that residual voltage in certain printed circuit board assemblies can cause electric shock.</td><td>Neither, at home. Pay a certified repairer or replace; the cost comparison is not the relevant question</td></tr>
<tr><td><strong>Washing machine drum bearings</strong></td><td>Regulation (EU) 2019/2023 requires the washing drum, drum spider and related ball bearings to be available to professional repairers for at least ten years after the last unit of the model is placed on the market, delivered within fifteen working days, replaceable with commonly available tools and without permanent damage.</td><td>Repair, through a professional — that specific part is on the repairer-only list, not the end-user list</td></tr>
<tr><td><strong>Television that will not power on</strong></td><td>UK SI 2021/745 Schedule 19 puts the internal power supply on the seven-year professional-repairer list and the external power supply on the list available to end users as well.</td><td>Check the cheap one first: an external supply is a part you are entitled to buy yourself</td></tr>
<tr><td><strong>Phone more than seven years past its last distribution</strong></td><td>Apple classifies it as obsolete, discontinues all hardware service for it, and states that service providers cannot order parts for it.</td><td>Replace. This is a closed window, not a high quote</td></tr>
<tr><td><strong>Nine-year-old MacBook with a dead battery</strong></td><td>Obsolete in general — but Mac laptops may be eligible for an extended battery-only repair period for up to ten years from when the product was last distributed for sale, subject to parts availability.</td><td>Repair, if the part is available; it is the one exception Apple publishes</td></tr>
<tr><td><strong>Laptop bought in Lagos that failed in week six</strong></td><td>FCCPA 2018 s.132(2): the consumer may return goods that do not meet the required standards within three months of delivery, and the supplier shall repair or replace them or refund the price paid — at the consumer's election, against the seller.</td><td>Neither, at your cost. The remedy is statutory and it is the shop's, not the service centre's</td></tr>
<tr><td><strong>Appliance that fails inside the EU legal guarantee</strong></td><td>The guarantee runs two years, and from 31 July 2026 choosing repair as the remedy extends the liability period by twelve months under the amended Sale of Goods Directive.</td><td>Repair — and the extension is a reason to choose it over replacement</td></tr>
<tr><td><strong>Appliance covered by a home warranty contract</strong></td><td>The contract's own terms decide: a trade service call fee per request, then per-item caps, and in the AHS specimen contract a clause under which a repair that would exceed the cap is settled at the cap minus the diagnostic cost.</td><td>Whichever the contract chooses. You are buying a decision procedure, not a repair</td></tr>
</tbody></table></div>

<h2>How to get a quote that means something</h2>

<p>A quote is only comparable if it answers the same questions as the next quote. These come straight out of what the documents require.</p>

<ul>
<li><strong>Ask for the failed part by name.</strong> "Other damage" is Apple's own catch-all and it spans $899 against a $129 battery on the same model. A named part is a price; a symptom is a range.</li>
<li><strong>Ask whether the price includes diagnosis.</strong> California's SB 244 requires documentation to be provided free of charge, which is why an independent shop's diagnostic fee is a labour charge and not an information charge — and why it should be separable from the repair.</li>
<li><strong>Ask whether the part is new, refurbished or previously used.</strong> Apple states that its repair and replacement equipment may contain new or previously used genuine parts that have been tested and pass its functional requirements. Samsung warrants its genuine self-repair parts for ninety days from delivery. Those are different answers and both are legitimate; you should know which one you are buying.</li>
<li><strong>Ask how long the repair itself is warranted.</strong> Apple guarantees its service and replacement parts for ninety days or the remaining term of your warranty, whichever is longer. Samsung's self-repair parts carry a ninety-day limited warranty. Anything shorter than ninety days is below what both manufacturers publish.</li>
<li><strong>Ask for the delivery window in writing.</strong> Regulation (EU) 2019/2023 sets a maximum of fifteen working days for washing-machine spare parts. A quote that cannot name a date is a quote for a machine that stays broken.</li>
<li><strong>Ask whether you are allowed to buy the part yourself.</strong> The EU and UK rules both split their parts lists into repairer-only and repairer-plus-end-user. In the UK, external power supplies and remote controls for displays are on the end-user list; internal power supplies are not.</li>
<li><strong>Find the model's last manufacturing or last distribution date.</strong> Every window above runs from one of those, not from your purchase date. A model discontinued three years ago has three years less cover than it looks like it has.</li>
<li><strong>In France, read the score before you buy.</strong> The index scores spare-part price as a ratio to product price, which is the repair-versus-replace calculation done for you at the shelf, and the durability index that is replacing it adds reliability. The government also runs a directory of repair professionals at longuevieauxobjets.gouv.fr.</li>
<li><strong>In Nigeria, write to the seller first.</strong> The three-month clock in FCCPA s.132(2) runs from delivery and the obligation sits with the undertaking that supplied the goods. A manufacturer's service centre is not the counterparty, and treating it as one can run the window down.</li>
</ul>

<h2>The e-waste ledger, kept separate from yours</h2>

<p>There is a second set of numbers that get attached to this decision, and they deserve to be handled carefully, because they are real and they are not about your device.</p>

<p>The fourth Global E-waste Monitor, published by ITU and UNITAR on 20 March 2024, reports a record 62 million tonnes of e-waste generated in 2022, up 82 per cent from 2010, rising by 2.6 million tonnes a year and on track to reach 82 million tonnes by 2030. Only 22.3 per cent of the 2022 mass was documented as properly collected and recycled, leaving some US $62 billion of recoverable resources unaccounted for, and the report projects that rate falling to 20 per cent by 2030 — because generation is growing faster than recycling, not because recycling is shrinking. Among the causes it names are limited repair options and shorter product life cycles. Small IT and telecommunication equipment — laptops, phones, routers — accounted for 4.6 million tonnes with a documented collection rate of just 22 per cent. Fewer than one per cent of documented collection and recycling happens in African countries, and of the 5.1 million tonnes shipped across borders in 2022, roughly 3.3 million tonnes moved from high-income to middle- and low-income countries through uncontrolled, undocumented movements. The report's own conclusion is that reaching 60 per cent by 2030 would deliver benefits exceeding costs by more than US $38 billion, and its lead author's call includes more promotion of repair and reuse.</p>

<p>Two honest limits on what those figures can do for you. First, they are system-level: nothing in them establishes that repairing your specific washing machine is cheaper than replacing it, and using them as though they do is how a cost decision gets dressed up as a moral one. Second, they describe documented flows. The 22.3 per cent is what was recorded as formally collected and recycled, which is not the same statement as "77.7 per cent was dumped" — some of the remainder is repaired, reused, stored in drawers or handled informally, and the report is explicit that informal handling carries health and environmental costs that may offset the material value recovered.</p>

<p>What the ledger does support is narrower and more useful: repair is a policy objective with measurable targets attached to it, in the EU, the UK, France, California and at the UN, and the reason those targets exist is that collection rates are falling behind generation. That is a reason to expect the parts windows to keep lengthening rather than shortening. It is not a reason to pay more than a replacement for a repair.</p>

<h2>One tool that earns its place here</h2>

<p>Every window in this article is a date, and dates are where these decisions actually go wrong — the guarantee expires on a day, not in a season. Receipts, order confirmations and warranty-registration emails routinely carry a machine timestamp rather than a readable date. Paste it into the <a href="/tech/tool/timestamp-converter/">timestamp converter</a> and you get the delivery date, which is the event the Nigerian three-month clock and the EU two-year guarantee both run from, and from which you can work out the day each window closes.</p>

<p>The other half of the arithmetic needs no tool at all: a repair quote divided by the price of a replacement that arrives with its own full parts window. What does deserve a look before you pay anything is whether you are already paying for the answer. An AppleCare or Samsung Care plan is a subscription, and the <a href="/tech/subscription-creep-audit/">subscription audit</a> applies unchanged — the estimator's $379 becoming $29 is worth nothing if the plan lapsed unnoticed, and worth a great deal if it did not. The <a href="/tech/home-insurance-vs-home-warranty/">home insurance versus home warranty</a> piece covers the appliance side of the same question, where a contract's caps rather than a repair quote decide whether the machine gets fixed or replaced. And when the answer is replace, <a href="/tech/refurbished-vs-new-tech/">refurbished versus new</a> is the next decision, with <a href="/tech/android-battery-health/">battery health</a> and <a href="/tech/ssd-vs-hdd/">the storage question</a> settling which component is actually failing before anyone charges you for it.</p>

<h2>What this article does not claim</h2>

<p>No universal rule is offered, because none of the sources supports one. Specifically: there is no "fifty per cent rule" here — no regulator, manufacturer or statute in the material above publishes a cost-ratio threshold, and the numbers that do exist are parts windows, published service prices and guarantee periods, all of which vary by product and country. The Apple prices are one model's estimates from one estimator read on one date, 16 September 2026; Apple does not publish a per-model table, and its own page says the device must be inspected before a final fee, that tax and shipping may be added, and that Authorized Service Providers set their own fees. The EU obligation applies through twenty-seven national laws, so the enforceable text differs by member state and the penalties and procedures are national. The UK figures come from one schedule of one statutory instrument covering electronic displays; other schedules set other windows for other products. California's SB 244 has exemptions — game consoles, alarm and fire protection systems, agricultural and outdoor power equipment — and an escape clause where a free equivalent replacement is offered. France's index covers five categories as of the ministry's July 2025 update and is being replaced category by category. Nigeria's three-month remedy is a consumer-protection provision, not a repair-access right, and nothing here should be read as suggesting Nigeria has one. Where a source is a company describing its own service, that is what it is: a published commitment, not an independent measurement.</p>"""

SOURCES = [
    ("Apple — Obtaining service for your Apple product after an expired warranty (vintage and obsolete definitions, five-to-seven-year window, Mac laptop battery exception, France commitment)", "https://support.apple.com/en-us/102772"),
    ("Apple — Service and Repair for iPhone Battery (published out-of-warranty and AppleCare estimates, read 16 September 2026; Limited Warranty exclusions; 90-day service guarantee)", "https://support.apple.com/iphone/repair/battery-replacement"),
    ("Samsung US — Self-Repair (parts via Encompass and iFixit, 90-day parts warranty, warranty-impact FAQ, safety warnings, legal disclosures)", "https://www.samsung.com/us/support/self-repair/"),
    ("California Bureau of Household Goods and Services — Industry Advisory: The Right to Repair Act effective 1 July 2024 (SB 244), 15 June 2024", "https://bhgs.dca.ca.gov/forms_pubs/sb_244_industry_advisory_english.pdf"),
    ("EUR-Lex — Directive (EU) 2024/1799 of 13 June 2024 on common rules promoting the repair of goods (OJ L, 2024/1799, 10.7.2024; consolidated version 31 July 2026)", "https://eur-lex.europa.eu/eli/dir/2024/1799/oj"),
    ("EUR-Lex — Commission Regulation (EU) 2019/2023: ecodesign requirements for household washing machines and washer-dryers (ten-year spare parts lists, fifteen working days, commonly available tools)", "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32019R2023"),
    ("legislation.gov.uk — The Ecodesign for Energy-Related Products and Energy Information Regulations 2021 (SI 2021/745), Schedule 19: design for repair and reuse, availability of spare parts", "https://www.legislation.gov.uk/uksi/2021/745/schedule/19/crossheading/design-for-repair-and-reuse-availability-of-spare-parts/made"),
    ("House of Commons Library — Right to Repair Regulations, briefing CBP-9302 (SI 2021/745 made 18 June 2021, most provisions in force 1 July 2021, grace period up to two years)", "https://commonslibrary.parliament.uk/research-briefings/cbp-9302/"),
    ("Ministère de la Transition écologique — Indice de réparabilité (published 16 December 2024, updated 8 July 2025: five categories, five scoring criteria, transition to the indice de durabilité in 2025)", "https://www.ecologie.gouv.fr/politiques-publiques/indice-reparabilite"),
    ("UNITAR and ITU — Global e-Waste Monitor 2024 press release, 20 March 2024 (62 Mt in 2022, 22.3 per cent documented recycling, 82 Mt projected by 2030, cross-border flows)", "https://unitar.org/about/news-stories/press/global-e-waste-monitor-2024-electronic-waste-rising-five-times-faster-documented-e-waste-recycling"),
    ("US Federal Trade Commission — Warranties (updated 9 December 2025: service contracts are not warranties; Magnuson-Moss limits on requiring specific parts or services)", "https://consumer.ftc.gov/articles/warranties"),
    ("BusinessDay — FCCPC advises consumers to seek redress when sold defective goods, 30 June 2022 (the Commission's own statement of FCCPA 2018 s.132(2): three months from delivery, repair or replace or refund)", "https://businessday.ng/news/article/fccpc-advises-consumers-to-seek-redress-when-sold-defective-goods/"),
    ("APC / Global Information Society Watch — Nigeria country report (NESREA established 2007; National Environmental (Electrical/Electronic Sector) Regulations approved 2011 as the instrument governing electrical and electronic waste)", "https://giswatch.org/node/6237"),
]

RELATED = [
    ("home-insurance-vs-home-warranty", "Home insurance vs home warranty: the two contracts that cover opposite failures"),
    ("refurbished-vs-new-tech", "Refurbished vs new tech: what the discount is actually for"),
    ("subscription-creep-audit", "How to actually audit every subscription you're paying for"),
    ("android-battery-health", "Android battery health: what the number means"),
    ("ssd-vs-hdd", "SSD vs HDD: the storage decision, plainly"),
]

BATCH_1010_B9 = [
    (
        "repair-vs-replace",
        "buying",
        "guide",
        "Repair vs replace: the five checks, and the laws that changed the answer",
        "Whether a repair is even purchasable is a question of law and of a manufacturer's published parts window — and those two clocks start at different events. The order to ask the five questions, with the documents that answer each one.",
        BODY,
        SOURCES,
        RELATED,
    ),
]
