# -*- coding: utf-8 -*-
"""Tech master build M2 — the QuantLab pillar (7 first-hand pieces, Sept 2026).

Evidence base: Ojeology/QUANTLAB (public; branches main + blind-validation), inspected
2026-09-10 via GitHub API. Anchors: README.md (main, 48KB), EXIT_MODEL_AUDIT.md,
forex_f001-f009.py, quantlab_r005-r095.py, scripts/ql_engine.py, demo_bot.py,
bot_config.yaml, quantlab_output/research_journal.csv (per README layout),
blind-validation branch (T1-T34 campaign).

EDITORIAL RULES (binding, from docs/ecosystem/tech-master-build.md):
- The spec research disclaimer appears verbatim in every piece.
- No performance figures republished as achievements; where numbers are essential they are
  framed as historical backtest results that did not survive re-testing (the T34 story).
- No strategy recommendation, no signals, no go-live encouragement; the bot is paper-only
  and the pieces say so. Deriv appears only as the negative random-walk result.
- kind="firsthand" for all 7 (kicker: "First-hand · verified against the real thing");
  authorship label applied via _TECH_FIRSTHAND in build-ecosystem.py.
"""

TECH_MASTER_M2 = [

("quantlab-project-how-built", "quant", "firsthand",
"How I built a quantitative research lab in Python \u2014 one person, no Bloomberg terminal",
"QuantLab is a research framework for systematic trading strategies, built as one script per experiment with a shared walk-forward engine and a journal that forces honesty. The architecture, from the person who built it.",
"""<p>QuantLab started with an uncomfortable realization: it is trivially easy to write a backtest that prints beautiful numbers and means nothing. So instead of hunting strategies, the project was built backwards &mdash; the machinery of discipline first, the strategy hunt second. This is how the lab is actually put together. It is a first-hand project report, not a tutorial paraphrase.</p>
<h2>One script per experiment, forever</h2>
<p>The core convention: every research question gets its own numbered script &mdash; <code>quantlab_r001.py</code> through <code>quantlab_r095.py</code> for the crypto arc, <code>forex_f001.py</code> through <code>forex_f009.py</code> for forex. One script, one falsifiable question, one answer written to a journal. Ninety-five scripts sounds chaotic until you see what it buys: any experiment from months ago can be re-run byte-for-byte, and nothing was ever edited in place to make a bad result look better. Gaps in the numbering are honest too &mdash; abandoned runs stay abandoned.</p>
<h2>The shared engine</h2>
<p>Common work lives in one place: a shared backtest engine (<code>scripts/ql_engine.py</code>) that handles feature engineering, signal masking and the walk-forward simulation loop, so every experiment runs its data through the same pipe. That is where the discipline lives &mdash; the engine splits time so that training only ever sees the past, and the experiment scripts cannot quietly peek at the future because they never hold it. Data flows through parquet caches (exchange OHLCV for crypto, 1H/1D sources for forex), because a lab that re-downloads its data every run is a lab that stops experimenting.</p>
<h2>The journal is the product</h2>
<p>Every run writes its verdict to <code>quantlab_output/</code> &mdash; a final report, a journal entry, CSVs of trades, charts &mdash; and one machine-readable CSV indexes them all. The vocabulary is decision-forcing: a run ends as PROMOTE, WATCHLIST, REJECT, RETRACTED or OVERFIT. There is no &ldquo;interesting&rdquo;. The journal exists because memory is where backtesting goes to die; the moment you let yourself remember results instead of logging them, the flattering ones get remembered and the rest fade.</p>
<h2>What the stack actually is</h2>
<p>Deliberately boring: Python, pandas, NumPy, scikit-learn for the condition filters, matplotlib for the charts, SQLite and Telegram alerts for the paper-trading bot. No distributed anything, no proprietary data &mdash; exchange APIs and free sources, gated by the project's rule that an edge must survive realistic costs or it is not an edge. The whole lab runs on one machine. The barrier to doing this work was never the tooling; it was the honesty layer, which no library ships.</p>
<p>What came out of it &mdash; including the failures that turned out to be the most valuable findings &mdash; is in <a href="/tech/hundred-experiments-lessons/">the lessons from ~140 documented experiments</a>, and the single most instructive bug is its own story: <a href="/tech/lookahead-bias-explained/">the day the lab caught its own lookahead bias</a>.</p>
<p><em>Research note: QuantLab experiments are presented for educational and research purposes. Historical backtests and simulations do not guarantee future results and should not be interpreted as investment advice.</em></p>""",
[("Ojeology/QUANTLAB \u2014 the repository (README documents the layout, the arcs and the research logs)", "https://github.com/Ojeology/QUANTLAB"),
 ("QuantLab README \u2014 repository layout and validation framework", "https://github.com/Ojeology/QUANTLAB/blob/main/README.md")],
[]),

("hundred-experiments-lessons", "quant", "firsthand",
"What ~140 documented trading experiments taught me (most of them failed)",
"Ninety-five crypto runs, nine forex runs, a strategy freeze, and a blind re-test campaign that overturned the freeze \u2014 the honest summary of a research project whose biggest findings are negative.",
"""<p>QuantLab has run roughly a hundred and forty documented experiments: 95 numbered crypto runs, 9 forex runs, and a post-freeze blind out-of-sample campaign numbered T1 through T34. Measured by the goal the project started with &mdash; find a robust trading edge &mdash; most of it failed. Measured by what it teaches, the failures are the yield. This is the summary the research journal writes by itself.</p>
<h2>The shape of the hunt</h2>
<p>The crypto arc (R001&ndash;R095) ran the full zoo: momentum and mean-reversion families, volatility-breakout variants, machine-learning condition filters, ensemble and portfolio constructions. The forex arc (F001&ndash;F009) tested whether anything transferred. Then the project did something unusual: on 2026-08-09 it declared a <strong>strategy freeze</strong> &mdash; no more tuning, the promising configs locked &mdash; and opened a separate branch to re-test the frozen conclusions <em>blind</em> on per-year out-of-sample data with costs, deliberately trying to break its own results.</p>
<h2>The negative results are the headline</h2>
<p><strong>Five-minute crypto has no cost-surviving edge</strong> &mdash; demonstrated seven independent ways in R089&ndash;R095. Not &ldquo;we didn't find one&rdquo;: proven, repeatedly, with different methods, that costs eat everything. <strong>A whole family of &ldquo;winning&rdquo; runs was retracted</strong> &mdash; the R066&ndash;R072 results looked excellent until an exit-model audit showed the measurement itself was flawed; they were re-registered as a proxy artifact. <strong>Most edges refused to travel</strong> &mdash; strategies that worked on some symbols failed on unseen ones (R044, R049, R078): they were descriptions of their training data, not edges. <strong>And the freeze itself failed</strong> &mdash; the locked configuration that survived in-sample scrutiny lost after costs on the strict per-year blind re-test, which forced a better, humbler final config. Deriv synthetics, tested for completeness, behaved like the random walk they are marketed as.</p>
<h2>What a hundred failures actually teach</h2>
<p>That the market's cost structure is a predator tuned to exactly the kind of edge an amateur finds. That a result you cannot re-derive blind is a rumor you told yourself. That discipline is a feature you build into the pipeline &mdash; journals, freezes, blind branches &mdash; because willpower is not a system. And that the promotion vocabulary matters as much as the tests: RETRACTED is a verdict the project has used on itself, in writing, and the log is better for it.</p>
<p>The flip side &mdash; what <em>did</em> survive, and how it was validated &mdash; is the <a href="/tech/backtest-validation-checklist/">validation gauntlet every result had to pass</a>. The single most educational incident, where a champion's logged profit quietly evaporated under a correct audit, is <a href="/tech/lookahead-bias-explained/">the lookahead-bias story</a>.</p>
<p><em>Research note: QuantLab experiments are presented for educational and research purposes. Historical backtests and simulations do not guarantee future results and should not be interpreted as investment advice.</em></p>""",
[("Ojeology/QUANTLAB \u2014 research logs R001\u2013R095, F001\u2013F009 and the freeze documentation", "https://github.com/Ojeology/QUANTLAB/blob/main/README.md"),
 ("The blind-validation branch \u2014 the post-freeze out-of-sample campaign (T1\u2013T34)", "https://github.com/Ojeology/QUANTLAB/tree/blind-validation")],
[]),

("lookahead-bias-explained", "quant", "firsthand",
"Lookahead bias: the bug that makes backtests lie \u2014 and how our own got caught",
"The classic backtest error, its everyday disguises, and the audit that found a champion strategy's numbers were reading the future \u2014 from the lab it happened to.",
"""<p>Lookahead bias is the backtest's native sin: any pathway by which information from the future leaks into a decision made in the past. The result is a simulation that could not have been traded, printing profits that were never available. Every backtesting practitioner knows the definition. QuantLab still shipped a case of it &mdash; caught by its own audit, months in, on its proudest result. This is the definitive explanation, from inside the incident.</p>
<h2>The everyday disguises</h2>
<p>The obvious version is trivial: deciding to buy at today's open using today's close. The dangerous versions wear suits. <strong>Normalization leakage:</strong> scaling features with a mean and deviation computed over the whole dataset, including the future. <strong>Selection leakage:</strong> choosing the strategy because it won on data you then &ldquo;validate&rdquo; on. <strong>The exit-anchor:</strong> computing a decision's features at the time the trade closes, while simulating it as if known at entry. That last one is the one that got us.</p>
<h2>The incident, plainly told</h2>
<p>The lab's trend strategy carried a machine-learning condition gate &mdash; a filter that decides whether a trade is worth taking. On paper the gated strategy was the campaign's champion: logged backtests around a $100 start simulating to roughly $199, profit factors comfortably above 1.3 across years. Then the T34 audit asked one hostile question: <em>at which bar are the gate's features actually computed?</em> Answer: the exit bar. The gate was reading the trade's outcome while &ldquo;deciding&rdquo; whether to take it &mdash; the future, piped politely into the past. Re-gated honestly at the entry bar, the same champion simulated to roughly $106 &mdash; a coin flip after costs. The entire premium was the bug. The numbers are framed here as what they now are: historical backtest results that did not survive re-testing.</p>
<h2>What the lab changed</h2>
<p>The audit that caught it (documented in the repo's exit-model audit) became mandatory: every promoted result gets a causal audit &mdash; prove, feature by feature, that each input is computable strictly before the decision it feeds. The deeper defenses are structural: point-in-time feature construction in the shared engine, gates anchored to the entry bar by construction, and a culture where re-deriving a result with an independent script is expected, not paranoid. The project had already retracted one result batch for a related measurement artifact; this audit exists because of it.</p>
<h2>The transferable lesson</h2>
<p>Lookahead bias is not a typo you make once; it is the default direction of every mistake when you write a simulator quickly, because the data is all sitting there in one frame and the future is the easiest column to reach. The cure is not caution &mdash; it is architecture and audit: one engine that makes leakage hard, and a standing rule that your best result is the one that gets the most hostile re-examination. The broader defense-in-depth is the <a href="/tech/backtest-validation-checklist/">full validation gauntlet</a>; the taxonomies of failure it guards against are in <a href="/tech/why-backtests-fail/">why backtests fail</a>.</p>
<p><em>Research note: QuantLab experiments are presented for educational and research purposes. Historical backtests and simulations do not guarantee future results and should not be interpreted as investment advice.</em></p>""",
[("Ojeology/QUANTLAB \u2014 EXIT_MODEL_AUDIT.md: the exit-engine correction that superseded R066\u2013R072", "https://github.com/Ojeology/QUANTLAB/blob/main/EXIT_MODEL_AUDIT.md"),
 ("The blind-validation branch \u2014 T34 entry-anchor audit documentation", "https://github.com/Ojeology/QUANTLAB/tree/blind-validation")],
[]),

("backtest-validation-checklist", "quant", "firsthand",
"The validation gauntlet: what a backtest must survive before you believe it",
"Walk-forward, untouched holdouts, cost gates, bootstrap intervals, Monte Carlo, leave-one-out: the checklist QuantLab applies to every result \u2014 and the promotion vocabulary that turns tests into decisions.",
"""<p>A single profitable backtest is not evidence; it is a hypothesis wearing a suit. QuantLab's answer was to build a gauntlet &mdash; a fixed sequence of tests every candidate must survive, with a vocabulary that forces a decision at the end. This is that gauntlet, written as the checklist it operates as. It is the single most transferable artifact of the whole project: none of it requires a trading account, and all of it applies anywhere a model meets data it has never seen.</p>
<h2>Before anything: the time discipline</h2>
<p><strong>Walk-forward optimization.</strong> Parameters are chosen using only data before the period being simulated, sliding forward through history &mdash; the simulator never trains on its own future. <strong>Untouched holdouts.</strong> Whole periods (calendar years, in the blind campaign) are sealed until the final verdict; a holdout you have peeked at is no longer a holdout. The lab's enforcement mechanism was structural: a separate branch, opened after a strategy freeze, whose only purpose was testing frozen conclusions on sealed years.</p>
<h2>The cost gate: where most edges die</h2>
<p>Every result is re-measured with realistic costs &mdash; exchange fees, spread, slippage; the lab's crypto runs used 0.05% per side, retail spreads plus swap on forex. The rule is absolute: <strong>an edge that dies at cost is not an edge</strong>. It is the single most lethal test in the gauntlet &mdash; the lab's five-minute-crypto hunt ended with seven independent demonstrations that nothing survives costs at that frequency.</p>
<h2>The statistical battery</h2>
<p><strong>Bootstrap confidence intervals</strong> on the profit factor (5th, 50th, 95th percentiles) &mdash; is the result stable when the trade sequence is resampled, or a lucky ordering? <strong>Monte Carlo simulation</strong> &mdash; P(profit) and the drawdown distribution over randomized paths, because the average path is not the one you live. <strong>Leave-one-out validation</strong> across symbols and folds &mdash; does the edge survive when any single market is removed, or was it one symbol wearing a costume? <strong>Monthly stability</strong> &mdash; what fraction of months are profitable, and how long is the worst losing streak? <strong>Regime and parameter analysis</strong> &mdash; does it hold across trending and ranging years, and how sharply does performance fall off when parameters move off the chosen value? A result that lives and dies by one parameter setting is curve-fit, not found.</p>
<h2>The vocabulary that ends every test</h2>
<p>Each run ends in exactly one verdict: <strong>PROMOTE</strong> (passed the gauntlet), <strong>WATCHLIST</strong> (promising, sample too thin to trust), <strong>REJECT</strong> (failed), <strong>RETRACTED</strong> (a previously promoted result withdrawn &mdash; used here, in writing, more than once), <strong>OVERFIT</strong> (performed, then refused to generalise). The vocabulary is the discipline: it prevents the third outcome most projects use, which is &ldquo;quietly stop mentioning it&rdquo;.</p>
<p>For the failures each test was built to catch, see <a href="/tech/why-backtests-fail/">the four ways a profitable backtest still loses money</a>; for the bug that prompted the mandatory causal audit at the top of this gauntlet, see <a href="/tech/lookahead-bias-explained/">the lookahead-bias story</a>. And the lab these ran inside is documented in <a href="/tech/quantlab-project-how-built/">how the research lab was built</a>.</p>
<p><em>Research note: QuantLab experiments are presented for educational and research purposes. Historical backtests and simulations do not guarantee future results and should not be interpreted as investment advice.</em></p>""",
[("Ojeology/QUANTLAB \u2014 the validation framework as documented in the README", "https://github.com/Ojeology/QUANTLAB/blob/main/README.md"),
 ("QuantLab shared walk-forward engine", "https://github.com/Ojeology/QUANTLAB/blob/main/scripts/ql_engine.py")],
[]),

("why-backtests-fail", "quant", "firsthand",
"Four ways a profitable backtest still loses money",
"Cost drag, measurement artifacts, universe-specificity and regime change \u2014 the four failure modes, each discovered the hard way inside one research project.",
"""<p>Every failed backtest fails for boring reasons wearing clever disguises. QuantLab's journal now holds enough failures to sort them into families, and the sorting is the useful part: each failure mode has a signature, a tell, and a defense. All four below were discovered inside this one project, on its own results, which is exactly why they are worth writing down.</p>
<h2>One: costs eat the edge</h2>
<p>The signature: superb results on high-frequency data that fade as fees are applied and collapse entirely with spread and slippage included. The lab's most complete demonstration: the five-minute crypto hunt, closed with seven independent lines of evidence that <strong>no cost-surviving edge existed at that frequency at all</strong> (R089&ndash;R095). The tell you are in danger: any backtest whose per-trade edge is smaller than a few times the round-trip cost. The defense: costs enter the simulation from the first prototype, never as a later &ldquo;realism&rdquo; pass; and a gate, not an afterthought &mdash; an edge must clear costs to even be discussed.</p>
<h2>Two: the measurement lies (proxy artifacts)</h2>
<p>The signature: results that are excellent, stable, reproducible &mdash; and wrong, because the simulator's bookkeeping flatters the strategy. The lab's retraction: an entire run family (R066&ndash;R072) was promoted on a backtest proxy that turned out to measure differently from tradeable reality; the exit-model audit withdrew the verdicts, and later found the same disease in the trend champion &mdash; a gate reading exit-bar features, quietly reading the future (the full story in <a href="/tech/lookahead-bias-explained/">the lookahead-bias piece</a>). The tell: results that survive every statistical test because the tests share the same flawed simulator. The defense: re-derive key results with an independent script, and audit every feature's timestamp against the decision it feeds.</p>
<h2>Three: the edge lives in one place</h2>
<p>The signature: a strategy shines on the symbols and periods it was developed on, and evaporates on unseen ones. The journal's examples are by name now: R044, R049, R078 &mdash; each an edge that refused to travel. This is universe-specificity, overfitting's most convincing costume, because the in-sample evidence is real; it is evidence about a place, not a rule. The defense is leave-one-out validation across symbols and folds, plus per-year gates &mdash; the blind campaign's strictest rule was that a result must hold year by year, not on average, because averages bury losing regimes.</p>
<h2>Four: the market changes under you</h2>
<p>The signature: a config that passes everything, then loses when the regime turns. The lab's freeze-and-blind protocol existed precisely to catch this &mdash; and it worked: the frozen configuration that looked like the project's crown jewel failed its strict per-year blind re-test after costs, and the honest full-universe audit showed the surviving champion carried a far deeper drawdown than its small-sample report had suggested. Drawdowns, in particular, are regime-shaped: a backtest that never touched a losing regime is not evidence of a small drawdown, it is evidence of a short memory. The defense: sealed holdout years, regime analysis, and treating the worst simulated path &mdash; not the average &mdash; as the planning number.</p>
<p>None of these four are exotic. All four were caught by the same infrastructure: <a href="/tech/backtest-validation-checklist/">the validation gauntlet</a>, running inside <a href="/tech/quantlab-project-how-built/">a lab built to make honesty cheap</a>. The pattern-level summary of what overfitting feels like from the inside is in <a href="/tech/overfitting-detection-guide/">the overfitting detection guide</a>.</p>
<p><em>Research note: QuantLab experiments are presented for educational and research purposes. Historical backtests and simulations do not guarantee future results and should not be interpreted as investment advice.</em></p>""",
[("Ojeology/QUANTLAB \u2014 research log and negative-results summary (main branch README)", "https://github.com/Ojeology/QUANTLAB/blob/main/README.md"),
 ("EXIT_MODEL_AUDIT.md \u2014 the measurement-artifact correction", "https://github.com/Ojeology/QUANTLAB/blob/main/EXIT_MODEL_AUDIT.md")],
[]),

("paper-trading-bot-lessons", "quant", "firsthand",
"Building the paper-trading bot: SQLite, Telegram, and why it never goes live",
"A paper-trading bot is where a validated strategy meets boring reality: scheduling, state, alerts, and an audit trail. How QuantLab's bot works \u2014 and why the project keeps it on paper forever.",
"""<p>After the research machinery says a strategy survives validation, the last honest gate is a machine that pretends to trade it, forever, with real data and no money. QuantLab's is a deliberately small piece of Python: <code>demo_bot.py</code>, SQLite, and Telegram alerts. It has never placed a live trade, by policy, and this piece is about both halves of that sentence &mdash; what building it teaches, and why &ldquo;never live&rdquo; is a design decision rather than a temporary caution.</p>
<h2>The shape of the thing</h2>
<p>The bot runs hourly scans against the lab's frozen configuration (held in a versioned <code>bot_config.yaml</code>, not in code &mdash; the config the freeze locked, read by the bot, never tuned by it). It keeps its state in SQLite: positions, fills it <em>would</em> have gotten, equity history. One-shot modes make it operable and auditable &mdash; scan now, show status, print a performance report &mdash; and every signal it acts on goes to Telegram, which doubles as the lab's heartbeat: a silent bot is a broken bot, and the alert log is the audit trail. No framework, no queue, no container orchestration. A research bot's job is to be understandable in a year, not impressive in a demo.</p>
<h2>What building it teaches that backtesting can't</h2>
<p><strong>State is harder than strategy.</strong> The simulation assumes you know your position; the bot has to actually keep it &mdash; through restarts, partial signals, data outages and timezone bugs (a timestamp-fixing utility exists in the repo for exactly the class of bug it caused). <strong>Data pipelines break in ways caches don't:</strong> the live feed and the cached research data disagree in format, gap policy and timing, and the bot is where those disagreements surface. <strong>Operational honesty:</strong> a backtest silently interpolates; a bot must decide what to do when a candle is missing at 3am, and that decision is engineering, not research.</p>
<h2>Why paper forever, stated plainly</h2>
<p>Because the bot's purpose is verification, not income. It exists to measure the gap between the simulation and executable reality &mdash; fills, latency, data breaks &mdash; at zero financial risk, and it does that job completely without ever wiring itself to an exchange order endpoint. Going live adds a new failure class (real money, real emotions, real exchange risk) while answering a question the research journal has usually already answered by then: most candidate strategies died in the <a href="/tech/backtest-validation-checklist/">validation gauntlet</a> long before the bot stage, and the ones that reached it were being tested, not trusted. The repo's own documentation marks the bot &ldquo;NEVER live&rdquo;; that is not timidity, it is scope.</p>
<p>The bot is also the project's most honest instructor about <a href="/tech/why-backtests-fail/">how simulations differ from reality</a> &mdash; and a good companion piece to <a href="/tech/learning-python-free-resources/">the honest guide to learning Python free</a> for anyone who wants to build small, real tools before ambitious ones.</p>
<p><em>Research note: QuantLab experiments are presented for educational and research purposes. Historical backtests and simulations do not guarantee future results and should not be interpreted as investment advice.</em></p>""",
[("Ojeology/QUANTLAB \u2014 demo_bot.py, bot_config.yaml and the paper-trading documentation", "https://github.com/Ojeology/QUANTLAB/blob/main/demo_bot.py"),
 ("QuantLab README \u2014 how to run the bot and the research scripts", "https://github.com/Ojeology/QUANTLAB/blob/main/README.md")],
[]),

("overfitting-detection-guide", "quant", "firsthand",
"Overfitting: how to catch yourself fitting the past",
"The most expensive mistake in quantitative work doesn't feel like a mistake \u2014 it feels like success. The tells, the controls, and the promotion vocabulary that keeps a research journal honest.",
"""<p>Overfitting is not an error you commit; it is a gravity you fall toward. Every choice in research &mdash; try another variant, tune a threshold, keep the good run &mdash; feels like diligence while quietly folding the model onto the past. After ~140 logged experiments, QuantLab's most useful artifact may be the list of tells that a result is curve-fit, because they were all learned by falling. Here is the detection guide.</p>
<h2>The tells, from the journal</h2>
<p><strong>The result needed the exact configuration.</strong> A parameter grid where performance spikes at one setting and dies a step away is not an optimum; it is an address where the past happened to live. The lab's frozen champion config looked like this from the outside &mdash; and the blind per-year re-test showed no static variant of the sweep survived all years after costs. <strong>Performance is strongest exactly where you looked.</strong> Universe-specificity: edges that worked on the symbols they were developed on and failed on unseen ones (logged by run number: R044, R049, R078). <strong>The drawdowns are too polite.</strong> A backtest with shallow, rare drawdowns has usually not met a hostile regime; the honest full-universe audit of the surviving champion found a drawdown several times deeper than its first report. <strong>It only wins on average.</strong> Aggregate results that hide a losing year are the classic pre-blind weakness &mdash; which is why the lab's blind campaign gates per year, not in total.</p>
<h2>The controls that work</h2>
<p><strong>Seal a holdout and touch it once.</strong> The lab's version: a strategy freeze, then a separate branch whose entire purpose was testing frozen conclusions on sealed years. The freeze matters as much as the holdout &mdash; tuning stopped is tuning you cannot undo the value of. <strong>Walk-forward, not in-sample/out-sample.</strong> Train only on the past, slide forward, and judge the joined result. <strong>Leave-one-out everything.</strong> Symbols, folds, years: if removing any one element kills the result, the result was that element. <strong>Pre-register the question.</strong> One script per numbered run, one falsifiable question, verdict logged before moving on &mdash; the journal structure in <a href="/tech/quantlab-project-how-built/">how the lab was built</a> exists to make result-shopping impossible. <strong>Statistical humility:</strong> bootstrap intervals and Monte Carlo on every promoted number, monthly stability checks, cost gates from the first prototype.</p>
<h2>The vocabulary is the cure</h2>
<p>The lab's verdicts &mdash; PROMOTE, WATCHLIST, REJECT, RETRACTED, OVERFIT &mdash; do the quiet work: WATCHLIST exists so a promising-but-thin result has somewhere honest to sit instead of being promoted by enthusiasm; RETRACTED exists so a withdrawn result stays in the log with its withdrawal dated. The project's biggest published conclusions are negative ones &mdash; including a family of retracted results and a failed freeze &mdash; and that record is worth more than any single win, because <strong>it is the record a stranger can audit</strong>. The moment your research journal can embarrass you, it starts protecting you.</p>
<p>If you take one habit from this: when a result looks best, that is the moment to schedule its most hostile audit &mdash; the lab's own champion fell to exactly that (<a href="/tech/lookahead-bias-explained/">the lookahead-bias story</a>), and the failures it joins are sorted in <a href="/tech/why-backtests-fail/">why backtests fail</a>.</p>
<p><em>Research note: QuantLab experiments are presented for educational and research purposes. Historical backtests and simulations do not guarantee future results and should not be interpreted as investment advice.</em></p>""",
[("Ojeology/QUANTLAB \u2014 the blind-validation campaign and promotion vocabulary", "https://github.com/Ojeology/QUANTLAB/tree/blind-validation"),
 ("QuantLab README \u2014 research philosophy and lessons", "https://github.com/Ojeology/QUANTLAB/blob/main/README.md")],
[]),
]
