# -*- coding: utf-8 -*-
"""Tech master build M5 — the troubleshooting library (8 pieces, Sept 2026).

Spec §14 template applied per piece: answer first -> quick checks -> causes -> fix ladder ->
alternatives -> mistakes -> provider-side -> support/escalation -> related. No volatile
claims anywhere: DNS flush commands, git error strings and WebSocket mechanics are stable;
browser error texts deliberately paraphrased, never quoted as exact UI strings.
Dedupe lanes vs the existing shelf (each older piece keeps its scope; these link in):
what-is-dns (concept) / phone-wont-connect-to-wifi (phone) / how-to-reset-forgotten-passwords
(reset flow) / http-status-codes-explained (codes reference) / handle-api-errors-python
(Python client) / storage-full-breaking-apps (the storage-specific crash cause).
Sources only where an external standard exists: git-scm book (conflicts), RFC 6455
(WebSocket), 12factor (config). Everything else: engineering reasoning, sources empty.
"""

TECH_MASTER_M5 = [

("dns-problems-diagnosed", "web-and-hosting", "guide",
"DNS problems: a diagnosis order that finds the cause fast",
"'Site down' is three different problems wearing one sentence. The lookup ladder: your machine, your resolver, the records, the host — and the flush that fixes the leftovers.",
"""<p>The diagnosis that saves the most time: before touching anything, work out <em>which layer</em> is broken. "The site is down" usually means one of four very different failures: your machine cached something stale, your resolver is having a moment, the domain's records are wrong, or the server behind the name is actually down. Each layer has a ten-second test.</p>
<h2>Quick checks, in order</h2>
<p><strong>1. Is it down for everyone, or just you?</strong> Try the site on another network (phone on mobile data). If it loads there, the problem is yours — skip to step 4. If it fails everywhere too, go to step 3. <strong>2. Can you reach other sites?</strong> If nothing resolves, your connection or resolver is the problem, not the site. <strong>3. What does the name resolve to?</strong> A DNS lookup tool (or <code>nslookup example.com</code> in a terminal) shows what the name currently points at. If it returns nothing or an old address while the host's dashboard says the records are right, the records or their propagation are the story — <a href="/tech/custom-domain-dns-order/">the custom-domain connection order</a> covers the record side. <strong>4. Is your own cache stale?</strong> This is the classic "I fixed it but still see the old site": flush your machine's cache — on Windows <code>ipconfig /flushdns</code>; on macOS <code>sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder</code>; on Linux, <code>resolvectl flush-caches</code> where systemd-resolved runs. Then retry with a fresh browser tab.</p>
<h2>The causes behind each symptom</h2>
<p><strong>Old site, new server:</strong> a cached record or a not-yet-propagated one. DNS records carry a TTL — how long any resolver may keep them — so changes become visible resolver by resolver, not everywhere at once. Nothing is "stuck"; it is expiring. <strong>New site, no resolution at all:</strong> missing or malformed records, wrong nameservers, or a domain whose registration lapsed — check the registrar first. <strong>Works on one device only:</strong> that device's cache or its configured DNS server. <strong>Intermittent, weird, ads redirecting:</strong> try a different reputable resolver (your router's default may be poorly maintained); changing resolvers on the device is a two-minute test that isolates the problem layer instantly.</p>
<h2>Common mistakes</h2>
<p>Changing records repeatedly while propagation is mid-flight (now <em>nobody</em> knows which version any resolver has — make one change, then wait out the TTL). Blaming the host before the lookup (step 3 exists so you don't). And the big one: assuming DNS when it's actually the browser — <a href="/tech/browser-problems/">the browser-problem triage</a> catches the cached-page-and-extension family, and <a href="/tech/why-restarting-fixes-problems/">the restart reflex</a> clears more "DNS problems" than any setting.</p>
<h2>When it's them, not you</h2>
<p>If lookups from multiple networks and resolvers all fail on one specific name, the domain's authoritative nameservers are the failing layer — that's registrar/hosting support, with the lookup output in hand. If everything everywhere fails, it's your ISP. Bring evidence: which layer, which test, which timestamp. Support escalates diagnosis, not desperation — <a href="/tech/what-is-dns/">and if DNS itself is the mystery, start there</a>.</p>""",
[],
[("what-is-dns", "What DNS actually does"),
 ("custom-domain-dns-order", "Custom domains, the right order"),
 ("browser-problems", "Browser problems, triaged")]),

("ssl-certificate-errors-explained", "web-and-hosting", "guide",
"SSL certificate errors: what each warning is actually telling you",
"Expired, wrong-name, self-signed and mixed content — the four certificate failures, what causes them, and which ones you must never click through.",
"""<p>A certificate error is your browser reporting that the padlock's promise failed — the cryptographic proof that you are talking to the real server, unmodified. The warnings look scary because they should: two of the four causes below are harmless-server-misconfiguration, and two are indistinguishable from an attack without more evidence. The skill is knowing which is which.</p>
<h2>The four failures</h2>
<p><strong>Expired certificate.</strong> The most common, and the server's fault, not yours: certificates expire on a schedule (the current maximum lifetime is 398 days) and whoever runs the site let the renewal lapse. The connection is still encrypted; the identity proof is stale. For a site you trust: stop, don't enter credentials, and report it — a big site with an expired cert is a site with broken maintenance, or something worse wearing that costume. <strong>Name mismatch.</strong> The certificate is real but belongs to a different name — <code>www.</code> missing from the list, or a subdomain served under the parent's cert. Usually a server misconfiguration; on sites you didn't seek out, name mismatch is also how naive phishing imitates real ones. <strong>Self-signed or unknown issuer.</strong> Nobody vouches for the server. Normal and intentional on internal company tools and local dev machines; on a public site, a serious signal — <a href="/tech/what-is-ssl-https/">the HTTPS explainer</a> covers why the issuer chain is the whole point. <strong>Mixed content</strong> (usually a shield icon, not a full-page block): the page is HTTPS but loads scripts or images over plain HTTP, which quietly reopens the hole the padlock closed — a site-owner bug, worth reporting.</p>
<h2>Quick checks before you conclude anything</h2>
<p>Is it one site or all sites? (All sites: your device's clock is the classic culprit — certificates are date-sensitive documents, and a wrong system clock makes every valid cert look expired.) Does the warning survive a fresh browser profile and another network? (If not, suspect your layer — extension, proxy, captive portal — before blaming the site, the <a href="/tech/browser-problems/">browser triage</a> applies.) Click the padlock/warning details: modern browsers name the exact failure — expired, name mismatch, untrusted issuer — and that name is the diagnosis.</p>
<h2>The rule about clicking through</h2>
<p>"Proceed anyway" exists for one legitimate case: sites you administer or a local development machine where you know exactly why the certificate is self-made. On a banking site, a login page, a payment page — never. The cost of a false alarm is one missed page load; the cost of a real interception is everything the padlock was invented to protect. Site owners on the other side of this table: the fix ladder lives in <a href="/tech/custom-domain-dns-order/">the domain-connection order</a> — certificates fail most often at the issuer-verification step, not the encryption itself.</p>""",
[],
[("what-is-ssl-https", "What HTTPS actually does"),
 ("browser-problems", "Browser problems, triaged"),
 ("custom-domain-dns-order", "Custom domains, the right order")]),

("git-errors-fixed", "coding", "guide",
"Git errors decoded: merge conflicts, detached HEAD, and the mistakes that cause them",
"The five errors every beginner meets, what Git is actually saying in each, and the fix that doesn't lose work.",
"""<p>Git's error messages are precise — the problem is that they're precise in Git's worldview, not yours. Here are the five every newcomer meets, translated, with fixes that keep your work. (The concepts behind these live in <a href="/tech/git-and-github-for-beginners/">the Git-and-G concepts guide</a>; this piece is the emergency room.)</p>
<h2>1. The merge conflict</h2>
<p><code>CONFLICT (content): Merge conflict in filename</code> — Git is saying: your change and another change touched the same lines, and it refuses to guess which wins. The file now contains markers: <code>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD</code> above your version, <code>=======</code>, and <code>&gt;&gt;&gt;&gt;&gt;&gt;&gt; branch-or-commit</code> above theirs. The fix is editorial, not magical: open the file, decide what the correct text should be (yours, theirs, or a blend), delete the markers, save. Then <code>git add filename</code> and commit. <strong>Never</strong> delete the file and start over — that's how a twenty-line conflict becomes a lost afternoon. And a conflict you can't resolve now has a clean escape: <code>git merge --abort</code> returns the repository to its pre-merge state, untouched.</p>
<h2>2. Detached HEAD</h2>
<p><code>You are in 'detached HEAD' state</code> — you checked out a specific past commit instead of a branch. Perfectly legal and useful for reading history; dangerous only if you commit there, because those commits belong to no branch and get garbage-collected away. If you made commits in this state and want them: <code>git switch -c my-rescue-branch</code> pins them to a new branch immediately. If you changed nothing: <code>git switch main</code> and move on.</p>
<h2>3. Push rejected</h2>
<p><code>! [rejected] ... fetch first</code> — the remote has commits you don't have. Git refuses to overwrite other people's work. The fix: <code>git pull</code> first (resolve any conflicts from step 1), then push. The mistake to avoid: <code>--force</code>, which exists for rewriting your <em>own</em> published history and annihilates everyone else's commits on shared branches.</p>
<h2>4. "fatal: not a git repository"</h2>
<p>You're running Git in a folder Git doesn't govern — usually the wrong directory, occasionally a deleted <code>.git</code> folder. Check where you are (<code>pwd</code>), <code>cd</code> into the project root, retry. If the folder genuinely lost its <code>.git</code>, the history is gone from that copy; re-clone from the remote and re-apply whatever wasn't pushed — which is the argument for <a href="/tech/github-beginner-mistakes/">pushing small and often</a>.</p>
<h2>5. The accidental commit</h2>
<p>Wrong message, or a secret file included: <strong>not yet pushed</strong> — <code>git commit --amend</code> fixes the message; <code>git reset --soft HEAD~1</code> unwinds the commit while keeping the changes staged. <strong>Already pushed</strong> — a later commit that removes the file is the safe move, and if the file was a credential, treat the key as burned and rotate it regardless of the cleanup (<a href="/tech/github-token-hygiene/">token hygiene</a>, and check <code>git log -S</code> for how deep it goes). History rewriting on shared branches buys cleanliness at the cost of everyone's sanity.</p>
<p>The meta-lesson from every incident here: Git almost never loses committed work — <em>uncommitted</em> work is what vanishes. When panic hits: <code>git status</code> first. It tells you exactly what state you're in, and its suggestion is usually the fix.</p>""",
[("Pro Git (official book) \u2014 advanced merging and conflict resolution", "https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging"),
 ("Pro Git (official book) \u2014 undoing things (amend, reset)", "https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things")],
[("git-and-github-for-beginners", "Git and GitHub for beginners"),
 ("github-beginner-mistakes", "GitHub beginner mistakes"),
 ("github-token-hygiene", "Token hygiene")]),

("app-crashes-android", "android", "guide",
"An app keeps crashing on Android: the triage that fixes most of it",
"Crash on open, crash on one action, or crash-after-update — the three patterns, the fix ladder from lightest to heaviest, and when the developer owns the bug.",
"""<p>An app that crashes is asking for triage in the right order, because the heavy-handed fixes (reinstall, clear data) destroy state you may want — logins, offline work, settings. Five minutes of pattern recognition first: <strong>crashes on open</strong> points at the app's saved state or its update; <strong>crashes on one specific action</strong> points at that feature (a camera permission, a corrupt file it reads); <strong>started after an app or system update</strong> points at a version conflict. The ladder below goes lightest-touch first.</p>
<h2>The fix ladder</h2>
<p><strong>1. Close it properly and retry once.</strong> Swipe it out of recents and reopen — a single crash is a data point, a pattern is a bug, and arestart clears the corrupted-memory case. <strong>2. Check storage.</strong> Crashes-on-open are disproportionately a full-disk symptom — Android apps need working space, and near-full phones break apps in ways that look random: <a href="/tech/storage-full-breaking-apps/">the storage-full mechanism</a> and <a href="/tech/free-up-storage-android/">the cleanup that fixes it</a>. <strong>3. Update the app.</strong> The store listing's "update" button fixes the single most common crash class: a bug the developer already fixed. Same for Play system / OS updates when they're pending. <strong>4. Clear the app's cache.</strong> Settings, then Apps, then the app, then Storage, then Clear cache: wipes junk the app wrote, keeps your logins and settings. Safe, fast, fixes the corrupt-saved-file family. <strong>5. Clear storage (the honest reset).</strong> Same screen, Clear data: the app returns to first-run state — fix for the corrupted-preferences case, at the cost of signing in again. Do this <em>before</em> reinstalling; it fixes most of the same bugs without re-downloading anything. <strong>6. Reinstall.</strong> Only now: uninstall and install fresh. Same cost as step 5 plus a download; do it when the store update itself was the suspect (an interrupted update corrupts installs).</p>
<h2>The permission-shaped crash</h2>
<p>A crash triggered by one action — sending a photo, recording audio — is often the app mishandling a denied permission: it asked for the camera, Android said no (permanently, possibly years ago), and a well-built app asks again while a buggy one dies. <a href="/tech/android-app-permissions/">Check what the app is allowed to do</a> and grant the relevant one; if the crash follows the permission like a shadow, the developer owns the bug.</p>
<h2>When it's the developer's problem</h2>
<p>Worked the ladder, still crashes on a clean install with full storage and current OS? That's a bug in the app, full stop — and it's worth ten seconds to report (store listing, scroll to the developer contact; Play Store reviews with "crashes on [device], after [action]" genuinely get read). Meanwhile: your data was never only in that app, was it? Backups are how app tragedies stop being data tragedies — <a href="/tech/three-two-one-backup-rule/">the 3-2-1 habit</a> applies to phones exactly as to everything else. And the battery-heat cousins of this story live in <a href="/tech/android-battery-health/">battery health, honestly</a>.</p>""",
[],
[("storage-full-breaking-apps", "The storage-full crash mechanism"),
 ("free-up-storage-android", "Freeing Android storage"),
 ("android-app-permissions", "Android app permissions")]),

("login-problems-checklist", "safety", "guide",
"Login problems: the complete checklist, in the order that finds the cause",
"Wrong-password loops, 2FA dead ends, lockouts and 'invalid email' — separate credential failures from account failures from browser failures, and fix the right one.",
"""<p>Failed logins feel like one problem and are at least five: wrong credentials, a dead recovery channel, a second-factor trap, an account that no longer exists, or a browser that's lying to you. The checklist below splits them in minutes, ordered so that each step either finds the cause or eliminates a layer.</p>
<h2>Layer one: the browser is innocent until proven guilty</h2>
<p>Before anything clever: is caps lock on? (Still the champion.) Then try the same login in a private window — password managers' autofill quietly submitting a saved <em>old</em> password is the single most common false "wrong password" in existence. If the private window works, clear the saved entry and <a href="/tech/browser-problems/">triage the browser</a>. If your manager holds the credential, log into the manager itself and copy it manually — and if the manager's copy also fails, you've just proven the problem is at the account, which is progress.</p>
<h2>Layer two: credentials vs account</h2>
<p><strong>"Incorrect password" on a manual, carefully typed attempt</strong> means the reset flow, and only that: <a href="/tech/how-to-reset-forgotten-passwords/">the reset walkthrough</a> covers it — including the golden rule that the reset email arriving (or not) is itself diagnostic. <strong>"No account found for this email"</strong> is a different animal entirely: the account lives under another address (an old one, an alias, a sign-up-with-Google/Apple identity instead of a password). Try the provider's sign-in-with buttons before concluding anything — half of "I lost my account" is "my account has no password because it never needed one."</p>
<h2>Layer three: the second factor</h2>
<p>2FA failures have their own short list: <strong>SMS codes not arriving</strong> — wait one full cycle (carriers delay, don't drop), then check whether the number on the account is still yours; a changed SIM or an old number is the classic dead end, which is why <a href="/tech/two-factor-authentication-setup/">an authenticator app beats SMS</a> the day you set it up. <strong>Authenticator app codes rejected</strong> — check the phone's clock: time-based codes die on a skewed clock (enable automatic time). <strong>Lost the device entirely</strong> — this is what the recovery codes were for at setup; no recovery codes and no second device means account-recovery support, and the provider will verify you slowly and thoroughly. That slowness is the feature working.</p>
<h2>Layer four: when the account itself is the problem</h2>
<p>Suspected compromise changes the order: go straight to the provider's account-recovery flow from a clean browser, change the password from wherever you get in first, then review active sessions and connected apps. And a password manager changes the arithmetic in your favour everywhere else — <a href="/tech/password-manager-or-browser/">the honest comparison</a> — because "which of my forty passwords did I use here" stops being a question you have to guess under pressure. One warning to close on: login problems make people pliable, and phishing knows it — a "support agent" offering to fix your login over chat or email is the attack, not the cure. Support comes from the provider's own site, typed by you (<a href="/tech/how-to-spot-a-suspicious-link/">the link-checking habit</a>).</p>""",
[],
[("how-to-reset-forgotten-passwords", "The password-reset walkthrough"),
 ("two-factor-authentication-setup", "2FA, set up properly"),
 ("browser-problems", "Browser problems, triaged")]),

("api-errors-decoded", "coding", "guide",
"API integration failing? A debugging order that finds the broken layer",
"The request-response autopsy: read the body, verify auth, match the payload, check the rate limit, and suspect versions before you suspect the universe.",
"""<p>When an API integration fails, the error message is the beginning of the conversation, not the end. The discipline that separates an afternoon of guessing from ten minutes of diagnosis: test each layer of the request separately — URL, authentication, payload, quota, version — in that order, because each step either finds the problem or eliminates a layer.</p>
<h2>1. Read the body of the error (yes, the error)</h2>
<p>The status code is the headline; the response <em>body</em> is the article. Good APIs return machine-readable detail in their errors — which field failed, why, what the server expected. Extract and print the body before anything else: in most client libraries that means catching the error and reading its response object rather than its message. A 400 that says <code>"email: invalid format"</code> needs no speculation at all. The codes themselves are the vocabulary: <a href="/tech/http-status-codes-explained/">the status-code field guide</a>, and the Python-shaped handling ladder is in <a href="/tech/handle-api-errors-python/">handling API errors properly</a>.</p>
<h2>2. Authentication: the 401/403 disambiguation</h2>
<p>A 401 (unauthorized) means credentials are missing, malformed or expired; a 403 (forbidden) means the credentials are <em>working</em> and this account simply may not do that. So: 401 → check the header format exactly (<code>Authorization: Bearer TOKEN</code> — scheme, spelling, the literal space), check whether the token expired, check whether it was pasted with a trailing newline or quotes. 403 → stop retrying with the same credentials; the fix is permissions on the account or a different scope, not a better request. This single distinction kills most auth debugging loops, and it's the same discipline as <a href="/tech/github-token-hygiene/">token hygiene</a>: scoped, current, and never pasted where it doesn't belong.</p>
<h2>3. The payload, verified byte by byte</h2>
<p>415 and 400 responses are usually one of three boring causes: the <code>Content-Type</code> header doesn't match what you're actually sending (JSON body without <code>application/json</code> is the champion), a required field is absent, or a field's type is wrong (a number sent as a string). Test the exact request outside your code — a standalone curl or an API client with the identical headers and body — and you have isolated your code from the request: whichever side fails the manual test is the side that's wrong.</p>
<h2>4. Quotas and the silent slowdown</h2>
<p>429s and mysterious mid-integration failures after weeks of success are rate limits and expired quotas. Check the response headers (most serious APIs advertise <code>RateLimit-*</code> or <code>Retry-After</code>), add the retry-with-backoff behaviour before you need it, and log your request rate — a retry loop with no backoff turns a soft limit into a hard ban. If it worked for months and broke today with a 401: check the provider's changelog first; rotated keys and expired demo credentials are the two horsemen of "nothing changed on my end."</p>
<h2>5. Versions and the last resort</h2>
<p>APIs deprecate: an endpoint that dies without code changes on your side is usually a version sunset — the provider's status page and changelog are the first read, before the bug report. And when the evidence says the failure is genuinely theirs (5xx across multiple clean requests, status page confirming incidents): your job is a support ticket with the autopsy attached — exact request (secrets redacted), exact response, timestamps, request IDs if the API returns them. The ticket that gets fixed same-day is the one that hands support their own log line. If the whole exchange happens in a browser tab, remember the status lookup tool exists for the quick checks: <a href="/tech/tool/http-status-lookup/">the HTTP status lookup</a>.</p>""",
[],
[("http-status-codes-explained", "HTTP status codes, explained"),
 ("handle-api-errors-python", "Handling API errors in Python"),
 ("what-is-api", "What an API actually is")]),

("websocket-debugging", "coding", "guide",
"WebSockets not connecting: the debugging path from handshake to heartbeat",
"When a socket won't open, dies mid-stream or silently stalls: read the handshake first, then the close code, then the network between you — and add the heartbeat you were missing.",
"""<p>A WebSocket is a plain HTTP conversation that upgrades into a persistent two-way connection (that's the whole trick, formalised in RFC 6455). Every failure therefore lives in one of three phases: the <strong>handshake</strong> (the upgrade never completes), the <strong>stream</strong> (connected, then messages fail), or the <strong>silence</strong> (no errors, just a dead connection nobody noticed). Diagnose by phase.</p>
<h2>Phase one: the handshake that never completes</h2>
<p>Open the browser's developer tools, Network tab, filter WS, and reload: the socket attempt appears as its own row. Failure modes and what they mean: <strong>HTTP 404/405 on the socket request</strong> — wrong path or the server doesn't accept upgrades there; <strong>403</strong> — the server's <em>origin check</em> rejected your page (WebSockets are not bound by the browser's same-origin policy; the server enforces its own allowlist, and your localhost dev origin is the classic rejection); <strong>401</strong> — auth missing: unlike regular requests, a WebSocket's credentials ride the initial request or the URL, so a token that works on the API may never reach the socket layer; <strong>connection reset / mixed content</strong> — an <code>ws://</code> socket from an <code>https://</code> page is blocked by the browser, full stop; the page must speak <code>wss://</code>. And the one that isn't your fault: some corporate proxies and networks simply refuse the upgrade — testing from another network (phone hotspot) settles "is it them or the firewall" in one minute.</p>
<h2>Phase two: connected, then gone — read the close code</h2>
<p>Sockets close with a numeric code, visible in the console and the WS row's timeline, and the numbers are the message: <strong>1000</strong> normal goodbye; <strong>1006</strong> the useful one — the connection died <em>abnormally</em> without a proper close (network drop, proxy timeout, process crash); <strong>1011</strong> the server hit an error while handling your session. 1006 after a few quiet minutes is almost always an idle timeout somewhere on the path: which brings the fix to you, not them.</p>
<h2>Phase three: the heartbeat you were missing</h2>
<p>Production sockets that must survive real networks implement a <strong>heartbeat</strong>: the client pings every N seconds, the server pongs, and either side that hears nothing for a timeout window closes and reconnects. Without it, half-open connections sit silently dead on both ends — the app shows "connected" while nothing flows. The same reconnect needs <strong>exponential backoff with jitter</strong> (1s, 2s, 4s…, plus randomness so a thousand clients don't stampede the server at second one). If your socket library offers ping/pong and auto-reconnect settings, the debugging in this paragraph is the reason they exist — set them deliberately rather than accepting defaults you can't state out loud.</p>
<h2>Logging that actually helps</h2>
<p>Log the phase transitions, not a message flood: opened, closed (with code), reconnect attempt number, and every error object whole. The pattern "opens fine, 1006 every four minutes behind one specific proxy" falls out of four log lines and points at the idle timeout immediately. WebSockets share the plain-HTTP road all the way to the upgrade — which means the generic networking triage (<a href="/tech/dns-problems-diagnosed/">DNS, resolution, reachability</a>) still applies as phase zero, and the server-side cousins of these failures live in <a href="/tech/render-deployment-failures-what-they-taught-me/">the deployment-failure field notes</a>.</p>""",
[("IETF RFC 6455 \u2014 The WebSocket Protocol (the upgrade handshake, close codes)", "https://datatracker.ietf.org/doc/html/rfc6455")],
[("dns-problems-diagnosed", "DNS problems, diagnosed"),
 ("http-status-codes-explained", "HTTP status codes, explained"),
 ("render-deployment-failures-what-they-taught-me", "Deployment failures, documented")]),

("environment-variables-guide", "web-and-hosting", "guide",
"Environment variables: what they are and why your API keys live there",
"Configuration that changes per machine without changing code: how env vars work in shells, .env files and hosting dashboards — and the rules that keep secrets out of repos.",
"""<p>An environment variable is a named value the operating system hands to every program it starts: <code>KEY=value</code>, invisible in the code, set per machine. That one mechanism is why the same application runs unchanged on your laptop, in CI, and in production — and it is the standard answer to the most important question in configuration: <em>what differs between those places?</em> Database URLs, API keys, feature flags, ports. The principle has a name in the Twelve-Factor methodology — keep config in the environment, never in the code — and it exists because code goes places config must not: repositories, forks, clones, screenshots.</p>
<h2>The shell: set, read, list</h2>
<p>On Linux and macOS, <code>export API_KEY="abc123"</code> sets it for this terminal session and everything launched from it; <code>echo "$API_KEY"</code> reads it; <code>env</code> (or <code>printenv</code>) lists what's currently set. Windows: <code>setx API_KEY "abc123"</code> persists it for future sessions (new terminals only — a classic trap), <code>set</code> for the current one. In Python you read them with <code>os.environ["API_KEY"]</code> — and the deliberate choice of bracket-access over <code>.get()</code> matters: an app should crash at startup without its secrets, not limp on and discover the hole in production (<a href="/tech/deploy-python-app/">the deploy walkthrough</a> builds exactly this way).</p>
<h2>The .env file: local convenience, with rules</h2>
<p>Real projects use a <code>.env</code> file — one <code>KEY=value</code> per line — loaded into the environment at startup by the language's dotenv library. Two rules are non-negotiable. <strong>One: <code>.env</code> goes in <code>.gitignore</code> before the first commit</strong> — the file's entire purpose is to hold values the repo must never contain; most ecosystems ship a <code>.env.example</code> with the keys and dummy values for teammates instead. <strong>Two: .env is a local pattern.</strong> In production the host's dashboard or secret manager injects the same variables at runtime — no files to leak, and rotation is a form field, not a deploy. A committed <code>.env</code> is how repositories end up in credential-scanning botnets within hours; if it happens, the key is burned regardless of the cleanup — <a href="/tech/github-token-hygiene/">rotate first, tidy second</a>.</p>
<h2>The two gotchas that cost everyone an hour</h2>
<p><strong>Scope:</strong> variables set in one terminal don't exist in another, don't reach services the system already started, and don't survive a reboot unless persisted (export lines in your shell profile, or setx/Task Scheduler equivalents on Windows). "Works in my terminal, not in the app" is scope, almost every time. <strong>Name drift:</strong> <code>API_KEY</code> and <code>APIKEY</code> are different variables; the failure mode is a silent empty string, which is why the crash-at-startup read beats the default-to-empty read everywhere it's practical.</p>
<p>One closing boundary, because this piece is about secrets: environment variables beat hardcoded keys and beat .env-in-repo, and they are still not a vault — anyone with code execution on the machine can read the process environment. They are the right tool for keeping secrets out of code and repos; actual secret-management systems (the host's encrypted stores) are the next tier, when the stakes justify it. For the reasoning about what should never sit in a plain file at all, see <a href="/tech/plain-text-passwords/">the plain-text password rule</a>.</p>""",
[("The Twelve-Factor App \u2014 Config (the environment, not the code)", "https://12factor.net/config"),
 ("Python docs \u2014 os.environ", "https://docs.python.org/3/library/os.html#os.environ")],
[("github-token-hygiene", "Token hygiene"),
 ("deploy-python-app", "Deploying a Python app"),
 ("plain-text-passwords", "The plain-text password rule")]),
]
