# BRYME Tech — the troubleshooting library (batch 28, 11 Sep 2026).
# Master Pack §3.1.2 priority builds + §4.1 template:
# symptom → likely causes (ordered) → diagnosis → fix → when the fix won't work → escalation → official docs (dated).
# First-hand claims are genuinely ours: this site is the evidence (Render deploys, the DNS saga, cert issuance, the sitemap validator).

TROUBLESHOOTING_GUIDES = [
("website-wont-deploy-fix", "web-and-hosting", "troubleshooting",
"Why won't my website deploy? The diagnostic tree",
"Build red, build green but the site wrong, or nothing happening at all — the three failure families, in the order that finds the cause fastest.",
"""<p><b>The symptom:</b> you push, and your site does not update. Or the deploy fails. Or it "succeeds" and serves something wrong. Before touching a single setting, sort the failure into one of three families — because each has a different first suspect, and testing in the wrong family wastes hours.</p>
<h2>Family 1: the build fails</h2>
<p><b>Likely causes, most common first:</b> a dependency problem (missing package, version pinned differently locally than in CI — <em>very common</em>); an environment variable the build needs but the platform does not have (<em>common</em>); a build command that works interactively but not in a clean checkout (wrong working directory, global tools, case-sensitive filenames — <em>common on Windows-authored projects</em>); Node/Python version mismatch (<em>occasional</em>).</p>
<p><b>Diagnosis:</b> read the build log bottom-up — the first error is usually above a wall of noise, but the <em>last</em> error is the fatal one; work between them. Then reproduce in a clean checkout: clone fresh, install, run the exact build command the platform runs. If it passes locally and fails remotely, it is an environment difference (versions, env vars, case). We debug our own builds exactly this way — this desk's builder once failed on a missing data key that only existed on our machines, and the clean-checkout rule found it in minutes.</p>
<p><b>Fix:</b> pin your runtime version in the repo (a <code>.node-version</code>/<code>runtime.txt</code>-style file); commit every env var the build needs into the platform's settings (never the repo); make the build command runnable from a fresh clone by a stranger.</p>
<h2>Family 2: the build passes but the site is wrong</h2>
<p><b>Likely causes:</b> the publish directory points at source instead of generated output (<em>the</em> classic); a redirect or header rule at the host shadowing your expectations; caching — the CDN or your browser serving the previous deploy; the deploy quietly serving the last good build after a later failure (static hosts do this by design — resilience that hides breakage).</p>
<p><b>Diagnosis:</b> hard-refresh with cache disabled, then check the deploy log's timestamp against the change you expect. Curl the exact URL and look at the bytes, not the browser. If the bytes are old, you are either looking at the wrong publish directory or the deploy did not actually succeed — the build badge and the log, never the homepage, tell you the truth.</p>
<h2>Family 3: nothing happens at all</h2>
<p><b>Likely causes:</b> the push never triggered a build (wrong branch watched — <em>very common</em>); the Git integration lost authorization; you are pushing to a fork/remote the platform is not watching.</p>
<p><b>Diagnosis:</b> confirm the commit is on the branch the platform watches (<code>git log origin/main</code> is your friend), then trigger a manual deploy. A manual build that works means the automation is the problem; one that fails means it was Family 1 all along.</p>
<h2>When this fix will not work</h2>
<p>If a clean checkout, pinned versions, committed env vars and a watched branch all check out and the build still fails in a way you cannot reproduce locally, you may be hitting a platform-side limit (build minutes, memory on the build image). Keep the log excerpt — you will need it. And if the site serves but a <em>path</em> is wrong while the root works, that is routing, not deployment: check redirects before rebuilding anything. The deeper post-mortems from real failures live in <a href="/tech/render-deployment-failures-what-they-taught-me/">what Render deployment failures taught us</a> and the full <a href="/tech/render-static-deploy/">Render static deploy walkthrough</a>.</p>
<h2>When to escalate</h2>
<p>After a reproducible log, a clean-checkout test, and a status check on the platform's own status page — that is the evidence package support (or a forum) needs. Posts without the log get guesses; posts with it get answers.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Render deploys &amp; troubleshooting (render.com/docs), GitHub Pages usage limits and troubleshooting (docs.github.com/pages), and your platform's build-log reference.</p>"""),
("dns-not-working-propagation", "web-and-hosting", "troubleshooting",
"Why does DNS not work — and why do changes 'take so long'?",
"Wrong records, caching layers, and the registry itself: how to find which layer is lying to you, and what propagation actually is.",
"""<p><b>The symptom:</b> you changed a DNS record, and part of the world still sees the old one. Or a brand-new domain simply does not resolve at all. DNS feels mystical mostly because there are five layers between your typing and the internet's answering, and any one of them can be the one that is out of date. Name the layer, and the mystery dies.</p>
<h2>Likely causes, most common first</h2>
<p><b>1. The record itself is wrong</b> (<em>very common</em>): a typo in the hostname or target; an A record where a CNAME was needed (or the reverse — CNAMEs cannot coexist with other records on the same name); an apex domain given a CNAME, which many providers forbid or flatten specially.</p>
<p><b>2. Caching, at the resolver</b> (<em>very common</em>): records carry a TTL — "time to live" — and resolvers keep answers until it expires. A low TTL (60–300 seconds) spreads changes fast; a high one (hours to a day) is why your aunt still sees the old site.</p>
<p><b>3. Your own device's cache</b> (<em>common during testing</em>): operating systems and browsers cache answers too; you are sometimes the stale one.</p>
<p><b>4. Nameservers not pointing where you think</b> (<em>common after a registrar or host change</em>): the records you are editing live at one provider, but the domain's nameservers point at another. You are carefully updating a record nobody reads.</p>
<p><b>5. The registry itself</b> (<em>rare, but the deepest</em>): the domain is expired, on hold, or not fully registered — no DNS anywhere can answer for it. We know this failure intimately: this site's own domain spent weeks not existing <em>at the registry level</em> while nameserver configuration sat correct at every provider — a reminder that the layer you can edit is not always the layer that is broken.</p>
<h2>Diagnosis: interrogate each layer</h2>
<p>Ask a public resolver directly: <code>dig yourdomain.com @1.1.1.1</code> (or an online equivalent). If the authoritative nameservers answer correctly but resolvers do not, it is caching — check the record's TTL and wait it out, or lower TTLs <em>before</em> the next change (the professional's habit). If the authoritative servers answer wrongly, fix the record at that provider. If nobody answers, check the domain's status at a registry whois lookup (ICANN Lookup): <code>clientHold</code>, <code>serverHold</code> or a missing delegation means the problem is above DNS entirely. Then compare two independent resolvers (say 1.1.1.1 and 8.8.8.8) — agreement means propagation is done, however your browser feels.</p>
<h2>The fix, in the right order</h2>
<p>Lower TTLs a day ahead of planned changes → make the change at the provider the nameservers actually point to → verify at the authoritative nameservers → let caches age out (minutes for low TTLs, up to a day or more for high ones) → only then troubleshoot "downstream" things like certificates, which need working DNS before they can issue at all — see <a href="/tech/ssl-certificate-not-issuing/">why your certificate will not issue</a>.</p>
<h2>When this fix will not work</h2>
<p>A registry hold only your registrar can lift; DNSSEC configured at the registrar but wrong at the host (validation failures look like total non-existence); and enterprise networks pinning their own resolvers with long caches — nothing you control fixes the last one fast, which is why propagation checkers that sample many networks exist.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Cloudflare's DNS learning library (cloudflare.com/learning/dns), ICANN Lookup (lookup.icann.org), and your registrar's DNS status reference. The fuller primer: <a href="/tech/what-is-dns/">what DNS actually is</a>, and the order-of-operations that avoids downtime in <a href="/tech/custom-domain-dns-order/">custom domains: the DNS order</a>.</p>"""),
("ssl-certificate-not-issuing", "web-and-hosting", "troubleshooting",
"Why is my site still not HTTPS? Certificate problems, in order",
"DNS first, CAA second, coverage third: why certificates fail to issue, and why the padlock can still say 'Not secure' on a working site.",
"""<p><b>The symptom:</b> your host promises free automatic HTTPS, and hours later the browser still warns, or the certificate simply never appears. Certificate issuance is a robot verifying control of your domain — and robots are literal. When it fails, it is almost always one of five things, in this order of frequency.</p>
<h2>Likely causes, most common first</h2>
<p><b>1. DNS is not actually pointing yet</b> (<em>the most common by far</em>): certificate authorities verify domain control by resolving your hostname. If DNS has not propagated — or resolves to the wrong place — issuance cannot start. No amount of host-side retrying fixes a record that does not answer; fix DNS first (<a href="/tech/dns-not-working-propagation/">the DNS diagnostic</a>), and issuance usually follows on its own.</p>
<p><b>2. You are looking at the wrong name</b> (<em>common</em>): a certificate that covers <code>example.com</code> does not automatically cover <code>www.example.com</code> (or vice versa). The browser visiting the uncovered variant sees a name-mismatch error while the other variant works perfectly.</p>
<p><b>3. A CAA record blocks your issuer</b> (<em>occasional and confusing</em>): CAA records name which certificate authorities may issue for the domain. If one exists and your host's CA is not on the list, issuance fails with an error that mentions authorization, not CAA — unless you know to look.</p>
<p><b>4. Mixed content</b> (<em>very common, and not an issuance problem at all</em>): the certificate is fine, but the page loads images or scripts over <code>http://</code>, so the browser still flags it "Not secure". The padlock tests the whole page, not just the connection.</p>
<p><b>5. Issuance delay or rate limits</b> (<em>occasional</em>): brand-new hostings can take a little while to request and receive certificates; authorities also rate-limit repeated failed attempts — hammering "renew" can make things worse.</p>
<h2>Diagnosis, safely</h2>
<p>Click the padlock (or the warning) and read the certificate detail: the browser tells you whether the cert is missing, expired, or for a different name — three different diseases. Then check the domain with an online SSL checker or <code>openssl s_client -connect yourdomain.com:443</code> to see what is actually being served. Confirm DNS answers first — certificate robots check it the same way. Search the domain's DNS for CAA records before suspecting the host.</p>
<h2>The fix, in the honest order</h2>
<p>DNS answers correctly → both variants (apex and www) covered by the host's certificate settings → CAA records either removed or listing your host's CA → trigger issuance once, then wait the provider's stated window → if the padlock still complains, audit the page for <code>http://</code> resources (the browser console lists every one) and fix those references. On this very site, the managed certificates issued without drama precisely because DNS was verified first — the boring order is the fast one.</p>
<h2>When this fix will not work</h2>
<p>Hosted names that cannot get public certificates (internal <code>.local</code>-style names); free hosting tiers with per-domain issuance limits; and browser-trust problems on very old devices — where the certificate is valid but the device's trust store is a decade stale. The last one is the environment's problem, not yours.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Let's Encrypt's docs on rate limits and CAA (letsencrypt.org/docs), MDN on mixed content (developer.mozilla.org), and your host's certificate/HTTPS reference. For what the certificate actually asserts, see <a href="/tech/what-is-ssl-https/">what SSL/TLS and HTTPS really are</a>; for the errors browsers show, <a href="/tech/ssl-certificate-errors-explained/">certificate errors, explained</a>.</p>"""),
("website-not-indexing-google", "web-and-hosting", "troubleshooting",
"Why is my site not on Google? An indexing diagnostic",
"From 'site:' to Search Console: the nine checks in the order that finds the blocker — and the honest truth about new sites.",
"""<p><b>The symptom:</b> the site (or one page) is live, loads fine in a browser, and simply does not appear on Google. Indexing is where most site-owners lose weeks to the wrong fixes. The diagnostic order below finds the actual blocker, from hardest block to softest.</p>
<h2>Step 1: ask Google what it thinks</h2>
<p>Search <code>site:yourdomain.com</code>. Results exist but the page is missing? That is a per-page problem. No results at all? That is a site-wide one — proceed in order. Then open <b>Google Search Console</b> (free), verify the site, and use URL Inspection on the exact page: Google states directly whether the URL is indexed, and if not, names the reason. Everything after this step is faster with Search Console open; its coverage report is the single most honest instrument in SEO.</p>
<h2>Likely causes, most common first</h2>
<p><b>1. The page says "noindex"</b> (<em>very common after redesigns/migrations</em>): a <code>&lt;meta name="robots" content="noindex"&gt;</code> left over from staging, or an <code>X-Robots-Tag</code> header doing the same silently. View-source and check; header checkers show the header variant.</p>
<p><b>2. robots.txt blocks crawling</b> (<em>common</em>): a <code>Disallow</code> aimed at staging that survived launch. Note the subtlety: robots.txt stops <em>crawling</em>, noindex stops <em>indexing</em> — and a page blocked from crawling can still appear as a bare URL if someone links to it. Fix them in that order: unblock crawl, and let (or tell) Google index.</p>
<p><b>3. The page is not reachable as a link</b> (<em>common on small sites</em>): Google finds pages chiefly by following links. If nothing internal links to the page and it is not in the sitemap, it may simply never be discovered. Every page on this desk sits in a sitemap and at least one shelf — internal linking is indexing plumbing, not decoration.</p>
<p><b>4. Canonical points elsewhere</b> (<em>occasional</em>): the page declares <code>rel=canonical</code> to another URL, and Google obeys. Check that the canonical is the page itself (or deliberately the preferred twin).</p>
<p><b>5. The sitemap is stale or wrong</b> (<em>common</em>): sitemaps that list pages which redirect or 404 teach Google to distrust them. The honest pattern this desk ships: every page in the sitemap exists, is canonical, is indexable — enforced by a validator at build time, so drift is impossible. A sitemap is a promise; keep it machine-checked.</p>
<p><b>6. It is simply too new</b> (<em>the honest one</em>): new domains can take days to weeks for a first crawl and indexing; sitemap submission in Search Console plus one real external link shortens the wait. Nothing you buy accelerates it — anyone selling "instant indexing" is selling noise.</p>
<p><b>7. Quality filters</b> (<em>the uncomfortable one</em>): thin, duplicated or scraped pages can be crawled and deliberately left out of results. The fix is the hard one: make the page deserve the query — the question this desk applies to every page before publishing is whether a real person would bookmark it.</p>
<h2>When the fix will not work</h2>
<p>Manual actions (visible in Search Console) and security hacks require a reconsideration process, not a tag change. And no diagnostic fixes a page whose answer nobody searches for — indexability is necessary, never sufficient.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Google Search Central's indexing and crawl-management docs (developers.google.com/search/docs) and Search Console Help (support.google.com/webmasters). Companions on this desk: <a href="/tech/check-if-google-indexed-your-page/">check if Google indexed a page</a> and <a href="/tech/sitemap-indexnow/">sitemaps and IndexNow, explained</a>.</p>"""),
]

TROUBLESHOOTING_GUIDES.extend([
("github-pages-not-showing-changes", "web-and-hosting", "troubleshooting",
"Why is GitHub Pages not showing my changes?",
"Branch, cache, base path: the three places a deployed change hides — and the project-page trap that breaks assets.",
"""<p><b>The symptom:</b> you pushed, GitHub says the Pages deployment succeeded, and the live site still shows yesterday. Or the text updated but the stylesheet and images went missing. GitHub Pages has three classic hiding places, and one infamous trap.</p>
<h2>Likely causes, most common first</h2>
<p><b>1. The change is not on the branch Pages publishes</b> (<em>very common</em>): Pages can serve from <code>main</code>, from <code>main</code>'s docs folder, or from a <code>gh-pages</code> branch — and your push may have gone to a different one. Check the commit hash GitHub shows for the deployment against <code>git log origin/&lt;branch&gt;</code>. Pushing to the wrong remote or a fork is the same disease.</p>
<p><b>2. The build didn't run, or built nothing new</b> (<em>common</em>): Pages builds can queue, and a failed or skipped workflow looks like silence. The Actions tab — not the site — is the source of truth: red build, no deploy; green build with an old timestamp, wrong branch.</p>
<p><b>3. Caching</b> (<em>common, and partly out of your control</em>): your browser caches aggressively. Hard-refresh with cache disabled or a private window before blaming GitHub; GitHub's own CDN may also serve the prior version briefly.</p>
<p><b>4. The project-page base-path trap</b> (<em>the infamous one</em>): a project site serves at <code>username.github.io/repo-name/</code>, not the domain root. Absolute paths like <code>/style.css</code> resolve to <code>username.github.io/style.css</code> — a different place entirely — so the HTML updates and every asset 404s. Relative paths (or a configured base URL in your generator) are the fix; custom domains remove the prefix entirely.</p>
<p><b>5. Jekyll interference</b> (<em>occasional</em>): Pages runs Jekyll by default, which ignores files starting with underscores and can alter processing. Files that vanish mysteriously are usually sitting in an underscore folder or were excluded by default; a <code>.nojekyll</code> file at the root opts out for sites that need no processing.</p>
<h2>Diagnosis, in order</h2>
<p>Confirm the commit is on the right branch → open the Actions tab and read the latest deployment (status and timestamp) → load the site in a private window (kills the cache variable) → view the exact asset URL that is failing and read its full path — the base-path trap is visible in the address bar. This mirrors the three-family triage in <a href="/tech/website-wont-deploy-fix/">why won't my website deploy</a>, just with GitHub's specifics.</p>
<h2>When this fix will not work</h2>
<p>DNS problems on a custom-domain Pages site are DNS problems, not Pages problems — the deployment can be perfect while the domain answers at the wrong place (<a href="/tech/dns-not-working-propagation/">the DNS diagnostic</a>; and the ordering that avoids the downtime trap is in <a href="/tech/custom-domain-dns-order/">custom domains: the DNS order</a>). And a repository over its Pages size limit or bandwidth quota serves stale or error states that no amount of re-pushing changes.</p>
<p><b>Official documentation (checked 11 September 2026):</b> GitHub Pages docs — configuring a publishing source, about custom domains and GitHub Pages, and Pages troubleshooting (docs.github.com/pages).</p>"""),
("firebase-deployment-failing", "web-and-hosting", "troubleshooting",
"Why does Firebase deployment fail? Rules, indexes, quota",
"The CLI's four honest error families — auth, project, rules and indexes — and the exact order to read them in.",
"""<p><b>The symptom:</b> <code>firebase deploy</code> ends in red, or deploys fine while the app itself throws errors the moment it runs. Firebase splits failures into two very different worlds — the deploy and the runtime — and mixing them up wastes evenings. This guide is built from the official documentation and public issue patterns, with sources dated below; it is deliberately not dressed up as a personal war story.</p>
<h2>Deploy failures: three families</h2>
<p><b>1. Authentication and project selection</b> (<em>the most common</em>): expired CLI login or CI token (<code>firebase login</code> again, or rotate the CI token), and — the quiet one — the CLI deploying to a different project than you think. Read the deploy output's project line against your intent, and check <code>.firebaserc</code> aliases: "deployed" to the staging project is the classic silent failure.</p>
<p><b>2. Rules and config rejections</b> (<em>common</em>): security-rules files with syntax errors, invalid <code>match</code> patterns, or a ruleset that fails validation stop the whole deploy. The CLI prints the file and line — read the first error, not the last.</p>
<p><b>3. Function deployment problems</b> (<em>common on Node projects</em>): a Node runtime version your functions declare but the region/plan does not support, a build step failing inside the functions folder, or IAM permission gaps on the deploying account. The fix order: local <code>npm run build</code> inside <code>functions/</code> must pass first — if it fails locally, no amount of redeploying helps.</p>
<h2>Runtime failures after a "successful" deploy</h2>
<p><b>1. The missing composite index</b> (<em>theFirestore classic</em>): a query with two range/orderBy fields needs a composite index. Firestore's error message contains a direct link that creates the index with one click — and index building takes minutes. This is not an error to "fix" in code; it is an error to click.</p>
<p><b>2. Permission-denied from security rules</b> (<em>very common</em>): rules validate every read and write. A ruleset that worked in the emulator may reject the deployed app's auth pattern (or the app may not be sending the token at all). The rule of rules: change them deliberately, test in the emulator, and never debug by making rules public — that is how Firebase projects leak.</p>
<p><b>3. Quota and plan walls</b> (<em>occasional, and confusing</em>): the no-cost Spark plan limits functions, outbound networking and some features; hitting a wall produces errors that look like bugs. The usage dashboard settles it.</p>
<h2>The honest escalation order</h2>
<p>CLI error verbatim → project/alias confirmation → local builds pass → rules emulator → indexes created and waited out → usage dashboard. If all six are clean and the failure persists, you have a genuine support case — and the repro steps to make it a good one.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Firebase CLI reference and hosting deploy docs (firebase.google.com/docs/cli), Firestore index and security-rules guides (firebase.google.com/docs/firestore), and the pricing/plan limits page (firebase.google.com/pricing).</p>"""),
("api-returns-error-diagnostic", "coding", "troubleshooting",
"Why is my API returning an error? A status-code diagnostic tree",
"401, 403, 404, 429, 5xx and the CORS illusion: what each code is actually telling you, in the order to check them.",
"""<p><b>The symptom:</b> your request fails, and the error is an alphabet soup — 401, 403, 429, 500, or a CORS wall of text. Every status code is a sentence from the server; most debugging pain is refusing to read the sentence. Here is the tree, in the order the codes deserve.</p>
<h2>401 Unauthorized — the key problem</h2>
<p>The server does not know who you are: missing header, malformed key, wrong scheme ("Bearer" missing), or a rotated/revoked token still living in an env file (<em>the single most common cause</em>). Diagnosis: print the exact request your code sends — not the one you think it sends — and compare against one made with curl from the provider's docs. We have lost count of the deploys where the code was fine and the env var was stale; this desk keeps its own provider tokens in server-side env vars precisely because tokens die (<a href="/tech/github-token-hygiene/">token hygiene</a> applies to every key you own).</p>
<h2>403 Forbidden — the permission problem</h2>
<p>Authenticated, but not allowed: the key is valid but scoped to different endpoints, the account lacks the feature, or a region/IP rule blocks it. Do not "fix" a 403 by upgrading blindly — read the provider's response body first; good APIs say <em>which</em> permission failed.</p>
<h2>404 Not Found — the address problem</h2>
<p>Version mismatch (<code>/v3/</code> where the API is now <code>/v4/</code>), a trailing slash the route does not declare, a base path duplicated (<code>/api/api/thing</code>), or an ID that simply does not exist. The URL in the failing request, read character by character, resolves most 404s without documentation.</p>
<h2>429 Too Many Requests — the pace problem</h2>
<p>You are too fast. The honest fix is respecting the limits the provider publishes — many send <code>Retry-After</code> or rate-limit headers; honour them, back off exponentially, and cache responses you already have. Retrying immediately converts a rate limit into a ban. (This desk's own data agent throttles on purpose and caches by design — the pattern scales down to hobby projects.)</p>
<h2>5xx — their problem, handled your way</h2>
<p>A server error is the provider's failure, but your handling is still yours: retry with backoff, make retries idempotent (never double-charge, never double-post), and show a human-appropriate message. Check the provider's status page before debugging your own code — a perfect codebase can do nothing about someone else's incident.</p>
<h2>The CORS illusion</h2>
<p>A wall of CORS errors in the browser console usually means "the request failed, and also CORS blocked reading the details" — the underlying 401/404/500 hides behind it. Test the identical request with curl: if curl succeeds and the browser fails, it is genuinely a CORS configuration problem; if both fail, fix the real status first. And keys that must stay secret never belong in browser code at all — proxy through a server (<a href="/tech/what-is-an-api/">what an API is</a>, <a href="/tech/api-errors-decoded/">error bodies, decoded</a>, and making the call from Python in <a href="/tech/call-api-python/">call an API with Python</a>).</p>
<p><b>Official documentation (checked 11 September 2026):</b> MDN's HTTP status and CORS references (developer.mozilla.org), RFC 9110 (HTTP semantics, rfc-editor.org), and your provider's own rate-limit and auth docs — the sentences that matter are always theirs.</p>"""),
("works-locally-fails-online", "coding", "troubleshooting",
"Why does it work locally but fail online? The six differences",
"Environment, case sensitivity, build-vs-serve, localhost URLs, dependency drift and paths — the gaps between your machine and the internet's.",
"""<p><b>The symptom:</b> the project runs beautifully on your machine and falls over deployed. This is not bad luck — your computer and a production server are different machines in every way that matters. There are six differences, and they explain nearly every case.</p>
<h2>1. Environment variables do not follow you</h2>
<p>Your <code>.env</code> file is gitignored (correctly!), so production does not have your keys — the app boots and fails on first use. Or worse, the platform has a <em>stale</em> value from months ago. Fix: list every env var the build and runtime need, set them in the platform's settings, and make the app fail loudly at startup when one is missing. Silent fallbacks to defaults are how wrong-database bugs are born.</p>
<h2>2. Case sensitivity</h2>
<p>Windows and macOS file systems are case-insensitive by default; production Linux is not. <code>import Header from './header.jsx'</code> works locally over <code>Header.jsx</code> and fails online. The same for images and data files: the case in your code must match the case on disk, exactly. If it "only fails on the server", audit case first.</p>
<h2>3. Build versus serve: the baked-at-build trap</h2>
<p>Static and front-end frameworks bake environment values at <em>build</em> time, not runtime — setting a variable on the server after building changes nothing. The classic: your production build was made months ago with old values, and no runtime setting can save it. Rebuild after every change, and know which of your values are build-time and which are runtime (<a href="/tech/website-wont-deploy-fix/">the deploy diagnostic</a> covers the publish-directory side of this).</p>
<h2>4. Hardcoded localhost</h2>
<p><code>http://localhost:3000/api</code> works on your machine and nowhere else in the universe. Search the codebase for "localhost" before every deploy; configuration belongs in env vars, and same-origin paths (<code>/api/...</code>) beat absolute URLs wherever your architecture allows.</p>
<h2>5. Dependency drift</h2>
<p>Locally you have whatever installed the month you built the project; production installs from the lockfile — or, without one, whatever is newest today. Pin dependencies, commit the lockfile, and use the same runtime version in CI as on your machine (a <code>.node-version</code>-style file, honoured by the platform).</p>
<h2>6. Paths: absolute, relative, and the missing base</h2>
<p>Absolute paths (<code>/assets/logo.png</code>) break when the app is served under a sub-path; case-sensitivity (difference #2) compounds it. Relative paths and configured base URLs survive relocation. When assets 404 in production only, this and #2 together are the culprit more often than not.</p>
<h2>The honest method</h2>
<p>Reproduce production locally once: build in production mode, serve the built output, run with empty env vars — most of these six will reproduce without deploying at all. Then fix them in the order that fails loudest. The payoff is permanent: a project that survives a clean-clone-plus-deploy is a project that deploys calmly forever. Companions: <a href="/tech/website-wont-deploy-fix/">the deployment diagnostic tree</a> and <a href="/tech/github-pages-not-showing-changes/">GitHub Pages hiding your changes</a>.</p>
<p><b>Official documentation (checked 11 September 2026):</b> your framework's environment-variables guide (Vite, Next.js and Create React App all document build-time vs runtime values), and the Twelve-Factor App's config principles (12factor.net) — the difference between your laptop and the internet, formalised.</p>"""),
])

TROUBLESHOOTING_GUIDES.extend([
("private-dns-not-working", "android", "troubleshooting",
"Why does Private DNS fail? The Android setting, diagnosed",
"Hostname formats, port-853 blocking and captive portals: why the phone's best privacy setting sometimes breaks the internet.",
"""<p><b>The symptom:</b> you set Android's Private DNS (Settings → Network → Private DNS), and either it silently reverts to "off", or the internet appears to die — apps spin, pages time out — until you switch it back. Private DNS encrypts your phone's name lookups over DNS-over-TLS; it is one of the best one-line privacy upgrades on Android, and its failures are specific and fixable. (What it is and why it matters: <a href="/tech/android-privacy-settings-checklist/">the Android privacy checklist</a>.)</p>
<h2>Likely causes, most common first</h2>
<p><b>1. The hostname is written wrong</b> (<em>the classic</em>): the Private DNS field wants a <b>provider hostname only</b> — something like <code>one.one.one.one</code> or <code>dns.google</code> — with no <code>https://</code> prefix, no slashes, and no IP address. Pasting a URL or an IP makes Android reject it or quietly fail to use it. Every provider publishes its exact hostname; copy that, the whole string, nothing else.</p>
<p><b>2. The network blocks the port</b> (<em>very common on public and workplace Wi-Fi</em>): DNS-over-TLS speaks on TCP port 853. Plenty of corporate, school, hotel and airport networks block it deliberately, because encrypted DNS defeats their filtering and their captive-portal redirects. Symptom pattern: Private DNS works on mobile data and home Wi-Fi, fails on one specific network.</p>
<p><b>3. The captive portal has not been passed</b> (<em>related, and temporary</em>): before you accept a hotel/airport login page, the network must answer plain DNS for the portal itself. With Private DNS in "strict" mode, that handshake can stall. Android usually falls back gracefully; when it does not, the fix is sequential — connect, pass the portal, then enable Private DNS.</p>
<p><b>4. The provider itself is down or rate-limiting</b> (<em>occasional</em>): free resolvers are reliable but not immortal; a provider outage looks like "the internet is broken" on every network at once. Test by switching to a second provider's hostname.</p>
<p><b>5. An always-on VPN is fighting it</b> (<em>occasional</em>): some VPN apps route or block DNS themselves; their DNS handling and Android's Private DNS can conflict, producing intermittent resolution failures. One DNS authority per device is the stable configuration — the VPN's or Android's.</p>
<h2>Diagnosis, in the right order</h2>
<p>Set the mode to the provider hostname exactly as published → test on mobile data first (no network blocking in the way) → then the problem network. If data works and Wi-Fi fails, it is the network's port 853 (cause 2), and no phone-side fiddling changes that. If it fails everywhere, check cause 1's formatting, then swap providers (cause 4). Android's private-DNS status also shows on the notification shade while it probes — "failed" versus "off" tells you whether it is trying and being blocked, or not configured.</p>
<h2>The honest trade-offs</h2>
<p>Two modes exist: <b>automatic</b> (use Private DNS when possible, fall back to plain DNS — never breaks, sometimes unencrypted) and the strict manual hostname (always encrypted, breaks on hostile networks). The desk's honest recommendation: automatic mode everywhere, strict mode on networks you trust, and the knowledge that blocking port 853 is a network-owner's policy choice — not your phone's malfunction.</p>
<h2>When this fix will not work</h2>
<p>Networks that force their own DNS through a login gateway you cannot bypass (some ISPs' hardware, some enterprises); older Android versions whose Private DNS implementation predates certain resolvers' TLS requirements; and managed/work-profile devices where policy overrides user settings entirely. On those, the honest answer is a VPN with encrypted DNS — a different tool, honestly labelled as one.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Google's Android Private DNS support notes (support.google.com), Cloudflare and Google Public DNS resolver documentation (one.one.one.one/docs, developers.google.com/speed/public-dns), and your provider's own hostname reference.</p>"""),
])
