# BRYME Tech — roadmap batch T2: Backups & data loss (3) + Storage & device health (3).
# [VERIFY] resolved 2026-09-10: phone loss/damage frequency — Asurion insurer claims data
# (1 in 4 lose/damage a phone in a year; ~72M phones lost/stolen/damaged in the US in 2018/19)
# and SquareTrade's 2018 study (66% of smartphone owners damaged a phone in the past year).
# All insurer figures dated in-text; 3-2-1 rule attributed (Peter Krogh / CISA backup guidance).

TECH_ROADMAP_T2 = [
("three-two-one-backup-rule", "safety", "guide",
"The 3-2-1 backup rule: why most people's 'backup' isn't actually one",
"Three copies, two different devices, one off site — and the honest reason the second and third numbers are the ones that save you.",
"""<p>Almost everyone believes they have a backup, and almost nobody does. What they have is a <em>copy</em> — on the same drive, in the same building, on the same account — and the day disaster arrives is precisely the day that distinction stops being pedantic. The 3-2-1 rule is the old photographer's discipline (popularised by Peter Krogh) that government agencies like CISA now recommend in their ransomware guidance, and it survives because every number in it defends against a different failure.</p>
<h2>The rule, decoded</h2>
<p><strong>Three copies</strong> of your data — the original plus two backups. <strong>Two different devices or media</strong> — never both backups on the same drive, the same laptop's disk, or the same box. <strong>One copy off site</strong> — another building, or the cloud. The origin story is photography: professionals who could not re-shoot a wedding learned that house fires and stolen camera bags were a single-point-of-failure problem, not a carelessness problem. The same logic is why CISA's ransomware guidance asks for at least one offline or immutable copy: modern ransomware specifically hunts connected backups to delete them first, so the backup that saved you has to be one the malware can't reach.</p>
<h2>Why your backup probably isn't one</h2>
<p>The common non-backups, and what defeats each: <strong>the copy on the same external drive</strong> — dies with the drive it's on (theft, fire, ransomware, or the drive itself — drives are consumables). <strong>Time Machine or File History to a drive that's plugged in constantly</strong> — better, but it's in the same building and reachable when the computer is compromised. <strong>The cloud-sync folder</strong> — this is the big one, and <a href="/tech/cloud-vs-local-backup/">the cloud-vs-local guide is dedicated to it</a>: sync is not backup, because when you delete a file (or malware encrypts one), the deletion syncs faithfully to all your copies. <strong>"The cloud provider has my files"</strong> — that's one copy on someone else's hardware; it defends against a dead laptop and against almost nothing else.</p>
<h2>What actually kills data</h2>
<p>Ranked by how often it's the culprit rather than by drama: hardware failure (drives fail without warning, and phone storage is not exempt), human deletion (the file you deleted in March and noticed in June), theft and loss (phones especially — <a href="/tech/phone-died-no-backup/">the frequency is worse than people assume</a>), software corruption and failed updates, and malware. Notice that no single backup location defends against all five — which is the entire reason the rule has three numbers instead of one.</p>
<h2>The 30-minute setup that satisfies the rule</h2>
<p>For a normal household: <strong>copy one</strong> is your computer/phone as it lives. <strong>Copy two</strong> — an automatic, continuous backup to cloud backup software or your platform's backup system (iCloud Backup, Google One device backup — device backup, not just sync storage). <strong>Copy three</strong> — an external drive, backed up on a schedule you can tolerate (monthly is realistic; weekly is better), that lives unplugged in a drawer when it isn't working. That's 3-2-1: original + cloud + offline drive, two devices, one off site. Photos get special mention because they're the irreplaceable category — <a href="/tech/what-free-apps-do-with-your-data/">know which cloud you've trusted with them</a>, and keep the drive copy anyway.</p>
<h2>The test that proves it</h2>
<p>A backup you've never restored is a hypothesis. Once, ever, try to restore something real — yesterday's version of a document, a photo, your phone onto a spare device. The restore is where backups fail (wrong app, forgotten password, sync-only copies), and finding that out on a quiet afternoon is the whole point. Backups aren't a thing you have; they're a thing you can prove work.</p>
<p><em>Sources: CISA StopRansomware guidance (multiple copies incl. offline/immutable); the 3-2-1 rule as popularised by Peter Krogh, The DAM Book. Reviewed September 2026.</em></p>""",
[("CISA — StopRansomware guidance", "https://www.cisa.gov/stopransomware"),
 ("CISA security tip: data protection & backups", "https://www.cisa.gov/news-events/news/protecting-against-ransomware")],
[("cloud-vs-local-backup", "Cloud vs local, honestly"),
 ("phone-died-no-backup", "When the phone dies"),
 ("what-free-apps-do-with-your-data", "What free apps do with data")]),

("cloud-vs-local-backup", "safety", "guide",
"Cloud storage vs. local backup: why you need both, not either",
"A sync folder protects your files from your laptop. A backup protects your files from you. They are not the same product, and the difference has a direction.",
"""<p>The most expensive misconception in personal data is that Dropbox, Google Drive, iCloud Drive or OneDrive are "backups". They're <em>sync</em> — an excellent, different thing — and the gap between the two has a direction that matters: sync protects your files from your <em>hardware</em>, while backup protects your files from <em>you</em> (and from the software acting on your behalf). You need both, and this page is the honest anatomy of why.</p>
<h2>What sync does, and does brilliantly</h2>
<p>A sync folder mirrors a directory across your devices and the provider's servers. Drop a file in on the phone; it's on the laptop and the cloud. This is real protection against a stolen laptop, a dead drive, a coffee spill — the hardware failures. Version history on the big providers even keeps prior versions for 30 days, which rescues the accidentally-overwritten document. For working files, sync is the correct tool and nobody should live without it.</p>
<h2>What sync cannot do — by design</h2>
<p>Sync's defining property is <em>obedience</em>: it reproduces whatever happens in the folder, immediately, everywhere. That means: <strong>delete a file, and the deletion propagates</strong> — to your laptop, your phone, the cloud, and (with third-party sync wired through it) your "backup" drive in the cupboard. <strong>Ransomware encrypts your files, and the encrypted versions propagate</strong> — overwriting the good versions at industrial speed. <strong>A buggy app corrupts its own data folder</strong> — and sync faithfully distributes the corruption. There's no moment at which sync says "that looks like a mistake, I'll keep the old one." Backup software, by contrast, is built around history: snapshots at points in time, retained for months, restorable as of a date. The whole discipline exists to answer the question sync cannot: <em>what did this folder look like last Tuesday?</em></p>
<h2>The local half, and why the cloud alone isn't enough either</h2>
<p>Backup in the cloud (true backup services, or your phone's device-backup) fixes the deletion problem. What it doesn't fix: <strong>the account itself</strong> — a forgotten password, a hijacked account, a terms-of-service change, a mistaken closure, or an automated ban can sever you from everything at once, and account recovery is a fragile thread when you most need it (<a href="/tech/security-questions-are-insecure/">build that thread properly</a>). <strong>Cloud economics</strong> — every terabyte is a monthly bill forever, and re-downloading a whole life's data after an outage takes days. So the local offline copy — an external drive, updated on a schedule, unplugged when done — isn't nostalgia; it's the copy that depends on no company, no subscription, and no account state. It's also the copy CISA's ransomware guidance wants, because it's the one malware can't touch.</p>
<h2>The honest minimum, assembled</h2>
<p>Working files live in sync (pick a major provider; two-factor it — <a href="/tech/two-factor-authentication-setup/">done right</a>). Devices run real backups — phone device-backup and/or cloud backup software, not just the sync folder. And an external drive gets the periodic offline copy, drawer-stored (<a href="/tech/three-two-one-backup-rule/">that's the 3-2-1 rule, quietly satisfied</a>). Total setup time: one evening. Total monthly cost: a cloud plan you were probably already paying for. The alternative cost, once, is everything with no directions back.</p>
<p><em>Sources: CISA StopRansomware guidance (offline/immutable copies); provider version-history documentation (30-day windows vary — check yours). Reviewed September 2026.</em></p>""",
[("CISA — StopRansomware guidance", "https://www.cisa.gov/stopransomware")],
[("three-two-one-backup-rule", "The 3-2-1 rule"),
 ("phone-died-no-backup", "When the phone dies"),
 ("cloud-storage-mistakes", "Cloud storage mistakes that lose files")]),

("phone-died-no-backup", "safety", "guide",
"When your phone dies with no backup: the numbers, and the 30-minute fix",
"Phones are the most-lost, most-damaged, least-backed-up computer you own. The insurer data is blunter than any scare story.",
"""<p>Here's the exercise this page replaces: think of what's actually on your phone — photos you can't re-take, the two-factor app or SMS that gates your other accounts, contacts, notes, the chat history — and then imagine the phone face-down in a lake. Now, honestly: did the backup happen? For most people the answer is a shrug, and the insurer data says the event is far more common than the complacency assumes.</p>
<h2>What the frequency actually is</h2>
<p>These figures come from insurer claims data — imperfect, but they're the only census of phone disasters that exists, and they've been consistent for a decade. <strong>Asurion</strong>, whose phone insurance underpins the big US carriers, has estimated that <strong>about one in four people lose or damage their phone in a year</strong>, and reported roughly <strong>72 million phones lost, stolen or damaged in the US in a single year</strong> (2018/19 reporting). <strong>SquareTrade's</strong> study put it even higher for damage specifically: <strong>66% of smartphone owners damaged a phone in the past year</strong>. Dates matter with insurer data and these are the years they were published — treat them as the order of magnitude, which is the part that changes behaviour: phone disaster is not a freak event; it's a rotating cast member. And the losses concentrate exactly where backup discipline doesn't: summer, travel, pockets, water.</p>
<h2>What you actually lose, ranked by pain</h2>
<p>Not the hardware — replacements are cheap and boring. <strong>The photos</strong>, obviously: the only truly unregenerable category. <strong>The 2FA</strong>, sneakily: authenticator apps and SMS-bound numbers live on that device, and losing them without preparation locks you out of your own accounts for weeks — <a href="/tech/two-factor-authentication-setup/">the 2FA guide covers the escape-hatch setup that prevents this</a>. <strong>The codes and keys</strong>: banking tokens, work logins, the Wi-Fi passwords nobody remembers. <strong>Contacts and chat history</strong>: usually restorable, occasionally not. The data was always the expensive half of the phone.</p>
<h2>The 30-minute fix, today</h2>
<p><strong>iPhone:</strong> Settings → your name → iCloud → iCloud Backup → on, and back up now (then confirm it re-runs automatically when the phone charges overnight — iCloud's free 5GB may need the small plan; photos have their own toggle worth enabling). <strong>Android:</strong> Settings → Google → Backup — device backup on, photos to Google Photos (check the quality setting), and WhatsApp's own backup if you use it. <strong>Then the second leg:</strong> every few months, a cable, a computer, and a manual copy of the camera folder to an external drive — <a href="/tech/three-two-one-backup-rule/">because one copy, wherever it lives, is not yet a backup</a>. <strong>And the 2FA leg:</strong> save your authenticator's transfer/recovery codes somewhere that isn't the phone, or you've backed up the photos and locked yourself out of everything else.</p>
<h2>For the phone that already died</h2>
<p>No backup, no recycle — but not necessarily no hope: a repair shop may recover data from a dead-but-intact phone (screen/dead-battery cases especially), a dropped-in-water phone should go straight to professionals unpowered (rice is folklore; corrosion is the killer), and a stolen phone's remote-wipe means the data question is already answered. The recovery odds are real but partial — which is the whole argument for never needing them.</p>
<p><em>Sources: Asurion claims data (1-in-4 annual loss/damage estimate; ~72M phones lost/stolen/damaged in the US, 2018/19 reporting via Forbes); SquareTrade Smartphone Damage Pulse Survey (66% damaged in past year, 2018). Reviewed September 2026 — insurer figures, years as published.</em></p>""",
[("Forbes — Asurion phone-loss data", "https://www.forbes.com/sites/christopherelliott/2019/07/06/are-you-ready-for-the-summer-surge-of-phone-damage/"),
 ("SquareTrade damage study", "https://www.squaretrade.com/press-release/mobile-myths-cost-consumers-dearly-americans-report-spending-34-billion-replacing/")],
[("three-two-one-backup-rule", "The 3-2-1 rule"),
 ("two-factor-authentication-setup", "2FA escape hatches"),
 ("cloud-vs-local-backup", "Cloud vs local, honestly")]),

("why-phones-slow-down", "android", "guide",
"Why your phone slows down over time (it's not just age)",
"Batteries, storage, app bloat and updates each add their own drag — and two of the four are fixable in an afternoon.",
"""<p>The two-year phone slowdown is so universal it feels designed — and occasionally, it literally has been. But most of the drag has mundane, partial fixes, and knowing which kind yours is decides whether the phone gets an afternoon of maintenance or a funeral. The honest breakdown: four mechanisms, in order of how often they're the culprit.</p>
<h2>One: the battery is old, and the phone is protecting itself</h2>
<p>The confirmed, documented one: lithium batteries degrade with charge cycles and years, and an aged battery can sag under the peak current a processor demands — causing shutdowns under load. Apple publicly acknowledged and now manages this with "performance management": a phone with a worn battery deliberately throttles peak performance to prevent random shutdowns. Android makers do similar things less formally. The tell-tales: slowdowns under heavy use, percentage jumps, shutdowns at 20-30%. <strong>This one is genuinely fixable</strong> — a battery replacement (cheap on most Androids, a service programme on iPhones) often restores the speed the headline claims died. Check your battery health screen before buying anything new.</p>
<h2>Two: storage is nearly full</h2>
<p>Flash storage slows down as it fills — the controller needs free space to shuffle writes efficiently, and a phone at 95% full writes like it's wading. This is the same mechanism behind <a href="/tech/storage-full-breaking-apps/">apps quietly breaking when storage runs out</a>, and both share the fix: get to 10-20% free space (offload photos, delete the video drafts, clear the cache of the worst offender apps). Storage pressure is the second most common cause and the second most fixable.</p>
<h2>Three: the software grew</h2>
<p>Apps accumulate — background services, login managers, analytics SDKs, the third app that wants to run "all the time". Each update adds polish and weight; the app that launched in 800ms in 2023 launches in 2s on the same hardware in 2026. Meanwhile the OS itself gains features the chip didn't plan for. The partial fixes: uninstall (not disable) the apps you haven't opened in a month, stop apps that don't need it from auto-updating in the background, and check the battery screen for the background drainers. A factory reset — the nuclear option — genuinely helps when the cruft is deep; do it with a fresh <a href="/tech/three-two-one-backup-rule/">backup</a> and only reinstall what you actually use.</p>
<h2>Four: it's the updates, deliberately — the scandal worth remembering</h2>
<p>The exception that proves the others: Apple was fined by France's competition authority (€25m, 2020) over the 2017 throttling disclosure — not for throttling itself, which it defended (and still does) as battery protection, but for the silence around it. The honest summary: platform makers do manage performance on aged hardware, the practice is now disclosed, and the remedy is the battery-replacement one from point one. Knowing this exists makes you a better buyer too: check the battery-health screen of any used phone before you buy it — <a href="/tech/refurbished-vs-new-tech/">the refurbished guide covers what else to check</a>.</p>
<h2>The afternoon plan, in order</h2>
<p>Battery health check (replace if degraded). Free space to 10-20% minimum. Uninstall the unused. Restart properly (it counts — <a href="/tech/why-restarting-fixes-problems/">restarts fix more than people think</a>). Then judge: if it's still slow after all four, the chip has genuinely been outrun by its software, and that's the upgrade decision — made with data instead of vibes.</p>
<p><em>Sources: Apple's published performance-management documentation (aged-battery throttling and mitigation); France's DGCCRF decision on Apple (€25m, 2020). Reviewed September 2026.</em></p>""",
[("Apple Support — iPhone performance management", "https://support.apple.com/en-us/HT208387")],
[("storage-full-breaking-apps", "The storage-full mistake"),
 ("why-restarting-fixes-problems", "Why restarting works"),
 ("refurbished-vs-new-tech", "Refurbished vs new")]),

("storage-full-breaking-apps", "android", "guide",
"The storage-full mistake that's silently breaking your apps",
"Phones misbehave for months before they admit why: no free space. The app failures it causes never announce their cause.",
"""<p>A phone that's nearly full doesn't complain clearly. It doesn't pop one dialog saying "this is about storage". Instead it produces a season of small, unrelated-seeming failures — apps that won't update, photos that won't send, chats that miss messages, a camera that lags, a phone that reboots oddly — and the owner concludes the phone is dying. Usually it isn't. It's full, and the mechanics of flash storage explain why "nearly full" behaves like broken.</p>
<h2>Why "nearly full" malfunctions</h2>
<p>Flash storage needs working room: to write a file efficiently, the controller shuffles data around, and that shuffling needs free space to happen in. Below roughly 10% free, write speeds fall off sharply — and more importantly for apps, <em>temporary</em> space starts running out: apps need scratch space to update themselves, process a photo, download an attachment before saving it, or even launch cleanly. When the scratch space isn't there, the failure surfaces as something specific and misleading: "update not completed", "message failed to send", "couldn't download", or an app that crashes on opening a large file. The phone then adds its own failure modes — clearing caches aggressively (so apps feel reset and slow), dropping message attachments, failing to record video at the worst moment.</p>
<h2>The specific failures worth recognising</h2>
<p><strong>Messaging apps</strong> (WhatsApp and cousins) silently fail to receive media or back up when storage is tight — and people discover the backup gap months later, when switching phones (<a href="/tech/phone-died-no-backup/">which is exactly when it hurts</a>). <strong>The camera</strong> records shorter clips, drops to lower quality, or refuses video outright. <strong>System updates fail</strong> — a several-gigabyte download needs several gigabytes of working room, so the phone stuck on last year's Android version may simply be a full phone. <strong>Apps "corrupt"</strong> — a mid-update storage exhaustion is a classic way an app's data ends up inconsistent.</p>
<h2>The 20-minute recovery</h2>
<p>Check what's eating the space first (Settings → Storage): the answer is almost always photos/videos, messaging-app media, and three or four apps you forgot exist. In order of least pain per gigabyte: clear the messaging apps' caches and old media <em>from inside the app</em> (WhatsApp's manage-storage tool is genuinely good); empty the "recently deleted" folders; offload the camera roll to cloud photos or a computer (<a href="/tech/cloud-vs-local-backup/">then keep a real backup, not just a sync copy</a>); uninstall — not disable — the untouched apps; and if your phone has an SD slot, move media, not apps (apps on SD cards cause their own slowdowns). Target: <strong>10-20% free, held permanently</strong> — the level at which the phone stops improvising.</p>
<h2>Keeping it from filling again</h2>
<p>The monthly two-minute habit: storage screen glance, delete the month's accumulated junk (screenshots, downloads-you'll-never-need, the video drafts). Set auto-delete on your photo cloud for device copies if it offers it. And the buying note for next time: 64GB phones are the trap — after the OS and the first dozen apps, they were full from birth; <a href="/tech/laptop-buying-ram-storage/">the buying guide does the storage maths properly</a>. A phone that keeps 20% free is a phone whose apps quietly work — which is the entire feature set people think they're paying for.</p>
<p><em>Reviewed September 2026 · general guidance based on documented flash-storage behaviour and platform storage-management tools.</em></p>""",
[],
[("why-phones-slow-down", "Why phones slow down"),
 ("free-up-storage-android", "Free up Android storage, step by step"),
 ("phone-died-no-backup", "Back up before it dies")]),

("laptop-buying-ram-storage", "windows", "guide",
"Laptop buying: the RAM and storage numbers that actually matter",
"The two specs that decide whether a laptop is still pleasant in year three — explained without a single benchmark.",
"""<p>Laptop marketing front-loads the processor name and the screen, and buries the two specifications that most decide whether the machine is still usable in three years: memory and storage. They're also the two specs most often crippled to hit a price point — and the two you usually can't upgrade later. Here's what the numbers actually mean, with the honest floors.</p>
<h2>RAM: how much, honestly</h2>
<p>RAM is the desk space your work happens on. Too small a desk and everything slows down — not dramatically, just constantly, as the system shuffles things to and from storage. <strong>4GB is not a buy</strong> in this era; it's a machine that feels old the day it's unboxed and ages fast. <strong>8GB is the genuine floor</strong> for normal life: browsing with real habits (a dozen tabs, not four), office work, streaming, messaging. It's fine — and it will feel tight within the laptop's lifetime, because software grows in only one direction. <strong>16GB is the honest recommendation</strong> for anyone keeping a laptop 4+ years, and mandatory for photo/video editing, development, or "I have 60 tabs and I'm not proud". <strong>32GB+ is professional-specific</strong> — video, virtual machines, data work — and nobody else should pay for it. The one spec-sheet trap: <strong>soldered RAM</strong>. Many thin laptops weld the memory to the board, so 8GB is 8GB forever. If the listing doesn't say upgradeable, assume it isn't — which makes buying the right amount <em>now</em> the only chance you get. (MacBooks: all soldered; choose accordingly.)</p>
<h2>Storage: type first, size second</h2>
<p>The type matters more than the number. <strong>SSD (NVMe SSD, sometimes just "SSD") is not optional</strong> — it's the difference between a machine that feels responsive and one that drinks coffee while it thinks; any new laptop still shipping spinning rust (HDD) or <strong>eMMC</strong> "storage" (the slow, small, soldered cousin) is cutting the single most felt corner. The honest sizes: <strong>128GB is the trap tier</strong> — after Windows/ChromeOS/macOS itself and the first dozen apps, it's effectively full at birth (<a href="/tech/storage-full-breaking-apps/">and full storage breaks apps</a>); <strong>256GB is the real floor</strong> for a working machine; <strong>512GB is the comfort pick</strong> for people with years of photos, games, or video; 1TB+ for media libraries and professionals. If the budget forces a choice between more RAM and more storage: RAM first, storage second — external drives and cloud photos are cheaper than memory, and there's no external RAM.</p>
<h2>The three spec-sheet traps, named</h2>
<p><strong>"8GB memory" on a machine with soldered everything and a 128GB eMMC drive</strong> — the classic budget-trap triangle; the price is real but the laptop is pre-aged. <strong>Numbers without letters:</strong> a "512GB SSD" and a "512GB eMMC" are not the same product in any way that matters — read the word, not the size. <strong>The upgradeable myth:</strong> listings that once had upgrade slots now routinely ship with everything soldered; if upgradeability matters to you, it must be stated explicitly in the listing or confirmed in a teardown review, not assumed from the good old days.</p>
<h2>The 30-second checklist</h2>
<p>16GB RAM if keeping it years, 8GB absolute floor. SSD, never eMMC or HDD. 256GB storage floor, 512GB comfort. Soldered? Then buy the final configuration now, not the upgrade-later fantasy. That's the whole spec war reduced to four lines — and it's the part that decides year three, long after the processor's launch-day benchmark has been forgotten (<a href="/tech/why-is-my-computer-slow/">and when slowness does arrive, this is the repair manual</a>).</p>
<p><em>Reviewed September 2026 · spec floors reflect current software realities; no benchmarks invented — check reviews of the specific model for thermals and screens, which specs alone don't capture.</em></p>""",
[],
[("storage-full-breaking-apps", "The storage-full mistake"),
 ("why-is-my-computer-slow", "Why the computer is slow"),
 ("refurbished-vs-new-tech", "Refurbished vs new")]),
]

TECH_ROADMAP_T2B = [
("why-restarting-fixes-problems", "windows", "guide",
"Why restarting actually fixes so many problems (the real reason, not the meme)",
"'Turn it off and on again' is engineering advice with a precise mechanism — understanding it tells you exactly which problems a restart can and can't fix.",
"""<p>"Have you tried turning it off and on again?" is funny because it works, and it works because of what a running computer actually is: not a thing, but a <em>process</em> — millions of tiny states (memory allocations, open files, cached answers, running routines) balanced in real time by software that assumes nobody ever makes a mistake. A restart demolishes that entire fragile tower and rebuilds it from clean blueprints. The meme is engineering.</p>
<h2>What accumulates while you run</h2>
<p>Four kinds of junk, all invisible. <strong>Leaked memory:</strong> programs request working memory and occasionally forget to hand it back; over days the machine hoards scraps until everything competes for what's left. <strong>Wedged processes:</strong> a crashed component inside an app can leave a half-alive process holding locks — files, devices, network connections — that nothing else may touch. <strong>Stale state:</strong> cached network settings, half-completed updates, corrupt temporary files — the system's short-term notes, which are sometimes wrong and almost never re-checked while the machine runs. <strong>The update waiting for you to stop:</strong> patches frequently can't apply to software that's running — which is why the fix for an unfixable weirdness is sometimes literally "the repair has been downloaded for two weeks; a restart installs it."</p>
<h2>Why it works on everything</h2>
<p>Because every layer of computing has the same architecture: your app, the services behind it, the OS, the router, the modem, the far-off server. Each one collects state. That's why the restart ladder solves problems at every altitude — the <em>app</em> restart (close it fully) clears the smallest tower; the <em>device</em> restart rebuilds the OS's day; the <em>router</em> reboot renews the home network's state (the ISP-facing bits too); and the remote service "restarting" is often just time passing while its engineers do exactly this. When someone says "it fixed itself overnight", the network quietly rebooted. It was always the same spell.</p>
<h2>What a restart can't fix — the honest boundary</h2>
<p>Restarting re-rolls the state, not the facts. Hardware failure (a failing drive, a worn battery — <a href="/tech/why-phones-slow-down/">the throttle-that-comes-back-after-a-battery-swap</a>) survives every reboot. Persistent corruption (a genuinely broken file) returns. Misconfiguration (a wrong setting) gets reloaded, wrong. And a full disk makes the machine slow again within hours (<a href="/tech/storage-full-breaking-apps/">that needs deletion, not a restart</a>). The diagnostic pattern worth learning: a problem a restart <em>cures permanently</em> was state. A problem that <em>returns every time</em> is configuration, resource, or hardware — and now you know which list it's on.</p>
<h2>The professional habit, adopted</h2>
<p>IT support's version of this page is a restart schedule: phones weekly (they're computers that never sleep), computers monthly-ish and after any weirdness, routers quarterly. It's not superstition — it's scheduled state-clearing, the digital equivalent of closing and reopening the shop so the floors can be mopped. The cheapest repair in computing is the one performed before the symptom, on a schedule, while nothing is wrong.</p>
<p><em>Reviewed September 2026 · general explanation; no benchmarks invented.</em></p>""",
[],
[("why-phones-slow-down", "Why phones slow down"),
 ("storage-full-breaking-apps", "The storage-full mistake"),
 ("why-is-my-computer-slow", "Why the computer is slow")]),

("refurbished-vs-new-tech", "buying", "guide",
"Refurbished vs new: when refurbished tech is actually the smarter buy",
"Not 'used' — refurbished. The distinction is a process, and knowing the process tells you exactly when the discount is safe to take.",
"""<p>The case for refurbished is easy: last year's flagship, professionally inspected, at 20-40% off, often with a warranty — is frequently the best value in consumer tech. The case against is also easy: "refurbished" is a label with no legal definition in most places, and underneath it can sit anything from a factory-standard rebuild to a wiped phone with a new screen protector. The skill is buying the process, not the price.</p>
<h2>What "refurbished" should mean</h2>
<p>The genuine article follows a real pipeline: returned or traded-in device, <strong>diagnosed, repaired with proper parts, data-wiped to standards, battery health checked (and replaced below a threshold), Cosmetically graded, and re-boxed with a warranty</strong> — typically 12 months from the manufacturer (Apple Certified Refurbished, Samsung Certified Re-newed, Dell/Lenovo Outlet) or the retailer (Back Market, CeX-style retailers, reputable refurbishers). Manufacturer-refurbished is the gold standard: original parts, factory QA, indistinguishable from new, often with the same warranty as new. Retailer-refurbished varies with the retailer. "Seller refurbished" on marketplaces varies with the seller — which is to say, with luck.</p>
<h2>The battery, the grade, and the questions</h2>
<p>Three checks separate the smart buy from the regret. <strong>Battery:</strong> on phones and laptops the battery is the wearing part — a "refurbished" phone with a five-year-old battery at 79% health is a repair you've pre-ordered. Ask for the battery's health percentage or the refurbisher's replacement threshold; good refurbishers publish one. <strong>The grade system (A/B/C):</strong> grades describe cosmetics, not function — A means barely a scuff; C means visibly lived-in. Grade C is where the bargains hide if you don't care about scratches; the function warranty should be identical. <strong>The warranty and return window:</strong> the single best proxy for a refurbisher's confidence. Twelve months and 30 days of returns is a professional operation; 90 days and "sold as seen" is a gamble with paperwork.</p>
<h2>What to buy refurbished, and what not to</h2>
<p><strong>Great refurbished buys:</strong> phones (the depreciation curve is brutal and the hardware mature — two-year-old flagships outclass new mid-rangers), laptops for students and office work (business-grade ThinkPads and Dells are built for refurbishment and priced accordingly), and tablets. <strong>Think twice:</strong> storage drives (HDDs and SSDs wear with use — history matters more than price), anything where the warranty period is your entire safety net (expensive cameras with shutter wear), and anything too new to have a refurbisher ecosystem. And the ecosystem note: <a href="/tech/laptop-buying-ram-storage/">check the RAM/storage reality before the discount dazzles you</a> — a cheap refurb with 8GB soldered and 128GB eMMC is a pre-aged laptop at any price.</p>
<h2>The 60-second purchase protocol</h2>
<p>Manufacturer or big-name refurbisher first. Warranty 12 months, returns 30 days, both in writing. Battery threshold stated (phones/laptops). Grade honestly described with photos of the actual grading scale. Payment by a method with buyer protection. That's the whole discipline — and when it's followed, the honest answer to "refurbished or new" is: refurbished, more often than the stigma admits. The stigma is twenty years old; the process is not (<a href="/tech/laptop-buying-ram-storage/">the RAM-and-storage maths completes the purchase</a>).</p>
<p><em>Reviewed September 2026 · warranty terms and grading scales vary by refurbisher — theirs is the document that governs.</em></p>""",
[],
[("laptop-buying-ram-storage", "The RAM and storage maths"),
 ("why-phones-slow-down", "Battery health matters"),
 ("phone-buying-specs-that-matter", "Phone specs vs marketing")]),

("what-free-apps-do-with-your-data", "safety", "guide",
"What 'free' apps are actually doing with your data",
"The price of a free app isn't zero — it's you. Here's the trade, in the industry's own disclosure language, and the controls most people never open.",
"""<p>Free apps are free the way broadcast TV is free: the product is audience attention, and increasingly, audience <em>information</em>. The industry discloses what it does — in privacy policies and the standardized data-safety labels app stores now require — and the disclosure, read plainly, describes four businesses running under the icon you tapped. Here's what's actually going on, and the controls that exist.</p>
<h2>The four businesses inside a free app</h2>
<p><strong>Advertising:</strong> the visible one — ads shown in-app, targeting built from whatever the app's SDKs can see: your device identifiers, approximate location, the other apps installed, sometimes the screen you're on. <strong>Data brokerage:</strong> many apps pass information to third-party data companies who assemble it across thousands of apps into profiles — the privacy-policy phrase is "sharing with partners", and the partners are the tell. <strong>Analytics:</strong> usage measurement, legitimately useful to developers and rarely limited to the minimum. <strong>And the model-training era:</strong> the newest line in modern privacy policies — user content and interactions "used to improve our services", which increasingly means training machine-learning systems on your photos, documents or prompts. Each of these can be legitimate; the pattern to notice is that they're all incentives to collect more than the app needs to function.</p>
<h2>How to read the labels honestly</h2>
<p>Both major app stores now carry standardized data labels, and the reading order matters. On <strong>Apple's "App Privacy" labels</strong>: "Data Linked to You" is the identity-attached collection; "Data Not Linked to You" is aggregate-but-still-collected; "Data Used to Track You" is the one that feeds cross-app advertising. On <strong>Google's "Data safety" section</strong>: the reveals are in the questions it answers — does the app share data with third parties, can you request deletion, is data encrypted in transit. The label that matters most is the absence: an app collecting contacts, location and photos while offering nothing but a torch function has told you its business model in one screen.</p>
<h2>The controls that actually exist</h2>
<p>Platform settings have quietly become powerful: <strong>permission review</strong> (Android and iOS both let you grant location "only while using", strip background access, and see which apps touched sensitive permissions — <a href="/tech/android-app-permissions/">the Android walkthrough is on this desk</a>); <strong>tracking controls</strong> — iOS's App Tracking Transparency (the "ask not to track" switch), Android's ad-ID reset and deletion tools; <strong>account-level dashboards</strong> — Google and Facebook both offer activity controls and ad-personalisation switches that turn down, though not off, the profiling; and the nuclear-but-effective option — paid alternatives, which convert you from product to customer for a few pounds a month.</p>
<h2>The working rule</h2>
<p>Match the data to the function: a maps app needs location; a game does not. Prefer apps whose business you can see (paid, subscription with a visible service) for the categories that touch your life most — photos, messages, documents, health. And treat "free" as a pricing question with a hidden currency: not "what does this cost", but "what does this cost per photo, per contact, per location ping, for as long as I use it?" Once the trade is visible, most people start choosing deliberately — which is the entire point of the disclosure.</p>
<p><em>Sources: app-store data-label documentation (Apple App Privacy labels; Google Play Data safety); platform privacy-control documentation. Reviewed September 2026 — label formats evolve; the reading order survives.</em></p>""",
[("Apple — App privacy details on the App Store", "https://developer.apple.com/app-store/app-privacy-details/"),
 ("Google Play — Data safety section", "https://support.google.com/googleplay/android-developer/answer/10787469")],
[("android-app-permissions", "Android permissions, walkthrough"),
 ("browser-privacy-settings", "Browser privacy settings"),
 ("smart-speaker-privacy", "What smart speakers hear")]),
]
