# BRYME Tech — roadmap batch T3: Software alternatives (3) + AI tools (3) + Web & hosting (3).
# AI cluster refresh-checked 2026-09-10: pricing tiers corroborate the desk's first-party check
# of 2026-09-09 (ChatGPT Free/$8 Go/$20 Plus/$100+$200 Pro; Claude Pro $20 [$17 annual]/Max
# $100+$200; Google AI Plus $4.99/Pro $19.99/Ultra $99.99+$199.99). Model NAMES conflict across
# aggregators → described by stable product-line names, versions deliberately not pinned.
# Free-tier limits: providers publish no fixed numbers → behaviour described, not counted.

TECH_ROADMAP_T3 = [
("free-software-alternatives", "tools", "guide",
"Free alternatives to expensive software that people don't know exist",
"The desk's own canon — photo, audio, video, office, passwords and messaging — every one opened and used, not scraped from a listicle.",
"""<p>There's a tier of free software that quietly outclasses the subscriptions people assume they need — not "free trials", not crippled demos: finished, maintained, sometimes open-source tools that professionals genuinely use. This desk has reviewed and compared them first-hand across a whole shelf; this page is the single map of the canon, category by category.</p>
<h2>Photos: you may not need that subscription</h2>
<p><strong>Photopea</strong> (<a href="/tech/photopea-vs-photoshop/">the full first-hand comparison is here</a>) is a browser-based editor that opens Photoshop's own file formats and covers most of what most people ever did in Photoshop — for free. And the ground shifted again when <strong>Affinity</strong> went free (<a href="/tech/affinity-now-free/">what that actually includes</a>), putting a professional-grade creative suite in everyone's hands. For quick edits and collabs, our <a href="/tech/pixlr-vs-canva/">Pixlr-vs-Canva</a> and <a href="/tech/polotno-studio-vs-canva/">Polotno comparisons</a> sort the lightweights.</p>
<h2>Office: LibreOffice, and the free web suites</h2>
<p><strong>LibreOffice</strong> is the open-source office suite that reads and writes Word, Excel and PowerPoint formats — free, offline, no account, no telemetry. Combined with Google Docs and Microsoft's free web Office, the honest position is that paying for office software is now a choice about features and ecosystem, not access (<a href="/tech/google-docs-vs-word-vs-notion/">which suite fits which workflow is its own comparison</a>).</p>
<h2>Video and audio: the professional free tier is real</h2>
<p><strong>DaVinci Resolve</strong> — Blackmagic's professional editor and colour grader — ships a genuinely usable free version that's not a watermark demo. <strong>OBS Studio</strong>, open-source, is the streaming and screen-recording standard that paid competitors reskin. <strong>Audacity</strong> remains the audio editor equivalent of a hammer: unfashionable, effective, everywhere.</p>
<h2>Passwords and messaging: the security canon</h2>
<p><strong>Bitwarden</strong> (<a href="/tech/bitwarden-free-password-manager/">reviewed honestly here</a>) free tier covers unlimited passwords on unlimited devices — the "free password manager can't be trusted" take never survived contact with it (<a href="/tech/password-manager-or-browser/">manager vs browser-built-in, compared</a>). <strong>Signal</strong> (<a href="/tech/signal-vs-whatsapp/">the privacy comparison</a>) is the messaging app whose encryption protocol the commercial apps adopted.</p>
<h2>Workspaces and AI: the free floors are higher than advertised</h2>
<p><strong>Notion's free plan</strong> (<a href="/tech/notion-free-plan/">what it includes and withholds</a>) runs a personal workspace indefinitely, and the <a href="/tech/chatgpt-claude-alternatives/">AI assistants' free tiers</a> have become useful daily tools (<a href="/tech/free-ai-tools-worth-using/">where each free tier actually ends</a>). And when a "free" comparison itself is trying to sell you something, that's the tell — <a href="/tech/plasfy-vs-canva/">we've caught listicle-shaped marketing on this desk before</a>.</p>
<h2>The rule that keeps this honest</h2>
<p>Free software isn't a charity; it's three business models — open source (community or foundation-funded), freemium (the free tier is the advertisement), and platform loss-leaders (Google wants you in the ecosystem). Knowing which one you're using tells you what changes when it doesn't: open source survives its company; freemium tightens; loss-leaders pivot. Choose accordingly for the tools your work depends on — and check this shelf first, because every recommendation on it was opened, used and argued with before it earned a link.</p>
<p><em>Reviewed September 2026 · free-tier terms shift; the comparisons on this desk are re-opened on republish.</em></p>""",
[("LibreOffice", "https://www.libreoffice.org/"),
 ("OBS Studio", "https://obsproject.com/")],
[("photopea-vs-photoshop", "Photopea vs Photoshop"),
 ("affinity-now-free", "Affinity went free"),
 ("bitwarden-free-password-manager", "Bitwarden, honestly")]),

("grammarly-alternatives-compared", "tools", "guide",
"Grammarly alternatives: free and paid, honestly compared",
"Grammarly's free tier is deliberately thin. Depending on what you actually need, the free alternatives now cover more ground — and the paid gaps have narrowed.",
"""<p>Grammarly won the grammar-checker name recognition war, and its free tier is built like a funnel: spelling and basic grammar included; tone, clarity rewrites, plagiarism and the fuller rewording engine held back for the subscription. That's a legitimate business model — but it means "Grammarly" and "free Grammarly" are different products, and plenty of writers never need the paid one. Here's the honest field, checked September 2026.</p>
<h2>LanguageTool: the best free default</h2>
<p><strong>LanguageTool</strong> is the free alternative that most people actually want: core grammar and spelling with no meaningful word-count ceiling, <strong>30+ languages</strong> (Grammarly is English-centric), browser extensions that work across Gmail, Docs and most web editors, and an open-source core you can inspect. Style and "picky" rules sit behind its own premium tier, but the free layer is a complete product, not a teaser — for multilingual writers it isn't just the value pick, it's the only pick.</p>
<h2>Hemingway Editor: the readability pass</h2>
<p><strong>Hemingway</strong> (free, web and desktop) doesn't do grammar at all — it scores readability and names the disease: passive voice, adverb fog, sentences that need a machete. Grammarly polishes sentences; Hemingway tells you which ones to delete. It pairs with any checker rather than competing, and the free web version covers everything most drafts need.</p>
<h2>ProWritingAid and QuillBot: the specialists</h2>
<p><strong>ProWritingAid</strong>'s free tier (~500 words per check) goes deeper on style analysis than Grammarly free — overused words, sentence variety, pacing — aimed at authors and long-form writers who'll trade a word cap for a real critique. <strong>QuillBot</strong> is the paraphraser: free-tier rewording with tighter limits, useful for untangling your own clumsy paragraphs and for nothing else. Grammarly Premium's domain — tone detection, full-sentence rewrites, plagiarism — remains the most integrated single package if you publish professionally all day; the honest gap is that the free ecosystem now covers maybe 80% of that for nothing.</p>
<h2>The decision, by need</h2>
<p><strong>Multilingual or free-forever:</strong> LanguageTool. <strong>Clearer, tighter prose:</strong> Hemingway alongside any checker. <strong>Deep style critique on long drafts:</strong> ProWritingAid (free tier, paid for novels). <strong>Professional publishing pipeline with tone and plagiarism in one pane:</strong> that's the case for paying for something — Grammarly Premium or ProWritingAid Premium, whichever's interface you'll actually keep open. And the desk's own trick, free: run a draft through LanguageTool <em>and</em> Hemingway — two minutes, different diseases, better than either premium tool at only its own job (<a href="/tech/free-software-alternatives/">the wider free-software canon is on this desk</a>).</p>
<p><em>Free tiers checked September 2026 — word caps and feature lines shift with pricing seasons; the product pages are the authority on the day.</em></p>""",
[("LanguageTool", "https://languagetool.org/"),
 ("Hemingway Editor", "https://hemingwayapp.com/")],
[("free-software-alternatives", "The free-software canon"),
 ("notion-free-plan", "Notion's free plan"),
 ("free-ai-tools-worth-using", "Free AI, honestly capped")]),

("google-docs-vs-word-vs-notion", "tools", "guide",
"Google Docs vs Microsoft Word vs Notion: which actually fits your workflow",
"Not a feature fight — a category fight. They're three different tools that happen to all hold text, and the right answer depends on what the text is for.",
"""<p>"Docs vs Word vs Notion" gets argued like a brand war, which misses the point: they're different instruments. <strong>Docs</strong> is a collaborative blank page. <strong>Word</strong> is a document factory with forty years of formatting obligations. <strong>Notion</strong> is a workspace where pages are one object type among databases, boards and wikis. Choosing wrong doesn't lose you features — it costs you the workflow you actually have.</p>
<h2>Google Docs: the collaborative default</h2>
<p>Docs is unbeatable at one thing: <strong>several people writing in the same document at once</strong> — suggesting, commenting, version-historied, zero setup, free. If your text is alive (drafts, notes, team docs, anything with a comment thread), Docs is the answer and Word is a paperwork tax. Its ceiling: long, format-heavy documents get unwieldy, offline is workable but second-class, and "finished document that must look exactly right" is where it hands off to Word.</p>
<h2>Microsoft Word: the document standard</h2>
<p>Word remains the format the professional world expects to receive — CVs, legal, academic submissions, anything with page layouts, footnotes, tables of contents and a printer at the end. The free web version covers real work, and Microsoft 365 adds the desktop app where the heavy formatting lives. Word's weakness is the inverse of Docs': live co-writing works, but it never feels native, and as a catch-all for notes and plans it's a filing cabinet used as a desk.</p>
<h2>Notion: the workspace, not the document</h2>
<p>Notion isn't competing on writing at all — it's where text becomes <em>structure</em>: pages nested in pages, databases with views, wikis, project trackers with the docs living beside the tasks. Its free plan is genuinely functional for personal use (<a href="/tech/notion-free-plan/">exactly what it includes and withholds</a>), and the cost of that power is the learning curve plus the lock-in-shaped dependency: your thinking slowly becomes Notion-shaped, which is fine until you need out.</p>
<h2>The decision, by the job</h2>
<p><strong>Writing together:</strong> Docs, full stop. <strong>A document to hand someone formal:</strong> Word. <strong>Organising a life or a team's knowledge:</strong> Notion. <strong>And the mix most people actually settle on:</strong> draft in Docs, deliver in Word, track everything in Notion — tools are cheap now, loyalty is the only expensive part. One working rule worth stealing: keep the <em>sources of truth</em> (policies, reference docs) somewhere durable and searchable, keep the <em>messy middle</em> wherever speed lives, and export a clean copy at every finish line (<a href="/tech/cloud-vs-local-backup/">because every cloud should have a drawer copy</a>).</p>
<p><em>Reviewed September 2026 · free-tier lines per vendor pages; features shift quarterly.</em></p>""",
[("Microsoft 365 for the web — free", "https://www.microsoft.com/en-us/microsoft-365/free-office-online-for-the-web"),
 ("Notion pricing", "https://www.notion.com/pricing")],
[("notion-free-plan", "Notion free plan, honestly"),
 ("free-software-alternatives", "The free-software canon"),
 ("free-ai-tools-worth-using", "Free AI, honestly capped")]),

("chatgpt-vs-claude-vs-gemini", "ai", "guide",
"ChatGPT vs Claude vs Gemini: an honest, non-hyped comparison",
"Pricing verified, model lines named without version-number theatre, and the strengths stated as trade-offs — including the ones each company would rather not headline.",
"""<p>Every AI comparison is a time capsule, so this one opens with its expiry date: <strong>written September 2026</strong>, prices verified against the providers' own pages and the model lines described by name — not version number, because the versions rotate quarterly while the page you're reading doesn't. What survives the rotation is each assistant's <em>shape</em>: what it's good at, what it costs, and what its free tier is for.</p>
<h2>The pricing, side by side (verified September 2026)</h2>
<p><strong>ChatGPT (OpenAI):</strong> Free tier; <strong>Go</strong> at $8/month; <strong>Plus</strong> at $20; <strong>Pro</strong> at $100 and a $200 tier. <strong>Claude (Anthropic):</strong> Free tier; <strong>Pro</strong> at $20 (about $17 monthly on annual billing); <strong>Max</strong> at $100 and $200 for the heavy usage tiers. <strong>Gemini (Google):</strong> free tier; <strong>AI Plus</strong> at $4.99 — the cheapest paid entry of the three; <strong>AI Pro</strong> at $19.99; <strong>AI Ultra</strong> at $99.99 and $199.99. All three bundle extras differently — Google's tiers ride on One storage, OpenAI's upper tiers carry the creative tools and highest limits, Anthropic's carry expanded usage of its coding and agent tooling. The one honest buying note: free tiers first. A week of real use costs nothing and beats every review (<a href="/tech/free-ai-tools-worth-using/">including ours — here's where the free tiers end</a>).</p>
<h2>The shapes, honestly</h2>
<p><strong>ChatGPT</strong> is the everything-store: voice, image generation and analysis, the widest third-party plugin ecosystem, and the best-polished mobile apps. Its weakness is the flip side of being everything — the assistant that's part of a hundred features is rarely the deepest at any one, and the free tier's flagship access is the most metered of the three. <strong>Claude</strong> is the writer's and builder's pick: long documents handled natively, prose that needs less editing, and — for the technical — the coding and agent tooling that professionals have quietly adopted fastest. Its free tier runs on rolling usage windows that run out sooner than you'd like on a working day. <strong>Gemini</strong> is the context-length and integration play: enormous document windows, and living inside Gmail, Docs and Search where your stuff already is — with the cheapest paid entry price. Its weakness is the same integration: your use of it is woven into Google's account ecosystem, and the data settings deserve a read (<a href="/tech/ai-assistant-data-training-settings/">we checked the training-settings question here</a>).</p>
<h2>How to choose without the hype</h2>
<p>Ignore benchmarks for a week; they measure a moving target and your prompts aren't the benchmark's prompts. Instead: take one real task you do weekly — a document you draft, code you maintain, research you sift — and run it through all three free tiers. The winner for <em>your</em> work is usually obvious inside five prompts, and the paid question only matters after the free tier has earned it. Our deeper dives: <a href="/tech/gemini-vs-chatgpt/">Gemini vs ChatGPT</a>, <a href="/tech/deepseek-vs-chatgpt/">the DeepSeek value case</a>, <a href="/tech/arena-ai-vs-chatgpt/">what Arena's head-to-head testing actually shows</a>, and <a href="/tech/chatgpt-claude-alternatives/">the wider alternatives map</a>.</p>
<p><em>Pricing verified September 2026 against OpenAI, Anthropic and Google's own plan pages; model lines described by name (versions rotate quarterly — check the provider's model page on the day). This page gets a refresh check before every republish.</em></p>""",
[("OpenAI — ChatGPT pricing", "https://openai.com/chatgpt/pricing/"),
 ("Anthropic — pricing", "https://www.anthropic.com/pricing"),
 ("Google One — AI plans", "https://one.google.com/about/ai-plans/")],
[("gemini-vs-chatgpt", "Gemini vs ChatGPT, deeper"),
 ("free-ai-tools-worth-using", "Where free tiers end"),
 ("ai-assistant-data-training-settings", "Training settings, checked")]),

("ai-useful-vs-hype", "ai", "guide",
"AI tools that are actually useful vs. the ones that are just hype",
"A working test for the 'AI-powered' label — five categories that earn their keep, four that don't, and the question that sorts any new tool in a minute.",
"""<p>Every app now has AI in it the way every snack once had "natural" on the label — as an incantation, not an ingredient. This desk's AI coverage has one house rule: no theatre. So here's the honest sort, offered as opinion and analysis, of which AI tools change what you can do and which just changed their own pricing page.</p>
<h2>The five that earn their keep</h2>
<p><strong>1. Drafting partner.</strong> The assistant that turns your bullet points into a first draft — the single highest-value everyday use, because the draft exists to be argued with, and arguing is what the models do well (<a href="/tech/chatgpt-vs-claude-vs-gemini/">any of the big three does this; the differences are editing time</a>). <strong>2. Code help, honestly used.</strong> Explaining an unfamiliar error, writing the boilerplate you've written forty times, reviewing a diff. The failure mode — trusting generated code you can't read — is a you-problem the tool can't fix (<a href="/tech/how-to-read-an-error-message/">the error-message skill still comes first</a>). <strong>3. The summariser with a verification habit.</strong> Long documents to a working summary is a genuine superpower — with the rule that anything you'll act on or repeat gets checked at its source, because summarisers are confident about details. <strong>4. The learning partner.</strong> "Explain this to me three ways, then quiz me" is the best free tutor ever shipped — and the one use where the mistakes don't matter, because you're checking against the course material anyway. <strong>5. Data janitor.</strong> Reformatting, extracting, converting — the tedious middle of office life, done in seconds with a paste and one instruction.</p>
<h2>The four that are mostly label</h2>
<p><strong>The "AI-powered" note-taker</strong> that summarises your meetings: the summary is real, the promise that you'll read it isn't — it's a transcript with extra steps unless it changes what you do after. <strong>AI photo "enhancers"</strong> that hallucinate detail into your images: impressive demos, uncanny outputs, unusable for anything you care about. <strong>Chatbots bolted onto support pages</strong> to deflect tickets rather than answer questions — you've met them; you've hated them. <strong>And the AI-feature upcharge:</strong> the app you pay for that now wants a further fee for the same product with a chat box — <a href="/tech/free-ai-tools-worth-using/">the free tiers usually cover the same need</a>, which tells you what the feature actually costs.</p>
<h2>The one-minute test</h2>
<p>When a new AI tool crosses your desk, ask three things. <strong>One: does it give me a draft I can check, or an answer I have to trust?</strong> (Drafts are useful; trust-me-answers are how errors get published.) <strong>Two: what does it cost when it's wrong?</strong> (Learning partner: nothing. Legal brief: everything.) <strong>Three: is the AI doing the task or decorating it?</strong> Strip the label and ask what remains — if the answer is "a slower app with a chat box", you've met the hype category. The tools that pass all three are already on this desk's AI shelf, re-opened on every republish — because this is the one category where even honest reviews have an expiry date.</p>
<p><em>Opinion and analysis, offered as such · reviewed September 2026.</em></p>""",
[],
[("chatgpt-vs-claude-vs-gemini", "The big three, compared"),
 ("free-ai-tools-worth-using", "Free AI, honestly capped"),
 ("ai-assistant-data-training-settings", "Training settings, checked")]),

("free-ai-tools-worth-using", "ai", "guide",
"Free AI tools worth using (and where the free tier actually ends)",
"Every major AI assistant has a free tier — and each one ends differently. How the caps behave, what they're good for, and how to test where yours runs out.",
"""<p>The free tiers of the major AI assistants have quietly become daily-driver tools — and each one runs out in a different way. This page maps the shapes honestly: what each free tier is good for, how its limits behave (no invented numbers — the providers don't publish fixed ones, and third-party counts conflict), and the working strategy for living free. Checked September 2026; this page has the shortest expiry of anything on the desk.</p>
<h2>ChatGPT free: the metered everything-store</h2>
<p>OpenAI's free tier gives limited access to the current flagship model with the full app experience around it — voice, image analysis, the works — but flagship messages are <strong>metered on a rolling window</strong>, and when the meter runs out, the assistant quietly hands you to a smaller, faster model until the window refreshes. You're never locked out; you're <em>downgraded</em>. Behaviour to expect: a burst of excellent answers, then subtler ones. Best free use: varied everyday tasks, voice, and trying the ecosystem before paying (<a href="/tech/chatgpt-vs-claude-vs-gemini/">pricing if you do: $8 Go, $20 Plus</a>).</p>
<h2>Claude free: the working writer's window</h2>
<p>Anthropic's free tier runs its flagship-class models on <strong>rolling usage windows that flex with demand</strong> — busy hours burn the allowance faster, and when it's gone, it's gone until the window resets. No smaller-model fallback; just a polite wall. Best free use: long-form writing, long documents (Claude handles big files natively), and the draft-and-revise loops where its prose needs the least editing. The honest catch: a working afternoon can spend a free tier by lunch, which is why the $20 Pro tier is the one free users graduate to first.</p>
<h2>Gemini free: the generous generalist</h2>
<p>Google's free tier runs its Flash-class model with the most forgiving limits of the three — no published cap, throttling rather than walls, plus the integration superpower: it lives inside Gmail, Docs, Drive and Search where your material already is. Trade-offs: the free model is a class below the paid flagship for hard reasoning, and the integration is also the data relationship (<a href="/tech/ai-assistant-data-training-settings/">review the training settings — we did</a>).</p>
<h2>The supporting cast, briefly</h2>
<p><strong>Perplexity</strong> — search-style answers with citations; free tier covers unlimited basic searches with a small daily quota of its deeper Pro mode: the free research tool of record. <strong>Microsoft Copilot</strong> — the GPT-class assistant with web grounding, free, woven into Windows and Bing; caps exist, throttles politely. <strong>DeepSeek</strong> — the free-and-cheap challenger whose consumer app is genuinely free (<a href="/tech/deepseek-vs-chatgpt/">the value case, examined</a>); treat data-sharing assumptions accordingly. <strong>And the non-chatbot free AI that's quietly excellent:</strong> the models inside Google Docs' writing help and Notion's AI tier — free enough to try, billed enough to notice (<a href="/tech/notion-free-plan/">Notion's free line, exactly drawn</a>).</p>
<h2>The strategy that works</h2>
<p>Don't marry one free tier — <strong>rotate by task</strong>: Claude free for the writing session, ChatGPT free for the everything-else afternoon, Gemini free for anything that lives in Google, Perplexity for research with receipts. The rotation isn't a hack; it's what the pricing actually models — each provider is subsidising a different kind of试用 usage. And the honest end-of-tier ritual: when you hit the same wall three days running, that's the market telling you which subscription your actual usage wants. Buy the one you ran out of, not the one with the best commercial (<a href="/tech/ai-useful-vs-hype/">and keep the hype test handy</a>).</p>
<p><em>Checked September 2026 · free-tier limits are deliberately unpublished and change without notice — the behaviours above are the durable part; numbers are not.</em></p>""",
[("OpenAI — ChatGPT pricing", "https://openai.com/chatgpt/pricing/"),
 ("Anthropic — pricing", "https://www.anthropic.com/pricing"),
 ("Google One — AI plans", "https://one.google.com/about/ai-plans/")],
[("chatgpt-vs-claude-vs-gemini", "The big three, compared"),
 ("ai-useful-vs-hype", "The useful-vs-hype test"),
 ("ai-assistant-data-training-settings", "Training settings, checked")]),

("free-vs-paid-hosting", "web-and-hosting", "guide",
"Free hosting vs. paid hosting: what actually changes",
"Static free hosting is the best deal in tech — until you need email, always-on compute or someone to call. The honest line, drawn from running this site.",
"""<p>This website runs on free hosting. It's fast, always on from the visitor's perspective, costs nothing monthly, and serves every page you're reading. That opening sentence is the whole argument against reflexively paying for hosting — and the rest of this page is about where the free tier's honest edges are, because they're real and they're specific.</p>
<h2>What free hosting genuinely is now</h2>
<p>The modern free tier isn't the ad-plastered subdomain of twenty years ago. <strong>GitHub Pages, Cloudflare Pages, Netlify and Render</strong> (which hosts this desk — <a href="/tech/where-to-host-website-for-free/">the first-hand walkthrough is here</a>) serve static sites and light apps on global CDNs with HTTPS, custom domains and no ads. For the vast majority of websites on Earth — portfolios, small business pages, documentation, content sites like this one — free static hosting is not a compromise; it's the correct engineering (<a href="/tech/render-static-deploy/">our own deploy, step by step</a>).</p>
<h2>The free tier's real edges</h2>
<p><strong>Cold starts and sleep:</strong> free <em>application</em> hosting (as opposed to static) usually spins down when idle — first visitor after a quiet hour waits seconds. Static sites don't have this problem; free server apps do. <strong>Bandwidth and build caps:</strong> generous but real; a viral month can bump them. <strong>No email:</strong> the big one nobody mentions — free hosting can't give you <em>you@yourdomain.com</em>; email needs its own (cheap, but not free) arrangement. <strong>No support line:</strong> when it breaks, the documentation is the support. <strong>Platform dependency:</strong> free tiers change terms on the provider's schedule (<a href="/tech/custom-domain-dns-order/">own your domain so a provider pivot is a chore, not a catastrophe</a>).</p>
<h2>What paying actually buys</h2>
<p><strong>A few dollars a month</strong> (basic shared hosting or a small VPS) buys: always-on compute, resources you control, email hosting possibilities, and someone's support queue. <strong>Managed platforms ($10-30)</strong> buy: backups, staging, updates handled for you — worth it for WordPress-type sites where maintenance is the job. <strong>Enterprise money</strong> buys: compliance, SLAs, dedicated infrastructure — real for businesses, irrelevant for a portfolio. Notice what's <em>not</em> on the list: speed and reliability for small static sites — the free CDN tiers already deliver those, which is the quiet scandal of every "you need premium hosting for speed" sales pitch.</p>
<h2>The decision by site type</h2>
<p><strong>Portfolio, docs, content site, small business brochure:</strong> free static hosting, custom domain, done — spend the savings on the domain and a good <a href="/tech/domain-names-explained/">registration setup</a>. <strong>Dynamic app with users:</strong> free tier to start, first paid tier when traffic or uptime demands it. <strong>WordPress-family site you don't want to admin:</strong> managed hosting, and worth every cent. <strong>Email at your domain:</strong> budget for it separately, always. The honest summary: pay for hosting when you're paying for a <em>specific, named</em> capability — email, always-on compute, maintenance labour — never for vague "faster, better" promises the free tier already delivers. That's not frugality; it's knowing what the money buys (<a href="/tech/why-your-website-is-slow/">especially before blaming hosting for a slow site</a>).</p>
<p><em>Written from first-hand experience running this site on a free tier · reviewed September 2026.</em></p>""",
[],
[("where-to-host-website-for-free", "Hosting free, first-hand"),
 ("render-static-deploy", "Our static deploy, step by step"),
 ("why-your-website-is-slow", "Why sites are actually slow")]),

("why-your-website-is-slow", "web-and-hosting", "guide",
"Why your website is slow: the real causes, not the guessed ones",
"Websites have exactly six speed problems, ranked by how often they're the culprit. Measure first, blame second — the fixes are different for each.",
"""<p>Slow websites get "fixed" in the wrong place constantly — people upgrade hosting when the problem is a 4MB hero image, or rip out a feature when the problem is a font. Site speed has a short list of real causes, and they're rankable by frequency. Measure first (Google's PageSpeed Insights or the browser's Lighthouse — free, thirty seconds), find your cause on this list, fix that one.</p>
<h2>Cause one: images (the usual culprit)</h2>
<p>Oversized images cause more slow sites than every other cause combined. A phone photo is 3-6MB; a webpage needs that same image at 100-300KB. The fixes are mechanical: resize to the display size, compress (modern formats like WebP/AVIF if your stack allows, JPEG at quality ~80 if not), and lazy-load everything below the fold. A site that does only this is usually transformed — it's <a href="/tech/free-up-storage-android/">the same disease as the full phone</a>: nobody notices bytes piling up until performance is the symptom.</p>
<h2>Cause two: the JavaScript habit</h2>
<p>Every widget, tracker, animation library and framework ships code the visitor's phone must download and run before the page settles. Modern sites routinely ship megabytes of JavaScript to display a thousand words of text. The fixes: audit what's actually loaded (the Lighthouse report lists it), delete what isn't earning its place, and load the rest deferred. The brutal honest question — "would this page still work with this script deleted?" — usually has yes as the answer.</p>
<h2>Cause three: third-party scripts</h2>
<p>Analytics, chat widgets, ad networks, embedded social feeds, maps: each one is your page waiting on <em>someone else's</em> server, and a slow third party makes your page slow by association. The fixes: fewer embeds, loaded last (async), and the occasional brutal audit — the chat widget nobody uses is often worth more removed than its "engagement" is worth kept.</p>
<h2>Cause four and five: caching and the server itself</h2>
<p><strong>Caching</strong> is the difference between rebuilding the page for every visitor and serving the finished one from memory — static-site generators and CDNs do this for free (it's why <a href="/tech/free-vs-paid-hosting/">free static hosting is so fast</a>); dynamic sites need it configured. <strong>The server's first response time</strong> — time-to-first-byte — is the one place hosting tier genuinely matters: an overloaded shared server adds half a second before your page even starts. TTFB is the measurement that tells you whether the slow site is the <em>site</em> or the <em>host</em> — which is the diagnosis most upgraded-hosting purchases should have started with.</p>
<h2>Cause six: fonts</h2>
<p>Web fonts block rendering while they load — a beautiful typeface from a slow server can hold your entire page hostage for seconds. Fix: host fonts locally, load them with <code>font-display: swap</code> (text shows immediately in a fallback), and carry two or three weights, not eight.</p>
<h2>The discipline that beats guessing</h2>
<p>Measure (PageSpeed Insights), read the biggest items in its report, fix exactly those, measure again. Three cycles of that beats any amount of performance folklore — and the site that emerges usually costs less to run than the slow one did, because the real fixes are subtractions (<a href="/tech/csp-safe-front-end/">the same subtraction discipline hardened this site's own front end</a>).</p>
<p><em>Sources: Google web.dev performance guidance (Core Web Vitals measurement methodology). Reviewed September 2026.</em></p>""",
[("web.dev — Why performance matters", "https://web.dev/learn/performance/why-performance-matters-2"),
 ("Google PageSpeed Insights", "https://pagespeed.web.dev/")],
[("free-vs-paid-hosting", "Free vs paid hosting"),
 ("csp-safe-front-end", "Hardening the front end"),
 ("where-to-host-website-for-free", "Hosting free, first-hand")]),

("domain-names-explained", "web-and-hosting", "guide",
"Domain names explained: what you're actually paying for",
"Annual fees, teaser pricing, privacy, premium traps and the 60-day lock — the honest anatomy of the £10-a-year thing your whole site stands on.",
"""<p>A domain is the strangest purchase in tech: an annual rent on a string of letters, paid to a company that doesn't host anything, without which your website technically still exists and is findable by nobody. Here's what the money actually buys, where the traps are, and why the domain deserves more respect than anything else in your setup (<a href="/tech/custom-domain-dns-order/">we learned the DNS part the hard way, first-hand</a>).</p>
<h2>What the fee is made of</h2>
<p>When you pay £10-15 a year for a .com, the money splits three ways: the <strong>registry fee</strong> (the organisation that operates .com — Verisign — charges registrars a wholesale rate), the <strong>ICANN fee</strong> (the global coordination body, small and fixed per domain), and the <strong>registrar's margin</strong> — the company you actually bought from (Namecheap, Cloudflare, GoDaddy and hundreds of others compete on this layer). The domain itself doesn't "exist" anywhere you could visit; it's an entry in a distributed database saying <em>who is allowed to say where this name points</em>. That's the product: the exclusive right to control that entry for a year, renewable forever if you keep paying.</p>
<h2>The pricing trap: the teaser and the renewal</h2>
<p>The famous first-year price — £1.99! — is a marketing loss-leader, and the <em>renewal</em> is the real price, often 5-15 times higher. Two honest moves: check the renewal price <em>before</em> the first purchase (it's on every registrar's pricing page, one click deep, hoping you won't), and know that transferring your domain to another registrar at renewal is a normal, routine act — providers like Cloudflare even sell at near-wholesale to attract the transfers. The other trap: <strong>premium domains</strong> — names the registry or a reseller prices at hundreds-to-millions because they're short or dictionary words. The search that returns "$2,499" isn't broken; it's telling you the good strings are taken and being resold.</p>
<h2>What else the money touches</h2>
<p><strong>WHOIS privacy:</strong> domain registrations are logged in a public database; registrars used to charge extra for privacy, and most now include it free — check yours does, because the spam difference is dramatic. <strong>The 60-day lock:</strong> ICANN rules generally forbid transferring a domain between registrars for 60 days after registration or a previous transfer — so choose the first registrar with some care, because you're married to it for two months. <strong>DNS hosting vs registration:</strong> the registrar is where you <em>pay</em>; DNS is where your domain's records actually live — usually bundled, but separate services (Cloudflare DNS is popular and free), and the distinction is exactly what <a href="/tech/custom-domain-dns-order/">the custom-domain guide unravels</a>. <strong>And the TLD itself:</strong> .com is the safe default, country codes carry local rules, and the newer suffixes (.tech, .shop, .io) work fine but read differently — and can price differently at renewal, sometimes startlingly.</p>
<h2>The care instructions</h2>
<p>Auto-renew on, payment method kept current (an expired card at renewal is how sites die silently), WHOIS privacy confirmed, registrar login protected with 2FA (<a href="/tech/two-factor-authentication-setup/">done right</a>) — because whoever controls your domain controls everything built on it: email, the website, the lot. Domain theft is rare and devastating; the locks are free. And that's the whole honest answer: for the price of two coffees a year you're renting the one irreplaceable part of your internet presence — everything else, hosting included, is <a href="/tech/free-vs-paid-hosting/">movable</a>.</p>
<p><em>Sources: ICANN's WHOIS lookup service; registrar pricing pages as of September 2026 — renewal prices shift, the teaser-renewal gap does not.</em></p>""",
[("ICANN Lookup (WHOIS)", "https://lookup.icann.org/")],
[("custom-domain-dns-order", "Custom domains & DNS, first-hand"),
 ("free-vs-paid-hosting", "Free vs paid hosting"),
 ("two-factor-authentication-setup", "2FA, done right")]),
]
