# -*- coding: utf-8 -*-
"""BRYME Tech desk — the comparison shelf, batch 2 (Phase 1 T10, 21 Sep 2026).

House rules these entries obey: no invented prices or specs; anything that can
change ships with a "check the official page" nudge; verdicts are frameworks,
not advertising; first-hand voice only where the desk has actually run the thing.
Tuple shape matches TECH_ARTICLES: (slug, title, blurb, body-html).
"""

TECH_COMPARE = [
 ("zoom-vs-google-meet-low-bandwidth",
  "Zoom vs Google Meet when your connection is bad: which one survives?",
  "Audio-only fallbacks, noise suppression, local recording and calendar gravity - the differences that matter when the uplink is holding on for its life.",
  """<p>Every video-call comparison is written by someone with fibre. This one is for the rest of us: the meeting that has to happen on a mobile hotspot, in a storm, with two bars. Both apps are good; they fail differently, and the failure modes are the whole buying decision.</p>
<h2>What each does when bandwidth drops</h2>
<p>Zoom's heritage is audio-first - it grew up dialling people in over telephone lines, and that instinct shows: it keeps a call alive on a lower-quality uplink by degrading video gradually and keeps screen-share legibility prioritised over face-cam. Meet, born inside Google Workspace, leans on the browser and on aggressive codecs; its newer plans sell software noise suppression as a headline feature, which is genuinely valuable when everyone is on laptop mics in Lagos traffic. For raw survival on a weak uplink, Zoom still has the edge the moment the network starts flapping; for a call where the noise, not the bandwidth, is the enemy, Meet's suppression is excellent - verify which plan you need on Google's own page, because these features move between tiers without warning.</p>
<h2>The fallbacks you will actually use</h2>
<ul><li><b>Dial-in audio.</b> Both offer PSTN numbers. When video dies, "I'll ring in" saves the meeting; check the current call-rate page for the number you will actually dial - rates change.</li>
<li><b>Local recording.</b> Zoom records to your machine by default, which means no upload time and a file you control. Meet records to the cloud, which means it keeps working when your disk is full but needs Workspace entitlements most personal accounts don't have.</li>
<li><b>No-install guests.</b> Meet opens in a browser tab politely; Zoom's web client works but pushes the app. If your participants are clients' assistants and in-law phones, that friction is a feature decision.</li>
<li><b>Calendar gravity.</b> If your org lives on Google Calendar, Meet links are one click and the room hardware understands them. Zoom wins when meetings are cross-org and ad-hoc.</li></ul>
<h2>The verdict, as a rule</h2>
<p>If the meeting is <em>yours</em> and the network is the variable: Zoom, video off by default, record locally, dial-in numbers in the invite. If the meeting is <em>inside Google Workspace</em> and the problem is a noisy room: Meet, noise suppression on, record to the cloud, never fight your admin about it. Whatever you choose, hold one habit above all features - send the agenda as a text message too, because the message that survives a dead call is the one that isn't in the call.</p>
<h2>Check before you commit</h2>
<p>Tier names, minute limits and which plan holds which suppression feature have changed more than once across both services in recent years. Both companies publish current limits plainly: Zoom's plans page and Google's Workspace editions page. Read those, not this page, before paying.</p>"""),

 ("canva-vs-adobe-express",
  "Canva vs Adobe Express: which one should actually be your design tool?",
  "Template depth, background removal lineage, brand kits and the one accounting question that decides it: are you already paying for Creative Cloud?",
  """<p>Canva is the default answer to "can you design something quick"; Adobe Express is Photoshop's company trying to make quick respectable. They want the same three minutes of your day, and the honest differences live in what happens after those three minutes.</p>
<h2>Where each one is genuinely stronger</h2>
<ul><li><b>Starting points.</b> Canva's template library is larger by a wide margin and organised like a search engine - type "fundraiser poster, Nigeria" and you get usable, non-boring results. Express's library is smaller and skews corporate-clean; if you want a style to borrow, Canva finds it faster.</li>
<li><b>Cut-outs and photo work.</b> Express inherits Adobe's object selection - subject isolation on a busy background is the one task where its AI feels like a Photoshop-grade hand, not a magic-wand demo. Canva's background remover is fine for portraits and unreliable for hair, fur and transparent edges.</li>
<li><b>Brand consistency.</b> Canva's brand kit locks fonts, palettes and logos across a team with per-user controls that just work. Express does the same via Creative Cloud libraries, which are more powerful - if someone has already built the library; if not, the setup tax is real.</li>
<li><b>Video and motion.</b> Express has the video-editor DNA (it shares a lineage with Premiere's templates); Canva's animation is presentation-cute, not edit-tight. Short clips with captions and clean typography: Express. Slideshow-with-music for a WhatsApp broadcast: Canva.</li>
<li><b>Free-plan reality.</b> Both free tiers are usable and both gate their best assets behind paid rows, in slightly different places each year. Check the current free-vs-paid pages before deciding - the honest summary is: free Canva gets you further on design volume, free Express on one good cut-out.</li></ul>
<h2>The accounting question</h2>
<p>If you already pay for Creative Cloud - for Photoshop, for Lightroom, for a student deal - Express is in the box. Its "free" cost is a lie and a true one: you own it, and Adobe's ecosystem (fonts via Typekit, stock via the stock tiers) clicks together. If you don't, Canva's single subscription usually buys more practical capability per naira - templates, brand kit, presentation, social scheduler - as one product.</p>
<h2>The verdict, as a rule</h2>
<p>Volume design work for a small team with one competent volunteer: Canva, no argument. Photo-first social clips, cut-outs, and anyone with a Creative Cloud subscription: Express. If you find yourself fighting Express's editor on a deck, or Canva's cut-out on a hair edge, that fight <em>is</em> the answer.</p>"""),

 ("showmax-vs-netflix-nigeria",
  "Showmax vs Netflix in Nigeria: what is each actually for?",
  "Local-first library versus global volume, the sports tier question, download discipline on metered data - the honest split for streaming from here.",
  """<p>This is not a quality comparison; Netflix and Showmax both stream beautifully when your bandwidth allows it. It is a question of which habit you want funded. Pick by what you'll watch, not what the library size says.</p>
<h2>The library identities</h2>
<p>Showmax built itself on proximity: Nollywood and African originals at real budgets, South African and Nigerian soaps with current episodes (the soaps are the retention engine - people do not cancel mid-story), plus the live-sports tiers that carry Premier League football. Netflix built itself on volume and depth: a global catalogue, kids' programming that is its own argument, and a growing - still small relative to the whole - slate of Nigerian originals that increasingly arrive with international co-production money behind them.</p>
<h2>The mechanics that matter from here</h2>
<ul><li><b>Sports.</b> If you want league football included, Showmax's sports-bearing tiers are the only streaming-in-Nigeria answer that consistently carries it; verify the current tier and add-on on Showmax's own plan page - sports rights move every season, and a subscription bought on an old page is a cancelled subscription within three months.</li>
<li><b>Downloads and data.</b> Both apps save to phone; both throttle on metered connections. On capped mobile data, download caps per tier matter more than bitrate - check which plan limits simultaneous devices and download counts before you commit a month's allowance to one.</li>
<li><b>Kids and household profiles.</b> Netflix's per-profile controls and junior catalogue are still the industry reference. Showmax profiles are functional; its kids tier is narrower.</li>
<li><b>Subtitling.</b> Showmax's local-language subtitle culture has improved steadily; Netflix's subtitle quality is uniform and searchable by language. If subtitles are non-negotiable for a household, test both free weekends with your own content rather than trusting anyone's claim - including this page's.</li></ul>
<h2>The verdict, as a rule</h2>
<p>Football plus Naija-soap habit: Showmax, bought at the right tier. Volume, variety and a household that argues about what to watch: Netflix. And the honest financial line, the one no review gives you: whichever you buy, rotate with the seasons - both services make leaving easy by design, and the catalogue that justified the sub in January will not be the one in July. Read the current pricing and tier pages for your region at signup; this page deliberately prints no numbers because numbers like these go stale faster than this desk re-verifies them.</p>"""),

 ("jumia-vs-konga-electronics",
  "Buying electronics on Jumia vs Konga: which marketplace protects you better?",
  "Seller ratings, protection programmes, warranty routing and the four habits that matter more than which logo is on the checkout page.",
  """<p>Nigerian electronics e-commerce has been won by process, not platform. Both Jumia and Konga sell genuine, excellent products next to mediocre ones, because most listings come from third-party sellers. The buying skill that actually protects you transfers between them - so this comparison is half platform, half procedure.</p>
<h2>How the platforms differ</h2>
<ul><li><b>Official brand stores.</b> Jumia's mall-style official stores (brand-operated or authorised-distributor listings) are the closest thing online to a warranty-backed shop counter. Konga's own stock - the era that made its name - is smaller now; when a high-value item is "sold by Konga" and in their warehouse, its handling of returns and inspection is often calmer than a third-party storefront.</li>
<li><b>Buyer protection.</b> Both publish protection programmes with money-back conditions; the devil is in the current wording (what "not as described" covers, who pays return shipping, inspection timelines). Read the live policy at checkout, not an old screenshot - these documents get quietly tightened.</li>
<li><b>Logistics honesty.</b> Delivery windows for Lagos-mainland are similar; the differences appear in second-city fulfilment and at pickup stations. Whichever platform has a station you can reach in one ride is the one that can absorb a failed delivery without drama - for you.</li>
<li><b>Warranty routing.</b> Local warranty lives in the distributor sticker in the box, not the marketplace receipt. A listing that names the authorised distributor is worth more than any platform badge; a listing that doesn't is worth exactly what an unboxed phone is worth at a repair counter.</li></ul>
<h2>The four habits</h2>
<p>One: sort to seller rating and years on platform, then open the store's own review pages - a 100-item electronics store with 4.2 stars is a safer room than a fresh one with five perfect reviews. Two: prefer "official store" or warehouse-stock listings for anything above a mid-range phone price. Three: film the unboxing, every time, in one take including the shipping label - the protection programmes all reference evidence and mean it. Four: test before the return window closes, with the box: pixels, battery, IMEI check, speaker grille - you are inspecting, not reviewing, and the clock is the clock.</p>
<h2>The verdict</h2>
<p>For laptops, phones and screens sold with local warranty: Jumia's official stores first, seller-graded listings second, never the cheapest new-store listing. For second-life, refurbished and warehouse-stock deals: watch Konga's own inventory and read the condition grade like a contract. If either platform's current protection page contradicts this paragraph, the platform page wins - that is the point of the habit.</p>"""),

 ("iphone-vs-android-nigeria",
  "iPhone vs Android in Nigeria: the decision is repair economics, not brand",
  "Screen-part availability, resale curves, banking-app reality and the file-transfer habits that decide which phone is cheaper over four years.",
  """<p>Almost every iPhone-vs-Android argument is a lifestyle argument pretending to be an economics one. In Nigeria specifically, the economics are unusual and decisive: what happens to this phone when it breaks in month thirty, and what it sells for in month forty-eight.</p>
<h2>Repair reality</h2>
<p>Android supports a vast grey-market repair economy - screens, batteries, charging ports for popular mid-range models are stocked everywhere from Alaba to Wuse at prices that don't feel like a new-phone purchase. iPhones repair well too, but parts are serialised and pairing matters: an "aftermarket screen" trade on an iPhone comes with a settings-menu warning and a degraded True-Tone/ Face-ID story depending on the board swap. Translation: on most Android mid-rangers, a repair shop conversation is about price; on iPhones it is about authenticity, and the premium is structural.</p>
<h2>Resale as a refund</h2>
<p>iPhone resale value holds - the second-hand market trusts the battery-health readout as a spec sheet, and two-generation-old iPhones remain sellable at percentages Android rarely matches. If you buy expensive and sell once, the iPhone's curve pays part of the premium back. If you buy mid-range and never sell, the Android's lower entry price is the better deal and the resale talk is decoration.</p>
<h2>The daily-work differences that matter here</h2>
<ul><li><b>File freedom.</b> Android behaves like a USB drive - moving video projects, a card from a camera, sharing folders with a print shop. iOS is a walled garden that works perfectly if your whole workflow lives in cloud apps; it is friction the moment it doesn't.</li>
<li><b>Banking and SIM life.</b> Both ecosystems carry every Nigerian bank app, authenticator and mobile-money tool; USSD works identically. The one practical note: eSIM-first iPhones abroad can mean a paperwork visit for a local SIM swap - keep your old plan's SIM details wherever you buy.</li>
<li><b>Charging infrastructure.</b> Lightning-era spare cables are still everywhere and USB-C iPhones share the world's most common cable; Android's advantage here has quietly evaporated - the cable in any Lagos drawer fits both now.</li></ul>
<h2>The verdict, as a rule</h2>
<p>You keep phones four years and sell things when you move apartments: iPhone - the repair premium is amortised by the resale refund. You want capability per naira, file freedom, or a second device that just works for work: a solid Android mid-ranger with a wide local parts footprint (before buying any model, search "[model] screen price" with a local marketplace open - that number is the review everyone skips). Whatever the badge: buy the case and the tempered glass, because the second-most expensive moment in phone ownership is the first fall.</p>"""),

 ("ubuntu-vs-debian-home-server",
  "Ubuntu vs Debian for the home server: the family feud, settled by hardware",
  "Same lineage, opposite temperaments: release cadence, the Snap question, hardware enablement, and which one lets you forget it exists.",
  """<p>This is a family argument: Ubuntu is built on Debian, and every choice Ubuntu makes is a choice Debian declined. For a home server, "which is better" is the wrong question; the right one is "which will I still be able to fix at 11 p.m. on the Sunday I actually attempt maintenance."</p>
<h2>Where Ubuntu earns its opinionated choices</h2>
<ul><li><b>Hardware freshness.</b> Newer NICs, Wi-Fi cards and CPU microcode arrive in Ubuntu's HWE kernels without surgery. Debian stable ships what it has tested for age - rock-solid and occasionally too old to drive last year's laptop. Buy a mini-PC with recent silicon: Ubuntu makes the first hour friendly.</li>
<li><b>Documentation gravity.</b> Every home-server tutorial on the internet is written against Ubuntu or its derivatives. When you search an error at 11 p.m., the answer is written for this box. That's a real feature; don't let anyone tell you otherwise.</li>
<li><b>The managed bits.</b> Landscape, unattended-upgrades configured by default, and a free personal Ubuntu Pro token (home-lab tier - verify the current machine allowance on Canonical's own page) that patches universe packages too.</li></ul>
<h2>Where Debian is the better answer</h2>
<ul><li><b>No Snap tax.</b> Ubuntu's Snap-first habits - notably the loopback interface it creates for Docker's benefit - will bite you the day a DNS container refuses to bind port 53, because systemd-resolved already lives there. Debian's plain apt has none of these surprises; what you install is what is running.</li>
<li><b>Stability as personality.</b> Debian stable's release cadence is "when it's ready," and its upgrade path is the smoothest in Linux because everything moves at once, rarely. If your server hosts a family archive and a media shelf, boring is correct.</li>
<li><b>Resource humility.</b> A Debian netinst with the few packages you choose genuinely idles smaller, boots on older RAM, and stays that way - no first-boot package flood.</li></ul>
<h2>The verdict, as a rule</h2>
<p>New hardware, want Docker/Kubernetes/play-it-from-tutorials life: Ubuntu Server LTS, and disable what you don't use the day it annoys you. Old hardware, static services, "install and forget": Debian netinst. If you'd rather learn one system forever than argue, learn Debian proper - Ubuntu is Debian with a personality, and the personality is a subscription to its choices. Whatever you pick: name the machine, snapshot before upgrades (Timeshift or plain LVM state), and test your restore while the thing you're protecting still exists.</p>"""),

 ("chrome-vs-edge-old-laptop",
  "Chrome vs Edge on an old laptop: which one actually breathes easier?",
  "Same engine, different manners - memory discipline, battery drain, phone handoff and the one Edge setting Chrome has never copied for slower machines.",
  """<p>Both browsers are built on the same Chromium engine, so the honest question is not which is faster - it is which wastes less of the two things an old laptop has: RAM and battery. The answers are settings, not badges, and one of them genuinely ships off by default in Edge's favour.</p>
<h2>Where Edge quietly wins for older hardware</h2>
<p>Edge has a built-in sleeping-tabs system that suspends background tabs after minutes of no use and hands their memory back - and a "efficiency mode" that does the same for the whole browser while a laptop runs on battery. Chrome added tab freezing later and still keeps every open tab's extensions awake; on a four-gigabyte machine the difference is real and measurable in fan noise. The second Edge advantage is Windows-level integration: the best performance gains on an old laptop come from what the browser lets the OS do, not how fast its JS engine benchmarks.</p>
<h2>Where Chrome still earns its weight</h2>
<ul><li><b>Extension survival.</b> Every extension you rely on exists for Chrome first; Edge's store is growing but thin at the long tail. An ad-blocker is the single biggest speed upgrade any old laptop can buy, so whichever browser runs <em>your</em> blocker wins.</li>
<li><b>Sync and password continuity.</b> If your phone is Android, Chrome keeps the password vault honest. Edge does the same for Microsoft accounts - pick the browser that matches the account you already trust with your passwords, because switching vaults is the actual migration cost.</li>
<li><b>Memory hog reputation, fairly:</b> Chrome's number-one drain is not the tabs, it's the tabs that keep extensions, casting and full-res video alive. Close what you are not reading and the gap narrows; the same is true of Edge.</li></ul>
<h2>The old-laptop checklist that beats either choice</h2>
<p>Whatever logo you keep: cap open tabs at ten, put the streaming site in its own window so its DRM machinery runs alone, check the task manager's memory sort once to find which extension is the leak (it is always one), and run the browser while the laptop is plugged in when possible - batteries past three years throttle hard on charge, and no browser choice fixes physics. For a genuinely tired four-gigabyte Windows machine, the best-performing free software is a lighter operating-system install, not a lighter browser - say so, as this desk does about everything.</p>
<h2>The verdict</h2>
<p>Old laptop, Windows, no extension dependencies: Edge with efficiency mode switched on, and stop pretending it is a compromise. Android-phone household with must-have Chrome-only extensions: stay on Chrome and manage it like fuel - tabs are the consumption. Both free in every sense: try both for a week with the task manager open, and let the memory graph, not this page, decide.</p>"""),

 ("wifi-extender-vs-second-router-nigerian-house",
  "Wi-Fi extender vs a second router vs a cable to the ceiling: fixing a Nigerian two-storey signal dead spot",
  "Why extenders usually halve what they extend, when a cheap second router beats them, and the two-storey truth about cables in the ceiling.",
  """<p>The Nigerian double-storey house has a physics problem the marketing solves badly: the ground floor router broadcasts through a concrete slab with steel mesh inside, and concrete-and-steel is the champion of Wi-Fi assassination. The box of hope sitting on the shelf - the plug-in extender - usually makes it worse before dinner. Here is why, and the order of fixes that works.</p>
<h2>Why the extender disappoints</h2>
<p>A single-band extender receives the signal and re-sends it on the same radio - it talks twice so it goes half as far, and everything behind it shares one breath. Dual-band extenders do better (receive on one band, rebroadcast on the other), but they still sit in the dead zone <em>receiving</em> the very signal that is already struggling. The honest rule: extenders amplify a bad situation; they do not fix it, and each one added to the house is another neighbour's channel to fight over at night.</p>
<h2>The three real fixes, in cost order</h2>
<ul><li><b>The second-router-as-access-point trick.</b> Any cheap router with an Ethernet port can be an access point: run one cable - even an ugly external one clipped along the wall - from the main router to the second floor, plug it into the second router's LAN port, turn <em>off</em> that router's DHCP, and give it the same network name and password on a different channel. Now devices roam to whichever is louder. This is the same job a mesh kit does for many times the money.</li>
<li><b>Powerline adapters, with an if.</b> In houses on stable wiring - one meter, clean connections - powerline carries the network through the electrical copper to another room's socket. The if: Nigerian homes often have separate circuits, old joints and stabiliser-heavy wiring; a good kit on one ring beats a bad one across two meters. Buy from a shop that lets you test on your own circuit before the week is out.</li>
<li><b>The ceiling-cable endgame.</b> One Cat6 run in the ceiling - through the roof space if you have one, clipped externally if you don't, with proper conduit where the sun hits - turns every future fix into plug-and-play. It is the one installation a competent electrician can do on the same visit as the wiring repairs, which is how the labour cost stays civilised.</li></ul>
<h2>What to do tonight, free</h2>
<p>Move the router: central, high - top of a wardrobe, not behind the TV where the metal panel eats it - and change the control-channel to the one your phone's Wi-Fi scanner shows as empty, because on a street of thirty networks, the least-crowded channel is worth more than any box. Then decide from the signal you actually measure - a phone's Wi-Fi reading at the dead spot is the instrument this whole page rests on, and it is in your pocket.</p>"""),

 ("dell-vs-hp-refurbished-laptops-nigeria",
  "Dell vs HP refurbished laptops: which brand survives Nigerian second-hand life better?",
  "Parts supply, keyboard ratings, the battery grading honesty test, and the two model families that keep this desk buying one brand with eyes open.",
  """<p>In the second-hand market, the brand badge on the lid is actually a supply chain: which spare parts will still exist in three years, and whether any technician in the city can fit them with tools from one drawer. Dell and HP both pass that test; the differences are in the habits their business lines left behind.</p>
<h2>The parts story</h2>
<p>Both brands flooded Nigerian offices with the same class of machine - corporate fleets renewed every three years - so the streets are carpeted with their parts: screens, hinges, keyboards, chargers. Dell's Latitude/Precision families share charger barrels and BIOS habits so deeply that a repair often becomes swap-and-go; HP's EliteBook/ProBook lines lean on ubiquitous USB-C charging now, which future-proofs the purchase. Either brand, the one question that predicts your next five years: "do they stock the keyboard for this model here?" If the answer at your shop is "we can import it, two weeks," a keyboard death becomes a funeral.</p>
<h2>Where each tends to land</h2>
<ul><li><b>Dell (Latitude/Precision):</b> thick, hinge-heavy business builds that survive the "carried everywhere in a backpack" life; BIOS menus that a technician can reset with nothing but a screwdriver; docking legacy that turns a used laptop into a desktop on a second-hand stand.</li>
<li><b>HP (EliteBook/ProBook):</b> often the nicer keyboard and the better screen for the same money; the EliteBook aluminium shells resist flex; and the one practical edge that matters - their recent mid-range all keep memory in ordinary slots rather than soldered, which is how a four-gigabyte find becomes sixteen gigabytes cheaply. Check the exact generation: HP has soldered more, and "usually" buys nothing.</li></ul>
<h2>The grading honesty test (works on any brand)</h2>
<p>Grade-A / Grade-B listings are a shop's vocabulary, not a standard - so ignore the word and run the five-minute interrogation on the actual machine: charge port - does the socket wiggle? Battery - health report from the OS, not the shop's promise; hinges - open and close it ten times, slowly; screen - full white and full black pages at max brightness for backlight bleed and dead pixels; screws - stripped heads mean a second repair, which means a first repair the shop will not warranty.</p>
<h2>The verdict, as a rule</h2>
<p>Whichever brand your specific shop can actually service is the right brand: the used-laptop market is local by nature, and a warranty you can walk to beats any model preference. Between two same-shop machines of equal grade and price: the one with the upgradeable RAM and the USB-C charge - that is where used-life economics live. And refuse any laptop whose battery "report" is a shopkeeper's memory: the operating system prints the number, and the number is the whole battery section of this article.</p>"""),

 ("kindle-vs-kobo-vs-tablet-reading",
  "Kindle vs Kobo vs your tablet for reading: the decision is the store, not the screen",
  "E-paper versus a glass screen at night, the library-loan card neither advertises, and the format wars settled by the one file type both e-readers eat.",
  """<p>Every specs comparison of e-readers misses the decision. The real question is where your books come from, because each device is a shop window with a screen attached - and if you buy the wrong window, the glass is still lovely while your library sits in the other ecosystem's file format.</p>
<h2>The screen, since it must be covered</h2>
<p>E-paper is not technology you watch, it is technology you ignore: ambient light on ink, no blue at bedtime, and a battery counted in weeks precisely because the page does not refresh itself like a video. A tablet does the same job on a good evening with dark mode - and makes the sleep you needed worse. If reading is how you fall asleep, the e-ink device is the only honest answer; the tablet is a reading lamp with a notification habit.</p>
<h2>The libraries nobody puts on the box</h2>
<ul><li><b>Kobo's quiet superpower:</b> it accepts the free library-loan format the public libraries built their lending systems around, so a Kobo and a library card can be the whole subscription - and in a country where most library delivery is not part of the deal, its openness to any file you can move from a folder still matters: it reads the standard unprotected book file; the shops' DRM formats are the ones it will not.</li>
<li><b>Kindle's gravity:</b> the store is the world's largest used-and-cheapest book machine; Whispersync moves your place between phone and reader, and the ecosystem's sale culture is genuinely the cheapest way to build a library in English. Its walls are walls - the proprietary file type is why sideloading guides exist - but they are walls around the biggest yard.</li>
<li><b>Tablet plus apps:</b> free library apps, PDFs that e-ink butchers (the real answer for a student with lecture packets is a ten-inch tablet and a stylus), audio-book support without a phone by the ear - the "one device for everything" argument is honest for exactly these jobs.</li></ul>
<h2>What the spec sheets get wrong</h2>
<p>Brightness: both e-readers light the page sideways so the screen surface stays matte - the numbers in their ads are marketing, not sunlight; test at dusk with the light off, which is when it matters. Storage: a thousand books fit in less than a phone's photo app wastes. Waterproofing: real now on the premium tier - if you read in a bath or a rainy compound veranda, it is worth money; if you read in bed, it is not.</p>
<h2>The verdict, as a rule</h2>
<p>Buying books in English, one store for life: Kindle, accept the walls, enjoy the yard. Owning your files and wanting zero subscription: Kobo. A student, a PDF reader, a commuter with three apps: keep the tablet, buy the reading light separately and sleep better on purpose. No one in the history of this desk has regretted the e-ink purchase; the regret is always the ecosystem, so choose the shop, not the screen.</p>"""),

 ("streaming-stick-vs-android-box",
  "Streaming stick vs Android TV box for a dumb TV: what each box cannot do for you",
  "The one app your stick will never install, the update cliff every box seller hides, and the honest cast-versus-native verdict for a Nigerian living room.",
  """<p>Both fix the same problem - a television with no apps - from opposite philosophies: the stick is a remote with ambition, the box is a phone you point at a wall. The differences decide in about eighteen months of ownership, not in the shop.</p>
<h2>The stick's case</h2>
<p>Interface polish and app certainty. A Chromecast-class stick brings a curated front page, an update stream that lasts years from a manufacturer with a platform to feed, and one trick the box never reproduces cleanly: casting - the phone is the remote <em>and</em> the content buffer, which on a shaky home connection outperforms the box downloading alone. It is smaller, uses the TV's own USB port for power (watch the port's amperage - some TVs sag; the supplied wall plug exists for a reason), and it survives the landlord change because it moves in a pocket.</p>
<h2>The box's case</h2>
<p>Freedom and the answer to "what about the app that isn't on the store" - when a service exists as an APK, the box is the TV that runs it: regional sports apps, local IPTV interfaces used <em>legitimately</em> (this desk will not walk you toward pirated anything - a subscription that costs less than a bottle of Fanta per month is not a deal, it's an eviction notice with a logo), sideloaded file players that eat every codec in a shared folder, and full keyboard-and-gamepad support. RAM and storage are real, and matter if you want the box to be more than a streamer.</p>
<h2>The two things sellers bury</h2>
<ul><li><b>The update cliff.</b> A no-name Android box gets its Android version and its security patches once, from a factory, on the day it ships. Two years later the bank app refuses the OS level and the store app stops updating. Branded TV boxes (the name-brand Android TV lines) are the middle ground - real update promises - which is precisely why they cost more than the grey import.</li>
<li><b>The interface tax.</b> Phone apps on a TV need a Leanback interface or you live in a remote-control maze; the stick's whole job is that interface, so the "limited app list" that reads like a weakness on the spec sheet is the product.</li></ul>
<h2>The verdict, as a rule</h2>
<p>One streaming habit, living room, family remote: a name-brand stick - the polish is the purchase. Tinkerer, sports-bundle collector, or the app you actually watch lives outside the store: a branded Android TV box with real update commitments, and if the grey import tempts you, budget for it to become a media player in two years and the price math changes. Either way, the HDMI port and the TV's own volume control will do the rest; the dumb TV, as always, is the second-best thing in the room after you fixed it.</p>"""),

 ("student-laptop-spec-floor-2026",
  "The honest spec floor for a student laptop in 2026: five numbers, no prices",
  "The minimum configuration that will still work in year three of a degree - and the two spec traps that make a cheap laptop expensive by second semester.",
  """<p>A student laptop is bought once and judged for four years, so the only sensible purchase question is: which numbers make it survive year three? This desk will not quote prices - they move - but the floor below which any laptop becomes coursework with a lid is stable and small enough to memorise.</p>
<h2>The five numbers</h2>
<ul><li><b>16 GB of RAM, or 8 that is upgradeable.</b> Browser tabs are the student's real workload, and each one is a small office. Four gigabytes is a 2020 laptop; eight is the 2026 minimum with a hard floor, sixteen is the one that stops you managing tabs for the last time.</li>
<li><b>A real SSD, any size you can grow.</b> Hard-disk laptops are still sold as "new" behind some counters; they are slow, they die from backpack life, and they teach you to hate computers. If the machine says HDD, walk - the secondhand SSD swap later is cheap; the lost project is not.</li>
<li><b>A screen you can read at 100 percent zoom.</b> 1920x1080 on 14 inches, matte, and - the trap - not the 1366x768 panels still shipping as "HD." Zoom once in the shop and look at the letter edges; your eyes are the lab.</li>
<li><b>Modern-ish CPU: any current four-core, generation not older than about three years.</b> For lecture-hall work, the processor is almost never the bottleneck - <em>except</em> in the one spec trap below.</li>
<li><b>Weight under 1.6 kg with the charger, measured in the shop, not the listing.</b> A lecture hall is a five-minute walk; a campus is a twenty-minute one, every day, for four years, and a 2.4 kg machine is a decision you make again each morning by not making it.</li></ul>
<h2>The two traps</h2>
<p>One: the Pentium/Celeron/"4-core feel" chips that carry modern RAM and SSD while being the bottleneck the whole specification exists to remove - the processor is where a "great value" laptop hides its crime. Two: soldered-everything thin-and-lights - the ultrabook shape at the student budget means no RAM path up, no battery swap without glue, and one deep scar from the repair shop that follows the machine like a debt. Both traps are visible in five minutes: open the back panel image, or ask the seller which slots are empty.</p>
<h2>The floor, as a card</h2>
<p>Sixteen gigabytes or a free slot. Solid-state storage. Full-HD matte screen. A four-core CPU no one has to hype. Under 1.6 kilos. Warranty you can <em>walk to</em> - in the second-hand market a shop's reputation is the manufacturer's warranty, so buy the dealer as much as the laptop. Every spec argument after those five is preference; a seller who argues they are "nice to have" is telling you which side of the till they are on. For engineering students running genuinely heavy software - check the department's published requirement before you buy anything, because that page, not this one, is your real floor.</p>"""),

 ("tablet-vs-budget-laptop-for-students",
  "Android tablet or a cheap laptop for school: the answer is your exam portal",
  "The exam software decides this purchase, not the spec sheet. What a tablet genuinely beats a laptop at, and the three things to check before you buy.",
  """<p>Every "tablet vs laptop for students" debate ends the same way: the tablet is more fun, the laptop survives, and the real judge is whichever piece of software your exams require. Before comparing anything, open the department's requirement page and the exam portal's system notes - if proctoring needs a desktop browser or lockdown software, the tablet is a lovely notebook and nothing more.</p>
<h2>Where the tablet quietly wins</h2>
<ul><li><b>Handwritten notes and marked-up PDFs.</b> A stylus on lecture slides beats typing on a small laptop keyboard for most people, and the tablet is doing it in a lecture where a laptop would be rude. Ten-inch class with a keyboard cover closes some of the laptop's gap.</li>
<li><b>All-day battery and instant-on.</b> Tablets idle like phones, wake like phones, and a good mid-range tablet genuinely survives a full campus day - most budget laptops with tired batteries do not, and your campus socket is a lottery.</li>
<li><b>The phone life it buys you.</b> Cellular tablets and a big phone on the same plan mean the notes travel without public Wi-Fi. A laptop in the same lecture hall is a theft conversation you did not want to have.</li></ul>
<h2>Where the laptop is not optional</h2>
<p>Long-form writing with a real keyboard at a real pace - theses, case notes, anything that ends in a proper document rather than an app's export. Files that are files: moving a folder of scanned sources, running reference managers, unzipping a dataset. And the one budget-laptop advantage over every tablet: it can grow - a free RAM slot, a bigger SSD, a second life as the house machine. The tablet you bought at "student price" is the exact size it will remain forever.</p>
<h2>Three checks before you buy either</h2>
<ul><li><b>The exam portal test.</b> Find one past paper or practice quiz the first-year class group chat never stopped complaining about, and confirm it runs on the device you are considering. That complaint list is the real review site.</li>
<li><b>Storage truth.</b> 64 GB on a tablet is a fiction after the university app, the messaging flood and one semester of PDFs - check the card slot or the cloud policy your school gives you before the device, not after.</li>
<li><b>The keyboard test.</b> If the tablet is in play, type a real paragraph on the on-screen keyboard for five minutes. Most people who hate typing on glass only know they do after a deadline.</li></ul>
<h2>The verdict, as a rule</h2>
<p>Tablet with a keyboard is the right machine for: reading-heavy courses, handwriting, fieldwork, one subject where a stylus changes how you think. Laptop is the right machine for: everything that ends in a serious document, proctored exams, and students who need one device to do the whole job. And for the budget that buys one good machine rather than two mediocre ones - the laptop wins for most people; the tablet wins for the few who know exactly which job it will do.</p>"""),

 ("power-bank-size-math-for-tv-and-wifi",
  "The power bank math nobody does: what a 20,000 mAh brick actually runs",
  "Milliamp-hours are marketing, watt-hours are physics. The one-minute conversion that tells you whether it runs a TV, a router, or nothing.",
  """<p>A power bank sold as "20,000 mAh!" and a television that "only uses 60 watts" are two numbers written in different languages, and the argument about whether the brick can run the TV is just translation. A minute with a calculator fixes it permanently. This page is the whole method.</p>
<h2>The translation, once and for all</h2>
<p>Energy (watt-hours) = capacity (amp-hours) x voltage. Phone cells live at about 3.7 volts, so 20,000 mAh is 20 Ah x 3.7 V = <b>74 Wh</b> of stored energy. Now subtract reality: every conversion (battery to USB to whatever plugs in after) leaks - budget 80-85 percent of the label for the actual usable pool, so roughly <b>60 Wh</b>. That number is the fuel tank; every device you name has an hour rating waiting inside it: hours = 60 Wh / device watts. A router drawing 10 W runs six hours. A 60 W television runs about one hour. A 10 W fan on the USB adapter runs six. The arithmetic is not negotiable and no marketing department can legislate against it - which is why the label says mAh and not Wh.</p>
<h2>Why "power my TV" needs a different tool</h2>
<p>A television on a USB power bank means an inverter brick, a DC-to-AC conversion and then the TV's own supply again - each hop is another ten percent gone, and the flat-screen's "60 W" is its average under content, while at switch-on with the backlight cold it briefly asks for more. The honest line: USB power banks are for phones, lights, routers, fans - devices native to DC or tiny enough not to care about losses. A television and decoder through the night is a small inverter-and-battery job (this desk's generator-versus-inverter article does that sizing by load, on purpose, without quoting prices), not a power bank one.</p>
<h2>The two spec traps on the box</h2>
<ul><li><b>Output watts are a cap, not a promise.</b> A "22.5W" bank running a device that asks for more will run it badly or not at all - check your device's charger label for the real ask, and the bank's output profile (USB-PD is a standard; a no-name "fast charge compatible" sticker is a rumour). A laptop asking for 45-65 W will refuse anything that is not a PD charger with a matching figure and a cable that can carry it.</li>
<li><b>Pass-through and the aging curve.</b> "Charge while it charges" is a chemistry tax - the bank gets warm and the usable capacity after a year of daily full cycles is genuinely lower than the number today. Buy capacity for the load you have <em>plus half again</em>, not for the load exactly.</li></ul>
<h2>What to actually buy with this method</h2>
<p>Write your list - router 10 W, two phones at 5 W each charging overnight, a 15 W fan - total the watts, decide the hours, divide, and the right brick size falls out in watt-hours. The shops will still argue in mAh; you now read the other language, and the argument costs them a sale to you only once.</p>"""),

 ("usb-c-fast-charge-not-working",
  "Your USB-C laptop charges slowly and it is not the laptop: the cable, the brick, the port",
  "Three suspects in order of how fast you can prove them guilty - and the label-reading skill that ends the mystery permanently.",
  """<p>USB-C "fast charging" is not a feature, it is a negotiation: the brick announces what it can supply, the laptop accepts a share of it, and something in the middle - a cable, a port, a firmware grudge - decides whether that number is 65 watts or a sorry 15. When charging slows, you are triaging a negotiation, and the three suspects can each be proven in two minutes with nothing but your eyes.</p>
<h2>Suspect one: the cable (it is usually the cable)</h2>
<p>A USB-C cable with no chip inside is legally allowed to carry only a small current, and 100W-capable laptops quietly settle for whatever the cable whispers. The fixes are visible: the cable that came with the laptop works, most cables that came with phones do not - look for the E-Marker mark on the connector or a rating on the packaging ("5A", "100W", "240W" for the newest standard). The test that needs no tool: borrow the laptop's own cable with the mystery brick. Same slow charge, the cable is innocent. Fast charge returns, you needed a cable, not a charger - and every counter in the market knows you did not know that yet.</p>
<h2>Suspect two: the brick's profile, not its watts</h2>
<p>"65W" on a multi-port brick is a total budget shared like a house fund: plug a phone in beside the laptop and the laptop is politely cut down so the phone can drink. And watts must appear in the right voltage conversation - the laptop asks for a USB-PD profile (20V is the laptop-relevant line in the fine print) and a brick whose 65W is spread purely across phone voltages cannot say yes to that request at any price. Read the tiny output table on the brick itself before the box; it is the only honest page on either.</p>
<h2>Suspect three: the port and the machine</h2>
<p>Not every USB-C port on every laptop is wired for power in, and some are current-limited even when they are - check the manual's port diagram for the charging mark and use only those. A port that charges at full speed on a Friday and limps on Monday has usually gathered lint: a toothpick and daylight, port side up, the compressed fluff at the bottom being the USB-C equivalent of the pocket lint that killed your phone's charger years ago. And the laptop's own health report - battery settings often name the accepted charge rate in plain watts - is your instrument for all three suspects above.</p>
<h2>The permanent fix</h2>
<p>Own one good cable per machine, marked for its watts; one brick whose output table names your laptop's voltage; and the one-line habit of plugging the laptop into its <em>own</em> brick when the deadline matters. Fast charging fails almost always because one link in the chain is honest-but-smaller than the label beside it; the chain, not the label, is what you are buying.</p>"""),

 ("anc-vs-passive-isolation-earbuds",
  "Noise cancelling versus just plugging your ear: what survives a Nigerian living room",
  "Active cancellation is a narrow science with a wide marketing net. What it beats, what it cannot touch, and the cheaper physics that sometimes wins.",
  """<p>"ANC" on a box promises silence; what it delivers is subtraction of one specific kind of noise - the steady drone - while everything sharp and human stays, unless the ear tips also seal the canal properly. Knowing which half of a noisy room you are buying relief for is the whole decision.</p>
<h2>What active cancellation is genuinely good at</h2>
<p>Generators at a distance, air conditioners, the fan that never switches off, a car's idle through a wall - these continuous, low, predictable sounds are what ANC microphones predict and delete, and done well, the relief is enormous and the tiredness it removes is real. It works least on voices, clattering plates and music next door, because those change too fast for the subtraction; and it never removes the pressure feeling some people get from the manufactured quiet. Budget ANC mostly buys the drone-cutting badly plus ear fatigue; premium ANC buys the same trick well. The honest middle is thin.</p>
<h2>What passive isolation - a good seal - is better than people think</h2>
<ul><li><b>Voices and sudden noise.</b> Foam tips, fitted properly and compressed into the canal, attenuate exactly the band ANC gives up on - the human range. The single most cost-effective quiet in existence, and it needs no battery.</li>
<li><b>Dust and harmattan.</b> A sealed ear keeps grit out of the driver where open-fit earbuds gather it like a shop tray - isolation is also maintenance.</li>
<li><b>Fitness, showers, the kitchen.</b> ANC earbuds that die from sweat were bought for the plane they never take; foam tips on wired buds out-survive most "sport" labels for a fraction of the price.</li></ul>
<h2>The combinations that actually win</h2>
<p>Best value quiet: decent-seal earbuds <em>plus</em> content at the volume you would use in a silent room - ANC earbuds played loudly to beat a generator are the worst of all worlds for the ears, and that habit's safety is not negotiable on any product page anywhere. For the open-plan office and a crying-baby-tolerant commute: good ANC <em>with</em> a real seal, microphones and foam each doing their own halves. And the trick the spec sheet never mentions: two layers - isolation buds inside ANC cups - is the ceiling for a shared flat; silly to look at, and the only answer for the genuinely loud.</p>
<h2>The verdict, as a rule</h2>
<p>Noise is a spectrum and the two technologies own different halves of it: cancellation buys the drone, isolation buys the people. If your enemy is a generator, a plane or a fan, save for real ANC. If it is the household, the market or the street, a properly fitted seal wins now and wins forever - and the battery never dies.</p>"""),

 ("smr-vs-cmr-hard-drives",
  "The drive that stutters: SMR vs CMR, the spec sheet's smallest and worst lie",
  "Two letters buried in the fine print decide whether a drive survives CCTV, backups and a NAS - and why one model family can be either.",
  """<p>Hard drives quietly split into two designs for writing data, and one of them is built for the wrong job in most homes and shops. The letters are on the manufacturer's spec page, nowhere else - and once you know them, you cannot shop for disks the same way again.</p>
<h2>The difference in one paragraph</h2>
<p><b>CMR</b> (conventional magnetic recording) writes each track in its own lane: predictable, steady, and how drives behaved when all drives were this. <b>SMR</b> (shingled - tracks overlap like roof shingles to squeeze more capacity from the same platters) writes in bands, and rewriting one lane forces the drive to shuffle neighbours in batches. A shingled drive is fine when data flows one way in long writes and is read politely - the archivist. It is miserable when writes arrive randomly and never stop: camera footage, a nightly backup into a changing folder, anything with two machines writing it. The drive stops to tidy itself, and the stutter is its real behaviour, not a fault.</p>
<h2>Which jobs punish SMR</h2>
<ul><li><b>CCTV and NVRs.</b> Surveillance write is continuous, multi-stream and forever - exactly the load that fills an SMR drive's cache and then spends its life in the shuffle. The "surveillance" labelled drives exist for this reason; their spec pages are where the letters live.</li>
<li><b>Any NAS, including the home box running media and backups side by side.</b> RAID itself is a rewrite machine; with shingled drives, resync and scrub windows grow and grow.</li>
<li><b>The video editor's scratch disk</b> - which is also the reason the "huge capacity, great price" portable shelves exist: the cheap capacious portable is frequently the SMR, sold for backups, bought for editing.</li>
<li><b>Windows machines where the disk is also the page file</b> - random small writes, forever.</li></ul>
<h2>How to buy safe</h2>
<p>The model number alone will not tell you - some families contain both designs in different capacities - so the rule is one deep link, not one glance: open the manufacturer's product specification page (not the retailer's listing), find Recording Method, and accept only CMR for the four jobs above; SMR is a fine purchase for cold archives and "copy the folder and put it in a drawer" drives. If the spec page does not say the word, treat that as an answer - hiding it is the modern version of the old "remanufactured" sticker - and walking to the next drive on the shelf is the cheapest insurance you will ever buy in that market.</p>"""),

 ("4g-router-antenna-worth-it",
  "External antennas for your 4G router: the 20-minute test that beats buying the kit",
  "TS9 ports, placement versus gain, and why a short cable to a window usually beats a tall antenna on a long wire - the honest physics.",
  """<p>Every stall selling "signal booster antenna" kits rests on one truth: a router with weak reception can improve by a metre of relocation, and the same router with the wrong antenna kit can stay exactly as bad. Before the wallet opens, run the test that tells you which machine you own - because the diagnosis changes the purchase from an antenna to nothing at all, or to one very specific thing.</p>
<h2>Step one: does your router even have the option?</h2>
<p>Look for two small coaxial ports - usually TS9 or SMA, behind a flap, sometimes only present on the "pro" revision of the consumer model. No ports means the internal antenna is the only body your router has, and every external kit becomes a dongle gamble or a new router, not an antenna. And the honest check the sellers skip: ports that exist on the stock photo but not your exact hardware revision - look at the device, not the listing.</p>
<h2>Step two: the 20-minute free experiment</h2>
<ul><li><b>Placement before gain.</b> The mast's direction beats everything: walk the router to a high point on the side of the house facing the mast - first floor, shelf height, off the metal shelf, away from the TV - and read the signal figures in the router's admin page before and after. The numbers are dBm, and less negative is better: -105 is a bad day, -75 is a strong one.</li>
<li><b>The hand test.</b> Move your hand between the router and the mast, watching the readings: if a hand drops a bar, the building skin was doing what the antenna box promises - and a window-mounted external antenna genuinely helps. If nothing moves, the signal arrives rich from its direction and an antenna is theatre.</li>
<li><b>The night reading.</b> Mobile data is a shared cell: record the numbers at 8pm for three nights before deciding the router is the problem - a congested tower answers to a better antenna the way a queue answers to a louder voice: not at all.</li></ul>
<h2>Step three: if you still buy, buy right</h2>
<p>External antennas are not generic: a kit must match your carrier's bands, the connector type (TS9 versus SMA is a genuine and common dead end), and - the part nobody mentions - cable loss matters more than the pretty dome: coax from the roof to the desk can swallow the entire gain the antenna adds, which is why a short cable to a window-mounted panel usually beats the big antenna on the pole with twenty metres of thin wire. The one spec worth money on the box is gain in dBi <em>for your band</em>, and the one honest review is your own admin page's readings before and after, same spot, same hour - the instrument has been built into your router all along, and it is the only judge this desk trusts.</p>"""),
 ("new-midrange-vs-used-flagship",
  "A new mid-ranger or a two-year-old flagship: which phone actually lasts longer?",
  "The new phone's advantages stop at warranty; the used flagship's stop at battery. The five questions that decide which side you are on.",
  """<p>It is the market's oldest stand-off: the fresh box with a two-year-old processor, or the sealed deal with a flagship's camera and a battery with history. Neither is the smart choice - the smart choice depends on which weaknesses you can live with, and both lists are short enough to read once.</p>
<h2>What the new mid-ranger genuinely buys</h2>
<ul><li><b>A battery with zero mileage.</b> The single component that ages everything else in a phone is the cell - and nothing beats a flagship's two-year head start except a first day. A tired battery means heat, throttling and a power-bank tether that no case fixes.</li>
<li><b>Warranty and parts runway.</b> A current-series phone can be repaired with new parts for years, under something resembling a warranty. A used flagship - no receipt, no box, seller's word only - is repaired with whatever the market has, when it has it.</li>
<li><b>Software years that actually arrive.</b> Flagships get the long update promises; mid-rangers get the short ones - this is the mid-ranger's real weakness, and it is why the next section exists. Check the manufacturer's stated policy for the exact model, on their site, before buying either side.</li></ul>
<h2>What the used flagship genuinely buys</h2>
<p>The things a spec sheet ages well: the camera sensor's size and lens quality, the display, the build and its sealing, speaker quality, and enough processor headroom that two years on the shelf is a generation, not a cliff. For photography, the two-generations-old flagship is usually still the better photographer. For charging speed on a grid that visits nightly, verify the charger situation on both sides before the camera argument even starts.</p>
<h2>The five questions that decide it</h2>
<ul><li><b>Can the flagship's battery be swapped, and does it have a report?</b> A replaceable cell erases the flagship's biggest weakness; an 84 percent health figure with a repair shop nearby is a bargain. No report, no deal - the number is the whole conversation.</li>
<li><b>How old is the update promise?</b> If the flagship's support window is visibly over - check the model's release year against the manufacturer's published policy - the phone works fine and ages offline; whether that costs you depends on how long you keep banking apps.</li>
<li><b>What is the mid-ranger's chipset reputation?</b> The gap between the new budget chip and the old flagship silicon is real heat and stutter on heavy camera and navigation loads - and negligible on messaging and video. Know your load.</li>
<li><b>Resale and repair symmetry.</b> Both lose value; the flagship's parts are pricier, the mid-ranger's are everywhere. Whichever you buy, the case and glass decision at the counter is the same insurance you should buy either way.</li>
<li><b>Do you actually need what the flagship has?</b> If you are paying a flagship's used price for a camera you will shoot in auto at night, the mid-ranger's warranty wins. If you shoot the kids' football and print anything, nothing under a good sensor will make you happy, and you know it.</li></ul>
<h2>The verdict, as a rule</h2>
<p>Verified recent battery health, repairable model, support window readable: take the used flagship and count the money saved as a head start on cases and chargers. Any of those three unknown, or a phone kept four years to its last breath: take the new mid-ranger, accept the software years as they come, and buy the power bank that its honest battery will make unnecessary. The mistake is not the choice; the mistake is the missing receipt on either side of it.</p>"""),

 ("before-a-new-laptop-the-two-part-surgery",
  "Before the new laptop: the two-part surgery that revives most old ones",
  "Memory and a solid-state drive are the whole operation for many 'dead slow' machines. What each costs in effort, which laptops refuse surgery, and the checklist that ends the grief before the till.",
  """<p>Most laptops are condemned for a slowness that is fixable with two parts and an afternoon, and the repair-shop economy around them has learned to quote replacements before repairs because repairs take twenty minutes and replacements take margin. This page is the counter-argument, in order, with its own honest limits.</p>
<h2>Part one: the solid-state drive</h2>
<p>If the machine boots by spinning - a hard disk clattering away behind the login - the single largest speed event available in consumer computing is swapping that for a solid-state drive. Boot times and app launches change from patient to instant; the processor never has to wait for a platter to rotate into position. The practical steps the desk has walked through on its own machines: (1) open the back - if it opens with a screwdriver and no glue, you are halfway there; (b) check the bay - 2.5-inch SATA drives are the era of laptop almost any shop can service, and the older the machine the better the odds; (c) clone or clean install - cloning software with a "clone disk" option and a cheap USB adapter moves everything across including Windows, with one reboot into the new drive to confirm; and (4) - the part everyone skips - refit the old drive into a USB enclosure for the backup machine it was before it was the boot drive.</p>
<h2>Part two: the memory</h2>
<p>Four gigabytes is the 2026 experience of a queue - the browser, the messaging app and everything else trading the same small room. The surgery: find the empty SODIMM slot (two latches, a notch offset - the physical shape guarantees the right module if you match generation DDR3L/DDR4/DDR5 to the label or the manual), seat it angled until the latches click, done. One caution the shops skip: matching the existing stick's generation and voltage matters more than matching speed, and a mixed pair will run together at the slower card's number - still a huge win, but buy knowing the rule. Machines with soldered memory - most thin ultrabooks - refuse this part; the manual or a back-panel photo tells you, and the second-hand market is where the non-soldered ones live.</p>
<h2>When the surgery is not your answer</h2>
<ul><li><b>The battery is the whole complaint.</b> Then the fix is a battery, not a laptop - provided the model's cells still exist on the market.</li>
<li><b>The screen, keyboard or board is dying.</b> That is the third part nobody counts cheap, and a good technician's "it's not worth it" is often the honest one.</li>
<li><b>The CPU is genuinely below the floor</b> - this desk's spec-floor article lists it, and a laptop missing that floor by two generations is a browsing machine by any surgery.</li></ul>
<h2>The order of operations for the shop</h2>
<p>Quote the two parts plus installation in writing; ask for the old drive back (it holds your life, and it is your backup); and if the laptop boots like new after surgery and still dies in a year, the culprit was a dying board the diagnosis could not see - a risk the replacement carries too, for twice the money. Every honest technician on this desk's list has watched a two-part repair save a laptop everyone had given up on; that is exactly why the counter quotes the whole machine first.</p>"""),

 ("satellite-vs-4g-fixed-wireless",
  "Satellite internet vs 4G fixed wireless: what the sky does that the mast can't",
  "Latency physics, weather truth, data caps and the mast question - the honest table this desk keeps refusing to print as 'starlink wins' or 'mtn wins'.",
  """<p>Both services promise internet without a cable, and they deliver it with opposite weaknesses: satellite fights physics (the speed of light is a service-level agreement you cannot negotiate) while fixed wireless fights geography (a mast, a line of sight, and every other household sharing it). Your house decides which weakness is survivable.</p>
<h2>What the sky costs you</h2>
<ul><li><b>Latency, honestly:</b> geostationary satellite internet adds a delay measured in hundreds of milliseconds - usable for browsing, painful for anything real-time, and the "low latency" generation of constellations in low orbit cuts that to tens of milliseconds by being closer, not by magic. Video calls work; a competitive game never will, on either version.</li>
<li><b>Weather:</b> heavy rain attenuates the Ku-band signals these services ride, and the outage is not the dish failing - it is the rain being a wall. Fixed wireless suffers its own weather story - mast congestion during storms when everyone is indoors at once.</li>
<li><b>Anything that counts your bits:</b> satellite plans historically meter, cap or slow; constellations have moved toward flat allowances, but the fine print and the local reseller's pricing are the truth here, not this page - check the current terms before the hardware is on the roof.</li></ul>
<h2>What the mast costs you</h2>
<p>Fixed wireless - a 4G/5G router with an external antenna port, or the carrier's home-broadband box - is only as good as the cell it can hear: the same tower your phone fights at 9pm, with your house's trees, buildings and distance in the way. The advantages are real: no dish to align on a roof, equipment from the carrier, and if you already have decent phone signal indoors the router inherits it. The dependency is also real: when the mast congests or its power fails, your neighbours' traffic is your traffic, and the mast's backup generator has its own fuel story.</p>
<h2>The decision, as a table</h2>
<ul><li><b>Rural compound, clear sky, no mast worth talking about:</b> satellite - it is the only one of the two that works by definition.</li>
<li><b>Suburb, good phone signal, light users:</b> fixed wireless wins on price-per-usable-megabyte and you lose nothing you were using.</li>
<li><b>Anything with video calls all day, banking, VPN work:</b> the latency argument matters - low-orbit or fibre-to-the-street over both, geostationary only if nothing else reaches.</li>
<li><b>The household that shares one connection with phones tethering and homework:</b> whichever service has the plan whose allowance you cannot accidentally hit by Tuesday - the cap is the real boss of the Nigerian home network.</li></ul>
<h2>One line neither seller says</h2>
<p>Both services are measured on the evening, on your own roof - the trial period and the router's admin page are your lab, and the desk's only firm recommendation is that you keep the service long enough to use it on a Friday night, because everything else is a Tuesday.</p>"""),

 ("fitness-band-vs-smartwatch-vs-phone",
  "The fitness band, the smartwatch and the phone in your pocket: what each truly measures",
  "Step counts are marketing theatre; heart rate and sleep are the useful parts. What the cheap band does as well as the expensive watch, and where the premium actually buys you something.",
  """<p>The wearable market sells you the same sensor twice at ten times the price, and the difference between a good band and an expensive watch is smaller - and in a different place - than any launch keynote claims. This desk tested step-count honesty on its own stairs, so it can say the following with numbers behind it.</p>
<h2>What the cheap band does at parity</h2>
<ul><li><b>Heart rate at steady effort.</b> The optical pulse sensor is the same physics at both prices, and during a walk or a run at constant pace, a good budget band tracks a chest-strap-grade watch within a few beats - it is at intervals, arm-swinging irregularity and cold skin that the cheap window drifts.</li>
<li><b>The alarm on your wrist.</b> The sleep-stage numbers are entertainment, and both tiers produce the same entertainment; the genuinely useful sleep feature is the vibration that wakes you without the phone across the room, and no tier does it better.</li>
<li><b>Step counts, at the same ratio:</b> both over-count while brushing teeth and under-count while pushing a stroller. For "more yesterday, tomorrow", either is honest enough - which is the only thing step counts were ever for.</li></ul>
<h2>Where the premium actually buys</h2>
<p>GPS without the phone is the honest dividing line - a watch with its own receiver maps the run while the band needs a shoeing phone in pocket; if you run free-handed, that is the purchase, full stop. After that: screens you can read in equatorial sun, cellular and contactless payment for the phone left at home, and training-load software for the second sport you now do. If none of those five describe your week, the band is the right size of wallet.</p>
<h2>The phone you already own is the control group</h2>
<p>Phone-in-pocket step counting is the reference these devices beat or match; and the phone's heart-rate absence is genuinely the one thing it cannot substitute. Before buying anything: walk a measured distance with the phone's app, check its number against the map, and ask what a wrist would change - usually the answer is "the pocket emptying at 5am", which is a real answer, and exactly the kind this desk prefers.</p>
<h2>The habit both tiers share</h2>
<p>A wearable changes nothing about the body; it changes the record. The only evidence-backed loop is: consistent time, a target you can see on a grey morning, and the streak you protect. Choose the device whose numbers you will actually look at daily, because the entry-price band with a daily habit beats the flagship in a drawer - and the desk's own stair test stands behind that sentence more than behind any spec sheet.</p>"""),

 ("inkjet-vs-laser-printer-nigeria",
  "Inkjet or laser for a Nigerian home office: the fault lines nobody warns you about",
  "Dried ink versus toner economics, the power-supply story neither box tells, and the one use case where inkjet wins outright.",
  """<p>The printer decision is bought with the wrong numbers: the box price and the pages-per-minute, when the actual budget lives in what dries, what jams, and what your local market stocks. Two technologies, two failure modes, and one honest recommendation table at the end.</p>
<h2>Why inkjet dies here</h2>
<p>Inkjet's head is a nozzle array measured in microns - and its enemy is a weekend, because when dye ink sits idle in an open nozzle it cements the head shut. Cleaning cycles are the machine's cough medicine; they drink your expensive ink doing it. In a home that prints ten pages on Monday and nothing until the 25th, this is the whole story - the printer does not run out of ink so much as silt up. Heat and harmattan static do the rest, and the cheap "refill" kits keep it alive in a bargain the manufacturer clearly did not intend but the market solved around.</p>
<h2>Why laser is usually the answer for documents</h2>
<ul><li><b>Toner is a powder that cannot dry.</b> A laser printer that sleeps two months prints page one identical to page two - the fault line on which office fleets are built, and the single strongest argument for a monochrome laser as the home document box.</li>
<li><b>The consumables story is upside down.</b> The drum and fuser are long-lived; toner cartridges are refillable at any counter for the price of a decent meal, and the "chip" locks that some models use have market workarounds the counter knows by heart.</li>
<li><b>The failure modes, honestly:</b> heat is the toner's enemy too - warped fusers and curled media in a hot room, and cheap third-party powder is a lottery; and the machine itself is heavier, pricier and bigger than the inkjet it replaces. A power surge takes the formatter board, not a head; it is still a board, and this desk's surge article is the companion page for exactly this reason.</li></ul>
<h2>Where inkjet wins, outright</h2>
<p>Photos on photo paper, and colour at all - the laser colour machines that make sense cost like a small appliance, and the cheap colour lasers are the market's own trap. Print a child's school posters or your own passport photos at the shop; but if a real colour document cadence exists in the house, the modern answer is the "ink tank" or EcoTank-class machine - bulk ink in, no cartridge, and a head the design assumes you will use weekly. The drying risk never leaves inkjet; the tank model just makes it cheaper to survive.</p>
<h2>The verdict, as a rule</h2>
<p>Documents and forms, sporadic week: mono laser, refill economy, zero drama. Photos or weekly colour: a tank-style inkjet, and print something every Friday as maintenance. One print a month, passport-sized: the shop, the queue, and no machine to defend. The machine that wins is the one whose fault you have already chosen to live with - the till is not where this decision is lost.</p>"""),

 ("surge-protector-stabiliser-ups",
  "Surge protected, stabilised or on a UPS: which box saves the TV, and which is a placebo",
  "Clamping voltage read in plain English, the Nigerian grid's three real threats, and the one thing no strip can fix.",
  """<p>Three boxes, one wall socket: the surge strip, the "voltage stabiliser" and the UPS all promise protection, all cost different money, and they defend against three different attacks. Buying the wrong one is how a lightning season becomes a dead TV with a healthy-looking fuse inside a protector.</p>
<h2>The three threats, named</h2>
<ul><li><b>The spike:</b> microseconds of over-voltage - lightning nearby, a transformer switching, the grid's own thunder. What kills electronics.</li>
<li><b>The brown-out:</b> sustained under-voltage - long harmattan-season sag while the compressor works harder and the PSU cooks. What ages electronics.</li>
<li><b>The black-out:</b> the zero that cuts mid-cycle, corrupts the file, drops the router, and ends the UPS conversation.</li></ul>
<h2>Which box does which job</h2>
<p><b>The surge strip</b> exists for one thing: the spike, absorbed by a metal-oxide varistor whose entire spec is "clamps at what voltage, and for how many joules." A MOV-rated strip with a real joule figure protects; a socket with a red light and a moulded shell is a power strip with anxiety relief bolted on. The honest test - the little "protected" lamp tells you the MOV is alive, and when it goes dark the strip is now ordinary - is the only maintenance this device asks, and it is why the indicator is not decorative.<br><br><b>The relay-type "stabiliser" box</b> handles the brown-out: it watches the line and switches taps inside a transformer to keep the output near nominal - with a visible, audible clunk, and a fraction-of-a-second of dropout per correction that modern switching supplies shrug off. It does nothing for a lightning spike beyond surviving it itself - the clunky box is the reason the TV still runs at 190 volts, and the reason the same TV still dies when the sky fires.</p>
<p><b>The UPS</b> is the only one that answers all three: battery-backed online or line-interactive boxes ride through the blackout, and a decent one filters spikes and sags on the way in. Its costs are the honest ones: the battery is a consumable on a two-to-four-year life in a warm room, and a "TV and decoder" line-interactive unit buys an orderly shutdown, not a movie marathon.</p>
<h2>What no box fixes: the earth</h2>
<p>Surge devices work by dumping energy to earth - and a Nigerian socket with an earth pin connected to nothing makes every protector in the house an expensive suggestion. If you buy one serious protection habit, it is this one: an electrician confirms the earth at the board and the socket you care about, because no clamp voltage survives the missing copper to the ground rod. Read the desk's wiring red-flags article for the visible signs that your earth is decorative before spending a kobo on boxes.</p>
<h2>The verdict, as a rule</h2>
<p>TV, decoder and console: a rated MOV strip with the indicator, on an earthed socket. A PC and router that cannot survive a mid-save blackout: a line-interactive UPS - the one appliance where the box earns its battery. A fridge or AC in a sago district: a motor-rated stabiliser, and nothing else near it. The grid will not tell you which night it brings which threat; the three boxes above are how you stop asking it.</p>"""),

 ("gaming-phone-vs-cooler",
  "The heat problem no spec sheet mentions: gaming phone, or the clip-on cooler?",
  "In a hot country the processor's story is a thermal one. What premium cooling actually buys, why the graphite era flopped upward, and the fan that fixes last year's flagship.",
  """<p>Every gaming phone pitch ends with the same sentence about the processor, and every gamer in a warm room knows the missing sentence: the chip does what it wants for about four minutes, then does what the weather allows. This is a thermal argument dressed as a spec argument, and the honest conclusion involves a second device that costs a fraction of the first.</p>
<h2>Why phones throttle here more than the review videos show</h2>
<p>A review written in an air-conditioned studio measures a phone that never met a 33-degree afternoon. The sustained frame rate your machine actually produces is governed by: ambient temperature, the cooling path (graphite sheet, vapor chamber, nothing), and the battery's own heat adding to the pot. Gaming phones answer the second item with hardware - vapor chambers, even a micro-fan in a few models - and the answer is real: they hold boost longer, in some titles twice as long as a same-chip regular phone. They do not answer the ambient, and nothing in a phone can.</p>
<h2>The clip-on cooler is the upgrade</h2>
<ul><li><b>What it is:</b> a small back-clip with a fan (and on the good ones a thermoelectric plate) that holds the phone's rear - where the SoC dumps its heat - below body temperature. It changes the physics: the phone's own cooling now has a cold side to push against, so boost clocks hold, and the frame-time spikes from thermal relief stop.</li>
<li><b>What it costs you:</b> it needs the phone's USB-C (check whether the model supports passthrough charging, or it will slowly drain while plugged), and it turns the device into a brick with wings - one-handed play ends. For the competitive session it is the right trade; for the commute game it is not.</li>
<li><b>What to believe in ads:</b> "30 degrees cooler" claims are measured on a cold phone in a cool room; the number that matters is whether it keeps your specific phone from downclocking after twenty minutes - and that is exactly what the desk's honest test protocol is: same map, same brightness, watch the frame time for half an hour with and without.</li></ul>
<h2>When the phone upgrade is actually the right money</h2>
<p>A gaming phone is a real thing for a real person: the one who plays emulated-heavy or gacha for hours daily, wants the shoulder triggers, and will use the cooler anyway. The trap is buying the gaming model's processor and paying for its LED back while your actual problem is an afternoon that feels like an oven - a normal flagship with the clip-on fan outperforms the gaming phone without it in most sustained sessions, because the thermal wall is the wall. And for the budget gamer, the free two first: lower the in-game frame target to 60 and brightness to what the sun allows; both are thermometers, not just settings.</p>
<h2>The verdict, as a rule</h2>
<p>Upgrade the phone when it cannot run the game at all; upgrade the cooling when it runs it hot. In a hot country the second need is permanent and the first is a lottery - which is why the desk has watched more clip-on fans save more gaming nights than more phones.</p>"""),

 ("data-shuttle-sd-usb-ssd",
  "The SD card, the thumb drive and the SSD: which one can carry the footage?",
  "Why the drive that returns the clips fine in the shop dies in the edit, the sustained-write trap, and the one format rule that saves the whole exchange.",
  """<p>Footage shuttling is the most deceptive purchase in the small-media market: every drive works in the shop, and the difference between them only appears at 40 gigabytes in, when the medium you chose has to keep writing while it is already nearly full, hot, and on its second hour. The three products are not three sizes of the same thing; they are three engineering briefs.</p>
<h2>Why cards fail at the job they were bought for</h2>
<p>SD and microSD are camera media first: they are tuned for the steady, one-stream write of recording, with cheap controllers and small caches. Copying the card to a computer is the opposite workload - thousands of files, random order - and a card that recorded 4K perfectly can crawl at read-out, then die from being asked forever. The killer detail: many "high capacity" cards at market prices are not just slow, they are counterfeit - the real capacity is a fraction and the drive lies about the rest, which is how footage vanishes with the card insisting it has free space.</p>
<h2>The thumb drive's trap and the SSD's real advantage</h2>
<ul><li><b>The USB stick</b> is the same cheap-flash-for-small-files brief as the card, shaped differently. A good one bursts; then it runs out of cache and sustained write falls through the floor - you have watched that progress bar stop at 87 percent, and that is what it is.</li>
<li><b>The portable SSD</b> (or bare SATA/NVMe drive in a good enclosure) exists for exactly this: more NAND, better controller, bigger or unnecessary cache because the drives keep writing at honest speed while warm. The two honest failure modes: no-name enclosures that overheat and throttle, and the cable that "works sometimes" - a flaky USB-C cable corrupts in a way that reads like drive failure. Budget the good cable.</li></ul>
<h2>The format rule that ends most of the arguments</h2>
<p>Anything that moves between a camera, an editor's laptop and the client's TV should be exFAT - the only common language of Windows, macOS and modern cameras - and should be formatted in the device that will read it most (the camera, for cards). NTFS reads on Macs but does not write; Mac-only formats are invisible on the editor's Windows box; and a card re-formatted on a computer every week is a card with a shorter life, because the quick format on the camera is the filesystem the firmware expects.</p>
<h2>The buying rule, as a card</h2>
<p>Cards: brand, from a shop that stocks spares, matched to the camera's speed class - and burned like batteries, not heirlooms. Thumb drives: for documents and one-off clips, never for the shoot. SSDs: the shuttle, bought from a brand the repair counter knows. And the habit above every product: the copy happens at both ends (your card to your drive before it leaves the location), because every one of these media is a container of maybes - the only thing in this article that never fails is the second copy.</p>"""),

 ("new-router-for-slow-internet",
  "Your internet is slow and the fix is not a new router: the bottleneck triage",
  "Three tests that tell you whether the router is even in the crime, the 'Wi-Fi 6 will save me' myth, and what to buy instead when it isn't.",
  """<p>The router counter will happily sell you the box that cannot fix this, because "internet slow" and "router weak" feel like the same sentence - and they are two different faults with two different shops. Run the triage first: it is free, it takes ten minutes, and it changes the purchase from a gamble to a receipt.</p>
<h2>The ten-minute triage</h2>
<ul><li><b>Test A - wire past the router:</b> one ethernet cable from the ISP's box (the ONT, the 4G router itself) to a laptop. Speeds jump to what you pay for? The problem was your Wi-Fi distribution - the router section below is about you. Speeds are still slow at the same number as on Wi-Fi? The router is innocent; stop shopping for one.</li>
<li><b>Test B - one device, one time:</b> all speed tests on a single device while the rest of the household is off the network. A family of five streaming is a bandwidth problem with no product answer; the desk's advice there is a conversation, not a box.</li>
<li><b>Test C - the evening curve:</b> fast at 6am, crawling at 9pm is cell congestion (if on 4G/5G) or shared-line congestion - the mast and the ISP's plan are the suspects, not your antenna.</li></ul>
<h2>What "Wi-Fi 6 for a slow line" actually does</h2>
<p>Nothing to the pipe; possibly something to the house. A newer router buys you: capacity under many devices, better battery behaviour for phones, and range from the newer antenna designs. It does not buy a single kilobyte if the ceiling is above your incoming line - a router cannot deliver what the ISP never sent. The real reasons a decent modern router is still the right purchase: a five-year-old box with an overheating power supply, a family where forty devices now share what twelve used to, or the same-dumb-ISP-line with a house whose layout defeated the old radio. Each of those is a distribution problem, and the fix must match it: placement before hardware (the centre-high spot, away from the metal shelf and the TV), channel work (the free scan from any phone), and a second access point over a long cable when one radio is asked to cross a concrete slab - the desk's extender-vs-router article covers that decision at length.</p>
<h2>The buy list, if you still buy</h2>
<p>Gigabit ports (not "100M" on the spec page - the silent limiter that makes a new router useless to a fibre day), a real QoS or device-priority feature if the household argues about the evening, and support for the security updates that keep it honest for five years - the last one means a brand with a reputation, which is also where the manual and the firmware archive live. And the desk's non-negotiable: change the admin password on day one. The router nobody secured is the reason a street of them goes slow at 2am.</p>"""),

 ("one-big-monitor-vs-two",
  "One big screen or two small ones: the desk decision nobody makes on specs",
  "Panel size maths, the window manager is the real spec, and the port that decides whether the dream setup is a cable or a circus.",
  """<p>The monitor decision is a desk decision wearing a spec-sheet costume: how you work decides how many panels you want, and the two ways to get a big workspace - one wide display or two normal ones - differ on the three things that end up mattering: windows, cables and the gap.</p>
<h2>The one-screen case</h2>
<p>A 34-inch ultrawide replaces the dual setup with a seamless desk and one cable in (via USB-C on the good ones - power, display and data in a single wire, which also turns a laptop into a desktop in one motion). The honest physics: a curved ultrawide is wide enough to see two full document-and-browser columns side by side, and the screen you do not have to think about is the one your eyes and window manager never trip on. The catch list: games and video get black bars (21:9 does not match 16:9 content), text at the far edges of a cheap panel is mush, and a wide single panel is one bad pixel from being a complaint, not a purchase - the pixel policy on the box matters as much as the size.</p>
<h2>The two-screen case</h2>
<p>Two 24s give you: cheaper money per inch, the ability to move reference-and-work to eyes-off angles, and - underrated - one fails, the other still works. The bezel gap is the tax: you pay it in the centre of your main app forever, and window snapping becomes a hobby. Two identical panels, both on the same height with the arms or stands aligned, is the version where the setup stops being a project; two mismatched panels are two window managers in a fight.</p>
<h2>The port and cable truth</h2>
<ul><li><b>One cable to the laptop (USB-C with DisplayPort Alt Mode) beats an HDMI zoo</b> - it is the difference between a desk and a cable show. Check the laptop's port actually does display, not just charge; the little "D" or lightning mark beside the port is the answer, the port's shape is not.</li>
<li><b>Daisy-chain (a second monitor off the first) needs the right generation of DisplayPort and a laptop that supports it</b> - it is elegant when it works and invisible in the spec sheet when it will not.</li>
<li><b>Matter that beats marketing here:</b> height adjust with the top of the screen at eye line, a matte finish for the Lagos window light, and a refresh rate of 75-100Hz - the cursor smoothness is felt in the wrist within a week, and it is the one spec the desk would die on a budget.</li></ul>
<h2>The verdict, as a rule</h2>
<p>Coding, writing, any two-apps-at-once life where a visible seam would nag: one good ultrawide with USB-C. Video editing with a timeline-and-preview split, or the work-and-a-second-reference-life where the reference should sit off-angle: two aligned panels, same model, both at the same height. Either way the 11/10 advice is the boring one the sales floor never mentions - the monitor is the least important thing in your view; the chair height is what actually ends the neck ache.</p>"""),

 ("esim-vs-sim",
  "eSIM vs the physical SIM: what the invisible card actually buys you",
  "Dual lines, travel that starts at the airport, and the two real costs - the swap friction and the carrier's fine print. No hype, just the mechanics.",
  """<p>An eSIM is a SIM with a mail slot: the carrier writes its credentials into a chip soldered in your phone, and the whole relationship that used to be a plastic card becomes a profile that can be added, left, and removed. That is the entire invention - and both the promises and the annoyances fall straight out of it, once you walk the mechanics.</p>
<h2>What it genuinely buys</h2>
<ul><li><b>The dual-line phone becomes two lines for real:</b> most eSIM-capable phones keep one or two profiles active alongside a physical slot, so the work line and the personal line live in one device without a dual-SIM tray, and the second stays invisible to the thief who pulls the first.</li>
<li><b>Travel data without the market detour:</b> the arrival-day SIM-swap becomes an app download at the gate - the short-list of local data plans in a foreign country is bought by QR code before you leave, and the home number keeps receiving OTPs on the other line while you are abroad. For the desk's readers who fly for work, this is the feature in one sentence: you stop borrowing phones to receive your own codes.</li>
<li><b>Activation logistics:</b> no card size to guess, no network outage because the shop's SIM stock ran out, and a lost phone is one carrier call to lock the profile - the number cannot be pulled and used in another handset while you do it. That last point is the security line most people never think about.</li></ul>
<h2>What it genuinely costs</h2>
<p><b>Swap friction, inverted:</b> the card you can move to a new phone in ten seconds is now a conversation with two carriers - eSIM transfers depend on whether your operator supports re-issuing the profile to a new device, and in markets where that support is thin, the phone breaks into "bring your own problem" land the week the handset dies. <b>The burn rule:</b> profiles can usually be deleted but not always reused, so a careless reset or a factory restore can mean a new plan before the phone is even unlocked. And <b>the QR is the contract:</b> that code is your line - photograph it and keep it in your password manager, because "the shop has my QR code" is a story with two endings, and neither is quick.</p>
<h2>The verdict, as a rule</h2>
<p>If your phone and your main carrier both support it, keep one line on the eSIM as the travel and dual-number workhorse and one physical card as the anchor - the hybrid setup buys every advantage with none of the stranded-phone risk. And for the traveller, the desk's firm word: check the fine print on what happens to your profile when the handset dies, before a trip makes it your problem - the invisible card is great until the day it needs a paper trail.</p>"""),

 ("blackout-internet-router-power",
  "The blackout that takes your Wi-Fi with it: why the phone stays up and the router drops",
  "The fibre/4G box is the one appliance you forgot on the mains. The power-bank bridge, the boot order for a genset, and the amp-draw maths for a router plus ONU.",
  """<p>Every generator plan has the same hole in it: the house has power again and the internet does not, because the fibre's little white box (the ONT) or the 4G router is the appliance nobody counts as a load. The phone keeps working because its battery is inside it; your connection keeps working only if you give it the same courtesy.</p>
<h2>The two-box problem</h2>
<p>A wired connection is a chain with two powered links: the carrier's box (ONT or mobile router) and your Wi-Fi router. A blackout drops whichever one sits behind the meter you switched off, and most homes lose both while the mast outside the house keeps running on its own backup. So the fix is a list of watts, not a brand: a typical ONT is a few watts, a mid-size router on its own charger a handful more - double digits total, which puts a whole night of connectivity in the range of a good power bank, and the desk's power-bank article covers the conversion maths (the Wh number is the fuel tank, the watts are the thirst, divide for hours).</p>
<h2>The bridge, three ways, in money order</h2>
<ul><li><b>The cable-swap trick:</b> most small carrier boxes accept 5V USB power or a DC barrel that an adapter cable pretends is a USB wall - a power bank through the right adapter runs the box through the outage, zero new hardware if you already own the brick.</li>
<li><b>The mini-UPS:</b> the small "router UPS" class of device - a battery dongle inline with the existing barrel plug - exists exactly for this job: it keeps the link alive through a short outage and, on the long ones, buys hours while the genset is what runs the rest of the house. Check the output voltage list before buying - 5V/9V/12V selectable covers the boxes; a fixed 12V on a 5V-only ONT is a paperweight.</li>
<li><b>Inverter-loop it:</b> if the house has an inverter, the router's and ONT's chargers go on the inverter circuit - which they already were on some installs, which is why the house has power and no internet: the switchboard's ring main forgot the one desk on the wall. The electrician's five minutes is the cheapest permanent fix on this list.</li></ul>
<h2>The boot order that saves a minute every time</h2>
<p>Power back is not the end: a router that boots before the carrier link is stable spends its first minute in a retry loop, and the fibre's handshake is slower than both. The order is: carrier box first, wait for its status light to settle (the PON/link lamp steady, not blinking), then the router. Genset owners: the box's switching power supply does not care about the generator's waveform, but a cheap phone-charger-style brick may, and a flickering router is a brown-out tell before it is a fault. Internet is a chain of appliances; treat the two boxes like the fridge - on the power you planned for, not the one you remembered.</p>"""),

]
