# BRYME Tech — the no-panic security checklist (batch 52, 13 Sep 2026).
# Directive Tech tool queue: security checklist built FIRST (assets/security-checklist.js).
# Desk-firsthand content (evergreen habits, no rotting stats); links only to
# existing safety-desk articles (all verified live this session). Desk byline;
# no invented reviewer. General guidance, never a security guarantee.

SC_SLUG = "your-security-checklist"

SC_BODY = """<div class="prose">
<p class="byline">BRYME Tech desk \u00b7 published 13 September 2026 \u00b7 evergreen habits, no rotting numbers \u00b7 general information, never a security guarantee</p>
<p><b>The 60-second answer.</b> Personal security in 2026 is not a product you buy \u2014 it\u2019s five habits that carry almost all the weight: <b>unique logins generated by a password manager</b>, <b>2FA with an app rather than SMS</b>, <b>automatic updates on</b>, <b>backups you could actually restore</b>, and <b>the two-second pause before clicking links or moving money</b>. Do those five and you are safer than the vast majority of people \u2014 including most people paying for \u201cpremium security\u201d bundles. The scorecard below turns that into a number: sixteen weighted checks across five groups, and it hands you your <b>next three moves</b> every time.</p>

<h2 id="scorecard">The scorecard</h2>
<div id="security-checklist-calc"></div>
<noscript><p><b>Static version \u2014 if you only do five things, in order:</b> 1) Turn 2FA on your main email (it\u2019s the reset key to everything). 2) Put unique, manager-generated passwords on your accounts. 3) Switch on automatic updates for your devices and browser. 4) Set up automatic backup of files you can\u2019t replace. 5) Adopt the pause: never move money or enter passwords from an unexpected call, text or link \u2014 go to the official app or type the official address yourself.</p></noscript>

<h2 id="five">Why those five carry everything</h2>
<ul>
<li><b>Email first.</b> Whoever controls your email can reset almost every account you own. 2FA there is the cheapest giant win in security (<a href="/tech/two-factor-authentication-setup/">2FA done right</a>).</li>
<li><b>Unique logins.</b> Breaches you can\u2019t prevent; reuse is what turns one breach into ten (<a href="/tech/best-password-manager-for-you/">pick a manager</a>, or weigh the honest <a href="/tech/password-manager-or-browser/">manager-vs-browser</a> trade-offs).</li>
<li><b>Updates.</b> They\u2019re shipped fixes for holes attackers already use. An un-updated device is choosing last month\u2019s locks.</li>
<li><b>Backups.</b> The only control that saves you from ransomware, theft, fire and \u201cthe cat walked on the keyboard\u201d alike \u2014 if you\u2019ve ever tested a restore (<a href="/tech/cloud-storage-mistakes/">the cloud mistakes to avoid</a>).</li>
<li><b>The pause.</b> No tool beats a human who checks a link before clicking (<a href="/tech/how-to-spot-a-suspicious-link/">how to spot one</a>) and refuses to move money on an unexpected call.</li>
</ul>

<h2 id="leftout">What this checklist deliberately leaves out</h2>
<ul>
<li><b>\u201cHave a VPN\u201d is not a checkbox.</b> It\u2019s the right tool on hostile networks and barely matters at home \u2014 the scenario-by-scenario honesty lives in <a href="/tech/vpn-and-password-safety-table/">the safety table</a> and <a href="/tech/vpn-what-it-protects/">what a VPN protects</a>.</li>
<li><b>No paid \u201csecurity suite\u201d line.</b> Modern operating systems ship capable built-in protection; the paid bundles mostly sell you fear with a dashboard. Spend the money on a manager\u2019s family plan instead.</li>
<li><b>No fear points.</b> The scorecard weights what attackers actually use \u2014 reused passwords, missing 2FA, un-updated devices, panicked payments \u2014 not exotic threats that make headlines but not breaches.</li>
</ul>

<h2 id="faq">FAQ</h2>
<p><b>How secure am I, really?</b><br>
Run the scorecard \u2014 it\u2019s weighted by what actually gets exploited. 100% is achievable in one focused evening; anything above 80% means what\u2019s left is finishing work, not exposure.</p>
<p><b>What should I secure first?</b><br>
Your main email. It\u2019s the reset key to everything else \u2014 2FA there plus a unique password protects every account that can \u201cforgot password\u201d through it.</p>
<p><b>Do I need antivirus in 2026?</b><br>
On phones and current Windows/macOS, the built-in protection is competent \u2014 your habits (updates, the pause, downloads from official stores) do the heavy lifting. Treat paid suites as optional comfort, not protection.</p>
<p><b>How often should I re-check?</b><br>
After any new device, app with money access, or life change (new number, new address, new people with account access) \u2014 and otherwise twice a year. The scorecard takes two minutes.</p>
<p><b>Is public Wi-Fi safe now?</b><br>
It depends what you\u2019re doing \u2014 that\u2019s exactly why it isn\u2019t a checkbox here. The honest per-scenario answer: <a href="/tech/vpn-and-password-safety-table/">the safety table</a>; the risks themselves: <a href="/tech/public-wifi-risks/">public Wi-Fi risks</a>.</p>

<script type="application/ld+json">
{"@context":"https://schema.org","@graph":[
{"@type":"Article","headline":"The no-panic security checklist - score your setup in two minutes",
"description":"Sixteen weighted checks across accounts, devices, browsing, money and backups - with your next three moves every time. Evergreen habits, no fear, no paid-suite sales.",
"author":{"@type":"Organization","name":"BRYME Tech desk"},
"publisher":{"@type":"Organization","name":"THE BRYME"},
"datePublished":"2026-09-13","dateModified":"2026-09-13"},
{"@type":"FAQPage","mainEntity":[
{"@type":"Question","name":"How secure am I, really?","acceptedAnswer":{"@type":"Answer","text":"Run the weighted scorecard - it measures what actually gets exploited: reused passwords, missing 2FA, un-updated devices, panicked payments. 100% is achievable in one focused evening."}},
{"@type":"Question","name":"What should I secure first?","acceptedAnswer":{"@type":"Answer","text":"Your main email. It is the reset key to everything else - 2FA there plus a unique password protects every account that can reset through it."}},
{"@type":"Question","name":"Do I need antivirus in 2026?","acceptedAnswer":{"@type":"Answer","text":"On current phones, Windows and macOS the built-in protection is competent. Your habits - updates, the pause before clicking, official app stores - do the heavy lifting. Paid suites are optional comfort."}},
{"@type":"Question","name":"How often should I re-check my security?","acceptedAnswer":{"@type":"Answer","text":"After any new device, app with money access, or life change - and otherwise twice a year. The scorecard takes two minutes."}},
{"@type":"Question","name":"Is public Wi-Fi safe now?","acceptedAnswer":{"@type":"Answer","text":"It depends what you are doing, which is why it is not a checklist item. Use a scenario-by-scenario guide: VPNs earn their keep on hostile networks and barely matter at home."}}]}]}
</script>

<p class="byline">Reviewed 13 September 2026 \u00b7 written from this desk\u2019s own builds and breakages \u00b7 security guidance is general information, never a guarantee \u00b7 no professional reviewer is claimed.</p>
</div>
<script src="/assets/security-checklist.js" defer></script>"""

NEW_SC_GUIDES = [
(SC_SLUG, "safety", "guide",
"The no-panic security checklist \u2014 score your setup in two minutes",
"Sixteen weighted checks across accounts, devices, browsing, money and backups \u2014 a live score and your next three moves, every time. No fear, no paid-suite sales.",
SC_BODY,
[("BRYME Tech desk - first-hand, companion pieces in /tech/safety/", "/tech/best-password-manager-for-you/")],
[("best-password-manager-for-you", "Choosing a manager"),
 ("two-factor-authentication-setup", "2FA done right")]),
]
