# BRYME Tech — the troubleshooting library (batch 28, 11 Sep 2026).
# Master Pack §3.1.2 priority builds + §4.1 template:
# symptom → likely causes (ordered) → diagnosis → fix → when the fix won't work → escalation → official docs (dated).
# First-hand claims are genuinely ours: this site is the evidence (Render deploys, the DNS saga, cert issuance, the sitemap validator).

TROUBLESHOOTING_GUIDES = [
("website-wont-deploy-fix", "web-and-hosting", "troubleshooting",
"Why won't my website deploy? The diagnostic tree",
"Build red, build green but the site wrong, or nothing happening at all — the three failure families, in the order that finds the cause fastest.",
"""<p><b>The symptom:</b> you push, and your site does not update. Or the deploy fails. Or it "succeeds" and serves something wrong. Before touching a single setting, sort the failure into one of three families — because each has a different first suspect, and testing in the wrong family wastes hours.</p>
<h2>Family 1: the build fails</h2>
<p><b>Likely causes, most common first:</b> a dependency problem (missing package, version pinned differently locally than in CI — <em>very common</em>); an environment variable the build needs but the platform does not have (<em>common</em>); a build command that works interactively but not in a clean checkout (wrong working directory, global tools, case-sensitive filenames — <em>common on Windows-authored projects</em>); Node/Python version mismatch (<em>occasional</em>).</p>
<p><b>Diagnosis:</b> read the build log bottom-up — the first error is usually above a wall of noise, but the <em>last</em> error is the fatal one; work between them. Then reproduce in a clean checkout: clone fresh, install, run the exact build command the platform runs. If it passes locally and fails remotely, it is an environment difference (versions, env vars, case). We debug our own builds exactly this way — this desk's builder once failed on a missing data key that only existed on our machines, and the clean-checkout rule found it in minutes.</p>
<p><b>Fix:</b> pin your runtime version in the repo (a <code>.node-version</code>/<code>runtime.txt</code>-style file); commit every env var the build needs into the platform's settings (never the repo); make the build command runnable from a fresh clone by a stranger.</p>
<h2>Family 2: the build passes but the site is wrong</h2>
<p><b>Likely causes:</b> the publish directory points at source instead of generated output (<em>the</em> classic); a redirect or header rule at the host shadowing your expectations; caching — the CDN or your browser serving the previous deploy; the deploy quietly serving the last good build after a later failure (static hosts do this by design — resilience that hides breakage).</p>
<p><b>Diagnosis:</b> hard-refresh with cache disabled, then check the deploy log's timestamp against the change you expect. Curl the exact URL and look at the bytes, not the browser. If the bytes are old, you are either looking at the wrong publish directory or the deploy did not actually succeed — the build badge and the log, never the homepage, tell you the truth.</p>
<h2>Family 3: nothing happens at all</h2>
<p><b>Likely causes:</b> the push never triggered a build (wrong branch watched — <em>very common</em>); the Git integration lost authorization; you are pushing to a fork/remote the platform is not watching.</p>
<p><b>Diagnosis:</b> confirm the commit is on the branch the platform watches (<code>git log origin/main</code> is your friend), then trigger a manual deploy. A manual build that works means the automation is the problem; one that fails means it was Family 1 all along.</p>
<h2>When this fix will not work</h2>
<p>If a clean checkout, pinned versions, committed env vars and a watched branch all check out and the build still fails in a way you cannot reproduce locally, you may be hitting a platform-side limit (build minutes, memory on the build image). Keep the log excerpt — you will need it. And if the site serves but a <em>path</em> is wrong while the root works, that is routing, not deployment: check redirects before rebuilding anything. The deeper post-mortems from real failures live in <a href="/tech/render-deployment-failures-what-they-taught-me/">what Render deployment failures taught us</a> and the full <a href="/tech/render-static-deploy/">Render static deploy walkthrough</a>.</p>
<h2>When to escalate</h2>
<p>After a reproducible log, a clean-checkout test, and a status check on the platform's own status page — that is the evidence package support (or a forum) needs. Posts without the log get guesses; posts with it get answers.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Render deploys &amp; troubleshooting (render.com/docs), GitHub Pages usage limits and troubleshooting (docs.github.com/pages), and your platform's build-log reference.</p>"""),
("dns-not-working-propagation", "web-and-hosting", "troubleshooting",
"Why does DNS not work — and why do changes 'take so long'?",
"Wrong records, caching layers, and the registry itself: how to find which layer is lying to you, and what propagation actually is.",
"""<p><b>The symptom:</b> you changed a DNS record, and part of the world still sees the old one. Or a brand-new domain simply does not resolve at all. DNS feels mystical mostly because there are five layers between your typing and the internet's answering, and any one of them can be the one that is out of date. Name the layer, and the mystery dies.</p>
<h2>Likely causes, most common first</h2>
<p><b>1. The record itself is wrong</b> (<em>very common</em>): a typo in the hostname or target; an A record where a CNAME was needed (or the reverse — CNAMEs cannot coexist with other records on the same name); an apex domain given a CNAME, which many providers forbid or flatten specially.</p>
<p><b>2. Caching, at the resolver</b> (<em>very common</em>): records carry a TTL — "time to live" — and resolvers keep answers until it expires. A low TTL (60–300 seconds) spreads changes fast; a high one (hours to a day) is why your aunt still sees the old site.</p>
<p><b>3. Your own device's cache</b> (<em>common during testing</em>): operating systems and browsers cache answers too; you are sometimes the stale one.</p>
<p><b>4. Nameservers not pointing where you think</b> (<em>common after a registrar or host change</em>): the records you are editing live at one provider, but the domain's nameservers point at another. You are carefully updating a record nobody reads.</p>
<p><b>5. The registry itself</b> (<em>rare, but the deepest</em>): the domain is expired, on hold, or not fully registered — no DNS anywhere can answer for it. We know this failure intimately: this site's own domain spent weeks not existing <em>at the registry level</em> while nameserver configuration sat correct at every provider — a reminder that the layer you can edit is not always the layer that is broken.</p>
<h2>Diagnosis: interrogate each layer</h2>
<p>Ask a public resolver directly: <code>dig yourdomain.com @1.1.1.1</code> (or an online equivalent). If the authoritative nameservers answer correctly but resolvers do not, it is caching — check the record's TTL and wait it out, or lower TTLs <em>before</em> the next change (the professional's habit). If the authoritative servers answer wrongly, fix the record at that provider. If nobody answers, check the domain's status at a registry whois lookup (ICANN Lookup): <code>clientHold</code>, <code>serverHold</code> or a missing delegation means the problem is above DNS entirely. Then compare two independent resolvers (say 1.1.1.1 and 8.8.8.8) — agreement means propagation is done, however your browser feels.</p>
<h2>The fix, in the right order</h2>
<p>Lower TTLs a day ahead of planned changes → make the change at the provider the nameservers actually point to → verify at the authoritative nameservers → let caches age out (minutes for low TTLs, up to a day or more for high ones) → only then troubleshoot "downstream" things like certificates, which need working DNS before they can issue at all — see <a href="/tech/ssl-certificate-not-issuing/">why your certificate will not issue</a>.</p>
<h2>When this fix will not work</h2>
<p>A registry hold only your registrar can lift; DNSSEC configured at the registrar but wrong at the host (validation failures look like total non-existence); and enterprise networks pinning their own resolvers with long caches — nothing you control fixes the last one fast, which is why propagation checkers that sample many networks exist.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Cloudflare's DNS learning library (cloudflare.com/learning/dns), ICANN Lookup (lookup.icann.org), and your registrar's DNS status reference. The fuller primer: <a href="/tech/what-is-dns/">what DNS actually is</a>, and the order-of-operations that avoids downtime in <a href="/tech/custom-domain-dns-order/">custom domains: the DNS order</a>.</p>"""),
("ssl-certificate-not-issuing", "web-and-hosting", "troubleshooting",
"Why is my site still not HTTPS? Certificate problems, in order",
"DNS first, CAA second, coverage third: why certificates fail to issue, and why the padlock can still say 'Not secure' on a working site.",
"""<p><b>The symptom:</b> your host promises free automatic HTTPS, and hours later the browser still warns, or the certificate simply never appears. Certificate issuance is a robot verifying control of your domain — and robots are literal. When it fails, it is almost always one of five things, in this order of frequency.</p>
<h2>Likely causes, most common first</h2>
<p><b>1. DNS is not actually pointing yet</b> (<em>the most common by far</em>): certificate authorities verify domain control by resolving your hostname. If DNS has not propagated — or resolves to the wrong place — issuance cannot start. No amount of host-side retrying fixes a record that does not answer; fix DNS first (<a href="/tech/dns-not-working-propagation/">the DNS diagnostic</a>), and issuance usually follows on its own.</p>
<p><b>2. You are looking at the wrong name</b> (<em>common</em>): a certificate that covers <code>example.com</code> does not automatically cover <code>www.example.com</code> (or vice versa). The browser visiting the uncovered variant sees a name-mismatch error while the other variant works perfectly.</p>
<p><b>3. A CAA record blocks your issuer</b> (<em>occasional and confusing</em>): CAA records name which certificate authorities may issue for the domain. If one exists and your host's CA is not on the list, issuance fails with an error that mentions authorization, not CAA — unless you know to look.</p>
<p><b>4. Mixed content</b> (<em>very common, and not an issuance problem at all</em>): the certificate is fine, but the page loads images or scripts over <code>http://</code>, so the browser still flags it "Not secure". The padlock tests the whole page, not just the connection.</p>
<p><b>5. Issuance delay or rate limits</b> (<em>occasional</em>): brand-new hostings can take a little while to request and receive certificates; authorities also rate-limit repeated failed attempts — hammering "renew" can make things worse.</p>
<h2>Diagnosis, safely</h2>
<p>Click the padlock (or the warning) and read the certificate detail: the browser tells you whether the cert is missing, expired, or for a different name — three different diseases. Then check the domain with an online SSL checker or <code>openssl s_client -connect yourdomain.com:443</code> to see what is actually being served. Confirm DNS answers first — certificate robots check it the same way. Search the domain's DNS for CAA records before suspecting the host.</p>
<h2>The fix, in the honest order</h2>
<p>DNS answers correctly → both variants (apex and www) covered by the host's certificate settings → CAA records either removed or listing your host's CA → trigger issuance once, then wait the provider's stated window → if the padlock still complains, audit the page for <code>http://</code> resources (the browser console lists every one) and fix those references. On this very site, the managed certificates issued without drama precisely because DNS was verified first — the boring order is the fast one.</p>
<h2>When this fix will not work</h2>
<p>Hosted names that cannot get public certificates (internal <code>.local</code>-style names); free hosting tiers with per-domain issuance limits; and browser-trust problems on very old devices — where the certificate is valid but the device's trust store is a decade stale. The last one is the environment's problem, not yours.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Let's Encrypt's docs on rate limits and CAA (letsencrypt.org/docs), MDN on mixed content (developer.mozilla.org), and your host's certificate/HTTPS reference. For what the certificate actually asserts, see <a href="/tech/what-is-ssl-https/">what SSL/TLS and HTTPS really are</a>; for the errors browsers show, <a href="/tech/ssl-certificate-errors-explained/">certificate errors, explained</a>.</p>"""),
("website-not-indexing-google", "explainers", "troubleshooting",
"Why is my site not on Google? An indexing diagnostic",
"From 'site:' to Search Console: the nine checks in the order that finds the blocker — and the honest truth about new sites.",
"""<p><b>The symptom:</b> the site (or one page) is live, loads fine in a browser, and simply does not appear on Google. Indexing is where most site-owners lose weeks to the wrong fixes. The diagnostic order below finds the actual blocker, from hardest block to softest.</p>
<h2>Step 1: ask Google what it thinks</h2>
<p>Search <code>site:yourdomain.com</code>. Results exist but the page is missing? That is a per-page problem. No results at all? That is a site-wide one — proceed in order. Then open <b>Google Search Console</b> (free), verify the site, and use URL Inspection on the exact page: Google states directly whether the URL is indexed, and if not, names the reason. Everything after this step is faster with Search Console open; its coverage report is the single most honest instrument in SEO.</p>
<h2>Likely causes, most common first</h2>
<p><b>1. The page says "noindex"</b> (<em>very common after redesigns/migrations</em>): a <code>&lt;meta name="robots" content="noindex"&gt;</code> left over from staging, or an <code>X-Robots-Tag</code> header doing the same silently. View-source and check; header checkers show the header variant.</p>
<p><b>2. robots.txt blocks crawling</b> (<em>common</em>): a <code>Disallow</code> aimed at staging that survived launch. Note the subtlety: robots.txt stops <em>crawling</em>, noindex stops <em>indexing</em> — and a page blocked from crawling can still appear as a bare URL if someone links to it. Fix them in that order: unblock crawl, and let (or tell) Google index.</p>
<p><b>3. The page is not reachable as a link</b> (<em>common on small sites</em>): Google finds pages chiefly by following links. If nothing internal links to the page and it is not in the sitemap, it may simply never be discovered. Every page on this desk sits in a sitemap and at least one shelf — internal linking is indexing plumbing, not decoration.</p>
<p><b>4. Canonical points elsewhere</b> (<em>occasional</em>): the page declares <code>rel=canonical</code> to another URL, and Google obeys. Check that the canonical is the page itself (or deliberately the preferred twin).</p>
<p><b>5. The sitemap is stale or wrong</b> (<em>common</em>): sitemaps that list pages which redirect or 404 teach Google to distrust them. The honest pattern this desk ships: every page in the sitemap exists, is canonical, is indexable — enforced by a validator at build time, so drift is impossible. A sitemap is a promise; keep it machine-checked.</p>
<p><b>6. It is simply too new</b> (<em>the honest one</em>): new domains can take days to weeks for a first crawl and indexing; sitemap submission in Search Console plus one real external link shortens the wait. Nothing you buy accelerates it — anyone selling "instant indexing" is selling noise.</p>
<p><b>7. Quality filters</b> (<em>the uncomfortable one</em>): thin, duplicated or scraped pages can be crawled and deliberately left out of results. The fix is the hard one: make the page deserve the query — the question this desk applies to every page before publishing is whether a real person would bookmark it.</p>
<h2>When the fix will not work</h2>
<p>Manual actions (visible in Search Console) and security hacks require a reconsideration process, not a tag change. And no diagnostic fixes a page whose answer nobody searches for — indexability is necessary, never sufficient.</p>
<p><b>Official documentation (checked 11 September 2026):</b> Google Search Central's indexing and crawl-management docs (developers.google.com/search/docs) and Search Console Help (support.google.com/webmasters). Companions on this desk: <a href="/tech/check-if-google-indexed-your-page/">check if Google indexed a page</a> and <a href="/tech/sitemap-indexnow/">sitemaps and IndexNow, explained</a>.</p>"""),
]
