# -*- coding: utf-8 -*-
"""Tech master build M3 — companion articles for BRYME Tools (5 pieces, Sept 2026).

Sources are the primary standards documents (stable RFCs / IANA registry), cited in-piece
and linked in sources. Tools live at /tech/tool/<slug>/ and are linked from bodies only
(related[] lists take guide slugs — the renderer path appends /tech/<slug>/).
"""

TECH_MASTER_M3 = [

("what-is-json", "coding", "guide",
"What JSON actually is (and why every API speaks it)",
"The data format that quietly runs the modern web: objects, arrays, the strict little syntax rules, and the errors everyone makes.",
"""<p>JSON is how machines pass structured data around in plain text. An API answering "who is this user?", a configuration file, a browser saving your preferences &mdash; underneath, very often, is a snippet of JSON. It stands for JavaScript Object Notation, and its origin explains its shape: it is literally the way JavaScript writes its own objects, adopted by everything else because it is simple, human-readable and unambiguous.</p>
<h2>The whole language in five lines</h2>
<p>JSON has exactly a few building blocks: <strong>objects</strong> (curly braces holding <code>"key": value</code> pairs), <strong>arrays</strong> (square brackets holding an ordered list), <strong>strings</strong> (always double quotes), <strong>numbers</strong>, and the literals <code>true</code>, <code>false</code>, <code>null</strong>. Nest them and you can describe almost anything: an object for a user containing an array of orders, each an object of its own. That is the entire language &mdash; which is precisely why it won. There is no versioning drama, no schema you must learn first; the format is defined by one short standards document, RFC 8259.</p>
<h2>The strictness everyone trips on</h2>
<p>JSON looks forgiving and is not. The rules that catch people daily: keys and strings use <strong>double quotes only</strong> &mdash; single quotes are invalid; <strong>no trailing commas</strong> &mdash; the last item in an object or array must not be followed by one; and <strong>comments do not exist</strong> in JSON, full stop (config formats that allow them, like YAML or JSON-with-comments flavours, are different formats). When a parser rejects your file, it is usually one of those three, and the error message points at the exact character &mdash; which is why the practical workflow is: paste, format, read the error position. <a href="/tech/tool/json-formatter/">The JSON formatter on this site does exactly that</a>, in your browser.</p>
<h2>Why it beat XML</h2>
<p>The previous answer to this problem was XML &mdash; angle-bracketed, verbose, and heavy with ceremony. JSON describes the same data in a fraction of the characters, maps directly onto programming-language data structures, and needs no closing tags. The industry's migration was less a decision than a relief. XML survives where documents (not data) are the product; everywhere else, APIs speak JSON by default.</p>
<h2>The two jobs to know</h2>
<p><strong>Parsing</strong> turns JSON text into live data structures your code can use; <strong>serialising</strong> turns your structures back into text to send or store. Every serious language has both built in (<code>JSON.parse</code> and <code>JSON.stringify</code> in JavaScript, the <code>json</code> module in Python). One security note that matters: parsing JSON from an untrusted source is reading data &mdash; the danger was never the format but what code does with it. And storing sensitive things? A format is not a lock: <a href="/tech/plain-text-passwords/">secrets in plain files are a mistake in any format</a>.</p>""",
[("IETF RFC 8259 \u2014 The JavaScript Object Notation (JSON) Data Interchange Format", "https://www.rfc-editor.org/rfc/rfc8259")],
[("what-is-api", "What an API actually is"),
 ("call-api-python", "Calling an API with Python")]),

("base64-explained", "coding", "guide",
"Base64 explained: what those = signs mean (and why it isn't encryption)",
"The encoding that turns any bytes into safe text: how it works, why it makes things a third bigger, and the security confusion that never dies.",
"""<p>Base64 is a translation layer between two worlds that don't mix: binary data and text-only systems. Email attachments, data URLs, embedded images in HTML, authentication headers, JSON web tokens &mdash; all of them use the same trick. The problem it solves: many systems built for text (email, XML, form fields, URLs to a degree) mangle raw binary bytes. Base64 re-expresses <em>any</em> bytes using only 64 safe, printable characters: letters, digits, <code>+</code>, <code>/</code> and the padding sign <code>=</code>.</p>
<h2>The mechanism, in one paragraph</h2>
<p>Take every 3 bytes of input (24 bits), slice them into four 6-bit chunks, and map each chunk onto one of the 64 characters (RFC 4648's alphabet, <code>A&ndash;Z</code>, <code>a&ndash;z</code>, <code>0&ndash;9</code>, <code>+</code>, <code>/</code>). Six bits is smaller than a byte, which is why the output is a third longer than the input: 3 bytes become 4 characters, and when the input isn't an exact multiple of 3, one or two <code>=</code> signs pad the end &mdash; the famous trailing equals signs are just arithmetic bookkeeping. That size cost is the tax; text-safety is what it buys.</p>
<h2>The confusion that never dies: encoding is not encryption</h2>
<p>Because Base64 output looks like gibberish, people keep treating it as protection. It is none: the alphabet is public, the mapping is fixed, and anyone can reverse it in one step &mdash; <a href="/tech/tool/base64-encoder/">the Base64 tool on this site</a> does it instantly, as does every language's standard library. Encoding is a <em>transport format</em>, not a secret. Passwords and tokens written in Base64 are plaintext wearing a costume &mdash; the same warning as <a href="/tech/plain-text-passwords/">keeping secrets in plain text files</a>, with extra steps. If something needs to be secret, it needs cryptography (and usually, it needs to not be stored at all).</p>
<h2>The variants worth knowing</h2>
<p><strong>URL-safe Base64</strong> swaps <code>+</code> and <code>/</code> for <code>-</code> and <code>_</code>, because those two characters have special meaning inside URLs &mdash; you will meet this flavour in web tokens. <strong>Line-wrapped Base64</strong> (every 76 characters) is the classic email form from the MIME era. And when a decoder complains, the causes are almost always: stray whitespace or newlines, a missing or extra <code>=</code>, or text that was never Base64 in the first place &mdash; which is why good tools say "not valid Base64" instead of guessing.</p>
<p>One habit worth adopting: when you see a long mysterious string in a config, header or token, Base64-decode it once <em>to understand it</em> (JWT headers are a readable JSON surprise for most people). Read, don't trust &mdash; and never paste anything secret into a tool you don't trust, including this site's.</p>""",
[("IETF RFC 4648 \u2014 The Base16, Base32, and Base64 Data Encodings", "https://datatracker.ietf.org/doc/html/rfc4648")],
[("plain-text-passwords", "Never store passwords in plain text"),
 ("what-is-json", "What JSON actually is")]),

("uuid-guide", "coding", "guide",
"UUIDs explained: the 128-bit answer to 'what do I call this?'",
"Unique identifiers without a central authority: what a UUID encodes, why version 4's randomness works, and when a random ID is the wrong choice.",
"""<p>Every database row, uploaded file, payment request and analytics event needs a name. Ask two servers to number things 1, 2, 3&hellip; and one day they will hand out the same number at the same moment. A UUID (universally unique identifier) sidesteps the whole coordination problem: a 128-bit value generated independently anywhere, whose chance of colliding with anything ever generated before is, for practical purposes, zero.</p>
<h2>Reading one</h2>
<p>The canonical form is 32 hexadecimal digits in five groups: <code>8-4-4-4-12</code>. Two of those digits carry structure, and they are worth learning to read: character 13 is the <strong>version</strong> (how this UUID was generated) and character 17's high bits are the <strong>variant</strong> (which flavour of UUID layout). A version-4 UUID &mdash; the random kind this site's <a href="/tech/tool/uuid-generator/">UUID generator produces</a> &mdash; shows a <code>4</code> in the version slot and an <code>8</code>, <code>9</code>, <code>a</code> or <code>b</code> in the variant slot.</p>
<h2>The versions that matter</h2>
<p><strong>Version 4 is the default of the modern web</strong>: 122 of its 128 bits come from a cryptographic random source. No coordination, no sequence to guess, safe to generate on any machine at any rate &mdash; that is why APIs, clients and distributed systems hand out v4 UUIDs freely. <strong>Version 1</strong> embeds a timestamp and the machine's hardware address: historically important, increasingly avoided because it leaks information. The 2024 revision of the standard (RFC 9562, which obsoleted the 2005 original, RFC 4122) formalised newer flavours &mdash; most usefully <strong>version 7</strong>, which encodes a millisecond timestamp in the leading bits with random low bits: time-ordered, so UUIDs sort naturally by creation in a database index, fixing v4's one real weakness (random IDs scatter across an index and bloat it).</p>
<h2>When <em>not</em> to use one</h2>
<p>A UUID is an identifier, not a security measure: a v4 ID is unguessable in practice, but if access control matters, unguessability must never be the <em>only</em> gate &mdash; treat capability URLs built on UUIDs as convenience, and put real authentication behind anything sensitive (the same layering as <a href="/tech/two-factor-authentication-setup/">proper 2FA</a>). And inside a single small database, plain sequential integers remain perfectly fine &mdash; UUIDs buy you independence between systems, and if you have only one system, you are paying storage and index cost for nothing.</p>
<p>The collision math, stated honestly rather than as trivia: you would need to generate billions of v4 UUIDs per second for a century to have a coin-flip chance of one collision. The failure mode of UUIDs is not duplication &mdash; it is copying an ID from a test environment into production, or reusing one as a "secret". Those are process failures, and no bit-layout fixes them.</p>""",
[("IETF RFC 9562 \u2014 Universally Unique IDentifiers (UUID), obsoleting RFC 4122 (2005)", "https://datatracker.ietf.org/doc/html/rfc9562"),
 ("IETF RFC 4122 \u2014 the original UUID A Rules and Deref standard, 2005", "https://datatracker.ietf.org/doc/html/rfc4122")],
[("what-is-a-database", "What a database actually is"),
 ("two-factor-authentication-setup", "2FA, set up properly")]),

("unix-time-explained", "coding", "guide",
"Unix time explained: why computers count seconds from 1970",
"The integer clock underneath every API and database: seconds since the epoch, the milliseconds trap, timezones, and the 2038 question.",
"""<p>Ask an API for the time and it will not answer in words. It will hand you a number &mdash; something like <code>1757548800</code>. That is Unix time: the count of seconds elapsed since <strong>1 January 1970, 00:00:00 UTC</strong> (the "epoch"), not counting leap seconds. One convention, one integer, the same moment everywhere on Earth &mdash; and that last property is the entire point.</p>
<h2>Why an integer wins</h2>
<p>Human time is a mess of timezones, daylight-saving shifts and calendar quirks; computer time needs to compare, sort and compute durations. An integer does all three trivially: later is bigger, subtraction gives elapsed seconds, and there is exactly one true value to store. Timezones enter only at the display layer &mdash; the same timestamp renders as Lagos afternoon, London evening and New York morning, because rendering to a timezone is a presentation choice, never a property of the stored moment. Storing local times instead of timestamps is one of the classic database mistakes precisely because it bakes a presentation choice into the data.</p>
<h2>The seconds-vs-milliseconds trap</h2>
<p>The number one timestamp bug in web development: some systems (JavaScript's <code>Date.now()</code> most prominently) give <strong>milliseconds</strong> since the epoch &mdash; thirteen digits &mdash; while most APIs and databases use <strong>seconds</strong> &mdash; ten digits. Feed milliseconds to a seconds-expecting system and your event lands in the year 57,000. The reliable tell is digit-count, and it is why <a href="/tech/tool/timestamp-converter/">the timestamp converter on this site auto-detects the unit</a> instead of asking you to guess. When an integration produces dates absurdly in the future, divide by 1000 and check before anything else.</p>
<h2>The 2038 question, stated calmly</h2>
<p>Systems that store Unix time in a <em>signed 32-bit</em> integer run out of representable seconds on 19 January 2038 &mdash; the count overflows the maximum the type can hold. This is the Y2K problem's quieter sibling: modern 64-bit systems are unaffected (the limit recedes by ~292 billion years), and the fix is boring and known &mdash; use a 64-bit time type. It matters mainly for old embedded devices and long-lived industrial systems, which is why the date still has a name.</p>
<p>Two honest footnotes for completeness: Unix time officially <strong>ignores leap seconds</strong> &mdash; the moments when Earth's sloppy rotation gets a correction second; they simply don't exist in the count, which occasionally causes minute-scale oddities in systems that care about astronomical precision. And <code>1970-01-01</code> itself is why a zero timestamp usually means "unset" in code. When you need to actually convert a value, <a href="/tech/tool/timestamp-converter/">the converter tool</a> does seconds, milliseconds, local and UTC in one place.</p>""",
[],
[("what-is-a-database", "What a database actually is"),
 ("call-api-python", "Calling an API with Python")]),

("http-status-codes-explained", "web-and-hosting", "guide",
"HTTP status codes explained: the numbers your browser whispers",
"What 200, 301, 304, 404, 429 and 500 actually mean, why 401 is not 403, and how to read a status code like a diagnosis instead of an error.",
"""<p>Every HTTP response carries a three-digit status code &mdash; the server's one-line verdict on what just happened. Most people know 404 and 500 the way they know one bad ex. But the codes form a small, logical language, and once you can read it, debugging the web (your site or someone's API) gets dramatically faster.</p>
<h2>The five families</h2>
<p>The first digit is the family: <strong>1xx</strong> informational (handshaking, rarely seen by humans), <strong>2xx</strong> success, <strong>3xx</strong> redirection, <strong>4xx</strong> the client's mistake, <strong>5xx</strong> the server's mistake. That split is the diagnosis in miniature: a 4xx means change your request; a 5xx means the other side broke something. The formal registry of every code lives at IANA; the practical vocabulary is maybe fifteen codes, covered below and in the <a href="/tech/tool/http-status-lookup/">filterable status-code lookup tool</a>.</p>
<h2>The ones that actually matter</h2>
<p><strong>200</strong> OK &mdash; worked, body attached. <strong>201</strong> Created &mdash; a POST made something. <strong>204</strong> No Content &mdash; success, nothing to say. On the redirect shelf: <strong>301</strong> moved permanently (update your links; search engines move rankings &mdash; this is the code every site migration lives and dies by, as <a href="/tech/custom-domain-dns-order/">domain migrations</a> know well), <strong>302</strong>/307 temporary (original URL stays canonical), and <strong>304</strong> Not Modified &mdash; the invisible workhorse that makes the web fast by confirming your cached copy is still valid.</p>
<p>The 4xx shelf: <strong>400</strong> your request is malformed; <strong>401</strong> "who are you?" &mdash; authentication missing or failed; <strong>403</strong> "I know exactly who you are &mdash; still no" &mdash; a permissions wall, and no amount of re-logging-in fixes it; <strong>404</strong> nothing at this URL; <strong>410</strong> gone on purpose, permanently; <strong>429</strong> too many requests &mdash; a rate limit, and the polite ones tell you when to retry. The 5xx shelf: <strong>500</strong> the server's own code crashed; <strong>502</strong> and <strong>504</strong> middleman trouble (a proxy or gateway got garbage, or waited too long, on the real server behind it); <strong>503</strong> overloaded or down for maintenance. On your own deployed site, 502/504 almost always mean "check the service behind the proxy" &mdash; a lesson this site's <a href="/tech/render-deployment-failures-what-they-taught-me/">deployment failures taught first-hand</a>.</p>
<h2>Reading them like a diagnosis</h2>
<p>Three habits. <strong>Family first:</strong> 4xx is yours, 5xx is theirs &mdash; that alone halves debugging time. <strong>401 vs 403 is the exam question:</strong> if re-authenticating might help, it was 401; if not, it was 403, and you need different permissions, not better credentials. <strong>Bodies matter:</strong> a 200 with an error message inside is an API design sin but a common reality &mdash; check the payload, not just the number, when something "succeeded" oddly. And security-adjacent: precise errors on public endpoints leak information; "not found" where "forbidden" is true is sometimes deliberate kindness to attackers. Status codes are metadata for humans &mdash; the spec behind them (RFC 9110) is readable, and the registry is complete, but the fifteen above will carry you through nearly every real incident.</p>""",
[("IANA \u2014 HTTP Status Code Registry (the authoritative list)", "https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml"),
 ("IETF RFC 9110 \u2014 HTTP Semantics (defines the status code classes)", "https://datatracker.ietf.org/doc/html/rfc9110")],
[("what-is-ssl-https", "What HTTPS actually does"),
 ("custom-domain-dns-order", "Custom domains: the DNS order")]),
]
