# -*- coding: utf-8 -*-
"""Tech master build M6 — Apps & Android expansion (6 pieces, Sept 2026).

Dedupe lanes vs the existing shelf (link-not-overlap):
- android-app-permissions (per-app audit)  -> android-privacy-settings-checklist is the
  device-WIDE pass (permission manager, ads ID, network, lock screen).
- android-notifications (tuning: DND, lanes) -> android-notifications-not-arriving is the
  FAILURE lane (why apps go quiet) — the "Why is X not working?" template.
- phone-wont-connect-to-wifi / bluetooth-not-pairing (other transports) -> mobile-data-not-working
  owns the mobile-data lane (APN, caps, roaming, VPN).
- storage-full-breaking-apps (why storage breaks apps) / free-up-storage-android (cleanup)
  -> android-backup-guide owns what backups COVER (not storage, not the stats piece).
- phone-died-no-backup (why it matters, insurer-verified stats) -> android-backup-guide
  (the how-and-what, Google's mechanisms, honest exclusions).
- what-free-apps-do-with-your-data (the data economics) -> how-to-tell-if-an-app-is-safe
  (the pre-install check, spec §8's "Is X safe?" template).
- android-battery-health, app-crashes-android, three-two-one-backup-rule: linked lanes.
No volatile claims: Find My Device and Google backup described by mechanism and setting
names that are stable; version numbers and menu paths paraphrased, never quoted as exact UI.
"""

TECH_MASTER_M6 = [

("android-privacy-settings-checklist", "android", "guide",
"The Android privacy settings worth changing (a one-time pass)",
"Ten minutes in Settings that outlast every app decision: the permission manager, the advertising ID, lock-screen leaks, and the network settings people forget exist.",
"""<p>App-by-app permission audits catch the worst offenders, but Android's privacy posture is set one level higher — in device settings most people open once and never again. This is the one-time pass, in the order that matters most. It takes about ten minutes, survives app installs, and needs repeating only when the OS has a major update.</p>
<h2>1. The permission manager: by permission, not by app</h2>
<p>Settings, then Privacy, then Permission manager (on some skins: Apps, then Special app access). The inversion is the point: instead of asking "what does this app have?", review by <em>permission</em> — Camera, Microphone, Location, Contacts — and see every app holding each. Two sweeps per permission: anything you can't explain gets revoked, and anything set to "Allow all the time" gets a hard question (location all-the-time is legitimate for exactly one or two apps — maps, a safety app — and nobody else). This is the device-wide version of <a href="/tech/android-app-permissions/">the per-app permission audit</a>; the two together are the full picture.</p>
<h2>2. The advertising ID: reset it, then consider deleting it</h2>
<p>Android assigns an advertising ID that apps and ad networks use to link activity across apps. Settings, then Privacy, then Ads: <strong>Delete advertising ID</strong> (or Reset on older versions). Resetting gives you a new random identifier; deleting removes the identifier entirely on current versions — apps fall back to weaker, less accurate signals. Neither stops advertising; both weaken cross-app tracking, which is the part worth weakening. The economics of why that matters are in <a href="/tech/what-free-apps-do-with-your-data/">what free apps do with your data</a>.</p>
<h2>3. The lock screen: what it shows before you unlock</h2>
<p>Settings, then Lock screen: decide what notifications reveal when the phone is locked — hide sensitive content (message previews are the leak), or show nothing. While there: confirm the screen lock itself is a six-digit PIN at minimum (pattern or four digits fall to shoulder-surfing and smudges far too easily), and that fingerprint/face unlock is set. The <a href="/tech/login-problems-checklist/">login-failure checklist</a> is less funny when the device holding your 2FA apps is behind a four-digit pattern.</p>
<h2>4. The network corners</h2>
<p>Two settings with outsized value. <strong>Private DNS</strong> (Settings, then Network, then Private DNS): pointing the phone at a DNS-over-TLS resolver encrypts name lookups device-wide — a one-line change with real effect on public Wi-Fi, and the reason it works is in <a href="/tech/what-is-dns/">what DNS does</a>. <strong>Wi-Fi permissions per app</strong>: apps don't need location to scan for networks — the "Wi-Fi control" permission exists; revoke it from apps that don't manage connectivity. And when mobile data itself misbehaves after all this tweaking, that diagnosis has its own ladder: <a href="/tech/mobile-data-not-working/">mobile data, diagnosed</a>.</p>
<h2>5. The forgotten two</h2>
<p><strong>Notification history</strong> (Settings, then Notifications): enable it — a rolling log of dismissed notifications that rescues the swipe you regret, and doubles as evidence when an app is vibrating without telling you why (the quiet-notification failure mode has its own piece: <a href="/tech/android-notifications-not-arriving/">why notifications go missing</a>). <strong>Google Play Protect</strong> (Play Store, profile, Play Protect): confirm it's on — it scans installed apps continuously and is the baseline malware defence; it is not a reason to install recklessly, which is the <a href="/tech/how-to-tell-if-an-app-is-safe/">pre-install checklist's</a> job.</p>""",
[],
[("android-app-permissions", "The per-app permission audit"),
 ("what-free-apps-do-with-your-data", "What free apps do with data"),
 ("what-is-dns", "What DNS actually does")]),

("android-notifications-not-arriving", "android", "guide",
"Notifications not arriving on Android: why apps go quiet",
"Silent apps, delayed buzzes, messages that appear only when opened — the failure modes, from battery optimisation to the app's own server, in diagnosis order.",
"""<p>The opposite problem from notification overload is worse: the app you <em>need</em> — messages, banking codes, the delivery window — has gone silent. Missed notifications usually aren't one bug; they're one of five layers swallowing the alert. Work them in order, because each is cheaper to check than the next.</p>
<h2>1. The app's notification channels got switched off</h2>
<p>Android apps post notifications through <strong>channels</strong> — categories you can control separately (messages versus promotions versus silent updates). An app can be "allowed" while its important channel is muted, and some apps start with channels off by default. Settings, then Apps, then the app, then Notifications: check each channel, and while there, confirm the app isn't in a paused or "silent" notification state. This is the mirror image of the tuning pass in <a href="/tech/android-notifications/">silencing the noise properly</a> — same controls, opposite direction.</p>
<h2>2. Battery optimisation is strangling the app</h2>
<p>The most common culprit on phones that "miss" messages overnight: aggressive battery management puts rarely-opened apps into deep sleep, blocking their background push. Settings, then Apps, then the app, then Battery: set it to Unrestricted (or exempt it from optimisation) for anything whose notifications matter — messaging, authenticators, delivery trackers. The trade is honest: unrestricted background means some battery cost, and <a href="/tech/android-battery-health/">the battery-drain picture</a> is where to check you haven't over-granted. Some manufacturers ship extra-aggressive "battery savers" with their own per-app kill lists — check the phone's own battery app for a "sleeping apps" list and move your critical apps out of it.</p>
<h2>3. Data restrictions cut the app's lifeline</h2>
<p>Push notifications ride data. Three data-side switches silence apps: Data Saver mode (Settings, then Network) blocks background data globally except for exempted apps — exempt the critical ones; per-app background data restrictions (App info, then Mobile data); and plain old "mobile data off" with apps that have no Wi-Fi fallback. If notifications flow on Wi-Fi but die on the road, it's this layer — and if <em>all</em> data is dead outside Wi-Fi, that's the <a href="/tech/mobile-data-not-working/">mobile-data diagnosis</a>, not a notification problem.</p>
<h2>4. The moment-of-truth checks</h2>
<p>Notifications arriving only when you open the app is the signature of background push being blocked (layers 2–3) — the app learns of the message fresh each launch. Notifications that buzz but show nothing is channel content-hidden (layer 1) or the lock-screen setting hiding content (<a href="/tech/android-privacy-settings-checklist/">the privacy pass</a> sets that deliberately). And a phone whose notifications stall everywhere, for every app, until you unlock it: that's USB/debugging mode or an aggressive third-party cleaner app — uninstall the cleaner; Android does not need one, and <a href="/tech/app-crashes-android/">the crash-triage piece</a> explains the harm category they live in.</p>
<h2>5. When it's the sender, not the phone</h2>
<p>One app silent everywhere — on your phone, a partner's phone, after a clean reinstall with notifications verified on? The app's own push infrastructure is the failing layer, and no phone setting fixes that: report via the store listing and wait out the fix. The quick cross-check that proves it: does the same category of alert arrive from a <em>different</em> app on the same phone? If yes, your phone is fine and the developer owns the bug — which is a diagnosis worth having before the tenth reinstall.</p>""",
[],
[("android-notifications", "Tuning notifications properly"),
 ("android-battery-health", "Battery drain, honestly"),
 ("mobile-data-not-working", "Mobile data, diagnosed")]),

("mobile-data-not-working", "android", "guide",
"Mobile data not working: the diagnosis that finds which layer failed",
"Wi-Fi fine, data dead? The ladder from the toggle you checked twice to the APN reset almost nobody needs — and the four settings that silently eat data.",
"""<p>Wi-Fi works, the signal bars are full, and mobile data is dead. The failure lives in one of six layers, and the fastest diagnosis walks them shortest-first: the switch, the cap, the coverage, the carrier setting, the phone, and only then the exotic fixes.</p>
<h2>The ladder, shortest first</h2>
<p><strong>1. The obvious switches, properly.</strong> Mobile data on (Quick Settings <em>and</em> Settings, then Network — the two toggles are genuinely separate on many phones), Airplane/Flight mode actually off, and if you're abroad, <strong>data roaming on</strong> — the setting that's off by default on most phones and silently kills data the moment you cross a border, <em>including</em> sometimes between networks at home. Roaming charges are a real thing to understand first: check your plan's roaming terms before flipping it abroad.</p>
<p><strong>2. The cap you forgot.</strong> Data-limit features and carrier fair-use throttles produce the same symptom as total failure: apps time out, the speed-test crawls. Check the phone's data-usage screen for a set limit, and the carrier's app or balance line for the real remaining allowance. Unlimited plans still throttle after thresholds — <a href="/tech/unix-time-explained/">timestamped</a> usage logs settle "when did it slow down" arguments instantly.</p>
<p><strong>3. Coverage, honestly tested.</strong> One bar in a basement is a coverage problem, not a phone problem — step outside, or check the carrier's coverage map for your exact location. 5G can also be the culprit in reverse: a phone clinging to a hopeless 5G connection does worse than a solid 4G one; forcing 4G (Settings, then SIM, then Preferred network type) is a legitimate fix in weak-5G areas, not a defeat.</p>
<p><strong>4. The VPN and the APN.</strong> A VPN app with a dead server tunnels your data into a wall — turn it off for one test (this same suspect breaks Wi-Fi onboarding too, as <a href="/tech/phone-wont-connect-to-wifi/">the Wi-Fi diagnosis</a> notes). If the VPN is innocent, the <strong>APN</strong> — the carrier's access-point settings — is the last software layer: Settings, then SIM, then Access Point Names, then "Reset to default". Wrong or corrupted APNs are rare, classically hit after switching carriers or SIM-swapping, and the reset fixes them in one tap.</p>
<p><strong>5. The phone, rebooted and SIM-checked.</strong> The restart reflex exists for a reason — it re-registers the phone to the network, which resolves the "shows signal, delivers nothing" state after outages or long subway rides. Then reseat the SIM (power off first): oxidised contacts produce intermittent data exactly like this. Try the SIM in another phone, or another SIM in yours — one minute of swapping answers "phone or SIM" definitively.</p>
<p><strong>6. The carrier.</strong> Worked the ladder, dead everywhere, no outage on the status page? Check for an outage page or community thread first (carriers have them), then call support with the evidence: SIM tested in another device, APN reset done, outages checked. That ticket gets fixed same-day; "it doesn't work" does not. And for the reverse situation — data fine, Wi-Fi broken — the same method lives in <a href="/tech/phone-wont-connect-to-wifi/">the Wi-Fi checklist</a>.</p>""",
[],
[("phone-wont-connect-to-wifi", "The Wi-Fi diagnosis"),
 ("android-notifications-not-arriving", "Notifications going missing"),
 ("unix-time-explained", "Why timestamps matter")]),

("how-to-tell-if-an-app-is-safe", "android", "guide",
"How to tell if an app is safe before you install it",
"The pre-install check: what the developer listing, the permissions, the reviews and the install source each tell you — and the red flags that end the conversation.",
"""<p>App safety is decided before the install screen, not after. The good news: the evidence is all visible in five minutes, and the red flags are consistent across platforms. This is the check, in the order that catches the most problems fastest — it answers the "is this app safe?" question the only honest way: as a risk assessment, not a guarantee.</p>
<h2>1. The install source is half the answer</h2>
<p>The official Play Store vets apps continuously (automated scanning plus policy enforcement) and can remotely remove bad actors after the fact. That makes it the safest <em>channel</em> — not a guarantee, a distribution with recourse. Sideloaded APKs from websites and link-shortened "download" pages have none of that: no vetting, no removal mechanism, no update path — the entire <a href="/tech/how-to-spot-a-suspicious-link/">suspicious-link threat model</a> in an installer. The rule: if an app isn't on an official store, the burden of proof inverts, and "the modded premium version, free" is proof of the opposite — pirated-app repackaging is a classic malware costume, and the same reasoning as <a href="/tech/what-free-apps-do-with-your-data/">why free has a business model</a> applies double when the "business model" is your bank credentials.</p>
<h2>2. The developer listing: who is actually asking</h2>
<p>Scroll past the icon to the developer line. A named company with a track record and other published apps is checkable in two taps (tap the name: their other apps, their website, how long they've existed). Brand-new developer + popular-app impersonation (the second "WhatsApp" with 50k installs) is the single most reliable red flag in the store. Impersonators survive on search typos — open store listings from the developer's official website link when the stakes are any higher than a torch app.</p>
<h2>3. The permissions, asked in context</h2>
<p>A torch app requesting contacts, a calculator wanting location, a game that must read SMS: permission-to-purpose mismatch is the loudest signal available, and Android shows the permission list right on the install page. Judge it the way the <a href="/tech/android-app-permissions/">permission audit</a> does: does this permission serve the app's actual job? Some mismatches have honest explanations (a camera app needing storage); most don't. And remember the install-page list is only the opening bid — apps accumulate permissions later, which is why the audit is a habit, not a ceremony.</p>
<h2>4. Reviews, read for forensics</h2>
<p>Ignore the star average; read the recent one-star reviews for the words that matter: "charged", "subscription", "permissions", "ads on lock screen", "my battery". A pattern of surprise-charging reviews on a flashlight is a business model, not a bug. Equally telling: a wall of five-star reviews posted within days, vague and grammatically uncanny — that's a review farm, and stores are imperfect at catching it. Review <em>velocity</em> against app age tells you whether popularity was earned.</p>
<h2>5. After install: the confirmation checks</h2>
<p>First launch is evidence too: an app that immediately demands account creation before showing any function, or floods full-screen ads in its first minute, has told you what it is — uninstall while the decision is cheap. Confirm Play Protect is on (it scans continuously), and give the app its first week under the <a href="/tech/android-privacy-settings-checklist/">privacy pass</a>: check what permissions it actually claimed versus what the install page promised. The strongest safety tool in the whole piece is the one nobody markets: willingness to delete. Apps earn their place on the phone the same sources earn their place in an article — by behaving.</p>""",
[],
[("android-app-permissions", "The permission audit"),
 ("what-free-apps-do-with-your-data", "The free-app data economy"),
 ("how-to-spot-a-suspicious-link", "Spotting suspicious links")]),

("android-backup-guide", "android", "guide",
"What Android backup actually covers (and what it quietly doesn't)",
"Google's phone backup is genuinely good and genuinely incomplete. The honest map: what's included, what needs separate arrangements, and how to prove your backup works.",
"""<p>Android's built-in backup is the reason most people who lose a phone lose less than they feared — and the reason some people lose exactly the thing they cared about. It is real backup, with real exclusions. This is the honest map of what's covered, what isn't, and the arrangements that close the gaps. (Why any of this matters — the cost of a phone with no backup — is documented with insurer data in <a href="/tech/phone-died-no-backup/">the phone-death piece</a>.)</p>
<h2>What the Google backup covers</h2>
<p>The device backup (Settings, then Google, then Backup — or Settings, then System, then Backup depending on the phone) captures, when enabled: contacts, calendar, Gmail (those live in the account anyway), device settings, app <em>lists</em>, call history, SMS text messages on most phones, photos and videos if Google Photos sync is on, and app <em>data</em> for apps that opted into the backup API — which is most of the big ones and by no means all apps. The restore flow works: a new or reset phone signed into the same Google account offers the backup back, and the phone reassembles itself to a recognisable degree within an hour.</p>
<h2>What it quietly doesn't cover</h2>
<p><strong>Chat apps with their own backup systems.</strong> The biggest one: WhatsApp runs its own backup to Google Drive on its own schedule, under its own toggle — the Android backup does not include it, and a restore that skips WhatsApp's setup loses chats people genuinely never get over. Check the chat app's own backup screen, on its own schedule, with its own encryption option. <strong>Authenticator apps.</strong> The codes guarding your logins are deliberately hard to export; an authenticator's seeds may not survive a restore unless the app offers its own sync (several now do — turn it on, and know which of your apps have it). This is the gap that turns "phone died" into "locked out of everything" — the <a href="/tech/two-factor-authentication-setup/">2FA setup guide</a> covers the recovery-code discipline that closes it. <strong>Anything in app-specific clouds.</strong> Notes apps, fitness history, game progress: covered only if the app syncs to its own account — and "sync" is not backup, as <a href="/tech/cloud-vs-local-backup/">the sync-versus-backup piece</a> explains; delete propagation applies to app accounts the same as to drives.</p>
<h2>Making it actually work</h2>
<p>Three arrangements. <strong>One:</strong> verify the master toggle is on and a backup has run <em>recently</em> — the settings page shows the last successful run; a backup that hasn't run since you installed everything that matters is decoration. <strong>Two:</strong> check the exclusions that apply to your actual apps — WhatsApp's toggle, the authenticator's sync, the notes app's account — each app's own screen, once. <strong>Three:</strong> do the restore rehearsal. The 3-2-1 principle (<a href="/tech/three-two-one-backup-rule/">three copies, two media, one off-site</a>) ends with "and test it", and the phone version takes ten minutes: note what the backup says it holds, factory-reset an old or spare Android if you have one (or borrow the flow mentally — the setup wizard's restore preview lists exactly what will come back). The preview alone is diagnostic gold: whatever is missing from that list is what you need to arrange separately, discovered now rather than in the worst week of the year.</p>""",
[],
[("phone-died-no-backup", "The cost of no backup, verified"),
 ("three-two-one-backup-rule", "The 3-2-1 rule"),
 ("cloud-vs-local-backup", "Sync is not backup")]),

("android-find-lost-phone", "android", "guide",
"Lost your Android phone: the find-it plan (and the prep that makes it work)",
"Find My Device does the locating — if the phone was set up to be findable. The recovery sequence for right now, and the four-minute setup for before next time.",
"""<p>Losing a phone compresses every feeling into one hour. The recovery tooling is genuinely good — <strong>Find My Device</strong> (google.com/android/find, or the app on any other Android) can ring, locate, lock and wipe a lost phone — but every one of those powers depends on settings chosen <em>before</em> the loss. This piece is both: the sequence for right now, and the four-minute setup for the version of you who doesn't want to read an article mid-panic.</p>
<h2>Right now: the sequence</h2>
<p><strong>1. Call it.</strong> From another phone or a contacts site — before anything clever. Couch cushions and taxi seats resolve differently. <strong>2. Open Find My Device</strong> on any browser, sign in with the Google account that's on the phone. If the phone is on and connected, you get a map location and a <strong>Ring</strong> button that plays at full volume even if the phone was silenced — this finds more phones than the map does. <strong>3. Read the map honestly.</strong> A location that's moving without you: do <em>not</em> go confront a stranger alone — police recover stolen phones; vigilante recoveries go differently. A location that's your own last-known spot with the phone offline: it will update if the phone reconnects, and the page offers notifications when it does. <strong>4. Secure it remotely.</strong> <strong>Lock</strong> (Find My Device's "Secure device") locks the screen with your PIN, signs the phone out of your Google account on that device, and shows a recovery message plus a callback number on the lock screen — an honest finder's easiest path to returning it. <strong>5. The last resort, chosen deliberately:</strong> Erase device factory-resets it remotely — right when you're confident it's gone for good or it holds something too sensitive to risk. Two honest notes: erase usually can't touch an SD card, and if the phone had a spare — the <a href="/tech/android-backup-guide/">backup map</a> is what makes erase survivable.</p>
<h2>If the phone was offline from the start</h2>
<p>Find My Device's reach has improved — on current Android versions, even a phone that's off or out of battery can show its last position for hours via the network-of-Androids "Find My Device network" (crowdsourced locating, on by default on recent versions). What no tool beats: a PIN on the screen and the SIM registered in your name — the first keeps strangers out, the second is how carriers block the device. Report the IMEI (dial <code>*#06#</code> to see it — <em>now</em>, and write it down) to your carrier to block the handset itself, and change passwords for anything the phone was logged into, starting with the Google account and email — the same triage as any suspected compromise, which is the territory the <a href="/tech/login-problems-checklist/">login checklist</a> maps.</p>
<h2>The four-minute prep (do it today)</h2>
<p>Four switches make everything above work. <strong>1.</strong> Find My Device on (Settings, then Security, then Find My Device — usually on by default; confirm). <strong>2.</strong> The Find My Device network on (Settings, then Google, then Find My Device network). <strong>3.</strong> A screen lock stronger than a swipe, plus fingerprint — the lock screen is the whole castle. <strong>4.</strong> The IMEI written somewhere that isn't the phone (password manager note, or paper in a wallet — the <a href="/tech/plain-text-passwords/">plain-text rule</a> is about secrets; an IMEI is an identifier, not a key). Bonus fifth: the backup verification from the <a href="/tech/android-backup-guide/">backup guide</a>, because the difference between losing a phone and losing a life is one settings screen checked today.</p>""",
[],
[("android-backup-guide", "What Android backup covers"),
 ("login-problems-checklist", "The login-failure checklist"),
 ("two-factor-authentication-setup", "2FA, set up properly")]),
]
