#!/usr/bin/env node
"use strict";
const {server}=require("../server/server.js");
const failures=[];const check=(x,m)=>{if(!x)failures.push(m)};
const get=(base,p,o={})=>fetch(base+p,{redirect:"manual",...o});
server.listen(0,"127.0.0.1",async()=>{const base=`http://127.0.0.1:${server.address().port}`;try{
 let r=await get(base,"/");check(r.status===200,`/ returned ${r.status}`);const home=await r.text();check(home.includes("Learn to write. Write with"),"writing-hub homepage copy missing");for(const h of ["content-security-policy","referrer-policy","permissions-policy","strict-transport-security","x-content-type-options"])check(r.headers.has(h),`missing ${h}`);
 for(const [p,status,to] of [["/writing/index.html",308,"/writing/"],["/make-money",301,"/writing/"],["/make-money/",301,"/writing/"],["/opportunities",301,"/writing/"],["/opportunities/",301,"/writing/"],["/jobs",301,"/writing/"],["/jobs/",301,"/writing/"],["/tech",301,"/guides/"],["/tech/",301,"/guides/"]]){r=await get(base,p);check(r.status===status,`${p}: ${r.status}`);check(r.headers.get("location")===to,`${p}: location ${r.headers.get("location")}`)}
 for(const p of ["/writing/","/writing/afrolicious/","/guides/","/guides/how-to-write-a-pitch/","/tested/","/about/","/author/ibrahim-sodiq/","/assets/bryme-v2.css","/assets/hub-tools.js","/favicon.ico","/learn/","/learn/start-writing/","/learn/start-writing/how-to-start-writing/","/learn/writing-basics/sentence-basics/","/tools/","/tools/word-counter/","/glossary/","/templates/","/checklists/","/problems/","/search/"]){r=await get(base,p);check(r.status===200,`${p}: ${r.status}`);await r.arrayBuffer()}
 for(const p of ["/sports/","/movie/the-invite/","/articles/","/anime/"]){r=await get(base,p);check(r.status===410,`${p} should be 410, got ${r.status}`);const bt=await r.text();check(bt.includes("moved")||bt.includes("left this publication")||bt.includes("no longer"),`${p}: migration explanation missing`)}
 for(const p of ["/missing","/package.json","/scripts/build-focus-site.py","/content/jobs.json","/content/opportunities.json","/reports/site-inventory.csv","/.git/HEAD"]){r=await get(base,p);check(r.status===404,`${p} should be 404, got ${r.status}`);check(/noindex/i.test(await r.text()),`${p}: 404 body lacks noindex`)}
 r=await get(base,"/writing/",{method:"POST",body:"x"});check(r.status===405,`POST returned ${r.status}`);check((r.headers.get("allow")||"").includes("GET"),"405 Allow missing");
 r=await get(base,"/writing/",{method:"HEAD"});check(r.status===200,`HEAD returned ${r.status}`);check((await r.text())==="","HEAD returned body");
 r=await get(base,"/healthz");check(r.status===200,"health failed");const health=await r.json();check(health.service==="bryme-work","health service mismatch");
 }catch(e){failures.push(e.stack||String(e))}finally{server.close(()=>{if(failures.length){console.error(`FAIL (${failures.length})`);failures.forEach(x=>console.error("  - "+x));process.exitCode=1}else console.log(JSON.stringify({ok:true,checks:"writing-first routes, redirects, legacy 410, containment, headers, HEAD"},null,2))})}});
