#!/usr/bin/env node
"use strict";
const fs=require("fs"),net=require("net"),path=require("path"),{spawn}=require("child_process");
const {chromium}=require("playwright");
const ROOT=path.resolve(__dirname,"..");
const routes=JSON.parse(fs.readFileSync(path.join(ROOT,"content/index-allowlist.json"),"utf8")).routes;
const failures=[];const check=(ok,msg)=>{if(!ok)failures.push(msg)};
function freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.listen(0,"127.0.0.1",()=>{const p=s.address().port;s.close(()=>resolve(p))});s.on("error",reject)})}
async function ready(url){for(let i=0;i<80;i++){try{if((await fetch(url)).ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw new Error("server did not start")}
(async()=>{const port=await freePort(),base=`http://127.0.0.1:${port}`;const child=spawn(process.execPath,["server/server.js"],{cwd:ROOT,env:{...process.env,PORT:String(port),HOST:"127.0.0.1"},stdio:"ignore"});let browser;
try{await ready(base+"/healthz");browser=await chromium.launch({headless:true});
 const viewports=[{name:"mobile",width:390,height:844},{name:"tablet",width:768,height:1024},{name:"desktop",width:1440,height:1000}];let rendered=0;
 for(const vp of viewports){const context=await browser.newContext({viewport:{width:vp.width,height:vp.height},serviceWorkers:"block"});const page=await context.newPage();let routeErrors=[];page.on("console",m=>{if(m.type()==="error")routeErrors.push(`console: ${m.text()}`)});page.on("pageerror",e=>routeErrors.push(`page: ${e.message}`));page.on("requestfailed",r=>routeErrors.push(`request: ${r.url()} ${r.failure()?.errorText||"failed"}`));
  for(const route of routes){routeErrors=[];const label=`${vp.name} ${route}`;try{const response=await page.goto(base+route,{waitUntil:"networkidle",timeout:15000});check(response&&response.status()===200,`${label}: HTTP ${response&&response.status()}`);const x=await page.evaluate(()=>{const css=e=>e?getComputedStyle(e):null,top=document.querySelector('.main-nav,.topnav'),bottom=document.querySelector('.bottom-nav,.mobile-nav'),main=document.querySelector('main#main'),imgs=[...document.images];return{title:document.title.trim(),h1:document.querySelectorAll('h1').length,main:!!main,skip:!!document.querySelector('.skip-link[href="#main"]'),text:(main?.innerText||'').trim().length,scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,topDisplay:css(top)?.display||'none',topLinks:top?[...top.querySelectorAll(':scope > a')].map(a=>a.textContent.trim()):[],topCurrent:!!top?.querySelector('[aria-current="page"]'),bottomDisplay:css(bottom)?.display||'none',bottomLinks:bottom?[...bottom.querySelectorAll(':scope > a')].length:0,bottomCurrent:!!bottom?.querySelector('[aria-current="page"]'),bottomHeight:bottom?.getBoundingClientRect().height||0,paddingBottom:parseFloat(css(document.body)?.paddingBottom||'0'),styles:[...document.querySelectorAll('link[rel="stylesheet"]')].map(e=>e.href),scripts:[...document.querySelectorAll('script[src]')].map(e=>e.src),badImages:imgs.filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.currentSrc||i.src),externalResources:performance.getEntriesByType('resource').map(e=>e.name).filter(u=>{try{return new URL(u).origin!==location.origin}catch{return false}})}});
   check(x.title.length>=12,`${label}: short title`);check(x.h1===1,`${label}: H1 count ${x.h1}`);check(x.main&&x.skip,`${label}: main/skip landmark missing`);check(x.text>=120,`${label}: thin rendered body (${x.text})`);check(x.scroll<=x.client+2,`${label}: horizontal overflow ${x.scroll}>${x.client}`);check(x.styles.some(s=>/\/assets\/(?:bryme-v2|content-v2)\.css/.test(s)),`${label}: green stylesheet missing`);check(x.scripts.every(s=>/\/assets\//.test(s)),`${label}: unexpected scripts ${x.scripts.join(', ')}`);check(x.badImages.length===0,`${label}: broken images ${x.badImages.join(', ')}`);check(x.externalResources.length===0,`${label}: third-party resource ${x.externalResources[0]||''}`);
   if(vp.name==="mobile"){check(x.bottomDisplay!=="none",`${label}: bottom navigation hidden`);check(x.bottomLinks===4,`${label}: bottom navigation has ${x.bottomLinks} links`);check(route==="/"||x.bottomCurrent,`${label}: no current bottom-navigation item`);check(x.bottomHeight>=50,`${label}: bottom navigation too short (${x.bottomHeight})`);check(x.paddingBottom>=70,`${label}: insufficient bottom clearance (${x.paddingBottom})`)}else if(vp.name==="desktop"){check(x.bottomDisplay==="none",`${label}: bottom navigation visible on desktop`);check(x.topDisplay!=="none",`${label}: desktop navigation hidden`);check(x.topLinks.join('|')==="Learn to write|Writing tools|Write & get paid|About",`${label}: desktop navigation is ${x.topLinks.join('|')}`);check(route==="/"||x.topCurrent,`${label}: no current desktop-navigation item`)};
   if(routeErrors.length)failures.push(`${label}: ${routeErrors[0]}`);rendered++}catch(e){failures.push(`${label}: ${e.name}: ${e.message}`)}
  }await context.close()}
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:"block"});const page=await context.newPage();for(const [route,status,needle] of [["/sports/",410,"moved"],["/movie/example/",410,"moved"],["/not-a-page/",404,"Page not found"]]){const r=await page.goto(base+route,{waitUntil:"domcontentloaded"});check(r.status()===status,`${route}: browser HTTP ${r.status()}`);check((await page.textContent("body")).includes(needle),`${route}: explanation missing`)}await context.close();
 console.log(JSON.stringify({ok:failures.length===0,routes:routes.length,viewports:viewports.map(v=>`${v.width}x${v.height}`),renderedCases:rendered,failures:failures.slice(0,100)},null,2));if(failures.length)process.exitCode=1;
}catch(e){console.error(e.stack||e);process.exitCode=1}finally{if(browser)await browser.close();child.kill("SIGTERM")}})();
