# -*- coding: utf-8 -*-
"""Third-pass extensions for writers pages still under the depth bar."""

WRITERS_DEPTH3 = {

"writers/learn/writing-checklists": """
<p>Two checklist habits separate the people who keep lists from the people who use them. First, the list lives where the work happens: taped inside the notebook, pinned in the editor, one keystroke away — a checklist stored "somewhere" is a wish. Second, the list is allowed to be rude: "did you CHECK the link or just assume" is a better line than "verify hyperlinks," because checklists work by interrupting confidence at exactly the moments confidence is least trustworthy. The desk's library at <a href="/writers/checklists/">the checklists page</a> is built on both principles, and the <a href="/writers/learn/editing-proofreading/">editing section</a> shows where each tier of the instrument plugs into the passes.</p>""",

"writers/tested": """
<p>What the shelf will not do is equally part of the method: it will not review a category the desk cannot test properly (no secondhand software verdicts from other outlets' screenshots), will not fill space with me-and-my-family anecdotes standing in for criteria, and will not declare a winner where the honest result is "two good options for different people." Where a product changes its pricing or its behaviour materially, the verdict is re-tested rather than patched — the review you read is always the review of the product as it exists, not as it was. That is the whole contract, and it is the same one the <a href="/writers/writing/">opportunity desk</a> makes with its listings: dated, criteria-led, re-checked, and correctable through the <a href="/writers/contact/">contact door</a> when it is wrong.</p>""",

"writers/newsletter": """
<p>For the curious, the newsletter's own mechanics, disclosed the way the desk discloses everything: it goes out weekly when the sweep produces changes and skips silently when it does not — no filler issues manufactured to train your habit; the archive stays on-site so nothing essential is email-only; and the subject line tells you what changed rather than teasing it. If you run your own publication and want the pattern, steal all three rules: send when there is news, keep the archive public, and write subject lines that respect the triage scan. The craft behind them lives in the <a href="/writers/learn/dos-and-donts/dos-and-donts-of-professional-emails/">professional-email dos and don'ts</a>, and the desk's <a href="/writers/writing/">opportunity desk</a> is the same data without the email delay, for readers who prefer to check in on their own schedule.</p>""",

"writers/learn/writing-glossary": """
<p>One desk note on using any glossary well: terms are doors, not destinations. When a word stops you — "unsolicited," "rights-reverted," "on spec" — look it up, then immediately reread the sentence that stopped you; the sentence is where the term means something. Collecting definitions without sentences is how glossaries become trivia. The full term list on the desk's <a href="/writers/glossary/">glossary page</a> is organised by the contexts where the terms bite (submission, contract, production), because context is what the definitions are actually for, and the <a href="/writers/guides/">guides shelf</a> is where every one of these terms appears doing its job.</p>""",

"writers/learn/writing-tools": """
<p>A final note on the tool question writers ask most — "which ones does this desk actually use?" — with the honest answer: a plain text editor for drafting, a browser tab for the style references, a spreadsheet for the ledgers, and the desk's own tools for the checking passes. That austerity is not a personality; it is the lesson of the <a href="/writers/tested/">Tested shelf</a> applied to ourselves — every tool that earns a place in the work survives a month of it, and most do not. Start with the library's plainest options, add nothing until a specific repeated annoyance names itself, and treat any urge to upgrade mid-draft as procrastination wearing a productivity costume. The <a href="/writers/learn/writing-process/">process section</a> is where the saved money and time both go.</p>""",

"writers/learn/writing-templates": """
<p>The library's maintenance rule, since templates rot differently from prose: every template carries its last-used date and dies of disuse gracefully — if a structure has not been needed in a year, it leaves the library rather than implying relevance. The templates that survive do so because the underlying form is stable (the pitch has looked basically the same for decades; the <a href="https://en.wikipedia.org/wiki/Special:Search?search=query+letter" rel="noopener">query-letter reference material on Wikipedia</a> shows how little the skeleton has moved), and because writers keep improving the sample sentences inside them. If you adapt a template into something better, the <a href="/writers/contact/">contact door</a> is open — the library improves the same way the rest of the desk does, by correction.</p>""",

"writers/learn/research-sources": """
<p>The desk's standing example of why capture-time receipts matter: the corrections this desk has had to run were almost never invented facts — they were real facts whose source had moved, closed, or been misremembered by the time a reader checked. Every one of them would have been caught by the one-minute rule (no published sentence whose source you cannot produce within a minute) applied before publishing rather than after. The habit is teachable in a week and lasts a career, and the formal versions of it — source hierarchies, citation mechanics, evaluation criteria — wait patiently in the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's research sections</a> for whenever your work starts demanding them. The <a href="/writers/intelligence/">intelligence page</a> shows this desk's own public version of the same discipline, labels and all.</p>""",

"writers/writing-opportunities/nepal": """
<p>One more desk note for writers working from smaller markets, because it matters more than any single listing: the eligibility line is a door, not a verdict. Markets that say "international submissions welcome" mean it — writers from Nepal win slots in Commonwealth short-story prizes, international magazine anthologies and online-first publications every year, and the pattern behind nearly every win is the one this desk keeps teaching: a specific angle no local desk could reach, pitched professionally to a market verified as open (this page and the <a href="/writers/writing/">full desk</a>), with the submission mechanics from the <a href="/writers/guides/how-to-submit-a-freelance-article/">guide</a> and the follow-up discipline from the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">timing table</a>. Small-market writers who pitch only local markets are competing for a fraction of the available slots; the world desk is the bigger room, and the door genuinely opens.</p>""",

"writers/studio": """
<p>For the tools' roadmap, since a workbench should say what it is building toward: the near-term additions are the checks writers ask for most — a reverse-outline helper for the <a href="/writers/learn/structure-formatting/">structure pass</a>, a style-sheet checker for the <a href="/writers/learn/grammar-language/">usage resolutions</a> you have personal choices about, and a submission-record exporter that talks to the <a href="/writers/tracker/">tracker</a>. The standing design rule for all of them is the one the studio already runs on: one job per tool, client-side by default, honest about what it cannot do, and subordinate to the writer at every step. Tool suggestions go through the <a href="/writers/contact/">contact door</a> like everything else — the desk builds what working writers actually ask for, in the order they ask.</p>""",

"writers/learn/structure-formatting": """
<p>One structural pattern deserves a warning label, because this section teaches it and beginners over-apply it: the five-paragraph essay reflex. Its discipline (one idea per unit, signposted, closed) is real; its rigidity — exactly three body paragraphs, a conclusion that restates — is a school scaffold that comes off the moment the reader is a stranger with choices. Professional structure keeps the discipline and drops the rigidity: a piece has as many paragraphs as the idea needs, and the conclusion does new work (the implication, the turn, the door out) rather than reciting. The <a href="/writers/learn/dos-and-donts/dos-and-donts-of-an-essay/">essay dos and don'ts</a> police the transition, and the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's organisation resources</a> show the scaffold and the buildings it becomes.</p>""",

"writers/learn/journaling-personal": """
<p>The privacy question deserves its own note, because a journal's honesty depends on its safety: write as if no one will read it, and make that true — a locked file, a private book, a password on the folder. The desk's standing advice is to decide the privacy boundary before the first entry, because mid-flight renegotiations with yourself are how honest journals become careful ones, and a careful journal is a diary for an imaginary committee. None of this affects the craft spillover: pages written for nobody still train the sentence-making, and the <a href="/writers/learn/creative-writing/">creative section</a> is where material that wants readers can eventually, deliberately, find them.</p>""",

"writers/learn/start-writing": """
<p>The desk's last word on starting, because the block behind most un-started pages is worth naming plainly: the page cannot be bad in any way that matters until it exists. Every rule in this section — the timer, the boring true version, the mid-flow stop — is machinery for getting a bad first draft on the record, and the draft is allowed to be embarrassing for exactly as long as it takes to reach the <a href="/writers/learn/editing-proofreading/">editing passes</a>, where embarrassment gets fixed professionally. The writers you admire were not better at starting; they were better at tolerating their own first drafts, which is a trainable tolerance, fifteen minutes at a time. The <a href="/writers/guides/how-to-get-your-first-paid-writing-gig/">first-gig plan</a> shows what the accumulating pages are for.</p>""",

"writers/guides/how-to-find-paid-writing-opportunities": """
<p>One desk note on the emotional architecture of the funnel, because the mechanics rarely fail — writers do, usually at week three: the pipeline is designed so that rejection is throughput, not verdict. Ten pitches a week means several noes a week is the system working; the tracker turns them into response-time data, the <a href="/writers/learn/writing-for-publication/a-rejected-pitch-is-not-wasted/">rejection guide</a> turns them into reroutes, and the two-in-ten conversion that eventually pays is a rate you earn by volume plus calibration, never by waiting to feel ready. Keep Friday's fifteen minutes sacred — that is when the system tells you the truth about itself, and the truth is always actionable somewhere in the <a href="/writers/guides/">guides shelf</a>.</p>""",

"writers/guides/how-to-write-a-strong-query-letter": """
<p>The letter's last line deserves its own note, because it is the one most writers overwrite: the close is one sentence — "The piece would run [length]; I can deliver by [date]" — or, for queries with attachments invited, a pointer to the samples. No gratitude for the reader's time (they know their time is valuable), no summary of the letter it concludes, and absolutely no "hope to hear from you soon," which every editor alive has read ten thousand times and none has ever found hopeful. The close is a door left open at the exact width the editor needs to walk through with a yes. The <a href="/writers/guides/how-to-write-a-pitch/">modern pitch guide</a> is where most letters should aspire to retire; the desk's <a href="/writers/writing/">opportunity desk</a> tells you which form each market still wants, dated.</p>""",

"writers/learn/common-problems": """
<p>The section's own escalation path, for the problem that outlives its diagnosis: if a draft has resisted two structured passes and still reads wrong, the honest next step is not a third pass but a verdict — the piece may be two pieces, or the wrong piece, or a piece whose time has passed. Killing a draft is a professional skill, and the desk's <a href="/writers/learn/writing-for-publication/a-rejected-pitch-is-not-wasted/">rejection guide</a> applies to your own manuscripts exactly as to pitches: salvage the working part (there is always a working paragraph), log the lesson in the <a href="/writers/learn/writing-process/">process notes</a>, and start the next one lighter. The <a href="/writers/learn/examples/">examples shelf</a> is the antidote of last resort — one hour with good published prose reminds the hands what the target feels like.</p>""",

}
