# -*- coding: utf-8 -*-
"""Writers-desk depth sections (Phase 3 tranche 5): injected post-build by
scripts/inject-writers-depth.py. Every section carries an h2, desk-specific
guidance, internal links and external references to stable, non-fabricated
resources (Purdue OWL, Poets & Writers, Wikipedia lookups, style guides)."""

OWL = "https://owl.purdue.edu/owl/purdue_owl.html"
PW = "https://www.pw.org/literary_magazines"
GRINDER = "https://thegrinder.diabolicalplots.com/"
GUARDIAN = "https://www.theguardian.com/guardian-observer-style-guide-a"
CHICAGO = "https://www.chicagomanualofstyle.org/home.html"

def _q(w):
    return "https://en.wikipedia.org/wiki/Special:Search?search=" + w

WRITERS_DEPTH = {

# ---------------- /writers/guides/ (22) ----------------

"writers/guides/how-african-writers-can-find-paid-publications": """
<h2>Desk notes: how to actually work this list</h2>
<p>The method this guide sketches is the one the desk runs daily on the <a href="/writers/writing/">opportunity desk</a>: every publication is recorded with its pay range, its eligibility line and the date we last read its guidelines. The advice that saves the most time is to filter by eligibility before anything else — a perfect market that does not accept writers in your country is a dead end no matter how good the rate looks. Read the eligibility line on the publication's own site, not in a repost, because eligibility changes without announcements.</p>
<p>Second, work the reference databases alongside the desk: <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers' literary magazine database</a> is free and filterable by region, and <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a> tracks response times reported by writers themselves. Cross-checking a market on both before submitting takes two minutes and catches most unpleasant surprises.</p>
<p>Third, keep the currency question concrete: note the rate, the currency, the payment method and who eats the transfer fee — the desk's <a href="/writers/guides/track-your-writing-income/">income-tracking guide</a> gives you the ledger habit that makes this automatic. And the standing rule from the guide above bears repeating in bold: no legitimate publication charges writers to submit. If a market asks for a reading fee, close the tab.</p>""",

"writers/guides/how-long-should-you-wait-for-an-editor": """
<h2>Desk notes: response windows, recorded not guessed</h2>
<p>The desk's position on waiting is blunt: a response time you cannot verify is a rumour. That is why every publication recorded on the <a href="/writers/writing/">opportunity desk</a> either states its window — with the date we last read it — or says plainly that none is stated. Where the magazine itself is silent, crowd-sourced data helps: <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a> and Duotrope both aggregate real writers' reported response times, which turns "I've been waiting two months" into "the reported average for this market is six weeks, so I'm inside the window."</p>
<p>The follow-up arithmetic in the guide above becomes mechanical once you track dates: submission date, plus the stated window, plus one polite week, equals follow-up day. The desk's <a href="/writers/tracker/">submission tracker</a> exists so none of this lives in your memory, and the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">when-to-follow-up guide</a> covers the wording.</p>
<p>One calibration note: slower is not worse. Literary magazines run on volunteer slush readers and can honestly take a quarter; a content mill replying in an hour is not efficiency, it is a conveyor belt. Match your expectations to the kind of market, not to your anxiety.</p>""",

"writers/guides/how-much-to-charge-for-an-article": """
<h2>Desk notes: pricing is research, not self-esteem</h2>
<p>The rate you charge is a market fact before it is a personal one, so the desk treats pricing as research. Every publication recorded on the <a href="/writers/writing/">opportunity desk</a> carries its stated per-article range and the date we last verified it — that is your floor-setter. Around it, three adjustments do most of the work: the research load (a reported piece is not the same product as an opinion post), the rights requested (exclusive, all-rights and first-rights are different prices for a reason — the <a href="/writers/guides/how-to-check-a-freelance-writing-contract/">contract guide</a> explains the differences), and the deadline pressure.</p>
<p>For calibration beyond the desk, <a href="https://www.pw.org/" rel="noopener">Poets &amp; Writers</a> publishes rate discussions and market surveys worth reading; the honest baseline, though, is what the market you are actually pitching pays, which is exactly what the desk records.</p>
<p>The habit that compounds: log every quoted rate, accepted rate and rejected rate in the <a href="/writers/tracker/">tracker</a>. Within a quarter you will see your own market data — which articles earn, which clients stretch, and when a "good rate" was actually below your realised hourly. Pricing confidence is a ledger, not a feeling.</p>""",

"writers/guides/how-to-build-writing-samples": """
<h2>Desk notes: what editors actually look at</h2>
<p>The desk reads hundreds of pitches a year (the corrections inbox alone guarantees that), so here is the honest editor's-eye view of samples: we click at most two links, we skim for the first sign you can structure a paragraph, and we notice publication names less than you think. That is why the advice above — few samples, best work, relevant to the pitch — matters more than volume.</p>
<p>Building the portfolio itself needs no permission: self-published work counts when it is good. A considered essay on a personal blog, a well-reported piece for a local outlet, even a meticulously edited newsletter archive — all legitimate. What editors discount is obvious filler: AI-generated posts, ten near-identical listicles, anything you would not defend in person. The Purdue OWL's guidance on <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">audience and purpose</a> is the fastest formal grounding for revising drafts into portfolio pieces.</p>
<p>The desk-specific route: the <a href="/writers/writing/">opportunity desk</a> records markets open to newer writers — many accept unpublished samples or ask for one clip rather than three. And once a sample earns you a yes, archive it: links rot, so keep a private copy of everything published. The <a href="/writers/guides/how-to-write-a-pitch/">pitch guide</a> shows how to attach samples without overloading the email.</p>""",

"writers/guides/how-to-check-a-freelance-writing-contract": """
<h2>Desk notes: the clauses that decide your year</h2>
<p>Contract reading is where freelance careers are quietly made or broken, so the desk keeps this guide next to the money pages deliberately. Beyond the checklist above, three clauses deserve your slowest reading. Rights and reversion: what exactly they license, for how long, and what happens when the piece is taken down — perpetual all-rights for a one-off fee is rarely worth it once you understand what it signs away. Kill fee: a professional contract pays you something (typically 25–50%) if the piece is cancelled through no fault of yours; its absence tells you how the publication views writers. Payment terms: "net 30" means nothing unless it says 30 days from what — acceptance, publication, or invoice.</p>
<p>For the formal vocabulary, the <a href="https://www.chicagomanualofstyle.org/home.html" rel="noopener">Chicago Manual of Style</a>'s publishing-law resources and the <a href="https://en.wikipedia.org/wiki/Special:Search?search=publishing+contract" rel="noopener">publishing-contract reference material on Wikipedia</a> are useful orientation — but neither is legal advice, and neither is this desk. Jurisdictions differ; for a contract you cannot parse, a paid hour with a lawyer familiar with media work is cheaper than the rights you might sign away.</p>
<p>The desk's own posture, stated on the <a href="/writers/disclosure/">disclosure page</a>: we record what guidelines say, never what they imply. Hold every contract to the same standard.</p>""",

"writers/guides/how-to-find-international-writing-opportunities": """
<h2>Desk notes: the international desk, worked properly</h2>
<p>Everything in this guide is mechanised on the <a href="/writers/writing/">opportunity desk</a>: each publication carries its eligibility line (including diaspora-specific rules), its pay range in the original currency, and the last-verified date. The discipline that makes international pitching work is reading those three fields before the pitch idea — in that order — because eligibility kills more international submissions than quality ever does.</p>
<p>The reference layer matters here too: <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers' magazine database</a> filters by region, and <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>'s response-time data covers many international markets. For African writers specifically, the desk's <a href="/writers/guides/how-african-writers-can-find-paid-publications/">dedicated guide</a> covers the diaspora-rule nuances, and continental platforms such as <a href="https://jaladaafrica.org/" rel="noopener">Jalada Africa</a> demonstrate the route from regional collective to international byline.</p>
<p>Payment mechanics deserve the repetition: confirm the currency, the method, and who absorbs the transfer cost — then log the realised amount in the <a href="/writers/tracker/">tracker</a> so your international rate comparisons use real numbers, not headline ones. And keep the scam filter from the guide above permanently on: upfront fees and "agents" who pitch on your behalf are disqualifying, everywhere, always.</p>""",

"writers/guides/how-to-find-paid-writing-opportunities": """
<h2>Desk notes: the funnel, formalised</h2>
<p>This guide describes the funnel the desk runs at scale, so here is the mechanical version. Source: the <a href="/writers/writing/">opportunity desk</a> — every entry carries pay, eligibility and a last-verified date, which eliminates the three ways writers waste time (unpaid markets, ineligible markets, dead markets). Reference databases widen the net: <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers</a> and <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a> are the two free staples, and this desk's <a href="/writers/writing-opportunities/">country atlas</a> slices the same data by where you live.</p>
<p>Filter: eligibility first, pay second, fit third — in that order, as the guide above argues. A market that fails eligibility is unreadable; a market that pays but never runs your kind of piece is a slow no.</p>
<p>Track: submissions are a pipeline, and pipelines need ledgers. The <a href="/writers/tracker/">submission tracker</a> records what went where and when, which is what turns "I never hear back" into data you can act on — see the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">follow-up timing guide</a>. The writers who get paid steadily are rarely the most talented in the room; they are the ones whose funnel never empties.</p>""",

"writers/guides/how-to-find-remote-writing-work": """
<h2>Desk notes: remote is a filter, not a genre</h2>
<p>Every paid opportunity on this desk is remote-workable by definition — what varies is time-zone expectations, communication style and whether "remote" means "anywhere" or "anywhere in this country for tax reasons." That distinction is the first filter to apply, and it is recorded: the <a href="/writers/writing/">opportunity desk</a> carries eligibility lines that say which, and the <a href="/writers/writing-opportunities/">country atlas</a> groups markets by geography.</p>
<p>The honest map of remote writing work has four quadrants: staff-remote (a salary, a manager, a country limit), contract-remote (the publication route this desk records most), platform-remote (content platforms and agencies — check the contract guide before signing), and client-direct (the freelance business in miniature; the <a href="/writers/guides/how-much-to-charge-for-an-article/">pricing guide</a> and the <a href="/writers/guides/track-your-writing-income/">income ledger</a> become your operating system).</p>
<p>Verification discipline travels with you: a remote gig you found through a channel you cannot trace deserves the same checks as an international publication — who is the client, what do past writers say, does the contract name real terms. The Purdue OWL's material on <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">professional writing contexts</a> is a fair grounding for the communication norms remote clients expect.</p>""",

"writers/guides/how-to-follow-up-on-a-writing-pitch": """
<h2>Desk notes: the follow-up, word for word</h2>
<p>The guide above gives the timing; here is the wording, because follow-up anxiety is mostly drafting anxiety. A professional follow-up is three sentences: restate the pitch in one line ("I'm following up on my 12 May pitch on X"), ask the question plainly ("do you have a sense of whether it might fit?"), and offer the exit gracefully ("if it's not a fit, no reply needed — I'll take the idea elsewhere after [date]"). No apology, no sarcasm, no second pitch smuggled in.</p>
<p>Timing lives in data, not nerves: if the publication states a window, the desk records it on the <a href="/writers/writing/">opportunity page</a> with the date we last read it; if it does not, <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>'s crowd-reported averages are the fairest proxy. The <a href="/writers/guides/when-to-follow-up-on-a-pitch/">dedicated timing guide</a> and the <a href="/writers/tracker/">tracker</a> turn this into arithmetic.</p>
<p>And the psychological rule that keeps pipelines healthy: silence is data, not insult. Magazines with volunteer slush readers can sit on submissions for a quarter without malice. Follow up once or twice as prescribed, then move the idea — the desk's <a href="/writers/learn/writing-for-publication/a-rejected-pitch-is-not-wasted/" rel="noopener">rejection guide</a> covers the rerouting.</p>""",

"writers/guides/how-to-get-your-first-paid-writing-gig": """
<h2>Desk notes: the first gig is a funnel problem</h2>
<p>First gigs feel like confidence problems and are actually funnel problems: you need enough at-bats for luck to find you. The desk's contribution to your funnel: the <a href="/writers/writing/">opportunity desk</a> records markets that accept new writers — including several that explicitly welcome unpublished samples — each with pay, eligibility and a last-verified date. Filter for "open to new writers," pick five, and follow the <a href="/writers/guides/how-to-submit-a-freelance-article/">submission mechanics guide</a> for each.</p>
<p>Lower the stakes honestly: the first paid clip is usually local, small or unglamorous — a regional outlet, a trade publication, a well-run content contract. All of it counts, all of it teaches you how editors edit, and none of it caps where you pitch next. The <a href="/writers/guides/how-to-build-writing-samples/">samples guide</a> shows how even self-published work becomes a legitimate portfolio piece while you wait.</p>
<p>Ground the craft side while the funnel runs: the Purdue OWL's <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">general writing resources</a> cover the professional-writing conventions editors assume, and the desk's own <a href="/writers/learn/">learn library</a> carries the dos-and-don'ts shelf. First bylines go to writers who are findable (samples), organised (tracker) and patient (pipeline) — in that order.</p>""",

"writers/guides/how-to-pitch-an-essay": """
<h2>Desk notes: the essay pitch, dissected</h2>
<p>Essay pitches fail differently from reported-piece pitches, so the desk separates them. A reported pitch sells access and information; an essay pitch sells a sensibility — which means the pitch itself must demonstrate the voice the essay will carry. Three sentences that do real work: the personal entry point (why you are the one who can write this), the turn (what the piece argues that a thousand think-pieces on the topic do not), and the form (length, structure, and why it suits the argument).</p>
<p>Where to send them: the <a href="/writers/writing/">opportunity desk</a> records essay-friendly markets with pay and eligibility; literary-aggregator databases like <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers'</a> filter by nonfiction. Read a market's published essays before pitching it — the pitch that quotes the section it belongs in reads like an insider's.</p>
<p>Craft grounding if you need it: the Purdue OWL's material on <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">purpose, audience and stance</a> is the formal skeleton under every good personal essay, and the desk's <a href="/writers/essays/">own essay shelf</a> exists partly as worked examples. And keep the timing discipline: essays age fast when tied to news, slow when tied to human nature — pitch accordingly, and track it all in the <a href="/writers/tracker/">tracker</a>.</p>""",

"writers/guides/how-to-price-ghostwriting-jobs": """
<h2>Desk notes: ghosting economics, stated plainly</h2>
<p>Ghostwriting pricing breaks freelancers' usual reference points, so the desk anchors it in three facts. One: you are selling the outcome, not the words — the client is buying a book/manuscript/speech that reads as theirs, which prices the project, not the hour. Two: your rate must carry the invisible work — interviews, research, restructure rounds — which is why per-word quotes mislead badly on long projects; price per project or per milestone. Three: the credit clause is money. "Acknowledgment" versus full anonymity versus a portfolio exception changes the fee conversation, and the <a href="/writers/guides/how-to-check-a-freelance-writing-contract/">contract guide</a> explains how to read what you are actually signing.</p>
<p>Calibration: the honest market range for book ghostwriting is enormous (four figures to six, by length, research load and the client's), so anchor on your own realised hourly from the <a href="/writers/tracker/">tracker</a> and quote projects that clear it with margin. For the business-of-writing framing, <a href="https://www.pw.org/" rel="noopener">Poets &amp; Writers</a>' tools pages and the <a href="https://en.wikipedia.org/wiki/Special:Search?search=ghostwriting" rel="noopener">ghostwriting reference material on Wikipedia</a> are fair orientation points.</p>
<p>The desk's one standing rule for ghosts: the agreement names the rounds. Two revision rounds included, further rounds billed — without that line, the project's real rate decays with every "small tweak."</p>""",

"writers/guides/how-to-submit-a-freelance-article": """
<h2>Desk notes: submission mechanics, done once, done right</h2>
<p>Most submissions fail on mechanics, not merit, so the desk keeps this page boring on purpose. The pre-flight: guidelines read on the publication's own site (the <a href="/writers/writing/">opportunity desk</a> links each one directly, with the date we last verified it), the pitch or article in the requested form, the requested subject line, and the bio line written to fit. Editors do not reject for missing fluff; they do bounce for ignored instructions.</p>
<p>The email itself: subject line per guidelines or "PITCH: [working title]" if none given; the pitch in the body of the email unless attachments are invited; links not attachments for samples — the <a href="/writers/guides/how-to-build-writing-samples/">samples guide</a> covers what to link. Send weekday mornings in the publication's time zone; log it immediately in the <a href="/writers/tracker/">tracker</a> with the date, so the <a href="/writers/guides/how-long-should-you-wait-for-an-editor/">waiting arithmetic</a> starts from fact.</p>
<p>And the house rule on exclusivity: unless the guidelines say simultaneous submissions are unwelcome, say so honestly in your pitch ("this is a simultaneous submission") if it is one. The publications that forbid simultaneity are telling you their response speed in advance — factor that into the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">follow-up plan</a>.</p>""",

"writers/guides/how-to-write-a-pitch": """
<h2>Desk notes: the pitch, annotated</h2>
<p>This is the desk's most-used guide, so here is the annotation editors never put in rejection letters. Subject line: "[Type] pitch: [specific title]" — the type (essay, reported feature, explainer) tells the editor which inbox brain to engage. First paragraph: the story in two sentences, written so a stranger could repeat it to a colleague — that is the test. Second: why you — access, evidence or lived experience, stated in one line without biography padding. Third: the practicals (length, timing, why this outlet). Done. The whole thing fits under two hundred words, which is the length test that most failed pitches fail.</p>
<p>Calibrate against the market: the <a href="/writers/writing/">opportunity desk</a> records what each publication actually runs, so read two recent pieces before pitching — the pitch that could only run in that outlet outscores three generic ones. For essay-specific voice work, the <a href="/writers/guides/how-to-pitch-an-essay/">essay pitch guide</a> continues this one; for the formal letter format some markets still ask for, see the <a href="/writers/guides/how-to-write-a-strong-query-letter/">query-letter guide</a>.</p>
<p>External grounding that is actually worth your time: the Purdue OWL's pages on <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">audience and purpose</a> underwrite every pitch principle above, and the desk's <a href="/writers/learn/writing-for-publication/a-rejected-pitch-is-not-wasted/">rejection guide</a> is where your pitch goes next if the answer is no.</p>""",

"writers/guides/how-to-write-a-strong-query-letter": """
<h2>Desk notes: the query, and where it still lives</h2>
<p>The query letter is the pitch's formal ancestor — longer, more structured, still required by some magazines, newspapers and most non-fiction book agents. The structure above (hook, angle, why-you, practicals, credits) maps cleanly onto the modern pitch, which is why the desk teaches it even in the email era: it teaches you to think in the editor's order.</p>
<p>For worked structure, the Purdue OWL's professional-writing sections — start from the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">OWL index</a> — carry annotated business-letter and query conventions, and the <a href="https://en.wikipedia.org/wiki/Special:Search?search=query+letter" rel="noopener">query-letter reference material on Wikipedia</a> gives the form's history and typical anatomy without vendor spin.</p>
<p>Where the desk differs from the old manuals: length discipline. Modern queries run shorter than the classic one-pager — the two-hundred-word register of the <a href="/writers/guides/how-to-write-a-pitch/">pitch guide</a> is the default unless a publication's guidelines ask for more (and the <a href="/writers/writing/">opportunity desk</a> records those guidelines verbatim, dated). And the credits line has one honest rule: published work only, named outlets, no adjectives about yourself. "My essay on X ran in Y" beats "passionate writer with a unique voice" every time it is read by a human.</p>""",

"writers/guides/how-writing-retainers-work": """
<h2>Desk notes: retainers are a contract before they are a calendar</h2>
<p>The retainer's promise — predictable income for predictable output — only holds if the contract carries the weight, so the desk reads retainers as contracts first. The five numbers that must be in writing: the monthly deliverable count, the per-piece scope (words, revisions, research included), the payment date and method, the rollover or use-it-or-lose-it rule, and the exit notice on both sides. A retainer missing any of the five is a mood, not an agreement — the <a href="/writers/guides/how-to-check-a-freelance-writing-contract/">contract guide</a> covers the reading.</p>
<p>Pricing the retainer: sum the monthly work at your real rates (the <a href="/writers/guides/how-much-to-charge-for-an-article/">article-pricing guide</a> and the realised-hourly ledger in the <a href="/writers/tracker/">tracker</a> give the numbers), then discount nothing or almost nothing — the trade for stability is their budget certainty, not your rate cut. Cap scope explicitly: "up to four posts of up to 800 words" is a boundary that keeps the arrangement alive.</p>
<p>The failure mode to design against: scope creep by drip. One extra "quick ask" a week is a fifth post by month's end. The professional response is neither anger nor silence — it is the agreed change process, restated once, kindly. Retainers that survive years are the ones where both sides know exactly what "yes" includes.</p>""",

"writers/guides/screenplay-format-basics": """
<h2>Desk notes: format is the industry's native language</h2>
<p>Screenplay format is not typographic fussiness; it is a protocol that lets a production team estimate, budget and shoot from your page. One page ≈ one minute is the whole economy, and it only holds when the format holds — which is why readers treat format errors as competence signals before they have judged a single scene. The rules in the guide above (12-point Courier, character names at 3.7 inches, dialogue blocked, action in present tense) are the industry's dialect; learn them once, exactly.</p>
<p>Two practical notes. First, the software is settled: free tools like <a href="https://fountain.io/" rel="noopener">Fountain-based editors</a> and any standard screenwriting app emit correct margins automatically, so "I couldn't format it" has been untrue for a decade. Second, for the formal conventions and their rationale, the <a href="https://en.wikipedia.org/wiki/Special:Search?search=screenplay+format" rel="noopener">screenplay-format reference material on Wikipedia</a> is a decent map, and produced screenplays (widely available as PDFs online) are the best calibration reading — read one produced script beside your own pages and the gaps announce themselves.</p>
<p>Where this desk connects: the <a href="/writers/compare/">format comparison page</a> sets screenplays beside the other writing formats, and the storytelling fundamentals live on the <a href="/writers/learn/creative-writing/">creative-writing shelf</a>. Format gets you read; story gets you sold. You need both, in that order.</p>""",

"writers/guides/the-tax-set-aside-habit": """
<h2>Desk notes: the set-aside, mechanised</h2>
<p>The guide above gives the principle; this note gives the plumbing, because the writers who get burned by tax are almost never under-informed — they are under-automated. The mechanism that works: a separate account, a fixed percentage moved the day any payment lands (not week's end — the day), and the transfer treated as the first bill, not the leftover. The desk's <a href="/writers/guides/track-your-writing-income/">income-tracking guide</a> supplies the ledger that makes the percentage audit-proof.</p>
<p>What percentage is honest? Jurisdictions differ wildly — Nigeria's self-assessment, the US quarterly system and the UK's self-assessment carry different rates and different deadlines — so the only safe universal is the habit, sized conservatively (a quarter of net income is a common starting rule) and trued-up annually against your actual bill. For the authoritative version of your own obligations, go to the source, not to freelancers' folklore: the official revenue authority for your country publishes the rates and dates, and a professional accountant's first consultation usually pays for itself in avoided penalties.</p>
<p>One desk-specific note, since writing income crosses borders often: foreign payments in foreign currencies are still income, and the exchange-rate record belongs in your ledger. The <a href="/writers/disclosure/">disclosure page</a> states the desk's boundaries plainly — general information, not tax advice — and this note stays inside them.</p>""",

"writers/guides/track-your-writing-income": """
<h2>Desk notes: the ledger that pays for itself</h2>
<p>The tracking habit this guide teaches is the desk's own operating system, scaled down: every payment recorded with date, source, currency, amount, and — the column everyone skips — realised hourly (amount divided by actual hours). Within a quarter, that last column reorders your whole business: the "prestigious" market at a poor hourly, the unglamorous client who pays fast and edits little, the article type that quietly out-earns everything. Decisions get made on evidence instead of mood.</p>
<p>The mechanics are deliberately simple: a spreadsheet with one row per payment beats most software, and the <a href="/writers/tracker/">submission tracker</a> on this desk handles the pre-payment half of the same pipeline (pitched, assigned, invoiced, paid). The tax dimension rides on top — the <a href="/writers/guides/the-tax-set-aside-habit/">set-aside guide</a> turns the ledger into automatic compliance — and the pricing feedback loop runs through the <a href="/writers/guides/how-much-to-charge-for-an-article/">rate-research guide</a>.</p>
<p>For the accounting vocabulary behind the simple ledger — invoicing, accrual versus cash basis — the <a href="https://en.wikipedia.org/wiki/Special:Search?search=revenue+recognition" rel="noopener">accounting reference material on Wikipedia</a> is honest background, and an accountant once a year keeps the ledger aligned with your jurisdiction's rules. The desk's standing boundary, stated on the <a href="/writers/disclosure/">disclosure page</a>: general information, not financial advice.</p>""",

"writers/guides/when-to-follow-up-on-a-pitch": """
<h2>Desk notes: the timing table, filled in</h2>
<p>The guide above gives the rules; here is the table they generate. Stated window of two weeks: follow up on day 17. Stated four weeks: day 29. Stated "up to six months" (literary fiction's classic): day 42, once, then let it ride to the deadline. No stated window: check the market's crowd-reported average on <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>, and default to three weeks for journalism, six for literary work. The <a href="/writers/writing/">opportunity desk</a> records each market's stated window with the date we last read it, so the first lookup is already done for desk-listed publications.</p>
<p>The second follow-up exists but is smaller: one more note, four weeks after the first, then the idea is formally yours again unless they reply. Say so in the note — "if I don't hear back by [date] I'll assume this isn't a fit and send it elsewhere" — which is courteous, and conveniently creates the deadline their inbox needed.</p>
<p>The machinery: none of this survives memory, so the <a href="/writers/tracker/">tracker</a> holds the dates and the <a href="/writers/guides/how-to-follow-up-on-a-writing-pitch/">wording guide</a> holds the sentences. Follow-up discipline is the cheapest professionalism there is — it costs three sentences and gains you a reputation as the writer who is easy to say yes to.</p>""",

"writers/guides/where-the-money-is-in-writing": """
<h2>Desk notes: the money map, kept current</h2>
<p>The honest version of this guide is a date-stamped market survey, which is exactly what the desk maintains: the <a href="/writers/writing/">opportunity desk</a> records publications with verified pay ranges and last-read dates, and the <a href="/writers/state-of-paid-writing-2026/">state-of-paid-writing survey</a> aggregates what the landscape paid this year. Use those two before any general advice — including the general advice below, which is structure rather than numbers.</p>
<p>The structural truth the guide sketches holds across years: the money concentrates where the writing touches a business outcome. Marketing and content roles pay salaries; trade and technical writing pays for precision; journalism pays for access and speed; and the literary tier pays in reputation with money as a bonus. None of these tiers is a moral judgement — but knowing which tier a market sits in tells you what its rate ceiling looks like before you pitch it, and the <a href="/writers/guides/how-much-to-charge-for-an-article/">pricing guide</a> turns that into quotes.</p>
<p>The portfolio move that compounds: build across two tiers deliberately — one for cash flow (business-adjacent), one for trajectory (the bylines that open doors) — and let the <a href="/writers/guides/track-your-writing-income/">realised-hourly ledger</a> tell you when the balance is wrong. Writers who burn out usually picked one tier and pretended it was two.</p>""",

"writers/guides/where-to-start-with-a-screenplay": """
<h2>Desk notes: the first page is a format and a promise</h2>
<p>Starting the screenplay is two decisions, and the guide above orders them correctly: learn the format first (it is small, fixed and covered in the desk's <a href="/writers/guides/screenplay-format-basics/">format basics</a>), then write scenes that keep its promise — one page, roughly one minute, every scene doing one job. The beginner error is reversing the order: drafting two hundred unpunctuated pages and discovering formatting is load-bearing at the worst possible moment.</p>
<p>The writing-side craft lives on the desk's <a href="/writers/learn/creative-writing/">creative-writing shelf</a> and the <a href="/writers/learn/structure-formatting/">structure section</a>; for the screen-specific grammar, reading produced scripts is worth more than any manual — major studios' award-season release PDFs circulate freely, and the <a href="https://en.wikipedia.org/wiki/Special:Search?search=screenwriting" rel="noopener">screenwriting reference material on Wikipedia</a> maps the terminology (slugline, action, parenthetical) before you meet it in the wild.</p>
<p>The desk's practical push: write the first ten pages in correct format this week, not the perfect outline. Ten formatted pages teach you more than a month of planning — they surface your pacing instincts, your dialogue tics, and whether the premise survives contact with scenes. Then the <a href="/writers/guides/how-to-build-writing-samples/">portfolio rule</a> applies: archive them, dated, because the spec pages you write this year are the writing samples your future collaborations will ask for.</p>""",

}

# ---------------- /writers/learn/<section>/ hubs (20) ----------------

WRITERS_DEPTH["writers/learn/academic-writing"] = """
<h2>Desk notes: what academic writing actually demands</h2>
<p>Academic writing is argument under citation discipline. The form asks you to make a claim, show exactly where every supporting fact came from, and let the reader check both — which is why it feels slow at first and trustworthy once it clicks. The guides in this section walk the core moves: the thesis that says one precise thing, the paragraph that develops it, and the citation that keeps you honest.</p>
<p>For the conventions themselves, the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL</a> is the desk's standing external recommendation: its style-guide coverage (APA, MLA, Chicago) is free, maintained and authoritative in a way aggregated tips never are. Pair it with this section's guides and you have both the formal rules and the working habits.</p>
<p>The desk's one addition for writers entering academia from journalism or blogging: academic register is not stuffing your sentences with long words. It is hedging precisely ("the data suggest" rather than "this proves"), attributing every claim, and structuring for a reader who will check you. If you can write a clean reported article, you already have the muscles; the section's <a href="/writers/learn/editing-proofreading/">editing guides</a> tune them to the form.</p>"""

WRITERS_DEPTH["writers/learn/common-problems"] = """
<h2>Desk notes: problems are patterns, and patterns have fixes</h2>
<p>Almost every stuck draft traces to one of a small set of patterns: no thesis (the piece has energy but no destination), buried lede (the real first sentence hides in paragraph four), scope creep (three essays wearing one title), or the fear spiral that mistakes drafting for judgement. This section exists so you can diagnose by pattern instead of by despair — naming the problem is half the fix, which is why the guides here are short and specific.</p>
<p>The desk's standing advice for the meta-problem ("my writing is bad"): bad is a draft's permanent address, not its fate. The <a href="/writers/learn/editing-proofreading/">editing section</a> carries the repair routines, the <a href="/writers/learn/writing-process/">process section</a> prevents the most common causes, and the Purdue OWL's <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">general writing resources</a> hold the formal versions of nearly every fix this section teaches.</p>
<p>One honest note about block: it is usually decision fatigue wearing a dramatic name. When the page stalls, the question is rarely "why can't I write" and usually "which of two next moves haven't I chosen?" Pick either one; drafts survive wrong turns better than stalled ones, and the <a href="/writers/learn/start-writing/">starting guides</a> cover the lowest-friction ways back in.</p>"""

WRITERS_DEPTH["writers/learn/creative-writing"] = """
<h2>Desk notes: craft before talent, always</h2>
<p>Creative writing rewards two learnable things ahead of any inherited gift: reading like a writer (noticing how a scene moves time, how dialogue withholds) and finishing things. This section's guides serve both — the craft pages break down scene, character and voice into moves you can practise, and the habit pages keep you finishing, because an unfinished brilliant story teaches nothing and a finished flawed one teaches everything.</p>
<p>For grounding beyond the desk, read widely across form: the public-domain libraries at <a href="https://www.gutenberg.org/" rel="noopener">Project Gutenberg</a> put a century of fiction — much of it structurally shameless and useful — one click away, and the <a href="https://en.wikipedia.org/wiki/Special:Search?search=narrative+structure" rel="noopener">narrative-structure reference material on Wikipedia</a> maps the terminology (three-act, frame, in medias res) you will meet in craft discussions.</p>
<p>The desk's practical ladder: write the scene, not the novel. Scenes are the unit of craft — a complete scene with a want, an obstacle and a turn teaches you more per hour than any amount of world-building notes. When a scene works, the <a href="/writers/learn/editing-proofreading/">editing section</a> shows you how to see why it worked, which is the whole discipline in miniature.</p>"""

WRITERS_DEPTH["writers/learn/dos-and-donts"] = """
<h2>Desk notes: rules are compression, not law</h2>
<p>Every do and don't on this shelf is a compressed story: a mistake thousands of writers made and a fix that survived. That is how to read them — not as commandments but as accumulated evidence. "Don't bury the lede" is every editor who stopped reading at paragraph four; "do read it aloud" is every writer who caught a dead sentence by ear after the eyes missed it ten times.</p>
<p>The shelf is organised by form — the <a href="/writers/learn/dos-and-donts/dos-and-donts-of-writing/">general writing list</a>, the essay, the cover letter, professional email, blogging — because context flips several rules. Casual voice is a don't in a grant application and a do in a newsletter; the guide above each list says which world it governs. For the formal register side of the arguments, the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian's public style guide</a> shows how a working newsroom encodes its own dos and don'ts — instructive reading precisely because it is maintained in public.</p>
<p>The desk's one meta-rule: when a don't and your instinct disagree, find out which evidence is newer. Conventions move (the singular they, sentence-starting conjunctions), and writers who update their rulebook periodically write more naturally than either the rebels or the strict constructionists.</p>"""

WRITERS_DEPTH["writers/learn/editing-proofreading"] = """
<h2>Desk notes: two different jobs, in the right order</h2>
<p>Editing and proofreading fail when they run together, so this section insists on the sequence: revise (argument, structure, what the piece says) then edit (paragraphs, sentences, what each part does) then proofread (surface: spelling, punctuation, consistency). Doing proof-level work on a draft that still needs structural surgery is the most common wasted afternoon in writing — the guides here sequence the work so each pass has one job.</p>
<p>The desk's standing techniques, expanded: the read-aloud pass catches rhythm damage that silent reading forgives; the reverse outline (one sentence per paragraph, then read the sentences) exposes structural gaps no line edit can hide; and the print-or-change-font trick defeats your brain's autocomplete, which is the enemy in every proofing pass. The Purdue OWL's <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">writing-process and revision pages</a> formalise all three, and the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian style guide</a> settles most consistency arguments (numbers, titles, abbreviations) with an authoritative word.</p>
<p>And the calibration that keeps this work humane: a piece needs enough editing to be clear and honest, not enough to be inhuman. When a draft has lost your voice in the name of polish — that is a real failure mode, the opposite of the mess it was meant to fix — walk it back one pass.</p>"""

WRITERS_DEPTH["writers/learn/examples"] = """
<h2>Desk notes: how to learn from examples without copying them</h2>
<p>Examples teach by dissection, not imitation. The right way through this section: read an example once as a reader, then again with one question — what did the writer do, and where exactly did they do it? Where does the piece earn the second paragraph? How does the ending refuse to summarise? That second reading is the whole skill; the first is just pleasure, pleasant but uneducational.</p>
<p>The desk keeps the worked examples here annotated by move, and the public-domain archive at <a href="https://www.gutenberg.org/" rel="noopener">Project Gutenberg</a> extends the shelf infinitely: century-old essays and journalism hold up as structure lessons precisely because their craft is visible — the seams show, and visible seams are learnable seams. For form definitions while you dissect, the <a href="https://en.wikipedia.org/wiki/Special:Search?search=essay" rel="noopener">encyclopedia entries on the essay and its forms</a> are honest background.</p>
<p>The counter-habit to guard against: example-hoarding. Reading forty openings is preparation, not practice; writing three bad openings after reading two good ones is the actual curriculum. The shelf works best as a loop — read one, write one, compare, repeat — and the <a href="/writers/learn/start-writing/">starting guides</a> keep the writing half of the loop honest.</p>"""

WRITERS_DEPTH["writers/learn/grammar-language"] = """
<h2>Desk notes: grammar as a service, not a scorecard</h2>
<p>Grammar exists to make sentences carry meaning without ambush, which is the spirit in which this section teaches it: the comma rules, the agreement patterns and the punctuation calls are tools for protecting the reader, not hurdles for the writer to trip over in public. Learn them by function — "this comma prevents this misreading" survives; "because the teacher said so" does not.</p>
<p>The desk's external anchors, kept few and authoritative: the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's grammar and mechanics sections</a> for rules with explanations and exercises, and the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian's public style guide</a> for the working-journalist resolutions of the arguments rules don't settle (data is/are, caught between British and American conventions, when to break your own rule on purpose).</p>
<p>One honesty note the section keeps repeating because the internet will not: several "grammar rules" you absorbed — never split an infinitive, never end a sentence with a preposition — were imported preferences, not laws of the language. The test that matters is whether the reader stumbles. Fix stumbles; keep your voice; and when the stakes are formal, let the <a href="/writers/learn/editing-proofreading/">proofing guides</a> catch what your ear forgives.</p>"""

WRITERS_DEPTH["writers/learn/journaling-personal"] = """
<h2>Desk notes: journaling that survives busy months</h2>
<p>The journaling shelf sits deliberately beside the craft sections, because a journal is where most writers keep their sentence muscles warm between projects — but the shelf's guides serve the practice on its own terms too, and the evidence-informed version of journaling is simpler than the aesthetic versions imply: brief, regular, and honest beats long, beautiful and abandoned.</p>
<p>The mechanics that hold up: a fixed trigger (with the morning coffee, after lights-out), a tiny floor (three sentences — lower on bad days), and no re-reading requirement. The research summary on <a href="https://en.wikipedia.org/wiki/Special:Search?search=journaling#Writing_therapy" rel="noopener">writing as a therapeutic practice on Wikipedia</a> is a fair orientation to why small regular expressive writing keeps being associated with measurably better outcomes; this desk adds no medical claims to that literature — if you are processing something heavy, a professional is the right reader, not a notebook alone.</p>
<p>The craft spillover is real and free: journals teach voice by removing the audience, the exact opposite of everything else on this desk. Writers blocked on the <a href="/writers/learn/start-writing/">starting guides</a> often find the block dissolves after two weeks of audienceless pages — and the <a href="/writers/learn/creative-writing/">creative shelf</a> shows where to spend that recovered flow.</p>"""

WRITERS_DEPTH["writers/learn/online-writing"] = """
<h2>Desk notes: writing for readers who scroll</h2>
<p>Online writing is a distinct discipline, not writing-with-URLs: readers arrive mid-feed, decide in seconds, and leave without guilt. The section's guides teach the corresponding moves — the front-loaded structure that survives skimming, subheads that carry meaning rather than decoration, paragraphs that breathe on a phone screen, links that earn their exits.</p>
<p>The fundamentals transfer from everywhere good: the Purdue OWL's <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">audience-and-purpose material</a> underwrites the scan-friendly structure, and reading your own piece on an actual phone before publishing catches more UX sins than any checklist — the thumb is the harshest editor most writers never consult.</p>
<p>One desk-specific caution, since this site monetises honestly and so might yours: online writing's economy rewards volume, and volume is where voice goes to die. The durable pattern is the one this desk follows — fewer, better pieces, structured for scanners and written for humans, with the money mechanics handled elsewhere (see the desk's <a href="/writers/guides/where-the-money-is-in-writing/">money map</a> and the <a href="/writers/disclosure/">disclosure page</a> for how this publication handles the advertising boundary).</p>"""

WRITERS_DEPTH["writers/learn/professional-writing"] = """
<h2>Desk notes: the professional register, decoded</h2>
<p>Professional writing is translation work: you are converting thought into a form a busy, wary reader can act on. That is why the section's guides obsess over the same small set of moves — the ask stated early, the context sized to the reader's stake, the structure that lets a skim still land the message. An email that respects the reader's minutes is not a style choice; it is the entire genre.</p>
<p>The external anchor worth bookmarking: the Purdue OWL's <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">professional and technical writing sections</a>, which carry the conventions (memos, reports, business correspondence) with worked examples — free, maintained, and the closest thing the field has to a neutral reference. For the register questions style guides actually settle, the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian style guide</a> is a working newsroom's public answers.</p>
<p>The desk's calibration note: professional does not mean bloodless. The most effective workplace writers keep one degree of voice — a plain sentence where the template would have written a paragraph — because readers trust prose that a human clearly wrote on purpose. If the register feels like a costume, the <a href="/writers/learn/editing-proofreading/">editing section</a> has a pass for finding the sentences where you disappeared.</p>"""

WRITERS_DEPTH["writers/learn/research-sources"] = """
<h2>Desk notes: research is a discipline of receipts</h2>
<p>This section teaches the least glamorous skill with the highest ceiling: knowing what you know, and being able to show where it came from. The guides walk the core habits — primary before secondary, sources logged at capture time (the copy-paste of a link is not a citation system), and the honesty of labelling what you inferred versus what you were told.</p>
<p>The desk runs the same discipline in public: every time-sensitive claim on this site carries a last-checked date, the fact labels live on the <a href="/writers/intelligence/">intelligence page</a>, and the <a href="/writers/learn/writing-for-publication/">publication guides</a> assume you can defend every factual sentence to an editor. For the formal layer — source hierarchies, citation systems — the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's research and citation resources</a> are the free standard, and the <a href="https://en.wikipedia.org/wiki/Special:Search?search=source+evaluation" rel="noopener">source-evaluation reference material on Wikipedia</a> is a fair orientation to the criteria professionals apply.</p>
<p>The desk's one addition for the AI-era: an unfamiliar-sounding claim now deserves one more verification step than it used to, because fabricated fluency exists. The habit that survives any tool: no sentence gets published whose source you could not produce within a minute of being asked. That is the whole discipline; everything here is technique for keeping it.</p>"""

WRITERS_DEPTH["writers/learn/start-writing"] = """
<h2>Desk notes: starting is smaller than it feels</h2>
<p>The starting problem is rarely the writing; it is the size of the imagined obligation — the book, the career, the finished essay — looming over the first sentence. This section's guides are all reductions: start with one paragraph, one timed session, one bad page on purpose. The desk's strongest-held opinion about starting: velocity first, quality second, and never on the same day. Drafting and judging use different mental gears, and writers who run both at once produce nothing and hate it.</p>
<p>The mechanics that unstick most people: a timer (fifteen minutes, honestly kept), a prompt or the <a href="/writers/learn/examples/">example shelf</a> as a model to answer, and permission to write the boring true version first. The Purdue OWL's material on <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">the writing process</a> formalises the draft-then-revise separation this section preaches.</p>
<p>And the destination matters less than the direction: a writer with two hundred imperfect words a day outearns — in craft and in career — a writer with a perfect plan and no pages. When the pages exist, the <a href="/writers/learn/writing-process/">process section</a> and the <a href="/writers/learn/editing-proofreading/">editing section</a> take over, and the <a href="/writers/guides/how-to-get-your-first-paid-writing-gig/">first-gig guide</a> shows what those pages can become.</p>"""

WRITERS_DEPTH["writers/learn/structure-formatting"] = """
<h2>Desk notes: structure is a reader's kindness</h2>
<p>Structure is how a piece keeps its promise to the reader: the title promises a thing, the opening defines it, the middle delivers it in an order the reader can follow, and the ending releases them without betrayal. This section's guides treat that chain as craft rather than formula — because the fix for most messy drafts is not more writing, it is an honest reverse outline: one sentence per paragraph, then read the sentences and watch the structure announce what it actually is.</p>
<p>The formal frameworks — the inverted pyramid for news, the essay's classical arc, the report's front-loaded summary — are all reader-kindness systems, and the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's organising-and-outline resources</a> cover them with exercises; the desk's <a href="/writers/compare/">format comparison page</a> sets the major forms beside each other so the structural expectations stop blurring together.</p>
<p>Formatting deserves its equal billing in this section's title: headings that mean something, paragraphs sized for the page they live on (a screen or a printout), lists that carry parallel items — all of it is structure at the sentence scale. The <a href="/writers/learn/online-writing/">online-writing guides</a> cover the screen-specific half, where structure is also interface.</p>"""

WRITERS_DEPTH["writers/learn/writing-basics"] = """
<h2>Desk notes: the basics are the professional layer</h2>
<p>There is a version of "basics" that means remedial, and this section is not it. The basics here — clear subject-verb relationships, concrete nouns, verbs that carry their own weight, paragraphs with one job each — are the layer professionals return to deliberately, because complexity fails first at the foundations. Every editing pass on this desk's own pages starts by checking whether the basics held.</p>
<p>The guides in this section walk those moves with examples, and the external standard behind them is the same one universities use: the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL</a>, free and maintained, whose grammar and general-writing sections pair cleanly with everything here. For usage questions the rules books disagree on, the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian's public style guide</a> shows one newsroom's working answers.</p>
<p>The desk's practice advice: drill the basics on throwaway drafts, not on work that matters. Ten minutes rewriting a bad paragraph three ways — plainer, shorter, concrete — builds the reflexes that show up unbidden when a real deadline looms. The <a href="/writers/learn/writing-process/">process section</a> gives those drills a schedule, and the <a href="/writers/learn/editing-proofreading/">editing section</a> turns them into passes.</p>"""

WRITERS_DEPTH["writers/learn/writing-checklists"] = """
<h2>Desk notes: checklists are how pilots write, too</h2>
<p>This section links the desk's checklist library — and the honest theory behind it comes from aviation: checklists exist not because professionals forget, but because memory under load is exactly where the important steps go missing. A pre-submission checklist is the same instrument for prose: did the lede land where it claims, does every claim carry a source, does the piece say the thing the title promised, are the links live, the names spelled right, the dates honest?</p>
<p>Build yours in three tiers, mirroring the section's structure: a pre-writing check (what is this piece, who is it for, what must it say), a revision check (structure, argument, the <a href="/writers/learn/editing-proofreading/">editing passes</a> in order), and a pre-send check (guidelines obeyed, the <a href="/writers/guides/how-to-submit-a-freelance-article/">submission mechanics</a> done, tracker updated). The desk's own publish checklist is similar; the <a href="https://en.wikipedia.org/wiki/Special:Search?search=checklist" rel="noopener">checklist reference material on Wikipedia</a> summarizes the evidence behind the instrument in fields where errors cost more than embarrassment.</p>
<p>The calibration: a checklist grows by post-mortem. Every embarrassing miss becomes one line on the list — that is how the instrument stays short enough to actually use and sharp enough to matter.</p>"""

WRITERS_DEPTH["writers/learn/writing-for-publication"] = """
<h2>Desk notes: publication is a system, not a lottery</h2>
<p>This section's guides connect the craft shelves to the paid world, so the desk frames it as the hinge it is: everything before this section makes you a better writer; this section makes you a published one. The system has four moving parts, each covered elsewhere on the desk and each recorded with dates: finding markets (the <a href="/writers/writing/">opportunity desk</a>, with pay and eligibility verified), fitting the market (read two recent pieces before pitching — the <a href="/writers/guides/how-to-write-a-pitch/">pitch guide</a> operationalises this), submitting professionally (the <a href="/writers/guides/how-to-submit-a-freelance-article/">mechanics guide</a>), and tracking the pipeline (the <a href="/writers/tracker/">tracker</a>).</p>
<p>The reference layer for widening the search beyond the desk: <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers' magazine database</a> and <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a> are the two free staples — the first for discovering markets, the second for their real response-time behaviour.</p>
<p>The mindset note the section keeps teaching: rejection is the system working, not failing. A submission is a request for information as much as for money — every no with a timing pattern tells you where your work fits. The <a href="/writers/learn/writing-for-publication/a-rejected-pitch-is-not-wasted/">rejection guide</a> turns that data into the next pitch.</p>"""

WRITERS_DEPTH["writers/learn/writing-glossary"] = """
<h2>Desk notes: why a glossary earns its page</h2>
<p>This section's glossary collects the working vocabulary of the desk — the terms editors, style guides and this site's own guides use without pausing to define. It exists because vocabulary is a gate: a writer who loses an instruction to an undefined term ("kill fee," "evergreen," "dek") loses more than a word; they lose the sentence it lived in.</p>
<p>The full terms live on the desk's <a href="/writers/glossary/">glossary page</a> — this section hub is the doorway. Use it the way professionals do reference works: not to memorise, but to look up the word the moment it blocks you, then return to the task. For deeper definitions than a glossary can carry, the <a href="https://en.wikipedia.org/wiki/Special:Search?search=journalism+terminology" rel="noopener">journalism-terminology reference material on Wikipedia</a> and the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian's public style guide</a> both define the trade's vocabulary in working context.</p>
<p>A learning note from the desk's experience: terms stick when met three times in the wild. So the fastest way through this section is reading — the <a href="/writers/learn/examples/">examples shelf</a> and the <a href="/writers/learn/dos-and-donts/">dos-and-don'ts lists</a> are full of the vocabulary in action, glossary open in a second tab.</p>"""

WRITERS_DEPTH["writers/learn/writing-process"] = """
<h2>Desk notes: process is personal, parts are not</h2>
<p>Every writer's process is idiosyncratic and every good process contains the same four stages: capture (ideas in, before they evaporate), draft (fast, judgement-free), revise (structure before sentences), and ship (the deadline that converts writing into work). This section's guides walk all four — and the desk's advice is to steal the stages while ignoring everyone's rituals, including ours. The mysticism around process ("I need the exact pen") is procrastination with props.</p>
<p>The external backbone: the Purdue OWL's writing-process resources — reachable from the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">OWL index</a> — lay out the standard stages with exercises, and they pair cleanly with this section's habit guides. What the formal resources omit, the desk's own pages supply: the paid-world half of the process (pitching, invoicing, the <a href="/writers/tracker/">tracker</a>) that turns finished drafts into a career.</p>
<p>The calibration most writers need: find which stage you secretly skip. Non-starters usually skip capture (nothing to draft from); chronic blockers skip drafting discipline (judging while generating); perpetual-polishers skip shipping (revising as hiding). The section's guides are ordered so you can diagnose your skipped stage and fix exactly that — and the <a href="/writers/learn/start-writing/">starting guides</a> are the floor under all of it.</p>"""

WRITERS_DEPTH["writers/learn/writing-templates"] = """
<h2>Desk notes: templates are scaffolding, not a cage</h2>
<p>This section links the desk's template library, and the honest theory of templates is that they automate the decisions that should not be decisions. A pitch template exists so your attention goes to the idea, not the formatting; a cover-letter template exists so the structure is right while the voice stays yours. The failure mode is template-worship — filing in blanks without asking whether the structure fits this piece — and every guide here teaches against it.</p>
<p>The library's templates mirror the desk's working formats: the pitch and query structures from the <a href="/writers/guides/how-to-write-a-pitch/">pitch guide</a>, the professional registers from the <a href="/writers/learn/professional-writing/">professional-writing section</a>, the submission cover notes from the <a href="/writers/guides/how-to-submit-a-freelance-article/">submission mechanics guide</a>. Each template carries its own "what to change first" note — start there, always.</p>
<p>For the formal conventions some templates encode (business letters, reports), the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's professional-writing sections</a> are the free authoritative reference, and the desk's <a href="/writers/learn/structure-formatting/">structure section</a> explains why each block sits where it sits — because a template you understand is a tool, and one you merely fill in is a slot machine.</p>"""

WRITERS_DEPTH["writers/learn/writing-tools"] = """
<h2>Desk notes: tools serve habits, never the reverse</h2>
<p>This section is the doorway to the desk's tool library — and the desk's honest position on writing tools is that there are only three kinds worth your attention: capture tools (the notebook or app that never loses an idea), drafting tools (the plain editor that resists distraction), and checking tools (the reader's-eye pass for structure, grammar and the <a href="/writers/learn/editing-proofreading/">editing sequence</a>). Everything else is stationery.</p>
<p>The library itself — <a href="/writers/tools/">the full tool shelf</a> — is built around those three jobs, each tool doing one thing and stating it plainly, the same way the desk's own guides do. For the conventions that checking tools enforce (and that no tool should overrule), the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL</a> remains the free standard; for the style calls tools get wrong, a public style guide like the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian's</a> is the arbiter.</p>
<p>The desk's one rule about tool-hunting, learned from watching writers redecorate instead of drafting: when you notice yourself shopping for tools twice in a month, the problem is on the page, not in the setup. Pick the plainest tool that works, and let the <a href="/writers/learn/start-writing/">starting guides</a> have the time you were about to spend configuring.</p>"""

# ---------------- /writers/learn/<section>/<guide>/ (9) ----------------

WRITERS_DEPTH["writers/learn/common-problems/my-introduction-is-weak"] = """
<h2>Desk notes: the introduction repair pass</h2>
<p>Weak introductions are almost always strong openings buried under throat-clearing — the warm-up paragraph where you explained the topic to yourself. The desk's repair pass, in order: delete the first sentence (it is always the worst one), find the first sentence that could not appear in anyone else's piece, and start there. Then check the promise: a good introduction tells the reader exactly what they will get and in what register, which is why vague openings and vague pieces usually share a draft.</p>
<p>For the formal anatomy — lead, nut graf, thesis — the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's introductions material</a> carries worked examples across genres, and this desk's <a href="/writers/learn/examples/">examples shelf</a> lets you dissect openings from published work. The <a href="/writers/learn/editing-proofreading/">editing section</a> holds this repair pass in its proper sequence: fix the opening after the structure is right, never before.</p>"""

WRITERS_DEPTH["writers/learn/common-problems/my-writing-sounds-too-formal"] = """
<h2>Desk notes: formal is a register, not a personality</h2>
<p>Writing that sounds too formal is usually writing that is frightened — of being wrong, of being casual, of a reader who might judge. The desk's fix runs on one operation: say the sentence aloud the way you would tell a colleague, then write that down and only then formalise what genuinely needs formality (technical terms, professional courtesy). Most drafts improve by twenty percent from this one pass, because the ear knows the register the hand was over-dressing.</p>
<p>Two mechanical de-formalisers from the <a href="/writers/learn/editing-proofreading/">editing section</a>: swap every nominalisation back into a verb ("make a decision" becomes "decide"), and cut every hedge that is not doing honest work ("it could perhaps be suggested that" was never saying anything). The <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian's public style guide</a> shows how professionally plain the working register can be — newsrooms write for a million readers a day in sentences a teenager can parse.</p>"""

WRITERS_DEPTH["writers/learn/dos-and-donts/dos-and-donts-of-writing"] = """
<h2>Desk notes: how to use a list of rules</h2>
<p>The general list above compresses this desk's most-repeated corrections into scannable lines, and it works best used diagnostically rather than decoratively: keep it beside a current draft and check five lines at random — the violations you find are your personal patterns, worth more than the list itself. The dos encode the habits professionals keep (read aloud, cut the first paragraph, concrete nouns); the don'ts encode the failures editors see most (hedges, throat-clearing, the throat-clearing hedges).</p>
<p>Where the rules come from: this desk's own edit logs, plus the public standards — the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL</a> for the formal versions and the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian style guide</a> for the working-newsroom calls. For the same treatment applied to specific forms, the essay, cover-letter, email and blogging lists on this shelf sit one click away, and the <a href="/writers/learn/editing-proofreading/">editing section</a> turns the don'ts into actual passes.</p>"""

WRITERS_DEPTH["writers/learn/dos-and-donts/dos-and-donts-of-a-cover-letter"] = """
<h2>Desk notes: the cover letter's single job</h2>
<p>A cover letter has one job: make someone want to read the thing attached. Every do and don't above serves that test — the length discipline (under a page, ideally half), the opening that goes to the point (the piece, the fit, the ask), the close that makes the next step easy. The classic failures are all the same failure: the letter talks about the writer's needs instead of the reader's interest. "I have always dreamed of writing for you" spends your best hundred words on you.</p>
<p>For job-application letters specifically (a cousin form with different etiquette), the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's cover-letter sections</a> carry worked examples, and the desk's <a href="/writers/guides/how-to-write-a-strong-query-letter/">query-letter guide</a> covers the pitch-letter variant editors actually receive. Pair the letter with the <a href="/writers/guides/how-to-build-writing-samples/">samples guide</a> — the letter's real power is what it points to.</p>"""

WRITERS_DEPTH["writers/learn/dos-and-donts/dos-and-donts-of-an-essay"] = """
<h2>Desk notes: what the essay form owes the reader</h2>
<p>The essay's dos and don'ts compress into one contract: an idea, pursued honestly, with a shape the reader can hold. The dos above serve the contract — the thesis stated early enough to orient, the paragraphs that advance rather than list, the ending that lands the idea instead of summarising it. The don'ts record the breakages: the five-paragraph reflex stretched over a thought that needed seven paragraphs, the conclusion that introduces its first new idea (a betrayal of everything before it), the anecdotes that decorate instead of argue.</p>
<p>The desk's worked examples live on the <a href="/writers/learn/examples/">examples shelf</a> — dissect one against this list and the rules stop being rules. For the formal scaffolding, the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's essay-writing sections</a> carry the academic variants, and the desk's <a href="/writers/guides/how-to-pitch-an-essay/">essay-pitch guide</a> is where a finished essay goes to earn.</p>"""

WRITERS_DEPTH["writers/learn/dos-and-donts/dos-and-donts-of-blogging"] = """
<h2>Desk notes: blogging is a promise schedule</h2>
<p>Blog dos and don'ts differ from essay rules in one structural way: the blog is a series, and half the craft is keeping the series alive. The dos above encode that — the scannable structure, the honest titles, the posting rhythm you can actually sustain. The don'ts record the serial-killer habits: burying the point below the scroll, writing for the algorithm in a voice nobody would recognise, abandoning the archive when enthusiasm cools.</p>
<p>The desk's position from running its own publication: consistency beats intensity. One honest post a week for a year builds more readers — and more skill — than a June of daily posts followed by silence. The craft layer lives in the <a href="/writers/learn/online-writing/">online-writing section</a> (structure for scanners, links that earn exits), and the <a href="/writers/learn/editing-proofreading/">editing section</a> keeps post number forty as clean as post number one.</p>"""

WRITERS_DEPTH["writers/learn/editing-proofreading/how-to-make-writing-more-concise"] = """
<h2>Desk notes: concision is subtraction with a test</h2>
<p>Cutting words is only concision when the meaning survives — otherwise it is just shorter. The desk's cutting pass runs on three tests, applied line by line: does this word carry meaning (delete "very," "really," "in order to"), does this sentence advance the piece (delete the applause line), does this paragraph earn its length (delete the second example that proves the same thing as the first). The guide above gives the categories; this is the calibration for using them without hollowing the prose.</p>
<p>The classic exercises hold up: rewrite a paragraph in half its words, then compare what was actually lost (usually nothing), and the sentence-combining drills in the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's conciseness sections</a> train the reflex with worked keys. The desk's own <a href="/writers/learn/editing-proofreading/">editing sequence</a> slots concision where it belongs — after structure, before proofing — because cutting early just relocates the work.</p>"""

WRITERS_DEPTH["writers/learn/dos-and-donts/dos-and-donts-of-professional-emails"] = """
<h2>Desk notes: the email as a small document</h2>
<p>Professional email is document craft in miniature, which is why the dos above read like the <a href="/writers/learn/professional-writing/">professional-writing section</a> compressed: the ask in the first two lines, the subject line that files itself, one topic per email, the close that names the next action and its owner. The don'ts are the genre's recorded disasters — the novel-length context dump, the passive-aggressive "per my last email," the reply-all at scale.</p>
<p>The desk's one addition, from years of editorial correspondence: write the subject line last, after the email exists, and make it the ask in five words ("Pitch: essay on X — 900 words"). Editors and clients triage by subject; the five honest words are the difference between opened and archived. For the formal conventions (salutations, sign-offs, formatting), the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's business-correspondence sections</a> carry worked examples, and the <a href="/writers/guides/how-to-submit-a-freelance-article/">submission guide</a> applies all of it to the pitch email specifically.</p>"""

WRITERS_DEPTH["writers/learn/online-writing/how-to-write-social-media-copy"] = """
<h2>Desk notes: the copywriter's honest physics</h2>
<p>Social copy is writing under a guillotine: the first line decides everything, because the platform shows three words and a "more" link. The guide above teaches the corresponding discipline — hook first (specific, curious, honest), one idea per post, the CTA that asks exactly one thing. The don'ts are the engagement-bait habits that trade long-term trust for this afternoon's numbers, and the desk holds the line it holds everywhere: the voice that survives is the one a reader could recognise without the logo.</p>
<p>Two craft transfers make this section easier than it looks: everything from the <a href="/writers/learn/online-writing/">online-writing guides</a> about front-loading applies at sentence scale, and the concision drills from the <a href="/writers/learn/editing-proofreading/">editing section</a> are the daily gym of the platform writer. For the advertising-adjacent conventions (CTAs, offer structure), the <a href="https://en.wikipedia.org/wiki/Special:Search?search=advertising+copywriting" rel="noopener">copywriting reference material on Wikipedia</a> maps the terminology without vendor mythologies.</p>"""

# ---------------- /writers/writing-opportunities/<country>/ (3) ----------------

WRITERS_DEPTH["writers/writing-opportunities/germany"] = """
<h2>How this page is maintained</h2>
<p>This page is reviewed by the BRYME writers desk at every sweep: each listing's pay range, language expectations and submission route are re-read from the publication's own guidelines, and the desk records the last-verified date beside every entry rather than promising availability it cannot check daily. Where a listing states no response window, the desk says so plainly — see the <a href="/writers/guides/how-long-should-you-wait-for-an-editor/">waiting guide</a> for how to work with unstated windows.</p>
<p>For markets beyond this page, the <a href="/writers/writing/">full opportunity desk</a> carries the complete verified list, and the desk's <a href="/writers/guides/how-to-find-international-writing-opportunities/">international-pitching guide</a> covers the mechanics that Germany listings share with every cross-border market: currency, transfer costs, and the eligibility line read on the publication's own site. Reference databases worth pairing with this page: <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers' magazine database</a> and <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>, both free.</p>"""

WRITERS_DEPTH["writers/writing-opportunities/ireland"] = """
<h2>How this page is maintained</h2>
<p>Reviewed by the BRYME writers desk at every sweep: pay ranges, eligibility lines and submission routes are re-read from each publication's own guidelines, and every entry carries its last-verified date. Listings that state no response window are marked as such rather than guessed at — the desk's <a href="/writers/guides/when-to-follow-up-on-a-pitch/">follow-up timing guide</a> covers the polite defaults.</p>
<p>To widen the search beyond this page: the <a href="/writers/writing/">full opportunity desk</a> lists every verified market regardless of geography, the <a href="/writers/guides/how-to-find-international-writing-opportunities/">international guide</a> covers currency and eligibility mechanics, and the free reference databases — <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers</a> and <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a> — carry many Irish and UK-adjacent markets with crowd-reported response data. The desk's standing rule applies to every listing here: guidelines on the publication's own site are the truth; everything else, including this page, is a dated snapshot.</p>"""

WRITERS_DEPTH["writers/writing-opportunities/nepal"] = """
<h2>How this page is maintained</h2>
<p>Reviewed by the BRYME writers desk at every sweep, with each listing's pay, eligibility and submission route re-read from the publication's own guidelines and a last-verified date recorded beside it. Where this page lists few markets, that is honesty rather than laziness — the desk records what it can verify, and the <a href="/writers/writing/">full opportunity desk</a> carries every market open to Nepali writers regardless of where the publication is based, which is usually the larger set.</p>
<p>The <a href="/writers/guides/how-to-find-international-writing-opportunities/">international-pitching guide</a> covers what matters most for cross-border applications from here: the eligibility line read on the publication's own site, the currency and transfer mechanics, and the fee rule that has no exceptions — no legitimate publication charges writers to submit. The free databases (<a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers</a>, <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>) widen the search, and the <a href="/writers/tracker/">tracker</a> keeps the pipeline honest once applications go out.</p>"""

# ---------------- writers root singles (11) ----------------

WRITERS_DEPTH["writers/checklists"] = """
<h2>Desk notes: using the checklist library well</h2>
<p>Checklists earn their place by preventing your specific, recurring misses — so the desk recommends building a personal layer on top of these: after any submission or publication that embarrasses you, add one line to your own list. The library's checklists cover the desk's three checkpoints (pre-writing, revision, pre-send) and pair with the sections they protect: the <a href="/writers/learn/editing-proofreading/">editing passes</a> behind the revision tier, the <a href="/writers/guides/how-to-submit-a-freelance-article/">submission mechanics</a> behind the pre-send tier.</p>
<p>The instrument has honest limits worth stating: a checklist is a floor, not a quality system — it catches the known unknowns, which is why the <a href="https://en.wikipedia.org/wiki/Special:Search?search=checklist" rel="noopener">evidence behind checklists in high-stakes fields</a> emphasises short lists, actually used. Ten lines you really run beat fifty you skim, and every line earns its place by surviving a miss.</p>"""

WRITERS_DEPTH["writers/compare"] = """
<h2>Desk notes: choosing a format is choosing a reader</h2>
<p>The comparisons on this page work best read backwards: start from the reader you want and the payment model you need, and let that eliminate formats — a how-to guide and a personal essay share a language but not a contract, and neither pays like the other. The desk keeps format advice adjacent to market reality: the <a href="/writers/guides/where-the-money-is-in-writing/">money map</a> shows what each format tends to pay, and the <a href="/writers/learn/">learn library</a> holds the craft section for whichever format wins.</p>
<p>One calibration across the comparison table: formats differ most in their structure promises. News front-loads, essays delay, guides enumerate, scripts dramatise — and writers who switch formats without updating the promise produce the mismatches this page exists to prevent. For the structural mechanics per form, the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's genre sections</a> are the free standard reference.</p>"""

WRITERS_DEPTH["writers/state-of-paid-writing-2026"] = """
<h2>Desk notes: how to read a year-survey honestly</h2>
<p>This survey aggregates what the desk could verify — rates published in guidelines, recorded with read-dates — and its honest limitation is stated on the page: it is a snapshot of observable listings, not a census of the industry. Pair it with two habits to make it useful: read the methodology note before the numbers, and treat every figure as a floor-finder for the <a href="/writers/guides/how-much-to-charge-for-an-article/">rate research</a> you still have to do per market.</p>
<p>The desk's standing context for any pay survey: rates disperse around genres and rights as much as around skill — the <a href="/writers/guides/how-to-check-a-freelance-writing-contract/">contract guide</a> explains the rights half of that variance — and the realised number that matters is yours, tracked in the <a href="/writers/tracker/">tracker</a>. Industry-wide context lives with the trade bodies and databases the desk cites throughout, including <a href="https://www.pw.org/" rel="noopener">Poets &amp; Writers</a>' tools and reports.</p>"""

WRITERS_DEPTH["writers/start"] = """
<h2>Desk notes: the beginner path, compressed</h2>
<p>Everything on this page exists to shrink the distance between "I want to write" and a finished page, so here is the compressed version of the path: today, one timed session from the <a href="/writers/learn/start-writing/">starting guides</a> — fifteen minutes, no judgement. This week, one piece edited with the <a href="/writers/learn/editing-proofreading/">editing sequence</a>. This month, one submission to a verified market from the <a href="/writers/writing/">opportunity desk</a>, using the <a href="/writers/guides/how-to-submit-a-freelance-article/">mechanics guide</a>. That loop — draft, edit, submit — is the whole engine; everything else on the desk is gear for it.</p>
<p>The external anchor for the craft half is the same one the universities use: the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL</a>, free and encyclopaedic. The desk's own <a href="/writers/learn/">learn library</a> is the guided tour. And the patience note the page implies but deserves saying plainly: the first pieces are allowed to be bad, are expected to be bad, and count fully — every working writer's earliest pages were rites, not monuments.</p>"""

WRITERS_DEPTH["writers/essays"] = """
<h2>Desk notes: reading the essay shelf as a writer</h2>
<p>Everything on this shelf is argument — the desk's positions on writing, money and the industry, stated with evidence and dated like everything else here. Read it twice: once as a reader, for the claims; once as a writer, for the moves. The essays are deliberately worked examples of the form this desk teaches — thesis early, evidence mid, turn late, no summary ending — which makes the shelf the practical companion to the <a href="/writers/learn/examples/">examples section</a> and the <a href="/writers/learn/dos-and-donts/dos-and-donts-of-an-essay/">essay dos and don'ts</a>.</p>
<p>If an essay's argument moves you to disagree, that is the shelf working: the desk's <a href="/writers/contact/">contact door</a> takes counter-arguments seriously, and the corrections policy applies to opinion pages with the same seriousness as to facts. For the essay craft itself beyond this desk, the <a href="https://en.wikipedia.org/wiki/Special:Search?search=essay" rel="noopener">essay reference material on Wikipedia</a> sketches the form's history and variants honestly.</p>"""

WRITERS_DEPTH["writers/tracker"] = """
<h2>Desk notes: what the tracker is for</h2>
<p>The submission tracker is the pipeline ledger the guides keep referencing: it holds what went where, on what date, and what came back — which is the raw material for every timing decision in the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">follow-up guide</a> and every rate decision in the <a href="/writers/guides/how-much-to-charge-for-an-article/">pricing guide</a>. The desk's honest position: the specific tool matters far less than the habit; a spreadsheet kept daily beats an app opened monthly, and this tracker exists because writers asked for one that matches the desk's own workflow.</p>
<p>Two fields most writers skip and should not: the response time when it comes (it builds your private database — compare it against <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder's</a> crowd data), and the realised hourly when payment lands (the <a href="/writers/guides/track-your-writing-income/">income ledger</a> takes over there). Data entered at the moment of the event is the only data that is ever complete.</p>"""

WRITERS_DEPTH["writers/writing-opportunities"] = """
<h2>Desk notes: how to work the atlas</h2>
<p>This page is the atlas view of the desk's verified markets — the <a href="/writers/writing/">main opportunity desk</a> carries the complete list with pay ranges, eligibility lines and last-verified dates, and this atlas slices it by geography for writers who want to start from where they live or can legally pitch. The desk's maintenance rule is stated on both pages: every entry is re-read from the publication's own guidelines at each sweep, and anything the desk cannot verify does not appear.</p>
<p>The working method: eligibility first, always — the <a href="/writers/guides/how-african-writers-can-find-paid-publications/">eligibility guide</a> explains how diaspora and residence rules differ — then pay, then fit. Beyond the atlas, the free reference databases (<a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers</a>, <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>) widen the net, and the <a href="/writers/guides/how-to-find-paid-writing-opportunities/">funnel guide</a> turns all of it into a weekly routine.</p>"""

WRITERS_DEPTH["writers/disclosure"] = """
<h2>Desk notes: why disclosure is a feature, not compliance</h2>
<p>This page exists because a publication that earns from affiliate relationships and advertising owes its readers the mechanism in plain sight — what earns, what does not, and where the boundary sits. The desk's structure is stated honestly: opportunity listings are editorial records, not paid placements; nothing on the desk is written for a fee from a subject; and where commercial links ever appear, they are labelled at the link, not in a footer nobody reads. The house-wide advertising rules (ads never resemble content, buttons or job cards) apply here with full force.</p>
<p>The standard the desk holds itself to is the readers'-trust school of affiliate disclosure — the <a href="https://www.ftc.gov/business-guidance/resources/ftcs-endorsement-guides" rel="noopener">FTC's endorsement-guides summary</a> is the clearest public articulation of the principles (clear, unavoidable, same-surface disclosure), even where the desk's own jurisdictions differ. Questions about any relationship on this desk go through the <a href="/writers/contact/">contact door</a>, and the <a href="/writers/corrections/">corrections policy</a> applies to this page like any other.</p>"""

WRITERS_DEPTH["writers/studio"] = """
<h2>Desk notes: the studio is a workbench, not a course</h2>
<p>The Writing Studio gathers the desk's interactive tools into one workbench — the difference between this and a writing course is stated plainly: a course narrates at you for weeks; a workbench does one thing to your text right now. Every tool on the desk states its job in one line, does it in your browser, and sends nothing anywhere — the privacy posture is the desk's standing one, described on the <a href="/writers/disclosure/">disclosure page</a>.</p>
<p>The intended loop with the rest of the desk: draft in your own editor, run the relevant studio tool for the pass you are on (the <a href="/writers/learn/editing-proofreading/">editing section</a> sequences the passes), then close the tool and make the decision yourself. Tools propose; writers dispose — which is also the desk's answer to the question of whether any tool can replace the <a href="/writers/learn/">learn library</a>: no, and the tools work better in hands that have read it.</p>"""

WRITERS_DEPTH["writers/newsletter"] = """
<h2>Desk notes: what the newsletter is, honestly</h2>
<p>The newsletter is the desk's weekly loop-closer: new verified opportunities, what changed in the guidelines the desk re-reads, and the week's additions to the guides — delivered as a plain, readable email with no sequencing tricks and no bought list. Subscribing is the lowest-effort way to keep the <a href="/writers/writing/">opportunity desk</a> working for you, because markets move and memory does not scale; the desk's verification dates are the system, and the newsletter is its heartbeat.</p>
<p>Two honesty notes the page implies: unsubscribe is one click and honoured immediately — a newsletter you cannot leave is a trap, not a service; and the desk's privacy posture (almost nothing collected, nothing sold) is stated on the <a href="/writers/disclosure/">disclosure page</a> and applies here in full. For the craft of running such a thing yourself, the <a href="/writers/learn/dos-and-donts/dos-and-donts-of-blogging/">blogging dos and don'ts</a> cover the rhythm question — consistency beats intensity — and the desk's own archive is the worked example.</p>"""

WRITERS_DEPTH["writers/tested"] = """
<h2>Desk notes: what "tested" commits us to</h2>
<p>BRYME Tested is the desk's hands-on shelf: tools and services actually used long enough to form an opinion, scored against stated criteria, with the testing date printed. The commitments that make the label mean something: no free gear with strings, no scores previewed to vendors, and a re-test whenever the product changes materially — the same verification discipline the <a href="/writers/writing/">opportunity desk</a> applies to guidelines, applied to objects.</p>
<p>Read the shelf with the desk's standard scepticism tools: the criteria first (stated per review, so you can disagree with the weighting before the verdict), the date second (software rot is real), and the alternative column always — every tested pick names what it displaces. The commercial boundaries are on the <a href="/writers/disclosure/">disclosure page</a>; when a tested item carries an affiliate link, the label travels with the link.</p>"""
