# -*- coding: utf-8 -*-
"""Second-pass depth boosts for writers pages (tranche 5). Consumed by
inject-writers-depth.py after WRITERS_DEPTH; separate idempotency marker."""

WRITERS_DEPTH2 = {

"writers/learn/writing-glossary": """
<h2>Terms this desk uses most, in working sentences</h2>
<p>A few of the words writers meet first in editor emails, used the way working people use them: an <b>evergreen</b> piece is one whose truth does not expire this quarter (this desk dates everything time-sensitive precisely so the evergreen pieces can be trusted). A <b>dek</b> is the one-line promise under a headline — the desk calls it a description and writes it before the piece, as a test. A <b>kill fee</b> is what a publication pays when it cancels an assigned piece; its presence signals a professional operation, its absence a warning. A <b>simultaneous submission</b> is the same pitch at several magazines at once — honest if declared, arson if denied.</p>
<p>The deeper glossary lives on the desk's <a href="/writers/glossary/">full glossary page</a>; the terms above are the ones that unlock the most sentences in the <a href="/writers/guides/">guides shelf</a>. Meet each term three times in the wild — the <a href="/writers/writing/">opportunity desk</a> is full of them in their natural habitat — and the definitions stick on their own, which is the only way vocabulary ever really sticks.</p>""",

"writers/tested": """
<h2>The testing method, spelled out</h2>
<p>Every Tested verdict follows the same protocol, so readers can audit it: the tool or service is used for real work for at least two weeks; the criteria are stated before the verdict, not chosen after; the cost is stated in the currency it charges; the reference standards for the categories come from public sources — <a href="https://www.pw.org/" rel="noopener">Poets &amp; Writers</a> for market context; and the date of the last re-test is printed, because software ages faster than prose. Where the desk has no competence to test a claim (privacy promises, for instance), the review says so instead of repeating marketing.</p>
<p>The shelf's relationship to the rest of the desk is deliberately boring: Tested reviews feed the <a href="/writers/learn/writing-tools/">tools section</a>'s recommendations, and any tool that stops earning its place gets re-tested out publicly. Vendors get the same treatment as publications on the <a href="/writers/writing/">opportunity desk</a> — a dated read, a stated standard, and no preview of the verdict. The commercial boundaries around links are on the <a href="/writers/disclosure/">disclosure page</a>, and they are short on purpose.</p>""",

"writers/learn/writing-checklists": """
<h2>A starter checklist, ready to run</h2>
<p>For writers who want a working instrument before building their own, the desk's three-tier starter: <b>before drafting</b> — who is this for, what is the one thing it must say, what is the promised length (the <a href="/writers/learn/start-writing/">starting guides</a> cover the session itself); <b>before revising</b> — has it rested long enough to be readable as a stranger, is the structure outlined in one sentence per paragraph (the <a href="/writers/learn/structure-formatting/">structure section</a> explains the reverse outline); <b>before sending</b> — guidelines re-read on the publication's own site, links live, names spelled, dates honest, the <a href="/writers/tracker/">tracker</a> updated.</p>
<p>The use rule that makes checklists work is the aviation one: run the list top to bottom, out loud if the stakes are high, and never tick from memory. The <a href="/writers/checklists/">full checklist library</a> has the desk's complete versions per form; this starter is the spine they all share.</p>""",

"writers/newsletter": """
<h2>What arrived this week, and why it matters to your pipeline</h2>
<p>For working freelancers the newsletter's value is arithmetic: markets change guidelines, close, reopen and change pay without announcing it (which is why the desk also points readers at the free public databases, from <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers’ magazine index</a> on), and the desk's sweep catches those movements because checking is the desk's job rather than yours. A single caught change — a market reopening to submissions, a rate rising, an eligibility line widening — pays for a year of emails in saved rejections.</p>
<p>Pair the newsletter with the desk's machinery and the pipeline runs itself: the week's opportunities land by email, the details live on the <a href="/writers/writing/">opportunity desk</a>, your responses live in the <a href="/writers/tracker/">tracker</a>, and the timing rules live in the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">follow-up guide</a>. The newsletter is simply the part of that system that finds you, so the system does not depend on you remembering to check.</p>""",

"writers/learn/writing-tools": """
<h2>Choosing a tool: three questions before any download</h2>
<p>The desk's tool-selection test, applied before anything joins the library: <b>what stage does it serve</b> — capture, drafting or checking (anything claiming to do all three does none well); <b>what does it cost after the honeymoon</b> — free tiers that nag, trials that auto-convert, subscriptions priced monthly to feel small; and <b>where does your text go</b> — a checking tool that uploads your unpublished work to someone's server is a privacy decision, not a writing one, and the desk flags each tool's posture in the library.</p>
<p>The deeper point the shelf keeps making: tools compound a process that exists — the <a href="/writers/learn/writing-process/">process section</a> first, tools second. A capture tool in service of a capture habit is transformative; the same tool without the habit is a subscription. Test-drive with a real week of real work before deciding, and let the <a href="/writers/tested/">Tested shelf</a> save you from the tools that fail week one.</p>""",

"writers/learn/research-sources": """
<h2>The receipt system, in practice</h2>
<p>The desk's working version of source discipline is a single habit with three parts. At capture: save the link, the publication name, the date you read it, and the exact line you are using — a bookmark without a quote is a rumour. While drafting: mark every factual sentence in the draft with its source's shorthand, so verification is a lookup rather than an archaeology. At revision: read the piece against the sources one final time, checking that the claim still says what the source said — the subtlest errors are drift, not invention.</p>
<p>For the formal end of the spectrum — citation systems, source hierarchies, academic attribution — the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's research and citation resources</a> are the free standard, and this desk's <a href="/writers/intelligence/">fact-label system</a> shows one publication's public answer to the same problem. Writers who adopt the receipt habit rarely need the formal systems until academia or corrections force the issue; writers who skip it meet those force-majeures sooner.</p>""",

"writers/learn/writing-templates": """
<h2>Three templates worth starting with</h2>
<p>Newcomers to the library ask where to begin, so the desk's honest three: the <b>pitch template</b> (the two-hundred-word structure from the <a href="/writers/guides/how-to-write-a-pitch/">pitch guide</a>, pre-formatted — the highest-value hundred words in a freelance career), the <b>submission cover note</b> (three sentences: what, why-here, practicals — the <a href="/writers/guides/how-to-submit-a-freelance-article/">submission mechanics</a> in letter form), and the <b>follow-up note</b> (the wording from the <a href="/writers/guides/how-to-follow-up-on-a-writing-pitch/">follow-up guide</a>, ready at the right date). Everything else in the library is situational; these three run weekly.</p>
<p>The customisation rule for all three: change the voice before the fields. A template that survives is one where your sentences replaced the sample ones — if the email still sounds like the template, the editor can tell, and so can you.</p>""",

"writers/studio": """
<h2>The workbench loop, end to end</h2>
<p>The studio works best inside the desk's standard loop: draft in your own environment, then bring the piece through the relevant tool for the pass you are on — structure first (the <a href="/writers/learn/structure-formatting/">structure guides</a> explain what to look for), sentences second, surface last. Each tool states which pass it serves, because the desk's standing argument is that out-of-order tooling wastes the writer's time: a grammar pass on a draft whose structure will change is polishing furniture in a house being rebuilt.</p>
<p>Two promises the studio makes explicitly, since tools have earned scepticism: nothing you paste or type leaves your browser — the tools run client-side, and the <a href="/writers/disclosure/">disclosure page</a> states the data posture in full; and no tool here writes for you, by policy — the conventions the checking tools enforce come from public standards like the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL</a>, never private whim — the desk's tools check, count, reveal and format, and the writing stays yours. When a tool's suggestion conflicts with your intent, the <a href="/writers/learn/grammar-language/">grammar section</a> usually explains which of them is confused.</p>""",

"writers/writing-opportunities/nepal": """
<h2>Pitching from Nepal: the mechanics that matter most</h2>
<p>Three practical notes for writers applying from Nepal, from the desk's international-verification records. Time zones work in your favour for news-adjacent pitching: Kathmandu sits ahead of both Europe and the Americas, so a pitch sent in the Nepali evening lands in a European morning inbox and an American inbox overnight — the desk's <a href="/writers/guides/how-to-submit-a-freelance-article/">submission guide</a> covers the send-timing details. Payment rails deserve a test: before accepting any first assignment, confirm the publication can actually pay to your bank or a service you can receive from — and log the realised amount and fees in the <a href="/writers/tracker/">tracker</a> so your rate comparisons stay honest.</p>
<p>And the portfolio route that builds fastest from anywhere: local expertise is internationally valuable. A writer in Nepal who can report a story no London desk can reach is not competing with the world's generalists — the <a href="/writers/guides/how-to-write-a-pitch/">pitch guide</a> shows how to frame that access as the pitch's spine.</p>""",

"writers/learn/structure-formatting": """
<h2>The reverse outline, demonstrated</h2>
<p>Because this section's most-recommended technique deserves a demonstration: take your messy draft and write one sentence per paragraph — what that paragraph actually says, not what it was supposed to say. Read just those sentences, in order. In a healthy piece, they form an argument you can hear. In a struggling piece, you will find the paragraph that repeats paragraph two, the paragraph that argues with the thesis, and the gap where the piece skips a step the reader needed. The fix is now plumbing, not poetry: move, cut, or write the missing paragraph.</p>
<p>The technique comes from the editing tradition this desk writes from, and the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's outlining resources</a> carry the forward-outline version for writers who prefer planning to surgery. Formatting's half of this section — headings that mean something, lists that carry parallel items, paragraphs sized to their medium — is the same kindness at smaller scale, and the <a href="/writers/learn/online-writing/">online-writing guides</a> take it to the screen.</p>""",

"writers/learn/journaling-personal": """
<h2>Starting a journal that lasts past January</h2>
<p>The desk's practical starter, assembled from what the guides here teach: pick a trigger you already do daily (first coffee, last light), attach three sentences to it, and write them before touching a screen — the inbox will manufacture urgency; the page manufactures perspective. Keep the entries undecorated: the journal is the one place on this desk where "it was raining and I was tired" is a complete entry. The floor matters more than the ceiling — a two-sentence day continues the streak, and the streak is the therapy and the craft practice alike.</p>
<p>For the evidence-informed framing of expressive writing's benefits, the summary at <a href="https://en.wikipedia.org/wiki/Special:Search?search=expressive+writing" rel="noopener">Wikipedia's expressive-writing entry</a> is a fair start, with this desk's standing boundary: a notebook supports care, it does not replace care. When the pages want somewhere to go, the <a href="/writers/learn/creative-writing/">creative section</a> shows how journal material becomes scenes — the transition from private pages to publishable prose is one of the quietest career-starters there is.</p>""",

"writers/learn/start-writing": """
<h2>The fifteen-minute session, scripted</h2>
<p>Because "just start" is bad advice without a script, here is the desk's: set a timer for fifteen minutes. Write the header — the working title, even a bad one. Write the sentence that states what this piece says (a lie is acceptable; revision exists). Then write the boring true version of the first paragraph, in plain words, as if telling one friend. When the timer ends, stop mid-flow if possible — the known next sentence is the cheapest bridge back tomorrow. That is the whole session: no research, no formatting, no judging. The <a href="/writers/learn/writing-process/">process section</a> schedules these sessions into a week; the <a href="/writers/learn/editing-proofreading/">editing section</a> owns everything the judge-brain wants to do now.</p>
<p>The external scaffold if you want one: the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's pre-writing and drafting pages</a> carry the formal versions of freewriting and outlining. But the desk's experience says the script above clears the bar most people actually trip on — starting — and the craft catches up with the pages.</p>""",

"writers/guides/how-to-write-a-strong-query-letter": """
<h2>A worked skeleton, line by line</h2>
<p>To make the structure above concrete, here is the skeleton with its job annotated. Line one — the hook: the story in one sentence a stranger could repeat ("A phone swap strands two strangers in each other's lives" energy, applied to your subject). Line two — the turn: what the piece argues or reveals that the coverage so far has not. Line three — the fit: why this outlet, in one clause that proves you read it (the <a href="/writers/writing/">opportunity desk</a> records what each market actually runs, dated). Line four — the you: one line of access, evidence or credits, no adjectives. Line five — the practicals: length, timing, exclusivity status. Close. Under two hundred words total; the letter's discipline is the article's discipline in miniature.</p>
<p>Calibrate against the market's own guidelines — some publications still ask for the fuller traditional letter, and the desk records those requests verbatim. For the form's formal anatomy, the <a href="https://en.wikipedia.org/wiki/Special:Search?search=query+letter" rel="noopener">query-letter reference material on Wikipedia</a> and the Purdue OWL's professional-writing pages (from the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">OWL index</a>) carry worked examples both modern and classical.</p>""",

"writers/learn/common-problems": """
<h2>The diagnosis table, expanded</h2>
<p>Because patterns deserve names you can search for, here is the section's expanded diagnostic: <b>the piece has no ending</b> — usually a missing thesis back at the top (the ending is the thesis, kept); <b>every sentence is the same length</b> — read the piece aloud and break the metronome at the load-bearing moments; <b>the research is showing</b> — you wrote the process, not the finding; move the journey to a footnote and the conclusion to paragraph one; <b>you have rewritten paragraph one nine times</b> — that is not editing, that is avoidance with a red pen; write paragraph two badly and keep moving. Each diagnosis links to a repair: the <a href="/writers/learn/editing-proofreading/">editing section</a> for the passes, the <a href="/writers/learn/start-writing/">starting guides</a> for the avoidance, and the Purdue OWL's <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">revision resources</a> for the formal versions of all of them.</p>
<p>The meta-rule the section keeps proving: problems that survive three passes are structure problems wearing sentence costumes. Go up one level of outline and look again.</p>""",

"writers/guides/how-long-should-you-wait-for-an-editor": """
<h2>The waiting ledger, worked example</h2>
<p>To make the arithmetic concrete, one honest worked example: 3 March, you send a reported piece to a market whose guidelines (re-read by the desk on the <a href="/writers/writing/">opportunity page</a>) state "responses within six weeks." The tracker logs the date; nothing happens for a month, which is inside the window and therefore not news. 14 April — six weeks plus one polite week — the follow-up goes out, three sentences per the <a href="/writers/guides/how-to-follow-up-on-a-writing-pitch/">wording guide</a>. A week later, silence. 12 May, the withdrawal note: "assuming this isn't a fit; sending elsewhere." The idea moves to the next market on the list, having cost you one calendar quarter and zero dignity.</p>
<p>Contrast the unstated-window case: <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a> shows a ninety-day median for that market — you wait ninety days before the first follow-up, because the data says that is what "normal" means there. The entire discipline is matching patience to evidence instead of to anxiety; the <a href="/writers/tracker/">tracker</a> is what makes the evidence available at the moment of decision.</p>""",

"writers/guides/how-to-find-international-writing-opportunities": """
<h2>The eligibility line, read carefully</h2>
<p>Because eligibility is where international pitching is won or lost, here is the desk's close-reading guide for the sentence that decides everything. "Open to writers worldwide" — the strongest line, rare, screenshot it. "Open to international writers" — check for the follow-on sentence; some markets mean "anywhere except [regions our payments cannot reach]." "Open to African writers" — usually continental residency or nationality; diaspora clauses vary by market, and the <a href="/writers/guides/how-african-writers-can-find-paid-publications/">dedicated guide</a> covers the variants. "Open to writers based in X" — residency, not nationality; the visa-state question matters and the desk records which is meant when guidelines say.</p>
<p>The verification habit stays the same even on the desk's own listings: the guideline page is the truth, the desk's entry is a dated snapshot of it, and the <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers database</a> is a third opinion when two sources disagree. Three minutes of eligibility reading saves the only irrecoverable cost in this business — a first impression with an editor who won't remember you kindly.</p>""",

"writers/guides/how-to-build-writing-samples": """
<h2>A sample shelf from zero, in one month</h2>
<p>For writers with an empty portfolio, the desk's month-one plan: week one, write one piece you would actually want published — a reported post, an essay with a spine, something in the genre you intend to pitch (the <a href="/writers/learn/start-writing/">starting guides</a> get it drafted). Week two, edit it with the full <a href="/writers/learn/editing-proofreading/">editing sequence</a> and put it where editors can reach it: a clean blog, a platform page, a personal site — owned beats rented. Week three, write the second piece in a second register to show range. Week four, submit both somewhere small and real; a credit beats a portfolio link, and a portfolio link beats a promise.</p>
<p>The external grounding for making self-published work look professional rather than desperate: the Purdue OWL's <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">audience, purpose and genre material</a> — the difference shows in the first paragraph. And the desk's <a href="/writers/guides/how-to-get-your-first-paid-writing-gig/">first-gig guide</a> is where the shelf goes job-hunting.</p>""",

"writers/guides/how-to-find-remote-writing-work": """
<h2>The scam filter, made explicit</h2>
<p>Because remote-first hunting happens in the scammiest corner of the market, here is the desk's explicit filter, applied before any application: no legitimate client charges you anything to work for them — training kits, "starter accounts," software licences you must buy: all disqualifying. No real job exists only in a messaging app with no named company; a company you cannot find outside the chat does not exist. Payment terms stated after the work starts are not terms; walk. And the interview that hires you in twenty minutes for "high-pay, no experience" is selecting for desperation, not skill.</p>
<p>The positive verification: a named entity with a history you can trace, a contract whose terms survive the <a href="/writers/guides/how-to-check-a-freelance-writing-contract/">contract guide</a>'s reading, and — the strongest signal — writers you can find who have been paid. The <a href="/writers/writing/">opportunity desk</a> applies this filter to every listing it records, dated, which is the quiet reason to start there rather than in the open market.</p>""",

"writers/guides/how-to-find-paid-writing-opportunities": """
<h2>The weekly routine, scheduled</h2>
<p>The funnel becomes a career when it becomes a calendar, so here is the desk's honest weekly routine. Monday (30 minutes): sweep the <a href="/writers/writing/">opportunity desk</a>'s new and updated listings; shortlist five. Tuesday (60 minutes): read each shortlisted market's recent pieces; match or discard. Wednesday (90 minutes): draft pitches for the two best fits — the <a href="/writers/guides/how-to-write-a-pitch/">pitch guide</a> owns this hour. Thursday (30 minutes): send, and log every send in the <a href="/writers/tracker/">tracker</a>. Friday (15 minutes): follow-ups due today, per the timing rules; update the ledger.</p>
<p>That is under four hours a week for a pipeline that never empties: ten pitches a week at two-in-ten conversion is two assignments — the maths that makes freelance income boring instead of miraculous. The reference databases (<a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers</a>, <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>) slot into Monday when the desk's listings run thin.</p>""",

"writers/writing-opportunities": """
<h2>Reading eligibility like an editor</h2>
<p>Since this atlas exists because geography is the first filter, here is the desk's close-reading habit for the eligibility lines across it. Nationality, residency and diaspora are three different keys — a market open to "writers from X" usually means nationality, "based in X" means residency, and diaspora clauses name their ancestry lines explicitly or not at all. When the guideline is ambiguous, the desk's listing says so, and the reliable answer comes from one place: a two-line email to the publication's submissions address, asking exactly the question the guideline dodged. Editors answer these; they prefer the question to the ineligible submission.</p>
<p>The atlas pairs with the <a href="/writers/writing/">main desk</a> (the full list), the <a href="/writers/guides/how-to-find-international-writing-opportunities/">international mechanics guide</a> (currency, transfers, verification), and the free databases for markets between sweeps: <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers</a> and <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>. Everything here carries a verification date because every listing everywhere is a snapshot; the guideline page is the country, and this page is the map.</p>""",


"writers/disclosure": """
<h2>The relationships this desk has, named one by one</h2>
<p>Completeness matters more than brevity in disclosure, so the full inventory: this desk earns through on-site advertising (house rules: ads never disguised as content, buttons, or job listings) and through affiliate links where a tool or service is genuinely recommended — each such link labelled where it appears, never after the fact. No listing on the <a href="/writers/writing/">opportunity desk</a> is paid placement: publications cannot buy inclusion, better pay figures, or kinder eligibility lines. No Tested review is previewed to its vendor. Editorial and commercial live in separate rooms, and the wall between them is stated rather than implied.</p>
<p>The reader's remedies: if you find a link you believe is unlabelled, or a listing you suspect was influenced, the <a href="/writers/contact/">contact door</a> treats that report as a correction-class matter, and the <a href="/writers/corrections/">corrections policy</a> governs the response. The public principles this desk aligns with are articulated in the <a href="https://www.ftc.gov/business-guidance/resources/ftcs-endorsement-guides" rel="noopener">FTC's endorsement guides</a> — worth every writer's time, since most of us disclose somewhere eventually.</p>""",

"writers/guides/how-to-follow-up-on-a-writing-pitch": """
<h2>The three follow-up sentences, filled in</h2>
<p>Because the wording is where everyone stalls, here is the desk's fill-in-the-blanks version: subject — "Follow-up: [original subject, unchanged]". Line one — "Following up on my pitch of [date] about [one-line description]." Line two — the ask, plainly: "Is this something you'd like to see?" or "Do you have a sense of timing on your end?" Line three — the graceful exit: "If it's not a fit, no reply needed — I'll take it elsewhere after [date two weeks out]." Send weekday morning in their time zone. That is the whole email; every additional sentence costs more than it buys.</p>
<p>The date in line three is doing real work — it converts your follow-up into a scheduling fact the editor can act on with one glance, and it hands you the moral right to move the piece without a withdrawal drama. The machinery around this note — when it goes, what the market's window was — lives in the <a href="/writers/tracker/">tracker</a> and the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">timing guide</a>.</p>""",

"writers/guides/how-to-pitch-an-essay": """
<h2>The essay pitch, worked example</h2>
<p>To show the voice-at-work principle, here is a skeleton filled with an imaginary-but-typical pitch: "For three years I kept my grandmother's shop accounts — and watched a cash economy go digital one customer at a time" (the access: lived, specific, unreplicable by a staff writer). "This essay argues the mobile-money story everyone tells as triumph has a quiet casualty no one covers: the record-keeping knowledge that died with the ledgers" (the turn: a real argument, not a topic). "1,800 words, reported-from-memory with documents; drafts in three weeks" (the practicals). "My reporting on market traders ran in [outlet]" (the credit, or the honest absence of one). That is the entire pitch — the essay exists in seed form, and the editor can already hear its voice.</p>
<p>The calibration point: the seed must grow into the essay you can actually write. Overclaiming access in the pitch produces the worst kind of assignment — the one you cannot deliver. The <a href="/writers/writing/">opportunity desk</a> records essay-friendly markets with dated guidelines; the <a href="/writers/guides/how-to-write-a-pitch/">general pitch guide</a> covers the reported-piece variant where the physics differ.</p>""",

"writers/learn/writing-basics": """
<h2>The one-paragraph workout</h2>
<p>For turning this section from reading into reflex, the desk's daily drill: take yesterday's paragraph (any paragraph), and rewrite it three ways — plainer (replace every abstraction with the thing itself), shorter (half the words, same meaning), and concrete (every generality traded for a specific). Ten minutes, throwaway draft, no stakes. Writers who run this drill for a month report the same thing: the corrections start happening in the first draft, silently, because the ear has been retrained.</p>
<p>The drill works because it isolates the layer most writers never deliberately practise — the sentence — while the guides here and the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's grammar and style pages</a> supply the theory underneath each move. When a drill rewrite consistently sounds better than the original, that is not taste; that is the basics, working. The <a href="/writers/learn/editing-proofreading/">editing section</a> is where the drill's lessons meet real drafts.</p>""",

"writers/guides/how-african-writers-can-find-paid-publications": """
<h2>The diaspora clauses, close up</h2>
<p>Because eligibility lines carry the most weight on this page, the desk's field guide to the variants you will actually meet: "African writers" unqualified — most markets mean citizen or resident of an African country; check which. "African diaspora" — ancestry-based, usually self-declared, occasionally documentation-requested; read the definition, because markets define generations differently. "Africa-based" — residency at submission time, which catches students and recent relocators from both directions. "Pan-African" — the widest of the family, but never safe to assume; the good markets define it, the careless ones leave you guessing, and the guessing is what email is for.</p>
<p>The desk records which variant each market uses, dated, precisely because these lines move. And the standing rule from the guide above gets its restatement here: where a guideline is ambiguous, a one-line question to the submissions address is professional everywhere — it is the ineligible submission that costs you the relationship. The <a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers database</a> and <a href="https://jaladaafrica.org/" rel="noopener">Jalada Africa</a> are the reference layer for widening the search.</p>""",

"writers/guides/how-to-submit-a-freelance-article": """
<h2>The pre-send pass, as a list</h2>
<p>The guide above describes the mechanics; here they are as the literal sixty-second pass the desk runs before anything goes out: guidelines read on the publication's own page this week (not from memory, not from a repost — the <a href="/writers/writing/">opportunity desk</a> links them with read-dates); the requested format honoured (body vs attachment, doc type, length); the subject line per guidelines or "PITCH: [title]"; the bio line present and one sentence; samples linked, not attached, unless invited; the timeline honest ("available from [date]"); and the tracker updated the moment the send happens, so the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">follow-up clock</a> starts from fact.</p>
<p>The style layer on top of the mechanics: the email itself is a writing sample — the pitch that demonstrates the requested register in five clean sentences is the strongest cover letter possible, and the Purdue OWL's <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">professional-correspondence sections</a> are the reference for the conventions if they are new to you.</p>""",

"writers/writing-opportunities/germany": """
<h2>Pitching into the German market: the notes that matter</h2>
<p>From the desk's verification records, three practical notes for this page's listings. Language lines vary more here than in most markets: some listings welcome English-language pitches explicitly, others mean German-language only even when the guideline is in English — the desk records which is which, and when the line is ambiguous, the one-line email to the publication settles it professionally (the <a href="/writers/guides/how-to-submit-a-freelance-article/">submission guide</a> covers the ask). Payment mechanics: most German publications pay by SEPA transfer, which is trivial inside Europe and worth a direct question from elsewhere — confirm the rail before the first assignment, then log the realised figure and fees in the <a href="/writers/tracker/">tracker</a>.</p>
<p>And the competitive note that works in your favour: German publications increasingly run English editions and international desks, which makes English-language specialist knowledge — including African and diaspora perspectives — a genuine differentiator rather than a hurdle. The <a href="/writers/guides/how-to-write-a-pitch/">pitch guide</a> shows how to lead with that access.</p>""",

"writers/guides/track-your-writing-income": """
<h2>The ledger, column by column</h2>
<p>For writers starting from an empty sheet, the desk's minimum viable ledger — one row per payment, six columns: date received; source (publication or client); project (one identifiable title); gross amount and currency; fees and conversion costs (the column that makes international income honest); net. Two derived columns once the habit holds: hours actually worked, and the realised hourly (net divided by hours) that reorders your business every quarter it is reviewed.</p>
<p>The ledger feeds three other desk systems automatically: the tax set-aside (the <a href="/writers/guides/the-tax-set-aside-habit/">habit guide</a> percentages off net), the rate-research feedback (the <a href="/writers/guides/how-much-to-charge-for-an-article/">pricing guide</a> uses your realised hourlies as the floor), and the annual survey context (<a href="https://www.pw.org/" rel="noopener">Poets &amp; Writers</a>' rate discussions) against which your numbers either match or teach you something. The desk's boundary, restated from the <a href="/writers/disclosure/">disclosure page</a>: this is general information and a working habit, not financial or tax advice for your jurisdiction.</p>""",

"writers/guides/how-to-get-your-first-paid-writing-gig": """
<h2>The first-ten plan, week by week</h2>
<p>Compressing the funnel into a calendar, the desk's first-ten plan: weeks one and two — build the sample shelf (two pieces, per the <a href="/writers/guides/how-to-build-writing-samples/">samples guide</a>) and set up the <a href="/writers/tracker/">tracker</a>. Weeks three to six — five pitches a week, drawn only from the <a href="/writers/writing/">opportunity desk</a>'s new-writer-friendly listings, each pitch per the <a href="/writers/guides/how-to-write-a-pitch/">guide</a>. Weeks seven and eight — follow-ups on schedule, then the second wave to the next five markets. The arithmetic of the plan: forty pitches at beginner conversion rates (one in ten is respectable) yields the first clips inside two months — with timing variance that is market luck, not personal verdict.</p>
<p>The mindset note that keeps the plan running: track sends, not wins, during this phase — the sends are the controllable variable, and the <a href="/writers/guides/where-the-money-is-in-writing/">money map</a> shows where the survivors of this funnel usually land first.</p>""",

"writers/tracker": """
<h2>The weekly tracker ritual, five minutes</h2>
<p>The tracker pays when it becomes a Friday habit, so here is the five-minute version: scan the week — anything sent (log date, market, piece), anything answered (log response and its character: accept, decline-with-note, silence), anything due for follow-up per the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">timing rules</a> (queue the note for Monday morning), anything paid (log the net into the <a href="/writers/guides/track-your-writing-income/">income ledger</a>). Close the laptop. The entire discipline is that nothing is remembered — everything is dated at the moment it happens, because reconstructive memory is where freelance pipelines go to die.</p>
<p>After a quarter, the tracker's aggregate view starts coaching you: your real response-time curve per market type, your conversion by pitch kind, the markets that answer fast but pay small versus the reverse. That is the data the crowd databases approximate — <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a> — except this version is about your work specifically, which is the only kind that can set your strategy.</p>""",

"writers/guides/how-much-to-charge-for-an-article": """
<h2>The quote, assembled live</h2>
<p>Because pricing pages end with "know your worth" and begin nowhere, here is the assembly order for an actual quote. Start at the market's stated range (the <a href="/writers/writing/">opportunity desk</a> records it, dated) — that is the anchor, whatever your feelings. Adjust for scope: interviews and original reporting multiply the base; pure rewrites divide it. Adjust for rights: full exclusivity and perpetual licensing are different products with different prices, and the <a href="/writers/guides/how-to-check-a-freelance-writing-contract/">contract guide</a> defines the terms. Adjust for the client's friction — the slow payer and the nine-round reviser are paying an invisible surcharge, priced in advance or suffered after.</p>
<p>Then check the quote against your ledger: the <a href="/writers/guides/track-your-writing-income/">realised hourly</a> from the last quarter is the number the quote must clear, with margin. If clearing it would lose you the job, that is information about the market, not about you — and the desk's <a href="/writers/state-of-paid-writing-2026/">year survey</a> exists precisely so that information arrives before the negotiation, not after.</p>""",

"writers/learn/online-writing": """
<h2>The phone pass, mandatory</h2>
<p>The single habit this section would make universal: before publishing anything online, read it on a phone, thumb-scrolling, in a feed context — the way it will actually be met. The pass catches what the desktop draft hides: the paragraph that renders as a wall, the subhead that promises nothing, the link that dies a thumb's-width from its neighbour, the opening that takes four screens to arrive. Writers who adopt the phone pass report the same discovery — their "flowery prose" problem was a layout problem all along.</p>
<p>Its companion habit is structural: front-load every unit (the piece, the section, the paragraph, the sentence), because the feed reader is always one flick from gone. The <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's purpose-and-audience material</a> explains why this works; the desk's <a href="/writers/learn/structure-formatting/">structure section</a> turns it into checks; and the honesty layer — never bait a title the piece cannot cash — is what separates writing that compounds from writing that churns.</p>""",

"writers/learn/creative-writing": """
<h2>The scene workout</h2>
<p>Because "practise craft" needs a unit, the desk's scene drill: write one complete scene — a character who wants something specific, an obstacle with power, a turn the reader did not schedule — in under four hundred words. Then the dissection pass: mark the line where the want becomes clear, the line where the obstacle bites, the line where the turn lands. If any of the three is missing, the scene was a vignette, and vignettes are decoration; scenes are story. Ten scenes of this, written across a month, teach more structure than a year of outlines.</p>
<p>The reading half of the drill pairs with it: one published scene per week, dissected with the same three marks — the public-domain shelves at <a href="https://www.gutenberg.org/" rel="noopener">Project Gutenberg</a> make century-of-fiction material free, and the <a href="/writers/learn/examples/">examples section</a> carries desk-annotated models. When the scenes start holding together, the <a href="/writers/learn/editing-proofreading/">editing section</a> is where they learn to behave in manuscripts.</p>""",

"writers/learn/editing-proofreading": """
<h2>The three passes, scheduled properly</h2>
<p>The section's core advice deserves its calendar version: the revise pass (structure, argument, what the piece says) runs after a rest — a night minimum, a week for anything that matters — because structural reading requires strangeness. The edit pass (paragraphs and sentences, what each part does) runs next, on paper or in a changed font so the eye cannot autopilot. The proof pass (surface: spelling, punctuation, names, numbers, links) runs last, aloud, because the ear catches what a reading brain politely corrects. Three passes, three different minds, in that order — and never two at once, which is how pieces get polished commas on broken spines.</p>
<p>The reference layer: the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's revision and proofreading pages</a> carry the formal checklists per pass, and the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian style guide</a> settles the consistency calls (numbers, titles, abbreviations) that proofing exists to catch. The desk's <a href="/writers/checklists/">checklist library</a> packages all three passes for the pre-send hour.</p>""",

"writers/guides/how-to-price-ghostwriting-jobs": """
<h2>The ghostwriting quote, line by line</h2>
<p>The assembled quote for a book-length project, in the order it should appear: scope (manuscript length in words, plus what counts as delivered — outline, drafts, final files); process (interview hours included, research included or billed separately); rounds (two revision rounds included, further rounds at a named rate — the clause that saves the engagement); credit (named, anonymous, or acknowledgment — each a different price, per the <a href="/writers/guides/how-to-check-a-freelance-writing-contract/">contract guide</a>); schedule (milestone dates with the client's reading windows stated, because the client's silence is the schedule's real enemy); and payment (deposit up front — a third is common — milestones through delivery, nothing "on publication," which is where ghost fees go to die).</p>
<p>Price the assembled quote against your ledger's realised hourly plus the invisible work, then trust it: the ghostwriting market's enormous spread exists because most buyers cannot price it either, and the professional who explains the line items wins the comparison against the mystery quote every time. The <a href="https://en.wikipedia.org/wiki/Special:Search?search=ghostwriting" rel="noopener">ghostwriting reference material on Wikipedia</a> frames the market's range honestly.</p>""",

"writers/guides/the-tax-set-aside-habit": """
<h2>The set-aside, jurisdiction-agnostic plumbing</h2>
<p>The habit survives every jurisdiction because it never names a rate: payments land, a fixed percentage moves the same day, the account is separate, and the percentage is trued up once a year against the actual bill. What varies by country is the true-up source — the official revenue authority publishes your rates and dates (the <a href="https://www.irs.gov/" rel="noopener">IRS</a>, for one example, carries the self-employed pages every other source paraphrases) (Nigeria's FIRS, the US IRS, HMRC in the UK — find your own, from the source, not from forums), and a one-hour accountant consult each year keeps the percentage honest. The desk's boundary stands: general information, not tax advice.</p>
<p>The freelancer-specific trap the plumbing prevents: the annual surprise that was actually twelve monthly warnings. Writers on the <a href="/writers/guides/track-your-writing-income/">ledger habit</a> watch the set-aside balance grow in plain sight, which converts the year's scariest envelope into arithmetic — and the writers who add a small margin above the percentage (for the year the income doubled) report the calm is worth more than the margin.</p>""",

"writers/guides/when-to-follow-up-on-a-pitch": """
<h2>The edge cases, ruled on</h2>
<p>Four situations the table above does not cover, ruled on as the desk handles them. The news cycle moved: if your pitch was timely and the moment passed while waiting, follow up early — "if this is still of interest, I can update it through [new development]" — timeliness suspends the normal window. You have news: a byline credit that strengthens the pitch justifies one early line ("since pitching, this ran in [outlet]" — that is new information, not nagging). The editor replied personally but slowly: a personal reply resets the clock generously; match their pace, not the table's. The market said "don't follow up, we answer everything": believe them, exactly once past their stated ceiling — then withdraw by note, not by sulking.</p>
<p>All four rulings assume the base machinery: the <a href="/writers/tracker/">tracker</a> holds the dates, the <a href="/writers/writing/">opportunity desk</a> holds the stated windows, and the <a href="/writers/guides/how-to-follow-up-on-a-writing-pitch/">wording guide</a> holds the sentences. Edge cases without records are just feelings.</p>""",

"writers/guides/how-to-write-a-pitch": """
<h2>The two-sentence test, applied</h2>
<p>The pitch's first paragraph passes or fails on one skill — compressibility — so here is the desk's drill for it: write your story idea as a message to one friend who knows nothing about the beat ("it's about the Lagos mechanics who retrain as EV technicians while their old skills expire"). If the friend would reply with a question, the pitch has a spine; if they would reply "ok," the idea is not yet an idea. Then trim the message to under twenty-five words and put it — that sentence — at the top of the pitch. Everything after it earns its place by serving the sentence.</p>
<p>The rest of the assembly is calibration: the <a href="/writers/writing/">opportunity desk</a> tells you what each market actually publishes (read two pieces minimum), the <a href="/writers/guides/how-to-pitch-an-essay/">essay guide</a> handles the voice-led variant, and the <a href="/writers/tracker/">tracker</a> records the send so the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">follow-up</a> has a birthday.</p>""",

"writers/writing-opportunities/ireland": """
<h2>The Ireland-and-UK-adjacent cluster, read correctly</h2>
<p>A practical note on this page's cluster: several Irish publications share submission ecosystems with UK markets — same festivals circuit, overlapping editorial networks, and eligibility lines that sometimes say "Ireland and UK" as one unit and sometimes split them (post-Brexit payment and rights logistics being the usual reason). The desk records each line as written, dated; when a listing says "Ireland and UK," writers based in either qualify, and when it says "island of Ireland," it means exactly that — the close reading habit from the <a href="/writers/guides/how-to-find-international-writing-opportunities/">international guide</a> applies in full.</p>
<p>Payment mechanics within the cluster are straightforward by European standards, but the currency question is real: some Irish markets pay in euros, UK-adjacent ones in sterling, and the realised-rate habit from the <a href="/writers/tracker/">tracker</a> keeps the comparison honest. The wider net lives on the <a href="/writers/writing/">main desk</a> and the free databases (<a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers</a>, <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>).</p>""",

"writers/learn/writing-process": """
<h2>The four stages, scheduled into a real week</h2>
<p>The process section's stages become a career when they get calendar slots, so here is the desk's honest scheduling for a working writer with more obligations than hours: <b>capture</b> runs continuously — one inbox for ideas, reviewed Friday (five minutes); <b>draft</b> gets the morning's first hour or nothing, three days a week, timer-ruled per the <a href="/writers/learn/start-writing/">starting script</a>; <b>revise</b> gets its own afternoon on pieces that have rested overnight — never the same session as drafting, per the section's core rule; <b>ship</b> gets Friday — submissions, invoices, the <a href="/writers/tracker/">tracker</a> sweep, the follow-ups from the <a href="/writers/guides/when-to-follow-up-on-a-pitch/">timing table</a>.</p>
<p>The schedule's quiet insight: shipping day is what makes the other three stages a career rather than a hobby, and it is the stage writers skip when the others run long. Guard it. The <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL's writing-process pages</a> carry the formal stage descriptions; the calendar above is what one desk actually runs.</p>""",

"writers/learn/dos-and-donts": """
<h2>When two rules disagree</h2>
<p>The shelf's lists occasionally conflict — "be concise" against "give it room to breathe," "cut the adverbs" against "the right adverb earns its place" — and the conflict is the lesson: every rule carries an implicit context, and the context is where judgement lives. The desk's resolution order: the reader's experience first (does the sentence serve the person reading it), the form's contract second (a grant application and a newsletter keep different promises), the rule third. Rules are compression of other people's contexts; the writer who can name the context can break the rule on purpose, which is the only interesting way to break it.</p>
<p>That is also why the shelf is per-form — the <a href="/writers/learn/dos-and-donts/dos-and-donts-of-writing/">general list</a>, essay, cover letter, email and blogging lists — and why the external standards (the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian style guide</a>, the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL</a>) state their scope on every page. A rule that claims to apply everywhere usually applies nowhere in particular.</p>""",

"writers/guides/how-writing-retainers-work": """
<h2>The retainer renewal, handled professionally</h2>
<p>Retainers die of awkwardness more often than of disagreement — nobody raises the rate, nobody raises the scope creep, everybody resents quietly until someone leaves. The desk's renewal protocol prevents the fade: ninety days out, the client gets a one-page review — what the retainer delivered (pieces, dates, outcomes you can name), what the next quarter proposes (same scope at the same rate, or the rate adjustment the year's realised hourlies justify, per the <a href="/writers/guides/track-your-writing-income/">ledger</a>), and any scope corrections stated as logistics, not grievances. Renewal becomes an appointment instead of a confrontation — and the number you propose arrives with a citation, from the same public references the desk records (<a href="https://www.pw.org/" rel="noopener">Poets &amp; Writers</a> among them).</p>
<p>The price conversation inside renewals follows the <a href="/writers/guides/how-much-to-charge-for-an-article/">pricing guide</a>'s anchor rules: your realised hourly is the floor, the market's recorded ranges are the anchor, and the discount conversation is where the <a href="/writers/disclosure/">disclosure page</a>'s transparency ethos applies internally too — you can see the deal, so can they, and deals that survive are the ones where both can.</p>""",

"writers/learn/grammar-language": """
<h2>The usage battles, resolved for working writers</h2>
<p>Because this section's inbox questions cluster on the same fights, the desk's working resolutions: the serial comma — house consistency beats ideology; pick one and enforce it everywhere (the <a href="/writers/learn/editing-proofreading/">proofing pass</a> exists for exactly this). Sentence-initial "however" — fine; the comma after it is not optional. "Data is/are" — count what you mean: singular as a mass ("the data is consistent"), plural when you can count the points. Singular "they" — settled, standard, and defended by every major style guide now in public circulation. "Less/fewer" — countable nouns take "fewer"; the supermarket express lane lost this war and so, gracefully, can you.</p>
<p>The meta-habit these resolutions serve: style calls are made once, written down, and applied mechanically — which is what public style guides like the <a href="https://www.theguardian.com/guardian-observer-style-guide-a" rel="noopener">Guardian's</a> are, and what the <a href="https://owl.purdue.edu/owl/purdue_owl.html" rel="noopener">Purdue OWL</a> teaches the mechanics underneath. A writer with a personal style sheet stops re-litigating old battles mid-draft, which is where the writing time actually hides.</p>""",

"writers/guides/how-to-check-a-freelance-writing-contract": """
<h2>The rights menu, translated</h2>
<p>Because rights language is where contracts hide their weight, the desk's plain-language menu of what the common terms actually buy: <b>first rights</b> — they publish it once, first; it becomes yours to resell afterwards (the freelancer's best default). <b>Exclusive rights, term-limited</b> — theirs alone for the stated period, then yours; priced above first rights, always. <b>All rights</b> — they own everything, forever, including reprints and adaptations; priced at multiples, or declined. <b>Work for hire</b> — you never owned it; you were paid to make a thing for them, ghost-style; legitimate in some contexts, a rip-off in others. <b>Electronic rights</b> — a legacy-print term that now means "the actual publication"; read what it includes (archives? syndication? AI training? — increasingly the clause that matters).</p>
<p>The formal definitions live in the publishing-law references — start from the <a href="https://en.wikipedia.org/wiki/Special:Search?search=publishing+contract" rel="noopener">publishing-contract material on Wikipedia</a> — and the desk's standing boundary applies: general information, not legal advice. The practical rule that survives every jurisdiction: the rights you sell should match the price you quoted, and the <a href="/writers/guides/how-much-to-charge-for-an-article/">pricing guide</a> is where that math starts.</p>""",

"writers/learn/writing-for-publication": """
<h2>The submission portfolio, balanced</h2>
<p>Writers emerging from this section into the market face one structural decision the guides here prepare but rarely name: the portfolio shape. The desk's recommendation is a deliberate two-track — a cash-flow track (the steadier, business-adjacent markets from the <a href="/writers/writing/">opportunity desk</a> that pay reliably and build the ledger) and a trajectory track (the bylines that compound reputation even when they pay modestly), with the mix reviewed quarterly against the <a href="/writers/guides/track-your-writing-income/">realised-hourly ledger</a> and the <a href="/writers/guides/where-the-money-is-in-writing/">money map</a>.</p>
<p>The balance prevents the two classic career failures: the writer chasing prestige into poverty, and the writer chasing invoices into invisibility. Publication is a long game played on two tables at once — the guides above teach the moves; the balance is the strategy; and the free databases (<a href="https://www.pw.org/literary_magazines" rel="noopener">Poets &amp; Writers</a>, <a href="https://thegrinder.diabolicalplots.com/" rel="noopener">The Submission Grinder</a>) keep both tables supplied.</p>""",

"writers/guides/screenplay-format-basics": """
<h2>Format details that read as professionalism</h2>
<p>Beyond the margins, four small conventions separate formatted from professional, and the desk records them here because manuals skip them: scene headings carry the established slugline punctuation exactly (INT./EXT., location, time — no invented variants); character names above dialogue appear in caps the first time and every time (never mixed case "out of laziness"); parentheticals are rare — an actor's direction twice a script is style, twenty times is mistrust; and (CONT'D) after a character's name marks continuing speech across action, spelled exactly, because the production software reads it. Screenwriting apps emit all of this automatically, which is why the <a href="https://fountain.io/" rel="noopener">Fountain-based free editors</a> remain the desk's recommendation for starting — the format is the easy part once software carries it.</p>
<p>The reading discipline from the guide above gets its restatement: produced scripts are the calibration standard, and the <a href="https://en.wikipedia.org/wiki/Special:Search?search=screenplay" rel="noopener">screenplay reference material on Wikipedia</a> maps every term this page uses. When format stops costing attention, the <a href="/writers/guides/where-to-start-with-a-screenplay/">starting guide</a> takes over — story time.</p>""",

"writers/checklists": """
<h2>The desk's own publish checklist, shown in full</h2>
<p>Because a checklist library earns trust by showing its own instrument, here is the desk's pre-publish pass, unabridged: every factual claim carries a source the desk could produce within a minute; every time-sensitive claim carries its checked date; the title's promise is kept by the piece (the <a href="/writers/learn/dos-and-donts/">dos-and-don'ts shelf</a> polices this); the structure passes the reverse-outline read; names, titles and numbers verified against sources, not memory; links checked live; the style sheet applied (the <a href="/writers/learn/grammar-language/">usage resolutions</a>); and the piece read aloud once, start to finish, before the publish button.</p>
<p>That list took this desk years of post-mortems to earn, which is the point of the section: your list starts shorter and grows honestly, one earned line at a time. The <a href="https://en.wikipedia.org/wiki/Special:Search?search=checklist" rel="noopener">checklist evidence base on Wikipedia</a> explains why the aviation standard — short, sequential, actually used — is the one worth copying.</p>""",

"writers/guides/where-to-start-with-a-screenplay": """
<h2>The first ten pages, defined</h2>
<p>Because "write the first ten pages" deserves its own definition, here is what the desk means: ten correctly formatted pages that contain — by page one, the world's ordinary rhythm established in one scene; by page three, the incident that breaks it; by page ten, the decision that makes the story this story and not a mood piece. That shape is not a formula imposed on your idea; it is the pacing contract the format itself implies (one page, one minute), and readers who stop at page ten are usually reporting its absence rather than their taste.</p>
<p>The pages then become your calling card for everything collaboration-shaped: the <a href="/writers/guides/how-to-build-writing-samples/">portfolio rule</a> applies to scripts exactly as to articles, and the craft shelf beside this one — the <a href="/writers/learn/creative-writing/">creative-writing section</a>, the <a href="/writers/guides/screenplay-format-basics/">format basics</a> — carries the rest. The <a href="https://en.wikipedia.org/wiki/Special:Search?search=screenwriting" rel="noopener">screenwriting reference material on Wikipedia</a> names the industry's page-count expectations so your ten land with the right neighbors.</p>""",

"writers/guides/where-the-money-is-in-writing": """
<h2>The tiers, with their honest trade-offs</h2>
<p>The map above earns one more layer: what each tier costs the writer, because every tier bills something. The business-adjacent tier (marketing, content, corporate) pays steadiest and bills voice — the work rewards clarity over personality, and writers who forget which register they are in feel it in revisions. The editorial tier (journalism, features) pays in access and pace, bills time (reported pieces are research-heavy; the <a href="/writers/guides/how-much-to-charge-for-an-article/">pricing guide</a> exists for exactly this tier), and pays reputation on publication. The literary tier pays mostly in standing, bills patience, and — the honest line the desk keeps repeating — remains the tier where the other two fund your presence.</p>
<p>The portfolio strategy that respects the trade-offs is on the <a href="/writers/learn/writing-for-publication/">publication guides</a> (two tracks, reviewed quarterly); the <a href="/writers/state-of-paid-writing-2026/">year survey</a> keeps the numbers current; and the trade context lives with <a href="https://www.pw.org/" rel="noopener">Poets &amp; Writers</a>' reports. The map is a market document, not a ranking of callings.</p>""",

"writers/learn/dos-and-donts/dos-and-donts-of-blogging": """
<h2>The archive rule, and the publishing cadence that works</h2>
<p>The blogging don'ts above save their strongest warning for the abandon-the-archive pattern, so the desk's counter-mechanics belong here: a cadence chosen below your maximum (one post a week beats three-for-a-month), a batching habit (draft two when you are hot, so the cold weeks publish on schedule), and the archive review — once a quarter, update or gracefully date-stamp your oldest still-linked posts, because a blog's credibility lives in its floor, not its ceiling. The <a href="/writers/learn/online-writing/">online-writing section</a> carries the screen craft; this note carries the maintenance discipline that keeps the screen craft visible.</p>
<p>For the monetisation-era boundaries — the same ones this desk runs under — the <a href="/writers/disclosure/">disclosure page</a> is the worked example: ads and affiliate labels stated where they occur, content never for sale. Blogging that respects its readers compounds; blogging that mines them churns, and the readers can tell at any distance.</p>""",

}
